force-app/main/default/objects/Case/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <description>QCC: Used to track/store the arrival airport for a case</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Airport</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OwnerName__c.field-meta.xml
<CustomField>
    <fullName>OwnerName__c</fullName>
    <description>QCC: Backend field For SLA Calculation</description>
    <formula>if(LEFT(OwnerId, 3)=&apos;005&apos;, Owner:User.Username,  Owner:Queue.DeveloperName)</formula>
    <label>Owner Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/QCC_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>QCC_Departure_Date__c</fullName>
    <description>Value comes from the Pre-Departure Platform event. This is used as a reference for the agent when they are working on a &quot;Review Complimentary Upgrade&quot; case.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/QCC_Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>QCC_Flight_Number__c</fullName>
    <description>This field captures the flight number without the carrier code for Qantas Flights.</description>
    <formula>VALUE(TRIM(IF (TEXT(Airline__c) =&apos;Qantas&apos;,SUBSTITUTE(SUBSTITUTE(UPPER(Flight_Number__c),&quot;QF&quot;,&quot;&quot;),&quot;A&quot;,&quot;&quot;),&apos;&apos;)))</formula>
    <label>QCC_Flight_Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual/fields/QCC_Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>QCC_Frequent_Flyer_Number__c</fullName>
    <description>Populated automatically with Frequent Flyer Number of the contact record that triggered the creation of Individual record</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Arrival_Port__c.field-meta.xml
<CustomField>
    <fullName>QCC_Arrival_Port__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Port</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Cabin_Class__c.field-meta.xml
<CustomField>
    <fullName>QCC_Cabin_Class__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cabin Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>QCC_Contact_Method__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Crew_CSAT_Score__c.field-meta.xml
<CustomField>
    <fullName>QCC_Crew_CSAT_Score__c</fullName>
    <label>Crew CSAT Score</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Customer_Service_Feedback__c.field-meta.xml
<CustomField>
    <fullName>QCC_Customer_Service_Feedback__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Service Feedback</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Delay_CSAT_Score__c.field-meta.xml
<CustomField>
    <fullName>QCC_Delay_CSAT_Score__c</fullName>
    <label>Delay CSAT Score</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>QCC_Departure_Airport__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Airport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>QCC_Departure_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>QCC_Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Post_Flight_Score__c.field-meta.xml
<CustomField>
    <fullName>QCC_Post_Flight_Score__c</fullName>
    <label>Post-Flight Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/QCC_Survey_Type__c.field-meta.xml
<CustomField>
    <fullName>QCC_Survey_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Survey Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response__c</fullName>
    <label>Survey Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Survey completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_SurveyResponseTriggerHelperTest.cls
/*********************************************************************************
Name         : QCC_SurveyResponseTriggerHelperTest
Created By   : Rafael Escuadra
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 12 December 2019
Usages       : This class is used for the code coverage of the apex class below:
- QCC_SurveyResponseTriggerHelper

Modified By : Venkata Suresh Kumar (TCS Team), 19-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method.
*********************************************************************************/
@isTest
public class QCC_SurveyResponseTriggerHelperTest{
    @testSetUp
    public static void setupTestData(){
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        List<Trigger_Status__c> customSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusSurveyResponse', null, null, null, null);
        insert customSettingList;
        List<Trigger_Status__c> caseCustomSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusCase', null, null, null, null);
        insert caseCustomSettingList;
        
        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        List<Contact> contactList = new List<Contact>();
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.RecordTypeId = contactRecordTypeId;
        contactRecord.Frequent_Flyer_Number__c = '1234567890';
        contactRecord.Frequent_Flyer_Tier__c = 'Platinum One';
        insert contactRecord;
    }
    
    static testmethod void createCaseFromSurveyResponseTest(){
        test.startTest();
        Id objectRecordTypeId = Schema.SObjectType.CASE.getRecordTypeInfosByDeveloperName().get('CCC_Complaints').getRecordTypeId();
        Survey_Response__c SurveyResponseRecord = new Survey_Response__c();
        SurveyResponseRecord.QCC_Arrival_Port__c = 'Sydney';
        SurveyResponseRecord.QCC_Departure_Airport__c = 'Singapore';
        SurveyResponseRecord.QCC_Cabin_Class__c = 'J';
        SurveyResponseRecord.QCC_Contact_Method__c = 'Email';
        SurveyResponseRecord.QCC_Flight_Number__c = '0003';
        Date departureDate = Date.today() + 3;
        SurveyResponseRecord.QCC_Departure_Date__c = departureDate;
        SurveyResponseRecord.QCC_Frequent_Flyer_Number__c =  '1234567890';
        SurveyResponseRecord.QCC_Survey_Type__c = 'Qantas INT Ops CX Survey';
        SurveyResponseRecord.QCC_Crew_CSAT_Score__c = 1;
        SurveyResponseRecord.QCC_Customer_Service_Feedback__c = 'testing createCaseFromSurveyResponseTest ';
        SurveyResponseRecord.QCC_Post_Flight_Score__c= 5;
        SurveyResponseRecord.QCC_Delay_CSAT_Score__c = 5;
        
        insert SurveyResponseRecord;
        test.stopTest();
        
        //check if Case record was created
        Case caseRecord = [SELECT 
                           Arrival_Airport__c,
                           Frequent_Flyer_Number__c, 
                           recordType.DeveloperName,
                           Subject,
                           OwnerName__c
                           FROM Case LIMIT 1];
        
        System.assertEquals('Sydney',caseRecord.Arrival_Airport__c ,  'Arrival_Airport__c should be same with survey response record');
        System.assertEquals('1234567890', caseRecord.Frequent_Flyer_Number__c, 'Frequent_Flyer_Number__c should be same with survey response record');
        System.assertEquals('CCC_Complaints', caseRecord.RecordType.DeveloperName, 'Record Type should be CCC_Complaints');
        //System.assertEquals('QANTAS_VIP_Post_Travel_Queue', caseRecord.OwnerName__c, 'Case record should belong to QANTAS_VIP_Post_Travel_Queue');
    }
}