force-app/main/default/objects/Case/fields/Assign_using_active_assignment_rules__c.field-meta.xml
<CustomField>
    <fullName>Assign_using_active_assignment_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether to assign cases using active assignment rules</description>
    <inlineHelpText>CCC: Tick this box to use queue allocation</inlineHelpText>
    <label>Assign using active assignment rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Booking_PNR__c.field-meta.xml
<CustomField>
    <fullName>Booking_PNR__c</fullName>
    <description>QCC: Created to show/store Booking Reference # (PNR).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PNR</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cabin_Class__c.field-meta.xml
<CustomField>
    <fullName>Cabin_Class__c</fullName>
    <description>QCC: Created to show/store Customer Cabin Class.</description>
    <inlineHelpText>CCC: Required for queuing prioritisation</inlineHelpText>
    <label>Cabin Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBC</fullName>
            </value>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Departure_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time__c</fullName>
    <description>QCC: Created to show/store Departure Date/Time of flight for which this Case is raised.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>CCC: Format DD/MM/YYYY HH:MM:SS</inlineHelpText>
    <label>Departure Date/Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/FF_Tier__c.field-meta.xml
<CustomField>
    <fullName>FF_Tier__c</fullName>
    <description>QCC: Frequent Flyer Number of customer copied to case on case creation for back-end usage;reporting.</description>
    <label>Frequent Flyer Tier on Case Creation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#2F5D85</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#CC0000</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#666666</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#AFCADF</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
                <color>#000000</color>
                <label>Chairmans Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairmans Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>QCC: Created to show/store Customer Flight Number for which this Case is raised.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Flight_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Flight_Type_Code__c</fullName>
    <description>Flight Type Code</description>
    <label>Flight Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Passenger_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Passenger_First_Name__c</fullName>
    <description>This is added for Insurance letter</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Passenger First Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Passenger_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Last_Name__c</fullName>
    <description>This is Added for Insurance Letters</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Passenger Last Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Passenger_Segment_Id__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Segment_Id__c</fullName>
    <description>Passenger Segment Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Passenger Segment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/QCC_Action_Items__c.field-meta.xml
<CustomField>
    <fullName>QCC_Action_Items__c</fullName>
    <description>Automatically populated. This is used as a note to the agent on things to do while working on the case.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Action Items</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QCC_Contact_Watchlist__c/QCC_Contact_Watchlist__c.object-meta.xml
<CustomObject>
    <label>Watchlist</label>
    <nameField>
        <displayFormat>CWL-{0000}</displayFormat>
        <label>Contact Watchlist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Watchlists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QCC_Contact_Watchlist__c/fields/QCC_Watchlist_End_Date__c.field-meta.xml
<CustomField>
    <fullName>QCC_Watchlist_End_Date__c</fullName>
    <description>Date until when the watchlist is considered</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Watchlist End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QCC_Contact_Watchlist__c/fields/QCC_Watchlist_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>QCC_Watchlist_Start_Date__c</fullName>
    <description>Date on when to start considering the watchlist</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Watchlist Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_setCaseFieldsInvocableTest.cls
/*********************************************************************************
Name         : QCC_setCaseFieldsInvocableTest
Created By   : Rafael Escuadra
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 28 August 2019
Usages       : This will handle the test class and code coverage of 
QCC_setCaseFieldsInvocable APEX class

Modified By : Venkata Suresh Kumar (TCS Team), 19-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method.  Added Test.start and Test.Stop methods 
*********************************************************************************/
@isTest
public class QCC_setCaseFieldsInvocableTest {
    @testSetup
    static void setupTestData(){
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.Frequent_Flyer_Number__c = '1234567890';
        contactRecord.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord.RecordTypeId = contactRecordTypeId;
        insert contactRecord;
        
        //Create test data for Contact object to be used as contact in watchlist
        Contact contactRecord1 = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord1.LastName = 'TestWatchlist';
        contactRecord1.Frequent_Flyer_Number__c = '1234567891';
        contactRecord1.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord1.RecordTypeId = contactRecordTypeId;
        insert contactRecord1;
        
        //Create test data for Watchlist
        QCC_Contact_Watchlist__c watchlistRecord = QCC_TestDataFactory.createWatchlistTestData(1, contactRecord1.id);
        watchlistRecord.QCC_Watchlist_Start_Date__c = Date.today() - 1;
        watchlistRecord.QCC_Watchlist_End_Date__c = Date.today() + 1;
        insert watchlistRecord;
        
        //Create custom setting for case trigger
        List<Trigger_Status__c> customSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusCase', null, null, null, null);
        insert customSettingList;
        
        List<Case> caseRecords = new List<Case>();
        String caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('QCC_Elite_Process').getRecordTypeId();
        
        Case caseRecord = QCC_TestDataFactory.createCaseTestData(accountRecord.Id, contactRecord.Id);
        caseRecord.RecordTypeId = caseRecordTypeId;
        caseRecord.Subject = 'Test Qantas Host';
        caseRecord.Status = 'New';
        caseRecord.Origin = 'BluePrism';
        caseRecord.Subject =  'PNR Health Check';
        caseRecord.Type = 'PNR Health Check';
        caseRecord.Passenger_First_Name__c = 'Test FirstName';
        caseRecord.Passenger_Last_Name__c = 'Test LastName';
        caseRecord.Booking_PNR__c = '123456';
        caseRecord.Departure_Date_Time__c = '21/12/2020 00:00:00';
        caseRecord.Flight_Number__c = 'QF0001';
        caseRecord.Passenger_Segment_Id__c = 'SFO-JFK';
        caseRecord.Flight_Type_Code__c = 'Domestic';
        caseRecord.Cabin_Class__c = 'Domestic';
        caseRecord.Frequent_Flyer_Number__c = '1234567890';
        caseRecord.FF_Tier__c = 'Platinum One';
        caseRecord.Description = 'The contact attach no this case has no watchlist.';
        caseRecord.Assign_using_active_assignment_rules__c = true;
        // caseRecords.add(caseRecord);
        
        Case caseRecord1 = QCC_TestDataFactory.createCaseTestData(accountRecord.Id, contactRecord1.Id);
        caseRecord1.RecordTypeId = caseRecordTypeId;
        caseRecord1.Status = 'New';
        caseRecord1.Origin = 'BluePrism';
        caseRecord1.Subject =  'PNR Health Check';
        caseRecord1.Type = 'PNR Health Check';
        caseRecord1.Passenger_First_Name__c = 'Test FirstName';
        caseRecord1.Passenger_Last_Name__c = 'Test LastName';
        caseRecord1.Booking_PNR__c = '123456';
        caseRecord1.Departure_Date_Time__c = '21/12/2020 00:00:00';
        caseRecord1.Flight_Number__c = 'QF0001';
        caseRecord1.Passenger_Segment_Id__c = 'SFO-JFK';
        caseRecord1.Flight_Type_Code__c = 'Domestic';
        caseRecord1.Cabin_Class__c = 'Domestic';
        caseRecord1.Frequent_Flyer_Number__c = '1234567890';
        caseRecord1.FF_Tier__c = 'Platinum One';
        caseRecord1.Description = 'The contact attached has record on watchlist.';
        caseRecord1.Assign_using_active_assignment_rules__c = true;
        caseRecords.add(caseRecord1);
        
        insert caseRecords;      
    }
    
    public static testMethod void updateFieldsTest(){ 
        Test.startTest();
        // List<Case> caseRecord1 = new List<Case>([SELECT id ,Subject, Type, Due_Date__c, Priority,QCC_Action_Items__c FROM Case = 'PNR Health Check']);
        for(Case caseRec : [SELECT id ,Subject, Type, Due_Date__c, Priority,QCC_Action_Items__c FROM Case WHERE Type = 'PNR Health Check']){
            System.debug('caseRec.Due_Date__c'+caseRec.Due_Date__c);
            System.debug('caseRec.Priority'+caseRec.Priority);
            System.debug('caseRec.QCC_Action_Items__c'+caseRec.QCC_Action_Items__c);
            System.assertEquals(caseRec.Due_Date__c, null, 'Due_date__c must be set');
            System.assertEquals(caseRec.Priority , 'Medium','Priority must be set to High');
            System.assertNotEquals(caseRec.QCC_Action_Items__c, '', 'QCC_Action_Items__c must be set');
        }
        Test.stopTest();
    }
    
    //WHERE  QCC_Watchlist_Start_Date__c <= TODAY AND QCC_Watchlist_End_Date__c >= TODAY
    public static testMethod void updateFieldsTestOnWatchList(){ 
        Test.startTest();
        for(Case caseRec : [SELECT id ,Subject, Type, Due_Date__c, Priority,QCC_Action_Items__c FROM Case WHERE Type = 'PNR Health Check - Watchlist']){
            System.assertNotEquals(caseRec.Due_Date__c, null, 'Due_date__c must be set');
            System.assertNotEquals(caseRec.Priority , 'Medium','Priority must be set to High');
            System.assertNotEquals(caseRec.QCC_Action_Items__c, '', 'QCC_Action_Items__c must be set');
        }
        Test.stopTest();
    }
}