force-app/main/default/objects/Case/fields/Baggage_Assessment_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Baggage_Assessment_Outcome__c</fullName>
    <description>Added for Insurance Letters in &apos;QCC Insurance Letter Layout&apos;  Case  Page Layout</description>
    <label>Baggage Assessment Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Emergency Expenses</fullName>
            </value>
            <value>
                <fullName>Financial Settlement</fullName>
            </value>
            <value>
                <fullName>Incomplete Claim Form</fullName>
            </value>
            <value>
                <fullName>Out of Timeframe</fullName>
            </value>
            <value>
                <fullName>QF not Liable</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resolution_Method__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Method__c</fullName>
    <description>QCC: Used to store/track the case resolution method</description>
    <inlineHelpText>CCC:Method of resolution at case closure</inlineHelpText>
    <label>Resolution Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Webchat</fullName>
            </value>
            <value>
                <fullName>Referred to another department</fullName>
            </value>
            <value>
                <fullName>Letter</fullName>
            </value>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Case auto closed</fullName>
            </value>
            <value>
                <fullName>Bulk Closure</fullName>
            </value>
            <value>
                <fullName>No action required</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Nat Memo</fullName>
            </value>
            <value>
                <fullName>Technical action required</fullName>
            </value>
            <value>
                <fullName>Referred to other area</fullName>
            </value>
            <value>
                <fullName>Other Airline</fullName>
            </value>
            <value>
                <fullName>Auto Closed - Sensitive Case</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>PNR Investigation</fullName>
            </value>
            <value>
                <fullName>Nil Action - Thank You</fullName>
            </value>
            <value>
                <fullName>Nil Action - Email Auto Reply</fullName>
            </value>
            <value>
                <fullName>Nil Action - Duplicate</fullName>
            </value>
            <value>
                <fullName>Nil Action - Internal Reply</fullName>
            </value>
            <value>
                <fullName>Nil Action - Customer Behaviour</fullName>
            </value>
            <value>
                <fullName>Auto Closed - Recovery</fullName>
            </value>
            <value>
                <fullName>Contact Only</fullName>
                <isActive>false</isActive>
                <label>Contact Only</label>
            </value>
            <value>
                <fullName>Duplicate</fullName>
                <isActive>false</isActive>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>Goodwill</fullName>
                <isActive>false</isActive>
                <label>Goodwill</label>
            </value>
            <value>
                <fullName>Nil Action</fullName>
                <isActive>false</isActive>
                <label>Nil Action</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_StartWorkResolveCaseControllerTest.cls
/*********************************************************************************
Name         : QCC_StartWorkResolveCaseControllerTest
Created By   : Lora Mae S. Dapulang
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 12 March 2020
Usages       : This class is used for the code coverage of the apex class below:
- QCC_StartWorkAndResolveCaseController

Modified By : Venkata Suresh Kumar (TCS Team), 19-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method.
*********************************************************************************/
@isTest
public class QCC_StartWorkResolveCaseControllerTest {    
    
    @testSetup
    static void setupTestData(){
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        List<Trigger_Status__c> caseCustomSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusCase', null, null, null, null);
        insert caseCustomSettingList;
        
        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.RecordTypeId = contactRecordTypeId;
        contactRecord.Frequent_Flyer_Number__c = '1234567891';
        insert contactRecord;
        
        //Create test data for Case object
        String caseEliteRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('QCC Elite Process').getRecordTypeId();
        String caseBaggageTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CCC Baggage').getRecordTypeId();
        List<Case> caseList = new List<Case>();        
        Case caseRec1 =  QCC_TestDataFactory.createCaseTestData(accountRecord.Id, contactRecord.Id);
        caseRec1.RecordTypeId = caseEliteRecordTypeId;
        caseList.add(caseRec1);
        
        Case caseRec2 =  QCC_TestDataFactory.createCaseTestData(accountRecord.Id, contactRecord.Id);
        caseRec2.RecordTypeId = caseEliteRecordTypeId;
        caseRec2.Status = 'Closed';
        caseRec2.Resolution_Method__c = 'Email';
        caseList.add(caseRec2);
        
        Case caseRec3 =  QCC_TestDataFactory.createCaseTestData(accountRecord.Id, contactRecord.Id);
        caseRec3.RecordTypeId = caseEliteRecordTypeId;
        caseRec3.Status = 'In Progress';
        caseList.add(caseRec3);
        
        Case caseRec4 =  QCC_TestDataFactory.createCaseTestData(accountRecord.Id, contactRecord.Id);
        caseRec4.RecordTypeId = caseBaggageTypeId;
        caseRec4.Status = 'New';
        caseList.add(caseRec4);
        insert caseList;
        
        //Set Custom Settings for Trigger_Status__c Custom settings
        List<Trigger_Status__c> customSettingTriggerStatusLists = QCC_TestDataFactory.createTriggerStatusData();
        insert customSettingTriggerStatusLists;
    }
    
    static TestMethod void testchangeNewCaseRecordStatus(){        
        Case caseRec = [SELECT Id, Status FROM Case WHERE Status = 'New' LIMIT 1];
        Test.startTest();
        QCC_StartWorkAndResolveCaseController.changeCaseRecordStatus(caseRec.Id);
        Test.stopTest();        
    }   
    
    static TestMethod void testchangeInProgressCaseRecordStatus(){        
        Case caseRec = [SELECT Id, Status, Resolution_Method__c FROM Case WHERE Status = 'In progress' AND Resolution_Method__c = NULL LIMIT 1];
        caseRec.Resolution_Method__c = 'Email';
        update caseRec;
        Test.startTest();
        QCC_StartWorkAndResolveCaseController.changeCaseRecordStatus(caseRec.Id);
        Test.stopTest();        
    }
    
    static TestMethod void testchangeCaseException(){       
        Case caseRec = [SELECT Id, Status FROM Case WHERE Status = 'In progress' AND Resolution_Method__c = NULL LIMIT 1];
        caseRec.ContactId = null;
        update caseRec;
        Test.startTest();
        QCC_StartWorkAndResolveCaseController.changeCaseRecordStatus(caseRec.Id);
        Test.stopTest();        
    }
    
    static TestMethod void testchangeCaseException1(){    
        Test.startTest();
        String caseBaggageTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CCC Baggage').getRecordTypeId();
        Case caseRec = [SELECT Id, Status FROM Case WHERE Status = 'New' AND RecordTypeId = :caseBaggageTypeId LIMIT 1];
        caseRec.Status ='closed';
        caseRec.Resolution_Method__c ='';
        caseRec.Baggage_Assessment_Outcome__c ='';
        update caseRec;
        QCC_StartWorkAndResolveCaseController.changeCaseRecordStatus(caseRec.Id);
        Test.stopTest();        
    }
}