force-app/main/default/objects/Case/fields/Cabin_Class__c.field-meta.xml
<CustomField>
    <fullName>Cabin_Class__c</fullName>
    <description>QCC: Created to show/store Customer Cabin Class.</description>
    <inlineHelpText>CCC: Required for queuing prioritisation</inlineHelpText>
    <label>Cabin Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBC</fullName>
            </value>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>IF( ISBLANK( ParentId ) ,  CaseNumber ,  Parent.CaseNumber )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CAP_ID__c.field-meta.xml
<CustomField>
    <fullName>CAP_ID__c</fullName>
    <description>Contact CAP ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>QCC: Created to show/store Total amount provided to customer.</description>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/API_Attempts__c.field-meta.xml
<CustomField>
    <fullName>API_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>QCC: Identifies the number of failed attempts made to call the Loyalty API</description>
    <label>API Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Cabin_class__c.field-meta.xml
<CustomField>
    <fullName>Cabin_class__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Cabin class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>QCC: Created to show/store Contact associated with the recovery.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>QCC: Used to store the email of the contact for QF Wine/Hotel vouchers</description>
    <formula>Case_Number__r.Contact_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <description>QCC: Used to store the first name of the contact for EFT/Credit card refunds</description>
    <formula>Case_Number__r.First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact_LastName__c.field-meta.xml
<CustomField>
    <fullName>Contact_LastName__c</fullName>
    <description>QCC Loyalty API</description>
    <formula>Case_Number__r.Last_Name__c</formula>
    <label>Contact LastName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/FF_Number__c.field-meta.xml
<CustomField>
    <fullName>FF_Number__c</fullName>
    <description>QCC Frequent Flyer</description>
    <formula>Case_Number__r.Contact.Frequent_Flyer_Number__c</formula>
    <label>FF Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/LoungePassErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>LoungePassErrorMessage__c</fullName>
    <description>QCC: Error messages from OPLA API if it returns an error</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Lounge Pass Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/LoungePassReference__c.field-meta.xml
<CustomField>
    <fullName>LoungePassReference__c</fullName>
    <description>QCC: The reference number or text from OPLA after calling the API to generate Lounge Pass</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Lounge Pass Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/LoungePassRequestTime__c.field-meta.xml
<CustomField>
    <fullName>LoungePassRequestTime__c</fullName>
    <description>QCC: The time when Lounge Pass is requested by calling the OPLA API</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Lounge Pass Request Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Process_Status__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Payment Details Received</fullName>
            </value>
            <value>
                <fullName>Queued for Payment Processing</fullName>
            </value>
            <value>
                <fullName>Submitted to Finance</fullName>
            </value>
            <value>
                <fullName>Findel Approved</fullName>
            </value>
            <value>
                <fullName>Payment Ready</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Finalised</fullName>
            </value>
            <value>
                <fullName>Submitted for Voucher Issuance</fullName>
            </value>
            <value>
                <fullName>Voucher Created</fullName>
            </value>
            <value>
                <fullName>Voucher Sent</fullName>
            </value>
            <value>
                <fullName>Submitted for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Action Required</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Linked</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Recovery_System_log__c.field-meta.xml
<CustomField>
    <fullName>Recovery_System_log__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Recovery System log</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: The status of the recovery</description>
    <label>Recovery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Further Action Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replaced Recovery</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submit for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalisation Declined</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>QCC: Created to show/store Type of goodwill given to customer.</description>
    <label>Recovery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qantas Points</fullName>
            </value>
            <value>
                <fullName>Payment (EFT)</fullName>
            </value>
            <value>
                <fullName>Payment (Credit Card)</fullName>
            </value>
            <value>
                <fullName>Travel vouchers</fullName>
                <label>Travel Vouchers</label>
            </value>
            <value>
                <fullName>Lounge Passes</fullName>
            </value>
            <value>
                <fullName>Bag Replacement</fullName>
            </value>
            <value>
                <fullName>Bag Repair</fullName>
            </value>
            <value>
                <fullName>No Goodwill</fullName>
            </value>
            <value>
                <fullName>Ticket Refund EFT</fullName>
            </value>
            <value>
                <fullName>Cover Refund</fullName>
            </value>
            <value>
                <fullName>First Lounge Pass</fullName>
                <label>First Lounge Pass (CCAT Only)</label>
            </value>
            <value>
                <fullName>Space available upgrade</fullName>
                <label>Space Available Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>Firm space upgrade</fullName>
                <label>Firm Space Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>QF_HOTEL_voucher</fullName>
            </value>
            <value>
                <fullName>QF_WINE_voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/recordTypes/Customer_Connect.recordType-meta.xml
<RecordType>
    <fullName>Customer_Connect</fullName>
    <active>true</active>
    <label>Customer Connect</label>
</RecordType>

force-app/main/default/objects/Recovery__c/recordTypes/Other_Recovery.recordType-meta.xml
<RecordType>
    <fullName>Other_Recovery</fullName>
    <active>true</active>
    <label>Other Recovery</label>
</RecordType>

force-app/main/default/classes/QCC_RecoveriesCallOPLAAPIBatchable.cls
/*-----------------------------------------------------------------------------------------
    Author: Nga Do
    Company: Capgemini
    Description: 
    Inputs: 
    Test Class: QCC_RecoveriesCallOPLAAPIBatchableTest
    ***************************************************************************************
    History:
    ***************************************************************************************
    22-June-2018
    ***************************************************************************************
    13-Oct-2021    
    JIRA : CRM-5003 | Member API V2 Changes | Introduced differnt callouts and modified wrapper references 
 ------------------------------------------------------------------------------------------*/
global class QCC_RecoveriesCallOPLAAPIBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts {

    
    global QCC_RecoveriesCallOPLAAPIBatchable() { 
        
    }
    /*--------------------------------------------------------------------------------------       
    Method Name:        start
    Description:        get all LP recovery has Declined status, and Attempts call API less than 3 times
    Parameter:          
    --------------------------------------------------------------------------------------*/ 
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        return Database.getQueryLocator([SELECT Id, 
                                            Amount__c, 
                                            FF_Number__c, 
                                            Name, 
                                            Status__c, 
                                            Case_Number__c,
                                            Case_Number__r.Contact.CAP_ID__c,
                                            Contact__r.Salutation,
                                            Contact__r.Frequent_Flyer_Number__c, 
                                            Contact_First_Name__c,
                                            Contact_LastName__c,
                                            Case_Number__r.Contact_Email__c,
                                            LoungePassRequestTime__c,
                                            LoungePassReference__c,
                                            LoungePassErrorMessage__c,
                                            Recovery_System_log__c,
                                            Type__c,
                                            API_Attempts__c 
                                         FROM Recovery__c 
                                         WHERE Type__c =: CustomSettingsUtilities.getConfigDataMap('RecoveryTypeLoungePasses')
                                         AND Status__c = :CustomSettingsUtilities.getConfigDataMap('RecoveryStatusApproved')
                                         AND API_Attempts__c < 3 AND (RecordType.DeveloperName='Customer_Connect' OR RecordType.DeveloperName='Other_Recovery')]);

    }
    /*--------------------------------------------------------------------------------------       
    Method Name:        execute
    Description:        retry to call to OLAP and update status of recovery, api call attempts
    Parameter:          List Recoveries
    --------------------------------------------------------------------------------------*/ 
    global void execute(Database.BatchableContext BC, List<Recovery__c> recoveries) {
        
        System.debug('######recoveries#####' + recoveries);
        QCC_OPLALoungePassWrapper.Response oplaResp;
        Set<Id> caseIds = new Set<Id>();
        Map<String, Id> mapQueue = new Map<String, Id>();
        Map<Id, String> mapRecoveryErrors = new Map<Id, String>();
        List<Recovery__c> errorRecoveries = new List<Recovery__c>();

        String searchFFNumber = '';
        String firstName = '';
        String lastName = '';

        for(Recovery__c objRecovery : recoveries){
            searchFFNumber = '';
            /* Commented by Purushotham - QDCUSCON-5003 -- START -- Function not needed because there is no Contact for Non FF as part of Remediation
            if(objRecovery.FF_Number__c == null){
                Contact contactSearch = new Contact();
                system.debug('#####QCC_RecoveriesCallOPLAAPIBatchable contactSearch.CAP_ID__c=' + objRecovery.Case_Number__r.Contact.CAP_ID__c);
                contactSearch.CAP_ID__c = objRecovery.Case_Number__r.Contact.CAP_ID__c;
                system.debug('#####QCC_RecoveriesCallOPLAAPIBatchable contactSearch.CAP_ID__c=' + contactSearch.CAP_ID__c);
                if( GenericUtils.checkBlankorNull(contactSearch.CAP_ID__c)){
                    QCC_CustomerSearchHandler.ContactWrapper contactResult = QCC_CustomerSearchHandler.searchCustomer(contactSearch, '');
                    if(contactResult != null && GenericUtils.checkBlankorNull(contactResult.contacts[0].Frequent_Flyer_Number__c)){
                        system.debug('#####QCC_RecoveriesCallOPLAAPIBatchable QCC_RecoveriesCallOPLAAPIQueueable$$$$$$$$=' + GenericUtils.checkBlankorNull(contactResult.contacts[0].Frequent_Flyer_Number__c));
                        searchFFNumber = contactResult.contacts[0].Frequent_Flyer_Number__c; 
                    } 
                }
            }
			QDCUSCON-5003 -- END*/
            Boolean isSuccess = false;
            String additionalComment;
            String comments;
            // check if Frequent Flyer Number is Exist , make a callout
            if(objRecovery.FF_Number__c != null || GenericUtils.checkBlankorNull(searchFFNumber)){

                searchFFNumber = GenericUtils.checkBlankorNull(searchFFNumber) ? searchFFNumber : objRecovery.FF_Number__c;
                //Added for Deployement
				QCC_LoyaltyResponseWrapper.QantasFrequentFlyerProfile loyaltyRes;
                try{
                    // Introduced new Member API V2 url - CRM 5003
                    //loyaltyRes = QCC_InvokeCAPAPI.invokeLoyaltyAPI(searchFFNumber);
                    loyaltyRes = QCC_InvokeCAPAPI.invokeLoyaltyProfileAPI(searchFFNumber);  
                }catch(Exception ex){
                    system.debug('ex####'+ex);
                }
                    firstName = objRecovery.Contact_First_Name__c;
                lastName = objRecovery.Contact_LastName__c;
                /* Commented by Purushotham on 09 Aug 2018 as requested by Niket
                if(loyaltyRes != null && firstName.equalsIgnoreCase(loyaltyRes.firstName) && lastName.equalsIgnoreCase(loyaltyRes.lastName)){
                */   
                if(loyaltyRes != null && lastName.equalsIgnoreCase(loyaltyRes.lastName)){
                    system.debug('QCC_RecoveriesCallOPLAAPIBatchable');

                    // init Loyalty Request
                    QCC_OPLALoungePassWrapper.Request oplaReq = initOPLARequest(objRecovery);
                    // call out
                    oplaResp = QCC_InvokeOPLAAPI.invokeLoungePassPostAPI(oplaReq);
                    isSuccess = oplaResp.isSuccess;
                }else{
                    additionalComment = ' Customer\'s frequent flyer details are not valid';
                }
            }else{

                additionalComment = ' No Frequent Flyer contact available, add Frequent Flyer contact and then resubmit recovery';
                objRecovery.LoungePassErrorMessage__c =' No Frequent Flyer contact available, add Frequent Flyer contact and then resubmit recovery';
            }
            System.debug('######additionalComment#####' + additionalComment);
            System.debug('######isSuccess#####' + isSuccess);
            System.debug('######oplaResp#####' + oplaResp);
            if(isSuccess){
                // if callout is succeed update recovery as follow:
                objRecovery.Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryStatusFinalised');
                objRecovery.LoungePassRequestTime__c = System.now();
                objRecovery.LoungePassReference__c = oplaResp.referenceNo;
               	objRecovery.LoungePassErrorMessage__c ='';
                objRecovery.Recovery_System_log__c = objRecovery.Recovery_System_log__c == null ? '':objRecovery.Recovery_System_log__c ;
                objRecovery.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000) + 'OPLA API SUCCESS' + '</li></ul>' + objRecovery.Recovery_System_log__c;
            }else{
                // if callout is failed update recovery as follow:
                //Commented by Navya for CDP2-348 changes
                //objRecovery.Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusException');
                objRecovery.LoungePassRequestTime__c = System.now();
                if(oplaResp != null){
                    objRecovery.LoungePassErrorMessage__c = oplaResp.errorMessage;

                }else{
                    objRecovery.LoungePassErrorMessage__c = additionalComment;
                }
                objRecovery.API_Attempts__c = objRecovery.API_Attempts__c == null? 1: objRecovery.API_Attempts__c + 1;
                comments = additionalComment == null ? 'OPLA API call unsuccessful Attempt #'+ Integer.valueOf(objRecovery.API_Attempts__c) : 'OPLA API call unsuccessful Attempt #'+ Integer.valueOf(objRecovery.API_Attempts__c) + '\n' + additionalComment;
                if(objRecovery.API_Attempts__c >= 3){
                    //CDP2-348 changes by Navya
                    objRecovery.Recovery_System_log__c = objRecovery.Recovery_System_log__c == null ? '':objRecovery.Recovery_System_log__c ;
                    objRecovery.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000) + ' Processing failed, please resubmit recovery' + '</li></ul>' + objRecovery.Recovery_System_log__c;
                    objRecovery.Process_Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusException');
                    caseIds.add(objRecovery.Case_Number__c);
                }
                errorRecoveries.add(objRecovery);
                mapRecoveryErrors.put(objRecovery.Id, comments);
            }
        }
        Database.update(recoveries,false);
        System.debug('######caseIds#####' + caseIds);
        List<Case> casesToUpdate = new List<Case>();
        for(QueueSobject  queueObj: [Select SobjectType, Id, QueueId, Queue.DeveloperName from QueueSobject where 
                                     SobjectType ='Case']){
                mapQueue.put(queueObj.Queue.DeveloperName, queueObj.QueueId);
        }

        // After 3 times failed, update status of Case and bounce back to queue
        if(caseIds != null && caseIds.size() > 0) {
            for(Case cs: [SELECT Id, Status, Cabin_Class__c, Frequent_Flyer_Tier__c FROM Case WHERE Id IN :caseIds]) {
                //CDP2-348 changes by Navya
                //cs.Status = CustomSettingsUtilities.getConfigDataMap('RecoveryError');
                //String queueName = 'Fulfillment_Queue';
                //cs.OwnerId = mapQueue.get(queueName);
                cs.OwnerId = UserInfo.getUserId(); 
                casesToUpdate.add(cs);
            }
        }
        System.debug('######casesToUpdate#####' + casesToUpdate);
        if(!casesToUpdate.isEmpty()){
            update casesToUpdate;
        }
        for(Recovery__c errObject : errorRecoveries){
            if(mapRecoveryErrors.containsKey(errObject.Id)){
                if(!Test.isRunningTest()) {
                    System.debug('errObject.Case_Number__c:::'+errObject.Case_Number__c);
                    System.debug('ConnectApi.FeedElementType.FeedItem:::'+ConnectApi.FeedElementType.FeedItem);
                    System.debug('mapRecoveryErrors.get(errObject.Id):::'+mapRecoveryErrors.get(errObject.Id));
                    //ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(null, rec.Case_Number__c, ConnectApi.FeedElementType.FeedItem, comments);
                    ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(null, errObject.Case_Number__c, ConnectApi.FeedElementType.FeedItem, mapRecoveryErrors.get(errObject.Id));
                    //ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(null, objRecovery.Case_Number__c, ConnectApi.FeedElementType.FeedItem, comments);
                }   
            }
        }
    }
    
    global void finish(Database.BatchableContext BC) {

    }
    
    /*--------------------------------------------------------------------------------------       
    Method Name:        initRoyaltyRequest
    Description:        initiate royal request
    Parameter:          Frequent flyer Number, Point of Recovery , LastName of contact, affected Passenger Name
    --------------------------------------------------------------------------------------*/ 
    private static QCC_OPLALoungePassWrapper.Request initOPLARequest(Recovery__c recovery){

        QCC_OPLALoungePassWrapper.Request oplaReq = new QCC_OPLALoungePassWrapper.Request();
        
        oplaReq.reference_no = recovery.Name;
        oplaReq.frequent_flyer_no = recovery.FF_Number__c;
        oplaReq.expiry_period = CustomSettingsUtilities.getConfigDataMap('QCC OPLA API Expiry Period');
        oplaReq.title = recovery.contact__r.Salutation;
        oplaReq.first_name = recovery.Contact_First_Name__c;
        oplaReq.last_name = recovery.Contact_LastName__c;
        oplaReq.email = recovery.Case_Number__r.Contact_Email__c;
        oplaReq.issuer_code = CustomSettingsUtilities.getConfigDataMap('QCC OPLA API Issuer Code');
        oplaReq.pass_type = CustomSettingsUtilities.getConfigDataMap(recovery.Type__c);
        oplaReq.no_of_pass = String.valueOf(recovery.Amount__c);

        return oplaReq;
    }
}