force-app/main/default/objects/Case/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>IF( ISBLANK( ParentId ) ,  CaseNumber ,  Parent.CaseNumber )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>QCC: Created to show/store Total amount provided to customer.</description>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/ApprovedBy__c.field-meta.xml
<CustomField>
    <fullName>ApprovedBy__c</fullName>
    <description>This field record the details of the individual who approved this recovery</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Approver_Comment__c.field-meta.xml
<CustomField>
    <fullName>Approver_Comment__c</fullName>
    <description>Comment left on the recovery after approving/rejecting it</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Approver Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Case_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Case_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store who was assigned the case?</description>
    <label>Case Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Recoveries_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/CaseAssignedTo__c.field-meta.xml
<CustomField>
    <fullName>CaseAssignedTo__c</fullName>
    <description>Stores the first person to work on this case</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Assigned To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>QCC: Used to store/show the Recovery description</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field is limited to 100 characters</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Fulfilled_Date__c.field-meta.xml
<CustomField>
    <fullName>Fulfilled_Date__c</fullName>
    <description>Qcc: To Store the fulfilled Date and time</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fulfilled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/FulfilledBy__c.field-meta.xml
<CustomField>
    <fullName>FulfilledBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Full filled by user will be stored.</description>
    <label>Fulfilled By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Recoveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Goodwill_Monetory_Value__c.field-meta.xml
<CustomField>
    <fullName>Goodwill_Monetory_Value__c</fullName>
    <description>This is a reporting field</description>
    <formula>IF(ISPICKVAL(Type__c,&quot;Business Lounge Passes&quot;),Value__c, 
IF(ISPICKVAL(Type__c,&quot;Qantas Points&quot;),Amount__c*0.01, 
IF(ISPICKVAL(Type__c,&quot;Qantas club lounge passes&quot;),Value__c, 
IF(ISPICKVAL(Type__c,&quot;Bag Replacement&quot;),Recovery_Baggage_Cost__c*Amount__c, 
IF(ISPICKVAL(Type__c,&quot;International Business Lounge Passes&quot;),Amount__c*40, 
IF(ISPICKVAL(Type__c,&quot;Domestic Qantas Club Lounge Passes&quot;),Amount__c*20, 
IF(AND(ISPICKVAL(Type__c,&quot;Valet Parking or Carwash&quot;),NOT(ISPICKVAL(Case_Number__r.Origin,&apos;Red App&apos;))),Amount__c*80, 
IF(AND(ISPICKVAL(Type__c,&quot;Valet Parking or Carwash&quot;),ISPICKVAL(Case_Number__r.Origin,&apos;Red App&apos;)),Value__c, 
IF(OR(ISPICKVAL(Type__c,&quot;Space available upgrade&quot;),ISPICKVAL(Type__c,&quot;Firm space upgrade&quot;)),0, 
IF(OR(ISPICKVAL(Type__c,&quot;Credit Card Refund&quot;),ISPICKVAL(Type__c,&quot;EFT Refund&quot;),ISPICKVAL(Type__c,&quot;Dinner vouchers&quot;),ISPICKVAL(Type__c,&quot;Flowers&quot;),ISPICKVAL(Type__c,&quot;Wine&quot;),ISPICKVAL(Type__c,&quot;Travel vouchers&quot;)),Value__c, 
0))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Goodwill Monetory Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Investigated_By__c.field-meta.xml
<CustomField>
    <fullName>Investigated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store person who investigated the recovery</description>
    <label>Investigated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Recoveries_User_CIBY</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Monetary_Value__c.field-meta.xml
<CustomField>
    <fullName>Monetary_Value__c</fullName>
    <description>QCC: Used to track the monetary value of the payment in any currency</description>
    <inlineHelpText>Credit card - Must be AUD equivalent.
EFT - Must be currency of country of bank</inlineHelpText>
    <label>Monetary Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Refund_Account__c.field-meta.xml
<CustomField>
    <fullName>Refund_Account__c</fullName>
    <description>QCC: Used to store the account the EFT/Credit card refund is coming from for a recovery</description>
    <label>Refund Account</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Centre_Account_Number__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>111017	(DPS Cntrl CCP Chargeback)</fullName>
            </value>
            <value>
                <fullName>151370	(QDT)</fullName>
            </value>
            <value>
                <fullName>320022	(Qlink CX SYD)</fullName>
            </value>
            <value>
                <fullName>351356 (Group Insurance Services)</fullName>
            </value>
            <value>
                <fullName>664100	(Misc Revenue)</fullName>
            </value>
            <value>
                <fullName>706021	(Other Employment Costs-Non FBT)</fullName>
            </value>
            <value>
                <fullName>712001	(EU Regulation)</fullName>
            </value>
            <value>
                <fullName>715105 (Sent to wrong destination / Mishandled)</fullName>
            </value>
            <value>
                <fullName>715110 (Cargo Claims)</fullName>
            </value>
            <value>
                <fullName>718000	(Baggage Emergency Expenses)</fullName>
            </value>
            <value>
                <fullName>718001	(Delay Costs)</fullName>
            </value>
            <value>
                <fullName>718005	(Frontline Recovery)</fullName>
            </value>
            <value>
                <fullName>718006	(Baggage Lost)</fullName>
            </value>
            <value>
                <fullName>718007 (Baggage Recharge)</fullName>
            </value>
            <value>
                <fullName>718009	(Events)</fullName>
            </value>
            <value>
                <fullName>718011	(Baggage Damaged)</fullName>
            </value>
            <value>
                <fullName>718012	(Surprise and Delight)</fullName>
            </value>
            <value>
                <fullName>718015	(Denied Boarding Compensation)</fullName>
            </value>
            <value>
                <fullName>718016	(Denied Pax Meals/Accom)</fullName>
            </value>
            <value>
                <fullName>718017	(Ex Gratia Passenger)</fullName>
            </value>
            <value>
                <fullName>718018	(Travel Certificate)</fullName>
            </value>
            <value>
                <fullName>718019	(Downgrade Compensation)</fullName>
            </value>
            <value>
                <fullName>718020	(EU Compensation)</fullName>
            </value>
            <value>
                <fullName>718038	(Charter/Divert Costs - QF)</fullName>
            </value>
            <value>
                <fullName>718044	(Baggage Pilferage)</fullName>
            </value>
            <value>
                <fullName>718086 (Misc Pax Expenses)</fullName>
            </value>
            <value>
                <fullName>718086	(Ops Expenditure)</fullName>
            </value>
            <value>
                <fullName>718100 (Canada Regulation)</fullName>
            </value>
            <value>
                <fullName>754315	(Short Collection)</fullName>
            </value>
            <value>
                <fullName>754905 (FF Operations)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: The status of the recovery</description>
    <label>Recovery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Further Action Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replaced Recovery</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submit for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalisation Declined</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>QCC: Created to show/store Type of goodwill given to customer.</description>
    <label>Recovery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qantas Points</fullName>
            </value>
            <value>
                <fullName>Payment (EFT)</fullName>
            </value>
            <value>
                <fullName>Payment (Credit Card)</fullName>
            </value>
            <value>
                <fullName>Travel vouchers</fullName>
                <label>Travel Vouchers</label>
            </value>
            <value>
                <fullName>Lounge Passes</fullName>
            </value>
            <value>
                <fullName>Bag Replacement</fullName>
            </value>
            <value>
                <fullName>Bag Repair</fullName>
            </value>
            <value>
                <fullName>No Goodwill</fullName>
            </value>
            <value>
                <fullName>Ticket Refund EFT</fullName>
            </value>
            <value>
                <fullName>Cover Refund</fullName>
            </value>
            <value>
                <fullName>First Lounge Pass</fullName>
                <label>First Lounge Pass (CCAT Only)</label>
            </value>
            <value>
                <fullName>Space available upgrade</fullName>
                <label>Space Available Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>Firm space upgrade</fullName>
                <label>Firm Space Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>QF_HOTEL_voucher</fullName>
            </value>
            <value>
                <fullName>QF_WINE_voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>QCC: Created to show/store the value of the goodwill given in AUD</description>
    <inlineHelpText>Goodwill value in AUD. This is a calculated field for equivalent AUD value. Please fill in monetary value instead.</inlineHelpText>
    <label>Equivalent AUD Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RecoveryChartInfoController.cls
/********************************************************************************************************************************

Description: Recovery Portfolio functionality
History:
======================================================================================================================
Name                    Jira                Description                                                 Tag
======================================================================================================================
Bharathkumar Narayanan  QDCUSCON-5396    Recovery Portfolio functionality                                T01
                                    
Created Date    : 01/02/19 (DD/MM/YYYY)

**********************************************************************************************************************************/

global  without sharing  class RecoveryChartInfoController {

      /*    public String PDFData {get; set;} 
    
    public RecoveryChartInfoController(){
        PDFData = '';
    }
    
    public PageReference downloadPDF(){         
        System.PageReference pageRef = new System.PageReference('/apex/PDFGenerator');
    
        //ensure pdf downloads and is assigned with defined name
        pageRef.getHeaders().put('content-disposition', 'attachment; filename=DataPDF.pdf');
     
        return pageRef;
    }*/
    @AuraEnabled
    public static List<User> getMembers(){
        
        List<User> usrList= [select ID,Firstname,Name,Email from User where ManagerId =:Userinfo.getUserId()];
        
        return usrList;
    } 
    
    @AuraEnabled
    public static List<Recovery__c> getMembersRecoveryTypeData(String usrId){
        //List<User> usrList = [select id from usergetMembersRecoveryData where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //Case_Assigned_To__c CaseAssignedTo__c
        System.debug('usrId$$$'+usrId);
       // System.debug('usrId$$$'+rcvryType);
        List<Recovery__c> rcvryList;
        if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
         //   if(rcvryType == null){
             rcvryList= [select ID,Status__c,Type__c,Amount__c,Approver_Comment__c,Monetary_Value__c, Value__c,Refund_Account__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c    , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrList];   
           // }else{
          //   rcvryList= [select ID,Status__c,Type__c,Amount__c,Approver_Comment__c,Monetary_Value__c, Value__c,Refund_Account__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c    , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrList and Type__c =:rcvryType];    
           // }
             
        }else{
            //if(rcvryType == null){
                 rcvryList= [select ID,Status__c,Type__c,Amount__c, Approver_Comment__c,
                                      Monetary_Value__c, Value__c,Description__c, Name,
                                      Case_Number__c, Investigated_By__c,
                                      ApprovedBy__c , FulfilledBy__c, Fulfilled_Date__c,Refund_Account__c from Recovery__c where createdbyId =:usrId];

           // }else{
             // rcvryList= [select ID,Status__c,Type__c,Amount__c, Approver_Comment__c,
               //                       Monetary_Value__c, Value__c,Description__c, Name,
                 //                     Case_Number__c, Investigated_By__c,
                   //                   ApprovedBy__c , FulfilledBy__c, Fulfilled_Date__c,Refund_Account__c from Recovery__c where createdbyId =:usrId and Type__c =:rcvryType];
            //}
        }
               
        return rcvryList;
    }
    
    @AuraEnabled
    public static List<String> getMembersRecoveryTypeList(){
        //List<User> usrList = [select id from usergetMembersRecoveryData where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //Case_Assigned_To__c CaseAssignedTo__c
        
        List<String> rcvryTypeList = new List<String>();
        Schema.DescribeFieldResult fieldResult = Recovery__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        System.debug('ple'+ple);
        for(Schema.PicklistEntry p : ple){
            if(p.isActive()){
                rcvryTypeList.add(p.getValue());
            }
        }
               
        return rcvryTypeList;
    }
    @AuraEnabled
    public static List<Recovery__c> getMembersRecoveryData(String usrId, String rcvryType ){
        //List<User> usrList = [select id from usergetMembersRecoveryData where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //Case_Assigned_To__c CaseAssignedTo__c
        System.debug('usrId$$$'+usrId);
        List<Recovery__c> rcvryList;
        if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
            if(rcvryType == null){
                 rcvryList= [select ID,Status__c,Type__c,Amount__c,Approver_Comment__c,Monetary_Value__c, Value__c,Refund_Account__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c    , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrList];    
            }else{
                 rcvryList= [select ID,Status__c,Type__c,Amount__c,Approver_Comment__c,Monetary_Value__c, Value__c,Refund_Account__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c    , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrList and Type__c = :rcvryType];
            }
            
        }else{
             if(rcvryType == null){
              rcvryList= [select ID,Status__c,Type__c,Amount__c, Approver_Comment__c,
                                      Monetary_Value__c, Value__c,Description__c, Name,
                                      Case_Number__c, Investigated_By__c,
                                      ApprovedBy__c , FulfilledBy__c, Fulfilled_Date__c,Refund_Account__c from Recovery__c where createdbyId =:usrId];

        
             }else{
                 rcvryList= [select ID,Status__c,Type__c,Amount__c, Approver_Comment__c,
                                      Monetary_Value__c, Value__c,Description__c, Name,
                                      Case_Number__c, Investigated_By__c,
                                      ApprovedBy__c , FulfilledBy__c, Fulfilled_Date__c,Refund_Account__c from Recovery__c where createdbyId =:usrId and Type__c = :rcvryType];


             }
        }
               
        return rcvryList;
    }
    
    @AuraEnabled
    public static List<Recovery__c> searchMembersRecoveryData(String usrId, String fDate, String tDate){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //Case_Assigned_To__c CaseAssignedTo__c
        System.debug('fDate$$$'+fDate);
        System.debug('tDate$$$'+tDate);
        String TimedStart = '11:01:00 AM';
        String TimedEnd = '1:59:00 PM';
        DateTime fromDate = DateTime.valueOf(fDate + ' ' + TimedStart);
        DateTime toDate = DateTime.valueOf(tDate + ' ' + TimedEnd);
        //DateTime fromDate;// = (DateTime) fDate;
        //DateTime toDate;// = (DateTime)tDate;
        System.debug('fDate$$$'+fDate);
        System.debug('tDate$$$'+tDate);
        System.debug('fromDate$$$'+fromDate);
        System.debug('toDate$$$'+toDate);
        List<Recovery__c> rcvryList;
        if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
             rcvryList= [select ID,Status__c,Type__c,Amount__c,Refund_Account__c, Approver_Comment__c,Monetary_Value__c, Value__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c   , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrList and createdDate >=:fromDate and createdDate <=:toDate];
        }else{
              rcvryList= [select ID,Status__c,Type__c,Amount__c,Refund_Account__c, Approver_Comment__c,Monetary_Value__c, Value__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c  , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrId and createdDate >=:fromDate and createdDate <=:toDate];
        }
               
        return rcvryList;
    }
    
    
    @AuraEnabled
    public static Integer getAverageRecoveryAmount(String usrId, String rcvryType){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        AggregateResult[] groupedResults;
         if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
             if(rcvryType == null && rcvryType == ''){
                groupedResults = [SELECT AVG(Amount__c)aver FROM Recovery__c where createdbyId =:usrList];
             }else{
                groupedResults = [SELECT AVG(Amount__c)aver FROM Recovery__c where createdbyId =:usrList and Type__c =:rcvryType]; 
             }
         }else{
             if(rcvryType == null && rcvryType == ''){
                groupedResults = [SELECT AVG(Amount__c)aver FROM Recovery__c where createdbyId =:usrId];
             }else{
                groupedResults = [SELECT AVG(Amount__c)aver FROM Recovery__c where createdbyId =:usrId and Type__c=:rcvryType]; 
             }
         }
        Object avgAmount = groupedResults[0].get('aver');  
        return Integer.valueOf(avgAmount);
       //Integer avgAmountInt = Integer.valueOf(avgAmount);
       // return avgAmountInt;
    }
    
     @AuraEnabled
    public static Integer getAverageRecoveryMonetaryValue(String usrId, String rcvryType){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
       // List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
       // 
       AggregateResult[] groupedResults;
         if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
              if(rcvryType == null && rcvryType == ''){
                 groupedResults = [SELECT AVG(Monetary_Value__c)aver FROM Recovery__c where createdbyId =:usrList];
              }else{
                   groupedResults = [SELECT AVG(Monetary_Value__c)aver FROM Recovery__c where createdbyId =:usrList and Type__c =:rcvryType];
              }
         }else{
             if(rcvryType == null && rcvryType == ''){
                 groupedResults = [SELECT AVG(Monetary_Value__c)aver FROM Recovery__c where createdbyId =:usrId];
             }else{
               groupedResults = [SELECT AVG(Monetary_Value__c)aver FROM Recovery__c where createdbyId =:usrId and Type__c =:rcvryType]; 
             }
         }                
        Object avgAmount = groupedResults[0].get('aver');                
        Integer avgAmountInt = Integer.valueOf(avgAmount);
        return avgAmountInt;
    }
    
     @AuraEnabled
    public static Integer getAverageRecoveryValue(String usrId, String rcvryType){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //AggregateResult[] groupedResults = [SELECT AVG(Value__c   )aver FROM Recovery__c where createdbyId =:usrId];// where Case_Number__c =:caseList];
        System.debug('userIdgggg'+usrId);
        AggregateResult[] groupedResults;
         if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
              if(rcvryType == null && rcvryType ==''){
                groupedResults = [SELECT AVG(Value__c)aver FROM Recovery__c where createdbyId =:usrList];
              }else{
                  groupedResults = [SELECT AVG(Value__c)aver FROM Recovery__c where createdbyId =:usrList and Type__c =:rcvryType];
              }
             System.debug('groupedResults'+groupedResults);
         }else{
             System.debug('groupedResults'+groupedResults);
              if(rcvryType == null && rcvryType==''){
                groupedResults = [SELECT AVG(Value__c)aver FROM Recovery__c where createdbyId =:usrId];
              }else{
                groupedResults = [SELECT AVG(Value__c)aver FROM Recovery__c where createdbyId =:usrId and Type__c =:rcvryType];   
              }
         }      
        
        Object avgAmount = groupedResults[0].get('aver'); 
        Integer avgAmountInt = Integer.valueOf(avgAmount);
        return avgAmountInt;
    }
    
    
     @AuraEnabled
    public static Integer getAverageRecoveryGoodwillMonetaryValue(String usrId){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //AggregateResult[] groupedResults = [SELECT AVG(Value__c   )aver FROM Recovery__c where createdbyId =:usrId];// where Case_Number__c =:caseList];
        System.debug('userIdgggg'+usrId);
        AggregateResult[] groupedResults;
         if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
            groupedResults = [SELECT AVG(Goodwill_Monetory_Value__c)aver FROM Recovery__c where createdbyId =:usrList];
             System.debug('groupedResults'+groupedResults);
         }else{
             System.debug('groupedResults'+groupedResults);
             groupedResults = [SELECT AVG(Goodwill_Monetory_Value__c)aver FROM Recovery__c where createdbyId =:usrId];
         }      
        
        Object avgAmount = groupedResults[0].get('aver'); 
        Integer avgAmountInt = Integer.valueOf(avgAmount);
        return avgAmountInt;
    }
    
    
    @AuraEnabled
    public static Integer getAverageRecoveryAmountDate(String usrId, String fDate, String tDate){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        String TimedStart = '11:01:00 AM';
        String TimedEnd = '1:59:00 PM';
        DateTime fromDate = DateTime.valueOf(fDate + ' ' + TimedStart);
        DateTime toDate = DateTime.valueOf(tDate + ' ' + TimedEnd);
        AggregateResult[] groupedResults;
         if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
            groupedResults = [SELECT AVG(Amount__c)aver FROM Recovery__c where createdbyId =:usrList and createdDate >=:fromDate and createdDate <=:toDate];
         }else{
             groupedResults = [SELECT AVG(Amount__c)aver FROM Recovery__c where createdbyId =:usrId and createdDate >=:fromDate and createdDate <=:toDate];
         }
        Object avgAmount = groupedResults[0].get('aver'); 
        return Integer.valueOf(avgAmount);
//Integer avgAmountInt = Integer.valueOf(avgAmount);
        //return avgAmountInt;
    }
    
     @AuraEnabled
    public static Integer getAverageRecoveryMonetaryValueDate(String usrId, String fDate, String tDate){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
       // List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
       String TimedStart = '11:01:00 AM';
        String TimedEnd = '1:59:00 PM';
        DateTime fromDate = DateTime.valueOf(fDate + ' ' + TimedStart);
        DateTime toDate = DateTime.valueOf(tDate + ' ' + TimedEnd);
       AggregateResult[] groupedResults;
         if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
            groupedResults = [SELECT AVG(Monetary_Value__c)aver FROM Recovery__c where createdbyId =:usrList and createdDate >=:fromDate and createdDate <=:toDate];
         }else{
             groupedResults = [SELECT AVG(Monetary_Value__c)aver FROM Recovery__c where createdbyId =:usrId and createdDate >=:fromDate and createdDate <=:toDate];
         }                
        Object avgAmount = groupedResults[0].get('aver');                
        return Integer.valueOf(avgAmount);
       // Integer avgAmountInt = Integer.valueOf(avgAmount);
       // return avgAmountInt;
    }
    
     @AuraEnabled
    public static Integer getAverageRecoveryValueDate(String usrId, String fDate, String tDate){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //AggregateResult[] groupedResults = [SELECT AVG(Value__c   )aver FROM Recovery__c where createdbyId =:usrId];// where Case_Number__c =:caseList];
        String TimedStart = '11:01:00 AM';
        String TimedEnd = '1:59:00 PM';
        DateTime fromDate = DateTime.valueOf(fDate + ' ' + TimedStart);
        DateTime toDate = DateTime.valueOf(tDate + ' ' + TimedEnd);
        System.debug('userIdgggg'+usrId);
        AggregateResult[] groupedResults;
         if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
            groupedResults = [SELECT AVG(Value__c)aver FROM Recovery__c where createdbyId =:usrList and createdDate >=:fromDate and createdDate <=:toDate];
             System.debug('groupedResults'+groupedResults);
         }else{
             System.debug('groupedResults'+groupedResults);
             groupedResults = [SELECT AVG(Value__c)aver FROM Recovery__c where createdbyId =:usrId and createdDate >=:fromDate and createdDate <=:toDate];
         }      
        
        Object avgAmount = groupedResults[0].get('aver'); 
        return Integer.valueOf(avgAmount);
        //Integer avgAmountInt = Integer.valueOf(avgAmount);
        //return avgAmountInt;
    }

 @AuraEnabled
    public static Integer getAverageRecoveryGoodwillMonetaryValueDate(String usrId, String fDate, String tDate){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //AggregateResult[] groupedResults = [SELECT AVG(Value__c   )aver FROM Recovery__c where createdbyId =:usrId];// where Case_Number__c =:caseList];
            String TimedStart = '11:01:00 AM';
        String TimedEnd = '1:59:00 PM';
        DateTime fromDate = DateTime.valueOf(fDate + ' ' + TimedStart);
        DateTime toDate = DateTime.valueOf(tDate + ' ' + TimedEnd);
        System.debug('userIdgggg'+usrId);
        AggregateResult[] groupedResults;
         if(usrId == null || usrId ==''){
            usrId = UserInfo.getUserId();
            List<User> usrList = [select id from user where ManagerId =: usrId];
            groupedResults = [SELECT AVG(Goodwill_Monetory_Value__c)aver FROM Recovery__c where createdbyId =:usrList and createdDate >=:fromDate and createdDate <=:toDate];
             System.debug('groupedResults'+groupedResults);
         }else{
             System.debug('groupedResults'+groupedResults);
             groupedResults = [SELECT AVG(Goodwill_Monetory_Value__c)aver FROM Recovery__c where createdbyId =:usrId and createdDate >=:fromDate and createdDate <=:toDate];
         }      
        
        Object avgAmount = groupedResults[0].get('aver'); 
        return Integer.valueOf(avgAmount);
        //Integer avgAmountInt = Integer.valueOf(avgAmount);
        //return avgAmountInt;
    }
        
        @AuraEnabled
    public static List<Recovery__c> getMembersRecoveryDataFiltered(String usrId, String status){
        //List<User> usrList = [select id from user where ManagerId =: usrId];
        //List<Case> caseList = [select id, OwnerId from case where OwnerId =:usrList];
        //Case_Assigned_To__c CaseAssignedTo__c
        System.debug('usrId$$$'+usrId);
        List<Recovery__c> rcvryList;
        if(status == 'All'){                    
            if(usrId == null || usrId ==''){
                usrId = UserInfo.getUserId();
                List<User> usrList = [select id from user where ManagerId =: usrId];
                 rcvryList= [select ID,Status__c,Type__c,Amount__c, Approver_Comment__c,Refund_Account__c,Monetary_Value__c, Value__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c   , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrList];
            }else{
                  rcvryList= [select ID,Status__c,Type__c,Amount__c, Approver_Comment__c,
                                          Monetary_Value__c, Value__c,Description__c, Name,
                                          Case_Number__c, Investigated_By__c,
                                          ApprovedBy__c , FulfilledBy__c, Fulfilled_Date__c,Refund_Account__c from Recovery__c where createdbyId =:usrId];    
            }
        }else{
            if(usrId == null || usrId ==''){
                usrId = UserInfo.getUserId();
                List<User> usrList = [select id from user where ManagerId =: usrId];
                 rcvryList= [select ID,Status__c,Type__c,Amount__c, Approver_Comment__c,Refund_Account__c,Monetary_Value__c, Value__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c   , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrList and Status__c=:status];
            }else{
                  rcvryList= [select ID,Status__c,Type__c,Amount__c, Approver_Comment__c,Refund_Account__c,Monetary_Value__c, Value__c,Description__c, Name,Case_Number__c, Investigated_By__c,ApprovedBy__c  , FulfilledBy__c, Fulfilled_Date__c from Recovery__c where createdbyId =:usrId and Status__c=:status];    
            }
        }
               
        return rcvryList;
    }   
}