force-app/main/default/objects/Case/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>IF( ISBLANK( ParentId ) ,  CaseNumber ,  Parent.CaseNumber )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated_From__c.field-meta.xml
<CustomField>
    <fullName>Escalated_From__c</fullName>
    <description>QCC: The owner who escalated the case</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Escalated From</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated_From_Location__c.field-meta.xml
<CustomField>
    <fullName>Escalated_From_Location__c</fullName>
    <description>QCC: The location of the consultant who escalated the case</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Escalated From Location</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated_To__c.field-meta.xml
<CustomField>
    <fullName>Escalated_To__c</fullName>
    <description>QCC: The team leader who the case was escalated to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Escalated To</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Used on CL Renewal Cases to capture the location of the Chairman Lounge member (his/her Home port)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <description>Getting Full name of Country to Populate from Contact Country to Case Country field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CountryName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Points_Balance__c.field-meta.xml
<CustomField>
    <fullName>Points_Balance__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer points balance.</description>
    <label>Points Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Email__c</fullName>
    <description>QCC: Created to show/store Preferred email address.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Preferred Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Phone_Number__c</fullName>
    <description>QCC: Created to show/store Contact preferred phone number.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Preferred Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_Frequent_Flyer_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>QCC_Frequent_Flyer_Anniversary_Date__c</fullName>
    <description>QCC: (QDCUSCON-865) Created to show Frequent Flyer Anniversary Date.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Frequent Flyer Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_Status_credits_till_next_Level__c.field-meta.xml
<CustomField>
    <fullName>QCC_Status_credits_till_next_Level__c</fullName>
    <description>QCC: (QDCUSCON-865) Created to store status credits till next level.</description>
    <label>Status credits till next Level</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status_Credits__c.field-meta.xml
<CustomField>
    <fullName>Status_Credits__c</fullName>
    <description>Contact&apos;s Frequent Flyer Status Credits balance</description>
    <label>Status Credits</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Year_of_Joining__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Joining__c</fullName>
    <description>QCC: Created to show/store Year the contact joined the Frequent Flyer program.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Year of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Non_Agency_Contact.recordType-meta.xml
<RecordType>
    <fullName>Non_Agency_Contact</fullName>
    <active>true</active>
    <description>To be used for all contacts.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <description>Frequent Flyer Number of the lead</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>QCC: Created to show/store Contact associated with the recovery.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Investigated_By__c.field-meta.xml
<CustomField>
    <fullName>Investigated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store person who investigated the recovery</description>
    <label>Investigated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Recoveries_User_CIBY</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: The status of the recovery</description>
    <label>Recovery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Further Action Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replaced Recovery</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submit for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalisation Declined</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Queue Members location (manila , Sydney , ..)</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manila</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Hobart</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Capetown</fullName>
            </value>
            <value>
                <fullName>Suva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <formula>Profile.Name</formula>
    <label>Profile Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QL_FFDetailsController.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Priyadharshini Vellingiri
Company:       TCS
Description:   Apex Class for FF Detail display on the Contact layout
Inputs:
Test Class:    QL_FFDetailsControllerTest
************************************************************************************************
History
************************************************************************************************
27-APR-2018    Priyadharshini Vellingiri Initial Design
JIRA : CRM 3092 
13-Oct-2021    Manjula Ravikumar 
JIRA : CRM-5003 | Member API V2 Changes | Introduced differnt callouts and modified wrapper references 
-----------------------------------------------------------------------------------------------------------------------*/
public class QL_FFDetailsController { 
    
    /*--------------------------------------------------------------------------------------      
    Method Name:        fetchCustomerDetail
    Description:        Fetches the QCC Customer information to display
    Parameter:          RecordId 
    --------------------------------------------------------------------------------------*/    
    @AuraEnabled
    public static BannerWrapper fetchCustomerDetail(String recId, Boolean isPageLoad){ 
        try{
            BannerWrapper bannerWrap = new BannerWrapper();
            system.debug('CaseID####'+recId);
            Id conId;
            
            Contact objCon = fetchContact(recId);
            System.debug('objConiiiiii'+objCon);
            if(objCon == Null){
                //Added by Anupam to handle empty contactid from Case
                return null;
            }
            
            Boolean isChanged = false;
            List<OtherProducts> lstOtherProducts = new List<OtherProducts>();
            /* Introduced 4 different API callouts as part of Member API V2 changes CRM - 5003 */
            List<QCC_LoyaltyResponseWrapper.programs> programWrapperList = new List<QCC_LoyaltyResponseWrapper.programs>();
            
            if(objCon != Null && objCon.Frequent_Flyer_Number__c != Null && isPageLoad){
                /*QCC_LoyaltyResponseWrapper loyaltyResponse = QCC_InvokeCAPAPI.invokeLoyaltyAPI(objCon.Frequent_Flyer_Number__c);*/ /*CRM-5003*/
                QCC_LoyaltyResponseWrapper.QantasFrequentFlyerAccount loyaltyAccountResponse = QCC_InvokeCAPAPI.invokeLoyaltyAccountAPI(objCon.Frequent_Flyer_Number__c);
                System.debug('loyaltyAccountResponse=======> ' + loyaltyAccountResponse);
                QCC_LoyaltyResponseWrapper.Programs loyaltyProgramResponse = QCC_InvokeCAPAPI.invokeLoyaltyProgramAPI(objCon.Frequent_Flyer_Number__c);
                System.debug('loyaltyProgramResponse=======> ' + loyaltyProgramResponse);
                QCC_LoyaltyResponseWrapper.QantasFrequentFlyerTier loyaltyTierResponse = QCC_InvokeCAPAPI.invokeLoyaltyTierAPI(objCon.Frequent_Flyer_Number__c);
                System.debug('loyaltyTierResponse=======> ' + loyaltyTierResponse);
                QCC_LoyaltyResponseWrapper.QantasFrequentFlyerProfile loyaltyProfileResponse = QCC_InvokeCAPAPI.invokeLoyaltyProfileAPI(objCon.Frequent_Flyer_Number__c);
                System.debug('loyaltyProfileResponse=======> ' + loyaltyProfileResponse);
                /*if(loyaltyResponse != Null){
                    if(objCon.Points_Balance__c != loyaltyResponse.pointBalance){	
                        objCon.Points_Balance__c = loyaltyResponse.pointBalance;	
                        isChanged = true;	
                    }*/  /*CRM-5003*/
               if(loyaltyAccountResponse != Null){
                    if(objCon.Points_Balance__c != loyaltyAccountResponse.pointBalance){
                        objCon.Points_Balance__c = loyaltyAccountResponse.pointBalance;
                        isChanged = true;
                    }
                     if(loyaltyAccountResponse.statusCredits != Null && objCon.Status_Credits__c != loyaltyAccountResponse.statusCredits.lifetime){
                        objCon.Status_Credits__c = loyaltyAccountResponse.statusCredits.lifetime;
                        isChanged = true;
                    }
                }
                
                /*	
                    if(objCon.Year_of_Joining__c != Date.valueOf(loyaltyResponse.dateOfJoining) || 	
                        objCon.QCC_Frequent_Flyer_Anniversary_Date__c != Date.valueOf(loyaltyResponse.dateOfJoining))	
                    {	
                        objCon.Year_of_Joining__c = Date.valueOf(loyaltyResponse.dateOfJoining);	
                        objCon.QCC_Frequent_Flyer_Anniversary_Date__c = Date.valueOf(loyaltyResponse.dateOfJoining);	
                        isChanged = true;	
                    }
               */ /*CRM--5003*/

                   if(loyaltyProgramResponse != null){
                    programWrapperList.add(loyaltyProgramResponse);
                    for(QCC_LoyaltyResponseWrapper.programs programRecord: programWrapperList) {
                    if(programRecord.enrolmentDate != Null && objCon.Year_of_Joining__c != Date.valueOf(programRecord.enrolmentDate) ||
                        objCon.QCC_Frequent_Flyer_Anniversary_Date__c != Date.valueOf(programRecord.enrolmentDate))
                    {
                        objCon.Year_of_Joining__c = Date.valueOf(programRecord.enrolmentDate);
                        objCon.QCC_Frequent_Flyer_Anniversary_Date__c = Date.valueOf(programRecord.enrolmentDate);
                        isChanged = true;
                    }
                }
                }   

                    

                    if(objCon.Birthdate !=  Date.valueOf(/*loyaltyResponse*/loyaltyProfileResponse.dateOfBirth)){
                        objCon.Birthdate = Date.valueOf(/*loyaltyResponse*/loyaltyProfileResponse.dateOfBirth);
                        isChanged = true;
                    }
                
                  /*   if(loyaltyResponse.programDetails != Null && loyaltyResponse.programDetails.size()>0){	
                        for(QCC_LoyaltyResponseWrapper.programDetails program: loyaltyResponse.programDetails){*/ /*CRM-5003*/

                    if(programWrapperList != Null && programWrapperList.size()>0){
                        for(QCC_LoyaltyResponseWrapper.programs program: programWrapperList){
                            if(program.programCode != 'QFF'){
                                OtherProducts otherProdInfo = new OtherProducts();
                                otherProdInfo.programName = program.programName;
                                otherProdInfo.programCode = program.programCode;
                                lstOtherProducts.add(otherProdInfo);
                            }
                            if(program.programCode == 'QFF' && loyaltyTierResponse != null &&
                                objCon.Frequent_Flyer_tier__c != CustomSettingsUtilities.getConfigDataMap(/*program.tierCode*/ loyaltyTierResponse.qantasFrequentFlyerTier.tierCode)
                                )
                            {
                                objCon.Frequent_Flyer_tier__c = CustomSettingsUtilities.getConfigDataMap(/*program.tierCode*/loyaltyTierResponse.qantasFrequentFlyerTier.tierCode);
                                isChanged = true;
                            }
                        } 
                    }
                    system.debug('aaaaaaaaaaaaa'+objCon.Frequent_Flyer_tier__c);
                    String setting = 'QCCFF_SC-'+objCon.Frequent_Flyer_tier__c;
                    system.debug('ssssssssssssss'+setting);
                    Integer nextLevel = String.isBlank(CustomSettingsUtilities.getConfigDataMap(setting))?/*loyaltyResponse*/loyaltyAccountResponse.statusCredits.lifetime:Integer.valueOf(CustomSettingsUtilities.getConfigDataMap(setting));
                    Integer remaining = nextLevel-/*loyaltyResponse*/loyaltyAccountResponse.statusCredits.lifetime;
                    if(objCon.QCC_Status_credits_till_next_Level__c != remaining){
                        objCon.QCC_Status_credits_till_next_Level__c = remaining;
                        isChanged = true;
                    }

                    // Execute Queueable Apex to update the Contact and LoyaltyProgram in the background
                    //System.enqueueJob(new QCC_UpdateLoyaltyAndContactFFQueueable( objCon));
                
            }

            bannerWrap.objContact = objCon;
            bannerWrap.lstOtherProducts = lstOtherProducts; 
            system.debug('bannerWrap##########'+bannerWrap);
            if(isChanged){
                try{
                    update objCon;
                }catch(Exception ex){
                    CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC_CustomerDetailController', 'QCC_CustomerDetailController', 
                                            'fetchCustomerDetail', String.valueOf(''), String.valueOf(''),false,'', ex);
                }
            }
            
            return bannerWrap;
        }catch(Exception ex){
            system.debug('ex######'+ex);
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC_CustomerDetailController', 'QCC_CustomerDetailController', 
                                    'fetchCustomerDetail', String.valueOf(''), String.valueOf(''),false,'', ex);
            throw new AuraHandledException(ex.getMessage());
        }
       // return null;
    }

   /*--------------------------------------------------------------------------------------      
    Method Name:        fetchContact
    Description:        Fetch all the Contact Info
    Parameter:          
    --------------------------------------------------------------------------------------*/    
    public static Contact fetchContact(String recId){
        Id conId;
        Contact objCon;
            Id ContRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Non_Agency_Contact').getRecordTypeId();
                if(recId.startsWith('003')){
                    conId = recId;
                }
                else if(recId.startsWith('500')){
            Case objCase = [select Id, ContactId from Case where Id =: recId];
                    conId = objCase.ContactId;
                }
                System.debug('conIddddd'+conId);
                if(conId != null){
                    objCon = [select Id, Name, FirstName, LastName, Frequent_Flyer_Number__c, Frequent_Flyer_Tier__c, 
                                    Points_Balance__c, Status_Credits__c, MobilePhone, Preferred_Phone_Number__c, 
                                    Preferred_Email__c, QCC_Status_credits_till_next_Level__c, Birthdate,
                                    QCC_Frequent_Flyer_Anniversary_Date__c,Year_of_Joining__c,
                                    MailingCity,MailingStreet,MailingState,MailingPostalCode ,CountryName__c 
                                    from Contact where Id =: conId
                     		  AND RecordTypeId = :ContRecordTypeId];      
                    System.debug('objConnnnn'+objCon);         
                              
        }
        return objCon;
    }


    /*--------------------------------------------------------------------------------------      
    Method Name:        fetchCaseSummary
    Description:        Fetches the All recordtype of case
    Parameter:          
    --------------------------------------------------------------------------------------*/    
    @AuraEnabled        
    public static BannerWrapper fetchCaseSummary(String recId){
        try{
            Contact objCon = fetchContact(recId);
            Integer disruptionsCount = 0;

            QCC_CAPTransactionWrapper.CAPTransactionRequest requestInfo = new QCC_CAPTransactionWrapper.CAPTransactionRequest();
            requestInfo.system_x = 'CAPCRE_CC';
            requestInfo.firstName = objCon.FirstName;
            requestInfo.surName = objCon.LastName;
            requestInfo.qantasFFNo = objCon.Frequent_Flyer_Number__c;
            requestInfo.version = '1.0';

            QCC_CAPTransactionWrapper.CAPTransactionResponse disruptionResponse = QCC_InvokeCAPAPI.invokeTransactionCAPAPI(requestInfo);
            if(disruptionResponse != null){
                disruptionsCount = disruptionResponse.flightDelayDomesticCount+disruptionResponse.flightDelayInternationalCount;
            }

            Date lastyr = system.today().addMonths(-12);
            Integer caseCount = [ Select count() from case where contactId =: objCon.Id and 
                                 CreatedDate >: lastyr];

            BannerWrapper bannerWrap = new BannerWrapper();
            bannerWrap.caseCount = caseCount;
            bannerWrap.disruptionsCount = disruptionsCount;
            return bannerWrap;
        }catch(Exception ex){
            system.debug('ex######'+ex);
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC_CustomerDetailController', 'QCC_CustomerDetailController', 
                                    'fetchCaseSummary', String.valueOf(''), String.valueOf(''),false,'', ex);
            throw new AuraHandledException(ex.getMessage());
        }
      //  return null;
    }
        

      
    /*--------------------------------------------------------------------------------------      
    Class Name:        BannerWrapper
    Description:        Wrapper to display on the page
    Parameter:          
    --------------------------------------------------------------------------------------*/    
    public class BannerWrapper{
        @AuraEnabled public Contact objContact;
        @AuraEnabled public Integer caseCount;
        @AuraEnabled public Integer disruptionsCount;
        @AuraEnabled public List<OtherProducts> lstOtherProducts;
    }

    public class OtherProducts{
        @AuraEnabled public String programName;
        @AuraEnabled public String programCode;

    }

    /*--------------------------------------------------------------------------------------      
    Method Name:        fetchRecordTypeValues
    Description:        Fetches the All recordtype of case
    Parameter:          
    --------------------------------------------------------------------------------------*/    
    @AuraEnabled        
    public static List<RecordType> fetchRecordTypeValues(){
        List<RecordType> rtNames = new List<RecordType>(); 
        List<Schema.RecordTypeInfo> recordtypes = Case.SObjectType.getDescribe().getRecordTypeInfos(); 
        for(RecordTypeInfo rt : recordtypes){
            if(!rt.isMaster() && rt.isAvailable())
             rtNames.add(new RecordType(Id = rt.getRecordTypeId(),Name = rt.getName()));
        }        
        return  rtNames;
    }
    
    /*--------------------------------------------------------------------------------------      
    Method Name:        saveRecovery
    Description:        Creates a Recovery record by pre-populating some vales from Case
    Parameter:          Id of Case
    --------------------------------------------------------------------------------------*/
    @AuraEnabled
    public static String saveRecovery(Id recId) {
        try {
            System.debug('Recovery ' + recId);
            Case cs = [SELECT Id, ContactId FROM Case WHERE Id = :recId];
            Recovery__c rec = new Recovery__c();
            rec.Case_Number__c = cs.Id;
            rec.Contact__c = cs.ContactId;
            //Jira:CDP2-671
            rec.Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryStatusNew');
            rec.Investigated_By__c = UserInfo.getUserId();
            insert rec;
            return rec.Id;
        } catch(Exception ex){
            System.debug('Exception: '+ex.getMessage());
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC_CustomerDetailController', 'QCC_CustomerDetailController', 
                                     'saveRecovery', String.valueOf(''), String.valueOf(''),false,'', ex);
            throw new AuraHandledException(ex.getMessage());
        }
      //  return null;
    }
    
    /*--------------------------------------------------------------------------------------      
    Method Name:        isConsultant
    Description:        Checks whether the current user is Consultant or not
    Parameter:          Id of User
    --------------------------------------------------------------------------------------*/
    @AuraEnabled
    public static Boolean isConsultant(Id userId) {
        try {
        
            User user = [SELECT Id, Profile_Name__c FROM User WHERE Id = :userId ];
            //CRM-11908 Update metadata rerferences
            if(user.Profile_Name__c == 'Qantas CC Consultant' || user.Profile_Name__c == 'PT1' || user.Profile_Name__c == 'QCC Contact Center Agent Hobart' || 
                user.Profile_Name__c == 'QCC Contact Center Agent Manila' || user.Profile_Name__c == 'QCC Contact Center Agent Capetown' || user.Profile_Name__c == 'QCC Contact Center Agent Suva' 
                || user.Profile_Name__c == 'QCC Contact Center Agent Auckland' || 
                user.Profile_Name__c == 'QCC Contact Center Agent Mumbai') {
                return true;
            }
        } catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC_CustomerDetailController', 'QCC_CustomerDetailController', 
                                     'isConsultant', String.valueOf(''), String.valueOf(''),false,'', ex);
            throw new AuraHandledException(ex.getMessage());
        }
        return false;
    }
    
    /*--------------------------------------------------------------------------------------      
    Method Name:        isCaseClosed
    Description:        Checks whether the Case is Closed or not
    Parameter:          Id of User
    --------------------------------------------------------------------------------------*/
    @AuraEnabled
    public static Boolean isCaseClosed(Id recId) {
        String rid = recId;
        try {
            if(rid.startsWith('500')){
                Case cs = [SELECT Id, Status FROM Case WHERE Id = :recId];
                if(cs.Status == 'Closed') {
                    return true;
                }
            }
        } catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC_CustomerDetailController', 'QCC_CustomerDetailController', 
                                        'isCaseClosed', String.valueOf(''), String.valueOf(''),false,'', ex);
            throw new AuraHandledException(ex.getMessage());
        }
        return false;
    }

    /*--------------------------------------------------------------------------------------      
    Method Name:        isCaseInQueue
    Description:        Checks whether the Case is Closed or not
    Parameter:          Id of User
    --------------------------------------------------------------------------------------*/
    @AuraEnabled
    public static Boolean isCaseInQueue(Id recId) {
        String rid = recId;
        try {
            if(rid.startsWith('500')){
                Case cs = [SELECT Id, Status , OwnerId FROM Case WHERE Id = :recId];
                if(string.valueOf(cs.OwnerId).startsWith('00G')) {
                    return true;
                }
            }
        } catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC_CustomerDetailController', 'QCC_CustomerDetailController', 
                                     'isCaseInQueue', String.valueOf(''), String.valueOf(''),false,'', ex);
            throw new AuraHandledException(ex.getMessage());
        }
        return false;
    }

    
    /*--------------------------------------------------------------------------------------      
    Method Name:        escalateCase
    Description:        Escalates a case and updates the Chatter feed.
    Parameter:          Record Id of Case
    Future:             To add logic to assign the case to Team Lead of the Component.- Done 26-11-2017
    --------------------------------------------------------------------------------------*/
    @AuraEnabled
    public static String escalatingCase(Id recId) {
        try {
            System.debug('Case Id '+recId);
            User user = [SELECT Id, ManagerId, Location__c, Manager.Name FROM User where id = :UserInfo.getUserId()];
            Case cs = [SELECT Id, ContactId, IsEscalated, Owner.Name, OwnerId  FROM Case WHERE Id = :recId];
            
            System.debug('ID of Case + value of Escalated'+ cs.Id + cs.IsEscalated);
            /********************************************************************************************************************/
            
            ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(null, cs.Id, ConnectApi.FeedElementType.FeedItem, 'Case Escalated By '+ cs.Owner.Name);            
           
            /********************************************************************************************************************/
            //Added by Purushotham
            cs.Escalated_From__c = cs.Owner.Name;
            cs.Escalated_From_Location__c = user.Location__c;
            //cs.Escalated_To__c = user.Manager.Name;
            //cs.IsEscalated = true; // Commented by Anupam
            cs.OwnerId = user.ManagerId;
            update cs;
            return cs.Id +','+cs.IsEscalated;
        } catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC_CustomerDetailController', 'QCC_CustomerDetailController', 
                                     'saveRecovery', String.valueOf(''), String.valueOf(''),false,'', ex);
        }
        return null;
    }
}