force-app/main/default/objects/Case/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>IF( ISBLANK( ParentId ) ,  CaseNumber ,  Parent.CaseNumber )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CAP_ID__c.field-meta.xml
<CustomField>
    <fullName>CAP_ID__c</fullName>
    <description>Contact CAP ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>QCC: Created to show/store Total amount provided to customer.</description>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/API_Attempts__c.field-meta.xml
<CustomField>
    <fullName>API_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>QCC: Identifies the number of failed attempts made to call the Loyalty API</description>
    <label>API Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>QCC: Created to show/store Contact associated with the recovery.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>QCC: Used to store the email of the contact for QF Wine/Hotel vouchers</description>
    <formula>Case_Number__r.Contact_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <description>QCC: Used to store the first name of the contact for EFT/Credit card refunds</description>
    <formula>Case_Number__r.First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact_LastName__c.field-meta.xml
<CustomField>
    <fullName>Contact_LastName__c</fullName>
    <description>QCC Loyalty API</description>
    <formula>Case_Number__r.Last_Name__c</formula>
    <label>Contact LastName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/FF_Number__c.field-meta.xml
<CustomField>
    <fullName>FF_Number__c</fullName>
    <description>QCC Frequent Flyer</description>
    <formula>Case_Number__r.Contact.Frequent_Flyer_Number__c</formula>
    <label>FF Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/LoungePassErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>LoungePassErrorMessage__c</fullName>
    <description>QCC: Error messages from OPLA API if it returns an error</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Lounge Pass Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/LoungePassReference__c.field-meta.xml
<CustomField>
    <fullName>LoungePassReference__c</fullName>
    <description>QCC: The reference number or text from OPLA after calling the API to generate Lounge Pass</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Lounge Pass Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/LoungePassRequestTime__c.field-meta.xml
<CustomField>
    <fullName>LoungePassRequestTime__c</fullName>
    <description>QCC: The time when Lounge Pass is requested by calling the OPLA API</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Lounge Pass Request Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Process_Status__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Payment Details Received</fullName>
            </value>
            <value>
                <fullName>Queued for Payment Processing</fullName>
            </value>
            <value>
                <fullName>Submitted to Finance</fullName>
            </value>
            <value>
                <fullName>Findel Approved</fullName>
            </value>
            <value>
                <fullName>Payment Ready</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Finalised</fullName>
            </value>
            <value>
                <fullName>Submitted for Voucher Issuance</fullName>
            </value>
            <value>
                <fullName>Voucher Created</fullName>
            </value>
            <value>
                <fullName>Voucher Sent</fullName>
            </value>
            <value>
                <fullName>Submitted for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Action Required</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Linked</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Recovery_System_log__c.field-meta.xml
<CustomField>
    <fullName>Recovery_System_log__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Recovery System log</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: The status of the recovery</description>
    <label>Recovery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Further Action Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replaced Recovery</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submit for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalisation Declined</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>QCC: Created to show/store Type of goodwill given to customer.</description>
    <label>Recovery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qantas Points</fullName>
            </value>
            <value>
                <fullName>Payment (EFT)</fullName>
            </value>
            <value>
                <fullName>Payment (Credit Card)</fullName>
            </value>
            <value>
                <fullName>Travel vouchers</fullName>
                <label>Travel Vouchers</label>
            </value>
            <value>
                <fullName>Lounge Passes</fullName>
            </value>
            <value>
                <fullName>Bag Replacement</fullName>
            </value>
            <value>
                <fullName>Bag Repair</fullName>
            </value>
            <value>
                <fullName>No Goodwill</fullName>
            </value>
            <value>
                <fullName>Ticket Refund EFT</fullName>
            </value>
            <value>
                <fullName>Cover Refund</fullName>
            </value>
            <value>
                <fullName>First Lounge Pass</fullName>
                <label>First Lounge Pass (CCAT Only)</label>
            </value>
            <value>
                <fullName>Space available upgrade</fullName>
                <label>Space Available Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>Firm space upgrade</fullName>
                <label>Firm Space Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>QF_HOTEL_voucher</fullName>
            </value>
            <value>
                <fullName>QF_WINE_voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/recordTypes/Customer_Connect.recordType-meta.xml
<RecordType>
    <fullName>Customer_Connect</fullName>
    <active>true</active>
    <label>Customer Connect</label>
</RecordType>

force-app/main/default/classes/QCC_RecoveriesCallOPLAAPIQueueable.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Cuong Ly
Company:       Capgemini
Description:   This Quequeable will be invoked by Recovery Trigger to generate Lounges Pass
Inputs:
Test Class:     
************************************************************************************************
History
************************************************************************************************
19-Jun-2018      Cuong Ly               Build execute function
13-Oct-2021    Manjula Ravikumar        JIRA : CRM-5003 | Member API V2 Changes | Introduced differnt callouts and modified wrapper references 
-----------------------------------------------------------------------------------------------------------------------*/
public class QCC_RecoveriesCallOPLAAPIQueueable implements Queueable, Database.AllowsCallouts  { 

    private List<Recovery__c> listRecoveries;

    /*--------------------------------------------------------------------------------------       
    Method Name:        QCC_RevoveriesCallOPLAAPIQueueable
    Description:        Contructer get the recoveries to execute
    Parameter:          set Id of recovery
    --------------------------------------------------------------------------------------*/
    public QCC_RecoveriesCallOPLAAPIQueueable(Set<Id> setRecoveryId){

        this.listRecoveries = [SELECT 
                                    Id, 
                                    Amount__c, 
                                    FF_Number__c, 
                                    Name, 
                                    Status__c, 
                                    Type__c,
                                    Case_Number__c,
                                    Case_Number__r.Contact.CAP_ID__c,
                                    contact__r.salutation, 
                                    Contact_First_Name__c,
                                    Contact_LastName__c,
                                    Case_Number__r.Contact_Email__c,
                                    LoungePassRequestTime__c,
                                    LoungePassReference__c,
                                    LoungePassErrorMessage__c,
                                    Recovery_System_log__c,
                                    API_Attempts__c
                                FROM 
                                    Recovery__c
                                WHERE 
                                    Id IN: setRecoveryId];
    }

    /*--------------------------------------------------------------------------------------       
    Method Name:        execute
    Description:        make callout to OPLA API and update status of recovery based on response from API
    Parameter:          Queueable Context
    --------------------------------------------------------------------------------------*/
    public void execute(QueueableContext context) {
        QCC_OPLALoungePassWrapper.Response oplaResp;
        Set<Id> recoveryIds = new Set<Id>();
        List<Case> cases = new List<Case>();
        String searchFFNumber = '';
        String firstName = '';
        String lastName = '';
        Boolean isSuccess = false;
        for(Recovery__c objRecovery : listRecoveries){
            searchFFNumber = '';
            /* Commented by Purushotham - QDCUSCON-5003 -- START -- Function not needed because there is no Contact for Non FF as part of Remediation
            if(objRecovery.FF_Number__c == null){
                Contact contactSearch = new Contact();
                system.debug('contactSearch.CAP_ID__c=' + objRecovery.Case_Number__r.Contact.CAP_ID__c);
                contactSearch.CAP_ID__c = objRecovery.Case_Number__r.Contact.CAP_ID__c;
                system.debug('contactSearch.CAP_ID__c=' + contactSearch.CAP_ID__c);
                if( GenericUtils.checkBlankorNull(contactSearch.CAP_ID__c)){
                    QCC_CustomerSearchHandler.ContactWrapper contactResult = QCC_CustomerSearchHandler.searchCustomer(contactSearch, '');
                    if(contactResult != null && GenericUtils.checkBlankorNull(contactResult.contacts[0].Frequent_Flyer_Number__c)){
                        //system.debug('QCC_RecoveriesCallOPLAAPIQueueable$$$$$$$$=' + GenericUtils.checkBlankorNull(contactResult.contacts[0].Frequent_Flyer_Number__c));
                        searchFFNumber = contactResult.contacts[0].Frequent_Flyer_Number__c; 
                    }
                } 
            }
            QDCUSCON-5003 -- END*/
            isSuccess = false;
            //system.debug('QCC_RecoveriesCallOPLAAPIQueueable objRecovery.FF_Number__c=' + objRecovery.FF_Number__c);
            // check if Frequent Flyer Number is Exist , make a callout
            if(objRecovery.FF_Number__c != null || GenericUtils.checkBlankorNull(searchFFNumber)){ 
                //Firstly, Call to loyalty API to check FF number 
                searchFFNumber = GenericUtils.checkBlankorNull(searchFFNumber) ? searchFFNumber : objRecovery.FF_Number__c;
                // Introduced new Member API V2 url - CRM 5003
                //  QCC_LoyaltyResponseWrapper loyaltyRes = QCC_InvokeCAPAPI.invokeLoyaltyAPI(searchFFNumber);
                QCC_LoyaltyResponseWrapper.QantasFrequentFlyerProfile loyaltyRes = QCC_InvokeCAPAPI.invokeLoyaltyProfileAPI(searchFFNumber);  
                firstName = objRecovery.Contact_First_Name__c;
                lastName = objRecovery.Contact_LastName__c;
                /* Commented by Purushotham on 09 Aug 2018 as requested by Niket
                if(loyaltyRes != null && firstName.equalsIgnoreCase(loyaltyRes.firstName) && lastName.equalsIgnoreCase(loyaltyRes.lastName)){
                */
                if(loyaltyRes != null && lastName.equalsIgnoreCase(loyaltyRes.lastName)){
                    system.debug('QCC_RecoveriesCallOPLAAPIQueueable');             
                    // init OPLA Request
                    QCC_OPLALoungePassWrapper.Request oplaReq = initOPLARequest(objRecovery);
                    // call out
                    oplaResp = QCC_InvokeOPLAAPI.invokeLoungePassPostAPI(oplaReq);
                    isSuccess = oplaResp.isSuccess;
                    if(isSuccess){
                        // if callout is succeed update recovery as follow:
                        //changes by Navya for CDP2-348
                        objRecovery.Process_Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusFinalised');
                        objRecovery.LoungePassRequestTime__c = System.now();
                        objRecovery.LoungePassReference__c = oplaResp.referenceNo;
                        objRecovery.LoungePassErrorMessage__c = '';
                        objRecovery.Recovery_System_log__c = objRecovery.Recovery_System_log__c == null ? '':objRecovery.Recovery_System_log__c ;
                        objRecovery.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000) + 'OPLA API SUCCESS' + '</li></ul>' + objRecovery.Recovery_System_log__c;
                       
                    }else{
                        recoveryIds.add(objRecovery.Id);
                        // if callout is failed update recovery as follow:
                        objRecovery.LoungePassRequestTime__c = System.now();
                        objRecovery.LoungePassErrorMessage__c = oplaResp.errorMessage;
                        objRecovery.Recovery_System_log__c = objRecovery.Recovery_System_log__c == null ? '':objRecovery.Recovery_System_log__c ;
                        objRecovery.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000) + ' Processing failed, please resubmit recovery' + '</li></ul>' + objRecovery.Recovery_System_log__c;
                        objRecovery.LoungePassReference__c = '';
                        objRecovery.API_Attempts__c = objRecovery.API_Attempts__c + 1;
                        //CDP2-348 Changes by Navya start
            
                        if(objRecovery.API_Attempts__c>=3){//Change this to 3 after testing 
                            objRecovery.Process_Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusException');
                        }
                        
                    }
                }else{
                    recoveryIds.add(objRecovery.Id);
                    objRecovery.Process_Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusException');
                    objRecovery.LoungePassErrorMessage__c = ' Customer\'s frequent flyer details are not valid';
                    objRecovery.Recovery_System_log__c = objRecovery.Recovery_System_log__c == null ? '':objRecovery.Recovery_System_log__c ;
                    objRecovery.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000) + objRecovery.LoungePassErrorMessage__c + '</li></ul>' + objRecovery.Recovery_System_log__c;
                    objRecovery.LoungePassReference__c = '';
                    //CDP2-348 Changes by Navya start
                    //objRecovery.API_Attempts__c = objRecovery.API_Attempts__c + 1;
                }
            }else{
                recoveryIds.add(objRecovery.Id);
                objRecovery.Process_Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusException');
                objRecovery.Recovery_System_log__c = objRecovery.Recovery_System_log__c == null ? '':objRecovery.Recovery_System_log__c ;
                objRecovery.LoungePassErrorMessage__c = ' No Frequent Flyer contact available, add Frequent Flyer contact and then resubmit recovery';
                objRecovery.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000) + objRecovery.LoungePassErrorMessage__c + '</li></ul>' + objRecovery.Recovery_System_log__c;
                objRecovery.LoungePassReference__c = '';
                //CDP2-348 Changes by Navya start
                //objRecovery.API_Attempts__c = objRecovery.API_Attempts__c + 1;
            }
            
        }
        Database.update(listRecoveries,false);
        postToChatter(recoveryIds);
    }

    /*--------------------------------------------------------------------------------------       
    Method Name:        initRoyaltyRequest
    Description:        initiate royal request
    Parameter:          Frequent flyer Number, Point of Recovery , LastName of contact, affected Passenger Name
    --------------------------------------------------------------------------------------*/ 
    private static QCC_OPLALoungePassWrapper.Request initOPLARequest(Recovery__c recovery){

        QCC_OPLALoungePassWrapper.Request oplaReq = new QCC_OPLALoungePassWrapper.Request();
        
        oplaReq.reference_no = recovery.Name;
        oplaReq.frequent_flyer_no = recovery.FF_Number__c;
        oplaReq.expiry_period = CustomSettingsUtilities.getConfigDataMap('QCC OPLA API Expiry Period');
        oplaReq.title = recovery.contact__r.Salutation;
        oplaReq.first_name = recovery.Contact_First_Name__c;
        oplaReq.last_name = recovery.Contact_LastName__c;
        oplaReq.email = recovery.Case_Number__r.Contact_Email__c;
        oplaReq.issuer_code = CustomSettingsUtilities.getConfigDataMap('QCC OPLA API Issuer Code');
        //System.debug('@@@@recovery.Type__c=' + recovery.Type__c);
        //System.debug('@@@@pass_type=' + CustomSettingsUtilities.getConfigDataMap(recovery.Type__c));
        oplaReq.pass_type = CustomSettingsUtilities.getConfigDataMap(recovery.Type__c);
        oplaReq.no_of_pass = String.valueOf(recovery.Amount__c);

        return oplaReq;
    }

    public static void postToChatter(Set<ID> recordIds)
    {   
        // Get those records based on the IDs
        List<Recovery__c> declinedRecoverys = [SELECT Id, Case_Number__c, Name, 
                                    Type__c, LoungePassErrorMessage__c, LoungePassReference__c FROM Recovery__c WHERE RecordType.DeveloperName='Customer_Connect' AND Id IN :recordIds];
        
        for(Recovery__c objRecovery: declinedRecoverys){
            if(!Test.isRunningTest()){
                String comments;
                if(GenericUtils.checkBlankorNull(objRecovery.LoungePassReference__c)){
                    comments = 'Recovery for' + objRecovery.Name + ' ' + objRecovery.Type__c + ' has been successful. Reference No: ' + objRecovery.LoungePassReference__c + '\n ';
                }else{
                    comments = 'OPLA API call unsuccessful Attempt 1 \n ' + objRecovery.LoungePassErrorMessage__c;
                }
                
                ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(null, objRecovery.Case_Number__c, ConnectApi.FeedElementType.FeedItem, comments); 
            }
        }
    }
}