force-app/main/default/objects/Case/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>IF( ISBLANK( ParentId ) ,  CaseNumber ,  Parent.CaseNumber )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resolution_Method__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Method__c</fullName>
    <description>QCC: Used to store/track the case resolution method</description>
    <inlineHelpText>CCC:Method of resolution at case closure</inlineHelpText>
    <label>Resolution Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Webchat</fullName>
            </value>
            <value>
                <fullName>Referred to another department</fullName>
            </value>
            <value>
                <fullName>Letter</fullName>
            </value>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Case auto closed</fullName>
            </value>
            <value>
                <fullName>Bulk Closure</fullName>
            </value>
            <value>
                <fullName>No action required</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Nat Memo</fullName>
            </value>
            <value>
                <fullName>Technical action required</fullName>
            </value>
            <value>
                <fullName>Referred to other area</fullName>
            </value>
            <value>
                <fullName>Other Airline</fullName>
            </value>
            <value>
                <fullName>Auto Closed - Sensitive Case</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>PNR Investigation</fullName>
            </value>
            <value>
                <fullName>Nil Action - Thank You</fullName>
            </value>
            <value>
                <fullName>Nil Action - Email Auto Reply</fullName>
            </value>
            <value>
                <fullName>Nil Action - Duplicate</fullName>
            </value>
            <value>
                <fullName>Nil Action - Internal Reply</fullName>
            </value>
            <value>
                <fullName>Nil Action - Customer Behaviour</fullName>
            </value>
            <value>
                <fullName>Auto Closed - Recovery</fullName>
            </value>
            <value>
                <fullName>Contact Only</fullName>
                <isActive>false</isActive>
                <label>Contact Only</label>
            </value>
            <value>
                <fullName>Duplicate</fullName>
                <isActive>false</isActive>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>Goodwill</fullName>
                <isActive>false</isActive>
                <label>Goodwill</label>
            </value>
            <value>
                <fullName>Nil Action</fullName>
                <isActive>false</isActive>
                <label>Nil Action</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <description>CASE Number For loyalty API</description>
    <formula>Case_Number__r.CaseNumber</formula>
    <label>CaseNumber</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Process_Status__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Payment Details Received</fullName>
            </value>
            <value>
                <fullName>Queued for Payment Processing</fullName>
            </value>
            <value>
                <fullName>Submitted to Finance</fullName>
            </value>
            <value>
                <fullName>Findel Approved</fullName>
            </value>
            <value>
                <fullName>Payment Ready</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Finalised</fullName>
            </value>
            <value>
                <fullName>Submitted for Voucher Issuance</fullName>
            </value>
            <value>
                <fullName>Voucher Created</fullName>
            </value>
            <value>
                <fullName>Voucher Sent</fullName>
            </value>
            <value>
                <fullName>Submitted for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Action Required</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Linked</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Recovery_System_log__c.field-meta.xml
<CustomField>
    <fullName>Recovery_System_log__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Recovery System log</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: The status of the recovery</description>
    <label>Recovery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Further Action Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replaced Recovery</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submit for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalisation Declined</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloneCaseAndReparentRecoveries.cls
public class CloneCaseAndReparentRecoveries {
    
    @InvocableMethod(label='Clone Parent Case and Reassign Recoveries' description='Clones the parent Case related to each Recovery by Case_Number__c and reassigns the Recoveries to the new Case')
    public static void cloneAndReparent(List<String> recoveryIds) {
        // Step 1: Query the Recovery records with the parent Case
        Map<String, List<Recovery__c>> caseNumberToRecoveries = new Map<String, List<Recovery__c>>();
       // Map<String, Case> caseNumberToOriginalCase = new Map<String, Case>();

        List<Recovery__c> recoveries = [
            SELECT Id, Name,Case_Number__c,Case_Number__r.ParentId,Recovery_System_log__c,casenumber__c,Case_Number__r.Casenumber
            FROM Recovery__c
            WHERE Id IN :recoveryIds
            
        ];

        for (Recovery__c rec : recoveries) {
            String caseNumber = rec.Case_Number__r.ParentId != null ? rec.Case_Number__r.ParentId : rec.Case_Number__c;
            if (!caseNumberToRecoveries.containsKey(caseNumber)) {
                caseNumberToRecoveries.put(caseNumber, new List<Recovery__c>());
            }
            caseNumberToRecoveries.get(caseNumber).add(rec);
        }
         system.debug('caseNumberToRecoveries '+caseNumberToRecoveries);

        // Step 2: Get the unique Cases by Case_Number__c
        Set<String> caseNumbers = caseNumberToRecoveries.keySet();
        List<String> fieldNames = new List<String>();
        for (String fieldName : Schema.SObjectType.Case.fields.getMap().keySet()) {
            fieldNames.add(fieldName);
        }

        // Join the fields into a comma-separated string for the SOQL query
        String soql = 'SELECT ' + String.join(fieldNames, ', ') + ' FROM Case WHERE Id = :caseNumbers';

        List<Case> originalCases = Database.query(soql);
        
        list<id> parentCaseIds = new list<id>();
        for (Case oldCase : originalCases) {
            if(oldCase.ParentId != null){
                parentCaseIds.add(oldCase.ParentId);                
            }
            parentCaseIds.add(oldCase.Id);
        }
        system.debug('parentCaseIds '+parentCaseIds);
        map<id, case> siblingCaseIds = new map<id,case>();
        for(case cs : [select id, parentid, recordtypeid,casenumber from case where parentId in : parentCaseIds and isclosed = false]){
            siblingCaseIds.put(cs.parentid,cs);
        }

        // Step 3: Clone Cases
        List<Case> newCases = new List<Case>();
        Map<id, case> caseNumberToNewCaseId = new Map<id, case>();
        list<case> newlistCase = new list<case>();
        for (Case oldCase : originalCases) {
            if(oldCase.parentId != null && siblingCaseIds.get(oldCase.parentId) != null && oldCase.recordtypeid == siblingCaseIds.get(oldCase.parentId).recordtypeid ){
                newlistCase.add(siblingCaseIds.get(oldCase.parentId));
                caseNumberToNewCaseId.put(oldCase.parentId, siblingCaseIds.get(oldCase.parentId));
            }
            else if(siblingCaseIds.get(oldCase.id) != null && oldCase.recordtypeid == siblingCaseIds.get(oldCase.id).recordtypeid){
                newlistCase.add(siblingCaseIds.get(oldCase.Id));
                caseNumberToNewCaseId.put(oldCase.id, siblingCaseIds.get(oldCase.Id));
            }
            else{
                Case newCase = oldCase.clone(false, true, false, false);
                newCase.parentId = oldCase.ParentId != null ? oldcase.parentId : oldCase.Id;
                newCase.Status = 'Pending Recovery';
                newCase.Resolution_Method__c = '';
                newCases.add(newCase);
                newlistCase.add(newCase);
            }
        }
        boolean isexception = false;
        string expectionmsg = '';
        try{
            insert newCases;
            for (Integer i = 0; i < newCases.size(); i++) {
                caseNumberToNewCaseId.put(newCases[i].parentId, newCases[i]);
            }            
        }
        catch(exception e){
            isexception = true;
            expectionmsg = e.getmessage();
        }

        

        // Step 4: Reparent Recoveries
        List<Recovery__c> updates = new List<Recovery__c>();
        
        list<string> fromcase = new list<string>();
        list<string> tocase = new list<string>();
        list<string> recoveryName = new list<string>();
        for (String caseNumber : caseNumberToRecoveries.keySet()) {
            case newCaseId = caseNumberToNewCaseId.get(caseNumber);
            for (Recovery__c rec : caseNumberToRecoveries.get(caseNumber)) {
                if(isexception){
                    rec.process_status__c = 'Exception';
                    rec.status__c = 'Further Action Required';
                    rec.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000)+ ' Rejected Recovery -  Manually Clone Case and Run Rejection on Recovery. </li></ul>' + rec.Recovery_System_log__c;
                }
                else{
                    
                   
                    fromcase.add(rec.Case_Number__c);
                    tocase.add(newCaseId.Id);
                    recoveryName.add(rec.name);
                    rec.Case_Number__c = newCaseId.id;
                    rec.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000)+ ' Recovery relinked From Case ['+rec.casenumber__c+'] after failed Payment </li></ul>' + rec.Recovery_System_log__c;
                   
                    
                }                 
                updates.add(rec);
            }
        }

        update updates;
        postRecoveryChatterMessages(fromcase,tocase,recoveryName);
    }    

    @future
    public static void postRecoveryChatterMessages(list<string> fromcase ,list<string> tocase,list<string> recoveyNames) {
        
        map<id,case> casemap = new map<id,case>([select id,casenumber from case where id in : fromcase or id in : tocase]);
        List<FeedItem> feedPosts = new List<FeedItem>();

        for (integer i =0 ; i< fromcase.size() ; i++) {
            if (true) {
                FeedItem post = new FeedItem();
                post.ParentId = fromcase[i];
                post.Body = recoveyNames[i] + ' moved to Case ' +
                            casemap.get(tocase[i]).CaseNumber +
                            ' due to Failed payment (from Case ' + casemap.get(fromcase [i]).CaseNumber+ ').';
                post.Type = 'TextPost';
                feedPosts.add(post);
            }
        }

        if (!feedPosts.isEmpty()) {
            insert feedPosts;
        }
    }
}