force-app/main/default/objects/Case/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>IF( ISBLANK( ParentId ) ,  CaseNumber ,  Parent.CaseNumber )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Bank_Details_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Bank_Details_Updated_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bank Details Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>QCC: Used to store the name of the bank branch for EFT refunds as recovery</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Branch_Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Party_Id__c</fullName>
    <description>QCC: Used to store the Bank Branch Party Id for EFT Refunds</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Party Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Branch_Swift_BIC_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Swift_BIC_Code__c</fullName>
    <description>Used to store the Branch Swift/BIC code for EFT refunds</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Required for foreign payments</inlineHelpText>
    <label>Branch Swift / BIC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Cost_Centre_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Cost_Centre_Account_Number__c</fullName>
    <label>Cost Centre/Account Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airports : Baggage Damaged (100814 : 718011)</fullName>
            </value>
            <value>
                <fullName>Airports : Baggage Lost (100814 : 718006)</fullName>
            </value>
            <value>
                <fullName>Customer Care : Ex Gratia Passenger (309276 : 718017)</fullName>
                <label>Customer Care : Goodwill Passenger (309276 : 718017)</label>
            </value>
            <value>
                <fullName>Customer Care : Ops Expenditure (309276 : 718086)</fullName>
                <label>Customer Care : Delays and Operational (309276 : 718086)</label>
            </value>
            <value>
                <fullName>Customer Care : Events  (309276 : 718009)</fullName>
            </value>
            <value>
                <fullName>Baggage Goodwill : Baggage Emergency Expenses (101366 :  718000)</fullName>
            </value>
            <value>
                <fullName>Baggage Goodwill :  Baggage Pilferage (101366 : 718044)</fullName>
            </value>
            <value>
                <fullName>EU Regulation :  EU Regulation (800301 : 712001)</fullName>
            </value>
            <value>
                <fullName>Canada Regulation : Canada Regulation (100333 : 718100)</fullName>
            </value>
            <value>
                <fullName>Full Cost Centre/ Account Number</fullName>
            </value>
            <value>
                <fullName>Customer Service : Cargo Claims (557175: 715110)</fullName>
            </value>
            <value>
                <fullName>Customer Service : Sent to Wrong Destination / Mishandled (557175: 715105)</fullName>
            </value>
            <value>
                <fullName>Sydney Freight : Cargo Claims (557143 : 715110)</fullName>
            </value>
            <value>
                <fullName>Sydney Freight : Sent to Wrong Destination / Mishandled (557143 : 715105)</fullName>
            </value>
            <value>
                <fullName>Melbourne Freight : Cargo Claims (557151 : 715110)</fullName>
            </value>
            <value>
                <fullName>Melbourne Freight : Sent to Wrong Destination / Mishandled (557151 : 715105)</fullName>
            </value>
            <value>
                <fullName>INT Baggage Solutions : Baggage Recharge (100782 : 718007)</fullName>
            </value>
            <value>
                <fullName>FF Operations : Operations and Service Centre (169789 : 754905)</fullName>
            </value>
            <value>
                <fullName>QANTAS Fin Svcs REVERA (100759 : 390527)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <formula>SUBSTITUTE(RIGHT( TEXT(Refund_POS_Country__c),(LEN( TEXT(Refund_POS_Country__c))-FIND(&quot;(&quot;, TEXT(Refund_POS_Country__c)))),&apos;)&apos;,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Original_Currency_Acronym__c.field-meta.xml
<CustomField>
    <fullName>Original_Currency_Acronym__c</fullName>
    <formula>LEFT(TEXT(Original_Currency__c) , 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Currency Acronym</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Process_Status__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Payment Details Received</fullName>
            </value>
            <value>
                <fullName>Queued for Payment Processing</fullName>
            </value>
            <value>
                <fullName>Submitted to Finance</fullName>
            </value>
            <value>
                <fullName>Findel Approved</fullName>
            </value>
            <value>
                <fullName>Payment Ready</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Finalised</fullName>
            </value>
            <value>
                <fullName>Submitted for Voucher Issuance</fullName>
            </value>
            <value>
                <fullName>Voucher Created</fullName>
            </value>
            <value>
                <fullName>Voucher Sent</fullName>
            </value>
            <value>
                <fullName>Submitted for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Action Required</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Linked</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Recovery_Reason__c.field-meta.xml
<CustomField>
    <fullName>Recovery_Reason__c</fullName>
    <businessOwnerUser>brenton.watson@qantas.com.au.pist</businessOwnerUser>
    <description>Recovery Reason shows the reason for the recovery, which is communicated to the customer</description>
    <label>Recovery Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Damaged Baggage</fullName>
            </value>
            <value>
                <fullName>Lost Baggage</fullName>
            </value>
            <value>
                <fullName>Ticket Refund (Compassionate Grounds)</fullName>
            </value>
            <value>
                <fullName>Ticket Refund (Non-Refundable Fare)</fullName>
            </value>
            <value>
                <fullName>Ticket Refund (Error)</fullName>
            </value>
            <value>
                <fullName>Cancellation Fees</fullName>
            </value>
            <value>
                <fullName>EMDS (Baggage &amp; Seats)</fullName>
            </value>
            <value>
                <fullName>EMDS (Bid Upgrade)</fullName>
            </value>
            <value>
                <fullName>Adcol Charged Incorrectly</fullName>
            </value>
            <value>
                <fullName>Expense Reimbursement (Flight Disruptions)</fullName>
            </value>
            <value>
                <fullName>Delayed Baggage (Emergency Expenses)</fullName>
            </value>
            <value>
                <fullName>EU Compensation</fullName>
            </value>
            <value>
                <fullName>Montreal Convention Compensation</fullName>
            </value>
            <value>
                <fullName>Civil Aviation Authority Compensation</fullName>
            </value>
            <value>
                <fullName>Bag Repair</fullName>
            </value>
            <value>
                <fullName>Missing Baggage Contents</fullName>
            </value>
            <value>
                <fullName>Damaged Mobility Aid</fullName>
            </value>
            <value>
                <fullName>Delayed Mobility Aid</fullName>
            </value>
            <value>
                <fullName>Lost Mobility Aid</fullName>
            </value>
            <value>
                <fullName>Ticket Refund</fullName>
            </value>
            <value>
                <fullName>In-flight Experience (defaulted)</fullName>
            </value>
            <value>
                <fullName>Airport Experience</fullName>
            </value>
            <value>
                <fullName>Lounge Experience</fullName>
            </value>
            <value>
                <fullName>In-flight Experience</fullName>
            </value>
            <value>
                <fullName>Digital Experience</fullName>
            </value>
            <value>
                <fullName>Flight Disruption</fullName>
            </value>
            <value>
                <fullName>Baggage Experience</fullName>
            </value>
            <value>
                <fullName>Contact Centre Service Experience</fullName>
            </value>
            <value>
                <fullName>Points Refund</fullName>
            </value>
            <value>
                <fullName>Seating Downgrades</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Recovery_System_log__c.field-meta.xml
<CustomField>
    <fullName>Recovery_System_log__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Recovery System log</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/SkipExceptionForEUComp__c.field-meta.xml
<CustomField>
    <fullName>SkipExceptionForEUComp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>1061 - Skip Process Status to Exception for Recovery Reason - EU Compensation when Submit for Processing button is clicked 
Applicable only for EFT Recoveries</description>
    <label>SkipExceptionForEUComp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>QCC: Created to show/store Type of goodwill given to customer.</description>
    <label>Recovery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qantas Points</fullName>
            </value>
            <value>
                <fullName>Payment (EFT)</fullName>
            </value>
            <value>
                <fullName>Payment (Credit Card)</fullName>
            </value>
            <value>
                <fullName>Travel vouchers</fullName>
                <label>Travel Vouchers</label>
            </value>
            <value>
                <fullName>Lounge Passes</fullName>
            </value>
            <value>
                <fullName>Bag Replacement</fullName>
            </value>
            <value>
                <fullName>Bag Repair</fullName>
            </value>
            <value>
                <fullName>No Goodwill</fullName>
            </value>
            <value>
                <fullName>Ticket Refund EFT</fullName>
            </value>
            <value>
                <fullName>Cover Refund</fullName>
            </value>
            <value>
                <fullName>First Lounge Pass</fullName>
                <label>First Lounge Pass (CCAT Only)</label>
            </value>
            <value>
                <fullName>Space available upgrade</fullName>
                <label>Space Available Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>Firm space upgrade</fullName>
                <label>Firm Space Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>QF_HOTEL_voucher</fullName>
            </value>
            <value>
                <fullName>QF_WINE_voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QCC_BankSearchCallHelper.cls
public class QCC_BankSearchCallHelper{
    public static string updateRecoveries(list<id> recordIds,string response , boolean isException,string responsebody){
        
        String query = getallFieldsRecovery(); 
        query += ' FROM Recovery__c WHERE Id IN :recordIds ';
        list<Recovery__c> tobeUpdatedRecovery = Database.query(query);
        for(Recovery__c recov : tobeUpdatedRecovery ){
            if(isException){
                recov.Process_Status__c = 'Exception';
            }else{
                QCC_BankBranchRecordsResponse responseObj = QCC_BankBranchRecordsResponse.parseJSON(response);
                system.debug('responseObj>>>'+responseObj);
                system.debug('recvy>>>'+recov);
                if(responseObj != null && responseObj.P_BANK_BRANCH_RECORDS != null
                  && responseObj.P_BANK_BRANCH_RECORDS.P_BANK_BRANCH_RECORDS_ITEM != null){

                    //Todo:add code here to select bank record with exact swift match if available, else select first record

                      QCC_BankBranchRecordsResponse.P_BANK_BRANCH_RECORDS_ITEM item; // = responseObj.P_BANK_BRANCH_RECORDS.P_BANK_BRANCH_RECORDS_ITEM[0];
                      for(QCC_BankBranchRecordsResponse.P_BANK_BRANCH_RECORDS_ITEM temp : responseObj.P_BANK_BRANCH_RECORDS.P_BANK_BRANCH_RECORDS_ITEM){
                          item = temp;
                          if(temp.EFT_SWIFT_CODE == recov.Branch_Swift_BIC_Code__c){
                              break;
                          }
                      }
                      //system.debug('item>>>'+item != null);
                      if( item.ERROR_CODE != null && item.ERROR_CODE != '' && item.ERROR_CODE != 'EC01' && item.ERROR_CODE != 'EC02'){ 
                          recov.Process_Status__c = 'Exception';
                          responsebody =  '<span style="color: red;">FAIL</span> '+item.ERROR_CODE+ ' ' +item.MESSAGE;
                      }
                      else if ( recov.Cost_Centre_Account_Number__c.contains('EU Regulation') 
                               && item.EFT_SWIFT_CODE == null && recov.Original_Currency_Acronym__c == 'AUD'){// added from CDP2-703
                          recov.Process_Status__c = 'Exception';
                          responsebody =  '<span style="color: red;">FAIL</span> RITM Needed to add Bank Swift code ';
                      }
                      else{
                          recov.Bank_Details_Updated_Date__c = System.now();
                          recov.Branch_Name__c = item.BANK_BRANCH_NAME;
                          recov.Branch_Party_Id__c = item.BRANCH_ID;
                          recov.Branch_Swift_BIC_Code__c = item.EFT_SWIFT_CODE;
                          //CDP2-997 Payment EFT and Recovery reason - EU Compensation
                          //1061 - Reset Skip Exception flag 
                          if(recov.Type__c == 'Payment (EFT)' && recov.Recovery_Reason__c == 'EU Compensation' && !recov.SkipExceptionForEUComp__c){
                            recov.Process_Status__c = 'Exception';
                          } 
                          else if(recov.Process_Status__c != 'Exception')//added 21/8/2024 CDP2-531 to ensure if status already exception due to currency conversion failure, no change allowed
                          {
                              recov.Process_Status__c = CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusQuedForPaymentPrcsng');
                          }
                          //1061 - Reset Skip Exception flag 
                          if(recov.SkipExceptionForEUComp__c) {
                            recov.SkipExceptionForEUComp__c = false;
                          }
                          responsebody =  '<span style="color: green;">SUCCESS </span> '+ (item.ERROR_CODE != 'EC01' && item.ERROR_CODE != 'EC02' ? 'Multiple ': '') +'Record found. Updating recovery branch name to '+item.BANK_BRANCH_NAME;
                      }
                    
                }
            }
            recov.Recovery_System_log__c = recov.Recovery_System_log__c == null ? '':recov.Recovery_System_log__c ;
            
            recov.Recovery_System_log__c = '<ul><li>'+ DateTime.Now().addSeconds( UserInfo.getTimezone().getOffset(DateTime.Now()) / 1000)+ ' (BANK SEARCH) ' +responsebody + '</li></ul>' + recov.Recovery_System_log__c;
            
            
        }
        RecoveryTriggerHelper.hasRun = true;
        update tobeUpdatedRecovery;
        return null;
    }
    public static string getallFieldsRecovery(){
        String query = 'SELECT ';        
        List<String> fieldNames = new List<String>();
        Map<String, Schema.SObjectField> fieldsMap = Schema.SObjectType.Recovery__c.fields.getMap();
        
        for (String fieldName : fieldsMap.keySet()) {
            fieldNames.add(fieldName);
        }        
        query += String.join(fieldNames, ', ');
        return query;
    }
    public static string preparePayload(list <id> recordIds){
        
        String query = getallFieldsRecovery(); 
        
        query += ' , Case_Number__r.Contact.Salutation, Case_Number__r.Contact.FirstName,Case_Number__r.Contact.LastName FROM Recovery__c WHERE Id IN :recordIds';
        requestJson request = new requestJson();
        request.inputParameters = new InputParameters();
        request.inputParameters.P_BANK_BRANCH_RECORDS = new P_BANK_BRANCH_RECORDS();
        request.inputParameters.P_BANK_BRANCH_RECORDS.P_BANK_BRANCH_RECORDS_ITEM = new List<P_BANK_BRANCH_RECORDS_ITEM>();
        
       
        for (recovery__c record : Database.query(query)) {
            P_BANK_BRANCH_RECORDS_ITEM item = new P_BANK_BRANCH_RECORDS_ITEM();
            item.CLAIM_NO = record.Name;
            item.BANK_COUNTRY = record.Country_Name__c;
            //Changes by Navya CDP2-1018
            if (!((record.type__c =='Payment (EFT)' || record.type__c =='Ticket Refund EFT' ) && 
                (record.Original_Currency__c =='AUD Australian Dollar' || record.Original_Currency__c == 'NZD New Zealand Dollar') ) && 
                record.payment_Details_added_manually__c ){
                   item.BANK_NAME = record.Bank_Name__c;
             }
            item.BANK_BRANCH_NAME = record.Branch_Name__c;
            item.BRANCH_NUMBER = record.Branch_Number_BSB_Sort_Code__c;
            item.EFT_SWIFT_CODE = record.Branch_Swift_BIC_Code__c;

            // Add the item to the list
            request.inputParameters.P_BANK_BRANCH_RECORDS.P_BANK_BRANCH_RECORDS_ITEM.add(item);
        }
        
        return JSON.serialize(request);        
    }
    public class requestJson{
        public InputParameters InputParameters;
    }

    public class InputParameters {
        public P_BANK_BRANCH_RECORDS P_BANK_BRANCH_RECORDS;
    }

    public class P_BANK_BRANCH_RECORDS {
        public List<P_BANK_BRANCH_RECORDS_ITEM> P_BANK_BRANCH_RECORDS_ITEM;
    }

    public class P_BANK_BRANCH_RECORDS_ITEM {
        public String CLAIM_NO;
        public String BANK_COUNTRY;
        public String BANK_NAME;
        public String BANK_BRANCH_NAME;
        public String BRANCH_NUMBER;
        public String BRANCH_ID;
        public String EFT_SWIFT_CODE;
    }
    // Example usage:
    //String jsonString = '{ "InputParameters": { "P_BANK_BRANCH_RECORDS": { "P_BANK_BRANCH_RECORDS_ITEM": [ { "CLAIM_NO": "TEST_01", "BANK_COUNTRY": "XXX", "BANK_NAME": "Citi", "BANK_BRANCH_NAME": "C", "BRANCH_NUMBER": "600037002", "EFT_SWIFT_CODE": "" } ] } } }';
    //BankBranchRecords bankBranchRecords = BankBranchRecords.parse(jsonString);
    //System.debug(bankBranchRecords);
}