force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>QCC: Created to show/store Issue Category.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Accommodation/Reimbursement of Expenses</fullName>
            </value>
            <value>
                <fullName>Account Queries</fullName>
            </value>
            <value>
                <fullName>Advertising</fullName>
            </value>
            <value>
                <fullName>Aircraft Condition</fullName>
            </value>
            <value>
                <fullName>Aircraft Schedule Change/Notification</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Airport Security</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Announcements</fullName>
            </value>
            <value>
                <fullName>AQIRE</fullName>
            </value>
            <value>
                <fullName>ARD Web</fullName>
            </value>
            <value>
                <fullName>Audits</fullName>
            </value>
            <value>
                <fullName>Award Bookings</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>BART Document</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Blue Prism</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Bounce Back</fullName>
            </value>
            <value>
                <fullName>Cabin Baggage</fullName>
            </value>
            <value>
                <fullName>Call outs</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation Fees</fullName>
            </value>
            <value>
                <fullName>Carbon Offset</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Charter Flights</fullName>
            </value>
            <value>
                <fullName>Chauffeur Drive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Problem_Type__c.field-meta.xml
<CustomField>
    <fullName>Problem_Type__c</fullName>
    <label>Waiver Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ADCOL</fullName>
            </value>
            <value>
                <fullName>Advance Purchase</fullName>
            </value>
            <value>
                <fullName>Advance Seat Selection</fullName>
            </value>
            <value>
                <fullName>Agent Discount Travel</fullName>
            </value>
            <value>
                <fullName>Internal - Booking Class</fullName>
            </value>
            <value>
                <fullName>Cancellation Fees</fullName>
            </value>
            <value>
                <fullName>Change Destinations</fullName>
            </value>
            <value>
                <fullName>Change of TMC</fullName>
            </value>
            <value>
                <fullName>Coupon Suspension</fullName>
            </value>
            <value>
                <fullName>Deposit Amount</fullName>
            </value>
            <value>
                <fullName>Deposit Deadline</fullName>
            </value>
            <value>
                <fullName>Excess Baggage</fullName>
            </value>
            <value>
                <fullName>Expired Fare</fullName>
            </value>
            <value>
                <fullName>Fare Quote</fullName>
            </value>
            <value>
                <fullName>Fare Reassessment</fullName>
            </value>
            <value>
                <fullName>Final Payment Deadline</fullName>
            </value>
            <value>
                <fullName>FOC Request</fullName>
            </value>
            <value>
                <fullName>Group/Family Qantas Club Access</fullName>
            </value>
            <value>
                <fullName>Group/Family Qantas First Lounge Access</fullName>
            </value>
            <value>
                <fullName>Lounge Access - Qantas Club</fullName>
            </value>
            <value>
                <fullName>Lounge Access – Qantas Club</fullName>
            </value>
            <value>
                <fullName>Lounge Access - Qantas Domestic Business Lounge</fullName>
            </value>
            <value>
                <fullName>Lounge Access – Qantas Domestic Business Lounge</fullName>
            </value>
            <value>
                <fullName>Lounge Access - Qantas First Lounge</fullName>
            </value>
            <value>
                <fullName>Lounge Access – Qantas First Lounge</fullName>
            </value>
            <value>
                <fullName>Lounge Access - Qantas International Business Lounge</fullName>
            </value>
            <value>
                <fullName>Lounge Access – Qantas International Business Lounge</fullName>
            </value>
            <value>
                <fullName>Maximum Stay</fullName>
            </value>
            <value>
                <fullName>Minimum Group Size</fullName>
            </value>
            <value>
                <fullName>Minimum Stay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Waiver_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Waiver_Sub_Type__c</fullName>
    <label>Waiver Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Problem_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled in Error</fullName>
            </value>
            <value>
                <fullName>Class Upgrade</fullName>
            </value>
            <value>
                <fullName>Live Booking</fullName>
            </value>
            <value>
                <fullName>Purged Booking</fullName>
            </value>
            <value>
                <fullName>Ticket Credit</fullName>
            </value>
            <value>
                <fullName>Ticketed - Interline/Codeshare</fullName>
            </value>
            <value>
                <fullName>Ticketed - Qantas/Jetstar</fullName>
            </value>
            <value>
                <fullName>Ticketed - Qantas Operated and Marketed</fullName>
            </value>
            <value>
                <fullName>Ticket Refund</fullName>
            </value>
            <value>
                <fullName>Ticket Reissue</fullName>
            </value>
            <value>
                <fullName>Ticket Revalidation</fullName>
            </value>
            <value>
                <fullName>Unticketed - Interline/Codeshare</fullName>
            </value>
            <value>
                <fullName>Unticketed - Qantas/Jetstar</fullName>
            </value>
            <value>
                <fullName>Unticketed - Qantas Operated and Marketed</fullName>
            </value>
            <value>
                <fullName>Class Upgrade - Ineligible</fullName>
            </value>
            <value>
                <fullName>Cancelled in Error - Ineligible</fullName>
            </value>
            <value>
                <fullName>Ticketed - Interline/Codeshare Ineligible</fullName>
            </value>
            <value>
                <fullName>Qantas Error</fullName>
            </value>
            <value>
                <fullName>Commercial Waiver</fullName>
            </value>
            <value>
                <fullName>Seating and Baggage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Fulfilment__c/Case_Fulfilment__c.object-meta.xml
<CustomObject>
    <label>Fulfilment Status</label>
    <nameField>
        <displayFormat>CF-{000000}</displayFormat>
        <label>Case Fulfilment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilments Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Fulfilment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Fulfilment__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remark</fullName>
            </value>
            <value>
                <fullName>EMD Creation</fullName>
            </value>
            <value>
                <fullName>Payment Completion</fullName>
            </value>
            <value>
                <fullName>Ticketed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Fulfilment__c/fields/Fulfilment_Name__c.field-meta.xml
<CustomField>
    <fullName>Fulfilment_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fulfilment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Fulfilment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/QAC_Fulfillment_Status__mdt.object-meta.xml
<CustomObject>
    <description>This metadata is used to store the pre defined values as individual records in Fulfillment Status object at the time of &quot;Service Request&quot; case creation. Subtype1 field of the case decides what kind of records to be created based on the sequence field values in the metadata.</description>
    <label>QAC Fulfillment Status</label>
    <pluralLabel>QAC Fulfillment Status</pluralLabel>
</CustomObject>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Fulfillment_Message__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Message__c</fullName>
    <label>Fulfillment Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Status__c</fullName>
    <label>Fulfillment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Sequence_1__c.field-meta.xml
<CustomField>
    <fullName>Sequence_1__c</fullName>
    <label>Sequence 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Sequence_2__c.field-meta.xml
<CustomField>
    <fullName>Sequence_2__c</fullName>
    <label>Sequence 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Sequence_3__c.field-meta.xml
<CustomField>
    <fullName>Sequence_3__c</fullName>
    <label>Sequence 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Sequence_4__c.field-meta.xml
<CustomField>
    <fullName>Sequence_4__c</fullName>
    <label>Sequence 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Sequence_5__c.field-meta.xml
<CustomField>
    <fullName>Sequence_5__c</fullName>
    <label>Sequence 5</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Sequence_6__c.field-meta.xml
<CustomField>
    <fullName>Sequence_6__c</fullName>
    <label>Sequence 6</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Sequence_7__c.field-meta.xml
<CustomField>
    <fullName>Sequence_7__c</fullName>
    <label>Sequence 7</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Sequence_8__c.field-meta.xml
<CustomField>
    <fullName>Sequence_8__c</fullName>
    <label>Sequence 8</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Waiver_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Waiver_Sub_Type__c</fullName>
    <label>Waiver Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Fulfillment_Status__mdt/fields/Waiver_Type__c.field-meta.xml
<CustomField>
    <fullName>Waiver_Type__c</fullName>
    <label>Waiver Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QAC_caseFulfilmentHandler.cls
/*
 * Created By : Ajay Bharathan | TCS | Cloud Developer 
 * Purpose 1 : to create case fulfillment records based on custom metadata - QAC_Fulfillment_Status__mdt
 * Referred from 
    > Trigger : trgTradeSiteResponse
*/

public class QAC_caseFulfilmentHandler {
    
    // used in trgTradeSiteResponse trigger
    public static void autoCreateFulfillmentRecords(list<Case> newCases){
        // During Case Insert
        system.debug('inside MDT for FF');
        list<Case_Fulfilment__c> newFFlist = new list<Case_Fulfilment__c>();
        map<Id,Case> caseMap = new map<Id,Case>();
        Set<String> waiverTypes = new Set<String>();
        Set<String> waiverSubTypes = new Set<String>();
        
        Id CaseRTId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Service Request').getRecordTypeId();
        
        for(Case eachCase : newCases){
            if(eachCase.Id != null && eachCase.Origin == 'QAC Website' && eachCase.RecordTypeId == CaseRTId){
                if(String.isNotBlank(eachCase.Problem_Type__c)) /* && String.isNotBlank(eachCase.Waiver_Sub_Type__c) */
                {
                    waiverTypes.add(eachCase.Problem_Type__c);
                    waiverSubTypes.add(eachCase.Waiver_Sub_Type__c);
                    caseMap.put(eachCase.Id,eachCase);
                }
            }
        }
        doCaseFulfilmentCreation(caseMap,waiverTypes,waiverSubTypes);
    }
    
    public static void doCaseFulfilmentCreation(Map<Id,Case> myMap, Set<String> myWaiverTypes, Set<String> myWaiverSubTypes){
        
        list<Case_Fulfilment__c> myFFlist = new list<Case_Fulfilment__c>();
        Map<String,QAC_Fulfillment_Status__mdt> allFFMDTmap = new Map<String,QAC_Fulfillment_Status__mdt>();
        Map<String,list<String>> allFFName_SeqStringMap = new Map<String,list<String>>();
        String waivCombo = '', myCaseWaivCombo = '';
        
        if(!myWaiverTypes.isEmpty()) /* && !myWaiverSubTypes.isEmpty() */
        {
            for(QAC_Fulfillment_Status__mdt eachFFMDT : [Select MasterLabel,DeveloperName,Fulfillment_Message__c,
                                                         Fulfillment_Status__c,Waiver_Type__c,Waiver_Sub_Type__c,
                                                         Sequence_1__c,Sequence_2__c,Sequence_3__c,Sequence_4__c,
                                                         Sequence_5__c,Sequence_6__c,Sequence_7__c,Sequence_8__c 
                                                         from QAC_Fulfillment_Status__mdt
                                                         where Waiver_Type__c IN: myWaiverTypes AND Waiver_Sub_Type__c IN: myWaiverSubTypes])
            {
                if(eachFFMDT != null)
                {
                    waivCombo = eachFFMDT.Waiver_Type__c+'_'+eachFFMDT.Waiver_Sub_Type__c;
                    allFFMDTmap.put(waivCombo,eachFFMDT);
                    
                    list<String> seqString = new list<String>{eachFFMDT.Sequence_1__c,eachFFMDT.Sequence_2__c,
                                                                eachFFMDT.Sequence_3__c,eachFFMDT.Sequence_4__c,
                                                                eachFFMDT.Sequence_5__c,eachFFMDT.Sequence_6__c,
                                                                eachFFMDT.Sequence_7__c,eachFFMDT.Sequence_8__c};
                    Integer i=0;
                    while(i < seqString.size()){
                        if(seqString[i] == null)
                            seqString.remove(i);
                        else
                            i++;
                    }
                    system.debug('all seq**'+seqString);
                    allFFName_SeqStringMap.put(waivCombo,seqString);
                }                
            }
            
            if(!allFFMDTmap.isEmpty() && !allFFName_SeqStringMap.isEmpty() && !myMap.isEmpty())
            {
                system.debug('FFMDT map'+allFFMDTmap);
                system.debug('FFMDT Sequence map'+allFFName_SeqStringMap);
                
                for(Case eachCase : myMap.values())
                {
                    myCaseWaivCombo = eachCase.Problem_Type__c+'_'+eachCase.Waiver_Sub_Type__c;
                    if(eachCase.Problem_Type__c == allFFMDTmap.get(myCaseWaivCombo).Waiver_Type__c &&
                       eachCase.Waiver_Sub_Type__c == allFFMDTmap.get(myCaseWaivCombo).Waiver_Sub_Type__c)
                    {
                        for(String eachFFMDT_SeqString : allFFName_SeqStringMap.get(myCaseWaivCombo)){
                            Case_Fulfilment__c newFF = new Case_Fulfilment__c();
                            newFF.Fulfilment_Name__c = eachCase.Problem_Type__c;
                            newFF.Category__c = eachFFMDT_SeqString;
                            newFF.Case__c = eachCase.Id;
                            newFF.Status__c = allFFMDTmap.get(myCaseWaivCombo).Fulfillment_Status__c;
                            newFF.Message__c = allFFMDTmap.get(myCaseWaivCombo).Fulfillment_Message__c;
                            newFF.Timestamp__c = System.now();
                            myFFlist.add(newFF);
                        }
                    }
                }
            }
        }

        if(!myFFlist.isEmpty())
            insert myFFlist;
    }
}