force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>QCC: Created to show/store Issue Category.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Accommodation/Reimbursement of Expenses</fullName>
            </value>
            <value>
                <fullName>Account Queries</fullName>
            </value>
            <value>
                <fullName>Advertising</fullName>
            </value>
            <value>
                <fullName>Aircraft Condition</fullName>
            </value>
            <value>
                <fullName>Aircraft Schedule Change/Notification</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Airport Security</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Announcements</fullName>
            </value>
            <value>
                <fullName>AQIRE</fullName>
            </value>
            <value>
                <fullName>ARD Web</fullName>
            </value>
            <value>
                <fullName>Audits</fullName>
            </value>
            <value>
                <fullName>Award Bookings</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>BART Document</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Blue Prism</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Bounce Back</fullName>
            </value>
            <value>
                <fullName>Cabin Baggage</fullName>
            </value>
            <value>
                <fullName>Call outs</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation Fees</fullName>
            </value>
            <value>
                <fullName>Carbon Offset</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Charter Flights</fullName>
            </value>
            <value>
                <fullName>Chauffeur Drive</fullName>
            </value>
            <value>
                <fullName>Staff Assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>QCC: Created to show/store Case Group.</description>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Flight Disruptions</fullName>
            </value>
            <value>
                <fullName>Contact Centre</fullName>
            </value>
            <value>
                <fullName>Departure Airport</fullName>
            </value>
            <value>
                <fullName>Lounges</fullName>
            </value>
            <value>
                <fullName>Arrival Airport</fullName>
            </value>
            <value>
                <fullName>In-Flight</fullName>
            </value>
            <value>
                <fullName>Frequent Flyer</fullName>
            </value>
            <value>
                <fullName>Qantas.com</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Insurance letter</fullName>
            </value>
            <value>
                <fullName>Request Copy of Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Damaged Baggage</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Delayed Flight</fullName>
            </value>
            <value>
                <fullName>Delayed or Lost Baggage</fullName>
            </value>
            <value>
                <fullName>Flight Cancelled by Qantas</fullName>
            </value>
            <value>
                <fullName>Personal Property Lost In-flight</fullName>
            </value>
            <value>
                <fullName>Proof of Boarding or No Show</fullName>
            </value>
            <value>
                <fullName>Baggage Delivery Delayed Baggage</fullName>
            </value>
            <value>
                <fullName>Mid Range Repair</fullName>
            </value>
            <value>
                <fullName>Post Flight Survey</fullName>
            </value>
            <value>
                <fullName>Denial</fullName>
            </value>
            <value>
                <fullName>General Wear and Tear or removal of locks email template</fullName>
            </value>
            <value>
                <fullName>Mid Range Letter</fullName>
            </value>
            <value>
                <fullName>Finalisation</fullName>
            </value>
            <value>
                <fullName>Delayed Baggage</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Specific Needs</fullName>
            </value>
            <value>
                <fullName>EMD Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCCEmailTemplateSelectorTest.cls
@isTest
public with sharing class QCCEmailTemplateSelectorTest {
    @TestSetup
    static void makeData(){
        TestUtilityDataClassQantas.insertQantasConfigData();
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createRecoveryTriggerSetting());
        insert lsttrgStatus;
        List<Account> accList = TestUtilityDataClassQantas.getAccounts();
        List<Contact> conList = TestUtilityDataClassQantas.getContacts(accList);

        Case thecase = new Case();
        thecase.AccountId = accList[0].Id;
        thecase.ContactId = conList[0].Id;
        thecase.RecordTypeId = [SELECT Id,Name, SobjectType FROM RecordType WHERE SobjectType ='Case' AND Name = 'CCC Complaints'].Id;
        thecase.Origin='Email';
        thecase.Description='adsf';
        thecase.Status='New';
        thecase.Type='Complaint';
        thecase.Group__c='Contact Centre';
        thecase.Category__c='Staff Assistance';

        insert thecase;

    }
    
    @isTest
    static void testGetEmailTemplates(){
        List<List<EmailTemplate>> theEmailTemplateList;
        List<Case> theCasesList = [SELECT Id FROM Case Limit 1];
        List<Id> caseIds = new List<Id>{theCasesList[0].Id};
        Test.startTest();
            theEmailTemplateList = QCCEmailTemplateSelector.getEmailTemplates(caseIds);
        Test.stopTest();
        System.debug('===in test method theEmailTemplateList.size===='  + theEmailTemplateList.size());
        System.assert(theEmailTemplateList != null);

    }
}