force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>QCC: Created to show/store Issue Category.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Accommodation/Reimbursement of Expenses</fullName>
            </value>
            <value>
                <fullName>Account Queries</fullName>
            </value>
            <value>
                <fullName>Advertising</fullName>
            </value>
            <value>
                <fullName>Aircraft Condition</fullName>
            </value>
            <value>
                <fullName>Aircraft Schedule Change/Notification</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Airport Security</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Announcements</fullName>
            </value>
            <value>
                <fullName>AQIRE</fullName>
            </value>
            <value>
                <fullName>ARD Web</fullName>
            </value>
            <value>
                <fullName>Audits</fullName>
            </value>
            <value>
                <fullName>Award Bookings</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>BART Document</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Blue Prism</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Bounce Back</fullName>
            </value>
            <value>
                <fullName>Cabin Baggage</fullName>
            </value>
            <value>
                <fullName>Call outs</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation Fees</fullName>
            </value>
            <value>
                <fullName>Carbon Offset</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Charter Flights</fullName>
            </value>
            <value>
                <fullName>Chauffeur Drive</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>QCC: Created to show/store Case Group.</description>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Flight Disruptions</fullName>
            </value>
            <value>
                <fullName>Contact Centre</fullName>
            </value>
            <value>
                <fullName>Departure Airport</fullName>
            </value>
            <value>
                <fullName>Lounges</fullName>
            </value>
            <value>
                <fullName>Arrival Airport</fullName>
            </value>
            <value>
                <fullName>In-Flight</fullName>
            </value>
            <value>
                <fullName>Frequent Flyer</fullName>
            </value>
            <value>
                <fullName>Qantas.com</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Insurance letter</fullName>
            </value>
            <value>
                <fullName>Request Copy of Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Damaged Baggage</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Delayed Flight</fullName>
            </value>
            <value>
                <fullName>Delayed or Lost Baggage</fullName>
            </value>
            <value>
                <fullName>Flight Cancelled by Qantas</fullName>
            </value>
            <value>
                <fullName>Personal Property Lost In-flight</fullName>
            </value>
            <value>
                <fullName>Proof of Boarding or No Show</fullName>
            </value>
            <value>
                <fullName>Baggage Delivery Delayed Baggage</fullName>
            </value>
            <value>
                <fullName>Mid Range Repair</fullName>
            </value>
            <value>
                <fullName>Post Flight Survey</fullName>
            </value>
            <value>
                <fullName>Denial</fullName>
            </value>
            <value>
                <fullName>General Wear and Tear or removal of locks email template</fullName>
            </value>
            <value>
                <fullName>Mid Range Letter</fullName>
            </value>
            <value>
                <fullName>Finalisation</fullName>
            </value>
            <value>
                <fullName>Delayed Baggage</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Specific Needs</fullName>
            </value>
            <value>
                <fullName>EMD Refund</fullName>
            </value>
            <value>
                <fullName>NDC Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <description>QCC: Built to show/store Sub Category.</description>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Beverage Payment</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Menu Select Meal not Provided</fullName>
            </value>
            <value>
                <fullName>Special Meal Quality/Provision</fullName>
            </value>
            <value>
                <fullName>Q Streaming</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Functionality</fullName>
            </value>
            <value>
                <fullName>Bassinet Availability</fullName>
            </value>
            <value>
                <fullName>Comfort/Functionality</fullName>
            </value>
            <value>
                <fullName>Seating Allocation</fullName>
            </value>
            <value>
                <fullName>Prepaid seat not provided</fullName>
            </value>
            <value>
                <fullName>Fees/Cost/Price</fullName>
            </value>
            <value>
                <fullName>In-Flight Seating</fullName>
            </value>
            <value>
                <fullName>Staff Assistance</fullName>
            </value>
            <value>
                <fullName>Poor Communication</fullName>
            </value>
            <value>
                <fullName>Agent booking</fullName>
            </value>
            <value>
                <fullName>Aircraft cleanliness</fullName>
            </value>
            <value>
                <fullName>Aircraft Type</fullName>
            </value>
            <value>
                <fullName>Airport co-ordination</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Applied correctly</fullName>
            </value>
            <value>
                <fullName>Applied incorrectly</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Bid Now Product</fullName>
            </value>
            <value>
                <fullName>Boarding Process</fullName>
            </value>
            <value>
                <fullName>Booking Errors</fullName>
            </value>
            <value>
                <fullName>Cabin baggage policy</fullName>
            </value>
            <value>
                <fullName>Car did not arrive</fullName>
            </value>
            <value>
                <fullName>Catering Quality</fullName>
            </value>
            <value>
                <fullName>Unable to view commission offer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Procurement/Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QAC_CaseReassignmentScheduler_Test.cls
/*----------------------------------------------------------------------------------------------------------------------
*******************************************************************
History
15-Jul-2026 Jonathan-Capgemini          RBAC SND
-----------------------------------------------------------------------------------------------------------------------*/
@isTest
public class QAC_CaseReassignmentScheduler_Test {

     @testSetup
    public static void setup() {
       
        
        String orgId = UserInfo.getOrganizationId();
        String sandboxName = UserInfo.getUserName().substringAfterLast('.au');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + randomInt;
        Profile pf = [Select Id from Profile where Name = 'Qantas Agency Connect and Agency Sales'];//RBAC SND - Profile Update
        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.Email = uniqueName + '@test' + sandboxName + '.com'; 
        u.CompanyName = 'test.com';
        u.Title = 'Test User';
        u.Username = uniqueName + '@test' + sandboxName + '.com'; 
        u.Alias = 'testuser';
        u.CommunityNickname = 'Test User';
        u.TimeZoneSidKey = 'Australia/Sydney';
        u.LocaleSidKey = 'en_AU';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = pf.Id;
        u.LanguageLocaleKey = 'en_US';
        insert u;
        
        //RBAC SND - Permission Set Update
        System.runAs(new User(Id = UserInfo.getUserId())) {
            List<Id> permissionSetIds = TestUtilityDataClassQantas.getPermissionSetIds('SND_Base_Permissions,SND_Non_GSA_Permission,SND_Agency_Connect_Support_Permissions');
            List<PermissionSetAssignment> psaList = TestUtilityDataClassQantas.createPermissionSetAssignments(u.Id,permissionSetIds);
        }
        
        String accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency Account').getRecordTypeId();
        String conRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        String caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('QAC Contact Us Support').getRecordTypeId();
        
        TestUtilityDataClassQantas.insertQantasConfigData();
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType();
        TestUtilityDataClassQantas.enableTriggers();
        
        Account testacc = new Account(Name='Test Tcs Account',Active__c = true,Type = 'Freight-Country',RecordTypeId = accRTId);
        insert testacc;
        
        Contact testcon = new Contact(FirstName='Bob1',LastName='Test2',AccountId=testacc.id,Function__c = 'IT',Business_Types__c = 'Freight',Email = 'abc@test.com',RecordTypeId =conRTId);
        insert testcon;
        system.debug('Before case create');
        
        List<Case> caseList = new List<Case>();
        
        Case newCase = new Case(AccountId = testacc.id, RecordTypeId = caseRTId,Status = 'Open',ContactId=testcon.id,Subject = 'Test01FRT',Description = 'some desc',
                                 Type = 'NDC',Group__c = 'NDC Portal', Category__c = 'Qantas NDC offers support', Sub_Category__c = 'Unable to view commission offer',
                                ownerId = u.Id
                               ); 
        insert newCase;
        	
            
        }
    
    
    @isTest 
    public static void executeTest()
    {
        Test.startTest();
        	Case c = [Select id,ownerId from case limit 1];
        	c.ownerId = UserInfo.getUserId();
            update c;
            System.schedule('QAC_CaseReassignmentSchedulerTest','0 0 * * * ?',new QAC_CaseReassignmentScheduler());
        Test.stopTest();
    }
    
    
    @isTest 
    public static void userLogoutTest()
    {
       Test.startTest();
       User u1 = [SELECT Id, UserName FROM User WHERE FirstName = 'Test' limit 1];
        Case c = [Select id,ownerId from case limit 1];
        	c.ownerId = u1.Id;
            update c;
       LogoutEventStream event = new LogoutEventStream();
       event.UserName = u1.UserName;
       event.UserId = u1.Id;
       EventBus.publish(event);
       Test.stopTest(); 
    }
}