force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>QCC: Created to show/store Issue Category.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Accommodation/Reimbursement of Expenses</fullName>
            </value>
            <value>
                <fullName>Account Queries</fullName>
            </value>
            <value>
                <fullName>Advertising</fullName>
            </value>
            <value>
                <fullName>Aircraft Condition</fullName>
            </value>
            <value>
                <fullName>Aircraft Schedule Change/Notification</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Airport Security</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Announcements</fullName>
            </value>
            <value>
                <fullName>AQIRE</fullName>
            </value>
            <value>
                <fullName>ARD Web</fullName>
            </value>
            <value>
                <fullName>Audits</fullName>
            </value>
            <value>
                <fullName>Award Bookings</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>BART Document</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Blue Prism</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Bounce Back</fullName>
            </value>
            <value>
                <fullName>Cabin Baggage</fullName>
            </value>
            <value>
                <fullName>Call outs</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation Fees</fullName>
            </value>
            <value>
                <fullName>Carbon Offset</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Charter Flights</fullName>
            </value>
            <value>
                <fullName>Chauffeur Drive</fullName>
            </value>
            <value>
                <fullName>Facilities/Signage</fullName>
            </value>
            <value>
                <fullName>Lounges</fullName>
            </value>
            <value>
                <fullName>Specific Needs</fullName>
            </value>
            <value>
                <fullName>Staff Assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Used to capture the new user&apos;s first name.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s first name, for whom the request is being logged.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>QCC: Created to show/store Case Group.</description>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Flight Disruptions</fullName>
            </value>
            <value>
                <fullName>Contact Centre</fullName>
            </value>
            <value>
                <fullName>Departure Airport</fullName>
            </value>
            <value>
                <fullName>Lounges</fullName>
            </value>
            <value>
                <fullName>Arrival Airport</fullName>
            </value>
            <value>
                <fullName>In-Flight</fullName>
            </value>
            <value>
                <fullName>Frequent Flyer</fullName>
            </value>
            <value>
                <fullName>Qantas.com</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Insurance letter</fullName>
            </value>
            <value>
                <fullName>Request Copy of Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Damaged Baggage</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Delayed Flight</fullName>
            </value>
            <value>
                <fullName>Delayed or Lost Baggage</fullName>
            </value>
            <value>
                <fullName>Flight Cancelled by Qantas</fullName>
            </value>
            <value>
                <fullName>Personal Property Lost In-flight</fullName>
            </value>
            <value>
                <fullName>Proof of Boarding or No Show</fullName>
            </value>
            <value>
                <fullName>Baggage Delivery Delayed Baggage</fullName>
            </value>
            <value>
                <fullName>Mid Range Repair</fullName>
            </value>
            <value>
                <fullName>Post Flight Survey</fullName>
            </value>
            <value>
                <fullName>Denial</fullName>
            </value>
            <value>
                <fullName>General Wear and Tear or removal of locks email template</fullName>
            </value>
            <value>
                <fullName>Mid Range Letter</fullName>
            </value>
            <value>
                <fullName>Finalisation</fullName>
            </value>
            <value>
                <fullName>Delayed Baggage</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Specific Needs</fullName>
            </value>
            <value>
                <fullName>EMD Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>To capture the new user&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s last name, for whom the request is being logged.</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Received_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>QCC: Created to show/store Case Received Date.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Received Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <description>QCC: Built to show/store Sub Category.</description>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Beverage Payment</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Menu Select Meal not Provided</fullName>
            </value>
            <value>
                <fullName>Special Meal Quality/Provision</fullName>
            </value>
            <value>
                <fullName>Q Streaming</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Functionality</fullName>
            </value>
            <value>
                <fullName>Bassinet Availability</fullName>
            </value>
            <value>
                <fullName>Comfort/Functionality</fullName>
            </value>
            <value>
                <fullName>Seating Allocation</fullName>
            </value>
            <value>
                <fullName>Prepaid seat not provided</fullName>
            </value>
            <value>
                <fullName>Fees/Cost/Price</fullName>
            </value>
            <value>
                <fullName>In-Flight Seating</fullName>
            </value>
            <value>
                <fullName>Staff Assistance</fullName>
            </value>
            <value>
                <fullName>Poor Communication</fullName>
            </value>
            <value>
                <fullName>Agent booking</fullName>
            </value>
            <value>
                <fullName>Aircraft cleanliness</fullName>
            </value>
            <value>
                <fullName>Aircraft Type</fullName>
            </value>
            <value>
                <fullName>Airport co-ordination</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Applied correctly</fullName>
            </value>
            <value>
                <fullName>Applied incorrectly</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Bid Now Product</fullName>
            </value>
            <value>
                <fullName>Boarding Process</fullName>
            </value>
            <value>
                <fullName>Booking Errors</fullName>
            </value>
            <value>
                <fullName>Cabin baggage policy</fullName>
            </value>
            <value>
                <fullName>Car did not arrive</fullName>
            </value>
            <value>
                <fullName>Catering Quality</fullName>
            </value>
            <value>
                <fullName>Lounges</fullName>
            </value>
            <value>
                <fullName>Specific Needs</fullName>
            </value>
            <value>
                <fullName>Wait times</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CCC_Medical.recordType-meta.xml
<RecordType>
    <fullName>CCC_Medical</fullName>
    <active>true</active>
    <businessProcess>QCC Support Process with PRStatus</businessProcess>
    <label>CCC Medical</label>
</RecordType>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Value__c.field-meta.xml
<CustomField>
    <fullName>Config_Value__c</fullName>
    <description>Text values used in the code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QualtricsSurveyNotification_Test.cls
/***********************************************************************************************************************************

Description: Test class for Qualtrics Survey notification to the end customer. 

History:
======================================================================================================================
Name                          Description                                           Tag
======================================================================================================================
Yuvaraj MV                    Qualtrics Survey notification to the end customer     T01
Created Date    : 29/04/19 (DD/MM/YYYY)

MainClass       : QualtricsSurveyNotification
**********************************************************************************************************************************/
@isTest
public class QualtricsSurveyNotification_Test 
{
    /*----------------------------------------------------------------------------------------------      
    Method Name:        dataSetup
    Description:        Datasetup for QantasConfigdata
    ----------------------------------------------------------------------------------------------*/
    @testsetup
    public static void dataSetup()
    {   
        QantasConfigData__c qcd = new QantasConfigData__c(Name = 'Log Exception Logs Rec Type',Config_Value__c = 'Exception Logs');
        insert qcd;
        
      /*  Trigger_Status__c caseQualtricsSurvey = new Trigger_Status__c();
        caseQualtricsSurvey.Name = 'QualtricsSurvey';
        caseQualtricsSurvey.Active__c = true;
        insert caseQualtricsSurvey; */
        
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createRecoveryTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createEventTriggerSetting());
        insert lsttrgStatus;
        TestUtilityDataClassQantas.insertQantasConfigData();
        List<Qantas_API__c> lstQantas = TestUtilityDataClassQantas.createQantasAPI();
        insert lstQantas;
        
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Integration Logs Rec Type','Integration Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('RecoveryStatusApproved','Approved'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_FligjtCode Domestic','Domestic'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_EmergencyOutcomeDomestic','Emergency Expense - Domestic Stage'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_FligjtCode International','International'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_EmergencyOutcomeInternational','   Emergency Expense - International Stage'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_EmergencyOutcomeNotEligible','Not Eligible for Emergency Expenses'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseStatusClosed','Closed'));
        
        insert lstConfigData;

    }
    //Insert caserecord
    public static testmethod void testQualtricsSurvey()
    {  
        id cccComplaint = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CCC_Complaints').getRecordTypeId();
        
        Trigger_Status__c  tgrStatus = new Trigger_Status__c();
        tgrStatus.Name = 'QualtricsSurvey';
        tgrStatus.Active__c = true;
        insert tgrStatus;
        
        List<case> caseList = new List<case>();
        
        case caseExcl = new case();
        caseExcl.RecordTypeId = cccComplaint;
        caseExcl.Group__c = 'Lounges';
        caseExcl.Category__c = 'Facilities/Signage';
        caseExcl.Sub_Category__c = 'Specific Needs';
        caseExcl.Type = 'Complaint';
        caseExcl.Status = 'Received';
        caseExcl.Origin = 'Email';
        caseExcl.Received_Date__c = datetime.now();
        caseExcl.Description = 'Testing Qualtrics';
        caseExcl.First_Name__c = 'Qualtricsname1';
        caseExcl.Last_Name__c = 'lastname1';
        caseExcl.Contact_Email__c = 'axbc1@cmgc.com';
        caseList.add(caseExcl);
        
        case caseIncl = new case();
        caseIncl.RecordTypeId = cccComplaint;
        caseIncl.Group__c = 'Lounges';
        caseIncl.Category__c = 'Staff Assistance';
        caseIncl.Sub_Category__c = 'Wait times';
        caseIncl.Type = 'Complaint';
        caseIncl.Status = 'Received';
        caseIncl.Origin = 'Email';
        caseIncl.Received_Date__c = datetime.now();
        caseIncl.Description = 'Testing Qualtrics';
        caseIncl.First_Name__c = 'Qualtricsname2';
        caseIncl.Last_Name__c = 'lastname2';
        caseIncl.Contact_Email__c = 'axbc2@cmgc.com';
        caseList.add(caseIncl);
        
        Test.startTest();
        try{
        insert caseList;
        }
        catch(Exception ex){
          system.assert(ex.getTypeName() == 'System.DmlException', 'Exception Occured');   
        }
        Test.stopTest();
        system.assert(caseList[0].Id != Null, 'Case is not Inserted');
    }
    
    //ExceptionHandling
    public static testmethod void testException()
    {   
        id cccMedical = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CCC_Medical').getRecordTypeId(); 

            
            List<case> caseList = new List<case>();
            
            case caseExcl = new case();
            caseExcl.RecordTypeId = cccMedical;
            caseExcl.Group__c = 'Lounges';
            caseExcl.Category__c = 'Facilities/Signage';
            caseExcl.Sub_Category__c = 'Specific Needs';
            caseExcl.Type = 'Complaint';
            caseExcl.Status = 'Received';
            caseExcl.Origin = 'Email';
            caseExcl.Received_Date__c = datetime.now();
            caseExcl.Description = 'Testing Qualtrics';
            caseExcl.First_Name__c = 'Qualtricsname1';
            caseExcl.Last_Name__c = 'lastname1';
            caseExcl.Contact_Email__c = 'axbc1@cmgc.com';
            
            caseList.add(caseExcl); 
            Test.startTest();
            try{
                insert caseList;
            }
            catch(Exception ex){
               system.assert(ex.getTypeName() == 'System.DmlException', 'Exception Occured');
            }
            Test.stopTest();

    }
}