force-app/main/default/objects/Case/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SSU__c.field-meta.xml
<CustomField>
    <fullName>SSU__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Corporate: Special Service Unit -This person&apos;s travel / relationship is overseen by the special service unit</inlineHelpText>
    <label>SSU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/To_Address__c.field-meta.xml
<CustomField>
    <fullName>To_Address__c</fullName>
    <label>To Address</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>casaqfin@emirates.com</fullName>
                <label>CASA - QF (IN) &lt;casaqfin@emirates.com&gt;</label>
            </value>
            <value>
                <fullName>customercare@qantastravelmoney.com</fullName>
                <label>Cash Card&lt;customercare@qantastravelmoney.com&gt;</label>
            </value>
            <value>
                <fullName>IFSSUPPORT@qantas.com.au</fullName>
                <label>Catering SHR IFS SUPPORT&lt;IFSSUPPORT@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>ccexec@qantas.com.au</fullName>
                <label>Customer Care Advocate Team  &lt;ccexec@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>customerjourney@qantas.com.au</fullName>
                <label>SHR Customer Journey &lt;customerjourney@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>EU Compensation EC261/2004 &lt;EUDISPUTERESOLUTION@qantas.com.au&gt;</fullName>
                <label>EUDISPUTERESOLUTION@qantas.com.au</label>
            </value>
            <value>
                <fullName>foodtech@qantas.com.au</fullName>
                <label>Food Poisoning Investigations &lt;foodtech@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>frequent_flyer@qantas.com.au</fullName>
                <label>Frequent Flyer &lt;frequent_flyer@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>entertainment@qantas.com.au</fullName>
                <label>Inflight Entertainment (IFE)&lt;entertainment@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>exec.case@jetstar.com</fullName>
                <label>Jetstar Executive Relations &lt;exec.case@jetstar.com&gt;</label>
            </value>
            <value>
                <fullName>QFCC.Escalations@Jetstar.com</fullName>
                <label>Jetstar High Priority &lt;QFCC.Escalations@Jetstar.com&gt;</label>
            </value>
            <value>
                <fullName>rania.jones@qantas.com.au</fullName>
                <label>Legal Issues-Rania Jones  &lt;rania.jones@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>publicaf@qantas.com.au</fullName>
                <label>Media &lt;publicaf@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>#Media_Team@qantas.com.au</fullName>
                <label>Media - Distribution List &lt;#Media_Team@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>onlinesalesqueries@qantas.com.au</fullName>
                <label>Onlines Sales Queries &lt;onlinesalesqueries@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>hello@qantasassure.com</fullName>
                <label>QantasAssure Insurance&lt;hello@qantasassure.com&gt;</label>
            </value>
            <value>
                <fullName>MobileApp@qantas.com.au</fullName>
                <label>QF Mobile App Support &lt;MobileApp@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>ancillaries@qantas.com.au</fullName>
                <label>SHR Ancillaries &lt;ancillaries@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>shrawardsproductspecialists@qantasloyalty.com</fullName>
                <label>SHR AwardsProductSpecialists  &lt;shrawardsproductspecialists@qantasloyalty.com&gt;</label>
            </value>
            <value>
                <fullName>cabincrewfeedback@qantas.com.au</fullName>
                <label>SHR CABIN CREW FEEDBACK &lt;cabincrewfeedback@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>shrccreq@qantas.com.au</fullName>
                <label>Shr CC REQ - Admin &lt;shrccreq@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>loyaltycustomerservice@qantasloyalty.com.au</fullName>
                <label>SHR LOYALTY CUSTOMER SERVICE &lt;loyaltycustomerservice@qantasloyalty.com.au&gt;</label>
            </value>
            <value>
                <fullName>PICS@qantas.com.au</fullName>
                <label>Shr PICS &lt;PICS@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>platinumone@qantas.com.au</fullName>
                <label>SHR PLATINUM ONE &lt;platinumone@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>Salesinitatives@qantas.com.au</fullName>
                <label>Shr Sales Initiatives &lt;Salesinitatives@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>security@qantas.com.au</fullName>
                <label>Shr Security &lt;security@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>socialmediaakl@qantas.com.au</fullName>
                <label>SHR Social Media AKL &lt;socialmediaakl@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>specialhandling@qantas.com.au</fullName>
                <label>SHR SPHL &lt;specialhandling@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>sponsorships@qantas.com.au</fullName>
                <label>Sponsorship Requests &lt;sponsorships@qantas.com.au&gt;</label>
            </value>
            <value>
                <fullName>paxcti@qantas.com.au</fullName>
                <label>Tax invoices &lt;paxcti@qantas.com.au&gt;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_SpecificNeedsEmailTest.cls
/*********************************************************************************
Name         : QCC_SpecificNeedsEmailTest
Created By   : Rafael Escuadra
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 13 March 2020
Usages       : This class is used for the code coverage of the apex class below:
- QCC_SpecificNeedsMailInvocable, QCC_SpecificNeedsSendMailQueueable

Modified By : Venkata Suresh Kumar (TCS Team), 19-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method.
*********************************************************************************/
@isTest
public class QCC_SpecificNeedsEmailTest {
    @testSetUp
    public static void setupTestData(){
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        List<Trigger_Status__c> caseCustomSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusCase', null, null, null, null);
        insert caseCustomSettingList;
        
        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        List<Contact> contactList = new List<Contact>();
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.RecordTypeId = contactRecordTypeId;
        contactRecord.Frequent_Flyer_Number__c = '1234567890';
        contactRecord.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord.SSU__c = true;
        insert contactRecord;
        
        //Create test data for Case object
        String caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Specific Needs').getRecordTypeId();
        
        system.debug('caseRecordTypeId'+caseRecordTypeId);
        system.debug('accountRecord.Id'+accountRecord.Id);
        system.debug('contactRecord.Id'+contactRecord.Id);
        Case caseRecord = QCC_TestDataFactory.createCaseTestData(accountRecord.Id, contactRecord.Id);
        caseRecord.RecordTypeId = caseRecordTypeId;
        caseRecord.Subject = 'TESTSUBJECT';
        caseRecord.Type = 'Mobility Aid';
        // caseRecord.Origin = 'Qantas.com';
        caseRecord.Contact_Email__c = 'ToEmailRecord@qantas.com.au';
        caseRecord.Description = 'test';
        insert caseRecord;
        
        EmailMessage email=new EmailMessage(FromAddress='FromEmailRecord@qantas.com.au',To_Address__c='ToEmailRecord@qantas.com.au',HtmlBody='This is an email for test class',MessageDate=system.now(),ParentId=caseRecord.id,subject='Qantas Freight Customer Support – Ref No ' + caseRecord.casenumber, RelatedToId =caseRecord.id, status='0');
        insert email;      
    }
    
    static testmethod void sendEmailTest(){
        test.startTest();
        Case caseRec = [SELECT Id, Contact_email__c FROM Case LIMIT 1];
        system.debug('case'+caseRec);
        EmailMessage emailRec= [SELECT id, parentId,To_Address__c From EmailMessage LIMIT 1];
        system.debug('EmailMessage'+emailRec);
        test.stopTest(); 
        
        System.assert(caseRec.Id == emailRec.parentID);
        System.assert(caseRec.contact_email__c == emailRec.To_Address__c);
    } 
}