force-app/main/default/objects/Case/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Used to capture the new user&apos;s first name.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s first name, for whom the request is being logged.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>To capture the new user&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s last name, for whom the request is being logged.</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/qcc_SearchTabAssociateContactTest.cls
/*****************************************************************************************
* Created By		Navpreet Kaur | TCS | Developer 
* Purpose			Test class for qcc_SearchTabAssociateContact
* Modified Date		20/11/23 (DD/MM/YYYY)
* Modified By		
* JIRA				CRM-6910 
******************************************************************************************/
@isTest
public with sharing class qcc_SearchTabAssociateContactTest 
{
	    @isTest
    	static void associateContactToCaseTest()
        { 
       		String caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CCC Voice').getRecordTypeId();
            String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        
              //Set Custom Settings for Trigger_Status__c Custom settings
            List<Trigger_Status__c> customSettingTriggerStatusLists = QCC_TestDataFactory.createTriggerStatusData();
            insert customSettingTriggerStatusLists;
            List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createCaseTriggerSetting();
            for(Trigger_Status__c ts : lsttrgStatus){
                ts.Active__c = false;
            }
           
            insert lsttrgStatus;
        
        	Case newCase=new Case(subject='Test Case',recordtypeid=caseRecordTypeId,First_Name__c='test',Last_Name__c='contact',Contact_Email__c='test.contact@qantas.com.au',Contact_Phone__c='+61465776556');
        	insert newCase;
        	Contact newCont=new Contact(recordtypeid=contactRecordTypeId,firstname='TestCont',lastname='ContCont',email='test.email@qantas.com',phone='87564857487');
            insert newCont;
        
          	 test.starttest();
             Boolean getReturn=	qcc_SearchTabAssociateContact.associateContact(newCase.id,newCont.id);
             getReturn=	qcc_SearchTabAssociateContact.associateContact(newCase.id,newCont.id);
            system.assert(true,getReturn);
            test.stoptest();
    	}
}