force-app/main/default/objects/Case/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Used to capture the new user&apos;s first name.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s first name, for whom the request is being logged.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>To capture the new user&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s last name, for whom the request is being logged.</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QCC_Data_Table__mdt/QCC_Data_Table__mdt.object-meta.xml
<CustomObject>
    <description>Dynamically Columns to the Data Table
Used in Lookup PNR popup, Case Search Results, Cases with same Contact Details</description>
    <label>QCC Data Table</label>
    <pluralLabel>QCC Data Table</pluralLabel>
</CustomObject>

force-app/main/default/objects/QCC_Data_Table__mdt/fields/ComponentName__c.field-meta.xml
<CustomField>
    <fullName>ComponentName__c</fullName>
    <description>QCC: Component name</description>
    <label>Component Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QCC_PNRSearch</fullName>
            </value>
            <value>
                <fullName>QCC_CaseSearchResult</fullName>
            </value>
            <value>
                <fullName>QCC_PossibleRelatedCases</fullName>
            </value>
            <value>
                <fullName>QCC_AddEventstoGlobalEvent</fullName>
            </value>
            <value>
                <fullName>QCC_AddEventstoGlobalHeadsUpEvent</fullName>
            </value>
            <value>
                <fullName>QCC_CAPBookingDetail</fullName>
                <isActive>false</isActive>
                <label>QCC_CAPBookingDetail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QCC_Data_Table__mdt/fields/FieldAPI__c.field-meta.xml
<CustomField>
    <fullName>FieldAPI__c</fullName>
    <description>QCC: Wrapper Value or Field API Value</description>
    <label>FieldAPI</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_Data_Table__mdt/fields/FieldLabel__c.field-meta.xml
<CustomField>
    <fullName>FieldLabel__c</fullName>
    <description>QCC: Field Label or Wrapper Label</description>
    <label>Field Label</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_Data_Table__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>QCC: Order  of the column</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QCC_Data_Table__mdt/fields/Sortable__c.field-meta.xml
<CustomField>
    <fullName>Sortable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Determine if the table can be sortable using this column</description>
    <label>Sortable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Data_Table__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>QCC: Data type of the field. To be displayed.</description>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>QCC: Used to store the email of the contact for QF Wine/Hotel vouchers</description>
    <formula>Case_Number__r.Contact_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: The status of the recovery</description>
    <label>Recovery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Further Action Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replaced Recovery</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submit for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalisation Declined</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>QCC: Created to show/store Type of goodwill given to customer.</description>
    <label>Recovery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qantas Points</fullName>
            </value>
            <value>
                <fullName>Payment (EFT)</fullName>
            </value>
            <value>
                <fullName>Payment (Credit Card)</fullName>
            </value>
            <value>
                <fullName>Travel vouchers</fullName>
                <label>Travel Vouchers</label>
            </value>
            <value>
                <fullName>Lounge Passes</fullName>
            </value>
            <value>
                <fullName>Bag Replacement</fullName>
            </value>
            <value>
                <fullName>Bag Repair</fullName>
            </value>
            <value>
                <fullName>No Goodwill</fullName>
            </value>
            <value>
                <fullName>Ticket Refund EFT</fullName>
            </value>
            <value>
                <fullName>Cover Refund</fullName>
            </value>
            <value>
                <fullName>First Lounge Pass</fullName>
                <label>First Lounge Pass (CCAT Only)</label>
            </value>
            <value>
                <fullName>Space available upgrade</fullName>
                <label>Space Available Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>Firm space upgrade</fullName>
                <label>Firm Space Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>QF_HOTEL_voucher</fullName>
            </value>
            <value>
                <fullName>QF_WINE_voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QCC_PNRSearchController.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Praveen Sampath
Company:       Capgemini
Description:   Customer Search using PNR
Inputs:
Test Class:     
************************************************************************************************
History
************************************************************************************************
03-Aug-2018      Praveen Sampath               Initial Design
28-Feb-2023      Jamie Wang                    invokePNRSearchWithoutLastName 
-----------------------------------------------------------------------------------------------------------------------*/
public without sharing class QCC_PNRSearchController {
    /*--------------------------------------------------------------------------------------      
    Method Name:        invokePNRSearch
    Description:        CAP PNR Search  
    Parameter:          PNR and Last Name
    --------------------------------------------------------------------------------------*/ 
    @AuraEnabled
    public static String invokePNRSearch(String pnr, String lastName){
        QCC_PNRPassengerInfoWrapper response;
        try {
            pnr = QCC_GenericUtils.doTrim(pnr);
            lastName = QCC_GenericUtils.doTrim(lastName);
            lastName = EncodingUtil.urlEncode(lastName, 'UTF-8').replaceAll('\\+','%20'); 
            String passengers;
            
            String token = QCC_GenericUtils.getCAPValidToken('QCC_BookingToken');
            system.debug('token####'+token);
            response = QCC_InvokeCAPAPI.invokePNRPassengerInfoCAPAPI(pnr, token, lastName);
            
            //response = (QCC_PNRPassengerInfoWrapper)JSON.deserialize('{"booking":{"reloc":"5ZE8Z4","travelPlanId":"561451371617264","bookingId":"561451371617264","creationDate":"13/07/2023","groupName":null,"groupUnassignedPassengerQty":null,"currentPassengerQuantity":"1","lastUpdatedTimeStamp":"13/07/2023 23:13:00","passengers":[{"passengerId":"782655084027381","passengerTattoo":"2","parentPassengerId":null,"ageCategoryCode":"A","typeCode":null,"passengerWithInfantIndicator":"N","firstName":"TEST","lastName":"XXXXXXXXXXUM","prefix":"MR","genderTypeCode":"M","birthDate":null,"age":null,"birthCity":null,"birthCountry":null,"uci":"510692340001839A","staffTravelType":null,"additionalText":null,"smeId":null,"corpId":null,"cemCustId":null,"qantasFFNo":"0006142208"}]}}', QCC_PNRPassengerInfoWrapper.class);
            system.debug('response###'+response);
            if(response != Null){
                QCC_PNRPassengerInfoWrapper.Booking booking = response.booking;
                if(booking != Null && booking.passengers != Null){
                    List<QCC_PNRPassengerInfoWrapper.Passengers> lstPas = new List<QCC_PNRPassengerInfoWrapper.Passengers>();
                    for(QCC_PNRPassengerInfoWrapper.Passengers pas: booking.passengers){
                        if(String.isBlank(pas.qantasFFNo )){
                            //pas.firstName = pas.firstName.substringBefore(' '); Commented to consider the middle names for existing contact search
                      
                            lstPas.add(pas);
                        }else{
                             lstPas.add(pas);
                        }
                    }
                    passengers = Json.serialize(lstPas);
                }
            }
            system.debug('passengers###'+passengers);
            if(String.isBlank(passengers) ){
                AuraHandledException ltEX = new AuraHandledException('');
                ltEX.setMessage(Label.QCC_NoValue);
                throw ltEX; 
            }
            
            return passengers;
        }catch(Exception ex){
            system.debug('Exception###'+ex);
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC - Customer Search', 'QCC_PNRSearchController', 
                                    'invokePNRSearch', String.valueOf(response), String.valueOf(''), true,'', ex);
            AuraHandledException ltEX = new AuraHandledException(ex.getMessage());
            throw ltEX;
        }   
    }
    /*--------------------------------------------------------------------------------------      
    Method Name:        invokePNRSearchWithoutLastName
    Description:        CAP PNR Search  
    Parameter:          PNR , creation Date
    Author:             Jamie Wang
    --------------------------------------------------------------------------------------*/ 
    @AuraEnabled
    public static String invokePNRSearchWithoutLastName(String pnr , String creationDate, Boolean archivalData){
        QCC_PNRPassengerInfoWrapper response;
        try {
            pnr = QCC_GenericUtils.doTrim(pnr);
            // lastName = QCC_GenericUtils.doTrim(lastName);
            // lastName = EncodingUtil.urlEncode(lastName, 'UTF-8').replaceAll('\\+','%20'); 
            String passengers;
            String archival = String.valueOf(archivalData);
            String token = QCC_GenericUtils.getCAPValidToken('QCC_BookingToken');
            system.debug('token####'+token);
            response = QCC_InvokeCAPAPI.invokePNRPassengerInfoCAPAPI(pnr, creationDate, token, archival);
            system.debug('response###'+response);
            if(response != Null){
                QCC_PNRPassengerInfoWrapper.Booking booking = response.booking;
                if(booking != Null && booking.passengers != Null){
                    List<QCC_PNRPassengerInfoWrapper.Passengers> lstPas = new List<QCC_PNRPassengerInfoWrapper.Passengers>();
                    for(QCC_PNRPassengerInfoWrapper.Passengers pas: booking.passengers){
                        if(String.isBlank(pas.qantasFFNo )){
                            //pas.firstName = pas.firstName.substringBefore(' '); Commented to consider the middle names for existing contact search
                            lstPas.add(pas);
                        }else{
                             lstPas.add(pas);
                        }
                    }
                    passengers = Json.serialize(lstPas);
                }
            }
            system.debug('passengers###'+passengers);
            if(String.isBlank(passengers) ){
                AuraHandledException ltEX = new AuraHandledException('');
                ltEX.setMessage(Label.QCC_NoValue);
                throw ltEX; 
            }
            
            return passengers;
        }catch(Exception ex){
            system.debug('Exception###'+ex);
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC - Customer Search', 'QCC_PNRSearchController', 
                                    'invokePNRSearch', String.valueOf(response), String.valueOf(''), true,'', ex);
            AuraHandledException ltEX = new AuraHandledException(ex.getMessage());
            throw ltEX;
        }   
    }

    
    /*--------------------------------------------------------------------------------------      
    Method Name:        invokeContactSearch
    Description:        CAP PNR Search  
    Parameter:          Pasenger Selected and PNR
    --------------------------------------------------------------------------------------*/ 
    @AuraEnabled
    public static String invokeContactSearch(String passenger, String cusPNR, String recId){
        String resp;
        try{
            cusPNR = QCC_GenericUtils.doTrim(cusPNR);
            system.debug('passenger$$$'+passenger);
            system.debug('cusPNR$$$'+cusPNR);
            passenger = passenger.removeStart ('[');
            passenger = passenger.removeEnd(']');
            system.debug('objpassenger$$$'+passenger);
            QCC_PNRPassengerInfoWrapper.Passengers passengerWrap = (QCC_PNRPassengerInfoWrapper.Passengers) Json.deserialize(passenger,  QCC_PNRPassengerInfoWrapper.Passengers.class);
            system.debug('passengerWrap$$$'+passengerWrap);
            
            
            if(String.isNotBlank(recId)){
                    Contact objcon;
                    if(passengerWrap.qantasFFNo != Null && String.isNotBlank(passengerWrap.qantasFFNo)){
                        resp = QCC_LookupFrequentFlyerController.lookupCustomer(passengerWrap.qantasFFNo, passengerWrap.lastName,'');
                        QCC_LookupFrequentFlyerController.CustomerWrapper respWrap = (QCC_LookupFrequentFlyerController.CustomerWrapper) Json.deserialize(resp, QCC_LookupFrequentFlyerController.CustomerWrapper.class);
                        QCC_ContactWrapper conWrap = new QCC_ContactWrapper();
                        conWrap.ffNumber = respWrap.ffNumber;
                        conWrap.lastName = respWrap.lastName;
                        conWrap.firstName = respWrap.firstName;
                        conWrap.ffTier = respWrap.ffTier;
                        conWrap.capId = respWrap.capId;
                        objcon = QCC_GenericUtils.fetchContactForFFCase(conWrap);
                    }else{
                        objcon = QCC_GenericUtils.fetchContactForNonFFCase();
                    }

                    if(objcon != Null){
                        Case objCase = [select id, (SELECT Id, Status__c FROM Recoveries_Case__r WHERE Status__c = 'Awaiting Approval') from case where Id =: recId];
                        if(objCase.Recoveries_Case__r == null || objCase.Recoveries_Case__r.size() == 0) {
                            objCase.ContactId = objcon.Id;
                            objCase.AccountId = objcon.AccountId;
                            update objCase;
                        }
                        else {
                            return 'Pending_Recoveries';
                        }
                    }else{
                        AuraHandledException ltEX = new AuraHandledException('');
                        ltEX.setMessage(Label.QCC_UnexpectedError);
                        throw ltEX; 
                    }
                    contactWrapper conInfo = new contactWrapper();
                    return 'success';

            }else if(passengerWrap.qantasFFNo != Null && String.isNotBlank(passengerWrap.qantasFFNo)){
                resp = QCC_LookupFrequentFlyerController.lookupCustomer(passengerWrap.qantasFFNo, passengerWrap.lastName,'');
                return resp;
            }else{
                contactWrapper conInfo = new contactWrapper();
                conInfo.fName = passengerWrap.firstName;
                conInfo.lName = passengerWrap.lastName;
                
                String token = QCC_GenericUtils.getCAPValidToken('QCC_BookingToken');
                QCC_PNRContactInfoWrapper pnrContact = QCC_InvokeCAPAPI.invokePNRContactInfoCAPAPI(cusPNR, token, passengerWrap.lastName);
                resp = json.serialize(pnrContact);
                if(pnrContact != Null && PnrContact.booking != Null){
                    List<QCC_PNRContactInfoWrapper.Email> lstEmail = (pnrContact.booking.contacts != Null && pnrContact.booking.contacts.email != Null)? pnrContact.booking.contacts.email : Null;
                    List<QCC_PNRContactInfoWrapper.Phone> lstPhone = (pnrContact.booking.contacts != Null && pnrContact.booking.contacts.phone != Null)? pnrContact.booking.contacts.phone : Null;
                    
                    if(lstEmail != Null){
                        //Jira CRM-6310: Look up PNR not populating email / phone number for non FF
                        for(QCC_PNRContactInfoWrapper.Email emailInfo: lstEmail) {
                            system.debug('emailInfo$$$$$'+emailInfo);
                            system.debug('emailInfo.passengerIds.size()$$$$$'+emailInfo.passengerIds.size());
                            if (emailInfo.passengerIds != Null && emailInfo.passengerIds.size() > 0 && emailInfo.passengerIds.contains(passengerWrap.passengerId)) {
                                conInfo.email = emailInfo.emailText;
                                break;
                            }
                        }
                        system.debug('conInfo######>'+conInfo);
                    }
                    
                    if(lstPhone != Null){
                        for(QCC_PNRContactInfoWrapper.Phone phoneInfo: lstPhone){
                            system.debug('phoneInfo$$$$$'+phoneInfo);
                            //Jira CRM-6310: Look up PNR not populating email / phone number for non FF
                            if (phoneInfo.passengerIds != Null && phoneInfo.passengerIds.size() > 0 && phoneInfo.passengerIds.contains(passengerWrap.passengerId)) {
                                        conInfo.phone = (String.isNotBlank(phoneInfo.countryCode) && phoneInfo.countryCode != null)?phoneInfo.countryCode:'';
                                    conInfo.phone += (String.isNotBlank(phoneInfo.areaCode) && phoneInfo.areaCode != null)?phoneInfo.areaCode:'';
                                    conInfo.phone += (String.isNotBlank(phoneInfo.phoneNumber) && phoneInfo.phoneNumber != null)?phoneInfo.phoneNumber:'';                     
                                    break;
                            }
                        }
                        
                    }
                }
                system.debug('conInfo######'+conInfo);
                 String strCon = Json.serialize(conInfo);

                /*contactWrapper cw = new contactWrapper();
                cw.email='test@testpnr.com';
                cw.ffNumber='';
                cw.fName='RT';
                cw.lName='PNR';
                cw.phone='452222222';
                String strCon = Json.serialize(cw);*/
                return strCon;
            }
        }catch(Exception ex){
            system.debug('Exception###'+ex);
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC - Customer Search', 'QCC_PNRSearchController', 
                                    'invokeContactSearch', resp, String.valueOf(''), true,'', ex);
            system.debug('ex####'+ex);
            // Added by Purushotham for Remediation hotfix -- START
            if(ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                ex.setMessage(ex.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').removeEnd(': []'));
            }
            // Added by Purushotham for Remediation hotfix -- END
            AuraHandledException ltEX = new AuraHandledException(ex.getMessage());
            throw ltEX;  
        }
    }

    /*--------------------------------------------------------------------------------------      
    Method Name:        invokeContactSearch
    Description:        CAP PNR Search  
    Parameter:          Pasenger Selected and PNR
    --------------------------------------------------------------------------------------*/ 
    @AuraEnabled
    public static String invokeAssignContacttoCase(String contactInfo, String recId){
        String resp;
        try{
            system.debug('contactInfo###'+contactInfo);
            QCC_ContactWrapper conWrap = (QCC_ContactWrapper)Json.deserialize(contactInfo, QCC_ContactWrapper.class);
            Contact objcon = QCC_GenericUtils.fetchContactForFFCase(conWrap);
            if(objcon != Null){
                Case objCase = [select id, (SELECT Id, Status__c FROM Recoveries_Case__r WHERE Status__c = 'Awaiting Approval') from case where Id =: recId];
                if(objCase.Recoveries_Case__r == null || objCase.Recoveries_Case__r.size() == 0) {
                    objCase.ContactId = objcon.Id;
                    objCase.AccountId = objcon.AccountId;
                    //CRM-7179
                    objCase.First_Name__c = objcon.FirstName;
                    objCase.Last_Name__c = objcon.LastName;
                    //CRM-8061 commented the line below to keep the phone entact
                    //objCase.Contact_Phone__c = objCon.Phone;
                    objCase.Contact_Email__c = objcon.Email;
                    System.debug('objCase====> ' + objCase);
                    update objCase;
                }
                else {
                    return 'Pending_Recoveries';
                }
            }
            return objcon.Id;

        }catch(Exception ex){
            system.debug('Exception###'+ex);
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC - Customer Search', 'QCC_PNRSearchController', 
                                    'invokeAssignContacttoCase', resp, String.valueOf(''), true,'', ex);
            system.debug('ex####'+ex);
            // Added by Purushotham for Remediation hotfix -- START
            if(ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                ex.setMessage(ex.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').removeEnd(': []'));
            }
            // Added by Purushotham for Remediation hotfix -- END
            AuraHandledException ltEX = new AuraHandledException(ex.getMessage());
            throw ltEX;  
        }
    }
    
    /*--------------------------------------------------------------------------------------      
    Method Name:        fetchColumn
    Description:        CAP Column
    Parameter:          Component Name
    --------------------------------------------------------------------------------------*/ 
    @AuraEnabled
    public static String fetchColumn(String componentName){
        List<columns> lstColumns = new List<columns>();
        for(QCC_Data_Table__mdt column: [select ComponentName__c , Order__c, FieldAPI__c , FieldLabel__c, 
                                         Sortable__c , Type__c  from QCC_Data_Table__mdt where 
                                         ComponentName__c  =: componentName Order By Order__c])
        {
            Columns objCol =  new Columns();
            objCol.label = column.FieldLabel__c;
            objCol.fieldName = column.FieldAPI__c;
            objCol.type = column.Type__c;
            objCol.sortable = column.Sortable__c;
            lstColumns.add(objCol);
        }
        String columns = Json.serialize(lstColumns);
        return columns;
    }

    /*--------------------------------------------------------------------------------------      
    Method Name:        assigntoGenericContact
    Description:        Assign Generic Contact
    Parameter:          caseID
    --------------------------------------------------------------------------------------*/ 
    @AuraEnabled
    public static String assigntoGenericContact(String caseId){
        try{
            Contact objcon = QCC_GenericUtils.fetchContactForNonFFCase();
            Case objCase = [select id, (SELECT Id, Status__c FROM Recoveries_Case__r WHERE Status__c = 'Awaiting Approval') from case where Id =: caseID];
            if(objCase.Recoveries_Case__r == null || objCase.Recoveries_Case__r.size() == 0) {
                objCase.ContactId = objcon.Id;
                objCase.AccountId = objcon.AccountId;
                update objCase;
                return 'success';
            }
            else {
                return 'Pending_Recoveries';
            }
            
        }catch(Exception ex){
            system.debug('Exception###'+ex);
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC - Customer Search', 'QCC_PNRSearchController', 
                                    'assigntoGenericContact', '', String.valueOf(''), true,'', ex);
            system.debug('ex####'+ex);
            // Added by Purushotham for Remediation hotfix -- START
            if(ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                ex.setMessage(ex.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').removeEnd(': []'));
            }
            // Added by Purushotham for Remediation hotfix -- END
            AuraHandledException ltEX = new AuraHandledException(ex.getMessage());
            throw ltEX;  
        }
    }
    
    public class Columns{
        public String label;
        public String fieldName ;
        public String type;
        public Boolean sortable;
    }
    
    public class contactWrapper{
        public String fName;
        public String lName;
        public String email;
        public String phone;
        public String ffNumber;
    }
}