force-app/main/default/objects/Case/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: related Flight Event for Cases created as part of proactive Recovery</description>
    <label>Flight Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Affected_Ports__c.field-meta.xml
<CustomField>
    <fullName>Affected_Ports__c</fullName>
    <description>QCC: Ports affected by this event</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Affected Ports</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ArrivalPort__c.field-meta.xml
<CustomField>
    <fullName>ArrivalPort__c</fullName>
    <description>QCC: arrival port of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/DelayFailureCode__c.field-meta.xml
<CustomField>
    <fullName>DelayFailureCode__c</fullName>
    <description>QCC: specific delay categories of the disruption(s).</description>
    <label>Delay Failure Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Turn Back</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Mechanical</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Medical</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Other</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Weather</fullName>
            </value>
            <value>
                <fullName>Flight Cancellation</fullName>
            </value>
            <value>
                <fullName>Flight Delay</fullName>
            </value>
            <value>
                <fullName>Add Stop</fullName>
            </value>
            <value>
                <fullName>Heads Up</fullName>
            </value>
            <value>
                <fullName>Flight Delay Greater than 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Greater than 20 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay Less between 5 and 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Less between 5 and 20 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay Less than 5 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Less than 5 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay between 5 and 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay between 5 and 20 Hours</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/DeparturePort__c.field-meta.xml
<CustomField>
    <fullName>DeparturePort__c</fullName>
    <description>QCC: departure port of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>QCC: Indicates when the global event was marked as resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <description>QCC: the flight number affected</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/IntDom__c.field-meta.xml
<CustomField>
    <fullName>IntDom__c</fullName>
    <description>QCC: identifies whether the flight is international or domestic</description>
    <label>Int/Dom</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Operational_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operational_Carrier__c</fullName>
    <description>QCC: Identifies the Flight Operator</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Operational Carrier</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Local_End_Time__c.field-meta.xml
<CustomField>
    <fullName>QCC_Local_End_Time__c</fullName>
    <description>End Time of the Global Heads Up flight event</description>
    <inlineHelpText>End Time of the Global Heads Up flight event</inlineHelpText>
    <label>Local End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Local_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>QCC_Local_Start_Time__c</fullName>
    <description>Start Time of the Global Heads Up flight event</description>
    <inlineHelpText>Start Time of the Global Heads Up flight event</inlineHelpText>
    <label>Local Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_TECH_Flight_Counter__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_Flight_Counter__c</fullName>
    <label>QCC TECH Flight Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepDate__c</fullName>
    <description>QCC: scheduled departure date of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>QCC: Indicates when the event was first noted</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/TECH_FlightAPIInvoked__c.field-meta.xml
<CustomField>
    <fullName>TECH_FlightAPIInvoked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Once the Flight API is Invoked it will be set to true</description>
    <label>FlightAPIInvoked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/TECH_RecordType_Duplication__c.field-meta.xml
<CustomField>
    <fullName>TECH_RecordType_Duplication__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TECH RecordType Duplication</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/QCC_GetFlightsForGlobalHeadsUpController.cls
/*********************************************************************************
Name         : QCC_GetFlightsForGlobalHeadsUpController
Created By   : Leslie Padilla
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 21 September 2019
Usages       : This class is used to retrieve flights affected by the Global Event based on the Departure and Arrival Ports and Dates
*********************************************************************************/
public class QCC_GetFlightsForGlobalHeadsUpController {
	@AuraEnabled
    public static GetFlightsWrapper getAllFlights(String headsUpEventId) {
        GetFlightsWrapper myWrapper = new GetFlightsWrapper();
        
        try {
            List<Event__c> globalHeadsUpEvents = new List<Event__c>([SELECT Id, Name, QCC_TECH_Flight_Counter__c, RecordTypeId, TECH_FlightAPIInvoked__c, Affected_Ports__c, Start_Date__c, QCC_Local_Start_Time__c, End_Date__c, QCC_Local_End_Time__c FROM Event__c WHERE Id =: headsUpEventId]);
            List<Event__c> flightEventsToCreate = new List<Event__c>();
            
            Integer freightLowRange = String.IsNotBlank(CustomSettingsUtilities.getConfigDataMap('QCC_FreightLowRange'))?Integer.valueOf(CustomSettingsUtilities.getConfigDataMap('QCC_FreightLowRange')):3000;
            Integer freightHighRange = String.IsNotBlank(CustomSettingsUtilities.getConfigDataMap('QCC_FreightHighRange'))?Integer.valueOf(CustomSettingsUtilities.getConfigDataMap('QCC_FreightHighRange')):10000;
            Integer flightSet = 0; //the number of flights set returned by the API response
                        
            //Start: Loop through the Global Event record
            for(Event__c globalHeadsUpRecord : globalHeadsUpEvents){
                system.debug('>>>Event Record: ' + globalHeadsUpRecord.TECH_FlightAPIInvoked__c + '-' + globalHeadsUpRecord.Affected_Ports__c + '-' + globalHeadsUpRecord.Start_Date__c + '-' + globalHeadsUpRecord.End_Date__c); 
                Integer flightSet_CounterStartAt = (globalHeadsUpRecord.QCC_TECH_Flight_Counter__c == NULL) ? 0 : Integer.valueOf(globalHeadsUpRecord.QCC_TECH_Flight_Counter__c);
                Integer flightSet_Counter = 0;
                //Check the record type and the required fields needed to invoke the invokeFlightStatusDepsAPI callout
                if(globalHeadsUpRecord.RecordTypeId == GenericUtils.getObjectRecordTypeId('Event__c', CustomSettingsUtilities.getConfigDataMap('QCC Flight Event Global Heads Up'))){
                    if( !globalHeadsUpRecord.TECH_FlightAPIInvoked__c && String.isNotBlank(globalHeadsUpRecord.Affected_Ports__c) && globalHeadsUpRecord.Start_Date__c != Null && globalHeadsUpRecord.End_Date__c != Null){
                        String startTime = String.valueOf(globalHeadsUpRecord.QCC_Local_Start_Time__c).left(5);
                        String endTime = String.valueOf(globalHeadsUpRecord.QCC_Local_End_Time__c).left(5);
                        
                        //String departureFrom = String.valueOf(globalHeadsUpRecord.Start_Date__c).replace('-','') + '0000';
                        //String departureTo = String.valueOf(globalHeadsUpRecord.End_Date__c).replace('-','') + '0000';
                        
                        String departureFrom = String.valueOf(globalHeadsUpRecord.Start_Date__c).replace('-','') + startTime.replace(':','');
                        String departureTo = String.valueOf(globalHeadsUpRecord.End_Date__c).replace('-','') + endTime.replace(':','');
                        
                        system.debug('>>>invokeFlightStatusDepsAPI inputs: ' + globalHeadsUpRecord.Affected_Ports__c + '-' + departureFrom + '-' + departureTo);
                        QCC_FlightStatusDepsAPIResponse response = QCC_InvokeCAPAPI.invokeFlightStatusDepsAPI(globalHeadsUpRecord.Affected_Ports__c, departureFrom, departureTo);
                        flightSet = response.flights.size(); //TO-DO: If custom setting is not set then get the size
                        //flightSet = 80;
                        system.debug('>>>response: ' + response);
                        system.debug('>>>flightSet: ' + flightSet + '>>>response.flights.size(): ' + response.flights.size());
                        
                        //Create the Heads Up flight event record
                        String recordTypeId = GenericUtils.getObjectRecordTypeId('Event__c', CustomSettingsUtilities.getConfigDataMap('QCC Flight Event Heads Up'));
                        List<String> airlineCodes = Label.QCC_Global_Heads_Up_Event_Airline_Code.split(';');
                        
                        //This number setting is used to set the number of flights to consider and serves as a control in case the number of response size limit is reached
                        Integer maxNumberOfFlights = Integer.valueOf(Label.QCC_Heads_Up_Max_Flights);
                        
                        //Start: Loop through the list of flights from the API response
                        for (QCC_FlightStatusDepsAPIResponse.Flights flights : response.flights) {
                        //for (flightSet_Counter = flightSet_CounterStartAt; flightSet_Counter < flightSet; flightSet_Counter++) {
                            system.debug('>>>flightSet_Counter: ' + flightSet_Counter);
                            //QCC_FlightStatusDepsAPIResponse.Flights flights = response.flights.get(flightSet_Counter);
                            system.debug('>>>flights: ' + flights);
                            //Start: Loop through the flight numbers. Will only consider the carrier specified on the custom label QCC_Global_Heads_Up_Event_Airline_Code
                            for (QCC_FlightStatusDepsAPIResponse.FlightNumbers flightNum : flights.flightNumbers) {
                                //Instantiate the flight event record
                                Event__c flightEvent = new Event__c();
                                flightEvent.RecordTypeId = recordTypeId;
                                
                                String operationalCarrier = flightNum.airline;
                                String flightNumber = flightNum.airline + String.valueOf(flightNum.code).leftPad(4,'0');
                                if (airlineCodes.contains(flightNum.airline)) {
                                    String IntDom = '';
                                    if (flightNum.code <= 399 || flightNum.code == 3000) { //TO-DO: Need to save this in a configurable way
                                        IntDom = 'International'; //will not include the Freight Flights between 30001 to 9999
                                    } else if (flightNum.code >= 400 && flightNum.code <= 2999) { //TO-DO: Need to save this in a configurable way
                                        IntDom = 'Domestic';
                                    }
                                    
                                    //If the flight has not been classified as either International or Domestic then don't proceed with creation of flight event
                                    if (IntDom != '') {
                                        flightEvent.IntDom__c = IntDom;
                                        flightEvent.FlightNumber__c = flightNumber;
                                        flightEvent.Operational_Carrier__c = operationalCarrier;
                                        
                                        //Get the sector departure details
                                        //TO-DO: Check what's the scenario where there will be multiple sectors
                                        for (QCC_FlightStatusDepsAPIResponse.Sectors sector : flights.sectors) {
                                            String departurePort = sector.from_Z;
                                            system.debug('>>>sector: ' + sector);
                                            String arrivalPort = sector.to;
                                            flightEvent.DeparturePort__c = departurePort;
                                            flightEvent.Affected_Ports__c = departurePort;
                                            flightEvent.ArrivalPort__c = arrivalPort;
                                            
                                            Date ScheduledDepDate = Date.valueOf(sector.departure.scheduled);
                                            flightEvent.ScheduledDepDate__c = ScheduledDepDate;
                                            
                                            flightEvent.Name = 'HEADS UP ' + sector.sectorId;
                                        }
                                        
                                        //Set this field so the record will be considered by the Duplicate Rule (Event Duplicate Rule)
                                        flightEvent.DelayFailureCode__c = 'Heads Up';
                                        flightEvent.TECH_RecordType_Duplication__c = 'Heads Up';
                                        system.debug('>>>flightEvent: ' + flightEvent);
                                        flightEventsToCreate.add(flightEvent);
                                    }
                                }
                            }//End: Loop through the flight numbers. Will only consider the carrier specified on the custom label QCC_Global_Heads_Up_Event_Airline_Code
                            //flightSet_Counter++;
                            system.debug('>>>flightSet_Counter: ' + flightSet_Counter);
                        }//End: Loop through the list of flights from the API response
                    }
                }
                
                system.debug('>>>flightSet=' + flightSet + '; flightSet_Counter=' + flightSet_Counter);
                globalHeadsUpRecord.QCC_TECH_Flight_Counter__c = flightSet_Counter;
                
            }//End: Loop through the Global Event record
            
            system.debug('>>>flightEventsToCreate.size(): ' + flightEventsToCreate.size());
            system.debug('>>>flightEventsToCreate: ' + flightEventsToCreate);
            
            List<Database.SaveResult> saveResultList = new List<Database.SaveResult>();
            Map<String, List<String>> resultMap = new Map<String, List<String>>(); 
            if (!flightEventsToCreate.isEmpty()) {
                saveResultList = Database.insert (flightEventsToCreate,false);
                system.debug('>>>saveResultList: ' + saveResultList);
            }
            
            //Generate the save result so that we can create a Log record later.
            Integer recordCounter = 0;
            for(Database.SaveResult saveResult : saveResultList) {
                String recordId = flightEventsToCreate[recordCounter].Id;
                List<String> resultMessageList = new List<String>();
                if (!saveResult.isSuccess()) {            
                    for(Database.Error err : saveResult.getErrors()) {
                        resultMessageList.add(err.getStatusCode() + ': ' + err.getMessage());
                    }
                    resultMap.put(recordId, resultMessageList);
                }
                recordCounter++;
            }
            System.debug('>>>resultMap: ' + resultMap);
            
            //Create the log record for those save result that fails
            List<Log__c> logRecords = new List<Log__c>();
            for(String recordId: resultMap.keyset()){
                for(String resultMessage : resultMap.get(recordId)) {
                    //If records went into error due to the Duplicate Rule, then no need to log as it's valid not to create the record.
                    if (!resultMessage.contains('DUPLICATES_DETECTED')) {
                        logRecords.add(QCC_LogUtilityHelper.generateLogRecord('QCC - Get Flights for Global Heads Up Event', 'QCC_GetFlightsForGlobalHeadsUpController', 'getAllFlights', '', '', false, recordId, null, resultMessage));
                    }
                }
            }
            if (!logRecords.isEmpty()) {
                QCC_LogUtilityHelper.createLogRecords(logRecords);
            }
            
            
            //Collect the Event Ids saved successfully to be passed on to the job QCC_UpdateFlightsForHeadsUpQueuable
            List<Id> listIds = new List<Id>();
            for (Event__c flightEvent : flightEventsToCreate) {
                if (flightEvent.Id != NULL) {
                	listIds.add(flightEvent.Id);
                }
            }
            system.debug('>>>listIds: ' + listIds);
            
            //Call the batch that will retrieve the info of the flight event
            Database.executeBatch(new QCC_UpdateFlightsForHeadsUpBatch(listIds), 1);
            
            //Enqueue the job that updates the Flight event info
            /*for (Id eventId : listIds) {
                System.enqueueJob(new QCC_UpdateFlightsForHeadsUpQueuable(new List<Id>{eventId},NULL,0));
            }*/
                        
            update globalHeadsUpEvents;
            
        } catch (Exception ex) {
            Log__c logRecord = QCC_LogUtilityHelper.generateLogRecord('QCC - Get Flights for Global Heads Up Event', 'QCC_GetFlightsForGlobalHeadsUpController', 'getAllFlights', '', '', false, '', ex, '');
            system.debug('>>>logRecord: ' + logRecord);
            QCC_LogUtilityHelper.createLogRecord(logRecord);
        } 
        
        return myWrapper;
    }
    
    public class GetFlightsWrapper {
        @AuraEnabled public Boolean hasError {get;set;}
        @AuraEnabled public Boolean errorMessage {get;set;}
    }
}