force-app/main/default/objects/Case/fields/FF_Tier__c.field-meta.xml
<CustomField>
    <fullName>FF_Tier__c</fullName>
    <description>QCC: Frequent Flyer Number of customer copied to case on case creation for back-end usage;reporting.</description>
    <label>Frequent Flyer Tier on Case Creation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#2F5D85</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#CC0000</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#666666</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#AFCADF</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
                <color>#000000</color>
                <label>Chairmans Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairmans Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Queue_Owner__c.field-meta.xml
<CustomField>
    <fullName>Last_Queue_Owner__c</fullName>
    <description>Stores the last queue owner.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Queue Owner</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_EscalateCaseToQueueTest.cls
@isTest
public class QCC_EscalateCaseToQueueTest {

	@testSetup
	static void createData() {
		Test.startTest();
        
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Account RecType1','Agency Account;Charter Account;Customer Account;Global Account;Other Account;Prospect Account;Regional Account;Person Account'));        
        insert lstConfigData;
        
		//Create test data for Account object
		String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
		Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
		accountRecord.RecordTypeId = accountRecordTypeId;
		insert accountRecord;

		//Create test data for Contact object
		List<Contact> contactRecords = new List<Contact>();
		String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
		Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
		contactRecord.RecordTypeId = contactRecordTypeId;
		contactRecord.Frequent_Flyer_Number__c = '000001';
		insert contactRecord;

		List<Trigger_Status__c> customSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusCase', null, null, null, null);
		insert customSettingList;

		//Create test data for Case object
		Case caseRecord = QCC_TestDataFactory.createCaseTestData(accountRecord.Id, contactRecord.Id);
		insert caseRecord;
		Test.stopTest();
	}

	static testMethod void testEscalation(){
		Test.startTest();
		Case caseRecord = [SELECT Id, OwnerId, FF_Tier__c,Last_Queue_Owner__c FROM Case LIMIT 1];//(User Story: QSFR-23) Added Last_Queue_Owner__c
		List<Case> listCase = new List<Case> {caseRecord};
		QCC_EscalateCaseToQueue.EscalateCaseWithWaitingStatus(listCase);
		Test.stopTest();
		//(User Story: QSFR-23) Start
		Group g1 = [Select Id, Name from group where developername = 'CCC_R1_Post_Travel_Q' Limit 1];
		caseRecord = [SELECT Id, OwnerId, FF_Tier__c,Last_Queue_Owner__c FROM Case LIMIT 1];
		system.assert (caseRecord.OwnerId == g1.Id, 'Escalation failed');
		//(User Story: QSFR-23) End
	}
}