force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Queue_Owner__c.field-meta.xml
<CustomField>
    <fullName>Last_Queue_Owner__c</fullName>
    <description>Stores the last queue owner.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Queue Owner</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Used on CL Renewal Cases to capture the location of the Chairman Lounge member (his/her Home port)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CAP_ID__c.field-meta.xml
<CustomField>
    <fullName>CAP_ID__c</fullName>
    <description>Contact CAP ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <description>Getting Full name of Country to Populate from Contact Country to Case Country field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CountryName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Procurement/Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agency Manager</fullName>
            </value>
            <value>
                <fullName>Agency Owner</fullName>
            </value>
            <value>
                <fullName>Ambassador / High Commissioner</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager - Agency</fullName>
            </value>
            <value>
                <fullName>Business Development Manager – Corporate</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chancellor</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Charter Key Contact</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of Business Unit</fullName>
            </value>
            <value>
                <fullName>Chief of Finance</fullName>
            </value>
            <value>
                <fullName>Chief of Organisation</fullName>
            </value>
            <value>
                <fullName>Chief of Procurement</fullName>
            </value>
            <value>
                <fullName>Chief of the Organisation</fullName>
            </value>
            <value>
                <fullName>Commercial Director</fullName>
            </value>
            <value>
                <fullName>Commerical Partner Contact</fullName>
            </value>
            <value>
                <fullName>Consultant/agent</fullName>
            </value>
            <value>
                <fullName>Consultant/agent - Senior</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Assistant</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Executive Team Member (non Finance)</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Head of Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Key Traveller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Queue Members location (manila , Sydney , ..)</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manila</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Hobart</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Capetown</fullName>
            </value>
            <value>
                <fullName>Suva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CCC_OmniUpdateLastQueueOwner_Test.cls
/*------------------------------------------------------------
   Company:        Salesforce
   Description:    Test for CCC_OmniUpdateLastQueueOwner

   History
   Date            Author                  Comments
   -------------------------------------------------------------
   06-04-2021      Salesforce              Initial Version
   -------------------------------------------------------------*/
@isTest
public class CCC_OmniUpdateLastQueueOwner_Test {

	@TestSetup
	static void testSetup(){
		List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.enableTriggers();
		TestUtilityDataClassQantas.insertQantasConfigData();

		Map<String, Profile> profMap = TestUtilityDataClassQantas.getProfileMap();
		// Replacing the Run as user profile with QCC Contact Center Agent profile and adding QCC Base,Contact Center and Genesys permission sets on the user as part of RBAC CRM-11628
		User u1 = new User(LastName = 'User1', Alias = 'User', Email = 'sampleuser1@sample.com',
		                   Username = 'sampleuser1username@sample.com', ProfileId = profMap.get('QCC Contact Center Agent Hobart').Id, 
		                   EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_AU',
		                   TimeZoneSidKey = 'Australia/Sydney', City='Manila', Location__c = 'Manila'
		                   );
        insert u1;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            List<Id> permissionSetIds = TestUtilityDataClassQantas.getPermissionSetIds('QCC_Base_User_Permissions,QCC_Contact_Center_Agent_Permissions,QCC_Genesys_User_Permissions');
            List<PermissionSetAssignment> psaList = TestUtilityDataClassQantas.createPermissionSetAssignments(u1.Id,permissionSetIds);
        }

		List<Contact> contacts = new List<Contact>();

		System.runAs(u1) {

			for(Integer i = 0; i < 1; i++) {
				Contact con = new Contact(LastName='Sample'+i, FirstName='User', Business_Types__c='Agency', Job_Role__c='Agency Manager',
				                          Function__c='Advisory Services', Email='test@sample.com', MailingStreet = '15 hobart rd',
				                          MailingCity = 'south launceston', MailingState = 'TAS', MailingPostalCode = '7249',
				                          CountryName__c = 'Australia', Frequent_Flyer_tier__c   = 'Silver', Frequent_Flyer_Number__c = '12345');
				con.CAP_ID__c = '71000000001'+ (i+7);
				contacts.add(con);
			}
			insert contacts;
		}
	}

	@isTest
	public static void omniUpdateLastQueueOwnerTest() {
		String type = 'Query';
		String recordType = 'CCC Query';
		Contact con = [SELECT Id, Name FROM Contact Limit 1];
		Case cs = TestUtilityDataClassQantas.createCaseWithCodingValues(recordType, type, '', '', '', '');
		cs.ContactId = con.id;
		insert cs;

		list<queuesObject> listQO = [select id, QueueId from QueuesObject where SobjectType ='Case'];
		Id queueId = listQO[0].QueueId;

		CCC_OmniUpdateLastQueueOwner.Input singleInput = new CCC_OmniUpdateLastQueueOwner.Input();
		singleInput.originalGroupId = queueId;
		singleInput.workItemId = cs.id;
		List<CCC_OmniUpdateLastQueueOwner.Input> inputs = new  List<CCC_OmniUpdateLastQueueOwner.Input>();
		inputs.add(singleInput);

		Test.startTest();
		CCC_OmniUpdateLastQueueOwner.updateLastQueueOwner(inputs);
		Case objCase = [Select id, Last_Queue_Owner__c from Case where Id = :cs.Id];
		Test.stopTest();
		System.assertEquals(objCase.Last_Queue_Owner__c, Id.valueOf(queueId), 'Last Queue Owner is Not Updated.');
	}
}