force-app/main/default/objects/Case/fields/QCC_Specific_Needs__c.field-meta.xml
<CustomField>
    <fullName>QCC_Specific_Needs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specific Needs</label>
    <referenceTo>QCC_Specific_Needs__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/QCC_Specific_Needs__c.object-meta.xml
<CustomObject>
    <description>Container for capturing the Specific Need Smart Forms</description>
    <label>Specific Needs</label>
    <nameField>
        <displayFormat>SN{00000000}</displayFormat>
        <label>Specific Needs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specific Needs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/Confirm_Outcome_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Outcome_to_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirm Outcome to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Booking_Created__c.field-meta.xml
<CustomField>
    <fullName>QCC_Booking_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Booking Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Case__c.field-meta.xml
<CustomField>
    <fullName>QCC_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Specific Needs</relationshipLabel>
    <relationshipName>Specific_Needs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Compliance_Approval_Request_Sent_SD__c.field-meta.xml
<CustomField>
    <fullName>QCC_Compliance_Approval_Request_Sent_SD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Compliance Approval Request Sent(option)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Compliance_Outcome_Received_SD__c.field-meta.xml
<CustomField>
    <fullName>QCC_Compliance_Outcome_Received_SD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Compliance Outcome Received(optional)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Confirmation_Sent_to_Customer_MC__c.field-meta.xml
<CustomField>
    <fullName>QCC_Confirmation_Sent_to_Customer_MC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmation Sent to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Confirmation_sent_to_Customer_MCIT__c.field-meta.xml
<CustomField>
    <fullName>QCC_Confirmation_sent_to_Customer_MCIT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmation sent to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Confirmation_Sent_to_Customer_MCNE__c.field-meta.xml
<CustomField>
    <fullName>QCC_Confirmation_Sent_to_Customer_MCNE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmation Sent to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Confirmation_sent_to_Customer_MCOD__c.field-meta.xml
<CustomField>
    <fullName>QCC_Confirmation_sent_to_Customer_MCOD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmation sent to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Confirmation_sent_to_Customer_MCOQS__c.field-meta.xml
<CustomField>
    <fullName>QCC_Confirmation_sent_to_Customer_MCOQS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmation sent to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Confirmation_Sent_to_Requestor_MBW__c.field-meta.xml
<CustomField>
    <fullName>QCC_Confirmation_Sent_to_Requestor_MBW__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmation Sent to Requestor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Contact__c.field-meta.xml
<CustomField>
    <fullName>QCC_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact related to the Specific Needs record.</description>
    <inlineHelpText>The contact related to the Specific Needs record.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Specific Needs</relationshipLabel>
    <relationshipName>Specific_Needs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Customer_has_accepted_Quote_MCOD__c.field-meta.xml
<CustomField>
    <fullName>QCC_Customer_has_accepted_Quote_MCOD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer has accepted Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Customer_has_accepted_Quote_MCOQS__c.field-meta.xml
<CustomField>
    <fullName>QCC_Customer_has_accepted_Quote_MCOQS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer has accepted Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Dog_Traveled_and_Previously_Approved__c.field-meta.xml
<CustomField>
    <fullName>QCC_Dog_Traveled_and_Previously_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dog Traveled and Previously Approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Final_Confirmation_Sent_to_Requester__c.field-meta.xml
<CustomField>
    <fullName>QCC_Final_Confirmation_Sent_to_Requester__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final Confirmation Sent to Requester</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_MEDA_Clearance_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>QCC_MEDA_Clearance_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MEDA Clearance Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_MEDA_Completed_Approved__c.field-meta.xml
<CustomField>
    <fullName>QCC_MEDA_Completed_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MEDA Completed/Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_MEDA_Completed_Approved_MCIT__c.field-meta.xml
<CustomField>
    <fullName>QCC_MEDA_Completed_Approved_MCIT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MEDA Completed/Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_MEDA_Completed_Approved_MCQS__c.field-meta.xml
<CustomField>
    <fullName>QCC_MEDA_Completed_Approved_MCQS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MEDA Completed/Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Notify_Airport_and_Crew_1_Day__c.field-meta.xml
<CustomField>
    <fullName>QCC_Notify_Airport_and_Crew_1_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Airport and Crew (-1 Day)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Notify_Cabin_Crew_CJMs_SD__c.field-meta.xml
<CustomField>
    <fullName>QCC_Notify_Cabin_Crew_CJMs_SD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Cabin Crew &amp; CJMs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Notify_Departure_Airport_3_Days_PAP__c.field-meta.xml
<CustomField>
    <fullName>QCC_Notify_Departure_Airport_3_Days_PAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Departure Airport (-3 Days)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Notify_Departure_Airport_3_Days_ST__c.field-meta.xml
<CustomField>
    <fullName>QCC_Notify_Departure_Airport_3_Days_ST__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Departure Airport (-3 Days)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Notify_Eng_Airport_Crew_2_days_IT__c.field-meta.xml
<CustomField>
    <fullName>QCC_Notify_Eng_Airport_Crew_2_days_IT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Eng/Airport/Crew (-2 days)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Notify_Eng_Airport_Crew_2_days_OD__c.field-meta.xml
<CustomField>
    <fullName>QCC_Notify_Eng_Airport_Crew_2_days_OD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Eng/Airport/Crew (-2 days)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Notify_Eng_Airport_Crew_2_days_QS__c.field-meta.xml
<CustomField>
    <fullName>QCC_Notify_Eng_Airport_Crew_2_days_QS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Eng/Airport/Crew (-2 days)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Outcome_Confirmation_Sent_to_Cst_SD__c.field-meta.xml
<CustomField>
    <fullName>QCC_Outcome_Confirmation_Sent_to_Cst_SD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Outcome Confirmation Sent to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Oxygen_Ordered__c.field-meta.xml
<CustomField>
    <fullName>QCC_Oxygen_Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oxygen Ordered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>QCC_Payment_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_PNR_Updated_MCIT__c.field-meta.xml
<CustomField>
    <fullName>QCC_PNR_Updated_MCIT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PNR Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_PNR_Updated_MCOD__c.field-meta.xml
<CustomField>
    <fullName>QCC_PNR_Updated_MCOD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PNR Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_PNR_Updated_MCOQS__c.field-meta.xml
<CustomField>
    <fullName>QCC_PNR_Updated_MCOQS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PNR Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_PNR_Updated_SD__c.field-meta.xml
<CustomField>
    <fullName>QCC_PNR_Updated_SD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PNR Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Quote_Provided_to_Customer_MCOD__c.field-meta.xml
<CustomField>
    <fullName>QCC_Quote_Provided_to_Customer_MCOD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Provided to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Quote_Provided_to_Customer_MCOQS__c.field-meta.xml
<CustomField>
    <fullName>QCC_Quote_Provided_to_Customer_MCOQS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Provided to Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Quote_Provided_to_Requester_MCST__c.field-meta.xml
<CustomField>
    <fullName>QCC_Quote_Provided_to_Requester_MCST__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Provided to Requester</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Seating_Allocated_for_Customer_CBBG__c.field-meta.xml
<CustomField>
    <fullName>QCC_Seating_Allocated_for_Customer_CBBG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seating Allocated for Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Update_Intelex__c.field-meta.xml
<CustomField>
    <fullName>QCC_Update_Intelex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update Intelex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Update_PNR_CBBG__c.field-meta.xml
<CustomField>
    <fullName>QCC_Update_PNR_CBBG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update PNR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Update_PNR_MBW__c.field-meta.xml
<CustomField>
    <fullName>QCC_Update_PNR_MBW__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update PNR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Update_PNR_MC__c.field-meta.xml
<CustomField>
    <fullName>QCC_Update_PNR_MC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update PNR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Update_PNR_MCNE__c.field-meta.xml
<CustomField>
    <fullName>QCC_Update_PNR_MCNE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update PNR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Update_PNR_MCST__c.field-meta.xml
<CustomField>
    <fullName>QCC_Update_PNR_MCST__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update PNR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/QCC_Updating_Service_Dog_Register__c.field-meta.xml
<CustomField>
    <fullName>QCC_Updating_Service_Dog_Register__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Service Dog Register</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_Specific_Needs__c/fields/Update_PNR_WC__c.field-meta.xml
<CustomField>
    <fullName>Update_PNR_WC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update PNR WC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QCC_DisplaySpecificNeedsController.cls
/*********************************************************************************
Name         : QCC_DisplaySpecificNeedsController
Created By   : Raymart Tolentino
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 2020-01-13
Usages       : This will handle the backend logic needed for QCC_DisplaySpecificNeedsRelatedToCase
*********************************************************************************/
public class QCC_DisplaySpecificNeedsController {
    //@Purpose: This method updates the QCC_Specific_Needs__c record based on the selected checkbox in the lightning component.
    //@input paremeters:
    //	-caseRecordId - The record id of the case which the specific need record is related.
    //	-specificNeedRecord - The object record containing all the updated field.
    //	-isNew - The flag to determine whether the case record should be updated or not.
    //@return type: List of sObject including fields with null values
    @AuraEnabled  
    public static void updateSpecificNeedRecord(String caseRecordId, String specificNeedRecord, Boolean isNew){
        system.debug('@@@SN: ' + specificNeedRecord);
        QCC_Specific_Needs__c specificNeedRecordToUpdate = (QCC_Specific_Needs__c)JSON.deserialize(specificNeedRecord, QCC_Specific_Needs__c.class);
        
        if (isNew) {
            Case caseRecord = [SELECT Id, QCC_Specific_Needs__c, ContactId FROM Case WHERE Id =: caseRecordId];
            caseRecord.QCC_Specific_Needs__c = specificNeedRecordToUpdate.Id;
            specificNeedRecordToUpdate.QCC_Contact__c = caseRecord.ContactId;
            specificNeedRecordToUpdate.QCC_Case__c = caseRecord.Id;
            
            update caseRecord;  
        }
        
        update specificNeedRecordToUpdate;
    }
    
    @AuraEnabled
    public static RequestTypeWrapper retrieveCheckboxValues(Id RecId){
        //List<String> ListValue = new List<String>();        
        system.debug('@@@DOINITrecord Id'+RecId);
        case cs = [
            SELECT Id, QCC_Specific_Needs__r.Update_PNR_WC__c,QCC_Specific_Needs__r.Confirm_Outcome_to_Customer__c, QCC_Specific_Needs__r.QCC_PNR_Updated_SD__c, 
            QCC_Specific_Needs__r.QCC_Dog_Traveled_and_Previously_Approved__c, QCC_Specific_Needs__r.QCC_Outcome_Confirmation_Sent_to_Cst_SD__c, 
            QCC_Specific_Needs__r.QCC_Compliance_Approval_Request_Sent_SD__c, QCC_Specific_Needs__r.QCC_Compliance_Outcome_Received_SD__c,
            QCC_Specific_Needs__r.QCC_Update_PNR_MC__c, QCC_Specific_Needs__r.QCC_Confirmation_Sent_to_Customer_MC__c,
            QCC_Specific_Needs__r.QCC_Update_PNR_MCST__c, QCC_Specific_Needs__r.QCC_Update_Intelex__c, QCC_Specific_Needs__r.QCC_MEDA_Clearance_Confirmed__c, 
            QCC_Specific_Needs__r.QCC_Payment_Received__c, QCC_Specific_Needs__r.QCC_Booking_Created__c, QCC_Specific_Needs__r.QCC_Quote_Provided_to_Requester_MCST__c, 
            QCC_Specific_Needs__r.QCC_Final_Confirmation_Sent_to_Requester__c,  QCC_Specific_Needs__r.QCC_PNR_Updated_MCOD__c, QCC_Specific_Needs__r.QCC_MEDA_Completed_Approved__c, QCC_Specific_Needs__r.QCC_Quote_Provided_to_Customer_MCOD__c,
            QCC_Specific_Needs__r.QCC_Customer_has_accepted_Quote_MCOD__c, QCC_Specific_Needs__r.QCC_Confirmation_sent_to_Customer_MCOD__c, QCC_Specific_Needs__r.QCC_PNR_Updated_MCOQS__c,
            QCC_Specific_Needs__r.QCC_MEDA_Completed_Approved_MCQS__c, QCC_Specific_Needs__r.QCC_Quote_Provided_to_Customer_MCOQS__c,
            QCC_Specific_Needs__r.QCC_Customer_has_accepted_Quote_MCOQS__c, QCC_Specific_Needs__r.QCC_Confirmation_sent_to_Customer_MCOQS__c,
            QCC_Specific_Needs__r.QCC_PNR_Updated_MCIT__c, QCC_Specific_Needs__r.QCC_MEDA_Completed_Approved_MCIT__c, QCC_Specific_Needs__r.QCC_Confirmation_sent_to_Customer_MCIT__c,
            QCC_Specific_Needs__r.QCC_Update_PNR_CBBG__c, QCC_Specific_Needs__r.QCC_Seating_Allocated_for_Customer_CBBG__c, QCC_Specific_Needs__r.QCC_Update_PNR_MBW__c,
            QCC_Specific_Needs__r.QCC_Confirmation_Sent_to_Requestor_MBW__c, QCC_Specific_Needs__r.QCC_Notify_Cabin_Crew_CJMs_SD__c, QCC_Specific_Needs__r.QCC_Notify_Departure_Airport_3_Days_PAP__c,
            QCC_Specific_Needs__r.QCC_Notify_Departure_Airport_3_Days_ST__c, QCC_Specific_Needs__r.QCC_Notify_Eng_Airport_Crew_2_days_OD__c,
            QCC_Specific_Needs__r.QCC_Notify_Eng_Airport_Crew_2_days_QS__c, QCC_Specific_Needs__r.QCC_Oxygen_Ordered__c, QCC_Specific_Needs__r.QCC_Notify_Eng_Airport_Crew_2_days_IT__c,
            QCC_Specific_Needs__r.QCC_Notify_Airport_and_Crew_1_Day__c, QCC_Specific_Needs__r.QCC_Updating_Service_Dog_Register__c,
            QCC_Specific_Needs__r.QCC_Update_PNR_MCNE__c, QCC_Specific_Needs__r.QCC_Confirmation_Sent_to_Customer_MCNE__c, QCC_Specific_Needs__r.QCC_Send_Notification_to_Airline_MCNE__c
            FROM Case 
            WHERE  id=:RecId
        ];
        RequestTypeWrapper requestTypeList = new RequestTypeWrapper();        
        List<String> listWC = new List<String>();
        List<String> listNE = new List<String>();
        List<String> listCBAP = new List<String>();
        List<String> listOD = new List<String>();
        List<String> listIQ = new List<String>();
        List<String> listIT = new List<String>();
        List<String> listST = new List<String>();
        List<String> listSD = new List<String>();
        List<String> listCBBG = new List<String>();
        List<String> listMBW = new List<String>();
        
        //Wheelchair
        if(cs.QCC_Specific_Needs__r.Update_PNR_WC__c == true){
            listWC.add('Update_PNR_WC__c');
        }
        if(cs.QCC_Specific_Needs__r.Confirm_Outcome_to_Customer__c == true){
            listWC.add('Confirm_Outcome_to_Customer__c');
        }
        
        //Medical Clearance - No Equipment
        if(cs.QCC_Specific_Needs__r.QCC_Update_PNR_MCNE__c == true){
            listNE.add('QCC_Update_PNR_MCNE__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Confirmation_Sent_to_Customer_MCNE__c == true){
            listNE.add('QCC_Confirmation_Sent_to_Customer_MCNE__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Send_Notification_to_Airline_MCNE__c == true){
            listNE.add('QCC_Send_Notification_to_Airline_MCNE__c');
        } 
        
        //CBAP
        if(cs.QCC_Specific_Needs__r.QCC_Update_PNR_MC__c == true){
            listCBAP.add('QCC_Update_PNR_MC__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Confirmation_Sent_to_Customer_MC__c == true){
            listCBAP.add('QCC_Confirmation_Sent_to_Customer_MC__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Notify_Departure_Airport_3_Days_PAP__c == true){
            listCBAP.add('QCC_Notify_Departure_Airport_3_Days_PAP__c');
        }

        //Medical Clearance - Oxygen Domestic
        if(cs.QCC_Specific_Needs__r.QCC_PNR_Updated_MCOD__c == true){
            listOD.add('QCC_PNR_Updated_MCOD__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_MEDA_Completed_Approved__c == true){
            listOD.add('QCC_MEDA_Completed_Approved__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Quote_Provided_to_Customer_MCOD__c == true){
            listOD.add('QCC_Quote_Provided_to_Customer_MCOD__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Customer_has_accepted_Quote_MCOD__c == true){
            listOD.add('QCC_Customer_has_accepted_Quote_MCOD__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Confirmation_sent_to_Customer_MCOD__c == true){
            listOD.add('QCC_Confirmation_sent_to_Customer_MCOD__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Notify_Eng_Airport_Crew_2_days_OD__c == true){
            listOD.add('QCC_Notify_Eng_Airport_Crew_2_days_OD__c');
        }
        
        //Medical Clearance - International Qantas Supplied
        if(cs.QCC_Specific_Needs__r.QCC_PNR_Updated_MCOQS__c == true){
            listIQ.add('QCC_PNR_Updated_MCOQS__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_MEDA_Completed_Approved_MCQS__c == true){
            listIQ.add('QCC_MEDA_Completed_Approved_MCQS__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Quote_Provided_to_Customer_MCOQS__c == true){
            listIQ.add('QCC_Quote_Provided_to_Customer_MCOQS__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Customer_has_accepted_Quote_MCOQS__c == true){
            listIQ.add('QCC_Customer_has_accepted_Quote_MCOQS__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Confirmation_sent_to_Customer_MCOQS__c == true){
            listIQ.add('QCC_Confirmation_sent_to_Customer_MCOQS__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Notify_Eng_Airport_Crew_2_days_QS__c == true){
            listIQ.add('QCC_Notify_Eng_Airport_Crew_2_days_QS__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Oxygen_Ordered__c == true){
            listIQ.add('QCC_Oxygen_Ordered__c');
        }
        
        //International Travel
        if(cs.QCC_Specific_Needs__r.QCC_PNR_Updated_MCIT__c == true){
            listIT.add('QCC_PNR_Updated_MCIT__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_MEDA_Completed_Approved_MCIT__c == true){
            listIT.add('QCC_MEDA_Completed_Approved_MCIT__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Confirmation_sent_to_Customer_MCIT__c == true){
            listIT.add('QCC_Confirmation_sent_to_Customer_MCIT__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Notify_Eng_Airport_Crew_2_days_IT__c == true){
            listIT.add('QCC_Notify_Eng_Airport_Crew_2_days_IT__c');
        }
        
        //Stretcher
        if(cs.QCC_Specific_Needs__r.QCC_Update_PNR_MCST__c == true){
            listST.add('QCC_Update_PNR_MCST__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Update_Intelex__c == true){
            listST.add('QCC_Update_Intelex__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Booking_Created__c == true){
            listST.add('QCC_Booking_Created__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Payment_Received__c == true){
            listST.add('QCC_Payment_Received__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_MEDA_Clearance_Confirmed__c == true){
            listST.add('QCC_MEDA_Clearance_Confirmed__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Final_Confirmation_Sent_to_Requester__c == true){
            listST.add('QCC_Final_Confirmation_Sent_to_Requester__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Quote_Provided_to_Requester_MCST__c == true){
            listST.add('QCC_Quote_Provided_to_Requester_MCST__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Notify_Departure_Airport_3_Days_ST__c == true){
            listST.add('QCC_Notify_Departure_Airport_3_Days_ST__c');
        }

        //ServiceDog
        if(cs.QCC_Specific_Needs__r.QCC_Compliance_Outcome_Received_SD__c == true){
            listSD.add('QCC_Compliance_Outcome_Received_SD__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Updating_Service_Dog_Register__c == true){
            listSD.add('QCC_Updating_Service_Dog_Register__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_PNR_Updated_SD__c == true){
            listSD.add('QCC_PNR_Updated_SD__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Notify_Cabin_Crew_CJMs_SD__c == true){
            listSD.add('QCC_Notify_Cabin_Crew_CJMs_SD__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Outcome_Confirmation_Sent_to_Cst_SD__c == true){
            listSD.add('QCC_Outcome_Confirmation_Sent_to_Cst_SD__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Compliance_Approval_Request_Sent_SD__c == true){
            listSD.add('QCC_Compliance_Approval_Request_Sent_SD__c');
        }

        //Baggage CBBG
        if(cs.QCC_Specific_Needs__r.QCC_Update_PNR_CBBG__c == true){
            listCBBG.add('QCC_Update_PNR_CBBG__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Seating_Allocated_for_Customer_CBBG__c == true){
            listCBBG.add('QCC_Seating_Allocated_for_Customer_CBBG__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Notify_Airport_and_Crew_1_Day__c == true){
            listCBBG.add('QCC_Notify_Airport_and_Crew_1_Day__c');
        }
        
        //Baggage MBW
        if(cs.QCC_Specific_Needs__r.QCC_Update_PNR_MBW__c == true){
            listMBW.add('QCC_Update_PNR_MBW__c');
        }
        if(cs.QCC_Specific_Needs__r.QCC_Confirmation_Sent_to_Requestor_MBW__c == true){
            listMBW.add('QCC_Confirmation_Sent_to_Requestor_MBW__c');
        }
        
        requestTypeList.strWheelChair = listWC;
        requestTypeList.strNoEquipment = listNE;
        requestTypeList.strCBAP = listCBAP;
        requestTypeList.strOxygenDomestic = listOD;
        requestTypeList.strIntQantas = listIQ;
        requestTypeList.strIntTravel = listIT;
        requestTypeList.strMCStretcher = listST;
        requestTypeList.strServiceDog = listSD;
        requestTypeList.strBaggageCBBG = listCBBG;
        requestTypeList.strBaggageMBW = listMBW;
        
        return requestTypeList;
        
    }
    public class RequestTypeWrapper{
        @AuraEnabled public List<String> strWheelChair {get; set;}
        @AuraEnabled public List<String> strNoEquipment {get; set;}
        @AuraEnabled public List<String> strCBAP{get; set;}
        @AuraEnabled public List<String> strOxygenDomestic {get; set;}
        @AuraEnabled public List<String> strIntQantas {get; set;}        
        @AuraEnabled public List<String> strIntTravel {get; set;}        
        @AuraEnabled public List<String> strMCStretcher {get; set;}
        @AuraEnabled public List<String> strServiceDog {get; set;}
        @AuraEnabled public List<String> strBaggageCBBG {get; set;}
        @AuraEnabled public List<String> strBaggageMBW {get; set;} 
        
    }
    @AuraEnabled
    public static List<metaDataWrapper> getMetadataFields(){
        
        List<metaDataWrapper> wrapperFieldsList = new List<metaDataWrapper>();
        
        List<QCC_Specific_Needs_Fields__mdt> sectionFields = [SELECT Id, label, Record_Form_Fields__c 
                                                              FROM QCC_Specific_Needs_Fields__mdt
                                                             ];
        for(QCC_Specific_Needs_Fields__mdt fieldsLoop : sectionFields){
            metaDataWrapper wrapperFields = new metaDataWrapper();
            List<String> fields = fieldsLoop.Record_Form_Fields__c.split(',');
            List<String> newStringList = new List<String>();
            for(String mdFields: fields){
                newStringList.add(mdFields.trim());
            }
            wrapperFields.fields = newStringList;
            wrapperFields.sectionName = fieldsLoop.label;
            wrapperFieldsList.add(wrapperFields);
        }
        
        return wrapperFieldsList;
    }
    
    public class metaDataWrapper{
        @AuraEnabled public List<String> fields {get; set;}
        @AuraEnabled public String sectionName {get; set;}
    }
}