force-app/main/default/objects/EventActionPlan__c/EventActionPlan__c.object-meta.xml
<CustomObject>
    <description>QCC:  CJM will enter the plans to overcome the event.</description>
    <label>Event Action Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Recovery Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EventActionPlan__c/fields/ActionCompleted__c.field-meta.xml
<CustomField>
    <fullName>ActionCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IOC Action Completed check box.</description>
    <label>Action Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/Arrangement_Comments__c.field-meta.xml
<CustomField>
    <fullName>Arrangement_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrangement Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/Arrangements_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Arrangements_Indicator__c</fullName>
    <label>Arrangements Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/Eligibility_Comments__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Eligibility Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/Eligibility_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Indicator__c</fullName>
    <label>Eligibility Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/Expense_Claim_Guide__c.field-meta.xml
<CustomField>
    <fullName>Expense_Claim_Guide__c</fullName>
    <label>Expense Claim Guide</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/Expense_Claim_Guide_Comments__c.field-meta.xml
<CustomField>
    <fullName>Expense_Claim_Guide_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expense Claim Guide Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/FlightEvent__c.field-meta.xml
<CustomField>
    <fullName>FlightEvent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Lookup to Flight Event</description>
    <label>Flight Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Action Plans</relationshipLabel>
    <relationshipName>Recovery_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RecoveryActionPlanController.cls
public with sharing class RecoveryActionPlanController {
    @AuraEnabled(cacheable=false)
    public static List<EventActionPlan__c> getReimbursementData(Id recordId, String name) {
        
        return [
            SELECT Id, Name, Eligibility_Comments__c, Arrangement_Comments__c, Expense_Claim_Guide_Comments__c, 
                   Eligibility_Indicator__c, Arrangements_Indicator__c, Expense_Claim_Guide__c
            FROM EventActionPlan__c
            WHERE FlightEvent__c = :recordId 
              AND Name = :name AND ActionCompleted__c = true
        ];
    }
}