force-app/main/default/objects/Discount_List__c/Discount_List__c.object-meta.xml
<CustomObject>
    <label>Proposal Fare Discount</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Proposal Discount Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Fare Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount_List__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field stores discount values. Proposal 2 Tier Changes - CRM 5209</description>
    <label>Tier 2 / Max</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount_List__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal Name</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Proposal Fare Discounts</relationshipLabel>
    <relationshipName>Fare_Structure_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Custom object to replace standard Quote object</description>
    <label>Proposal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QEC_ProposalFareDiscountsControllerTest.cls
/**********************************************************************
Name:  QEC_ProposalFareDiscountsControllerTest
Copyright © 2019  Qantas Airways.
======================================================
Req: 
QEC - inline Editing the fare discounts on proposal
======================================================
Purpose:                                                            
Test class for QEC_ProposalFareDiscountsController
======================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE              DETAIL
1.0 	Ram Kolli       05/06/2019      Initial Development
========================================================
Methods
1. validateTestDataActiveProposal() - performs data insert and call QEC_ProposalFareDiscountsController methods
***********************************************************************/
@isTest
public class QEC_ProposalFareDiscountsControllerTest {
    
    static testMethod void validateTestDataActiveProposal() {
        List<Account> accList = TestUtilityDataClassQantas.getAccounts();
        List<Opportunity> oppList = TestUtilityDataClassQantas.getOpportunities(accList);
        List<Proposal__c> proposalList = TestUtilityDataClassQantas.getProposal(oppList);
        
        Test.startTest();               
            try{
                List<Discount_List__c> discList = [SELECT Id, Discount__c from Discount_List__c where Proposal__r.id =: proposalList[0].id];
                
                //Invoke the controller Method
                String JSONString = JSON.serialize(discList);
                QEC_ProposalFareDiscountsController.getFareDiscounts(proposalList[0].Id);
                QEC_ProposalFareDiscountsController.saveDiscountObject(JSONString);
                
            }catch(Exception e){
                System.debug('Error Occured: '+e.getMessage());
            } 
            Test.stopTest(); 
        }
    
     static testMethod void validateDiscountListInsertion() {
        TestUtilityDataClassQantas.enableTriggers();
         List<Account> accList = TestUtilityDataClassQantas.getAccounts();
        List<Opportunity> oppList = TestUtilityDataClassQantas.getOpportunities(accList);
        List<Proposal__c> proposalList = TestUtilityDataClassQantas.getProposal(oppList);
        
       // Test.startTest();               
            try{
                List<Discount_List__c> discList = [SELECT Id, Discount__c from Discount_List__c where Proposal__r.id =: proposalList[0].id];
                
                //Invoke the controller Method
                String JSONString = JSON.serialize(discList);
                QEC_ProposalFareDiscountsController.getFareDiscounts(proposalList[0].Id);
                QEC_ProposalFareDiscountsController.saveDiscountObject(JSONString);
               
                
            }catch(Exception e){
                System.debug('Error Occured: '+e.getMessage());
            } 
           // Test.stopTest(); 
        }
    
    static testMethod void testDiscountListHandler() {
        
         TestUtilityDataClassQantas.enableTriggers();
         List<Account> accList = TestUtilityDataClassQantas.getAccounts();
        List<Opportunity> oppList = TestUtilityDataClassQantas.getOpportunities(accList);
        List<Proposal__c> proposalList = TestUtilityDataClassQantas.getProposal(oppList);
         List<Discount_List__c> discList = new List<Discount_List__c>();
        Map<Id, Discount_List__c> newDiscList = new Map <Id, Discount_List__c> ([SELECT Id, Discount__c from Discount_List__c where Proposal__r.id =: proposalList[0].id]);
        
        for (Discount_List__c  dis : newDiscList.values()){
         
           Discount_List__c dis1  = new Discount_List__c();
            dis1.id = dis.Id;
            dis1.Discount__c = 60;
            discList.add(dis1);
            
        }

    		DiscountListHandler.afterApprovalsDiscountChanged(discList,newDiscList);
        DiscountListHandler.handleAfterDelete(discList);
        
        }
    
}