force-app/main/default/objects/AirlineCarrierCodes__c/AirlineCarrierCodes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>QCC: Airline carrier codes</description>
    <label>AirlineCarrierCodes</label>
</CustomObject>

force-app/main/default/objects/AirlineCarrierCodes__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>QCC: Airline Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AMEX_Response_Code_Setting__mdt/AMEX_Response_Code_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Stores the AMEX Response Code in Salesforce and this code is picked up by ETL to AMEX</description>
    <label>AMEX Response Code Setting</label>
    <pluralLabel>AMEX Response Code Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AMEX_Response_Code_Setting__mdt/fields/AMEXResponseCode__c.field-meta.xml
<CustomField>
    <fullName>AMEXResponseCode__c</fullName>
    <description>Stores the AMEX Response Code value</description>
    <label>AMEXResponseCode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <default>true</default>
                <label>D</label>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AMEX_Response_Code_Setting__mdt/fields/Corporate_Deal__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Deal__c</fullName>
    <description>Stores the Corporate Deal value for AMEX Code Calculation</description>
    <label>Corporate Deal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <default>true</default>
                <label>Y</label>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AMEX_Response_Code_Setting__mdt/fields/Customer_Requested_Choice__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Choice__c</fullName>
    <description>Stores the Customer Requested Choice for AMEX Response Code Calculation</description>
    <label>Customer Requested Choice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AMEX_Response_Code_Setting__mdt/fields/QBR_Override__c.field-meta.xml
<CustomField>
    <fullName>QBR_Override__c</fullName>
    <description>Stores the QBR Override for AMEX Response Code Calculation</description>
    <label>QBR Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <default>true</default>
                <label>Y</label>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AMEX_Response_Code_Setting__mdt/fields/Travel_Agent__c.field-meta.xml
<CustomField>
    <fullName>Travel_Agent__c</fullName>
    <description>Stores the Travel Agent for AMEX Response code Calculation</description>
    <label>Travel Agent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <default>true</default>
                <label>Y</label>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conga_Email_Template_Config__mdt/Conga_Email_Template_Config__mdt.object-meta.xml
<CustomObject>
    <description>(Platform change)</description>
    <label>Conga Email Template Config</label>
    <pluralLabel>Conga Email Template Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Qantas_API__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <description>Stores the ClientId of the system to be integrated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ClientId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <description>Stores the Client Secret of the System to be integrated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ClientSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>Allows to set the Endpoint of the system to be integrated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/fields/GrantType__c.field-meta.xml
<CustomField>
    <fullName>GrantType__c</fullName>
    <description>Stores the Grant Type of the system to be integarted</description>
    <encryptionScheme>None</encryptionScheme>
    <label>GrantType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Sets the method for the system to be integrated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/fields/QCC_Extended_Scope__c.field-meta.xml
<CustomField>
    <fullName>QCC_Extended_Scope__c</fullName>
    <description>This field holds the extended scope that the original Scope field cannot handle.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field holds the extended scope that the original Scope field cannot handle.</inlineHelpText>
    <label>Extended Scope</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>QCC: Scope to be used when generating the access token</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>CRM-7281: Stores the Token of the system to be integarted</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Value__c.field-meta.xml
<CustomField>
    <fullName>Config_Value__c</fullName>
    <description>Text values used in the code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_BookingCodeMappings__c/QCC_BookingCodeMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>QCC: Mappings related to Booking record</description>
    <label>QCC_BookingCodeMappings</label>
</CustomObject>

force-app/main/default/objects/QCC_BookingCodeMappings__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>QCC: The status value for the status Code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomSettingsUtilities.cls
/*----------------------------------------------------------------------- 
File name:      CustomSettingsUtilities.cls
Author:         Praveen Sampath
Company:        Capgemini  
Description:    This class is created as Utill class for Custom Settings.
Test Class:     
Created Date :  28/10/2016
<Date>      <Authors Name>     <Brief Description of Change>
************************************************************************************************
History
************************************************************************************************
05-May-2017    Praveen S               Added  getAmexResponseCodeForAccount and getAllAmexResponseCode Methods
31-Oct-2017    Praveen S               Added  getToken Method
31-Oct-2017    Praveen S               Added  getQantasCAPAPI Method
------------------------------------------------------------------------------------------------*/
public without sharing class CustomSettingsUtilities{ // CRM 13075 added without sharing as this class is  retrieving Qantas_API__c records
    @TestVisible private static Boolean QueryExceptionforTest = false;
     
    //Returns an individual record value from QantasConfigData__c custom setting. If the record is not found for the input parameters, it returns null.
    public static String getConfigDataMap(String paramName){
            if (paramName != ''){
                if(QantasConfigData__c.getValues(paramName)!=null){
                    QantasConfigData__c configData = QantasConfigData__c.getValues(paramName);
                    string confVal = configData.Config_Value__c;
                    return confVal;
                }
            }           
        return ''; 
    }

    //Returns an individual record value from QCC_BookingCodeMappings__c custom setting. If the record is not found for the input parameters, it returns null.
    public static String getBookingCodeMapping(String paramName){
            if (paramName != ''){
                if(QCC_BookingCodeMappings__c.getValues(paramName)!=null){
                    QCC_BookingCodeMappings__c configData = QCC_BookingCodeMappings__c.getValues(paramName);
                    string confVal = configData.Value__c;
                    return confVal;
                }
            }           
        return ''; 
    }

    //Returns an individual record value from AirlineCarrierCodes__c custom setting. If the record is not found for the input parameters, it returns null.
    public static String getAirlineCarrierCodes(String paramName){
            if (paramName != ''){
                if(AirlineCarrierCodes__c.getValues(paramName)!=null){
                    AirlineCarrierCodes__c configData = AirlineCarrierCodes__c.getValues(paramName);
                    string confVal = configData.Value__c;
                    return confVal;
                }
            }           
        return ''; 
    }
    
   
    //Returns an individual record value from Qantas_API__c custom Object. If the record is not found for the input parameters, it returns null.
    public static Qantas_API__c getQantasCAPAPI(String paramName){
            if (paramName != ''){
                List<Qantas_API__c> qantasAPI =[ Select Name, ClientId__c, ClientSecret__c, EndPoint__c, GrantType__c,
                                           Method__c, Token__c, Scope__c, LastModifiedDate, QCC_Extended_Scope__c from Qantas_API__c where Name =: paramName];
                if(qantasAPI!=null && qantasAPI.size() > 0){
                    return qantasAPI[0];
                }
            }           
        return null; 
    }

    //Returns Map of AMEX_Response_Code_Setting__mdt Custom metadata.
    public static Map<String, String> getAllAmexResponseCode(){
        Map<String, String> mapAmexResCode = new Map<String, String>();
        for(AMEX_Response_Code_Setting__mdt amexCode: [ Select Id, Travel_Agent__c, Corporate_Deal__c, QBR_Override__c, 
                                                        Customer_Requested_Choice__c, AMEXResponseCode__c from 
                                                        AMEX_Response_Code_Setting__mdt ] )
        {
            String mapKey = 'ARC_'+''+amexCode.Travel_Agent__c+''+amexCode.Corporate_Deal__c+''+amexCode.QBR_Override__c+''+amexCode.Customer_Requested_Choice__c;
            mapAmexResCode.put(mapKey, amexCode.AMEXResponseCode__c);
        }
        return mapAmexResCode;
    }

    //Returns Map of AMEX_Response_Code_Setting__mdt Custom metadata.
    public static String getAmexResponseCodeForAccount( Map<String, String> mapAmexResCode, String agency, String corporateDeal, 
                                                        String qbrOverride, String customerChoise ){
        String  amexCode;
        String amexResCodeKey = 'ARC_'+''+agency+''+corporateDeal+''+qbrOverride+''+customerChoise;
        amexCode = mapAmexResCode.containsKey(amexResCodeKey)?mapAmexResCode.get(amexResCodeKey):'';        
        return amexCode;
    }

    //Returns Map of Conga_Email_Template_Config__mdt Custom metadata.
    public static Map<String, String> getCongaEmailTemplateId(){
        Map<String, String> mapCongaTemplateId = new Map<String, String>();
        for(Conga_Email_Template_Config__mdt template: [ SELECT Id, DeveloperName, MasterLabel, Label, Record_Type_Name__c, Case_Type__c, Email_Template__c, 
                                                            Email_Template_Id__c, Record_Type_Id__c 
                                                         FROM Conga_Email_Template_Config__mdt ] )
        {
            String mapKey = template.Record_Type_Id__c+':'+template.Case_Type__c+':'+template.Email_Template__c;
            mapCongaTemplateId.put(mapKey, template.Email_Template_Id__c);
        }
        return mapCongaTemplateId;
    }

}