force-app/main/default/objects/QAC_Manage_File__mdt/QAC_Manage_File__mdt.object-meta.xml
<CustomObject>
    <label>QAC Manage File</label>
    <pluralLabel>QAC Manage Files</pluralLabel>
</CustomObject>

force-app/main/default/objects/QAC_Manage_File__mdt/fields/Case_Closed__c.field-meta.xml
<CustomField>
    <fullName>Case_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case_Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QAC_Manage_File__mdt/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <label>Case_Record_Type</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QAC_Manage_File__mdt/fields/No_of_Days_from_Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>No_of_Days_from_Closed_Date__c</fullName>
    <description>QAC - Manage delete file.</description>
    <label>No_of_Days_from_Closed_Date</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QAC_ManageFilesBatchScheduler.cls
/*
 * Created By  : Ajay | TCS | Cloud Developer 
 * Modified By : Jay (Purpose: Test class has been written for this Scheduler class, code coverage:100%)
 * Modified By : Yuvaraj| TCS | Developer
 * Purpose : To Schedule the Batch Class
 * Dependent Batch Class : QAC_ManageFilesBatch
 * Test Class Name : QAC_ManageFilesBatch_Test.
*/
global class QAC_ManageFilesBatchScheduler implements Schedulable
{
    global void execute(SchedulableContext sc){
        Map<String,QAC_Manage_File__mdt> allMFmap = new Map<String,QAC_Manage_File__mdt>();
       // String rtName = 'Service Request';
        String rtServiceRequestName = 'Service Request';
        String rtQacContactUsSupportName = 'QAC Contact Us Support';
        Id recTypeServiceRequestId = GenericUtils.getObjectRecordTypeId('Case', rtServiceRequestName);
        Id recTypeQacContactUsSupportId = GenericUtils.getObjectRecordTypeId('Case', rtQacContactUsSupportName);      

        for(QAC_Manage_File__mdt eachFileData : [SELECT MasterLabel,No_of_Days_from_Closed_Date__c,Case_Record_Type__c,Case_Closed__c,DeveloperName
                                                 FROM QAC_Manage_File__mdt])
        {
            if(eachFileData != null){
                allMFmap.put(eachFileData.Case_Record_Type__c,eachFileData);
            }
        }
        //system.debug('allMFmap:'+allMFmap);
       // String rtId = QAC_PaymentsProcess.fetchRecordTypeId('Case',allMFmap.get(rtName).Case_Record_Type__c);
        //system.debug('rtId:'+rtId+' allMFmap.get(rtName).No_of_Days_from_Closed_Date__c:'+allMFmap.get(rtName).No_of_Days_from_Closed_Date__c+' allMFmap.get(rtName).Case_Closed__c:'+allMFmap.get(rtName).Case_Closed__c);
        Database.executeBatch(new QAC_ManageFilesBatch(recTypeServiceRequestId,
                                                       allMFmap.get(rtServiceRequestName).No_of_Days_from_Closed_Date__c,
                                                       allMFmap.get(rtServiceRequestName).Case_Closed__c));
        
              Database.executeBatch(new QAC_ManageFilesBatch(recTypeQacContactUsSupportId,
                                                       allMFmap.get(rtQacContactUsSupportName).No_of_Days_from_Closed_Date__c,
                                                       allMFmap.get(rtQacContactUsSupportName).Case_Closed__c));
    }
}