force-app/main/default/objects/Associated_Person__c/Associated_Person__c.object-meta.xml
<CustomObject>
    <description>To store incoming details regarding associated people to this account</description>
    <label>Member/Traveller</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Person Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member/Travellers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Person__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Relation to master Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Associated_People</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Person__c/fields/Active_Profile_Record__c.field-meta.xml
<CustomField>
    <fullName>Active_Profile_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating that this is an active Profile record.</description>
    <label>Active Profile Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Associated_Person__c/fields/Active_QBD_Record__c.field-meta.xml
<CustomField>
    <fullName>Active_QBD_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating that this is an active QBD record.</description>
    <label>Active QBD Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Associated_Person__c/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <description>To store incoming Frequent Flyer Number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>To store incoming last name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Person__c/fields/Last_Name_Match__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_Match__c</fullName>
    <formula>AND( Active_QBD_Record__c, Active_Profile_Record__c, UPPER(QBD_Last_Name__c ) == UPPER(Last_Name__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is driven by the comparision between &apos;QBD Last Name&apos; (that comes in as part of QBD request) and &apos;Last Name&apos; - this flag is checked if the two Last Name match (case insensitive).</inlineHelpText>
    <label>Last Name Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Associated_Person__c/fields/QBD_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>QBD_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>To capture the Last Name that comes in as part of QBD registration or QBD Traveller request. This is compared with the &quot;Last Name&quot; that comes in from Profile and this comparision determines the &apos;Last Name Match&apos; flag.</inlineHelpText>
    <label>QBD Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Person__c/fields/Sync_Traveller_Override__c.field-meta.xml
<CustomField>
    <fullName>Sync_Traveller_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>System Administrators can use this flag to override the &apos;last name&apos; matching logic so that the traveller record can be forced to flow across to the downstream system.</inlineHelpText>
    <label>Sync Traveller Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>To capture the new user&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s last name, for whom the request is being logged.</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Change of TMC</fullName>
            </value>
            <value>
                <fullName>Variation to Discounts</fullName>
            </value>
            <value>
                <fullName>Incentive Fares</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Still In Negotiation</fullName>
            </value>
            <value>
                <fullName>Global RFP</fullName>
            </value>
            <value>
                <fullName>Company Operating Environment</fullName>
            </value>
            <value>
                <fullName>QF Internal Requirement</fullName>
            </value>
            <value>
                <fullName>QBD Registration added for New Customer</fullName>
            </value>
            <value>
                <fullName>Duplicate QBD Registration Identified</fullName>
            </value>
            <value>
                <fullName>Agency Account Identified</fullName>
            </value>
            <value>
                <fullName>QBD Registration updated for Existing Customer</fullName>
            </value>
            <value>
                <fullName>No matching accounts with Aquire membership</fullName>
            </value>
            <value>
                <fullName>Multiple agency accounts identified</fullName>
            </value>
            <value>
                <fullName>Multiple matching accounts with Aquire membership</fullName>
            </value>
            <value>
                <fullName>No Account Identified</fullName>
            </value>
            <value>
                <fullName>Unique Account Identified</fullName>
            </value>
            <value>
                <fullName>Multiple Accounts Identified</fullName>
            </value>
            <value>
                <fullName>New QBD Traveller added</fullName>
            </value>
            <value>
                <fullName>Existing Member updated with QBD Traveller details</fullName>
            </value>
            <value>
                <fullName>Duplicate QBD Traveller identified</fullName>
            </value>
            <value>
                <fullName>Duplicate Members identified</fullName>
            </value>
            <value>
                <fullName>Multiple QBD Accounts identified</fullName>
            </value>
            <value>
                <fullName>No QBD Account identified</fullName>
            </value>
            <value>
                <fullName>Last Name Mismatch</fullName>
            </value>
            <value>
                <fullName>New Account Creation</fullName>
            </value>
            <value>
                <fullName>Deactivate Account</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>Account Related Updates</fullName>
            </value>
            <value>
                <fullName>Tradesite Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QBD.recordType-meta.xml
<RecordType>
    <fullName>QBD</fullName>
    <active>false</active>
    <businessProcess>QBD</businessProcess>
    <label>QBD</label>
</RecordType>

force-app/main/default/objects/QBD_Case_Subtype__c/QBD_Case_Subtype__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores the case picklist values values for subtype used in apex code</description>
    <label>QBD Case Subtype</label>
</CustomObject>

force-app/main/default/objects/QBD_Case_Subtype__c/fields/PickList_value__c.field-meta.xml
<CustomField>
    <fullName>PickList_value__c</fullName>
    <description>Case subtype value used in apex code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PickList value</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MemberTriggerHandler.cls
/**********************************************************************************************************************************
Modified Date   : 29/01/19 (DD/MM/YYYY)
Added By        : Vinothkumar Balasubramanian
JIRA            : CRM - 3494
Version         : V2.0 - Commented this class after discussing with Nijo as this functionality has been deprecated

**********************************************************************************************************************************/

public class MemberTriggerHandler
{
  
  /*public static void processCases(List<Associated_Person__c> newList, Map<Id, Associated_Person__c> oldMap){
      
      Set<String> ffSet = new Set<String>();
      Map<String, List<Case>> casesMap = new Map<String, List<Case>>();
      Set<Case> subtypeCases = new Set<Case>();
      Set<Case> closeCases = new Set<Case>();
      List<Case> updateAllCases = new List<Case>();
      Map<string, QBD_Case_Subtype__c> mapCodes = QBD_Case_Subtype__c.getAll();
      
      for(Associated_Person__c ap : newList){
          if(ap.Active_Profile_Record__c != oldMap.get(ap.Id).Active_Profile_Record__c || ap.Active_QBD_Record__c != oldMap.get(ap.Id).Active_QBD_Record__c || ap.Last_Name_Match__c != oldMap.get(ap.Id).Last_Name_Match__c || ap.Last_Name__c != oldMap.get(ap.Id).Last_Name__c || ap.QBD_Last_Name__c != oldMap.get(ap.Id).QBD_Last_Name__c || ap.Sync_Traveller_Override__c != oldMap.get(ap.Id).Sync_Traveller_Override__c){
              ffSet.add(ap.Frequent_Flyer_Number__c);
          }
      }
      
      if(ffSet.size() > 0) casesMap = allRelatedCases(ffSet);
      
      for(Associated_Person__c ap : newList){
        if(ap.Active_QBD_Record__c && ap.Active_Profile_Record__c){      
             if(ap.Active_Profile_Record__c != oldMap.get(ap.Id).Active_Profile_Record__c || ap.Active_QBD_Record__c != oldMap.get(ap.Id).Active_QBD_Record__c || ap.Last_Name_Match__c != oldMap.get(ap.Id).Last_Name_Match__c || ap.Last_Name__c != oldMap.get(ap.Id).Last_Name__c || ap.QBD_Last_Name__c != oldMap.get(ap.Id).QBD_Last_Name__c || ap.Sync_Traveller_Override__c != oldMap.get(ap.Id).Sync_Traveller_Override__c){
                  if(casesMap.containsKey(ap.Frequent_Flyer_Number__c)){
                      List<Case> casesList = casesMap.get(ap.Frequent_Flyer_Number__c);
                      for(Case myCase : casesList){
                          if(myCase.AccountId == ap.Account__c){
                              if(ap.Last_Name_Match__c == false && ap.Sync_Traveller_Override__c == false){
                                 if(myCase.Sub_Type__c == mapCodes.get('New QBD Traveller added').PickList_value__c || myCase.Sub_Type__c  == mapCodes.get('Member updated with QBD Traveller').PickList_value__c){
                                      subtypeCases.add(myCase);
                                 }
                              }
                              if(ap.Last_Name_Match__c == true || ap.Sync_Traveller_Override__c == true){                      
                                      closeCases.add(myCase);                      
                              }
                           }
                       }                   
                  }
              }
         } 
      }
      
      for(Case cs : subtypeCases){
          cs.Sub_Type__c = mapCodes.get('Last Name Mismatch').PickList_value__c;
          updateAllCases.add(cs);
      }
      
      for(Case cs1 : closeCases){
          cs1.Status = 'Closed';
          updateAllCases.add(cs1);
      }
      
      Database.Update(updateAllCases);      
  }
  
  public static Map<String, List<Case>> allRelatedCases(Set<String> allMembers){
      Map<String, List<Case>> casesMap = new Map<String, List<Case>>();
      Map<string, QBD_Case_Subtype__c> mapCodes = QBD_Case_Subtype__c.getAll();
      List<String> caseSubType = new List<String>();
      caseSubType.add(mapCodes.get('New QBD Traveller added').PickList_value__c);
      caseSubType.add(mapCodes.get('Member updated with QBD Traveller').PickList_value__c);
      caseSubType.add(mapCodes.get('Last Name Mismatch').PickList_value__c);
      List<Case> allCases = [SELECT Id, Status, Frequent_Flyer_Number__c, Sub_Type__c, AccountId FROM Case where Status != 'Closed' AND Frequent_Flyer_Number__c IN :allMembers AND Sub_Type__c IN :caseSubType];
      
      for(Case cs : allCases){
          if(!casesMap.containsKey(cs.Frequent_Flyer_Number__c)) casesMap.put(cs.Frequent_Flyer_Number__c, new List<Case>());
          casesMap.get(cs.Frequent_Flyer_Number__c).add(cs);
      }
      return casesMap;
  }*/

}