force-app/main/default/objects/EnableValidationRule__c/EnableValidationRule__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Profile Override Validation Rule</description>
    <label>Enable Validation Rule</label>
</CustomObject>

force-app/main/default/objects/EnableValidationRule__c/fields/PreventAttachmentDelete__c.field-meta.xml
<CustomField>
    <fullName>PreventAttachmentDelete__c</fullName>
    <defaultValue>true</defaultValue>
    <description>QCC: Used in Attachment Trigger Helper, Block user from deleting the attachment.</description>
    <label>PreventAttachmentDelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AttachmentTriggerHelper.cls
public class AttachmentTriggerHelper {

	public static void eligiblityCheckOnAttachmentDel(List<Attachment> lstAttachment){
		try{
			Boolean isPreventDelete = false;
		
			
           if(EnableValidationRule__c.getInstance(userInfo.getUserId()) != Null ){
				isPreventDelete = EnableValidationRule__c.getInstance(userInfo.getUserId()).PreventAttachmentDelete__c;
			}

			if(isPreventDelete){
				for(Attachment objAtt: lstAttachment){
					if(String.valueOf(objAtt.ParentId).startsWith('02s')){
						objAtt.addError(CustomSettingsUtilities.getConfigDataMap('QCC_PreventAttDelete'));
					}
				}
			}
		}
		catch(Exception ex){
			system.debug('ex###############'+ex);
	        CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC - Attachment Trigger', 'AttachmentTriggerHelper', 
	                                'eligiblityCheckOnAttachmentDel', String.valueOf(''), String.valueOf(''),false,'', ex);
	    }
	}
}