force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/SchemeFees__c/SchemeFees__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Loyalty Holds the Scheme Fees Details</description>
    <label>Scheme Fees</label>
</CustomObject>

force-app/main/default/objects/SchemeFees__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Scheme_Type__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheme Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SchemeFee_Batch_Scheduler.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Praveen Sampath 
Company:       Capgemini
Description:   Schedule class to run when the Custom Setting value on Scheme Fee is changed
Inputs:        
Test Class:     
************************************************************************************************
History
************************************************************************************************

-----------------------------------------------------------------------------------------------------------------------*/
global class SchemeFee_Batch_Scheduler implements Schedulable {
         
    global void execute(SchedulableContext sc) {
        DateTime dtNow =  DateTime.now();
        DateTime dtBefor24hrs = dtNow.addHours(-24);
        boolean isGSTChanged = false;
        List<SchemeFees__c> lstSchemeFee  = [select Id, Scheme_Type__c, Currency__c, LastModifiedDate from 
                                              SchemeFees__c where LastModifiedDate >: dtBefor24hrs ];
       

        List<String> lstName = CustomSettingsUtilities.getConfigDataMap('GSTSettings').split(';');
        system.debug('lstName#######'+lstName);
        List<QantasConfigData__c> lstConfig  = [select Id, LastModifiedDate from QantasConfigData__c where 
                                                LastModifiedDate >: dtBefor24hrs and Name IN: lstName];

        if(lstConfig != Null && lstConfig.size()>0){
            isGSTChanged = true;
        }
       
        if(lstSchemeFee.size()>0 || isGSTChanged){
            SchemeFee_Daily_Update_Check_Batch runBatch = new SchemeFee_Daily_Update_Check_Batch(isGSTChanged, lstSchemeFee);
            Database.executeBatch(runBatch);
        }
    }
}