force-app/main/default/objects/Affected_Passenger__c/Affected_Passenger__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures the affected passenger list for a specific Event. This stores passenger information pertaining to the specific Event, such as, FF tier (snapshot), Cabin, Seat No, Pre and Post Flight</description>
    <label>Passenger</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Passenger__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: the related Case for Insurance Letter creation</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Affected_Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Passenger_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Sequence__c</fullName>
    <label>Passenger Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/QAC_Request_Country__c.field-meta.xml
<CustomField>
    <fullName>QAC_Request_Country__c</fullName>
    <label>QAC Request Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>ASIA</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>EUMEIAFR</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Fee_Applies__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Applies__c</fullName>
    <label>Service Fee Applies?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes - Apply</fullName>
            </value>
            <value>
                <fullName>Yes - Waive</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Travel_Type__c.field-meta.xml
<CustomField>
    <fullName>Travel_Type__c</fullName>
    <label>Travel Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Product_Credit_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Credit_Value__c</fullName>
    <description>QAC</description>
    <label>Product Credit Value</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RFIC_code__c.field-meta.xml
<CustomField>
    <fullName>RFIC_code__c</fullName>
    <label>RFIC code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFPT</fullName>
            </value>
            <value>
                <fullName>AFPS</fullName>
            </value>
            <value>
                <fullName>ICS1</fullName>
                <isActive>false</isActive>
                <label>ICS1</label>
            </value>
            <value>
                <fullName>ICS2</fullName>
                <isActive>false</isActive>
                <label>ICS2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QAC_Pricebook_Detail__mdt/QAC_Pricebook_Detail__mdt.object-meta.xml
<CustomObject>
    <label>QAC Pricebook Detail</label>
    <pluralLabel>QAC Pricebook Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/QAC_Pricebook_Detail__mdt/fields/Pricebook_Channel__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Channel__c</fullName>
    <label>Pricebook Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
                <default>true</default>
                <label>Call</label>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QAC_Pricebook_Detail__mdt/fields/Pricebook_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Country_Code__c</fullName>
    <label>Pricebook Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
                <default>true</default>
                <label>AU</label>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
                <isActive>false</isActive>
                <label>UK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Payment__c/Service_Payment__c.object-meta.xml
<CustomObject>
    <label>Service Payment</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Service Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Payments</relationshipLabel>
    <relationshipName>Service_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Payment__c/fields/Payment_Currency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Currency__c</fullName>
    <label>Payment Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Payment__c/fields/Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Due_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Payment__c/fields/Quantity_UOM__c.field-meta.xml
<CustomField>
    <fullName>Quantity_UOM__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quantity UOM</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Payment__c/fields/RFIC_code__c.field-meta.xml
<CustomField>
    <fullName>RFIC_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RFIC code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Payment__c/fields/Total_Payable_credits__c.field-meta.xml
<CustomField>
    <fullName>Total_Payable_credits__c</fullName>
    <description>QAC</description>
    <label>Total Payable credits</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Payment__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Payments</relationshipLabel>
    <relationshipName>Service_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Total_Payable_Credits__c.field-meta.xml
<CustomField>
    <fullName>Total_Payable_Credits__c</fullName>
    <description>QAC</description>
    <label>Total Payable Credits</label>
    <summarizedField>WorkOrderLineItem.Product_Credit_Value__c</summarizedField>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Travel_Type__c.field-meta.xml
<CustomField>
    <fullName>Travel_Type__c</fullName>
    <label>Travel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Product_Credit_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Credit_Value__c</fullName>
    <description>QAC</description>
    <label>Product Credit Value</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Total_Payable_credits__c.field-meta.xml
<CustomField>
    <fullName>Total_Payable_credits__c</fullName>
    <description>QAC</description>
    <formula>Quantity *  Product_Credit_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Payable credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QAC_PaymentsProcess.cls
/*
* Created By : Ajay Bharathan | TCS | Cloud Developer 
* Purpose : Utility Class for Processing Payments 
* Referred in : QAC_ServiceReqCaseCreationProcess
  History
  ************************************************************************************************
  01-Jul-2019      Jay               Agency Credits related Changes.
  ************************************************************************************************
  
  Modified Date   : 30/11/19 (DD/MM/YYYY)
  Modified By     : Vinothkumar Balasubramanian
  JIRA            : CRM-4017
  Version         : V2.0 - Work Order Line Item Product Credit Value needs to calculate for Per Passenger
  
  Modified Date   : 11/02/2020 (DD/MM/YYYY)
  Modified By     : Vinothkumar Balasubramanian
  JIRA            : CRM-4166
  Version         : V3.0 - Payment Initiation Enabled for Online Cases
  
*/

public with sharing class QAC_PaymentsProcess 
{
    // do work order, work order line item, service payment record creation
    public static Map<String,SObject> doPaymentsCreation(String subTypeCombo, DateTime myCreatedDate, Case myCase, Boolean myPaxSeq)
    {
        Map<String,SObject> allPaymentResponses = new Map<String,SObject>();
        
        system.debug('myPaxSeq **'+myPaxSeq);
        
        if(String.isNotBlank(myCase.QAC_Request_Country__c) && String.isNotBlank(myCase.Travel_Type__c)){
            
            // to fetch Price Book Name, Product and PBE Id
            String PrBkName = fetchPBName(myCase);
            Product2 currentProd = fetchProduct(subTypeCombo.split('_')[0]);
            String pbId = (fetchPriceBook(PrBkName) != null) ? fetchPriceBook(PrBkName).Id : null;
            String pbeId = (currentProd != null) ? fetchPriceBookEntry(currentProd.Id,pbId).Id : null;
            String isoCode = (currentProd != null) ? fetchPriceBookEntry(currentProd.Id,pbId).CurrencyIsoCode : null;
                
            // create WO
            WorkOrder newWO = new WorkOrder();
            newWO.CaseId = myCase.Id;
            newWO.RecordTypeId = fetchRecordTypeId('WorkOrder','Service Request');
            newWO.StartDate = myCreatedDate;
            newWO.Travel_Type__c = myCase.Travel_Type__c;
            newWO.Pricebook2Id = pbId;
            newWO.Status = 'New';
            newWO.CurrencyIsoCode = isoCode;
            insert newWO;
            system.debug('newWO:'+newWO);
            allPaymentResponses.put(newWO.Id+'_WO',newWO);
            
            // create WOLI
            WorkOrderLineItem newWOLI = new WorkOrderLineItem();
            newWOLI.WorkOrderId = newWO.Id;
            newWOLI.RecordTypeId = fetchRecordTypeId('WorkOrderLineItem','Service Request');
            newWOLI.PricebookEntryId = pbeId;
            newWOLI.Quantity = Decimal.valueOf(calcQuantityforWOLI(myCase,currentProd,myPaxSeq));
            if(fetchPriceBookEntry(currentProd.Id,pbId).Product_Credit_Value__c != null ){
            newWOLI.Product_Credit_Value__c = fetchPriceBookEntry(currentProd.Id,pbId).Product_Credit_Value__c;
            }
            system.debug('newWOLI:'+newWOLI);
            insert newWOLI;
            allPaymentResponses.put(newWOLI.Id+'_WOLI',newWOLI);
            
            // to fetch Work Order and create Service Payments
            WorkOrder createdWO = fetchWorkOrder(newWO.Id);
            system.debug('WO Values'+createdWO);
            
            Service_Payment__c newSPay = new Service_Payment__c();
            newSPay.Case__c = myCase.Id;
            newSPay.RecordTypeId = fetchRecordTypeId('Service_Payment__c','Service Request');
            //Changes added as per JIRA:TS-3165
            newSPay.Payment_Due_Date__c = addBusinessDays(myCase, myCreatedDate, 3);
            //Changes End as per JIRA:TS-3165
            newSPay.Work_Order__c = createdWO.Id;
            newSPay.CurrencyIsoCode = isoCode;
            newSPay.Payment_Currency__c = createdWO.CurrencyIsoCode;
            newSPay.Total_Amount__c = createdWO.TotalPrice.setScale(2);
            newSPay.RFIC_code__c = currentProd.RFIC_code__c;
            newSPay.Quantity_UOM__c = currentProd.QuantityUnitOfMeasure;
            newSPay.Payment_Status__c = 'Pending';
      // Changes Start for CRM-4017
            //newSPay.Total_Payable_credits__c =  createdWO.Total_Payable_credits__c;
            newSPay.Total_Payable_credits__c = Decimal.valueOf(calcQuantityforWOLI(myCase,currentProd,myPaxSeq)) * createdWO.Total_Payable_credits__c;
            // Changes end for CRM-4017    
            insert newSPay;
            system.debug('newSPay:'+newSPay);
            
            allPaymentResponses.put(newSPay.Id+'_SP',newSPay);
            system.debug('all resp**'+allPaymentResponses);
        }
        return allPaymentResponses;
    }    
    
    public static WorkOrder fetchWorkOrder(Id woId){
        return [SELECT Id,CurrencyIsoCode,TotalPrice,Total_Payable_credits__c FROM WorkOrder WHERE Id =: woId];
    }
    
    public static Id fetchRecordTypeId(String obj, String rtName)
    {
        //String myId = Schema.getGlobalDescribe().get(obj).getDescribe().getRecordTypeInfosByName().get(rtName).getRecordTypeId();        
        List<Schema.DescribeSObjectResult> describes = Schema.describeSObjects(new String[] { obj }, SObjectDescribeOptions.DEFERRED);
        return describes[0].getRecordTypeInfosByName().get(rtName).getRecordTypeId();
    }
    
    public static String fetchPBName(Case myCase){
    // Changes Start for CRM-4166
    //String caseOrigin = (myCase.Origin == 'QAC Website') ? 'Online' : 'Call';
    Id caseId = myCase.Id; 
    String caseOrigin;
    
    for(Case eachCase : [Select Id, Origin, Service_Fee_Applies__c, QAC_Request_Country__c from Case where Id =: caseId]){
		if(eachCase.Origin == 'QAC Website' && String.isBlank(eachCase.Service_Fee_Applies__c)) caseOrigin = 'Online';
		else caseOrigin = 'Call';
    }
    //Changes End for CRM-4166
        String pbName = getPBData(myCase.QAC_Request_Country__c,caseOrigin);
        return pbName;
    }
    
    public static Pricebook2 fetchPriceBook(String pbName)
    {
        Pricebook2 myPricebook;
        if(String.isNotBlank(pbName))
        {
            for(Pricebook2 eachPB : [Select Id, Name, IsActive from Pricebook2 where Name =: pbName]){
                myPricebook = eachPB;                
            }
        }
        return myPricebook;
    }
    
    public static Product2 fetchProduct(String prodName)
    {
        Product2 myProd;
        for(Product2 eachProd : [Select Id,ProductCode,CurrencyIsoCode,Name,QuantityUnitOfMeasure,IsActive,RFIC_code__c
                                 FROM Product2 WHERE Name =: prodName LIMIT 1])
        {
            myProd = eachProd;            
        }
        return myProd;    
    }
    
    public static PricebookEntry fetchPriceBookEntry(Id prodId,Id pbId)
    {
        PricebookEntry myPBE;
        
        if(String.isNotBlank(prodId) && String.isNotBlank(pbId))
        {
            for(PricebookEntry eachPBE : [Select Id,Pricebook2id,Product2Id,CurrencyIsoCode,UnitPrice,ProductCode,IsActive,Product_Credit_Value__c
                                          FROM PricebookEntry WHERE Product2Id =: prodId AND Pricebook2id =: pbId LIMIT 1])
            {
                myPBE = eachPBE;    
            }
        }
        return myPBE;
    }
    
    // to calculate Quantity for LineItem
    public static Integer calcQuantityforWOLI(Case myCase, Product2 currentProd, Boolean paxExists)
    {
        Integer myQuantity;
        String myQuery;
        list<AggregateResult> results;
        Id caseId = myCase.Id;
        String pRTID = Schema.SObjectType.Affected_Passenger__c.getRecordTypeInfosByName().get('Service Request').getRecordTypeId();                    
        
        if(currentProd != null && currentProd.QuantityUnitOfMeasure == 'Ticket' && paxExists){
            if(myCase.Travel_Type__c == 'Domestic'){
                myQuery = 'Select Case__c, COUNT(Id) idCount, COUNT(Passenger_Sequence__c) notNull_qty,COUNT_DISTINCT(Passenger_Sequence__c) Distinct_qty from Affected_Passenger__c WHERE Case__c =: caseId AND RecordTypeId =: pRTID GROUP BY Case__c';
            }
            else if(myCase.Travel_Type__c == 'International'){
                myQuery = 'Select COUNT(Id) idCount from Affected_Passenger__c WHERE Case__c =: caseId AND RecordTypeId =: pRTID';   
            }
            results = Database.query(myQuery);
            
            if(results != null){
                for (AggregateResult ar : results){
                    system.debug('values Id:'+ar);
                    // with Null Values
                    if(myCase.Travel_Type__c == 'Domestic'){
                        myQuantity = ((Integer)ar.get('idCount') - (Integer)ar.get('notNull_qty')) + (Integer)ar.get('Distinct_qty'); }
                    else if(myCase.Travel_Type__c == 'International'){
                        myQuantity = ((Integer)ar.get('idCount'));}
                }
            }
        }
        else if(currentProd != null && currentProd.QuantityUnitOfMeasure == 'PNR'){
            myQuantity = 1;
        }
        return myQuantity;
    }
    
    // to add business days to due date
    public static Datetime addBusinessDays(Case myCase, Datetime currentDT, Integer noOfDays)
    {
        Integer businessDaysAdded = 0;
        while (businessDaysAdded < noOfDays) 
        {
            currentDT = currentDT.addDays(1);
            if (currentDT.format('E') != 'Sat' && currentDT.format('E') != 'Sun' && validWorkingDay(myCase.QAC_Request_Country__c,currentDT)) {
                // it's a business day, so add 1 to the counter that works towards the amount of days to add
                businessDaysAdded = businessDaysAdded + 1;
            } 
        }       
        return currentDT;
    }
    
    public static List<Holiday> getHolidays(String countryCode){
        String ccode = 'QAC '+countryCode+'%';
        List<Holiday> holidays = new list<Holiday>();
        
        for(Holiday eachHol : [Select h.StartTimeInMinutes, h.Name, h.ActivityDate From Holiday h WHERE h.Name LIKE :ccode]){
            if(eachHol != null){
                holidays.add(eachHol);    
            }
        }
        system.debug('holidays **'+holidays);
        return holidays;        
    }
    
    /*
    public static List<Holiday> holidays {
    get {
    if(holidays == null)
    holidays = [Select h.StartTimeInMinutes, h.Name, h.ActivityDate From Holiday h WHERE h.Name LIKE 'QAC%'];
    return holidays;
    }
    private set;
    }
    */
    
    public static boolean validWorkingDay(String countryCode,Datetime myDT)
    {
        Date currentDate = myDT.date();
        Date weekStart = currentDate.toStartofWeek();
        
        for(Holiday hDay : getHolidays(countryCode)){
            if(currentDate.daysBetween(hDay.ActivityDate) == 0) return false;
        }
        //return (weekStart.daysBetween(currentDate) == 0 || weekStart.daysBetween(currentDate) == 6) ? false : true ;
        return true ;
    }
    
    public static String getPBData(String countryCode, String origin){
        String pbName;
        for(QAC_Pricebook_Detail__mdt eachPBDmdt : [Select MasterLabel,Pricebook_Country_Code__c,DeveloperName,Pricebook_Channel__c
                                                    from QAC_Pricebook_Detail__mdt where Pricebook_Country_Code__c =: countryCode AND Pricebook_Channel__c =: origin])
        {
            if(eachPBDmdt != null){
                pbName = eachPBDmdt.MasterLabel;
                break;
            }
        }
        system.debug('PB Name'+pbName);
        return pbName;
    }
    
}