force-app/main/default/objects/Affected_Passenger__c/Affected_Passenger__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures the affected passenger list for a specific Event. This stores passenger information pertaining to the specific Event, such as, FF tier (snapshot), Cabin, Seat No, Pre and Post Flight</description>
    <label>Passenger</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Passenger__c/fields/OffloadRequest__c.field-meta.xml
<CustomField>
    <fullName>OffloadRequest__c</fullName>
    <description>IOC: Offload request is accepted or rejected by passenger</description>
    <label>Offload Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unable to contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QCC_DeleteOffloadPassengerBatchProcess.cls
global class QCC_DeleteOffloadPassengerBatchProcess implements Database.Batchable<sObject> {
	global Database.QueryLocator start(Database.BatchableContext bc) {
        Integer days = Integer.valueOf(CustomSettingsUtilities.getConfigDataMap('DaysOlderToDeleteOffloadPassengers'));
        String offloadRT = GenericUtils.getObjectRecordTypeId('Affected_Passenger__c', 'QCC Offload Passenger');
        
        System.debug([SELECT Id FROM affected_Passenger__c WHERE (OffloadRequest__c = null OR OffloadRequest__c = '') AND recordtypeId = :offloadRT AND CreatedDate < :System.today() - days]);
        return Database.getQueryLocator([SELECT Id FROM affected_Passenger__c WHERE OffloadRequest__c = null  AND recordtypeId = :offloadRT AND CreatedDate < :System.today() - days]);
    }
    
    global void execute(Database.BatchableContext bc, List<affected_Passenger__c> offloadPassengers) {
        delete offloadPassengers;
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
}