force-app/main/default/objects/Affected_Passenger__c/Affected_Passenger__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures the affected passenger list for a specific Event. This stores passenger information pertaining to the specific Event, such as, FF tier (snapshot), Cabin, Seat No, Pre and Post Flight</description>
    <label>Passenger</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Passenger__c/fields/Affected__c.field-meta.xml
<CustomField>
    <fullName>Affected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: flag to determine whether the passenger is affected by the related Event</description>
    <label>Affected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/ArrivalPort__c.field-meta.xml
<CustomField>
    <fullName>ArrivalPort__c</fullName>
    <description>QCC: Full Length Arrival Port</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Cabin__c.field-meta.xml
<CustomField>
    <fullName>Cabin__c</fullName>
    <description>QCC: the Cabin allocation for the passenger</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Booked Cabin</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/DeparturePort__c.field-meta.xml
<CustomField>
    <fullName>DeparturePort__c</fullName>
    <description>QCC: Full Length Departure Port</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: the related Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Affected_Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <label>Failure Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Failure_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Passenger First Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <formula>Event__r.FlightNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flight Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Passenger Last Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/SeatNo__c.field-meta.xml
<CustomField>
    <fullName>SeatNo__c</fullName>
    <description>QCC: the seat number allocation for the passenger</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Seat No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/TECH_PostFlight__c.field-meta.xml
<CustomField>
    <fullName>TECH_PostFlight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: flag to determine whether the passenger was on the plane</description>
    <label>Post Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/TECH_PreFlight__c.field-meta.xml
<CustomField>
    <fullName>TECH_PreFlight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: flag to determine whether the passenger was originally booked for the flight</description>
    <label>Pre Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/TravelledCabin__c.field-meta.xml
<CustomField>
    <fullName>TravelledCabin__c</fullName>
    <description>QCC: Any Upgrade to Cabin will be added here or Travelled Cabin will be Added.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Travelled Cabin</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/ArrivalPort__c.field-meta.xml
<CustomField>
    <fullName>ArrivalPort__c</fullName>
    <description>QCC: arrival port of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/DelayFailureCode__c.field-meta.xml
<CustomField>
    <fullName>DelayFailureCode__c</fullName>
    <description>QCC: specific delay categories of the disruption(s).</description>
    <label>Delay Failure Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Turn Back</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Mechanical</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Medical</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Other</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Weather</fullName>
            </value>
            <value>
                <fullName>Flight Cancellation</fullName>
            </value>
            <value>
                <fullName>Flight Delay</fullName>
            </value>
            <value>
                <fullName>Add Stop</fullName>
            </value>
            <value>
                <fullName>Heads Up</fullName>
            </value>
            <value>
                <fullName>Flight Delay Greater than 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Greater than 20 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay Less between 5 and 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Less between 5 and 20 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay Less than 5 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Less than 5 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay between 5 and 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay between 5 and 20 Hours</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/DeparturePort__c.field-meta.xml
<CustomField>
    <fullName>DeparturePort__c</fullName>
    <description>QCC: departure port of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EstimatedDepDateTime__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDepDateTime__c</fullName>
    <description>QCC: Estimated departure date/time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Estimated Departure Date/Time</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <description>QCC: the flight number affected</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Operational_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operational_Carrier__c</fullName>
    <description>QCC: Identifies the Flight Operator</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Operational Carrier</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepDate__c</fullName>
    <description>QCC: scheduled departure date of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepTime__c</fullName>
    <description>QCC: scheduled departure time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: status of the Event</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Re-Opened</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlightFailure__c/FlightFailure__c.object-meta.xml
<CustomObject>
    <label>Flight Failure</label>
    <nameField>
        <displayFormat>FD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Failures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FlightFailure__c/fields/Affected_Region__c.field-meta.xml
<CustomField>
    <fullName>Affected_Region__c</fullName>
    <label>Affected Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Flight</fullName>
            </value>
            <value>
                <fullName>Cabin</fullName>
            </value>
            <value>
                <fullName>Zone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlightFailure__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <label>Failure Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Failure_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Failure_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Flight Delay</fullName>
    </customValue>
    <customValue>
        <fullName>Flight Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Air Turn Back</fullName>
    </customValue>
    <customValue>
        <fullName>Add Stop</fullName>
    </customValue>
    <customValue>
        <fullName>Diversion Due to Mechanical</fullName>
    </customValue>
    <customValue>
        <fullName>Diversion Due to Medical</fullName>
    </customValue>
    <customValue>
        <fullName>Diversion Due to Weather</fullName>
    </customValue>
    <customValue>
        <fullName>Diversion Due to Other</fullName>
    </customValue>
    <customValue>
        <fullName>A/C Downgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Baggage</fullName>
    </customValue>
    <customValue>
        <fullName>Catering</fullName>
    </customValue>
    <customValue>
        <fullName>IFE Failure - Full</fullName>
    </customValue>
    <customValue>
        <fullName>IFE Failure - Partial</fullName>
    </customValue>
    <customValue>
        <fullName>Lights</fullName>
    </customValue>
    <customValue>
        <fullName>Q-Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Strike Action</fullName>
    </customValue>
    <customValue>
        <fullName>Toilets</fullName>
    </customValue>
    <customValue>
        <fullName>Wifi</fullName>
    </customValue>
    <customValue>
        <fullName>Offload</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Delay Failure Code hierarchy</description>
    <masterLabel>Failure Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FlightFailureTriggerHelperTest.cls
@IsTest
public class FlightFailureTriggerHelperTest {
    private static Event__c myEvent;
    static {
        
        TestUtilityDataClassQantas.insertQantasConfigData();
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createGlobalEventTriggerSetting();
        
        List<Trigger_Status__c> lstAffectedPassenger = TestUtilityDataClassQantas.createAffectedPassengerTriggerSetting();
        lstAffectedPassenger[0].Active__c = true;
        lsttrgStatus.addAll(lstAffectedPassenger);
        
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createFlightFailureSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createEventTriggerSetting());
        database.insert( lsttrgStatus, false);
        
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC Offload Passenger RecType','QCC Offload Passenger'));
         insert lstConfigData;
        // create Flight Event
        myEvent    = TestUtilityDataClassQantas.createEventWithValues('Flight Event - Active','Assigned', 'Flight Delay','International');
        myEvent.FlightNumber__c = 'QF0007';
        myEvent.DeparturePort__c = 'SYD';
        myEvent.ArrivalPort__c = 'MEL';
        myEvent.ScheduledDepDate__c = System.today();
        myEvent.DelayFailureCode__c = 'Flight Delay';
        myEvent.Status__c = 'Assigned';
        //newEvent1.EstimatedDepDateTime__c = string.valueOf(System.Now());
        //newEvent1.ScheduledDepTime__c = '19:15';
        
        myEvent.Operational_Carrier__c = 'QF';
        insert myEvent;
    }
    
    static testMethod void testInsertFlightFailure() {
        List<Affected_Passenger__c> lstAffectedPassenger = new List<Affected_Passenger__c>();
        lstAffectedPassenger.add(createAffectedPassenger(myEvent.Id,'',true,true,'Economy','1A'));
        lstAffectedPassenger.add(createAffectedPassenger(myEvent.Id,'',true,true,'Economy','2A'));
        insert lstAffectedPassenger;
        List<FlightFailure__c> lstFlightFailure = new List<FlightFailure__c>();
        //lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Full Flight','Wifi','Full Flight',true,true));
        //lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Cabin','Baggage','Economy',true,true));
        //lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Zone','Catering','Row 1',true,true));
        lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Zone','Lights','Row 1',false,false));
        //lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Full Flight','Wifi','Full Flight',false,true));
        Test.startTest();
        insert lstFlightFailure;
        Test.stopTest();
        List<Affected_Passenger__c> lstPassenger = [
          SELECT Id, 
            Affected__c
          FROM Affected_Passenger__c
          WHERE Event__c = :myEvent.Id
        ];
        //System.assertEquals(true, lstPassenger[0].Affected__c);
    }

    static testMethod void testInsertFlightFailure2() {
        List<Affected_Passenger__c> lstAffectedPassenger = new List<Affected_Passenger__c>();
        lstAffectedPassenger.add(createAffectedPassenger(myEvent.Id,'',true,true,'Business','1A'));
        insert lstAffectedPassenger;
        List<FlightFailure__c> lstFlightFailure = new List<FlightFailure__c>();
        lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Cabin','Baggage','Economy',true,true));
        //lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Full Flight','Wifi','Full Flight',false,true));
        Test.startTest();
        insert lstFlightFailure;
        lstFlightFailure[0].Failure_Code__c = 'Other';
        update lstFlightFailure[0];
        Test.stopTest();
        List<Affected_Passenger__c> lstPassenger = [
          SELECT Id, 
            Affected__c
          FROM Affected_Passenger__c
          WHERE Event__c = :myEvent.Id
        ];
        //System.assertEquals(true, lstPassenger[0].Affected__c);
    }
    
    static testMethod void testInsertFlightFailureDelete() {
        List<Affected_Passenger__c> lstAffectedPassenger = new List<Affected_Passenger__c>();
        lstAffectedPassenger.add(createAffectedPassenger(myEvent.Id,'',true,true,'Business','1A'));
        insert lstAffectedPassenger;
        List<Group> listQueue = [Select id, name from Group where Type='Queue' AND developerName='CCC_CIOC_Queue'];
        myEvent.OwnerId = listQueue[0].id;
        update myEvent;
        List<FlightFailure__c> lstFlightFailure = new List<FlightFailure__c>();
        lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Cabin','Baggage','Economy',true,true));
        //lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Full Flight','Wifi','Full Flight',false,true));
        Test.startTest();
        insert lstFlightFailure;
        Boolean isError= false;
        try{
        delete lstFlightFailure[0];
        }catch(Exception ex){
           isError = true; 
           system.assert(isError == true, 'Record is deleted');
        }
        Test.stopTest();
    }

    static testMethod void testInsertFlightFailureDuplicate() {
        List<Affected_Passenger__c> lstAffectedPassenger = new List<Affected_Passenger__c>();
        lstAffectedPassenger.add(createAffectedPassenger(myEvent.Id,'',true,true,'Economy','1A'));
        insert lstAffectedPassenger;
        List<FlightFailure__c> lstFlightFailure = new List<FlightFailure__c>();
        lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Full Flight','Wifi','Full Flight',true,true));
        lstFlightFailure.add(createFlightFailure(myEvent.Id, 'Full Flight','Wifi','Full Flight',false,true));
        Test.startTest();
        try{
            insert lstFlightFailure;
        }catch(exception ex){
            System.assertNotEquals(ex, null);
        }
        
        Test.stopTest();
    }
    
    private static Affected_Passenger__c createAffectedPassenger(String myEventId, String failureCode,
                                                                Boolean preFlight, Boolean postFlight,
                                                                String caBin, String seatNo){
        Affected_Passenger__c myAffectedPassenger = new Affected_Passenger__c();
        myAffectedPassenger.FirstName__c = 'FName';
        myAffectedPassenger.LastName__c = 'LName';
        myAffectedPassenger.Name = 'Gold Frequentflyer1';
        myAffectedPassenger.Event__c = myEventId;
        myAffectedPassenger.Failure_Code__c = failureCode;
        myAffectedPassenger.TECH_PreFlight__c = preFlight;
        myAffectedPassenger.TECH_PostFlight__c = postFlight;
        myAffectedPassenger.Cabin__c = caBin;
        myAffectedPassenger.TravelledCabin__c = caBin;
        myAffectedPassenger.SeatNo__c = seatNo;
        myAffectedPassenger.Affected__c = true;
        Id myRecordTypeId = Schema.SObjectType.Affected_Passenger__c.getRecordTypeInfosByName().get('QCC EventPassenger').getRecordTypeId();
        myAffectedPassenger.RecordTypeId = myRecordTypeId;
        return myAffectedPassenger;
    }
    
    private static FlightFailure__c createFlightFailure(String myEventId, String inType, 
                                                        String failureCode, String affectSub,
                                                       Boolean preFlight, Boolean postFlight){
        FlightFailure__c myFlightFailure = new FlightFailure__c();
        myFlightFailure.Affected_Region__c = inType;
        myFlightFailure.Failure_Code__c = failureCode;
                          
        if(inType == 'Full Flight'){
            myFlightFailure.Affect_Sub_Section__c = affectSub;
        } else if(inType == 'Cabin'){
            myFlightFailure.Affect_Sub_Section__c = affectSub;
        } else if(inType == 'Zone'){
            myFlightFailure.Affect_Sub_Section__c = affectSub;
        }
        myFlightFailure.OnlyLeg__c = true;
        myFlightFailure.Flight_Event__c = myEventId;
        myFlightFailure.Post_Flight__c = postFlight;
        myFlightFailure.Pre_Flight__c = preFlight;
        return myFlightFailure;
    }
}