force-app/main/default/objects/Affected_Passenger__c/Affected_Passenger__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures the affected passenger list for a specific Event. This stores passenger information pertaining to the specific Event, such as, FF tier (snapshot), Cabin, Seat No, Pre and Post Flight</description>
    <label>Passenger</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Passenger__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: the related Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Affected_Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SSU__c.field-meta.xml
<CustomField>
    <fullName>SSU__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Corporate: Special Service Unit -This person&apos;s travel / relationship is overseen by the special service unit</inlineHelpText>
    <label>SSU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/QCC_Number_of_SSUs__c.field-meta.xml
<CustomField>
    <fullName>QCC_Number_of_SSUs__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count of passengers which tagged as SSU</description>
    <inlineHelpText>Count of SSU passengers</inlineHelpText>
    <label>SSUs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Number_of_VIP_with_DOM_IN_CONX__c.field-meta.xml
<CustomField>
    <fullName>QCC_Number_of_VIP_with_DOM_IN_CONX__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of VIP PAX with a DOM inbound connection</description>
    <inlineHelpText>Number of VIP PAX with a DOM inbound connection</inlineHelpText>
    <label>VIPs With DOM IN CONX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Number_of_VIP_with_DOM_OUT_CONX__c.field-meta.xml
<CustomField>
    <fullName>QCC_Number_of_VIP_with_DOM_OUT_CONX__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of VIP PAX with a DOM outbound connection</description>
    <inlineHelpText>Number of VIP PAX with a DOM outbound connection</inlineHelpText>
    <label>VIPs With DOM OUT CONX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Number_of_VIP_with_INTL_IN_CONX__c.field-meta.xml
<CustomField>
    <fullName>QCC_Number_of_VIP_with_INTL_IN_CONX__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of VIP PAX with an INTL inbound connection</description>
    <inlineHelpText>Number of VIP PAX with an INTL inbound connection</inlineHelpText>
    <label>VIPs With INTL IN CONX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Number_of_VIP_with_INTL_OUT_CONX__c.field-meta.xml
<CustomField>
    <fullName>QCC_Number_of_VIP_with_INTL_OUT_CONX__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of VIP PAX with an INTL outbound connection</description>
    <inlineHelpText>Number of VIP PAX with an INTL outbound connection</inlineHelpText>
    <label>VIPs With INTL OUT CONX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Number_of_VIPs__c.field-meta.xml
<CustomField>
    <fullName>QCC_Number_of_VIPs__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count of passengers which Tier code is Chairman&apos;s Lounge Platinum One and Platinum One</description>
    <inlineHelpText>Count of VIP passengers</inlineHelpText>
    <label>VIPs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_PassengerUpdateCountInvocableTest.cls
/*********************************************************************************
Name         : QCC_HeadsUpEventActionReportCntrllrTest
Created By   : Raymart Airon Tolentino
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 16 September 2019
Usages       : This class is used for the code coverage of the apex class below:
			   - QCC_PassengerUpdateCountInvocable

Modified By : Venkata Suresh Kumar (TCS Team), 18-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method. Added Test.start and Test.Stop methods
*********************************************************************************/
@isTest
public class QCC_PassengerUpdateCountInvocableTest {
	@testSetup
    static void setupTestData(){
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        List<Contact> contactList = new List<Contact>();
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.RecordTypeId = contactRecordTypeId;
        contactRecord.Frequent_Flyer_Number__c = '000001';
        contactRecord.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord.SSU__c = true;
        insert contactRecord;
        
        //Create test data for Flight Event object
        List<Event__c> flightEventRecords = new List<Event__c>();
        List<Trigger_Status__c> customSettingList1 = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusFlightEvent', null, null, null, null);
        insert customSettingList1;
        
        String headsUpRecordTypeId = Schema.SObjectType.Event__c.getRecordTypeInfosByName().get('Heads Up').getRecordTypeId();
        Event__c flightEventRecord = QCC_TestDataFactory.createFlightEventTestData();
        flightEventRecord.RecordTypeId = headsUpRecordTypeId;
        flightEventRecords.add(flightEventRecord);
        
        insert flightEventRecords;
        
        //Create test data for Passenger object
        List<Trigger_Status__c> customSettingList2 = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusPassenger', null, null, null, null);
        insert customSettingList2;
        
        String passengerRecordTypeId = Schema.SObjectType.Affected_Passenger__c.getRecordTypeInfosByName().get('QCC EventPassenger').getRecordTypeId();
        Affected_Passenger__c passengerRecord = QCC_TestDataFactory.createPassengerTestData(flightEventRecord.Id, contactRecord.Id);
        insert passengerRecord;
    }
    
    static testmethod void test1(){
        List<Affected_Passenger__c> passengerRecords = new List<Affected_Passenger__c>();
        Affected_Passenger__c passengerRecord = [SELECT Id, Event__c FROM Affected_Passenger__c LIMIT 1];
        passengerRecords.add(passengerRecord);
        Test.startTest();
        QCC_PassengerUpdateCountInvocable.processData(passengerRecords);
        
        Event__c flightEventRecord = [
            SELECT Id, QCC_Number_of_VIPs__c, QCC_Number_of_SSUs__c, 
            QCC_Number_of_VIP_with_DOM_IN_CONX__c, QCC_Number_of_VIP_with_DOM_OUT_CONX__c, 
            QCC_Number_of_VIP_with_INTL_IN_CONX__c, QCC_Number_of_VIP_with_INTL_OUT_CONX__c 
            FROM Event__c WHERE Id =: passengerRecord.Event__c
        ];
        Test.stopTest();
        System.assertNotEquals(flightEventRecord.QCC_Number_of_VIPs__c, 0);
    }
}