force-app/main/default/objects/Affected_Passenger__c/Affected_Passenger__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures the affected passenger list for a specific Event. This stores passenger information pertaining to the specific Event, such as, FF tier (snapshot), Cabin, Seat No, Pre and Post Flight</description>
    <label>Passenger</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Passenger__c/fields/Cabin__c.field-meta.xml
<CustomField>
    <fullName>Cabin__c</fullName>
    <description>QCC: the Cabin allocation for the passenger</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Booked Cabin</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: the related Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Affected_Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/EventCommunication__c.field-meta.xml
<CustomField>
    <fullName>EventCommunication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Event CommunicationLook up</description>
    <label>Event Communication</label>
    <referenceTo>EventCommunication__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <label>Failure Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Failure_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/GlobalEvent__c.field-meta.xml
<CustomField>
    <fullName>GlobalEvent__c</fullName>
    <description>QCC: Global Event the Passenger Associated with. Used for Reports</description>
    <formula>Event__r.GlobalEvent__c</formula>
    <label>Global Event</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/IsCommsRequired__c.field-meta.xml
<CustomField>
    <fullName>IsCommsRequired__c</fullName>
    <defaultValue>true</defaultValue>
    <description>QCC: Email or Recovery will be sent or created only if this check box is true.</description>
    <label>Is Comms Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/SeatNo__c.field-meta.xml
<CustomField>
    <fullName>SeatNo__c</fullName>
    <description>QCC: the seat number allocation for the passenger</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Seat No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/TECH_PostFlight__c.field-meta.xml
<CustomField>
    <fullName>TECH_PostFlight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: flag to determine whether the passenger was on the plane</description>
    <label>Post Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/TECH_PreFlight__c.field-meta.xml
<CustomField>
    <fullName>TECH_PreFlight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: flag to determine whether the passenger was originally booked for the flight</description>
    <label>Pre Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/TravelledCabin__c.field-meta.xml
<CustomField>
    <fullName>TravelledCabin__c</fullName>
    <description>QCC: Any Upgrade to Cabin will be added here or Travelled Cabin will be Added.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Travelled Cabin</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/GlobalEvent__c.field-meta.xml
<CustomField>
    <fullName>GlobalEvent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Event</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Event__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>GlobalEvent</value>
        </filterItems>
        <filterItems>
            <field>Event__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>QCC_Global_Heads_Up</value>
        </filterItems>
        <infoMessage>All Global Events</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Flight Events</relationshipLabel>
    <relationshipName>Global_Event</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventCommunication__c/EventCommunication__c.object-meta.xml
<CustomObject>
    <description>QCC: This object will hold all the communication sent to the customer for a event</description>
    <label>Event Communication</label>
    <nameField>
        <displayFormat>EC-{000000}</displayFormat>
        <label>EventCommunication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Communications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EventCommunication__c/fields/FailureCode__c.field-meta.xml
<CustomField>
    <fullName>FailureCode__c</fullName>
    <description>QCC: Failure code Related to the Comms</description>
    <label>Failure Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Failure_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlightFailure__c/FlightFailure__c.object-meta.xml
<CustomObject>
    <label>Flight Failure</label>
    <nameField>
        <displayFormat>FD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Failures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FlightFailure__c/fields/Affect_Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Affect_Sub_Section__c</fullName>
    <label>Affect Sub Section</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Affected_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Flight</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Row 1</fullName>
            </value>
            <value>
                <fullName>Row 2</fullName>
            </value>
            <value>
                <fullName>Row 3</fullName>
            </value>
            <value>
                <fullName>Row 4</fullName>
            </value>
            <value>
                <fullName>Row 5</fullName>
            </value>
            <value>
                <fullName>Row 6</fullName>
            </value>
            <value>
                <fullName>Row 7</fullName>
            </value>
            <value>
                <fullName>Row 8</fullName>
            </value>
            <value>
                <fullName>Row 9</fullName>
            </value>
            <value>
                <fullName>Row 10</fullName>
            </value>
            <value>
                <fullName>Row 11</fullName>
            </value>
            <value>
                <fullName>Row 12</fullName>
            </value>
            <value>
                <fullName>Row 13</fullName>
            </value>
            <value>
                <fullName>Row 14</fullName>
            </value>
            <value>
                <fullName>Row 15</fullName>
            </value>
            <value>
                <fullName>Row 16</fullName>
            </value>
            <value>
                <fullName>Row 17</fullName>
            </value>
            <value>
                <fullName>Row 18</fullName>
            </value>
            <value>
                <fullName>Row 19</fullName>
            </value>
            <value>
                <fullName>Row 20</fullName>
            </value>
            <value>
                <fullName>Row 21</fullName>
            </value>
            <value>
                <fullName>Row 22</fullName>
            </value>
            <value>
                <fullName>Row 23</fullName>
            </value>
            <value>
                <fullName>Row 24</fullName>
            </value>
            <value>
                <fullName>Row 25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlightFailure__c/fields/EventStatus__c.field-meta.xml
<CustomField>
    <fullName>EventStatus__c</fullName>
    <description>QCC: Event Status</description>
    <formula>TEXT(Flight_Event__r.Status__c)</formula>
    <label>Event Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlightFailure__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <label>Failure Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Failure_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlightFailure__c/fields/Flight_Event__c.field-meta.xml
<CustomField>
    <fullName>Flight_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Failure_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FlightFailure__c/fields/Post_Flight__c.field-meta.xml
<CustomField>
    <fullName>Post_Flight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Failure happens after Flight.</description>
    <label>Post Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FlightFailure__c/fields/Pre_Flight__c.field-meta.xml
<CustomField>
    <fullName>Pre_Flight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Failure happens before Flight.</description>
    <label>Pre Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FlightFailure__c/fields/Tech_FlightEventStatus__c.field-meta.xml
<CustomField>
    <fullName>Tech_FlightEventStatus__c</fullName>
    <description>IOC: Flight Event Status, This is used in Trigger to check if flight failure can be deleted.</description>
    <formula>TEXT(Flight_Event__r.Status__c)</formula>
    <label>Flight Event Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_ValidFlightEvent__mdt/QCC_ValidFlightEvent__mdt.object-meta.xml
<CustomObject>
    <description>QCC: Table to validate if Flight Event record should be created or not</description>
    <label>QCC Valid Flight Event</label>
    <pluralLabel>QCC Valid Flight Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/QCC_ValidFlightEvent__mdt/fields/CheckCriteria__c.field-meta.xml
<CustomField>
    <fullName>CheckCriteria__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: To determine if Event to be created immediately or based on Criteria</description>
    <label>Check Criteria</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_ValidFlightEvent__mdt/fields/CreateEventRecord__c.field-meta.xml
<CustomField>
    <fullName>CreateEventRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Event Record will be created only if this field is set to true</description>
    <label>Create Event Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_ValidFlightEvent__mdt/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>QCC: Criteria to be validated</description>
    <label>Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_ValidFlightEvent__mdt/fields/PostFlight__c.field-meta.xml
<CustomField>
    <fullName>PostFlight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Valid Post Flight Value for a Failure</description>
    <label>Post Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_ValidFlightEvent__mdt/fields/PreFlight__c.field-meta.xml
<CustomField>
    <fullName>PreFlight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Valid Pre Flight Value for a Failure</description>
    <label>Pre Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Failure_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Flight Delay</fullName>
    </customValue>
    <customValue>
        <fullName>Flight Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Air Turn Back</fullName>
    </customValue>
    <customValue>
        <fullName>Add Stop</fullName>
    </customValue>
    <customValue>
        <fullName>Diversion Due to Mechanical</fullName>
    </customValue>
    <customValue>
        <fullName>Diversion Due to Medical</fullName>
    </customValue>
    <customValue>
        <fullName>Diversion Due to Weather</fullName>
    </customValue>
    <customValue>
        <fullName>Diversion Due to Other</fullName>
    </customValue>
    <customValue>
        <fullName>A/C Downgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Baggage</fullName>
    </customValue>
    <customValue>
        <fullName>Catering</fullName>
    </customValue>
    <customValue>
        <fullName>IFE Failure - Full</fullName>
    </customValue>
    <customValue>
        <fullName>IFE Failure - Partial</fullName>
    </customValue>
    <customValue>
        <fullName>Lights</fullName>
    </customValue>
    <customValue>
        <fullName>Q-Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Strike Action</fullName>
    </customValue>
    <customValue>
        <fullName>Toilets</fullName>
    </customValue>
    <customValue>
        <fullName>Wifi</fullName>
    </customValue>
    <customValue>
        <fullName>Offload</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Delay Failure Code hierarchy</description>
    <masterLabel>Failure Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FlightFailureTriggerHelper.cls
public class FlightFailureTriggerHelper {
    
    public static void beforeFlightFailureDeleteCheck(List<FlightFailure__c> lstOldFltFailure){
        String statusOpenEvent = CustomSettingsUtilities.getConfigDataMap('Event Open Status');
        String statusClosedEvent = CustomSettingsUtilities.getConfigDataMap('Event Closed Status');
        for(FlightFailure__c objFF: lstOldFltFailure){
            if(objFF.Tech_FlightEventStatus__c == statusClosedEvent){
                objFF.addError(Label.IOCFFdeleteCloseMSG);
            }else if(objFF.Tech_FlightEventStatus__c != statusOpenEvent){
                objFF.addError(Label.IOCFFdeleteMSG);
            }
        }
    }
    
    public static void addFailureCodetoPassengerandEvent(List<FlightFailure__c>lstFltFailure, Map<Id, FlightFailure__c>mapOldFltFailure)
    {
        Set<Id> setAffectedPassFF = new Set<Id>();
        Map<Id, List<FlightFailure__c>> mapff = new Map<Id, List<FlightFailure__c>>();
        List<Affected_Passenger__c> lstUpdatePassenger = new List<Affected_Passenger__c>();
        Boolean isVaidEventUpdate = false;
        Set<Id> setEventFF = new Set<Id>();
        for(FlightFailure__c objFF: lstFltFailure){
            FlightFailure__c oldFF = mapOldFltFailure != Null? mapOldFltFailure.get(objFF.Id): Null;
            if(oldFF == Null || oldFF.Affect_Sub_Section__c != objFF.Affect_Sub_Section__c ||
                oldFF.Failure_Code__c != objFF.Failure_Code__c || oldFF.Post_Flight__c != objFF.Post_Flight__c ||
                oldFF.Pre_Flight__c != objFF.Pre_Flight__c)
            {
                setAffectedPassFF.add(objFF.Flight_Event__c);
                
                //For Event Update
                if(oldFF == Null || oldFF.Failure_Code__c != objFF.Failure_Code__c){
                    setEventFF.add(objFF.Flight_Event__c);
                }
            }
        
        }
        if(setAffectedPassFF.size()>0){
             mapff = QCC_EventGenericUtils.queryFlightFailures(setAffectedPassFF);
        }
        //All Passenger Related Logic
        if(mapff.size()>0){
            Map<Id, List<Affected_Passenger__c>> mapEvtPassenger = new Map<Id, List<Affected_Passenger__c>>();
            
            //All Passenger related to the Event 
            for(Affected_Passenger__c objPassenger: [select Id, Failure_Code__c, Event__c, EventCommunication__c, IsCommsRequired__c, SeatNo__c, GlobalEvent__c,
                                                     TECH_PostFlight__c, TECH_PreFlight__c, Cabin__c , TravelledCabin__c from Affected_Passenger__c 
                                                     where Event__c IN: mapff.keyset() ])
            {
                List<FlightFailure__c> lstFF = mapff.get(objPassenger.Event__c);
                system.debug('lstFF###'+lstFF);
                lstUpdatePassenger.add(QCC_EventGenericUtils.updatePassengerFailureCode(objPassenger, lstFF, new List<EventCommunication__c>()));
                system.debug('lstUpdatePassenger####'+lstUpdatePassenger);
            }
            update lstUpdatePassenger;
        }

        // All Event Related Logic
        if(setEventFF.size()>0){
            Set<String> setDelayFailure = new Set<String>();
            List<Event__c> lstUpdateEvt = new List<Event__c>();
            for(QCC_ValidFlightEvent__mdt validFlightEvt: [SELECT Label,DeveloperName, CheckCriteria__c,
                                                           CreateEventRecord__c, Criteria__c, FailureCode__c,
                                                           PreFlight__c, PostFlight__c, Flight_Status__c, 
                                                           Priority__c FROM QCC_ValidFlightEvent__mdt])
            {
                
                setDelayFailure.add(validFlightEvt.FailureCode__c);
            }

            for(Id evtId: setEventFF){
                Event__c objEvent = new Event__c();
                objEvent.Id = evtId;
                String nonDelay = '';
                for(FlightFailure__c objFF: mapff.get(evtId)){
                    if(setDelayFailure.contains(objFF.Failure_Code__c)){
                        objEvent.DelayFailureCode__c = objFF.Failure_Code__c;
                    }else{
                        nonDelay += objFF.Failure_Code__c+';';
                    }
                    system.debug('nonDelay###'+nonDelay);
                }
                objEvent.Non_Delay_Failure_Code__c = nonDelay;
                lstUpdateEvt.add(objEvent);

            }
            update lstUpdateEvt;
        }
    }


    public static void updateEmailComs(List<FlightFailure__c>lstFltFailure, Map<Id, FlightFailure__c>mapOldFltFailure){
        Set<Id> setEventFF = new Set<Id>();
        for(FlightFailure__c objFF: lstFltFailure){
            FlightFailure__c oldFF = mapOldFltFailure != Null? mapOldFltFailure.get(objFF.Id): Null;
            if((objFF.OnlyLeg__c != oldFF.OnlyLeg__c) && objFF.EventStatus__c == 'Assigned')
            {
                setEventFF.add(objFF.Flight_Event__c);
            }
       }

       if(setEventFF.size()>0){
            QCC_EventGenericUtils.createEmailCommsForEvents(setEventFF);
       }
    }


    public static void checkFlightFailureDuplication(List<FlightFailure__c>lstFltFailure, Map<Id, FlightFailure__c>mapOldFltFailure){
        //populate the unique key field: event - failure code
        
         
          for(FlightFailure__c ff : lstFltFailure){ 
            if(ff.Flight_Event__c!=NULL){
            ff.Unique_Event_ErrorCode__c = ff.Flight_Event__c+'_'+ff.Failure_Code__c;
              }
              else{
            ff.Unique_Event_ErrorCode__c=ff.Operating_Carrier__c+'-'+ff.Flight_Number__c+'-'+string.valueof(ff.DepartureDateLocal__c)+ff.DepartureAirport__c+ff.ArrivalAirport__c+'-'+ff.failure_code__c;
              }
            //else{
            //ff.Unique_Event_ErrorCode__c=ff.Flight_Event__r.FlightNumber__c+'-'+ff.Flight_Event__r.Schedule_Departure_Date__c+ff.Flight_Event__r.DeparturePort__c+ff.Flight_Event__r.ArrivalPort__c+'-'+ff.Flight_Event__r.DelayFailureCode__c;
            //}
        }
    }
}