force-app/main/default/objects/Affected_Passenger__c/Affected_Passenger__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures the affected passenger list for a specific Event. This stores passenger information pertaining to the specific Event, such as, FF tier (snapshot), Cabin, Seat No, Pre and Post Flight</description>
    <label>Passenger</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Passenger__c/fields/Affected__c.field-meta.xml
<CustomField>
    <fullName>Affected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: flag to determine whether the passenger is affected by the related Event</description>
    <label>Affected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: the related Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Affected_Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/RecoveryIsCreated__c.field-meta.xml
<CustomField>
    <fullName>RecoveryIsCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RecoveryIsCreated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/TECH_OfferedQantasPoints__c.field-meta.xml
<CustomField>
    <fullName>TECH_OfferedQantasPoints__c</fullName>
    <description>QCC: the amount of Qantas Points offered for this customer if applicable. This is based on the points specified on the Event based on Frequent Flyer Tier and Cabin</description>
    <formula>IF(Affected__c, CASE(FF_Tier__c+&quot;, &quot;+Cabin__c,
    &quot;Platinum One, First&quot;, Event__r.Platinum1SSUFirstClass__c,
    &quot;Platinum One, Business&quot;, Event__r.Platinum1SSUBusiness__c,
    &quot;Platinum One, Premium Economy&quot;, Event__r.Platinum1SSUPremiumEconomy__c,
    &quot;Platinum One, Economy&quot;, Event__r.Platinum1SSUEconomy__c,
    &quot;Chairman&apos;s Lounge, First&quot;, Event__r.Platinum1SSUFirstClass__c,
    &quot;Chairman&apos;s Lounge, Business&quot;, Event__r.Platinum1SSUBusiness__c,
    &quot;Chairman&apos;s Lounge, Premium Economy&quot;, Event__r.Platinum1SSUPremiumEconomy__c,
    &quot;Chairman&apos;s Lounge, Economy&quot;, Event__r.Platinum1SSUEconomy__c,
    &quot;Chairman&apos;s Lounge Platinum One, First&quot;, Event__r.Platinum1SSUFirstClass__c,
    &quot;Chairman&apos;s Lounge Platinum One, Business&quot;, Event__r.Platinum1SSUBusiness__c,
    &quot;Chairman&apos;s Lounge Platinum One, Premium Economy&quot;, Event__r.Platinum1SSUPremiumEconomy__c,
    &quot;Chairman&apos;s Lounge Platinum One, Economy&quot;, Event__r.Platinum1SSUEconomy__c,  
    &quot;Platinum, First&quot;, Event__r.PlatinumFirstClass__c,
    &quot;Platinum, Business&quot;, Event__r.PlatinumBusiness__c,
    &quot;Platinum, Premium Economy&quot;, Event__r.PlatinumPremiumEconomy__c,
    &quot;Platinum, Economy&quot;, Event__r.PlatinumEconomy__c,
    &quot;Gold, First&quot;, Event__r.GoldFirstClass__c,
    &quot;Gold, Business&quot;, Event__r.GoldBusiness__c,
    &quot;Gold, Premium Economy&quot;, Event__r.GoldPremiumEconomy__c,
    &quot;Gold, Economy&quot;, Event__r.GoldEconomy__c,
    &quot;Silver, First&quot;, Event__r.SilverFirstClass__c,
    &quot;Silver, Business&quot;, Event__r.SilverBusiness__c,
    &quot;Silver, Premium Economy&quot;, Event__r.SilverPremiumEconomy__c,
    &quot;Silver, Economy&quot;, Event__r.SilverEconomy__c,
    &quot;Bronze, First&quot;, Event__r.BronzeFirstClass__c,
    &quot;Bronze, Business&quot;, Event__r.BronzeBusiness__c,
    &quot;Bronze, Premium Economy&quot;, Event__r.BronzePremiumEconomy__c,
    &quot;Bronze, Economy&quot;, Event__r.BronzeEconomy__c,
    &quot;Non-Tiered, First&quot;, Event__r.NonTieredFirstClass__c,
    &quot;Non-Tiered, Business&quot;, Event__r.NonTieredBusiness__c,
    &quot;Non-Tiered, Premium Economy&quot;, Event__r.NonTieredPremiumEconomy__c,
    &quot;Non-Tiered, Economy&quot;, Event__r.NonTieredEconomy__c,
    0 ), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offered Qantas Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/RecoveryIsCreated__c.field-meta.xml
<CustomField>
    <fullName>RecoveryIsCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Indicates whether or not a Recovery has been created for the reference event.</description>
    <label>Recovery Is Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QCC_EventSubmitRecoveriesController.cls
/*-----------------------------------------------------------------------------------------
    Author: Nga Do
	Company: Capgemini
	Description: 
	Inputs: 
	Test Class: QCC_EventSubmitRecoveriesControllerTest
	***************************************************************************************
	History:
	***************************************************************************************
	08-May-2018
 ------------------------------------------------------------------------------------------*/
public class QCC_EventSubmitRecoveriesController {
    private static string submittedEventId;

    /*--------------------------------------------------------------------------------------       
    Method Name:        createRecoveries
    Description:        submit recovery for specific event
    Parameter:          set Id of Event
    --------------------------------------------------------------------------------------*/
    @AuraEnabled
    public static String createRecoveries(String eventId){
        
        submittedEventId = eventId;
        try{
            // get event need to update
            Event__c eventOject = [SELECT Id, RecoveryIsCreated__c FROM Event__c WHERE  Id =: eventId];
            // if the QCC Lead or OM submit recoveries once the recoveries are created show Error Message;
            if(eventOject.RecoveryIsCreated__c == true){
                return CustomSettingsUtilities.getConfigDataMap('Recovery Submitted Error Message');
            }
            String strSQL = 'SELECT ' 
                            +    'count() '
                            +'FROM '
                            +    'Affected_Passenger__c '
                            +'WHERE '
                            +    'RecoveryIsCreated__c = FALSE ' 
                            +'AND Affected__c = TRUE '
                            +'AND TECH_OfferedQantasPoints__c > 0 '
                            +'AND Event__c =: submittedEventId LIMIT 50000';
                            
            Integer numberAffectedPassengers = Database.countQuery(strSQL); 
            if(numberAffectedPassengers == 0){
                return CustomSettingsUtilities.getConfigDataMap('Recovery Submitted No Passenger Msg');
            }
            // call batcheable to creating cases and recoveries
            Database.executeBatch(new QCC_EventSubmitRecoveriesBatchable(eventId), 50);

            return CustomSettingsUtilities.getConfigDataMap('Recovery Submitted Initializing'); 
            
        }catch(Exception ex){
            
            return 'Error: '+ CustomSettingsUtilities.getConfigDataMap('Recovery Submitted Fail Message');
            
        }
        
    }
   
}