force-app/main/default/objects/Affected_Passenger__c/Affected_Passenger__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures the affected passenger list for a specific Event. This stores passenger information pertaining to the specific Event, such as, FF tier (snapshot), Cabin, Seat No, Pre and Post Flight</description>
    <label>Passenger</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Passenger__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: the related Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Affected_Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <formula>Event__r.FlightNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flight Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>QCC: related Contact as the passenger</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Affected_Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/QCC_Disruption_Actioned__c.field-meta.xml
<CustomField>
    <fullName>QCC_Disruption_Actioned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If set to TRUE, it indicates that the passenger has been actioned already</description>
    <inlineHelpText>Check this if you have talked with the passenger and provided a heads up action</inlineHelpText>
    <label>Disruption Actioned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Root_cause__c.field-meta.xml
<CustomField>
    <fullName>Root_cause__c</fullName>
    <formula>TEXT(Event__r.Root_Cause__c)</formula>
    <label>Root cause</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Schedule_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Departure_Date__c</fullName>
    <description>QCC: System field to combine schedule departure date and time for matching rule</description>
    <formula>TEXT(DAY(Event__r.ScheduledDepDate__c))&amp;&apos; &apos;&amp;CASE(MONTH(Event__r.ScheduledDepDate__c), 1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;None&quot;)&amp;&apos; &apos;&amp;TEXT(YEAR(Event__r.ScheduledDepDate__c))</formula>
    <label>Schedule Departure Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/DelayFailureCode__c.field-meta.xml
<CustomField>
    <fullName>DelayFailureCode__c</fullName>
    <description>QCC: specific delay categories of the disruption(s).</description>
    <label>Delay Failure Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Turn Back</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Mechanical</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Medical</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Other</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Weather</fullName>
            </value>
            <value>
                <fullName>Flight Cancellation</fullName>
            </value>
            <value>
                <fullName>Flight Delay</fullName>
            </value>
            <value>
                <fullName>Add Stop</fullName>
            </value>
            <value>
                <fullName>Heads Up</fullName>
            </value>
            <value>
                <fullName>Flight Delay Greater than 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Greater than 20 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay Less between 5 and 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Less between 5 and 20 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay Less than 5 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Less than 5 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay between 5 and 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay between 5 and 20 Hours</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Disruption_Reason_Text__c.field-meta.xml
<CustomField>
    <fullName>Disruption_Reason_Text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employee Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <description>QCC: the flight number affected</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/IntDom__c.field-meta.xml
<CustomField>
    <fullName>IntDom__c</fullName>
    <description>QCC: identifies whether the flight is international or domestic</description>
    <label>Int/Dom</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Primary_Root_Cause__c.field-meta.xml
<CustomField>
    <fullName>Primary_Root_Cause__c</fullName>
    <label>Primary Root Cause</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acft/Ramp Handling</fullName>
            </value>
            <value>
                <fullName>Aircraft Cleaning</fullName>
            </value>
            <value>
                <fullName>Aircrew Rotation</fullName>
            </value>
            <value>
                <fullName>Airport &amp; Govt Auth</fullName>
            </value>
            <value>
                <fullName>Airport Services</fullName>
            </value>
            <value>
                <fullName>Air Traffic Services</fullName>
            </value>
            <value>
                <fullName>Apt Infrastructure</fullName>
            </value>
            <value>
                <fullName>Auto Equipment</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Cabin Crew</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Damage to Aircraft</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Enroute delays</fullName>
            </value>
            <value>
                <fullName>Flight Operations</fullName>
            </value>
            <value>
                <fullName>Freight &amp; Mail</fullName>
            </value>
            <value>
                <fullName>Fuelling</fullName>
            </value>
            <value>
                <fullName>Load Control</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Network &amp; Airline Op</fullName>
            </value>
            <value>
                <fullName>No Group Allocated</fullName>
            </value>
            <value>
                <fullName>Rotation</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Cabin</fullName>
            </value>
            <value>
                <fullName>Aircraft Grounded</fullName>
            </value>
            <value>
                <fullName>Customer Delay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Root_Cause__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause__c</fullName>
    <label>Root Cause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mechanical</fullName>
            </value>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Air Traffice Flow Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Schedule_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Departure_Date__c</fullName>
    <formula>Scheduled_Departure_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Schedule Departure Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Scheduled_Depature_UTC__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Depature_UTC__c</fullName>
    <description>QCC: The scheduled Departure time in UTC format</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure UTC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledArrDateTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledArrDateTime__c</fullName>
    <description>QCC: scheduled arrival date and time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Arrival Date/Time</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepDate__c</fullName>
    <description>QCC: scheduled departure date of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepTime__c</fullName>
    <description>QCC: scheduled departure time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: status of the Event</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Re-Opened</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/QCC_DisruptionWarningController.cls
/*********************************************************************************
Name         : QCC_DisruptionWarning
Created By   : Nicole Abesamis
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 28 August 2019
Usages       : This will handle the query of related passenger from Contact
*********************************************************************************/

public without sharing class QCC_DisruptionWarningController {

    //This method will return if related passenger is in disruption or not.
    @AuraEnabled
    public static DisruptionWarningWrapper getRelatedPassengerRec(String contactId) {
        System.debug('contactId: ' + contactId);
        Boolean hasRedDisruptionIcon = false;
        Boolean hasYellowDisruptionIcon = false;
        Boolean hasGreenDisruptionIcon = false;
        DisruptionWarningWrapper myWrapper = new DisruptionWarningWrapper();
        myWrapper.hasError = false;
        List<DisruptionEventWrapper> disruptionEventWrapperList = new List<DisruptionEventWrapper>();
        List<Affected_Passenger__c> passengerRecords;

       if(contactId!=null)
            passengerRecords = new List<Affected_Passenger__c>([
            SELECT Id, Passenger__c, Event__r.IntDom__c, Event__r.DelayFailureCode__c,  Event__r.FlightNumber__c, Event__r.RecordTypeId,
            Event__r.ScheduledDepDate__c, Event__r.ScheduledDepTime__c,  Event__r.Scheduled_Depature_UTC__c,
            Event__r.Schedule_Departure_Date__c,  Event__r.ScheduledArrDateTime__c, QCC_Disruption_Actioned__c, Event__r.Status__c,Event__r.Primary_Root_Cause__c,Event__r.Root_Cause__c,Event__r.Disruption_Reason_Text__c
            FROM Affected_Passenger__c
            WHERE Passenger__c =: contactId
            AND Event__r.ScheduledDepDate__c != null
            AND Event__r.ScheduledDepTime__c != null
            AND Event__r.Scheduled_Depature_UTC__c != null
            AND Event__r.Schedule_Departure_Date__c != null
            AND Event__r.ScheduledArrDateTime__c != null
        ]);

       
        Id headsUpRecordTypeId = Schema.SObjectType.Event__c.getRecordTypeInfosByName().get('Heads Up').getRecordTypeId();
        Id activeRecordTypeId = Schema.SObjectType.Event__c.getRecordTypeInfosByName().get('Flight Event - Active').getRecordTypeId();
        Id closedRecordTypeId = Schema.SObjectType.Event__c.getRecordTypeInfosByName().get('Flight Event - Closed').getRecordTypeId();
        Id offloadRecordTypeId = Schema.SObjectType.Event__c.getRecordTypeInfosByName().get('Flight Event - Offload').getRecordTypeId();

        System.debug('headsUpRecordTypeId: ' + headsUpRecordTypeId);
        System.debug('activeRecordTypeId: ' + activeRecordTypeId);
        System.debug('closedRecordTypeId: ' + closedRecordTypeId);
        System.debug('offloadRecordTypeId: ' + offloadRecordTypeId);

        try {
            system.debug('>>>passengerRecords: ' + passengerRecords);
            if(passengerRecords!=null && passengerRecords.size()>0)
            for(Affected_Passenger__c passengerRecord: passengerRecords){
                //Get datetime now
                DateTime systemNow = System.now();

                //Generate the departure date and time from string values
                Date scheduledDepartureDate = passengerRecord.Event__r.ScheduledDepDate__c;
                String scheduledDepartureTime = passengerRecord.Event__r.ScheduledDepTime__c;
                //Convert the combination of the departure date and time (which is a text) into a DateTime field
                DateTime finalDepDateTime = DateTime.valueOf(scheduledDepartureDate.year() + '-' + scheduledDepartureDate.month() + '-' + scheduledDepartureDate.day() + ' ' + scheduledDepartureTime + ':00');
                System.debug('finalDepDateTime: ' + finalDepDateTime);

                //Generate the arrival date and time from string values
                String scheduleArrivalDateTime = passengerRecord.Event__r.ScheduledArrDateTime__c;
                List<String> arrivalDateTimeSplitted = scheduleArrivalDateTime.split(' ');
                List<String> scheduleArrivalDate = arrivalDateTimeSplitted[0].split('/');
                DateTime finalArrDateTime = DateTime.valueOf(scheduleArrivalDate[2] + '-' + scheduleArrivalDate[1] + '-' + scheduleArrivalDate[0] + ' ' + arrivalDateTimeSplitted[1]);
                System.debug('finalArrDateTime: ' + finalArrDateTime);

                System.debug('passengerRecord.Event__r.IntDom__c: ' + passengerRecord.Event__r.IntDom__c);
                System.debug('passengerRecord.Event__r.DelayFailureCode__c: ' + passengerRecord.Event__r.DelayFailureCode__c);
                System.debug('passengerRecord.Event__r.RecordTypeId: ' + passengerRecord.Event__r.RecordTypeId);

                Boolean isIncluded = false;
                if (passengerRecord.Event__r.RecordTypeId == headsUpRecordTypeId) {
                    //Logic for yellow/green icon depending on QCC_Disruption_Actioned__c field
                    Boolean hasPermission = FeatureManagement.checkPermission('QCC_View_Flight_Heads_Up_Amber_Status');
                    if (systemNow < finalArrDateTime.addHours(Integer.valueOf(Label.QCC_DisruptionWarningYellow)) && hasPermission) {
                        if (!passengerRecord.QCC_Disruption_Actioned__c && passengerRecord.Event__r.Status__c != 'Closed') {
                            hasYellowDisruptionIcon = true;
                            isIncluded = true;
                        } else if (passengerRecord.QCC_Disruption_Actioned__c || passengerRecord.Event__r.Status__c == 'Closed') {
                            hasGreenDisruptionIcon = true;
                            isIncluded = true;
                        }
                    }
                } else if (passengerRecord.Event__r.RecordTypeId == activeRecordTypeId ||
                           passengerRecord.Event__r.RecordTypeId == closedRecordTypeId ||
                           passengerRecord.Event__r.RecordTypeId == offloadRecordTypeId)
                {
                    //Logic for red/green icon depending on QCC_Disruption_Actioned__c field
                    if ((passengerRecord.Event__r.DelayFailureCode__c == 'Flight Delay' && systemNow < finalArrDateTime.addHours(Integer.valueOf(Label.QCC_DisruptionWarningRedFlightDelay))) ||
                        (passengerRecord.Event__r.IntDom__c == 'Domestic' && systemNow < finalDepDateTime.addHours(Integer.valueOf(Label.QCC_DisruptionWarningRedDomestic))) ||
                        (passengerRecord.Event__r.IntDom__c == 'International' && systemNow < finalDepDateTime.addHours(Integer.valueOf(Label.QCC_DisruptionWarningRedInternational))))
                    {
                        if (!passengerRecord.QCC_Disruption_Actioned__c) {
                            hasRedDisruptionIcon = true;
                        } else {
                            hasGreenDisruptionIcon = true;
                        }
                        isIncluded = true;
                    }
                }

                System.debug('isIncluded: ' + isIncluded);

                //Add to Disruption Event List
                if (isIncluded) {
                    disruptionEventWrapperList.add(
                        new DisruptionEventWrapper(
                            passengerRecord.Event__r.DelayFailureCode__c,
                            passengerRecord.Event__r.FlightNumber__c,
                            finalDepDateTime.format('dd/MM/y HH:mm'),
                            passengerRecord.Event__r.Primary_Root_Cause__c,
                            passengerRecord.Event__r.Root_Cause__c,
                            passengerRecord.Event__r.Disruption_Reason_Text__c
                        )
                    );
                }
            }
        } catch (Exception ex) {
            myWrapper.hasError = true;
            myWrapper.errorMessage = ex.getMessage();
            Log__c logRecord = QCC_LogUtilityHelper.generateLogRecord('QCC - Disruption Warning', 'QCC_DisruptionWarningController', 'getRelatedPassengerRec', '', '', false, '', ex, '');
            QCC_LogUtilityHelper.createLogRecord(logRecord);
        }

        if (hasRedDisruptionIcon) {
            myWrapper.iconToDisplay = 'redIcon';
        } else if (hasYellowDisruptionIcon) {
            myWrapper.iconToDisplay = 'yellowIcon';
        } else if (hasGreenDisruptionIcon) {
            myWrapper.iconToDisplay = 'greenIcon';
        } else {
            myWrapper.iconToDisplay = '';
        }

        myWrapper.disruptionEvents = disruptionEventWrapperList;

        return myWrapper;
    }

    public class DisruptionWarningWrapper {
        @AuraEnabled public Boolean hasError {get;set;}
        @AuraEnabled public String errorMessage {get;set;}
        @AuraEnabled public String iconToDisplay {get;set;}
        @AuraEnabled public List<DisruptionEventWrapper> disruptionEvents {get;set;}
    }

    public class DisruptionEventWrapper {
        @AuraEnabled public String delayFailureCode {get;set;}
        @AuraEnabled public String flightNumber {get;set;}
        @AuraEnabled public String scheduleDepartureDateTime {get;set;}
        @AuraEnabled public String primaryRootcause {get;set;}
        @AuraEnabled public String rootCause {get;set;}
        @AuraEnabled public String employeeMessage {get;set;}
        public DisruptionEventWrapper(String failureCode, String flightNo, String departureDateTime, String primarryrtCause, String rtCause, String empmessage) {
            delayFailureCode = failureCode;
            flightNumber = flightNo;
            scheduleDepartureDateTime = departureDateTime;
            primaryRootcause = primarryrtCause;
            rootCause = rtCause;
            employeeMessage = empmessage;
        }
    }
}