force-app/main/default/objects/QCC_Other_Waiver__c/QCC_Other_Waiver__c.object-meta.xml
<CustomObject>
    <description>Container for waivers entered into Aqire to be recorded against the customer</description>
    <label>Other Waiver</label>
    <nameField>
        <displayFormat>W{00000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Waivers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QCC_Other_Waiver__c/fields/QCC_Amount__c.field-meta.xml
<CustomField>
    <fullName>QCC_Amount__c</fullName>
    <description>Amount which has been wavered for the customer</description>
    <inlineHelpText>Please add either currency or points in a whole amount, to display in the Value field</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QCC_Other_Waiver__c/fields/QCC_Reason__c.field-meta.xml
<CustomField>
    <fullName>QCC_Reason__c</fullName>
    <description>The reason for making the waiver</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The reason for making the waiver</inlineHelpText>
    <label>Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_Other_Waiver__c/fields/QCC_Status__c.field-meta.xml
<CustomField>
    <fullName>QCC_Status__c</fullName>
    <description>Status of the waiver which can either be manually set based on business rules or will be automatically set by the approval process</description>
    <inlineHelpText>Status of the waiver</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_OtherWaiverTriggerHelperTest.cls
/*********************************************************************************
Name         : QCC_OtherWaiverTriggerHelperTest
Created By   : Rafael Escuadra
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 21 FEB 2020
Usages       : This class is used for the code coverage of the apex class QCC_OtherWaiverTriggerHelper

Modified By : Venkata Suresh Kumar (TCS Team), 18-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method. Added Test.start and Test.Stop methods 
*********************************************************************************/
@isTest
public class QCC_OtherWaiverTriggerHelperTest {
    
 
    static QCC_Other_Waiver__c otherWaiver;
    
    @testSetUp
    public static void setupTestData(){
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        List<Trigger_Status__c> customSettingTriggerStatusLists = QCC_TestDataFactory.createTriggerStatusData();
   		insert customSettingTriggerStatusLists;
        List<Trigger_Status__c> customSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusOtherWaiver', null, null, null, null);
        insert customSettingList;
        
        //create test data  for User object
        Profile qantasCcConsultantProfile = [Select Id, Name from Profile where Name = 'Qantas CC Consultant'];
       	User qantasCcConsultantUser = QCC_TestDataFactory.createUserTestData(qantasCcConsultantProfile.Id);
        qantasCcConsultantUser.username  = 'consultant@user.com';
        insert qantasCcConsultantUser;
        
        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        List<Contact> contactList = new List<Contact>();
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.RecordTypeId = contactRecordTypeId;
        insert contactRecord;
        
        //Create test data for Other_Waiver__c object
        otherWaiver = QCC_TestDataFactory.createOtherWaiverTestData(qantasCcConsultantUser.Id, contactRecord.Id);
        otherWaiver.QCC_Status__c = 'Open';
        otherWaiver.QCC_Amount__c = 5000;
        otherWaiver.QCC_Reason__c = 'Delete Me';
        insert otherWaiver;
    }
    
    static testMethod void testDeleteOtherWaiver() {        
        //As Qantas Cc Consultant, you would not be able to delete QCC_Other_Waiver__c records.
        User qantasCcConsultantUser = [SELECT id FROM User WHERE Username = 'consultant@user.com'];
        Test.startTest();
        QCC_Other_Waiver__c otherWaiverRecord = [SELECT id FROM QCC_Other_Waiver__c WHERE QCC_Reason__c = 'Delete Me'];
        System.runAs(qantasCcConsultantUser){    
            try{
                Delete otherWaiverRecord;
            }catch(exception ex){
                System.assert(ex.getMessage().contains('User does not have the right access to delete this record'));
            }
        }
        
       	//deleting as administrator should be successful
        Delete otherWaiverRecord;
        List<QCC_Other_Waiver__c> OtherWaivers  = new List<QCC_Other_Waiver__c>([SELECT id FROM QCC_Other_Waiver__c WHERE QCC_Reason__c = 'Delete Me']);
		System.assertEquals(0,OtherWaivers.size(), 'No record should be retrieved since it will be successfully deleted by Admin');
        Test.stopTest();        
    }
}