force-app/main/default/objects/Asset/fields/Applied_GST__c.field-meta.xml
<CustomField>
    <fullName>Applied_GST__c</fullName>
    <label>Applied GST (system)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Batch_Run__c.field-meta.xml
<CustomField>
    <fullName>Batch_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be set to true when batch Runs and reset to false once completed</description>
    <label>Batch Run [System]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Join_Fee_Gross__c.field-meta.xml
<CustomField>
    <fullName>Join_Fee_Gross__c</fullName>
    <label>Join Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Join_Fee_GST__c.field-meta.xml
<CustomField>
    <fullName>Join_Fee_GST__c</fullName>
    <label>Join Fee GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Join_Fee_Points__c.field-meta.xml
<CustomField>
    <fullName>Join_Fee_Points__c</fullName>
    <label>Join Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Join_Fee_Points_Published__c.field-meta.xml
<CustomField>
    <fullName>Join_Fee_Points_Published__c</fullName>
    <label>Published Join Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Join_Fee_Published__c.field-meta.xml
<CustomField>
    <fullName>Join_Fee_Published__c</fullName>
    <label>Published Join Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Member_Fee_Discount__c.field-meta.xml
<CustomField>
    <fullName>Member_Fee_Discount__c</fullName>
    <label>Qantas Club Member Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Override_Fees_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Override_Fees_Calculation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the User to Override the Member Fees Discount</description>
    <label>Override Fees Calculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Override_Waiver_Discounts_Active__c.field-meta.xml
<CustomField>
    <fullName>Override_Waiver_Discounts_Active__c</fullName>
    <formula>IF(Waiver_Start_Date__c &lt;= Today() &amp;&amp;  Waiver_End_Date__c &gt;= Today(), true, false)</formula>
    <inlineHelpText>Checked if date today falls within override / waiver start and end dates</inlineHelpText>
    <label>Override / Waiver Discounts Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Qantas_Club_Join_Discount__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Club_Join_Discount__c</fullName>
    <label>Qantas Club Join Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Qantas_Club_Join_Discount_Offer__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Club_Join_Discount_Offer__c</fullName>
    <formula>IF(NOT(ISBLANK(TEXT(Contract__r.Qantas_Club_Join_Discount_Offer__c))),
VALUE(SUBSTITUTE(TEXT(Contract__r.Qantas_Club_Join_Discount_Offer__c), &quot;%&quot;,&quot;&quot;))/100,0)</formula>
    <label>Qantas Club Join Discount Offer</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Qantas_Club_Member_Discount_Offer__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Club_Member_Discount_Offer__c</fullName>
    <formula>IF(NOT(ISBLANK(TEXT(Contract__r.Qantas_Club_Discount_Offer__c))),
VALUE(SUBSTITUTE(TEXT(Contract__r.Qantas_Club_Discount_Offer__c), &quot;%&quot;,&quot;&quot;))/100,0)</formula>
    <label>Qantas Club Member Discount Offer</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_Currency__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Currency__c</fullName>
    <label>Scheme Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
                <default>true</default>
                <label>AUD</label>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Discount_Type__c</fullName>
    <description>Only Coordinator, Individual and Retail</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheme Discount Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_Type__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Type__c</fullName>
    <label>Scheme Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Fee_Gross__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Fee_Gross__c</fullName>
    <label>1 Yr M&apos;ship Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Fee_GST__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Fee_GST__c</fullName>
    <label>1 Year Membership Fee GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Fee_Points__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Fee_Points__c</fullName>
    <label>1 Yr M&apos;ship Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Fee_Points_Published__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Fee_Points_Published__c</fullName>
    <label>Published 1 Yr M&apos;ship Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Fee_Published__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Fee_Published__c</fullName>
    <label>Published 1 Yr M&apos;ship Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Renewal_Fee__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Renewal_Fee__c</fullName>
    <description>Used in AssetTriggerHandler</description>
    <label>1 Yr M&apos;ship Renewal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Renewal_Fee_GST__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Renewal_Fee_GST__c</fullName>
    <label>1 Yr M&apos;ship Renewal Fee GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Renewal_Fee_Points__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Renewal_Fee_Points__c</fullName>
    <label>1 Yr M&apos;ship Renewal Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Year_Membership_Renewal_Fee_Published__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Renewal_Fee_Published__c</fullName>
    <label>Published 1 Yr M&apos;ship Renewal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X1_Yr_Mship_Renewal_Fee_Points_Published__c.field-meta.xml
<CustomField>
    <fullName>X1_Yr_Mship_Renewal_Fee_Points_Published__c</fullName>
    <label>Published 1 Yr M&apos;ship Renewal Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X2_Year_Membership_Fee_Gross__c.field-meta.xml
<CustomField>
    <fullName>X2_Year_Membership_Fee_Gross__c</fullName>
    <label>2 Yr M&apos;ship Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X2_Year_Membership_Fee_points__c.field-meta.xml
<CustomField>
    <fullName>X2_Year_Membership_Fee_points__c</fullName>
    <label>2 Year Membership Fee points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X2_Year_Membership_Renewal_Fee__c.field-meta.xml
<CustomField>
    <fullName>X2_Year_Membership_Renewal_Fee__c</fullName>
    <label>2 Yr M&apos;ship Renewal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X2_Year_Membership_Renewal_Fee_Points__c.field-meta.xml
<CustomField>
    <fullName>X2_Year_Membership_Renewal_Fee_Points__c</fullName>
    <label>2 Yr M&apos;ship Renewal Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X2_Year_Membership_Renewal_Fee_Published__c.field-meta.xml
<CustomField>
    <fullName>X2_Year_Membership_Renewal_Fee_Published__c</fullName>
    <label>Published 2 Yr M&apos;ship Renewal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/X2_Yr_Mship_Renewal_Fee_Points_Published__c.field-meta.xml
<CustomField>
    <fullName>X2_Yr_Mship_Renewal_Fee_Points_Published__c</fullName>
    <label>Published 2 Yr M&apos;ship Renewal Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/SchemeFees__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Loyalty Holds the Scheme Fees Details</description>
    <label>Scheme Fees</label>
</CustomObject>

force-app/main/default/objects/SchemeFees__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Join_Fee_Exculde_GST__c.field-meta.xml
<CustomField>
    <fullName>Join_Fee_Exculde_GST__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Join Fee Exculde GST</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Join_Fee_Points__c.field-meta.xml
<CustomField>
    <fullName>Join_Fee_Points__c</fullName>
    <label>Join Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Membership_Fee_Exclude_GST__c.field-meta.xml
<CustomField>
    <fullName>Membership_Fee_Exclude_GST__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Membership Fee Exclude GST</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Published_1_Year_Membership_Fee__c.field-meta.xml
<CustomField>
    <fullName>Published_1_Year_Membership_Fee__c</fullName>
    <label>Published 1 Year Membership Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Published_2_Year_Membership_Fee__c.field-meta.xml
<CustomField>
    <fullName>Published_2_Year_Membership_Fee__c</fullName>
    <label>Published 2 Year Membership Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Published_Join_Fee__c.field-meta.xml
<CustomField>
    <fullName>Published_Join_Fee__c</fullName>
    <label>Published Join Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Scheme_Type__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheme Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/X1_Year_Membership_Fee_Points__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Fee_Points__c</fullName>
    <label>Publised 1 Year Membership Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/X1_Year_Membership_Renewal_Fee_Published__c.field-meta.xml
<CustomField>
    <fullName>X1_Year_Membership_Renewal_Fee_Published__c</fullName>
    <label>Published 1 Yr M&apos;ship Renewal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/X1_Yr_Mship_Renewal_Fee_Points_Published__c.field-meta.xml
<CustomField>
    <fullName>X1_Yr_Mship_Renewal_Fee_Points_Published__c</fullName>
    <label>Published 1 Yr M&apos;ship Renewal Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/X2_Year_Membership_Fee_points__c.field-meta.xml
<CustomField>
    <fullName>X2_Year_Membership_Fee_points__c</fullName>
    <label>Publised 2 Year Membership Fee points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/X2_Year_Membership_Renewal_Fee_Published__c.field-meta.xml
<CustomField>
    <fullName>X2_Year_Membership_Renewal_Fee_Published__c</fullName>
    <label>Published 2 Yr M&apos;ship Renewal Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/X2_Yr_Mship_Renewal_Fee_Points_Published__c.field-meta.xml
<CustomField>
    <fullName>X2_Yr_Mship_Renewal_Fee_Points_Published__c</fullName>
    <label>Published 2 Yr M&apos;ship Renewal Fee Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AssetTriggerHelper.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Benazir Amir/Praveen Sampath 
Company:       Capgemini
Description:   Class to be invoked from Asset Trigger
Inputs:        
Test Class:    AssetTriggerHelperTest. 
************************************************************************************************
History     Refactored the code to remove system debug and commented code that is not required
************************************************************************************************

-----------------------------------------------------------------------------------------------------------------------*/
public class AssetTriggerHelper{

    /*--------------------------------------------------------------------------------------      
    Method Name:        calculateAssetFeesandDiscounts
    Description:        corporate scheme field updates with published rates and applied discounts
    Parameter:           new Map and old Map records
    --------------------------------------------------------------------------------------*/      
    public static void convertingAssetType(Map<Id,Asset> newAssetMap, map<Id,Asset> oldAssetMap){
        try{
            //Get record type and published fees from custom settings
            String corpSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Corporate Scheme Rec Type');
            Id corpSchemeRecTypeId = GenericUtils.getObjectRecordTypeId('Asset', corpSchemeRecTypeName );
            String publicSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Public Scheme Rec Type');
            Id publicSchemeRecTypeId = GenericUtils.getObjectRecordTypeId('Asset', publicSchemeRecTypeName );
            
            Map<Id, Id> accOwnerMap = new Map<Id, Id>();
            Set<Id> setAccId = new Set<Id>();
            for(Asset objAsset: newAssetMap.values()){
                if(objAsset.RecordtypeId == corpSchemeRecTypeId && objAsset.RecordtypeId != oldAssetMap.get(objAsset.Id).RecordtypeId){
                    setAccId.add(objAsset.AccountId);
                }
            }
            
            //Get Corp account Owner Id
            for(Account acc: [Select Id, OwnerId from Account where Id IN: setAccId]){
                accOwnerMap.put(acc.Id, acc.OwnerId);
            }

            for(Asset objAsset: newAssetMap.values()){
                Asset objOldAsset = oldAssetMap.get(objAsset.Id);
                if(objAsset.RecordtypeId != objOldAsset.RecordtypeId){
                    if(objAsset.RecordtypeId == corpSchemeRecTypeId){
                        AssetObjectHelper.convertPublicSchmeToCorporateSchemeUI(objAsset, accOwnerMap.containsKey(objAsset.AccountId)?accOwnerMap.get(objAsset.AccountId):Null);
                    }else if(objAsset.RecordtypeId == publicSchemeRecTypeId){
                        AssetObjectHelper.convertCorporateSchmeToPublicSchemeUI(objAsset);
                    }
                }
            }
        }catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Asset Triggers - Loyalty', 'AssetTriggerHelper', 
                                     'convertingAssetType', String.valueOf(''), String.valueOf(''),false,'', ex);
        
        }

    }
   
    
    /*--------------------------------------------------------------------------------------      
    Method Name:        calculateAssetFeesandDiscounts
    Description:        corporate scheme field updates with published rates and applied discounts
    Parameter:          List of new and old Map records
    --------------------------------------------------------------------------------------*/      
    public static void calculateAssetFeesandDiscounts(List<Asset> newAssetList, map<Id,Asset> oldAssetMap){
        try{
            //Get record type and published fees from custom settings
            String corpSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Corporate Scheme Rec Type');
            Id corpSchemeRecTypeId = GenericUtils.getObjectRecordTypeId('Asset', corpSchemeRecTypeName );
            String publicSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Public Scheme Rec Type');
            Id publicSchemeRecTypeId = GenericUtils.getObjectRecordTypeId('Asset', publicSchemeRecTypeName );
            
            //Scheme Fees Metadata 
            Map<String, SchemeFees__c> mapSchemeFee = new Map<String, SchemeFees__c>();
            for(SchemeFees__c  fee: SchemeFees__c.getall().values() ){
                mapSchemeFee.put(fee.Currency__c+''+fee.Scheme_Type__c, fee);
            }
            
            for(Asset objAsset: newAssetList){
                //Old Asset values 
                Asset objOldAsset  = oldAssetMap != Null? oldAssetMap.get(objAsset.Id): Null;
                Boolean isValid = false;

                //Check Old Map and New Map, To find it is a Valid Update to recalculate
                if(objAsset.Batch_Run__c){
                    isValid = true;
                }else if(objOldAsset == Null){
                    isValid = true;
                }
                else if(objOldAsset != Null){
                    List<Schema.FieldSetMember> lstAssetFields = SObjectType.Asset.FieldSets.Scheme_Fee_Fields.getFields();
                    for(Schema.FieldSetMember assetField: lstAssetFields){
                        if(objAsset.get(assetField.getFieldPath()) != objOldAsset.get(assetField.getFieldPath())){
                            isValid = true;
                            break;
                        }
                    }
                }

                  
                if(isValid && (objAsset.RecordTypeId == publicSchemeRecTypeId || objAsset.RecordTypeId == corpSchemeRecTypeId))
                {
                    
                    //Get GST % from custom setting
                    objAsset.Applied_GST__c = Double.valueOf(CustomSettingsUtilities.getConfigDataMap('GST Rate '+objAsset.Scheme_Currency__c));
                    string selectedCurrency = (objAsset.Scheme_Currency__c == 'AUD') || (objAsset.Scheme_Currency__c == 'NZD') ? objAsset.Scheme_Currency__c : '000'; 
                    objAsset.CurrencyIsoCode = objAsset.Scheme_Currency__c;

                    //Get Scheme Base on Currency and Scheme Type
                    SchemeFees__c currentScheme =  mapSchemeFee.containsKey(selectedCurrency+''+objAsset.Scheme_Discount_Type__c)?mapSchemeFee.get(selectedCurrency+''+objAsset.Scheme_Discount_Type__c):Null;
                    
                    if(currentScheme != Null){
                        system.debug('currentScheme########'+currentScheme);
                         //Get Join Discount and Fee Discount percent
                        Decimal feeDiscount = 0;
                        Decimal joiningDiscount = 0;
                        //Adding Flat Disount for Public Scheme CRM-10572
                        if(objAsset.RecordTypeId == publicSchemeRecTypeId )
                        {
                         feeDiscount =  Double.valueOf(CustomSettingsUtilities.getConfigDataMap('Public Scheme Discount Rate'));
                         joiningDiscount = Double.valueOf(CustomSettingsUtilities.getConfigDataMap('Public Scheme Joining Discount Rate'));
                        }
                        else
                        {
                        if(objAsset.Override_Waiver_Discounts_Active__c == true){
                            feeDiscount = objAsset.Member_Fee_Discount__c == Null?0 :objAsset.Member_Fee_Discount__c;
                            joiningDiscount = objAsset.Qantas_Club_Join_Discount__c == Null?0 :objAsset.Qantas_Club_Join_Discount__c;
                        }else{
                            feeDiscount = objAsset.Qantas_Club_Member_Discount_Offer__c == Null?0 :objAsset.Qantas_Club_Member_Discount_Offer__c;
                            joiningDiscount = objAsset.Qantas_Club_Join_Discount_Offer__c == Null?0 :objAsset.Qantas_Club_Join_Discount_Offer__c;
                            
                        }
                        }
                        
                        
                        Integer roundOffNumber = Integer.valueOf(CustomSettingsUtilities.getConfigDataMap('SchemesPointRoundOffNumber'));
                        
                        //Don't Calculate Point and Fee when Override is true
                        if(objAsset.Override_Fees_Calculation__c != true){
                            objAsset.Join_Fee_Gross__c = currentScheme.Published_Join_Fee__c *((100-joiningDiscount)/100);
                            Integer joinPoints = Integer.valueOf(currentScheme.Join_Fee_Points__c *((100-joiningDiscount)/100));
                            objAsset.Join_Fee_Points__c = roundOffNumber*Math.round((joinPoints/roundOffNumber));
                            
                            objAsset.X1_Year_Membership_Fee_Gross__c = currentScheme.Published_1_Year_Membership_Fee__c *((100-feeDiscount)/100);
                            Integer oneYRPoints = Integer.valueOf(currentScheme.X1_Year_Membership_Fee_Points__c *((100-feeDiscount)/100));
                            objAsset.X1_Year_Membership_Fee_Points__c = roundOffNumber*Math.round((oneYRPoints/roundOffNumber));

                            objAsset.X2_Year_Membership_Fee_Gross__c = currentScheme.Published_2_Year_Membership_Fee__c *((100-feeDiscount)/100);
                            Integer twoYRPoints = Integer.valueOf(currentScheme.X2_Year_Membership_Fee_points__c *((100-feeDiscount)/100)); 
                            objAsset.X2_Year_Membership_Fee_Points__c = roundOffNumber*Math.round((twoYRPoints/roundOffNumber));
                            
                            objAsset.X1_Year_Membership_Renewal_Fee__c =  currentScheme.X1_Year_Membership_Renewal_Fee_Published__c*((100-feeDiscount)/100);
                            Integer oneYRRenewalPoints = Integer.valueOf(currentscheme.X1_Yr_Mship_Renewal_Fee_Points_Published__c*((100-feeDiscount)/100));
                            objAsset.X1_Year_Membership_Renewal_Fee_Points__c = roundOffNumber*Math.round((oneYRRenewalPoints/roundOffNumber));
                            
                           
                            objAsset.X2_Year_Membership_Renewal_Fee__c =  currentScheme.X2_Year_Membership_Renewal_Fee_Published__c*((100-feeDiscount)/100);
                            Integer twoYRRenewalPoints = Integer.valueOf(currentscheme.X2_Yr_Mship_Renewal_Fee_Points_Published__c*((100-feeDiscount)/100));
                            objAsset.X2_Year_Membership_Renewal_Fee_Points__c = roundOffNumber*Math.round((twoYRRenewalPoints/roundOffNumber));
                     
                        }

                        //All Join Fee Calculation
                        objAsset.Join_Fee_Published__c = currentScheme.Published_Join_Fee__c;
                        objAsset.Join_Fee_GST__c = currentScheme.Join_Fee_Exculde_GST__c || objAsset.Join_Fee_Gross__c == Null? 0 :objAsset.Applied_GST__c*(objAsset.Join_Fee_Gross__c  /(100.0+objAsset.Applied_GST__c));
                        objAsset.Join_Fee_Points_Published__c = currentScheme.Join_Fee_Points__c;
                        
                        //All First Year Calculation
                        objAsset.X1_Year_Membership_Fee_Published__c = currentScheme.Published_1_Year_Membership_Fee__c;
                        objAsset.X1_Year_Membership_Fee_GST__c = currentScheme.Membership_Fee_Exclude_GST__c || objAsset.X1_Year_Membership_Fee_Gross__c == Null? 0 :objAsset.Applied_GST__c*(objAsset.X1_Year_Membership_Fee_Gross__c  /(100.0+objAsset.Applied_GST__c));
                        objAsset.X1_Year_Membership_Fee_Points_Published__c = currentScheme.X1_Year_Membership_Fee_Points__c;
                        objAsset.X1_Year_Membership_Renewal_Fee_Published__c = currentScheme.X1_Year_Membership_Renewal_Fee_Published__c;
                        objAsset.X1_Yr_Mship_Renewal_Fee_Points_Published__c = currentScheme.X1_Yr_Mship_Renewal_Fee_Points_Published__c;
                        objAsset.X1_Year_Membership_Renewal_Fee_GST__c =  currentScheme.Membership_Fee_Exclude_GST__c || objAsset.X1_Year_Membership_Renewal_Fee__c == Null? 0 :objAsset.Applied_GST__c*(objAsset.X1_Year_Membership_Renewal_Fee__c/(100.0+objAsset.Applied_GST__c));
                        //All Secound year Calculation
                        objAsset.X2_Year_Membership_Fee_Published__c = currentScheme.Published_2_Year_Membership_Fee__c;
                        objAsset.X2_Year_Membership_Fee_GST__c = currentScheme.Membership_Fee_Exclude_GST__c || objAsset.X2_Year_Membership_Fee_Gross__c == Null? 0 :objAsset.Applied_GST__c*(objAsset.X2_Year_Membership_Fee_Gross__c  /(100.0+objAsset.Applied_GST__c));
                        objAsset.X2_Year_Membership_Fee_Points_Published__c = currentScheme.X2_Year_Membership_Fee_points__c;
                        objAsset.X2_Year_Membership_Renewal_Fee_Published__c = currentScheme.X2_Year_Membership_Renewal_Fee_Published__c;
                        objAsset.X2_Yr_Mship_Renewal_Fee_Points_Published__c = currentScheme.X2_Yr_Mship_Renewal_Fee_Points_Published__c;
                        objAsset.X2_Year_Membership_Renewal_Fee_GST__c =  currentScheme.Membership_Fee_Exclude_GST__c || objAsset.X2_Year_Membership_Renewal_Fee__c == Null? 0 :objAsset.Applied_GST__c*(objAsset.X2_Year_Membership_Renewal_Fee__c/(100.0+objAsset.Applied_GST__c));
                       
              
                    }
                }


                //Back to false after Batch Run
                if(objAsset.Batch_Run__c){
                    objAsset.Batch_Run__c = false;
                }
            }
        }
        catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Asset Triggers - Loyalty', 'AssetTriggerHelper', 
                                     'calculateAssetFeesandDiscounts', String.valueOf(''), String.valueOf(''),false,'', ex);
        }   
    }
    
   /*--------------------------------------------------------------------------------------      
    Method Name:        calculateFourthYearMembership
    Description:        All Fourth year Calculation. Only for Public Scheme - Commented for CRM- 10164
    
    --------------------------------------------------------------------------------------*/
    
   /* Public static void calculateFourthYearMembership (Asset objAsset, SchemeFees__c currentScheme, Decimal roundOffNumber, Decimal feeDiscount ){
      if( currentScheme.Published_4_Year_Membership_Fee__c != Null){
            objAsset.X4_Year_Membership_Fee_Published__c =currentScheme.Published_4_Year_Membership_Fee__c;
            objAsset.X4_Year_Membership_Fee_Gross__c = currentScheme.Published_4_Year_Membership_Fee__c *((100-feeDiscount)/100);
            objAsset.X4_Year_Membership_Fee_GST__c = currentScheme.Membership_Fee_Exclude_GST__c? 0 :objAsset.Applied_GST__c*(objAsset.X4_Year_Membership_Fee_Gross__c  /(100.0+objAsset.Applied_GST__c));
        }
        if(currentScheme.Published_4_Year_Membership_Fee_Points__c != Null ){
            objAsset.X4_Year_Membership_Fee_Points_Published__c = currentScheme.Published_4_Year_Membership_Fee_Points__c;
            Integer fourYRPoints = Integer.valueOf(currentScheme.Published_4_Year_Membership_Fee_Points__c*((100-feeDiscount)/100));
            objAsset.X4_Year_Membership_Fee_Points__c = roundOffNumber*Math.round((fourYRPoints/roundOffNumber));
        }
    
    }*/
}