force-app/main/default/objects/Asset/fields/Batch_Run__c.field-meta.xml
<CustomField>
    <fullName>Batch_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be set to true when batch Runs and reset to false once completed</description>
    <label>Batch Run [System]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_Currency__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Currency__c</fullName>
    <label>Scheme Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
                <default>true</default>
                <label>AUD</label>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Discount_Type__c</fullName>
    <description>Only Coordinator, Individual and Retail</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheme Discount Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_Type__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Type__c</fullName>
    <label>Scheme Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SchemeFees__c/SchemeFees__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Loyalty Holds the Scheme Fees Details</description>
    <label>Scheme Fees</label>
</CustomObject>

force-app/main/default/objects/SchemeFees__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SchemeFees__c/fields/Scheme_Type__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheme Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SchemeFee_Daily_Update_Check_Batch.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Praveen Sampath
Company:       Capgemini
Description:   Batch Class to Update the Scheme Fees when there is a chnage on the Scheme Fee Custom Setting Value
Test Class:    
*********************************************************************************************************************************
*********************************************************************************************************************************
History
*********************************************************************************************************************************

**********************************************************************************************************************************/
global class SchemeFee_Daily_Update_Check_Batch implements Database.Batchable<sObject>, Database.Stateful{
    
    String query;
    Set<Id> setAssetRecTypeId = new Set<Id>();
    Set<String> setCurrency = new Set<String>();
    Set<String> setSchemetype = new Set<String>(); 
    global Map<String, List<String>> mapError;
   


    /*----------------------------------------------------------------------------------------------------      
    Method Name:        SchemeFee_Daily_Update_Check_Batch
    Description:        Daily Update Batch Method
    Parameter:          List of Scheme Fee Record and a Boolean check to determine the Schedule Run
    -----------------------------------------------------------------------------------------------------*/             
    global SchemeFee_Daily_Update_Check_Batch(Boolean isAllRun, List<SchemeFees__c> lstSchemeFee) {
        mapError = new Map<String, List<String>>();
        String corpSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Corporate Scheme Rec Type');
        setAssetRecTypeId.add(GenericUtils.getObjectRecordTypeId('Asset', corpSchemeRecTypeName ));
        
        String publicSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Public Scheme Rec Type');
        setAssetRecTypeId.add(GenericUtils.getObjectRecordTypeId('Asset', publicSchemeRecTypeName ));
       
        query = 'Select Id, Batch_Run__c from Asset where ';
        query += 'RecordTypeId IN: setAssetRecTypeId and status != \'Inactive\'';
        if(lstSchemeFee != Null && lstSchemeFee.size()>0){
            for(SchemeFees__c fee: lstSchemeFee){
                setSchemetype.add(fee.Scheme_Type__c);
                setCurrency.add(fee.Currency__c);
            }
            query += ' and Scheme_Currency__c IN: setCurrency and Scheme_Discount_Type__c IN: setSchemetype';
        }
    }
    
    /*----------------------------------------------------------------------------------------------------      
    Method Name:        SchemeFee_Daily_Update_Check_Batch
    Description:        Daily Update Batch Method
    Parameter:          List of Scheme Fee Records 
    -----------------------------------------------------------------------------------------------------*/  
    global SchemeFee_Daily_Update_Check_Batch(String batchQuery){
        mapError = new Map<String, List<String>>();
        query = batchQuery;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('query######'+query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Asset> lstAssets) {
        system.debug('lstAssets#######'+lstAssets);
        for(Asset objAsset: lstAssets){
            objAsset.Batch_Run__c = true;
        }
        Integer i = 0;
        Database.SaveResult[] lstSaveResult = Database.update(lstAssets, False);
        for(Database.SaveResult sr : lstSaveResult){ 
            if (!sr.isSuccess()) { 
                Id assetId = lstAssets[i].Id;
                List<String> lstErrorMSG = new List<String>();
                for(Database.Error err : sr.getErrors()){
                    lstErrorMSG.add(err.getMessage());
                }
                mapError.put(assetId, lstErrorMSG);
            }
            i++;
        }
    }

    global void finish(Database.BatchableContext BC) {
        List<Log__c> lstLogException = new List<Log__c>();
        Integer i = 0;

        for(String assetId: mapError.keyset()){
            lstLogException.add(CreateLogs.insertLogBatchRec( 'Log Exception Logs Rec Type', 'Loyalty Batches', 'SchemeFee_Daily_Update_Check_Batch', 
                                     'execute', assetId, mapError.get(assetId)));
            i++;
        }
        insert lstLogException;
    }
    
}