force-app/main/default/objects/Asset/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Move_to_Public_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Move_to_Public_Scheme__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFSCHEMES-22 --&gt; Convert to Public scheme, during the renewal process.</description>
    <label>Move to Public Scheme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Override_Fees_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Override_Fees_Calculation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the User to Override the Member Fees Discount</description>
    <label>Override Fees Calculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_End_Date_f__c.field-meta.xml
<CustomField>
    <fullName>Scheme_End_Date_f__c</fullName>
    <formula>IF(
RecordType.DeveloperName == &apos;Corporate_Scheme&apos;,
Contract__r.Contract_End_Date__c,
IF(
RecordType.DeveloperName == &apos;Public_Scheme&apos;,
Public_Scheme_End_Date__c,
null
)
)</formula>
    <label>Scheme End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the end date for the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the start date for the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/PreviousContract__c.field-meta.xml
<CustomField>
    <fullName>PreviousContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for Loyalty. Will hold the previous contract if this is a extension contract. All Corporate schmes attached to the prevous contracts will be reparented automatically on the previus contract end date.</description>
    <inlineHelpText>Holds the Previous contract Value, If this Contract is an Extention of any.</inlineHelpText>
    <label>Previous Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contracts &amp; Agreements</relationshipLabel>
    <relationshipName>Contracts_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required - Internal</fullName>
            </value>
            <value>
                <fullName>Signature Required by Customer</fullName>
            </value>
            <value>
                <fullName>Signed by Customer</fullName>
            </value>
            <value>
                <fullName>Rejected - Customer</fullName>
            </value>
            <value>
                <fullName>Rejected – Legal</fullName>
            </value>
            <value>
                <fullName>Approval Required – Legal</fullName>
            </value>
            <value>
                <fullName>Rejected - Internal</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Superceded</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Airfares</fullName>
            </value>
            <value>
                <fullName>Qantas Business Savings</fullName>
                <default>true</default>
                <label>Qantas Business Savings</label>
            </value>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>FIFO Scheduled</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CorporateScheme_Contract_Renewal_Batch.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Praveen Sampath 
Company:       Capgemini
Description:   Batch Class to Remap the new Contract when old Contract expies
Inputs:        
Test Class:     
************************************************************************************************
History
************************************************************************************************

-----------------------------------------------------------------------------------------------------------------------*/
global class CorporateScheme_Contract_Renewal_Batch implements Database.Batchable<sObject>, Database.Stateful{
	
	String batchQuery;
    global Map<String, List<String>> mapError;
    
	global CorporateScheme_Contract_Renewal_Batch(String query) {
		batchQuery = query;
		mapError = new Map<String, List<String>>();
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		system.debug('query111111111111111####'+batchQuery);
		return Database.getQueryLocator(batchQuery);
	}

   	global void execute(Database.BatchableContext BC, List<Contract__c> lstContract) {
    	try{
	   		List<Asset> lstUpdateAsset = new List<Asset>();
	   		Map<Id, Id> mapOldandNewContract = new Map<Id, Id>();
	   		String corpSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Corporate Scheme Rec Type');
	        Id corpSchemeRecTypeId = GenericUtils.getObjectRecordTypeId('Asset', corpSchemeRecTypeName );
	        Map<String, Id> mapEndContract = new Map<String, Id>();
	        Set<Id> setAccId = new Set<Id>();

			if(lstContract != Null && lstContract.size()>0){
				for(Contract__c objContract: lstContract){
					
					if(objContract.Contract_End_Date__c == System.today().addDays(-1)){
						mapEndContract.put(objContract.Account__c, objContract.Id);
						setAccId.add(objContract.Account__c);
					}
				}

				for(Contract__c objContract: [Select Id, PreviousContract__c, Type__c,  Contract_Start_Date__c, 
											  Contract_End_Date__c, Account__c  from Contract__c where 
											  Contract_Start_Date__c = TODAY and Status__c ='Signed by Customer' and 
											  Account__c IN: setAccId])
				{
					if(mapEndContract.containskey(objContract.Account__c)){
						mapOldandNewContract.put(mapEndContract.get(objContract.Account__c),objContract.Id);
					}
				}
			}

			system.debug('mapOldandNewContract#########'+mapOldandNewContract);
			
			for(Asset objCorpAsset: [Select Id, Contract__c, Override_Fees_Calculation__c from Asset where RecordtypeId =:corpSchemeRecTypeId and
									  Contract__c IN: mapOldandNewContract.keyset()  and Status != 'Inactive'])
			{
				if(mapOldandNewContract.containskey(objCorpAsset.Contract__c)){
					objCorpAsset.Contract__c = mapOldandNewContract.get(objCorpAsset.Contract__c);
					objCorpAsset.Override_Fees_Calculation__c = false;
				}
				lstUpdateAsset.add(objCorpAsset);
			}
			system.debug('lstUpdateAsset#########'+lstUpdateAsset);

			Integer i = 0, j =0;
			Database.SaveResult[] lstSaveResult = Database.update(lstUpdateAsset, False);
			for(Database.SaveResult sr : lstSaveResult){ 
				if (!sr.isSuccess()) { 
		    		Id assetId = lstUpdateAsset[i].Id;
			        List<String> lstErrorMSG = new List<String>();
	    			for(Database.Error err : sr.getErrors()){
	    				lstErrorMSG.add(err.getMessage());
	    			}
	    			mapError.put(assetId, lstErrorMSG);
			    }
			    i++;
			}
			system.debug('mapError############'+mapError);

		}catch(Exception ex){
			CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Loyalty Batches', 'CorporateScheme_Contract_Renewal_Batch', 
                                     'execute', String.valueOf(''), String.valueOf(''),false,'', ex);
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		system.debug('mapError############'+mapError);

		//GenericUtils.sendEmailonBatchFinish(BC);
		List<Log__c> lstLogException = new List<Log__c>();
		Integer i = 0;
		for(String assetId: mapError.keyset()){
    		lstLogException.add(CreateLogs.insertLogBatchRec( 'Log Exception Logs Rec Type', 'Loyalty Batches', 'CorporateScheme_Contract_Renewal_Batch', 
                                     'execute', assetId, mapError.get(assetId)));
    		i++;
    	}
		insert lstLogException;
		
		// Add batch job calling logic in Finish method
		String schemeQuery = 'Select Id, RecordtypeId, Move_to_Public_Scheme__c from Asset where Scheme_End_Date_f__c = YESTERDAY and Status != \'Inactive\'';
		CorporateScheme_ContractEnd_Batch batchSchemeEnd = new CorporateScheme_ContractEnd_Batch(schemeQuery, mapError.keyset()); 
		database.executebatch(batchSchemeEnd);
	}
	
}