force-app/main/default/objects/Flight_Tracker__c/Flight_Tracker__c.object-meta.xml
<CustomObject>
    <description>QCC: Used to track the flight.</description>
    <label>Flight Tracker</label>
    <nameField>
        <displayFormat>FT{000000}</displayFormat>
        <label>Flight Tracker No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Trackers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Tracker__c/fields/Origin_Date__c.field-meta.xml
<CustomField>
    <fullName>Origin_Date__c</fullName>
    <description>QCC: The origin date of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Origin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QCC_DeleteFlightTrackersBatchProcess.cls
/*------------------------------------------------------------------------------------------------------------------------
    Author:        Purushotham
    Company:       Capgemini
    Description:   Deletes Flight Tracker records that are older than the days defined in Qantas ConfigData custom setting
				   'DaysOlderToDeleteFlightTrackers' and Origin Date less than today's date
    Inputs:
    Test Class:     
    ************************************************************************************************
    History
    ************************************************************************************************
    01-Jul-2018      Purushotham               Initial Design
------------------------------------------------------------------------------------------------------------------------*/
global class QCC_DeleteFlightTrackersBatchProcess implements Database.Batchable<sObject> {
	global Database.QueryLocator start(Database.BatchableContext bc) {
        Integer days = Integer.valueOf(CustomSettingsUtilities.getConfigDataMap('DaysOlderToDeleteFlightTrackers'));
        //System.debug('days===== '+days);
        //System.debug([SELECT Id FROM Flight_Tracker__c WHERE Origin_Date__c < :System.today() AND CreatedDate < :System.today() - days]);
        return Database.getQueryLocator([SELECT Id FROM Flight_Tracker__c WHERE Origin_Date__c < :System.today() AND CreatedDate < :System.today() - days]);
    }
    
    global void execute(Database.BatchableContext bc, List<Flight_Tracker__c> flgTrackers) {
        delete flgTrackers;
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
}