force-app/main/default/objects/Account/recordTypes/Agency_Account.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account</fullName>
    <active>true</active>
    <description>To be used for all Industry Accounts having a contract with Qantas</description>
    <label>Agency Account</label>
</RecordType>

force-app/main/default/objects/Agency_Info__c/Agency_Info__c.object-meta.xml
<CustomObject>
    <label>TMC Info</label>
    <nameField>
        <displayFormat>TMC-{0000}</displayFormat>
        <label>TMC Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMC Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TMC Info</relationshipLabel>
    <relationshipName>Agency_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>For intergration</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/ATPCO_Status__c.field-meta.xml
<CustomField>
    <fullName>ATPCO_Status__c</fullName>
    <label>ATPCO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>This stores the GDS (Global Distribution System) Values</description>
    <inlineHelpText>Global Distribution System</inlineHelpText>
    <label>GDS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AARON GROUP</fullName>
            </value>
            <value>
                <fullName>Aeronology</fullName>
            </value>
            <value>
                <fullName>AirGateway</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Apollo</fullName>
            </value>
            <value>
                <fullName>Axess</fullName>
            </value>
            <value>
                <fullName>ClarityTTS</fullName>
            </value>
            <value>
                <fullName>CTM</fullName>
            </value>
            <value>
                <fullName>Duffel</fullName>
            </value>
            <value>
                <fullName>Expedia</fullName>
            </value>
            <value>
                <fullName>Farelogix</fullName>
                <label>Farelogix (F1)</label>
            </value>
            <value>
                <fullName>Galileo</fullName>
            </value>
            <value>
                <fullName>Infini</fullName>
            </value>
            <value>
                <fullName>Kyte</fullName>
            </value>
            <value>
                <fullName>Mystifly</fullName>
            </value>
            <value>
                <fullName>Navan</fullName>
            </value>
            <value>
                <fullName>QDP Portal</fullName>
            </value>
            <value>
                <fullName>Sabre</fullName>
            </value>
            <value>
                <fullName>Sabre Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Serko</fullName>
            </value>
            <value>
                <fullName>Spotnana</fullName>
            </value>
            <value>
                <fullName>TPConnects</fullName>
            </value>
            <value>
                <fullName>Travelfusion</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Concur</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Cytric</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Locomote</fullName>
            </value>
            <value>
                <fullName>Travelsky</fullName>
            </value>
            <value>
                <fullName>Verteil Technologies</fullName>
            </value>
            <value>
                <fullName>Worldspan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/GDS_Status__c.field-meta.xml
<CustomField>
    <fullName>GDS_Status__c</fullName>
    <description>Introduced as part of Agency Channel Registration, It will be updated by ETL Jobs When its status is New</description>
    <label>GDS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validating</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
            <value>
                <fullName>Pending de-registration</fullName>
                <isActive>false</isActive>
                <label>Pending de-registration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/QDP_Status__c.field-meta.xml
<CustomField>
    <fullName>QDP_Status__c</fullName>
    <label>QDP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Surcharge_Exemption_Status__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Exemption_Status__c</fullName>
    <label>Surcharge Exemption Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/recordTypes/GDS.recordType-meta.xml
<RecordType>
    <fullName>GDS</fullName>
    <active>true</active>
    <description>To be used only for Agency Accounts</description>
    <label>GDS</label>
</RecordType>

force-app/main/default/objects/Asset/fields/GDS__c.field-meta.xml
<CustomField>
    <fullName>GDS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GDS</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <errorMessage>GDS should be Active and Channel Enabled or Farelogix Enabled</errorMessage>
        <filterItems>
            <field>GDS_Reference__c.Channel_Enabled__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>GDS_Reference__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>GDS_Reference__c.FareLogix_Indicator__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Add only Channel Enabled GDS OR Farelogix Enabled GDS</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GDS_Reference__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/GDS_Name__c.field-meta.xml
<CustomField>
    <fullName>GDS_Name__c</fullName>
    <formula>GDS__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GDS Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Agency_Channel.recordType-meta.xml
<RecordType>
    <fullName>Agency_Channel</fullName>
    <active>true</active>
    <description>This is being used for Channel Registration.</description>
    <label>Agency Channel</label>
</RecordType>

force-app/main/default/classes/QC_AssetderegistrationBatch.cls
/**********************************************************************************************************************************

Created Date    : 18/10/19 (DD/MM/YYYY)
Added By        : Vinothkumar Balasubramanian
Description     : Channel Deregistration : Batch job - Update Asset Status and Active flag in Asset
JIRA            : TS-4816
Version         : V1.0 - 18/10/19 - Initial version

Modified Date   : 31/10/19 (DD/MM/YYYY)
Modified By     : Vinothkumar Balasubramanian
JIRA            : CRM-4015
Version         : V2.0 - Include GDS Status "Service"

**********************************************************************************************************************************/


global class QC_AssetderegistrationBatch implements Database.Batchable<sObject> 
{
    
    String tmcRTId = Schema.SObjectType.Agency_Info__c.getRecordTypeInfosByDeveloperName().get('GDS').getRecordTypeId();
    String accAgencyRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agency_Account').getRecordTypeId();
    String assetRTId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Agency_Channel').getRecordTypeId(); 
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([SELECT Id,AccountId,GDS_Name__c, Status, Active__c, GDS__c FROM Asset where RecordTypeId =: assetRTId
                                         AND Status = 'Pending deregistration' AND AccountId != null AND GDS__c != null]);
    }
    
    global void execute(Database.BatchableContext ctx, List<Asset> assetInfo )
    {
        List<Asset> assetList = new list<Asset>();
        Set<Id> accIds = new Set<Id>();
        Set<Id>tmcderegAccIds = new Set<Id>();
        Set<String>tmcderegAccGDScombo = new Set<String>();
        Set<String>tmcAccGDScombo = new Set<String>();
        Set<Id>tmcderegIds = new Set<Id>();
        Set<Id>tmcAccountId = new Set<Id>();
        Set<String> assetGDSNames = new Set<String>();
        
        for(Asset eachAst : assetInfo){
            accIds.add(eachAst.AccountId);
            assetGDSNames.add(eachAst.GDS_Name__c);
            System.debug('Asset AccountIds:' +accIds);
            System.debug('Asset GDS Names:' +assetGDSNames);
        }
        
        if(!accIds.isEmpty() && !assetGDSNames.isEmpty()){
            for (Agency_Info__c tmcInfo : [SELECT Id, Account__c, Code__c, GDS_Status__c, ATPCO_Status__c, Surcharge_Exemption_Status__c, QDP_Status__c FROM Agency_Info__c WHERE Account__c IN: accIds AND Code__c IN: assetGDSNames AND RecordTypeId =: tmcRTId 
                                           AND((GDS_Status__c = 'Deregistered' AND ATPCO_Status__c = '' AND Surcharge_Exemption_Status__c = '' AND QDP_Status__c = '') OR
                                               (GDS_Status__c = 'Deregistered' AND ATPCO_Status__c = 'Deregistered' AND Surcharge_Exemption_Status__c = 'Deregistered' AND QDP_Status__c = 'Deregistered') OR
                                               (GDS_Status__c = 'Rejected' AND ATPCO_Status__c = '' AND Surcharge_Exemption_Status__c = '' AND QDP_Status__c = '') OR
                                               (GDS_Status__c = 'Inactive' AND ATPCO_Status__c = 'Inactive' AND Surcharge_Exemption_Status__c = 'Inactive' AND QDP_Status__c = 'Inactive') OR
                                               (GDS_Status__c = 'Inactive' AND ATPCO_Status__c = '' AND Surcharge_Exemption_Status__c = '' AND QDP_Status__c = '') OR
                         //Changes added by Vinoth for CRM-4015
                         (GDS_Status__c = 'Service' AND ATPCO_Status__c = '' AND Surcharge_Exemption_Status__c = '' AND QDP_Status__c = ''))]){
                          //Changes ends for CRM-4015
                                                   
                                                   if(tmcInfo != NULL){
                                                       tmcderegAccIds.add(tmcInfo.Account__c);
                                                       tmcderegIds.add(tmcInfo.Id);
                                                       tmcderegAccGDScombo.add(tmcInfo.Account__c+'_'+tmcInfo.Code__c);
                                                       
                                                       System.debug('Dereg Account IDS:' +tmcderegAccIds);
                                                       System.debug('TMC Info' +tmcInfo);
                                                   }
                                               }
        }
        
        if(!tmcderegAccIds.isEmpty() && !assetGDSNames.isEmpty()){
            for (Agency_Info__c tmcInfo : [SELECT Id, Account__c, Code__c, GDS_Status__c, ATPCO_Status__c, Surcharge_Exemption_Status__c, QDP_Status__c  FROM Agency_Info__c WHERE Account__c IN: tmcderegAccIds AND Code__c IN: assetGDSNames AND RecordTypeId =: tmcRTId 
                                           AND Id NOT IN:tmcderegIds]){
                                               
                                               if(tmcInfo != NULL){
                                                   tmcAccGDScombo.add(tmcInfo.Account__c+'_'+tmcInfo.Code__c);
                                                   System.debug('TMC Info for Reg Accids' +tmcInfo);
                                               }
                                           }
        }
        
        
        if(tmcderegAccGDScombo != NULL && tmcAccGDScombo != NULL){
            for (String tmcAccGDS : tmcAccGDScombo){
                if(tmcderegAccGDScombo.contains(tmcAccGDS)) tmcderegAccGDScombo.remove(tmcAccGDS);
                System.debug('Dereg final Account IDS:' +tmcderegAccIds);
                
            }
        }
        
        for(String tmcAccountGDS : tmcderegAccGDScombo){
            String tmcAccount = tmcAccountGDS.substringBefore('_');
            System.debug('TMC Account:' +tmcAccount);
            tmcAccountId.add(tmcAccount);
            System.debug('TMC Account Id:' +tmcAccountId);
        }
        
        if(!tmcAccountId.isEmpty()){
            
            for(Asset eachAsset : [SELECT Id,AccountId,GDS_Name__c, Status, Active__c FROM Asset where AccountId IN: tmcAccountId and RecordTypeId =: assetRTId
                                   AND GDS_Name__c IN: assetGDSNames and Status = 'Pending deregistration']){
                                       
                                       if(eachAsset != null){
                                           eachAsset.Status = 'Deregistered';
                                           eachAsset.Active__c = FALSE;
                                           assetList.add(eachAsset);
                                           System.debug('Asset List Update' +assetList);
                                       }
                                   }
        }
        
        Database.SaveResult[] srListUpdate = Database.update(assetList, false);
    }
    
    global void finish(Database.BatchableContext ctx){
        
    }
}