force-app/main/default/objects/Account/recordTypes/Agency_Account.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account</fullName>
    <active>true</active>
    <description>To be used for all Industry Accounts having a contract with Qantas</description>
    <label>Agency Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Charter_Account.recordType-meta.xml
<RecordType>
    <fullName>Charter_Account</fullName>
    <active>true</active>
    <description>To be used for all Charter or Charter Broker Accounts</description>
    <label>Charter Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer_Account.recordType-meta.xml
<RecordType>
    <fullName>Customer_Account</fullName>
    <active>true</active>
    <description>To be used for all non-Agency accounts having a contract with Qantas - this covers Corporate &amp; Government, University Consortiums, SMEs &amp; Multi-national accounts</description>
    <label>Customer Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Freight_Account.recordType-meta.xml
<RecordType>
    <fullName>Freight_Account</fullName>
    <active>true</active>
    <description>To be used for Freight Accounts. Accounts owned by Qantas Freight.</description>
    <label>Freight Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Global_Account.recordType-meta.xml
<RecordType>
    <fullName>Global_Account</fullName>
    <active>true</active>
    <description>Shell account for the local POS accounts.</description>
    <label>Global Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Other_Account.recordType-meta.xml
<RecordType>
    <fullName>Other_Account</fullName>
    <active>true</active>
    <description>To be used for non-customer accounts like Suppliers, Sponsors etc.</description>
    <label>Other Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Prospect_Account.recordType-meta.xml
<RecordType>
    <fullName>Prospect_Account</fullName>
    <active>true</active>
    <description>To be used for prospect accounts - this covers Aquire/Amex accounts and any other prospect accounts that are manually captured</description>
    <label>Prospect Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Regional_Account.recordType-meta.xml
<RecordType>
    <fullName>Regional_Account</fullName>
    <active>true</active>
    <description>To be used for monitoring the performance of regional ports</description>
    <label>Regional Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>QCC: Created to show/store Issue Category.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Accommodation/Reimbursement of Expenses</fullName>
            </value>
            <value>
                <fullName>Account Queries</fullName>
            </value>
            <value>
                <fullName>Advertising</fullName>
            </value>
            <value>
                <fullName>Aircraft Condition</fullName>
            </value>
            <value>
                <fullName>Aircraft Schedule Change/Notification</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Airport Security</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Announcements</fullName>
            </value>
            <value>
                <fullName>AQIRE</fullName>
            </value>
            <value>
                <fullName>ARD Web</fullName>
            </value>
            <value>
                <fullName>Audits</fullName>
            </value>
            <value>
                <fullName>Award Bookings</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>BART Document</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Blue Prism</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Bounce Back</fullName>
            </value>
            <value>
                <fullName>Cabin Baggage</fullName>
            </value>
            <value>
                <fullName>Call outs</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation Fees</fullName>
            </value>
            <value>
                <fullName>Carbon Offset</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Charter Flights</fullName>
            </value>
            <value>
                <fullName>Chauffeur Drive</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Freight_Claims.recordType-meta.xml
<RecordType>
    <fullName>Freight_Claims</fullName>
    <active>true</active>
    <businessProcess>Freight Case</businessProcess>
    <description>Freight – request information for a claim</description>
    <label>Freight Claims</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Freight_Feedback.recordType-meta.xml
<RecordType>
    <fullName>Freight_Feedback</fullName>
    <active>true</active>
    <businessProcess>Freight Case</businessProcess>
    <description>Freight – raise a complaint/compliment or general feedback</description>
    <label>Freight Feedback</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Freight_Query.recordType-meta.xml
<RecordType>
    <fullName>Freight_Query</fullName>
    <active>true</active>
    <businessProcess>Freight Case</businessProcess>
    <description>Freight – general query request</description>
    <label>Freight Query</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Freight_Shipment.recordType-meta.xml
<RecordType>
    <fullName>Freight_Shipment</fullName>
    <active>true</active>
    <businessProcess>Freight Case</businessProcess>
    <description>Freight – request action on an existing shipment</description>
    <label>Freight Shipment</label>
</RecordType>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/Freight_RecordTypeSeggregation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting designed for Segregation of Trigger Logic based on Record types.</description>
    <label>Freight_RecordTypeSeggregation</label>
</CustomObject>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>It will be used to categorized recordtype as Sales Passenger or Freight.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Category</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ObjectType</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <description>It will contain 18 digit Id of RecordType.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RecordTypeId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Quote or Contract type</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Airfares</fullName>
                <default>true</default>
                <label>Corporate Airfares</label>
            </value>
            <value>
                <fullName>Qantas Business Savings</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>FIFO Scheduled</fullName>
            </value>
            <value>
                <fullName>Spot Rate</fullName>
            </value>
            <value>
                <fullName>Preferred Rate</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Market Rate</fullName>
            </value>
            <value>
                <fullName>DPP Onboarding</fullName>
            </value>
            <value>
                <fullName>RB - Limited Availability Lanes</fullName>
            </value>
            <value>
                <fullName>RB - Special Lane Pricing</fullName>
            </value>
            <value>
                <fullName>RB - New Accounts Tier Assignment</fullName>
            </value>
            <value>
                <fullName>RB - Change in Tier Assignment</fullName>
            </value>
            <value>
                <fullName>RB - Spot Rates</fullName>
            </value>
            <value>
                <fullName>RB - Partner Rates</fullName>
            </value>
            <value>
                <fullName>Freighter</fullName>
            </value>
            <value>
                <fullName>Freighter - Spot Rates</fullName>
            </value>
            <value>
                <fullName>Freighter - SLP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Business_and_Government.recordType-meta.xml
<RecordType>
    <fullName>Business_and_Government</fullName>
    <active>true</active>
    <businessProcess>Qantas Sales Process</businessProcess>
    <description>To be used to capture all opportunities for Business and Government</description>
    <label>Business and Government</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Freight.recordType-meta.xml
<RecordType>
    <fullName>Freight</fullName>
    <active>true</active>
    <businessProcess>Freight Sales</businessProcess>
    <description>To be used to capture all opportunities for Qantas Freight</description>
    <label>Freight</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Global_opportunity.recordType-meta.xml
<RecordType>
    <fullName>Global_opportunity</fullName>
    <active>true</active>
    <businessProcess>Qantas Sales Process</businessProcess>
    <description>A holistic view of all the opportunities under multiple Local POS tagged to a Multinational Deal</description>
    <label>Global opportunity</label>
</RecordType>

force-app/main/default/classes/Freight_TriggerRecordTypeUtility.cls
/*-----------------------------------------------------------------------------------------------------------------------------
Author:        Jayaraman Jayaraj
Company:       TCS
Description:   This is utility class to seggregate the records based on the record types.
Test Class:    Test_TriggerRecordTypeUtility
*********************************************************************************************************************************
*********************************************************************************************************************************
History
Abhijeet P          Added Method for creation for Custom Setting data, for Test Class utility.        
********************************************************************************************************************************/

Public class Freight_TriggerRecordTypeUtility{
    
        
    /*--------------------------------------------------------------------------------------      
    Method Name:        returnAccountTriggerMap
    Description:        Method to return Trigger map, based on the category of Account data.
    Parameter:          Account Map, String (Category as in Sales/Freight), String(Object type)
    --------------------------------------------------------------------------------------*/    
    
    public  map<Id, Account> returnAccountTriggerMap(map<Id, Account> triggerMap, String category, String objectType){
        
        // Map to return in the form of newMap or oldMap
        map<Id,Account> returnMap = new map<Id,Account>();
        
        // Map to hold Key as RecordTypeid and Value as Category (Sales or Freight)
        map<String, String> mapRecordTypeVsCategory = returnRecordTypeSettingMap(category, objectType);
                
        // Populating Account New or Old Map based Category (Sales or Freight).
        if(triggerMap != null){
            for(Account eachAccount : triggerMap.values()){
                
                // Validating the recordtype for each Category and Object
                if(mapRecordTypeVsCategory.containsKey(eachAccount.RecordTypeId)){
                    returnMap.put(eachAccount.Id,eachAccount);
                }
            }   
        }
        return returnMap;
    }
    
    
    /*--------------------------------------------------------------------------------------      
    Method Name:        returnRecordTypeSettingMap
    Description:        Method to record type setting data Based on Category and Object
    Parameter:          Strings, in the form of Category and Object
    --------------------------------------------------------------------------------------*/ 
    
    public map<String, String> returnRecordTypeSettingMap(string category, string objectType){
        
        // Getting all the recordtype values from custom setting
        list<Freight_RecordTypeSeggregation__c> recordTypeSettings = Freight_RecordTypeSeggregation__c.getall().values();
        
        // map to be returned based for recordTypeId and category
        map<String, String> returnMap = new map<String, String>();
        
        // Considering relevant recordTypes for Account and relevant category
        for(Freight_RecordTypeSeggregation__c eachSetting : recordTypeSettings){
            if(eachSetting.Category__c == category && eachSetting.ObjectType__c == objectType){
                returnMap.put(eachSetting.RecordTypeId__c,eachSetting.Category__c);   
            }
        }
        return returnMap;        
    }
      
    /*--------------------------------------------------------------------------------------      
    Method Name:        createAccTrigTestCustomSetting
    Description:        Method to create Custom Setting data for test classes
    Parameter:          NA
    --------------------------------------------------------------------------------------*/    
    public static List<Freight_RecordTypeSeggregation__c> createAccTrigTestCustomSetting(){
      
        List<Freight_RecordTypeSeggregation__c> listRecordTypeCustomSettingData = new List<Freight_RecordTypeSeggregation__c>();
      
        Freight_RecordTypeSeggregation__c customSettingRecord = new Freight_RecordTypeSeggregation__c();
      
        // Agency Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Agency_Account', Category__c = 'Sales', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);

        // Charter Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Charter_Account', Category__c = 'Sales', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Charter Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);

        // Customer Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Customer_Account', Category__c = 'Sales', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);       
        
        
        // Freight Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Freight_Account', Category__c = 'Freight', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Freight Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        
        // Global Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Global_Account', Category__c = 'Sales', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Global Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        
        /*CRM-2943 Delete 'New Account' Recordtype
        // New Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'New_Account', Category__c = 'Sales', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('New Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);*/
        
        // Other Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Other_Account', Category__c = 'Sales', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Other Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
      
        // Prospect Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Prospect_Account', Category__c = 'Sales', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
      
        // Regional Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Regional_Account', Category__c = 'Sales', ObjectType__c = 'Account',
                                            RecordTypeId__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Regional Account').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        
        // Regional Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Business and Government', Category__c = 'Sales', ObjectType__c = 'Opportunity',
                                            RecordTypeId__c = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Business_and_Government').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        
         // Regional Account Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Global_opportunity', Category__c = 'Sales', ObjectType__c = 'Opportunity',
                                            RecordTypeId__c = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Global opportunity').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        
        // Regional Case Freight claims Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Freight_Claims', Category__c = 'Freight', ObjectType__c = 'Case',
                                            RecordTypeId__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Claims').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        // Regional Case Freight Email to Case Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Freight_Email_to_Case', Category__c = 'Freight', ObjectType__c = 'Case',
                                            RecordTypeId__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Email to Case').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        // Regional Case Freight Feedback Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Freight_Feedback', Category__c = 'Freight', ObjectType__c = 'Case',
                                            RecordTypeId__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Feedback').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        // Regional Case Freight Invoicing Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Freight_Invoicing', Category__c = 'Freight', ObjectType__c = 'Case',
                                            RecordTypeId__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Invoicing').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        // Regional Case Freight Query Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Freight_Query', Category__c = 'Freight', ObjectType__c = 'Case',
                                            RecordTypeId__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Query').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        // Regional Case Freight Shipment Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Freight_Shipment', Category__c = 'Freight', ObjectType__c = 'Case',
                                            RecordTypeId__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Shipment').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        // Regional Case Freight Track & Trace Exceptions Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Freight_Track_Trace_Exceptions', Category__c = 'Freight', ObjectType__c = 'Case',
                                            RecordTypeId__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Track & Trace Exceptions').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        // Regional Case Qantas Freight Custom Setting Record Added.
        customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Qantas_Freight', Category__c = 'Freight', ObjectType__c = 'Case',
                                            RecordTypeId__c = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Qantas Freight').getRecordTypeId());
        listRecordTypeCustomSettingData.add(customSettingRecord);
        
       
      
        return listRecordTypeCustomSettingData; 
    }
    
}