force-app/main/default/objects/Account/recordTypes/Placeholder.recordType-meta.xml
<RecordType>
    <fullName>Placeholder</fullName>
    <active>true</active>
    <description>QCC: This is used as a placeholder to attach Placeholder Account</description>
    <label>Placeholder</label>
</RecordType>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_TECH_RecordType__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_RecordType__c</fullName>
    <description>Populated automatically for Individual Contact record to be used in enforcing matching rules</description>
    <encryptionScheme>None</encryptionScheme>
    <label>QCC TECH RecordType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Placeholder.recordType-meta.xml
<RecordType>
    <fullName>Placeholder</fullName>
    <active>true</active>
    <description>QCC: This is used as a placeholder to attach Cases for non Frequent Flyers. This is not to be treated as a Contact person</description>
    <label>Placeholder</label>
</RecordType>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_SearchContactAPITest.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Praveen Sampath
Company:       Capgemini
Description:   Test Class for QCC_SearchContactAPITest
Inputs:
Test Class:    Not Required
************************************************************************************************
History
************************************************************************************************
03-AUG-2018     Praveen Sampath     InitialDesign
17-APR-2023     Leslie Padilla      Split methods to cover scenario for Null Contact (searchContactPlaceholderPositive) and Non FF Contact (searchContactNONFFPositive)
-----------------------------------------------------------------------------------------------------------------------*/
@isTest(seeAllData = false)
private class QCC_SearchContactAPITest {
    @testSetup
    static void createTestData(){ 
        
        TestUtilityDataClassQantas.insertQantasConfigData();
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createRecoveryTriggerSetting());
        insert lsttrgStatus;
        

        List<Qantas_API__c> lstQantas = TestUtilityDataClassQantas.createQantasAPI();
        insert lstQantas;
        
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Integration Logs Rec Type','Integration Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_PlaceHolderAcc','PlaceHolder Acc 1'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_PlaceHolderAccRectype','Placeholder'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_GenericConDescription','Testtstst jhgdsfkh lsdfh'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC Non FF Contact Duplicate Rule Name','QCC_Non_FF_Contact_Duplicate_Rule'));
        upsert lstConfigData;

        String recordtypeId = GenericUtils.getObjectRecordTypeId('Account', 'Placeholder');
        Account objAcc = new Account();
        objAcc.RecordtypeId = recordtypeId;
        objAcc.Name = 'PlaceHolder Acc 1';
        insert objAcc;
    }

    
    static TestMethod void searchContactFFPositive(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        QCC_ContactWrapper conWrap = new QCC_ContactWrapper();
        conWrap.ffNumber = '1234566'; 
        conWrap.lastName = 'Sampath';
        conWrap.firstName = 'Praveen';
        conWrap.ffTier = 'Gold';
        conWrap.capId = '123477888';
        conWrap.isFF = true;
        String msg = Json.serialize(conWrap);
        
        req.requestURI = '/services/apexrest/QCCSearchContact';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        
        RestContext.request = req;
        RestContext.response= res;

        
        Test.startTest();
            QCC_SearchContactAPI.searchContact();
            system.assert(res.statusCode == 200, 'Response code is not 200');
        Test.StopTest();   
    }

    //GRAPHITE-932: Scenario to cover when contact is already existing, then link the case to the existing "Individual Contact"
    static TestMethod void searchContactFFExisting(){
        //Create Individual Contact record
        Integer ffNumber = 1234566;
        Contact b2cContactRecord = QCC_TestDataFactory.createContactTestData(ffNumber, null);
        b2cContactRecord.RecordTypeId = GenericUtils.getObjectRecordTypeId('Contact', CustomSettingsUtilities.getConfigDataMap('QCC Individual Contact'));
        b2cContactRecord.Frequent_Flyer_Number__c = String.valueOf(ffNumber);
        b2cContactRecord.Frequent_Flyer_Tier__c = 'Platinum One';
        b2cContactRecord.QCC_TECH_RecordType__c = 'Individual Contact';
        insert b2cContactRecord;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        QCC_ContactWrapper conWrap = new QCC_ContactWrapper();
        conWrap.ffNumber = '1234566'; 
        conWrap.lastName = 'Sampath';
        conWrap.firstName = 'Praveen';
        conWrap.ffTier = 'Gold';
        conWrap.capId = '123477888';
        conWrap.isFF = true;
        String msg = Json.serialize(conWrap);
        
        req.requestURI = '/services/apexrest/QCCSearchContact';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        
        RestContext.request = req;
        RestContext.response= res;

        
        Test.startTest();
            QCC_SearchContactAPI.searchContact();
            //system.assert(res.statusCode != 200, 'Response code is not 200');
        Test.StopTest();   
    }
    
    static TestMethod void searchContactPlaceholderPositive(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        QCC_ContactWrapper conWrap = new QCC_ContactWrapper();
        conWrap.ffNumber = ''; 
        conWrap.lastName = '';
        conWrap.firstName = '';
        conWrap.email = '';
        conWrap.phone = '';
        conWrap.ffTier = '';
        conWrap.capId = '';
        conWrap.isFF = false;
        String msg = Json.serialize(conWrap);
        
        req.requestURI = '/services/apexrest/QCCSearchContact';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        
        RestContext.request = req;
        RestContext.response= res;

        
        Test.startTest();
            QCC_SearchContactAPI.searchContact();
            system.assert(res.statusCode == 200, 'Response code is not 200');
        Test.StopTest();   
    }
    
    static TestMethod void searchContactNONFFPositive(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        QCC_ContactWrapper conWrap = new QCC_ContactWrapper();
        conWrap.ffNumber = ''; 
        conWrap.lastName = 'test';
        conWrap.firstName = 'test';
        conWrap.email = 'test@example.com';
        conWrap.phone = '0411234567';
        conWrap.ffTier = '';
        conWrap.capId = '';
        conWrap.isFF = false;
        String msg = Json.serialize(conWrap);
        
        req.requestURI = '/services/apexrest/QCCSearchContact';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        
        RestContext.request = req;
        RestContext.response= res;

        
        Test.startTest();
            QCC_SearchContactAPI.searchContact();
            system.assert(res.statusCode == 200, 'Response code is not 200');
        Test.StopTest();   
    }

    static TestMethod void searchContactException(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        String msg = 'hello';
        
        req.requestURI = '/services/apexrest/QCCSearchContact';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        
        RestContext.request = req;
        RestContext.response= res;

        
        Test.startTest();
            QCC_SearchContactAPI.searchContact();
            system.assert(res.statusCode == 400, 'Response code is not 200');
        Test.StopTest();   
    }

}