force-app/main/default/objects/Account/recordTypes/Placeholder.recordType-meta.xml
<RecordType>
    <fullName>Placeholder</fullName>
    <active>true</active>
    <description>QCC: This is used as a placeholder to attach Placeholder Account</description>
    <label>Placeholder</label>
</RecordType>

force-app/main/default/objects/Case/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Used to capture the new user&apos;s first name.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s first name, for whom the request is being logged.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>To capture the new user&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s last name, for whom the request is being logged.</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Used on CL Renewal Cases to capture the location of the Chairman Lounge member (his/her Home port)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Placeholder.recordType-meta.xml
<RecordType>
    <fullName>Placeholder</fullName>
    <active>true</active>
    <description>QCC: This is used as a placeholder to attach Cases for non Frequent Flyers. This is not to be treated as a Contact person</description>
    <label>Placeholder</label>
</RecordType>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Queue Members location (manila , Sydney , ..)</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manila</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Hobart</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Capetown</fullName>
            </value>
            <value>
                <fullName>Suva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QCC_PossibleRelatedCasesControllerTest.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Purushotham B
Company:       Capgemini
Description:   Test class for QCC_PossibleRelatedCasesController
Inputs:
Test Class:     
************************************************************************************************
History
************************************************************************************************
06-Aug-2018             Purushotham B          Initial Design 
-----------------------------------------------------------------------------------------------------------------------*/
@isTest
public class QCC_PossibleRelatedCasesControllerTest {
	static testMethod void test() {
        Test.startTest();
        String str = QCC_PossibleRelatedCasesController.getColumns('QCC_PossibleRelatedCases');
        Test.stopTest();
        System.assert(str != null, 'No columns defined in "QCC Data Table" custom metadata for QCC_PossibleRelatedCases LC');
        List<QCC_CaseSearchResultController.displayColumn> columns = (List<QCC_CaseSearchResultController.displayColumn>)JSON.deserialize(str, List<QCC_CaseSearchResultController.displayColumn>.Class);
        System.assert(columns.size() != 0);
    }
    
    static testMethod void testSearch() {
        TestUtilityDataClassQantas.insertQantasConfigData();
        Test.startTest();
        List<Case> cases = QCC_PossibleRelatedCasesController.search('User','Sample0','test@sample.com','12345678','');
        Test.stopTest();
        System.assert(cases.size() == 0, 'Found cases');
    }
    
    static testMethod void testSearchWithExistingCases() {
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        insert lsttrgStatus;
        TestUtilityDataClassQantas.insertQantasConfigData();
        Map<String, Profile> profMap = TestUtilityDataClassQantas.getProfileMap();
        User u1 = new User(LastName = 'User1', Alias = 'User', Email = 'sampleuser1@sample.com', 
                           Username = 'sampleuser1username@sample.com', ProfileId = profMap.get('System Administrator').Id,
                           EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_AU',
                           TimeZoneSidKey = 'Australia/Sydney', City='Manila', location__c = 'Manila'
                          );
        
        Id conPlaceHolderRecTypeId = GenericUtils.getObjectRecordTypeId('Contact', 'Placeholder');
        Id accPlaceHolderRecTypeId = GenericUtils.getObjectRecordTypeId('Account', 'Placeholder');
        Account acc = new Account(Name='Null',RecordTypeId=accPlaceHolderRecTypeId);
        insert acc;
        Contact con = new Contact(LastName='Null',RecordTypeId=conPlaceHolderRecTypeId,Frequent_Flyer_Tier__c='Non-Tiered',AccountId=acc.Id);
        insert con;
        System.runAs(u1) {
            String type = 'Insurance Letter';
            String recordType = 'CCC Insurance Letter Case';
            List<Case> caseList = new List<Case>();
            Case cs = TestUtilityDataClassQantas.createCaseWithCodingValues(recordType, type, 'Proof of Boarding or No Show','','','');
            cs.ContactId = con.Id;
            cs.Origin = 'Phone';
            cs.First_Name__c = 'TestFN';
            cs.Last_Name__c = 'TestLN';
            cs.Contact_Email__c = 'test@test.com';
            cs.Contact_Phone__c = '12345678';
            caseList.add(cs);
            
            Case cs2 = TestUtilityDataClassQantas.createCaseWithCodingValues(recordType, type, 'Proof of Boarding or No Show','','','');
            cs2.ContactId = con.Id;
            cs2.Origin = 'Phone';
            cs2.First_Name__c = 'TestFN';
            cs2.Last_Name__c = 'TestLN';
            cs2.Contact_Email__c = 'test@test.com';
            cs2.Contact_Phone__c = '12345678';
            caseList.add(cs2);
            insert caseList;
        
            Test.startTest();
            List<Case> cases = QCC_PossibleRelatedCasesController.search('TestFN','TestLN','test@test.com','12345678',caseList[0].Id);
            Test.stopTest();
                
            System.assert(cases.size() == 1, 'Found more than one case');
        }
    }
}