force-app/main/default/objects/AEQCC_Variance__c/AEQCC_Variance__c.object-meta.xml
<CustomObject>
    <label>AMEX Variance</label>
    <nameField>
        <displayFormat>V-{00000}</displayFormat>
        <label>AEQCC Variance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMEX Variance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Domestic_Other_Carrier_Marketshare__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Domestic_Other_Carrier_Marketshare__c</fullName>
    <formula>IF( LYTD_Total_Dom_Revenue__c != 0,   LYTD_Domestic_Other_Carrier_Revenue__c  / LYTD_Total_Dom_Revenue__c ,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LYTD Domestic Other Carrier Marketshare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Domestic_Other_Carrier_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Domestic_Other_Carrier_Revenue__c</fullName>
    <label>LYTD Domestic Other Carrier Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_Other_Airlines_Dom_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>LY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Domestic_Qantas_Marketshare__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Domestic_Qantas_Marketshare__c</fullName>
    <formula>IF( LYTD_Total_Dom_Revenue__c != 0,  LYTD_Domestic_Qantas_Revenue__c / LYTD_Total_Dom_Revenue__c,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LYTD Domestic Qantas Marketshare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Domestic_Qantas_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Domestic_Qantas_Revenue__c</fullName>
    <label>LYTD Domestic Qantas Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_QF_Dom_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>LY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_International_Other_Carrier_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_International_Other_Carrier_Revenue__c</fullName>
    <label>LYTD International Other Carrier Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_Other_Airlines_Intl_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>LY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_International_Qantas_Marketshare__c.field-meta.xml
<CustomField>
    <fullName>LYTD_International_Qantas_Marketshare__c</fullName>
    <formula>IF( LYTD_Total_Intl_Revenue__c != 0,  LYTD_International_Qantas_Revenue__c  / LYTD_Total_Intl_Revenue__c,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LYTD International Qantas Marketshare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_International_Qantas_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_International_Qantas_Revenue__c</fullName>
    <label>LYTD International Qantas Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_QF_Intl_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>LY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Total_Air_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Total_Air_Revenue__c</fullName>
    <formula>LYTD_Total_Qantas_Revenue__c  +  LYTD_Total_Other_Carrier_Revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LYTD Total Air Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Total_Dom_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Total_Dom_Revenue__c</fullName>
    <formula>LYTD_Domestic_Other_Carrier_Revenue__c  +  LYTD_Domestic_Qantas_Revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LYTD Total Dom Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Total_Intl_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Total_Intl_Revenue__c</fullName>
    <formula>LYTD_International_Other_Carrier_Revenue__c  +  LYTD_International_Qantas_Revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LYTD Total Intl Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Total_Other_Carrier_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Total_Other_Carrier_Revenue__c</fullName>
    <label>LYTD Total Other Carrier Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_Other_Airlines_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>LY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/LYTD_Total_Qantas_Revenue__c.field-meta.xml
<CustomField>
    <fullName>LYTD_Total_Qantas_Revenue__c</fullName>
    <label>LYTD Total Qantas Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_Qantas_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>LY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/Product_Link__c.field-meta.xml
<CustomField>
    <fullName>Product_Link__c</fullName>
    <label>Product Link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Registration__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>AEQCC Registration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Registration__c</referenceTo>
    <relationshipLabel>AMEX Variance</relationshipLabel>
    <relationshipName>AEQCC_Variance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Domestic_Other_Carrier_Marketshare__c.field-meta.xml
<CustomField>
    <fullName>YTD_Domestic_Other_Carrier_Marketshare__c</fullName>
    <formula>IF(YTD_Total_Dom_Revenue__c != 0,  YTD_Domestic_Other_Carrier_Revenue__c  / YTD_Total_Dom_Revenue__c ,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>YTD Domestic Other Carrier Marketshare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Domestic_Other_Carrier_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_Domestic_Other_Carrier_Revenue__c</fullName>
    <label>YTD Domestic Other Carrier Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_Other_Airlines_Dom_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>TY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Domestic_Qantas_Marketshare__c.field-meta.xml
<CustomField>
    <fullName>YTD_Domestic_Qantas_Marketshare__c</fullName>
    <formula>IF(YTD_Total_Dom_Revenue__c != 0, YTD_Domestic_Qantas_Revenue__c  /  YTD_Total_Dom_Revenue__c ,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>YTD Domestic Qantas Marketshare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Domestic_Qantas_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_Domestic_Qantas_Revenue__c</fullName>
    <label>YTD Domestic Qantas Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_QF_Dom_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>TY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Int_Other_Carrier_Marketshare__c.field-meta.xml
<CustomField>
    <fullName>YTD_Int_Other_Carrier_Marketshare__c</fullName>
    <formula>IF( YTD_Total_Intl_Revenue__c != 0,  YTD_International_Other_Carrier_Revenue__c / YTD_Total_Intl_Revenue__c ,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>YTD Intl Other Carrier Marketshare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_International_Other_Carrier_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_International_Other_Carrier_Revenue__c</fullName>
    <label>YTD International Other Carrier Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_Other_Airlines_Intl_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>TY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_International_Qantas_Marketshare__c.field-meta.xml
<CustomField>
    <fullName>YTD_International_Qantas_Marketshare__c</fullName>
    <formula>IF( YTD_Total_Intl_Revenue__c != 0,  YTD_International_Qantas_Revenue__c / YTD_Total_Intl_Revenue__c,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>YTD International Qantas Marketshare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_International_Qantas_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_International_Qantas_Revenue__c</fullName>
    <label>YTD International Qantas Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_QF_Intl_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>TY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Total_Air_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_Total_Air_Revenue__c</fullName>
    <formula>YTD_Total_Other_Carrier_Revenue__c +  YTD_Total_Qantas_Revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>YTD Total Air Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Total_Dom_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_Total_Dom_Revenue__c</fullName>
    <formula>YTD_Domestic_Other_Carrier_Revenue__c  +  YTD_Domestic_Qantas_Revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>YTD Total Dom Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Total_Intl_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_Total_Intl_Revenue__c</fullName>
    <formula>YTD_International_Other_Carrier_Revenue__c  +  YTD_International_Qantas_Revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>YTD Total Intl Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Total_Other_Carrier_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_Total_Other_Carrier_Revenue__c</fullName>
    <label>YTD Total Other Carrier Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_Other_Airlines_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>TY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AEQCC_Variance__c/fields/YTD_Total_Qantas_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_Total_Qantas_Revenue__c</fullName>
    <label>YTD Total Qantas Revenue</label>
    <summarizedField>AEQCC_Performance__c.YTD_Qantas_CV__c</summarizedField>
    <summaryFilterItems>
        <field>AEQCC_Performance__c.Rollup__c</field>
        <operation>equals</operation>
        <value>TY</value>
    </summaryFilterItems>
    <summaryForeignKey>AEQCC_Performance__c.Variance_Link__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/prodregextensions.cls
public with sharing class prodregextensions {
//public List<AEQCC_Variance__c> aeqccvariance  {get; set;} 
    Public id prodregid;
    public prodregextensions (ApexPages.StandardController stdController)
    {
        prodregid = stdcontroller.getRecord().id;
    }
    public List<AEQCC_Variance__c> getrelatedCustObjRecs() {
   List<AEQCC_Variance__c> conList = New List<AEQCC_Variance__c>();
       for(Product_Registration__c pr:[select id,name,(select Name, CurrencyIsoCode, Product_Link__c, YTD_Total_Qantas_Revenue__c, LYTD_Total_Qantas_Revenue__c, 
                                                       YTD_Domestic_Qantas_Revenue__c, LYTD_Domestic_Qantas_Revenue__c, YTD_International_Qantas_Revenue__c, 
                                                       LYTD_International_Qantas_Revenue__c, YTD_Domestic_Other_Carrier_Revenue__c, LYTD_Domestic_Other_Carrier_Revenue__c, 
                                                       YTD_International_Other_Carrier_Revenue__c, LYTD_International_Other_Carrier_Revenue__c, YTD_Total_Other_Carrier_Revenue__c, 
                                                       LYTD_Total_Other_Carrier_Revenue__c, YTD_Total_Air_Revenue__c, LYTD_Total_Air_Revenue__c, YTD_Total_Dom_Revenue__c, 
                                                       LYTD_Total_Dom_Revenue__c, YTD_Total_Intl_Revenue__c, LYTD_Total_Intl_Revenue__c, YTD_Domestic_Qantas_Marketshare__c, 
                                                       LYTD_Domestic_Other_Carrier_Marketshare__c, LYTD_Domestic_Qantas_Marketshare__c, YTD_Domestic_Other_Carrier_Marketshare__c, 
                                                       YTD_International_Qantas_Marketshare__c, LYTD_International_Qantas_Marketshare__c, YTD_Int_Other_Carrier_Marketshare__c, 
                                                       LYTD_International_Other_Carrier_Markets__c, YoY_Total_Qantas_Revenue__c, YoY_Domestic_Qantas_Revenue__c, 
                                                       YoY_Domestic_Qantas_Marketshare__c, YoY_Intl_Qantas_Revenue__c, YoY_Intl_Qantas_MarketShare__c, 
                                                       YoY_Total_Other_Carrier_Revenue__c, YoY_Dom_Other_Carrier_Revenue__c, YoY_Dom_Other_Carrier_Marketshare__c, 
                                                       YoY_Intl_Other_Carrier_Revenue__c, YoY_Intl_Other_Carrier_Marketshare__c, YoY_Total_Air_Reveue__c, YoY_Dom_QF_MS_Indicator__c, 
                                                       YoY_Dom_QF_Revenue_Indicator__c, YoY_Intl_QF_MS_Indicator__c, YoY_Intl_QF_Revenue_Indicator__c, YoY_Total_QF_Revenue_Indicator__c, 
                                                       YoY_Total_Air_Revenue_Indicator__c, YoY_Dom_Other_Carrier_MS_Indicator__c, YoY_Dom_Other_Carrier_Revenue_Indicator__c, 
                                                       YoY_Intl_Other_Carrier_MS_Indicator__c, YoY_Intl_Other_Carrier_Revenue_Indicator__c, 
                                                       YoY_Total_Other_Carrier_Revenue_Indicato__c,Reporting_Period__c
                                                       from AEQCC_Variance__r) from Product_Registration__c where id=:prodregid]){
           for(AEQCC_Variance__c aev:pr.AEQCC_Variance__r)
               conList.add(aev); 
       }
       return conList;
    }
}