force-app/main/default/objects/Agency_Info__c/Agency_Info__c.object-meta.xml
<CustomObject>
    <label>TMC Info</label>
    <nameField>
        <displayFormat>TMC-{0000}</displayFormat>
        <label>TMC Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMC Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TMC Info</relationshipLabel>
    <relationshipName>Agency_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>For intergration</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/ATPCO_Status__c.field-meta.xml
<CustomField>
    <fullName>ATPCO_Status__c</fullName>
    <label>ATPCO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Channel_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Channel_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Channel_RecG_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Channel_RecG_Identifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel RecG Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Channel_YR_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Channel_YR_Identifier__c</fullName>
    <label>Channel YR Identifier</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>This stores the GDS (Global Distribution System) Values</description>
    <inlineHelpText>Global Distribution System</inlineHelpText>
    <label>GDS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AARON GROUP</fullName>
            </value>
            <value>
                <fullName>Aeronology</fullName>
            </value>
            <value>
                <fullName>AirGateway</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Apollo</fullName>
            </value>
            <value>
                <fullName>Axess</fullName>
            </value>
            <value>
                <fullName>ClarityTTS</fullName>
            </value>
            <value>
                <fullName>CTM</fullName>
            </value>
            <value>
                <fullName>Duffel</fullName>
            </value>
            <value>
                <fullName>Expedia</fullName>
            </value>
            <value>
                <fullName>Farelogix</fullName>
                <label>Farelogix (F1)</label>
            </value>
            <value>
                <fullName>Galileo</fullName>
            </value>
            <value>
                <fullName>Infini</fullName>
            </value>
            <value>
                <fullName>Kyte</fullName>
            </value>
            <value>
                <fullName>Mystifly</fullName>
            </value>
            <value>
                <fullName>Navan</fullName>
            </value>
            <value>
                <fullName>QDP Portal</fullName>
            </value>
            <value>
                <fullName>Sabre</fullName>
            </value>
            <value>
                <fullName>Sabre Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Serko</fullName>
            </value>
            <value>
                <fullName>Spotnana</fullName>
            </value>
            <value>
                <fullName>TPConnects</fullName>
            </value>
            <value>
                <fullName>Travelfusion</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Concur</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Cytric</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Locomote</fullName>
            </value>
            <value>
                <fullName>Travelsky</fullName>
            </value>
            <value>
                <fullName>Verteil Technologies</fullName>
            </value>
            <value>
                <fullName>Worldspan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/GDS_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>GDS_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GDS Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/GDS_Status__c.field-meta.xml
<CustomField>
    <fullName>GDS_Status__c</fullName>
    <description>Introduced as part of Agency Channel Registration, It will be updated by ETL Jobs When its status is New</description>
    <label>GDS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validating</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
            <value>
                <fullName>Pending de-registration</fullName>
                <isActive>false</isActive>
                <label>Pending de-registration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Last_Inactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Inactive_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Inactive Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/PCC__c.field-meta.xml
<CustomField>
    <fullName>PCC__c</fullName>
    <description>This is to store the PCC (Pseudo City Code)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Pseudo City Code</inlineHelpText>
    <label>PCC</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/QDP_Status__c.field-meta.xml
<CustomField>
    <fullName>QDP_Status__c</fullName>
    <label>QDP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Surcharge_Exemption_Status__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Exemption_Status__c</fullName>
    <label>Surcharge Exemption Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/recordTypes/GDS.recordType-meta.xml
<RecordType>
    <fullName>GDS</fullName>
    <active>true</active>
    <description>To be used only for Agency Accounts</description>
    <label>GDS</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Channel_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/GDS__c.field-meta.xml
<CustomField>
    <fullName>GDS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GDS</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <errorMessage>GDS should be Active and Channel Enabled or Farelogix Enabled</errorMessage>
        <filterItems>
            <field>GDS_Reference__c.Channel_Enabled__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>GDS_Reference__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>GDS_Reference__c.FareLogix_Indicator__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Add only Channel Enabled GDS OR Farelogix Enabled GDS</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GDS_Reference__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/GDS_Name__c.field-meta.xml
<CustomField>
    <fullName>GDS_Name__c</fullName>
    <formula>GDS__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GDS Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Agency_Channel.recordType-meta.xml
<RecordType>
    <fullName>Agency_Channel</fullName>
    <active>true</active>
    <description>This is being used for Channel Registration.</description>
    <label>Agency Channel</label>
</RecordType>

force-app/main/default/objects/GDS_Reference__c/GDS_Reference__c.object-meta.xml
<CustomObject>
    <label>GDS Reference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GDS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDS References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GDS_Reference__c/fields/Channel_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GDS_Reference__c/fields/PCC_Max_Length__c.field-meta.xml
<CustomField>
    <fullName>PCC_Max_Length__c</fullName>
    <label>PCC Max Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GDS_Reference__c/fields/PCC_Min_Length__c.field-meta.xml
<CustomField>
    <fullName>PCC_Min_Length__c</fullName>
    <label>PCC Min Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QAC_TMCHandler.cls
/* Created By :TCS
* Purpose : TS-4468-To include business logic for TMC Triggers on Channel functionality
* Description : To update TMC Info records when an asset is existing for IATA
* References : TMCTrigger
* Test Class : QAC_TMCHandler_Test

Modified Date   : 25/07/19 (DD/MM/YYYY)
Modified By     : Vinothkumar Balasubramanian
JIRA            : CRM-3816, CRM-3845
Version         : V2.0 - GDS PCC Length should be matched based on PCC Min Length and PCC Max Length on GDS Reference Object
TMC Duplicate Rule on PCC, GDS and Account ID

Modified Date   : 07/08/19 (DD/MM/YYYY)
Modified By     : Vinothkumar Balasubramanian
JIRA            : CRM-3871
Version         : V3.0 - Changes to avoid the CPU limit

Modified Date   : 18/09/19 (DD/MM/YYYY)
Modified By     : Vinothkumar Balasubramanian
JIRA            : CRM-3908
Version         : V4.0 - Changes to update the GDS Status based on PCC GDS Combination
*/
public with sharing class QAC_TMCHandler 
{
    //PCC Validation based on GDS
    // to update GDS status field on TMC Info records
    public static void QCH_updateTMC(list<Agency_Info__c> newTMCs, map<Id,Agency_Info__c> oldTMCs)
    {
        String assetRTId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Agency_Channel').getRecordTypeId();
        String tmcRTId = Schema.SObjectType.Agency_Info__c.getRecordTypeInfosByDeveloperName().get('GDS').getRecordTypeId();
        
        String[] assetStatus = new String[]{'New','Validating','Accepted'};
            Map<Id,List<String>> existingAstGDSmap = new Map<Id,List<String>>();
        Map<String,GDS_Reference__c> gdsMap = new map<String,GDS_Reference__c>();
        Set<Id> accIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        Set<String> gdsValues = new Set<String>();
        Set<String> pccValues = new Set<String>();
        list<Agency_Info__c> existingTMCInfo;
        Set<String> accGDSPCCCombo = new Set<String>();
        Set<String> otherAccGDSPCCCombo = new Set<String>();
        Set<String> incomingTMCInfo = new Set<String>();
        
        
        for(Agency_Info__c eachAg : newTMCs)
        {
            if(eachAg != null && eachAg.RecordTypeId == tmcRTId)
            {
                if(oldTMCs == null ||(oldTMCs != null && eachAg.Active__c != oldTMCs.get(eachAg.Id).Active__c))
                    accIds.add(eachAg.Account__c); 
                
                if(eachAg.PCC__c != null && eachAg.Code__c != null && eachAg.Account__c != null && (oldTMCs == null || (oldTMCs != null && ((eachAg.Code__c != oldTMCs.get(eachAg.Id).Code__c)||(eachAg.PCC__C != oldTMCs.get(eachAg.Id).PCC__C) || (eachAg.Account__c != oldTMCs.get(eachAg.Id).Account__c)))))
                {
                    gdsValues.add(eachAg.Code__c);
                    pccValues.add(eachAg.PCC__c);
                    accountIds.add(eachAg.Account__c);
                }
                
                // Added as part of CRM-3816 to Convert PCC to UpperCase
                if(eachAg.PCC__c!=null)
                    eachAg.pcc__c =eachAg.PCC__c.toUpperCase();
            }    
        }
        system.debug('incoming TMC account Ids***'+accIds);
        
        if(!gdsValues.isEmpty())
        {
            for(GDS_Reference__c gdsReference:[select Id,Name,PCC_Min_Length__c,PCC_Max_Length__c from GDS_Reference__c where PCC_Min_Length__c!=null AND PCC_Max_Length__c !=null AND Name IN:gdsValues])
            {
                if(gdsReference != null)
                    gdsMap.put(gdsReference.Name,gdsReference);
            }
            if(!accountIds.isEmpty() && !pccValues.isEmpty())
            {
                existingTMCInfo = [SELECT Id, Account__c, PCC__c, Code__c FROM Agency_Info__c WHERE Account__c IN: accountIds AND PCC__c IN: pccValues AND Code__c IN: gdsValues AND RecordTypeId =: tmcRTId];
                if(existingTMCInfo.size()>0){
                    for(Agency_Info__c oldTMC : existingTMCInfo){
                        accGDSPCCCombo.add(oldTMC.Account__c+'-'+oldTMC.PCC__c+'-'+oldTMC.Code__c);
                        system.debug('Existing Account GDS PCC Combo***'+accGDSPCCCombo);
                    }
                }
            }
        }
        
        // query for existing assets 
        if(!accIds.isEmpty())
        {
            for(Asset eachAsset : [SELECT Id,Status,AccountId,GDS__c,GDS_Name__c FROM Asset 
                                   WHERE AccountId IN: accIds AND Active__c = True
                                   AND RecordTypeId =: assetRTId AND Status IN: assetStatus])
            {
                if(eachAsset != null){
                    if(existingAstGDSmap.containsKey(eachAsset.AccountId)){
                        existingAstGDSmap.get(eachAsset.AccountId).add(eachAsset.GDS_Name__c);
                    }
                    else{
                        existingAstGDSmap.put(eachAsset.AccountId, new List<String>{eachAsset.GDS_Name__c});
                    }                
                }    
            }
            system.debug('existing Assets***'+existingAstGDSmap);
        }
        for(Agency_Info__c eachTMC : newTMCs)
        {
            if(eachTMC != null & eachTMC.PCC__C != null && eachTMC.RecordTypeId == tmcRTId && (oldTMCs == null || (oldTMCs != null && ((eachTMC.Code__c != oldTMCs.get(eachTMC.Id).Code__c)||(eachTMC.PCC__C != oldTMCs.get(eachTMC.Id).PCC__C)))))
            {
                if(gdsMap.get(eachTMC.Code__c)!=null)
                {
                    if(eachTMC.PCC__C.length()<gdsMap.get(eachTMC.Code__c).pcc_min_length__c || 
                       eachTMC.PCC__C.length()>gdsMap.get(eachTMC.Code__c).pcc_max_length__c)
                    {
                        if(gdsMap.get(eachTMC.Code__c).pcc_min_length__c==gdsMap.get(eachTMC.Code__c).pcc_max_length__c)
                        {
                            eachTMC.pcc__c.adderror(gdsMap.get(eachTMC.Code__c).Name+' PCC length should be '+gdsMap.get(eachTMC.Code__c).pcc_min_length__c+' Characters');
                        }
                        else
                        {
                            eachTMC.pcc__c.adderror(gdsMap.get(eachTMC.Code__c).Name+' PCC length should be between '+gdsMap.get(eachTMC.Code__c).pcc_min_length__c+' and '+
                                                    gdsMap.get(eachTMC.Code__c).pcc_max_length__c+' Characters');
                        }
                    }
                }
            }
            Agency_Info__c existingAgencyInfo = oldTMCs != null ? oldTMCs.get(eachTMC.Id) : null;
            
            if(eachTMC != null && eachTMC.PCC__c != null && eachTMC.Code__c !=null && eachTMC.Account__c != null && eachTMC.RecordTypeId == tmcRTId &&
               (existingAgencyInfo == null || 
                (existingAgencyInfo != null && (eachTMC.Account__c != existingAgencyInfo.Account__c || eachTMC.PCC__c != existingAgencyInfo.PCC__c || eachTMC.Code__c != existingAgencyInfo.Code__c))))
            {
                String tmcCombo = eachTMC.Account__c+'-'+eachTMC.PCC__c+'-'+eachTMC.Code__c;
                system.debug('Account GDS PCC Combo***'+tmcCombo);
                if(!accGDSPCCCombo.isEmpty() && accGDSPCCCombo.contains(tmcCombo)){
                    eachTMC.addError('This ' +eachTMC.Code__c+ ' ' +eachTMC.PCC__c+ ' already exists on this Account');
                    
                }
            }
            
            if(!existingAstGDSmap.isEmpty())
            {
                if(eachTMC != null && eachTMC.RecordTypeId == tmcRTId &&
                   (oldTMCs == null || 
                    (oldTMCs != null && eachTMC.Active__c != oldTMCs.get(eachTMC.Id).Active__c)))
                {
                    if(existingAstGDSmap.get(eachTMC.Account__c) != null && 
                       existingAstGDSmap.get(eachTMC.Account__c).contains(eachTMC.Code__c))
                        
                    {
                        eachTMC.GDS_Status__c = ((eachTMC.GDS_Status__c =='New' || String.isBlank(eachTMC.GDS_Status__c)) && eachTMC.Active__c) ? 'New' : 
                        ((eachTMC.GDS_Status__c =='New' || String.isBlank(eachTMC.GDS_Status__c)) && !eachTMC.Active__c) ? '' : 
                        eachTMC.GDS_Status__c;                           
                    }
                }
            }
        }
    }
    
    // Changes added by Vinoth - For Updating GDS Status based on PCC GDS Combination : CRM-3908
    
    public static void QCH_afterupdateTMC (list<Agency_Info__c> newTMCs, map<Id,Agency_Info__c> oldTMCs)
        
    {
        String tmcRTId = Schema.SObjectType.Agency_Info__c.getRecordTypeInfosByDeveloperName().get('GDS').getRecordTypeId();
        Set<Id> accountIds = new Set<Id>();
        Set<String> gdsValues = new Set<String>();
        Set<String> pccValues = new Set<String>();
        Set<String> inactiveGdsValues = new Set<String>();
        Set<String> inactivePccValues = new Set<String>();
        Set<Id> inactiveTMCAccountIds = new Set<Id>();
        Set<String> deregisterGdsValues = new Set<String>();
        Set<String> deregisterPccValues = new Set<String>();
        Set<Id> deregisterTMCAccountIds = new Set<Id>();
        String[] tmcStatus = new String[]{'New','Validating','Rejected'};
            Map<String,Agency_Info__c> agencyMap = new Map<String,Agency_Info__c>();
        List<Agency_Info__c> toUpdateActive = new List<Agency_Info__c>();
        List<Agency_Info__c> toUpdateInactive = new List<Agency_Info__c>();
        List<Agency_Info__c> toUpdateDeregistered = new List<Agency_Info__c>();
        List<Agency_Info__c> existingAcceptedTMCInfo;
        List<Agency_Info__c> existingAgencyTMCInfo;
        
        for(Agency_Info__c eachAg : newTMCs)
        {
            if(eachAg != null && eachAg.RecordTypeId == tmcRTId)
            {
                if(eachAg.PCC__c != null && eachAg.Code__c !=null && eachAg.GDS_Status__c == 'Accepted' && eachAg.ATPCO_Status__c == 'Accepted' && eachAg.Surcharge_Exemption_Status__c == 'Accepted' && eachAg.QDP_Status__c == 'Accepted' &&
                   (oldTMCs == null || 
                    (oldTMCs != null && (eachAg.GDS_Status__c != oldTMCs.get(eachAg.Id).GDS_Status__c || eachAg.ATPCO_Status__c != oldTMCs.get(eachAg.Id).ATPCO_Status__c || eachAg.Surcharge_Exemption_Status__c != oldTMCs.get(eachAg.Id).Surcharge_Exemption_Status__c  || eachAg.QDP_Status__c  != oldTMCs.get(eachAg.Id).QDP_Status__c))))
                    
                {
                    String tmcGDSPCCCombo = eachAg.PCC__c+'_'+eachAg.Code__c;
                    agencyMap.put(tmcGDSPCCCombo,eachAg);
                    gdsValues.add(eachAg.Code__c);
                    pccValues.add(eachAg.PCC__c);
                    accountIds.add(eachAg.Account__c);
                    system.debug('incoming After TMC account Ids***'+accountIds);
                }
                
                if(eachAg != null && eachAg.PCC__c != null && eachAg.Code__c !=null && eachAg.GDS_Status__c == 'Inactive' && eachAg.ATPCO_Status__c == 'Inactive' && eachAg.Surcharge_Exemption_Status__c == 'Inactive' && eachAg.QDP_Status__c == 'Inactive' &&
                   (oldTMCs == null || 
                    (oldTMCs != null && (eachAg.GDS_Status__c != oldTMCs.get(eachAg.Id).GDS_Status__c || eachAg.ATPCO_Status__c != oldTMCs.get(eachAg.Id).ATPCO_Status__c || eachAg.Surcharge_Exemption_Status__c != oldTMCs.get(eachAg.Id).Surcharge_Exemption_Status__c  || eachAg.QDP_Status__c  != oldTMCs.get(eachAg.Id).QDP_Status__c))))
                    
                {
                    inactiveGdsValues.add(eachAg.Code__c);
                    inactivePccValues.add(eachAg.PCC__c);
                    inactiveTMCAccountIds.add(eachAg.Account__c);
                }
                
                if(eachAg != null && eachAg.PCC__c != null && eachAg.Code__c !=null && eachAg.GDS_Status__c == 'Deregistered' && eachAg.ATPCO_Status__c == 'Deregistered' && eachAg.Surcharge_Exemption_Status__c == 'Deregistered' && eachAg.QDP_Status__c == 'Deregistered' &&
                   (oldTMCs == null || 
                    (oldTMCs != null && (eachAg.GDS_Status__c != oldTMCs.get(eachAg.Id).GDS_Status__c || eachAg.ATPCO_Status__c != oldTMCs.get(eachAg.Id).ATPCO_Status__c || eachAg.Surcharge_Exemption_Status__c != oldTMCs.get(eachAg.Id).Surcharge_Exemption_Status__c  || eachAg.QDP_Status__c  != oldTMCs.get(eachAg.Id).QDP_Status__c))))
                    
                {
                    deregisterGdsValues.add(eachAg.Code__c);
                    deregisterPccValues.add(eachAg.PCC__c);
                    deregisterTMCAccountIds.add(eachAg.Account__c);
                }
            }
        }
        
        if(!accountIds.isEmpty() && !pccValues.isEmpty() && !gdsValues.isEmpty())
        {
            
            for(Agency_Info__c eachTMC : [SELECT Id,Account__c,PCC__c,Code__c,Active__c,GDS_Effective_Date__c,Channel_Effective_Date__c,
                                          GDS_Status__c 
                                          FROM Agency_Info__c 
                                          WHERE Account__c NOT IN: accountIds AND PCC__c IN: pccValues AND Code__c IN: gdsValues  
                                          AND RecordTypeId =: tmcRTId AND Active__c = TRUE AND GDS_Status__c IN: tmcStatus])
                
                
            {
                if (eachTMC != null)
                    system.debug('New TMC***'+eachTMC);
                {
                    String TMCCombo = eachTMC.PCC__c+'_'+eachTMC.Code__c;
                    
                    if(agencyMap.containsKey(TMCCombo))
                    {
                        eachTMC.GDS_Status__c = 'Active';
                        eachTMC.ATPCO_Status__c = '';
                        eachTMC.Surcharge_Exemption_Status__c = '';
                        eachTMC.QDP_Status__c = '';
                        eachTMC.GDS_Effective_Date__c = agencyMap.get(TMCCombo).GDS_Effective_Date__c;
                        eachTMC.Channel_Effective_Date__c = agencyMap.get(TMCCombo).Channel_Effective_Date__c;
                        eachTMC.Channel_RecG_Identifier__c = '';
                        eachTMC.Channel_YR_Identifier__c = null ;
                        toUpdateActive.add(eachTMC);
                    }
                }
            }
        }
        
        if(!inactiveTMCAccountIds.isEmpty() && !inactivePccValues.isEmpty() && !inactiveGdsValues.isEmpty())
        {
            existingAcceptedTMCInfo = [SELECT Id, Account__c, PCC__c, Code__c FROM Agency_Info__c WHERE Account__c NOT IN: inactiveTMCAccountIds AND PCC__c IN: inactivePccValues AND Code__c IN: inactiveGdsValues AND GDS_Status__c = 'Accepted' AND RecordTypeId =: tmcRTId];
            
            if(existingAcceptedTMCInfo.isEmpty())
            {
                for(Agency_Info__c eachTMC : [SELECT Id,Account__c,PCC__c,Code__c,Active__c,GDS_Effective_Date__c,Channel_Effective_Date__c,
                                              GDS_Status__c, Channel_End_Date__c, Last_Inactive_Date__c
                                              FROM Agency_Info__c 
                                              WHERE Account__c NOT IN: inactiveTMCAccountIds AND PCC__c IN: inactivePccValues AND Code__c IN: inactiveGdsValues  
                                              AND RecordTypeId =: tmcRTId AND Active__c = TRUE AND GDS_Status__c = 'Active'])
                    
                {
                    if (eachTMC != null)
                    {
                        eachTMC.GDS_Status__c = 'Inactive';
                        eachTMC.Active__c = FALSE;
                        eachTMC.Channel_End_Date__c = system.today();
                        eachTMC.Last_Inactive_Date__c = system.now();
                        toUpdateInactive.add(eachTMC);
                    }
                }
            }
        }
        
        if(!deregisterTMCAccountIds.isEmpty() && !deregisterPccValues.isEmpty() && !deregisterGdsValues.isEmpty())
        {
            existingAgencyTMCInfo = [SELECT Id, Account__c, PCC__c, Code__c FROM Agency_Info__c WHERE Account__c NOT IN: deregisterTMCAccountIds AND PCC__c IN: deregisterPccValues AND Code__c IN: deregisterGdsValues AND GDS_Status__c = 'Accepted' AND RecordTypeId =: tmcRTId];
            
            if(existingAgencyTMCInfo.isEmpty())
            {
                for(Agency_Info__c eachTMC : [SELECT Id,Account__c,PCC__c,Code__c,Active__c,GDS_Effective_Date__c,Channel_Effective_Date__c,
                                              GDS_Status__c, Channel_End_Date__c, Last_Inactive_Date__c
                                              FROM Agency_Info__c 
                                              WHERE Account__c NOT IN: deregisterTMCAccountIds AND PCC__c IN: deregisterPccValues AND Code__c IN: deregisterGdsValues  
                                              AND RecordTypeId =: tmcRTId AND Active__c = TRUE AND GDS_Status__c = 'Active'])
                    
                {
                    if (eachTMC != null)
                    {
                        eachTMC.GDS_Status__c = 'Deregistered';
                        eachTMC.Channel_End_Date__c = system.today();
                        toUpdateDeregistered.add(eachTMC);
                    }
                }
            }
        }
        
        if(!toUpdateActive.isEmpty())
            update toUpdateActive;
        
        if(!toUpdateInactive.isEmpty())
            update toUpdateInactive;
        
        if(!toUpdateDeregistered.isEmpty())
            update toUpdateDeregistered;
    }
    
    // Changes ended
}