force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>Contact_Information__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the end date for the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the start date for the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Forecast_Charter_Spend__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Charter_Spend__c</fullName>
    <label>Forecast Charter Spend [EXCL GST]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts &amp; Agreements</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proposal Name</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required - Internal</fullName>
            </value>
            <value>
                <fullName>Signature Required by Customer</fullName>
            </value>
            <value>
                <fullName>Signed by Customer</fullName>
            </value>
            <value>
                <fullName>Rejected - Customer</fullName>
            </value>
            <value>
                <fullName>Rejected – Legal</fullName>
            </value>
            <value>
                <fullName>Approval Required – Legal</fullName>
            </value>
            <value>
                <fullName>Rejected - Internal</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Superceded</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forecast_MCA_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Forecast_MCA_Revenue__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Made Field Required based on CRM-5337 
Removed Required Field check -FCRM-956</description>
    <inlineHelpText>Including EK spend if joint customer</inlineHelpText>
    <label>Forecast MCA Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To be used for Group Sales Opportunity</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Payment Received</fullName>
            </value>
            <value>
                <fullName>Deposit Taken</fullName>
            </value>
            <value>
                <fullName>Full Amount Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Custom object to replace standard Quote object</description>
    <label>Proposal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>Contact_Information__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Forecast_MCA_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Forecast_MCA_Revenue__c</fullName>
    <description>Made Field Required based on CRM-5337</description>
    <inlineHelpText>Forecast QF+EK spend on MCA routes only</inlineHelpText>
    <label>Forecast MCA Revenue</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Proposal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposal_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the End Date for the Contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Proposal_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the Start Date of the Contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required - Internal</fullName>
            </value>
            <value>
                <fullName>Acceptance Required - Customer</fullName>
            </value>
            <value>
                <fullName>Accepted by Customer</fullName>
            </value>
            <value>
                <fullName>Rejected - Internal</fullName>
            </value>
            <value>
                <fullName>Rejected - External</fullName>
            </value>
            <value>
                <fullName>Pending ENG Approval</fullName>
            </value>
            <value>
                <fullName>ENG approved</fullName>
            </value>
            <value>
                <fullName>System Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QL_ConvertProposalContract.cls
public with sharing class QL_ConvertProposalContract
{
    @AuraEnabled public Boolean isSuccess {get;set;}
    @AuraEnabled public String msg {get;set;}
    //@AuraEnabled public String recID {get;set;}
    
    @AuraEnabled
    public static QL_ConvertProposalContract createProposalContract(Id OpporId)
    {
        QL_ConvertProposalContract Obj = new QL_ConvertProposalContract();
        
        try
        {
            system.debug('*******'+OpporId);
            Opportunity thisOpportunity = [Select Id, AccountId, Name, Forecast_Charter_Spend__c, Contact_Information__c, Description from Opportunity where Id = :OpporId];
            
            If(thisOpportunity != null)
            {
                Proposal__c NewProposal = new Proposal__c();
                NewProposal.Opportunity__c = thisOpportunity.Id;
                NewProposal.Account__c = thisOpportunity.AccountId;
                NewProposal.Name = thisOpportunity.Name;
                Newproposal.Status__c = 'System Created';
                Newproposal.Proposal_Start_Date__c = system.today();
                Newproposal.Proposal_End_Date__c = system.today();
                Newproposal.Forecast_MCA_Revenue__c = 1000;
            
                if(thisOpportunity.Forecast_Charter_Spend__c != null)
                    Newproposal.Forecast_Charter_Spend__c = thisOpportunity.Forecast_Charter_Spend__c;
                
                Newproposal.Contact_Information__c = thisOpportunity.Contact_Information__c;
                Newproposal.Description__c = thisOpportunity.Description;
                
                Id NewproposalRecordTypeId = Schema.SObjectType.Proposal__c.getRecordTypeInfosByName().get('Adhoc Charter').getRecordTypeId();
                Newproposal.RecordTypeId = NewproposalRecordTypeId;
            
                insert Newproposal;
                
                Contract__c NewContract = new Contract__c();
                NewContract.Account__c = Newproposal.Account__c;
                NewContract.Opportunity__c = Newproposal.Opportunity__c;
                NewContract.Name = Newproposal.Name;
                NewContract.Proposal__c = Newproposal.Id;
                NewContract.Contract_Start_Date__c = Newproposal.Proposal_Start_Date__c;
                NewContract.Contract_End_Date__c = Newproposal.Proposal_End_Date__c;
                NewContract.Forecast_Charter_Spend__c = Newproposal.Forecast_Charter_Spend__c;
                NewContract.Description__c = Newproposal.Description__c;
                NewContract.Contact_Information__c = Newproposal.Contact_Information__c;
                
                Id NewContractRId = Schema.SObjectType.Contract__c.getRecordTypeInfosByName().get('Adhoc Charter').getRecordTypeId();                
                NewContract.RecordTypeId = NewContractRId;
                
                insert NewContract;
                
                Obj.isSuccess = true;
                Obj.msg = 'The current Opportunit is converted to Proposal & Contract: '+ NewProposal.Name;
            }
            else
            {
                Obj.isSuccess = false;
                Obj.msg = 'There is no such Opportunity';
            }
            return Obj;            
        }
        catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());    
        }
    }

}