force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/recordTypes/Agency_Signed_by_Customer.recordType-meta.xml
<RecordType>
    <fullName>Agency_Signed_by_Customer</fullName>
    <active>true</active>
    <label>Agency - Signed by Customer</label>
</RecordType>

force-app/main/default/objects/Contract_Payments__c/Contract_Payments__c.object-meta.xml
<CustomObject>
    <description>Used to capture the contract payment information against each Payment Type.</description>
    <label>Contract Payments</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contract Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Payments__c/recordTypes/Channel_Incentive.recordType-meta.xml
<RecordType>
    <fullName>Channel_Incentive</fullName>
    <active>true</active>
    <description>This determines the records that belong to Channel Incentive Contract Payments</description>
    <label>Channel Incentive</label>
</RecordType>

force-app/main/default/objects/Contract_Payments__c/recordTypes/Channel_Tech_Fund.recordType-meta.xml
<RecordType>
    <fullName>Channel_Tech_Fund</fullName>
    <active>true</active>
    <label>Channel Tech Fund</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Agency_Partnerships.recordType-meta.xml
<RecordType>
    <fullName>Agency_Partnerships</fullName>
    <active>true</active>
    <businessProcess>Qantas Sales Process</businessProcess>
    <description>To be used to capture all types of opportunities for Agency Partnerships</description>
    <label>Agency Partnerships</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Agency_Partnerships.recordType-meta.xml
<RecordType>
    <fullName>Agency_Partnerships</fullName>
    <active>true</active>
    <label>Agency Partnerships</label>
</RecordType>

force-app/main/default/classes/QP_ContractPaymentControllerTest.cls
/**********************************************************************
Name:  QP_ContractPaymentControllerTest
Copyright © 2019  Qantas Airways.
======================================================
Req: 
To return record types for opportunity, quote, contract and agreement and contract payment objects
======================================================
Purpose:                                                            
Test class for QP_ContractPaymentController
======================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE              DETAIL
1.0 	Anil Nair       27/08/2019      Initial Development
========================================================
Methods
1. testCreateRecord() - performs data insert and call the createRecord method to check the ids of the record types
***********************************************************************/
@isTest
public class QP_ContractPaymentControllerTest {
    public static testmethod void testCreateRecord() {
        QP_ContractPaymentController obj = QP_ContractPaymentController.createRecord();
        System.assertEquals(Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Agency_Partnerships').getRecordTypeId(), obj.opptyRTId);
        System.assertEquals(Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('Agency_Partnerships').getRecordTypeId(), obj.quoteRTId);
        System.assertEquals(Schema.SObjectType.Contract__c.getRecordTypeInfosByDeveloperName().get('Agency_Signed_by_Customer').getRecordTypeId(), obj.contractRecordTypeID);
        System.assertEquals(Schema.SObjectType.Contract_Payments__c.getRecordTypeInfosByDeveloperName().get('Channel_Incentive').getRecordTypeId(), obj.cpIncentiveRTId);
        System.assertEquals(Schema.SObjectType.Contract_Payments__c.getRecordTypeInfosByDeveloperName().get('Channel_Tech_Fund').getRecordTypeId(), obj.cpTechFundRTId);
    }
}