force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proposal Name</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Share</fullName>
            </value>
            <value>
                <fullName>Volume</fullName>
            </value>
            <value>
                <fullName>Token</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Custom object to replace standard Quote object</description>
    <label>Proposal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Share</fullName>
            </value>
            <value>
                <fullName>Volume</fullName>
            </value>
            <value>
                <fullName>Token</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QEC_Rule__c/QEC_Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QEC_Rule__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Deal_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QEC_Rule__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTODEAL</fullName>
            </value>
            <value>
                <fullName>SUBVENTION</fullName>
            </value>
            <value>
                <fullName>DOMESTIC</fullName>
            </value>
            <value>
                <fullName>INTERNATIONAL</fullName>
            </value>
            <value>
                <fullName>NETFARE</fullName>
                <isActive>false</isActive>
                <label>NETFARE</label>
            </value>
            <value>
                <fullName>PRIVATEFARE</fullName>
                <isActive>false</isActive>
                <label>PRIVATEFARE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QEC_Rule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QEC_Rule__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CONSOLIDATOR</fullName>
            </value>
            <value>
                <fullName>CORPORATE</fullName>
            </value>
            <value>
                <fullName>ENTERTAINMENT</fullName>
            </value>
            <value>
                <fullName>FLYCRUISE</fullName>
            </value>
            <value>
                <fullName>GROUP</fullName>
            </value>
            <value>
                <fullName>GROUPS-ADHOC</fullName>
            </value>
            <value>
                <fullName>GROUPS-SERIES</fullName>
            </value>
            <value>
                <fullName>INDUSTRY</fullName>
            </value>
            <value>
                <fullName>INTERNET</fullName>
            </value>
            <value>
                <fullName>RETAIL(AUSTRALIA)</fullName>
            </value>
            <value>
                <fullName>RETAIL(RESTOFWORLD)</fullName>
            </value>
            <value>
                <fullName>SEAMAN</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>STUDENT</fullName>
            </value>
            <value>
                <fullName>VFR</fullName>
            </value>
            <value>
                <fullName>WHOLESALE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QEC_Rule__c/fields/Recommended__c.field-meta.xml
<CustomField>
    <fullName>Recommended__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recommended flag for Rules</description>
    <label>Recommended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QEC_Rule_Guidelines__c/QEC_Rule_Guidelines__c.object-meta.xml
<CustomObject>
    <label>QEC Rule Guidelines</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Guideline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QEC Rule Guidelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QEC_Rule_Guidelines__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTODEAL</fullName>
            </value>
            <value>
                <fullName>SUBVENTION</fullName>
            </value>
            <value>
                <fullName>DOMESTIC</fullName>
            </value>
            <value>
                <fullName>INTERNATIONAL</fullName>
            </value>
            <value>
                <fullName>NETFARE</fullName>
                <isActive>false</isActive>
                <label>NETFARE</label>
            </value>
            <value>
                <fullName>PRIVATEFARE</fullName>
                <isActive>false</isActive>
                <label>PRIVATEFARE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QEC_Rule_Guidelines__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>MX</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
                <isActive>false</isActive>
                <label>AUS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QEC_Rule_Guidelines__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CONSOLIDATOR</fullName>
            </value>
            <value>
                <fullName>CORPORATE</fullName>
            </value>
            <value>
                <fullName>ENTERTAINMENT</fullName>
            </value>
            <value>
                <fullName>FLYCRUISE</fullName>
            </value>
            <value>
                <fullName>GROUP</fullName>
            </value>
            <value>
                <fullName>GROUPS-ADHOC</fullName>
            </value>
            <value>
                <fullName>GROUPS-SERIES</fullName>
            </value>
            <value>
                <fullName>INDUSTRY</fullName>
            </value>
            <value>
                <fullName>INTERNET</fullName>
            </value>
            <value>
                <fullName>RETAIL(AUSTRALIA)</fullName>
            </value>
            <value>
                <fullName>RETAIL(RESTOFWORLD)</fullName>
            </value>
            <value>
                <fullName>SEAMAN</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>STUDENT</fullName>
            </value>
            <value>
                <fullName>VFR</fullName>
            </value>
            <value>
                <fullName>WHOLESALE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QEC_Rule_Guidelines__c/fields/Recommended__c.field-meta.xml
<CustomField>
    <fullName>Recommended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recommended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QEC_Rule_Guidelines__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QEC_Rule_Guidelines__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QEC_FareRulesControllerTest.cls
/***********************************************************************************************************************************
Description: Test class for Handling Fare rules in Contract Object
Apex Class : QEC_FareRulesController.apxc
Lightning Component : QEC_FareRules

History:
======================================================================================================================
Name                    Jira        Description                                                 Tag
======================================================================================================================
Ram Kolli             EXPRCON-67     Manage Fare rules in Contract  object                      T01		        	
Created Date    : 09/09/19 (DD/MM/YYYY)
**********************************************************************************************************************************/

@isTest
public class QEC_FareRulesControllerTest {
    
    static testMethod void validateTestDataActiveProposal() {
        //Insert Fare rule guidlines
        Test.startTest();
        List<QEC_Rule_Guidelines__c> guidelineList = new List<QEC_Rule_Guidelines__c>();
        List<QEC_FareRulesController.guidelines> wrapper = new List<QEC_FareRulesController.guidelines>();
        QEC_FareRulesController.guidelines rec = new QEC_FareRulesController.guidelines();
        List<Account> accList = TestUtilityDataClassQantas.getAccounts();
        List<Opportunity> oppList = TestUtilityDataClassQantas.getOpportunities(accList);
        List<Proposal__c> proposalList = TestUtilityDataClassQantas.getProposal(oppList);
        List<Contract__c> contractList = TestUtilityDataClassQantas.getContracts(proposalList);
        
        rec.dealType='INTERNATIONAL';
        rec.location='AU';
        rec.mktSgmt='CORPORATE';
        rec.recommended=true;
        rec.ruleName='Test name1';
        rec.sequence=1;
        rec.textAreaData='Test data1';
        wrapper.add(rec);
        for(Integer i=0;i<10;i++){
            QEC_Rule_Guidelines__c record = new QEC_Rule_Guidelines__c();
            record.Location__c ='AU';
            record.Deal_Type__c='INTERNATIONAL';
            record.Market_Segment__c='CORPORATE';
            record.Recommended__c = true;
            record.Sequence_Number__c = i;
            record.Name ='Test name'+i;
            record.Text__c='Test Data'+i;
            guidelineList.add(record);
        }
        
        insert guidelineList;
        delete [select id from QEC_Rule__c limit 100];
        //insert wrapper;
        QEC_FareRulesController.getRuleGuidelines(Label.QEC_Deal_Type,Label.QEC_Market_Segment,contractList.get(0).Id);
        QEC_FareRulesController.saveFareRules(wrapper,contractList.get(0).Id);
        QEC_FareRulesController.getRuleGuidelines(Label.QEC_Deal_Type,Label.QEC_Market_Segment,contractList.get(0).Id);
        Test.stopTest();
    }
}