force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ABTA_Number__c.field-meta.xml
<CustomField>
    <fullName>ABTA_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Applicable only for UK &amp; Ireland Accounts</inlineHelpText>
    <label>ABTA Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Agency_Sales_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Sales Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Region__c.sales_h_eq_type__c</field>
            <operation>equals</operation>
            <value>Corporate-Industry, Industry</value>
        </filterItems>
        <filterItems>
            <field>Sales_Region__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>The Brand value and associated Brand Code comes from the Sales Region master list. For the value to appear as a selectable it must be added to the Sales Region list first.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Agency Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Sub_Chain__c.field-meta.xml
<CustomField>
    <fullName>Agency_Sub_Chain__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Agency Sub Chain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ATAS__c.field-meta.xml
<CustomField>
    <fullName>ATAS__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the agencies AFTA Travel Accreditation Scheme Number</inlineHelpText>
    <label>ATAS Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ATOL_Number__c.field-meta.xml
<CustomField>
    <fullName>ATOL_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Applicable only for UK &amp; Ireland Accounts</inlineHelpText>
    <label>ATOL Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <inlineHelpText>Freight: Please select relevant business type
Corporate:
Prospect - Corporate account not on a deal
Customer - Corporate account on a deal
Agency - An Industry Account</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>Leisure &amp; Corporate</fullName>
            </value>
            <value>
                <fullName>Consolidator</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Share of Business</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
            <value>
                <fullName>Commercial Partner</fullName>
            </value>
            <value>
                <fullName>ITO - Inbound Tour Operator</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Customer Prospect</fullName>
            </value>
            <value>
                <fullName>Agency Prospect</fullName>
            </value>
            <value>
                <fullName>Online Travel Agent (OTA)</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Tourism</fullName>
            </value>
            <value>
                <fullName>Freight Forwarder</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Partner Airline</fullName>
            </value>
            <value>
                <fullName>GSA</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Aggregator</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Mobile Developer</fullName>
            </value>
            <value>
                <fullName>Online Booking Tool</fullName>
            </value>
            <value>
                <fullName>Travel Management Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Member__c.field-meta.xml
<CustomField>
    <fullName>Channel_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Channel Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Generic Company Email</inlineHelpText>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Date__c</fullName>
    <description>TS-4725 : Save maintenance date in SF for Agency Accounts</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agency : The date when the agency manager reviewed and confirmed the agency contact details online.</inlineHelpText>
    <label>Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone_Area__c.field-meta.xml
<CustomField>
    <fullName>Phone_Area__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone Area Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Phone_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone Country Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QAC_Request_Pending__c.field-meta.xml
<CustomField>
    <fullName>QAC_Request_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Pending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Qantas_Industry_Centre_ID__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Industry_Centre_ID__c</fullName>
    <description>Unique Field after CRM-1340 is resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Qantas Industry Centre Identifier</inlineHelpText>
    <label>QIC ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Tradesite__c.field-meta.xml
<CustomField>
    <fullName>Tradesite__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Mark if the agent is a register user of the Industry Sales Site</inlineHelpText>
    <label>Tradesite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/Agency_Info__c.object-meta.xml
<CustomObject>
    <label>TMC Info</label>
    <nameField>
        <displayFormat>TMC-{0000}</displayFormat>
        <label>TMC Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMC Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TMC Info</relationshipLabel>
    <relationshipName>Agency_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>For intergration</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>This stores the GDS (Global Distribution System) Values</description>
    <inlineHelpText>Global Distribution System</inlineHelpText>
    <label>GDS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AARON GROUP</fullName>
            </value>
            <value>
                <fullName>Aeronology</fullName>
            </value>
            <value>
                <fullName>AirGateway</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Apollo</fullName>
            </value>
            <value>
                <fullName>Axess</fullName>
            </value>
            <value>
                <fullName>ClarityTTS</fullName>
            </value>
            <value>
                <fullName>CTM</fullName>
            </value>
            <value>
                <fullName>Duffel</fullName>
            </value>
            <value>
                <fullName>Expedia</fullName>
            </value>
            <value>
                <fullName>Farelogix</fullName>
                <label>Farelogix (F1)</label>
            </value>
            <value>
                <fullName>Galileo</fullName>
            </value>
            <value>
                <fullName>Infini</fullName>
            </value>
            <value>
                <fullName>Kyte</fullName>
            </value>
            <value>
                <fullName>Mystifly</fullName>
            </value>
            <value>
                <fullName>Navan</fullName>
            </value>
            <value>
                <fullName>QDP Portal</fullName>
            </value>
            <value>
                <fullName>Sabre</fullName>
            </value>
            <value>
                <fullName>Sabre Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Serko</fullName>
            </value>
            <value>
                <fullName>Spotnana</fullName>
            </value>
            <value>
                <fullName>TPConnects</fullName>
            </value>
            <value>
                <fullName>Travelfusion</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Concur</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Cytric</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Locomote</fullName>
            </value>
            <value>
                <fullName>Travelsky</fullName>
            </value>
            <value>
                <fullName>Verteil Technologies</fullName>
            </value>
            <value>
                <fullName>Worldspan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/recordTypes/GDS.recordType-meta.xml
<RecordType>
    <fullName>GDS</fullName>
    <active>true</active>
    <description>To be used only for Agency Accounts</description>
    <label>GDS</label>
</RecordType>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <description>Created as a result of SFDC and iDeal integration.</description>
    <label>Sales Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Region__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Active flag based on End Date</description>
    <formula>OR(Today() &lt; sales_h_end_date__c, ISNULL(sales_h_end_date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Brand Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agency : Email address which the report will be sent to. Separate multiple email addresses using the semicolon character &quot;;&quot;</inlineHelpText>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Hide_TMCTA__c.field-meta.xml
<CustomField>
    <fullName>Hide_TMCTA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To show/hide on the Website</description>
    <label>Hide TMCTA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QAC_AcctRetrievalUsingIATA.cls
/*
Purpose : used by My Agency Profile for retrieving the account primary and secondary Information using IATA Code. 
Developed By : 
Yuvraj MV :     Account record retrieval class
Ajay :          Edited Class based on Channel changes
TestClass :     QAC_AcctRetrievalUsingIATA_Test

Modified Date   : 23/08/19 (DD/MM/YYYY)
Modified By     : Vinothkumar Balasubramanian
JIRA            : TS-4725
Version         : V2.0 - Added new field "Maintenance Date"

Modified Date   : 18/09/19 (DD/MM/YYYY)
Modified By     : Vinothkumar Balasubramanian
JIRA            : TS-4810
Version         : V3.0 - Add Agency Sales Region Brand Code
*/
@RestResource(urlmapping='/QACAcctInformationRetrieval/*')
global with sharing class QAC_AcctRetrievalUsingIATA 
{
    @HttpGet
    global static void doAcctRetrieval()
    {
        QAC_AgencyAccountRetrieval accret;
        QAC_AgencyAccountRetrieval.AgencyPrimaryDetails primary;
        QAC_AgencyAccountRetrieval.AgencySecondaryDetails secondary;
        
        QAC_AgencyProfileResponses.exceptionResponse mapErrorResponse;
        List<QAC_AgencyProfileResponses.FieldErrors> listFieldErrorResp = new List<QAC_AgencyProfileResponses.FieldErrors>();
        map<String,Account> existingAccountmap = new map<String,Account>();
        map<String,Set<String>> existingTMCGDSmap = new map<String,Set<String>>();
        
        string finalResponse;
        String iataCode;
        String myFilter;
        
        try
        {
            RestRequest request = RestContext.request;
            RestResponse response = RestContext.response;
            iataCode = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
            
            system.debug('IATA CODE**'+iataCode);
            
            myFilter = request.params.get('filter');
            
            if(string.isNotEmpty(iataCode))
            {
                //New Changes JIRA:TS-4810 (Add Agency Sales Region Brand Code to the Below query)
                for(Account eachAccount : [Select Id,Name,ABN_Tax_Reference__c, Qantas_Industry_Centre_ID__c,Agency_Sub_Chain__c,
                                           QAC_Request_Pending__c,Agency_Sales_Region__r.Name,Active__c,Business_Type__c,Channel_Member__c,Agency_Sales_Region__r.Brand_Code__c,
                                           Agency_Sales_Region__r.Hide_TMCTA__c,Agency_Sales_Region__c,BillingStreet,Email__c,Tradesite__c,
                                           BillingCity,BillingCountryCode,BillingPostalCode,Phone_Number__c,Phone_Country_Code__c,
                                           Phone_Area__c,phone,ATAS__c,BillingState,NumberOfEmployees,Website,ABTA_Number__c,ATOL_Number__c,Maintenance_Date__c //New Change JIRA:TS-4725 : Add Maintenance Date on this query
                                           from Account where Qantas_Industry_Centre_ID__c =: iataCode])
                {
                    if(eachAccount != null)
                    {
                        existingAccountmap.put(eachAccount.Qantas_Industry_Centre_ID__c,eachAccount);
                    }
                }
            }
            
            system.debug('existing ***'+existingAccountmap);
            
            if(!existingAccountmap.isEmpty())
            {
                if(String.isNotBlank(myFilter))
                {
                    String tmcRTId = Schema.SObjectType.Agency_Info__c.getRecordTypeInfosByName().get('GDS').getRecordTypeId();                    
                    for(Agency_Info__c eachAgency : [SELECT Id,Account__r.Qantas_Industry_Centre_ID__c FROM Agency_Info__c
                                                     WHERE Account__r.Qantas_Industry_Centre_ID__c IN: existingAccountmap.keySet()
                                                     AND RecordTypeId =: tmcRTId AND Active__c = TRUE])
                    {
                        
                     /*   if(eachAgency != null){
                            if(existingTMCGDSmap.containsKey(eachAgency.Account__r.Qantas_Industry_Centre_ID__c)){
                                existingTMCGDSmap.get(eachAgency.Account__r.Qantas_Industry_Centre_ID__c).add(eachAgency.Code__c);
                            }
                            else{
                                existingTMCGDSmap.put(eachAgency.Account__r.Qantas_Industry_Centre_ID__c, new Set<String>{eachAgency.Code__c});
                            }
                        }*/
                    }
                    
                   // System.debug('existingTMCGDSmap'+existingTMCGDSmap);
                }
                
                response.statusCode = 200;
                
                if(existingAccountmap.containsKey(iataCode))
                {
                    accret = new QAC_AgencyAccountRetrieval();
                    primary =  new QAC_AgencyAccountRetrieval.AgencyPrimaryDetails(existingAccountmap.get(iataCode));
                    secondary = new QAC_AgencyAccountRetrieval.AgencySecondaryDetails(existingAccountmap.get(iataCode),
                                                                                      (existingTMCGDSmap.isEmpty()) ? null : existingTMCGDSmap.get(iataCode));
                    accret.agencyPrimaryDetails = primary;
                    accret.agencySecondaryDetails = secondary;
                    finalResponse = JSON.serializePretty(accret,true);
                    response.responseBody = Blob.valueOf(finalResponse);
                }
            }
            else if(string.isEmpty(iataCode))
            {
                response.statusCode = 400;
                listFieldErrorResp.add(new QAC_AgencyProfileResponses.FieldErrors('Id','IATA is Blank, Please enter valid IATA code' ));
                mapErrorResponse = new QAC_AgencyProfileResponses.exceptionResponse('400', 'Bad Request', listFieldErrorResp);
                response.responseBody = Blob.valueOf(JSON.serializePretty(mapErrorResponse,true));
            }
            else
            {
                response.statusCode         = 404;
                listFieldErrorResp.add(new QAC_AgencyProfileResponses.FieldErrors('Id','IATA doesnt exits' ));
                mapErrorResponse = new QAC_AgencyProfileResponses.exceptionResponse('404', 'Bad Request', listFieldErrorResp);
                response.responseBody = Blob.valueOf(JSON.serializePretty(mapErrorResponse,true));
            }
        }
        catch(Exception ex)
        {
            RestRequest request = RestContext.request;
            RestResponse response = RestContext.response;
            system.debug('Exception###' + ex);
            response.statusCode = 500;
            listFieldErrorResp.add(new QAC_AgencyProfileResponses.FieldErrors(ex.getStackTraceString(), ex.getMessage() ));
            mapErrorResponse = new QAC_AgencyProfileResponses.ExceptionResponse('500', 'Salesforce Internal Error', listFieldErrorResp);
            response.responseBody = Blob.valueOf(JSON.serializePretty(mapErrorResponse,true));
        }
    }
}