force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <description>Is this an agency account? (Aquire)</description>
    <label>Travel Agent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire__c.field-meta.xml
<CustomField>
    <fullName>Aquire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is either &quot;Active&quot; or &quot;Pending&quot;.</description>
    <inlineHelpText>Agency is a member of the Qantas Business Rewards Program</inlineHelpText>
    <label>QBR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_Override__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Override__c</fullName>
    <description>Override Aquire? (Aquire)</description>
    <label>QBR Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealing_Flag__c.field-meta.xml
<CustomField>
    <fullName>Dealing_Flag__c</fullName>
    <description>Is Qantas currently dealing with this customer?</description>
    <label>Corporate Deal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Air_Travel_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Air_Travel_Spend__c</fullName>
    <inlineHelpText>Used to capture the total estimated air travel spend (AUD) of the account - this field is either populated via Aquire/QBD product registration or is to be manually captured/updated by the Account Manager/Team. This is used to drive the account assignment.</inlineHelpText>
    <label>Estimated Total Air Travel Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manual_Revenue_Update__c.field-meta.xml
<CustomField>
    <fullName>Manual_Revenue_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Revenue Update [System]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer_Account.recordType-meta.xml
<RecordType>
    <fullName>Customer_Account</fullName>
    <active>true</active>
    <description>To be used for all non-Agency accounts having a contract with Qantas - this covers Corporate &amp; Government, University Consortiums, SMEs &amp; Multi-national accounts</description>
    <label>Customer Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <description>QAC - This field is used to Store ABN number which is coming from Agency Account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <description>QCC: Used to track/store the flight airline</description>
    <label>Airline</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aer Lingus</fullName>
            </value>
            <value>
                <fullName>Aeropelican</fullName>
            </value>
            <value>
                <fullName>Air Asia X</fullName>
            </value>
            <value>
                <fullName>Air Berlin</fullName>
            </value>
            <value>
                <fullName>Aircalin</fullName>
            </value>
            <value>
                <fullName>Air Canada</fullName>
            </value>
            <value>
                <fullName>Air China</fullName>
            </value>
            <value>
                <fullName>Air India</fullName>
            </value>
            <value>
                <fullName>Airlines PNG</fullName>
            </value>
            <value>
                <fullName>Air Mauritius</fullName>
            </value>
            <value>
                <fullName>Air New Zealand</fullName>
            </value>
            <value>
                <fullName>Airnorth</fullName>
            </value>
            <value>
                <fullName>Air Nuigini</fullName>
            </value>
            <value>
                <fullName>Air Pacific</fullName>
            </value>
            <value>
                <fullName>Air Vanuatu</fullName>
            </value>
            <value>
                <fullName>Alaska Airlines</fullName>
            </value>
            <value>
                <fullName>Alitalia</fullName>
            </value>
            <value>
                <fullName>All Nippon Airways</fullName>
            </value>
            <value>
                <fullName>American Airline</fullName>
            </value>
            <value>
                <fullName>American Airlines</fullName>
            </value>
            <value>
                <fullName>Asiana</fullName>
            </value>
            <value>
                <fullName>Beijing Capital Airlines</fullName>
            </value>
            <value>
                <fullName>Brindabella Airlines</fullName>
            </value>
            <value>
                <fullName>British Airways</fullName>
            </value>
            <value>
                <fullName>Cathay Pacific</fullName>
            </value>
            <value>
                <fullName>Cebu Pacific</fullName>
            </value>
            <value>
                <fullName>China Airlines</fullName>
            </value>
            <value>
                <fullName>China Eastern</fullName>
            </value>
            <value>
                <fullName>China Southern Airlines</fullName>
            </value>
            <value>
                <fullName>Delta Airlines</fullName>
            </value>
            <value>
                <fullName>Qantas</fullName>
                <default>true</default>
                <label>Qantas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Booking_PNR__c.field-meta.xml
<CustomField>
    <fullName>Booking_PNR__c</fullName>
    <description>QCC: Created to show/store Booking Reference # (PNR).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PNR</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>QCC: Created to show/store Customer Flight Number for which this Case is raised.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Migrated__c.field-meta.xml
<CustomField>
    <fullName>Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used for data migration only</description>
    <label>Migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Suburb__c.field-meta.xml
<CustomField>
    <fullName>Suburb__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Suburb</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Procurement/Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agency Manager</fullName>
            </value>
            <value>
                <fullName>Agency Owner</fullName>
            </value>
            <value>
                <fullName>Ambassador / High Commissioner</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager - Agency</fullName>
            </value>
            <value>
                <fullName>Business Development Manager – Corporate</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chancellor</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Charter Key Contact</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of Business Unit</fullName>
            </value>
            <value>
                <fullName>Chief of Finance</fullName>
            </value>
            <value>
                <fullName>Chief of Organisation</fullName>
            </value>
            <value>
                <fullName>Chief of Procurement</fullName>
            </value>
            <value>
                <fullName>Chief of the Organisation</fullName>
            </value>
            <value>
                <fullName>Commercial Director</fullName>
            </value>
            <value>
                <fullName>Commerical Partner Contact</fullName>
            </value>
            <value>
                <fullName>Consultant/agent</fullName>
            </value>
            <value>
                <fullName>Consultant/agent - Senior</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Assistant</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Executive Team Member (non Finance)</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Head of Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Key Traveller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the contact&apos;s job title within the organisation. Please use full description and avoid using abbreviations.
**S&amp;D - max 50 character limit applies.</inlineHelpText>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/migrated__c.field-meta.xml
<CustomField>
    <fullName>migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QCC_SensitiveCaseListControllerTest.cls
@isTest
private class QCC_SensitiveCaseListControllerTest {
    
    private static List<User> listUser = new List<User>();
    
    static {
        
        listUser = TestUtilityDataClassQantas.getUsers('Standard User', 'Department 1', 'QF');
        System.debug('=======listUser=========' + listUser);
        // Create Account
        System.runAs(listUser[0]){
            // create Case
            TestUtilityDataClassQantas.insertQantasConfigData();
            List<Trigger_Status__c> listTriggerConfigs = new List<Trigger_Status__c>();
            listTriggerConfigs.addAll(TestUtilityDataClassQantas.createEventTriggerSetting());
            listTriggerConfigs.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
            listTriggerConfigs.addAll(TestUtilityDataClassQantas.createAffectedPassengerTriggerSetting());
            listTriggerConfigs.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
            for(Trigger_Status__c triggerStatus : listTriggerConfigs){
                triggerStatus.Active__c = false;
            }
            insert listTriggerConfigs;
            
            //Fix for Jira(CRM-3702) - Prospect validation exception.
            List<Account> listAccountTest = new List<Account>();
            Id AccRecType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer_Account').getRecordTypeId();
            
            for(Integer i=1; i<4; i++){ 
                Account acc = new Account(Name = 'Sample'+i, Active__c = true, Aquire__c = true, Type = 'Customer Account', 
                                          RecordTypeId = AccRecType, Migrated__c = false, 
                                          Estimated_Total_Air_Travel_Spend__c = 0, Manual_Revenue_Update__c = false,
                                          Agency__c = 'N', Dealing_Flag__c = 'N', Aquire_Override__c = 'N' ,ABN_Tax_Reference__c = '1234567890'+i  
                                         );
                listAccountTest.add(acc); 
            }
            
            insert listAccountTest;
            
            //List<Account> listAccountTest = TestUtilityDataClassQantas.getAccounts();
            listAccountTest[0].OwnerId = listUser[0].Id;
            update listAccountTest[0];
            // CRETAE contact
            List<Contact> listContactTest = TestUtilityDataClassQantas.getContacts(listAccountTest);
            String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
            Contact newContact = new Contact();
            newContact.RecordTypeId = contactRecordTypeId;
            newContact.AccountId = listAccountTest[0].Id;
            newContact.Function__c = 'IT';
            newContact.Business_Types__c = 'B&G';
            newContact.Job_Role__c ='BDM';
            newContact.Job_Title__c ='Developer';
            newContact.Phone='8907654321';
            newContact.Email='abc@gmail.com';
            newContact.FirstName = 'newContact';
            newContact.LastName = 'newContact';
            
            insert  newContact;
            
            // create case
            List<Case> listCaseTest = new List<Case>();
            
            listCaseTest.add(createSensitiveCase('caseTest1', listContactTest[0].Id,true));
            listCaseTest.add(createSensitiveCase('caseTest2', listContactTest[1].Id,true));
            listCaseTest.add(createSensitiveCase('caseTest2', newContact.Id,true));
            
            listCaseTest.add(createSensitiveCase('caseTest1', listContactTest[0].Id,false));
            listCaseTest.add(createSensitiveCase('caseTest2', listContactTest[1].Id,false));
            listCaseTest.add(createSensitiveCase('caseTest2', newContact.Id,false));
            
            insert listCaseTest;
        }
        
        
        
    }
    
    private static Case createSensitiveCase(String subject, String contactId, Boolean sensitive){
        String type = 'Insurance Letter';
        String recordType = 'CCC Insurance Letter Case';
        Case cs = TestUtilityDataClassQantas.createCaseWithCodingValues(recordType, type, 'Proof of Boarding or No Show','','','');
        cs.Subject = subject;
        cs.Origin = 'Qantas.com';
        cs.Booking_PNR__c = 'K5F5ZE';
        cs.Flight_Number__c = 'QF0401';
        cs.ContactId = contactId;
        cs.Airline__c = 'Qantas';
        cs.Suburb__c = 'NSW';
        cs.Street__c = 'Jackson';
        cs.State__c = 'Mascot';
        cs.Post_Code__c = '20020';
        cs.Country__c = 'Australia';
        cs.Cabin_Class__c = 'Business';
        cs.Sensitive__c = sensitive;
        //For sensitive Case validation error
        cs.Status = 'In Progress';
        
        return cs;
    }
    
    @isTest static void testGetListCaseWrapperAccountPageOwnerNotLoginUser() {
        List<Account> lstAccount = [SELECT Id FROM Account where OwnerId =: listUser[0].Id];
        
        Test.startTest();
        
        // Implement test code
        ApexPages.StandardController sc = new ApexPages.StandardController(lstAccount[0]);
        QCC_SensitiveCaseListController controller = new QCC_SensitiveCaseListController(sc);
        
        PageReference pageRef = Page.QCC_AccountSensitiveCaseList;
        pageRef.getParameters().put('id', String.valueOf(lstAccount[0].Id));
        Test.setCurrentPage(pageRef);
        Boolean isDisplayList = controller.getIsDisplay();
        System.assertEquals(false, isDisplayList);
        Test.stopTest();
    }
    
    @isTest static void testGetListCaseWrapperAccountPageOwnerLoginUser() {
        List<Account> lstAccount = [SELECT Id, OwnerId FROM Account where OwnerId =: listUser[0].Id Limit 1];
        System.runAs(listUser[0]){
            Test.startTest();
            // Implement test code
            ApexPages.StandardController sc = new ApexPages.StandardController(lstAccount[0]);
            QCC_SensitiveCaseListController controller = new QCC_SensitiveCaseListController(sc);
            
            PageReference pageRef = Page.QCC_AccountSensitiveCaseList;
            pageRef.getParameters().put('id', String.valueOf(lstAccount[0].Id));
            Test.setCurrentPage(pageRef);
            controller.initSensitiveCaseLayout();
            controller.getSensitiveCaseWrapperList();
            controller.getIsDisplay();
            controller.getTotalPages();
            controller.getTotalPages();
            controller.previous();
            controller.next();
            controller.getTotalRecord();
            system.assertEquals( false ,controller.hasPrevious);
            system.assertEquals( false ,controller.hasNext);
            system.assertEquals( 1 ,controller.pageNumber);
            Test.stopTest();
        }
        
    }
    
    @isTest static void testGetListCaseWrapperContactPage() {
        List<Contact> lstContact = [SELECT Id, OwnerId FROM Contact Limit 1];
        System.runAs(listUser[0]){
            Test.startTest();
            // Implement test code
            ApexPages.StandardController sc = new ApexPages.StandardController(lstContact[0]);
            QCC_SensitiveCaseListController controller = new QCC_SensitiveCaseListController(sc);
            
            PageReference pageRef = Page.QCC_AccountSensitiveCaseList;
            pageRef.getParameters().put('id', String.valueOf(lstContact[0].Id));
            Test.setCurrentPage(pageRef);
            controller.initSensitiveCaseLayout();
            controller.getSensitiveCaseWrapperList();
            controller.getIsDisplay();
            system.assertEquals( false ,controller.hasPrevious);
            system.assertEquals( false ,controller.hasNext);
            system.assertEquals( 1 ,controller.pageNumber);
            Test.stopTest();
        }
        
    }
    
    @isTest static void testGetListCaseWrapperAccountPageOwnerLoginUserNonSensitive() {
        List<Account> lstAccount = [SELECT Id, OwnerId FROM Account where OwnerId =: listUser[0].Id Limit 1];
        System.runAs(listUser[0]){
            Test.startTest();
            // Implement test code
            ApexPages.StandardController sc = new ApexPages.StandardController(lstAccount[0]);
            QCC_SensitiveCaseListController controller = new QCC_SensitiveCaseListController(sc);
            
            PageReference pageRef = Page.QCC_AccountSensitiveCaseList;
            pageRef.getParameters().put('id', String.valueOf(lstAccount[0].Id));
            Test.setCurrentPage(pageRef);
            controller.initNonSensitiveCaseLayout();
            controller.getSensitiveCaseWrapperList();
            controller.getIsDisplay();
            controller.getTotalPages();
            controller.getTotalPages();
            controller.previous();
            controller.next();
            controller.getTotalRecord();
            system.assertEquals( false ,controller.hasPrevious);
            system.assertEquals( false ,controller.hasNext);
            system.assertEquals( 1 ,controller.pageNumber);
            Test.stopTest();
        }
        
    }
    
}