force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire__c.field-meta.xml
<CustomField>
    <fullName>Aquire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is either &quot;Active&quot; or &quot;Pending&quot;.</description>
    <inlineHelpText>Agency is a member of the Qantas Business Rewards Program</inlineHelpText>
    <label>QBR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Member__c.field-meta.xml
<CustomField>
    <fullName>Channel_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Channel Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Subscription_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Subscription_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Subscription Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Air_Travel_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Air_Travel_Spend__c</fullName>
    <inlineHelpText>Used to capture the total estimated air travel spend (AUD) of the account - this field is either populated via Aquire/QBD product registration or is to be manually captured/updated by the Account Manager/Team. This is used to drive the account assignment.</inlineHelpText>
    <label>Estimated Total Air Travel Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IATA_Number__c.field-meta.xml
<CustomField>
    <fullName>IATA_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IATA #</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency_Account.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account</fullName>
    <active>true</active>
    <description>To be used for all Industry Accounts having a contract with Qantas</description>
    <label>Agency Account</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <description>ADT-8/AC1: Record Type used in Qantas Call Center Page Layout</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/TaskEventTriggerTest.cls
@isTest
public class TaskEventTriggerTest{
    
    @testSetup
    public static void setup() {
        
        String agencyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agency_Account').getRecordTypeId();
        List<Trigger_Status__c> trgStatusList = new List<Trigger_Status__c>();
        Trigger_Status__c eventTrigger = new Trigger_Status__c(Name = 'EventTrigger',Active__c = true);
        Trigger_Status__c taskTrigger = new Trigger_Status__c(Name = 'TaskTrigger',Active__c = true);
        trgStatusList.add(eventTrigger);
        trgStatusList.add(taskTrigger);
        
        //trgStatusList.addAll(TestUtilityDataClassQantas.createAccountTriggerSetting());
        insert trgStatusList;
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added by Suresh
        
        Account myAccount = new Account(Name = 'Sample', Active__c = true, Aquire__c = true, Type = 'Agency Account', 
                                        RecordTypeId = agencyRecordTypeId, Migrated__c = true, ABN_Tax_Reference__c  ='34563565365',
                                        Channel_Subscription_Date__c=Date.today(),Channel_Member__c=true,
                                        Estimated_Total_Air_Travel_Spend__c = 0,IATA_Number__c = '2020202');
        insert myAccount;
    }
    
    public static testMethod void taskInsertTest(){
        Test.startTest();
        Account myAccount = [Select Id, Active__c from Account where Name = 'Sample'];
        
        myAccount.Active__c = FALSE;
        update myAccount;
        
        Task t = new Task(
            Subject = 'Call',
            Status = 'Not Started',
            Priority = 'Normal',
            WhatId = myAccount.Id
        );
        Try{
            insert t;
        }catch(Exception e){
            
        }
        Test.stopTest();
    }
    
    public static testMethod void eventInsertTest(){
        Test.startTest();
        Account myAccount = [Select Id, Active__c from Account where Name = 'Sample'];
        
        myAccount.Active__c = FALSE;
        update myAccount;
        
        
        Event eve = new Event(
            StartDateTime = System.Today(),
            EndDateTime = System.Today(),
            WhatId = myAccount.Id
        );
        Try{
            insert eve;
        }catch(Exception e){
            
        }
        Test.stopTest();
    }
}