force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <description>Is this an agency account? (Aquire)</description>
    <label>Travel Agent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AMEX__c.field-meta.xml
<CustomField>
    <fullName>AMEX__c</fullName>
    <defaultValue>false</defaultValue>
    <description>American Express Qantas Co-brand Card</description>
    <inlineHelpText>American Express Qantas Co-brand Card</inlineHelpText>
    <label>AMEX</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire__c.field-meta.xml
<CustomField>
    <fullName>Aquire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is either &quot;Active&quot; or &quot;Pending&quot;.</description>
    <inlineHelpText>Agency is a member of the Qantas Business Rewards Program</inlineHelpText>
    <label>QBR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Air_Travel_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Air_Travel_Spend__c</fullName>
    <inlineHelpText>Used to capture the total estimated air travel spend (AUD) of the account - this field is either populated via Aquire/QBD product registration or is to be manually captured/updated by the Account Manager/Team. This is used to drive the account assignment.</inlineHelpText>
    <label>Estimated Total Air Travel Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manual_Revenue_Update__c.field-meta.xml
<CustomField>
    <fullName>Manual_Revenue_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Revenue Update [System]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Qantas_Corporate_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Corporate_Identifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Qantas Corporate Identifier</inlineHelpText>
    <label>QCI</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/LookupAccount__c.field-meta.xml
<CustomField>
    <fullName>LookupAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up Account to associate with campaing</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <formula>IF( LeadId != null,Lead.ABN_Tax_Reference__c ,IF(ContactId != null , Contact.Account.ABN_Tax_Reference__c,&apos;&apos;))</formula>
    <label>ABN/Tax Reference</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Assigned_to_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To Track the campaign members assigned to logged-in user</description>
    <label>Assigned to User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Related) Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agency Manager</fullName>
            </value>
            <value>
                <fullName>Agency Owner</fullName>
            </value>
            <value>
                <fullName>Ambassador / High Commissioner</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager - Agency</fullName>
            </value>
            <value>
                <fullName>Business Development Manager – Corporate</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chancellor</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Charter Key Contact</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of Business Unit</fullName>
            </value>
            <value>
                <fullName>Chief of Finance</fullName>
            </value>
            <value>
                <fullName>Chief of Organisation</fullName>
            </value>
            <value>
                <fullName>Chief of Procurement</fullName>
            </value>
            <value>
                <fullName>Chief of the Organisation</fullName>
            </value>
            <value>
                <fullName>Commercial Director</fullName>
            </value>
            <value>
                <fullName>Commerical Partner Contact</fullName>
            </value>
            <value>
                <fullName>Consultant/agent</fullName>
            </value>
            <value>
                <fullName>Consultant/agent - Senior</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Assistant</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Executive Team Member (non Finance)</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Head of Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Key Traveller</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the contact&apos;s job title within the organisation. Please use full description and avoid using abbreviations.
**S&amp;D - max 50 character limit applies.</inlineHelpText>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QL_CampaignMemberDetailstest.cls
/***********************************************************************************************************************************

Description: Test Class for Campaign Member List component

History:
======================================================================================================================
Name                    Jira        Description                                                          Tag
======================================================================================================================
Pushkar Purushothaman   CRM-3081    Test Class for Campaign Member List component                    T01

Created Date    : 28/04/2018 (DD/MM/YYYY)

Modified By : Venkata Suresh Kumar (TCS Team), 02-Apr-2026
Desc : Remediated test class failures. Added setUpData() method. Formatted code

**********************************************************************************************************************************/
@isTest
public class QL_CampaignMemberDetailstest 
{
    @testSetup static void setUpData() {
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
    }
    
    @isTest static void Testmethod1()
    {
        String orgId = UserInfo.getOrganizationId();
        String sandboxName = UserInfo.getUserName().substringAfterLast('.au');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + randomInt;
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.Email = uniqueName + '@test' + sandboxName + '.com'; /*'testuser@test123456789.com';*/
        u.CompanyName = 'test.com';
        u.Title = 'Test User';
        u.Username = uniqueName + '@test' + sandboxName + '.com'; /*'testuser@test123456789.com';*/
        u.Alias = 'testuser';
        u.CommunityNickname = 'Test User';
        u.TimeZoneSidKey = 'Australia/Sydney';
        u.LocaleSidKey = 'en_AU';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = pf.Id;
        u.LanguageLocaleKey = 'en_US';
        insert u;
        
        system.runAs(u)
        {           
            Id RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Account').getRecordTypeId();
            
            Account acc = new Account(Name = 'Sample Acc ', Active__c = true, Aquire__c = true, Type = 'Customer Account', 
                                      RecordTypeId = RecordTypeId, Qantas_Corporate_Identifier__c = 'ABC', 
                                      Estimated_Total_Air_Travel_Spend__c = 0, Manual_Revenue_Update__c = false,
                                      Agency__c = 'N', AMEX__c = True, ABN_Tax_Reference__c = '1234567890');
            insert acc;            
            
            List<Contact> contactlist = new List<Contact>();
            for(Integer i=0;i<5;i++)
            {
                Contact con = new Contact(FirstName = 'FirstContact'+i,LastName='ContTest', Email='test1contact@duptest.com', AccountId = acc.Id,
                                          MailingCity = 'Sydney', MailingState = 'NSW', MailingPostalCode = '2000', MailingCountry = 'AU',  MailingStreet = 'Hill Road', Phone = '0444444444',
                                          Job_Role__c = 'Manager',Job_Title__c = 'MR');
                contactlist.add(con);
            }     
            insert contactlist;
            
            Campaign camp = new Campaign();
            camp.Name = 'Test campaign';
            camp.LookupAccount__c = acc.id;
            insert camp;            
            
            List<CampaignMember> cmember = new List<CampaignMember>();        
            for(Contact c : contactlist)
            {
                CampaignMember Newmember = new CampaignMember();
                Newmember.ContactId = c.id;
                Newmember.CampaignId = camp.Id;
                Newmember.Status = 'Planned';  
                Newmember.Assigned_to_User__c = u.Id; 
                Newmember.Related_Account__c = acc.Id;
                cmember.add(Newmember);                
            }
            
            Test.startTest();
            insert cmember;        
            QL_CampaignMemberDetails.fetchCampMembers(u.Id, 2, 1, camp.Id);
            Test.stopTest();
        }
    }
}