force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Domain</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <description>Is this an agency account? (Aquire)</description>
    <label>Travel Agent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Agency_Sales_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Sales Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Region__c.sales_h_eq_type__c</field>
            <operation>equals</operation>
            <value>Corporate-Industry, Industry</value>
        </filterItems>
        <filterItems>
            <field>Sales_Region__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>The Brand value and associated Brand Code comes from the Sales Region master list. For the value to appear as a selectable it must be added to the Sales Region list first.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Agency Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/AMEX__c.field-meta.xml
<CustomField>
    <fullName>AMEX__c</fullName>
    <defaultValue>false</defaultValue>
    <description>American Express Qantas Co-brand Card</description>
    <inlineHelpText>American Express Qantas Co-brand Card</inlineHelpText>
    <label>AMEX</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AMEX_response_Code__c.field-meta.xml
<CustomField>
    <fullName>AMEX_response_Code__c</fullName>
    <description>Eligibility Code that gets sent to to AMEX.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>D - Double Points, R - Rebate, I - Ineligible</inlineHelpText>
    <label>AMEX Eligibility Code [System]</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_Override__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Override__c</fullName>
    <description>Override Aquire? (Aquire)</description>
    <label>QBR Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealing_Flag__c.field-meta.xml
<CustomField>
    <fullName>Dealing_Flag__c</fullName>
    <description>Is Qantas currently dealing with this customer?</description>
    <label>Corporate Deal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Generic Company Email</inlineHelpText>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Listner_Type__c.field-meta.xml
<CustomField>
    <fullName>Listner_Type__c</fullName>
    <description>Captures the Listener type for which the Outbound is sent</description>
    <label>Listner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Stream</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Manager__mdt/Account_Manager__mdt.object-meta.xml
<CustomObject>
    <description>List of Account managers specific to country</description>
    <label>Account Manager</label>
    <pluralLabel>Account Managers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_Manager__mdt/fields/Account_OwnerId__c.field-meta.xml
<CustomField>
    <fullName>Account_OwnerId__c</fullName>
    <label>Account OwnerId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Manager__mdt/fields/Agency_Sales_Region_Number__c.field-meta.xml
<CustomField>
    <fullName>Agency_Sales_Region_Number__c</fullName>
    <label>Agency Sales Region Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Manager__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>To be used under the &quot;Special Conditions&quot; section</description>
    <label>Performance Bonus Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Payments__c/Contract_Payments__c.object-meta.xml
<CustomObject>
    <description>Used to capture the contract payment information against each Payment Type.</description>
    <label>Contract Payments</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contract Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Payments__c/fields/Contract_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Contract_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract &amp; Agreement</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Payments</relationshipLabel>
    <relationshipName>Contract_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delete_Tracker_Log__c/Delete_Tracker_Log__c.object-meta.xml
<CustomObject>
    <description>This will track the records Deleted.This will now track Account Records deleted which has Active QBR Products</description>
    <label>Delete Tracker Log</label>
    <nameField>
        <displayFormat>DT-{0000}</displayFormat>
        <label>Delete Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delete Tracker Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoices__c/Invoices__c.object-meta.xml
<CustomObject>
    <description>Created in accordance with Contract payment information</description>
    <label>Payments</label>
    <nameField>
        <displayFormat>Bags-18-{000000}</displayFormat>
        <label>Fact No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoices__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <formula>Contract_Payments__r.Contract_Agreement__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoices__c/fields/Contract_Payments__c.field-meta.xml
<CustomField>
    <fullName>Contract_Payments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Payments</label>
    <referenceTo>Contract_Payments__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/Product_Registration__c.object-meta.xml
<CustomObject>
    <description>To be used to capture details for different product registrations like Aquire and AMEX.</description>
    <label>Product Registration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>To be used to link the registered product record with the respective account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Registration</relationshipLabel>
    <relationshipName>Product_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Customer_s_Requested_Choice__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_Requested_Choice__c</fullName>
    <description>Customer’s Requested Choice from AMEX</description>
    <inlineHelpText>A - Aquire Points, R - Rebate</inlineHelpText>
    <label>Customer’s Requested Choice</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <description>Created as a result of SFDC and iDeal integration.</description>
    <label>Sales Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Region__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Active flag based on End Date</description>
    <formula>OR(Today() &lt; sales_h_end_date__c, ISNULL(sales_h_end_date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agency : Email address which the report will be sent to. Separate multiple email addresses using the semicolon character &quot;;&quot;</inlineHelpText>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/sales_h_region_id__c.field-meta.xml
<CustomField>
    <fullName>sales_h_region_id__c</fullName>
    <description>Field created as a result of SFDC and iDeal integration.</description>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <label>Sales Region ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHelper.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Praveen Sampath
Company:       Capgemini
Description:   Class to be invoked from Account Trigger
Inputs:
Test Class:    AccountTriggerHelperTest. 
************************************************************************************************
History
************************************************************************************************
06-Mar-2017    Benazir S A               Initial Design
07-Mar-2017    Praveen Sampath          Added createDelAccountLogTracker Method
21-Apr-2017    Praveen/Benazir         Added createCaseOnMultipleActiveQBR Method
-----------------------------------------------------------------------------------------------------------------------*/
public class AccountTriggerHelper {
    public Static Set<Id> setRecTypeId = allNonFreightAccountRecordType();
    
    /*--------------------------------------------------------------------------------------      
Method Name:        updateAccountDetail
Description:        Method to Assign Amex Response Code
Parameter:          Account New List & Old Map 
--------------------------------------------------------------------------------------*/    
    public static void updateAccountDetail(List<Account> newlstAccount, Map<Id,Account> oldMapAccount){
        try{
            Set<Id> setAccId = new Set<Id>();
            Map<String, String> mapAmexResCode = new Map<String, String>();
            Map<Id, String> mapAccCustomer = new Map<Id, String>(); 
            
            
            for(Account acc: newlstAccount){
                Account oldAcc = oldMapAccount.get(acc.Id);
                if(acc.AMEX__c == true && acc.AMEX_response_Code__c != 'D' && setRecTypeId.contains(acc.RecordTypeId) &&
                   ( acc.Agency__c != oldAcc.Agency__c || acc.Aquire_Override__c != oldAcc.Aquire_Override__c || 
                    acc.Dealing_Flag__c != oldAcc.Dealing_Flag__c))
                {
                    setAccId.add(acc.Id);
                }
            }
            
            if(setAccId.size() > 0){
                Id amexRecId = GenericUtils.getObjectRecordTypeId('Product_Registration__c',  CustomSettingsUtilities.getConfigDataMap('Prd Reg AEQCC Registration Rec Type'));
                
                for(Product_Registration__c prodReg: [select Id, Customer_s_Requested_Choice__c, Account__c from Product_Registration__c
                                                      where Account__c IN: setAccId AND RecordTypeId =: amexRecId AND Active__c = true ])
                {
                    mapAccCustomer.put(prodReg.Account__c, prodReg.Customer_s_Requested_Choice__c);
                }
                
                if(mapAccCustomer.size() > 0){
                    mapAmexResCode = CustomSettingsUtilities.getAllAmexResponseCode();
                }
            }
            
            for(Account acc: newlstAccount){
                if(setAccId.contains(acc.Id)){
                    acc.AMEX_response_Code__c = CustomSettingsUtilities.getAmexResponseCodeForAccount( mapAmexResCode, 
                                                                                                      acc.Agency__c, acc.Dealing_Flag__c, acc.Aquire_Override__c,
                                                                                                      mapAccCustomer.get(acc.Id)); 
                }
            }
        }
        catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Account Team - Account Trigger', 'AccountTriggerHelper', 
                                    'updateAccountDetail', String.valueOf(''), String.valueOf(''),false,'', ex);
        }
        
    }
    
    /*--------------------------------------------------------------------------------------      
Method Name:        updateAccountTeam
Description:        Method to Assign & create Account team members based on user department
Parameter:          Account New Map & Old Map 
--------------------------------------------------------------------------------------*/    
    public static void updateAccountTeam(Map<Id,Account> newMapAccount, Map<Id,Account> oldMapAccount){
        try{
            //AccountTeamHandler accHandler = new AccountTeamHandler(); // Commented on Feb 23 as this AccountTeamHandler class is no longer used
            List<Account> lstNewAccount = newMapAccount.values();
            // accHandler.setRevenueManualUpdate(lstNewAccount, oldMapAccount);
            //  accHandler.createAccountTeamMembers(lstNewAccount, oldMapAccount);
        }
        catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Account Team - Account Trigger', 'AccountTriggerHelper', 
                                    'updateAccountTeam', String.valueOf(''), String.valueOf(''),false,'', ex);
        }
    }
    
    /*--------------------------------------------------------------------------------------      
Method Name:        createAccountEligiblityLogs
Description:        Method to Create AccountIneligibilty Logs and Update
Parameter:          Account New Map & Old Map 
--------------------------------------------------------------------------------------*/    
    public static void createAccountEligiblityLogs(Map<Id,Account> newMapAccount, Map<Id,Account> oldMapAccount){
        try{
            AccountEligibilityLogHandler.createAccountEligiblityLogs(newMapAccount, oldMapAccount);
        }
        catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Account Team - Account Trigger', 'AccountTriggerHelper', 
                                    'createAccountEligiblityLogs', String.valueOf(''), String.valueOf(''),false,'', ex);
        }
    }
    
    /*--------------------------------------------------------------------------------------      
Method Name:        calculateDiscountCode
Description:        Method to DiscountCode Calculations on Products
Parameter:          Account New Map & Old Map 
--------------------------------------------------------------------------------------*/    
    public static void calculateDiscountCode(Map<Id,Account> newMapAccount, Map<Id,Account> oldMapAccount){
        try{
            AccountAirlineLevelHandler.updateDiscountCodeOnProducts(newMapAccount, oldMapAccount);
        }
        catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Account Team - Account Trigger', 'AccountTriggerHelper', 
                                    'calculateDiscountCode', String.valueOf(''), String.valueOf(''),false,'', ex);
        }
    }
    
    /*--------------------------------------------------------------------------------------      
Method Name:        createDelAccountLogTracker
Description:        Method to Create Delete Tracker Logs records when any Account is Deleted
Parameter:          Account Old Map 
--------------------------------------------------------------------------------------*/    
    public static void createDelAccountLogTracker(Map<Id,Account> oldMapAccount){
        try{
            String recTypeName = CustomSettingsUtilities.getConfigDataMap('Del Log SME Account Rec Type');
            List<CreateLogs.DeleteLogWrapper> lstDelLogWrapper = new List<CreateLogs.DeleteLogWrapper>();
            for(Account acc: oldMapAccount.values()){
                String directvalue = CustomSettingsUtilities.getConfigDataMap('AccListner Type Direct Stream');
                if(acc.Listner_Type__c == directvalue){
                    CreateLogs.DeleteLogWrapper delLogWrapper = new CreateLogs.DeleteLogWrapper();
                    delLogWrapper.recType = recTypeName;
                    delLogWrapper.recName =  acc.Name;
                    delLogWrapper.abnNumber = acc.ABN_Tax_Reference__c;
                    delLogWrapper.sobjectId = acc.Id;
                    delLogWrapper.sobjectName = 'Account';
                    lstDelLogWrapper.add(delLogWrapper);
                }
            }
            List<Delete_Tracker_Log__c> lstDelTrackerLog = CreateLogs.createDeleteLog(lstDelLogWrapper);
            insert lstDelTrackerLog;
        }catch(Exception ex){
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Account Team - Account Trigger', 'AccountTriggerHelper', 
                                    'createDelAccountLogTracker', String.valueOf(''), String.valueOf(''),false,'', ex);
        }
    }
    
    //Private Method to add Recortype
    private static Set<Id> allNonFreightAccountRecordType(){
        String allNonFreightAccRecType = String.isBlank(CustomSettingsUtilities.getConfigDataMap('Account RecType1'))?'':CustomSettingsUtilities.getConfigDataMap('Account RecType1');
        allNonFreightAccRecType += String.isBlank(CustomSettingsUtilities.getConfigDataMap('Account RecType2'))?'':CustomSettingsUtilities.getConfigDataMap('Account RecType2');
        allNonFreightAccRecType += String.isBlank(CustomSettingsUtilities.getConfigDataMap('Account RecType3'))?'':CustomSettingsUtilities.getConfigDataMap('Account RecType3');
        List<String> setAllRectypeName = allNonFreightAccRecType.split(';');
        
        Set<Id> setRecId = new Set<Id>();
        for(String recTypeName: setAllRectypeName){
            setRecId.add(GenericUtils.getObjectRecordTypeId('Account', recTypeName)); 
        }
        return setRecId;
    }
    /* Included as part of Global Registration
* To update Account Owner from Account_Manager__mdt
*/
    public static void beforeInsert(List<Account> accList)
    {
        String accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency Account').getRecordTypeId();
        List<Account> agencyAccounts = new List<Account>();
        Set<Id> salesRegionIds = new Set<Id>();
        for(Account acc:accList)
        {
            if(acc.recordtypeId==accRTId)
            {
                agencyAccounts.add(acc); 
                if (String.isNotBlank(acc.Agency_Sales_Region__c)) salesRegionIds.add(acc.Agency_Sales_Region__c);

            } 
        }
        if(agencyAccounts.size()>0)
        {
            OwnerUpdate(agencyAccounts, salesRegionIds);
        }
    }
    /* Included as part of Global Registration
* To update Account Owner from Account_Manager__mdt
*/
    public static void beforeUpdate(List<Account> listOfAcc, map<Id,Account> oldAccMap)
    {
        String accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency Account').getRecordTypeId();
        List<Account> countryChange = new List<Account>();
        Set<Id> salesRegionIds = new Set<Id>();
        String currentUser = [select Name from User where Id = :UserInfo.getUserId()].Name;
        Set<String> excludedUserNamesList = new Set<String>{'Marione Lozano','MARY ELEK','NADINE FERNANDESMONIZ'};
        for(Account acc: listOfAcc)
        {
            if(!excludedUserNamesList.contains(currentUser)){
                if((acc.billingcountrycode!=oldAccMap.get(acc.Id).billingcountrycode) && acc.recordtypeId==accRTId)
                {
                    countryChange.add(acc); 
                    if (String.isNotBlank(acc.Agency_Sales_Region__c)) salesRegionIds.add(acc.Agency_Sales_Region__c);
                }
                if(acc.recordtypeId==accRTId && String.isNotBlank(acc.Agency_Sales_Region__c) && acc.Agency_Sales_Region__c!= oldAccMap.get(acc.Id).Agency_Sales_Region__c)
                {
                    countryChange.add(acc);
                    salesRegionIds.add(acc.Agency_Sales_Region__c);
                }
            }
        }
        if(countryChange.size()>0)
        {
            OwnerUpdate(countryChange, salesRegionIds);
            
        }    
    }
    /* Included as part of Global Registration
* To update Account Owner from Account_Manager__mdt
*/
    public static void OwnerUpdate(List<Account> ownerTobeUpdated, Set<Id> salesRegionIds)
    {
        List<Account_Manager__mdt> ownerList = [Select Developername,Account_OwnerId__c,Country_Code__c, Agency_Sales_Region_Number__c from Account_Manager__mdt];
        Map<String, String> countryOwnerId = new Map<String,String>();
        Set<String> userId = new Set<String>();
        Map<String,User> activeUsers;
        Map<Id, Sales_Region__c> salesRegionRecs = new Map<Id, Sales_Region__c>([Select id, sales_h_region_id__c from Sales_Region__c where id in :salesRegionIds]);
        
        for(Account_Manager__mdt owner:ownerList)
        {
            countryOwnerId.put(owner.Country_Code__c + (owner.Agency_Sales_Region_Number__c ?? ''),owner.Account_OwnerId__c);
            userId.add(owner.Account_OwnerId__c);
        }
        activeUsers=new Map<String,User>([Select Id,IsActive from User where Id in : userId and IsActive=True]);
        for(Account acc: ownerTobeUpdated)
        {
            String key = acc.billingcountrycode + salesRegionRecs.get(acc.Agency_Sales_Region__c)?.sales_h_region_id__c;
            if( countryOwnerId.get(key)!=null && activeUsers.containskey(countryOwnerId.get(key))) {
                acc.OwnerId=countryOwnerId.get(key);
            }
            else if(countryOwnerId.get(acc.billingcountrycode)!=null && activeUsers.containskey(countryOwnerId.get(acc.billingcountrycode)))
            {
                acc.OwnerId=countryOwnerId.get(acc.billingcountrycode);
            }else{
                acc.OwnerId=countryOwnerId.get('DefaultOwner');
            }  
        }   
    }
    
    /*public static boolean run = true;
    public static boolean runOnce(){
        try{
            if(run) {
                run=false;
                return true;
            } else {
                return run;
            }
        }catch(System.NullPointerException e)
        {
            return run;
        }
    }*/
            
    
    public static void updateRelatedRecordsOnOwnerChange(List<Account> accNew, Map<Id,Account> accMap)
    {
        List<sObject> updateRelatedRecords = new List<sObject>();
        Map<Id,Id> accIdnewOwnerId = new Map<Id,Id>();
        String accRecordTypes = Label.Qantas_Sales_Account_Recordtypes;
        system.debug('accNew### '+accNew);
        system.debug('accMap'+accMap);
        
        for(Account acc : accNew)
        {
            String accRecordTypeDevName = Schema.SObjectType.Account.getRecordTypeInfosById().get(acc.RecordTypeId).getDeveloperName();
            if(accRecordTypes.Contains(accRecordTypeDevName)) // Jira 5028
            {
                accIdnewOwnerId.put(acc.Id, acc.OwnerId);
                System.debug('accIdnewOwnerId'+accIdnewOwnerId);
            }
        }
        
        List<String> salesAssetRecordTypes = new List<String>();
        salesAssetRecordTypes.addAll(Label.Qantas_Sales_Asset_RecordTypes.split(';'));
        
        for(Asset a : [Select Id, Name, Status, Active__c, OwnerId, AccountId, RecordType.DeveloperName from Asset where 
                       AccountId IN :accIdnewOwnerId.keyset() AND RecordType.DeveloperName IN:salesAssetRecordTypes AND
                       (Status='Draft' OR Active__c = TRUE)])
        {
            if(a.OwnerId != accIdnewOwnerId.get(a.AccountId))
            {
                a.OwnerId = accIdnewOwnerId.get(a.AccountId);
                updateRelatedRecords.add(a);                
            }
        }
        
        Map<Id,Contract_Payments__c> updatedCP = new Map<Id,Contract_Payments__c>();
        List<Invoices__c> updatePayments = new List<Invoices__c>();
        for(Contract__c c : [Select Id, Account__c, (Select Id, Amount__c,OwnerId, Contract_Agreement__c from Contract_Payments__r) 
                             from Contract__c where Account__c IN:accIdnewOwnerId.keyset() AND Active__c = true])
        {
            for(Contract_Payments__c cp : c.Contract_Payments__r)
            {
                if(cp.OwnerId != accIdnewOwnerId.get(c.Account__c))
                {
                    cp.OwnerId = accIdnewOwnerId.get(c.Account__c);
                    updatedCP.put(cp.Id,cp);
                    updateRelatedRecords.add(cp);                    
                }
            }
        }
        
        for(Invoices__c payments : [Select Id, OwnerId, Contract_Payments__c from Invoices__c where 
                                    Contract_Payments__c IN:updatedCP.keyset()])
        {
            if(payments.OwnerId != updatedCP.get(payments.Contract_Payments__c).OwnerId)
            {
                payments.OwnerId = updatedCP.get(payments.Contract_Payments__c).OwnerId;
                updateRelatedRecords.add(payments);     
            }           
        }
        
        if(updateRelatedRecords.size()>0)
        {
            Database.SaveResult[] srList = Database.update(updateRelatedRecords, false);
            
            system.debug('update result '+srList);
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    System.debug('Records Successfully Updated');
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.' +err.getStatusCode() + ': ' + err.getMessage());                    
                    }
                }
            }     
        }
    }


    public static void updateDomainFromAccountEmail(List<Account> accountList, Map<Id, Account> oldAccountMap) {
        Account oldAccountRec;
        for (Account accRecord : accountList) {
            oldAccountRec = (oldAccountMap == null) ? null : oldAccountMap.get(accRecord.Id);
            if (String.isNotBlank(accRecord.Email__c) 
                && (oldAccountRec == null || accRecord.Email__c != oldAccountRec.Email__c)) 
            {
                accRecord.Account_Domain__c = accRecord.Email__c.substringAfter('@');
            }
        }
    }
}