force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Agency_Sales_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Sales Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Region__c.sales_h_eq_type__c</field>
            <operation>equals</operation>
            <value>Corporate-Industry, Industry</value>
        </filterItems>
        <filterItems>
            <field>Sales_Region__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>The Brand value and associated Brand Code comes from the Sales Region master list. For the value to appear as a selectable it must be added to the Sales Region list first.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Agency Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire__c.field-meta.xml
<CustomField>
    <fullName>Aquire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is either &quot;Active&quot; or &quot;Pending&quot;.</description>
    <inlineHelpText>Agency is a member of the Qantas Business Rewards Program</inlineHelpText>
    <label>QBR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Member__c.field-meta.xml
<CustomField>
    <fullName>Channel_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Channel Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Subscription_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Subscription_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Subscription Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Air_Travel_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Air_Travel_Spend__c</fullName>
    <inlineHelpText>Used to capture the total estimated air travel spend (AUD) of the account - this field is either populated via Aquire/QBD product registration or is to be manually captured/updated by the Account Manager/Team. This is used to drive the account assignment.</inlineHelpText>
    <label>Estimated Total Air Travel Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IATA_Number__c.field-meta.xml
<CustomField>
    <fullName>IATA_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IATA #</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency_Account.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account</fullName>
    <active>true</active>
    <description>To be used for all Industry Accounts having a contract with Qantas</description>
    <label>Agency Account</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Channel_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/GDS__c.field-meta.xml
<CustomField>
    <fullName>GDS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GDS</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <errorMessage>GDS should be Active and Channel Enabled or Farelogix Enabled</errorMessage>
        <filterItems>
            <field>GDS_Reference__c.Channel_Enabled__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>GDS_Reference__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>GDS_Reference__c.FareLogix_Indicator__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Add only Channel Enabled GDS OR Farelogix Enabled GDS</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GDS_Reference__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Premium_Channel_Status__c.field-meta.xml
<CustomField>
    <fullName>Premium_Channel_Status__c</fullName>
    <label>Premium NDC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>GDS Pending</fullName>
            </value>
            <value>
                <fullName>GDS Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>GDS Disable</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Agency_Channel.recordType-meta.xml
<RecordType>
    <fullName>Agency_Channel</fullName>
    <active>true</active>
    <description>This is being used for Channel Registration.</description>
    <label>Agency Channel</label>
</RecordType>

force-app/main/default/objects/GDS_Reference__c/GDS_Reference__c.object-meta.xml
<CustomObject>
    <label>GDS Reference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GDS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDS References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GDS_Reference__c/fields/Channel_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GDS_Reference__c/fields/Channel_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Channel_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Channel Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GDS_Reference__c/fields/PCC_Max_Length__c.field-meta.xml
<CustomField>
    <fullName>PCC_Max_Length__c</fullName>
    <label>PCC Max Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GDS_Reference__c/fields/PCC_Min_Length__c.field-meta.xml
<CustomField>
    <fullName>PCC_Min_Length__c</fullName>
    <label>PCC Min Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Offer_Allocation__c/Offer_Allocation__c.object-meta.xml
<CustomObject>
    <label>Offer Allocation</label>
    <nameField>
        <displayFormat>OAN-{0000}</displayFormat>
        <label>Offer Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Allocation__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Offer_Allocation__c/fields/Offer_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Offer_Catalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Catalogue</label>
    <referenceTo>Offer_Catalogue__c</referenceTo>
    <relationshipLabel>Offer Allocations</relationshipLabel>
    <relationshipName>Offer_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Deallocated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer_Catalogue__c/Offer_Catalogue__c.object-meta.xml
<CustomObject>
    <label>Offer Catalogue</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Offer Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Catalogue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Catalogue__c/fields/Marketing_Description__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Marketing Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer_Catalogue__c/fields/Offer_Customer_Selection__c.field-meta.xml
<CustomField>
    <fullName>Offer_Customer_Selection__c</fullName>
    <label>Offer Customer Selection</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Offer</fullName>
            </value>
            <value>
                <fullName>Frequent Flyer Offer</fullName>
            </value>
            <value>
                <fullName>Tactical Offer</fullName>
                <isActive>false</isActive>
                <label>Tactical Offer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Value__c.field-meta.xml
<CustomField>
    <fullName>Config_Value__c</fullName>
    <description>Text values used in the code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <description>Created as a result of SFDC and iDeal integration.</description>
    <label>Sales Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Region__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Active flag based on End Date</description>
    <formula>OR(Today() &lt; sales_h_end_date__c, ISNULL(sales_h_end_date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Brand Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/sales_h_end_date__c.field-meta.xml
<CustomField>
    <fullName>sales_h_end_date__c</fullName>
    <description>Field created as a result of SFDC and iDeal integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/sales_h_eq_type__c.field-meta.xml
<CustomField>
    <fullName>sales_h_eq_type__c</fullName>
    <label>Sales Hierarchy Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate-Industry</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Contract Group</fullName>
            </value>
            <value>
                <fullName>Consolidator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AgencyInvitationControllerTest.cls
@isTest
private class AgencyInvitationControllerTest {

    @testSetup
    public static void setup() {
        
        String agencyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agency_Account').getRecordTypeId();
        String assetRTId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Agency_Channel').getRecordTypeId();       

        List<Trigger_Status__c> lsttrgStatus = new List<Trigger_Status__c>();
        Trigger_Status__c calculateFeesAndDiscounts = new Trigger_Status__c(Name = 'AssetCalculateFeesandDiscounts',Active__c = false);
        lsttrgStatus.add(calculateFeesAndDiscounts);
        Trigger_Status__c assetConvertingAssetType  = new Trigger_Status__c(Name = 'AssetConvertingAssetType',Active__c = false);
        lsttrgStatus.add(assetConvertingAssetType);
        Trigger_Status__c chAsset = new Trigger_Status__c(Name = 'AssetChannel',Active__c = true);
        lsttrgStatus.add(chAsset);

        lsttrgStatus.addAll(TestUtilityDataClassQantas.createAccountTriggerSetting());
        insert lsttrgStatus;
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType();
        
        QantasConfigData__c qcd = new QantasConfigData__c(Name = 'Log Integration Logs Rec Type',Config_Value__c = 'Integration Logs');
        insert qcd;
        
        QantasConfigData__c qcd2 = new QantasConfigData__c(Name = 'Log Exception Logs Rec Type',Config_Value__c = 'Exception Logs');
        insert qcd2;

        Sales_Region__c mySR = new Sales_Region__c();
        mySR.Brand_Code__c = 'AU';
        mySR.sales_h_eq_type__c = 'Industry';
        mySR.sales_h_end_date__c = Date.today().addDays(1);
        mySR.Name = 'FCm Travel Solutions Test';
        insert mySR;
        
        //Inserting Account
        list<Account> accList = new list<Account>();
        Account myAccount = new Account(Name = 'Sample', Active__c = true, Aquire__c = true, Type = 'Agency Account', Agency_Sales_Region__c = mySR.Id,
                                        RecordTypeId = agencyRecordTypeId, Migrated__c = true, ABN_Tax_Reference__c  ='34563565365',
                                        Channel_Subscription_Date__c=Date.today(),Channel_Member__c=true,
                                        Estimated_Total_Air_Travel_Spend__c = 0,IATA_Number__c = '2020202');
        //insert myAccount;
        
        accList.add(myAccount);
        insert accList;
        
        
        // inserting GDS Reference
        list<GDS_Reference__c> gdsList = new list<GDS_Reference__c>();
        GDS_Reference__c gds1 = new GDS_Reference__c(Name='Amadeus',Channel_Enabled__c=true,Active__c=true,PCC_Max_Length__c=8,PCC_Min_Length__c=3);
        GDS_Reference__c gds2 = new GDS_Reference__c(Name='Sabre',Channel_Enabled__c=true,Active__c=true,PCC_Max_Length__c=6,PCC_Min_Length__c=3);
        gdsList.add(gds1);
        gdsList.add(gds2);
        insert gdsList;
        
        // inserting Asset
        list<Asset> allAssets = new list<Asset>();
        Asset myAsset1 = new Asset(Name='Sample',RecordTypeId = assetRTId,AccountId=myAccount.Id,Status='New',GDS__c=gds1.id,Customer_ID__c='12345',Channel_Effective_Date__c=Date.today(), 
                                    Premium_Channel_Status__c='Active'); 
        Asset myAsset2 = new Asset(Name='Sample2',RecordTypeId = assetRTId,AccountId=myAccount.Id,Status='New',GDS__c=gds2.id,Customer_ID__c='12345',Channel_Effective_Date__c=Date.today()); 
        allAssets.add(myAsset1);
        allAssets.add(myAsset2);
        insert allAssets;

        Offer_Catalogue__c offrCat = new Offer_Catalogue__c(Name = 'Test-1', Marketing_Description__c = 'testr', 
            Offer_Customer_Selection__c = 'General Offer', Offer_Audience__c = 'PNDC - Agent Specific', Offer_Start_Date__c = Date.today().addDays(1),
            /*Cabin__c = 'Business Class', */CurrencyIsoCode = 'AUD', Offer_Type__c = 'Fare Offer', Point_of_Sale_Country__c = 'AU');
        insert offrCat;

        Offer_Allocation__c offrAlloc = new Offer_Allocation__c(Offer_Catalogue__c = offrCat.Id,  Account__c = myAccount.Id, 
                                                                Status__c = 'Allocated', Effective_Date__c = Date.today());
        insert offrAlloc;
    }

    @IsTest
    private static void getAllocationsTestSuccess() {
        List<String> agencyIATA = new List<String>();
        List<String> agencyBrand = new List<String>();
        List<String> agencyGroup = new List<String>{'fcm%'};
        List<String> agencyIATACodes = new List<String>();
        Object agencyAllocations;
        Offer_Catalogue__c selectedOffer = [SELECT Id FROM Offer_Catalogue__c WHERE Name = 'Test-1' LIMIT 1];
        Test.startTest();
            agencyAllocations = AgencyInvitationController.getAllocations(agencyBrand, agencyGroup, agencyIATA, agencyIATACodes, selectedOffer.Id);
        Test.stopTest();
    }

    @IsTest
    private static void getAgencyInvitationsTestSuccess() {
        List<String> agencyIATA = new List<String>();
        List<String> agencyBrand = new List<String>();
        List<String> agencyGroup = new List<String>{'fcm%'};
        List<String> agencyIATACodes = new List<String>();
        List<sObject> agencyInvitation = new List<sObject>();
        Test.startTest();
            agencyInvitation = AgencyInvitationController.getAgencyInvitations(agencyBrand, agencyGroup, agencyIATA, agencyIATACodes);
        Test.stopTest();
    }

    @isTest
    static void testSendInvitationsSuccess() {
        // Arrange
        List<String> managerEmails = new List<String>{'test1@example.com'};
        String invitationType = 'Commercial Agreement';

        // Act
        Test.startTest();
        AgencyInvitationController.sendInvitations(managerEmails, invitationType);
        Integer sentEmails = Limits.getEmailInvocations();
        Test.stopTest();
        
        // Assert
        System.assertEquals(1, sentEmails, 'One emails should have been sent.');
        // Verify that emails were sent
    }

    @isTest
    static void testSendInvitationsInvalidType() {
        // Arrange
        List<String> managerEmails = new List<String>{'test1@example.com'};
        String invitationType = 'Invalid Type';

        // Act & Assert
        try {
            Test.startTest();
            AgencyInvitationController.sendInvitations(managerEmails, invitationType);
            Test.stopTest();
            System.assert(false, 'Exception should have been thrown for invalid invitation type.');
        } catch (AuraHandledException e) {
            System.assertEquals('Script-thrown exception', e.getMessage(), 'Exception message should match.');
        }
    }

    @isTest
    static void testSendInvitationsEmptyEmails() {
        // Arrange
        List<String> managerEmails = new List<String>{};
        String invitationType = 'Commercial Agreement';

        // Act
        Test.startTest();
        AgencyInvitationController.sendInvitations(managerEmails, invitationType);
        Test.stopTest();

        // Assert
        // Verify that no emails were sent
        System.assertEquals(0, Limits.getEmailInvocations(), 'No emails should have been sent.');
    }

@IsTest
    private static void getAgencyNamesFromIATAsTest() {
        Test.startTest();
            List<sObject> results = AgencyInvitationController.getAgencyNamesFromIATAs(new List<String>{'2020202'});
        Test.stopTest();
        
        System.assert(results != null, 'Results should not be null');
        System.assert(!results.isEmpty(), 'Results should not be empty');
        System.assert(results.size() >= 1, 'Results should contain at least one record');
    }

}