force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire__c.field-meta.xml
<CustomField>
    <fullName>Aquire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is either &quot;Active&quot; or &quot;Pending&quot;.</description>
    <inlineHelpText>Agency is a member of the Qantas Business Rewards Program</inlineHelpText>
    <label>QBR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Air_Travel_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Air_Travel_Spend__c</fullName>
    <inlineHelpText>Used to capture the total estimated air travel spend (AUD) of the account - this field is either populated via Aquire/QBD product registration or is to be manually captured/updated by the Account Manager/Team. This is used to drive the account assignment.</inlineHelpText>
    <label>Estimated Total Air Travel Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IATA_Number__c.field-meta.xml
<CustomField>
    <fullName>IATA_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IATA #</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Qantas_Industry_Centre_ID__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Industry_Centre_ID__c</fullName>
    <description>Unique Field after CRM-1340 is resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Qantas Industry Centre Identifier</inlineHelpText>
    <label>QIC ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Agency_Info__c/Agency_Info__c.object-meta.xml
<CustomObject>
    <label>TMC Info</label>
    <nameField>
        <displayFormat>TMC-{0000}</displayFormat>
        <label>TMC Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMC Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TMC Info</relationshipLabel>
    <relationshipName>Agency_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>For intergration</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/ATPCO_Status__c.field-meta.xml
<CustomField>
    <fullName>ATPCO_Status__c</fullName>
    <label>ATPCO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Channel_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>This stores the GDS (Global Distribution System) Values</description>
    <inlineHelpText>Global Distribution System</inlineHelpText>
    <label>GDS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AARON GROUP</fullName>
            </value>
            <value>
                <fullName>Aeronology</fullName>
            </value>
            <value>
                <fullName>AirGateway</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Apollo</fullName>
            </value>
            <value>
                <fullName>Axess</fullName>
            </value>
            <value>
                <fullName>ClarityTTS</fullName>
            </value>
            <value>
                <fullName>CTM</fullName>
            </value>
            <value>
                <fullName>Duffel</fullName>
            </value>
            <value>
                <fullName>Expedia</fullName>
            </value>
            <value>
                <fullName>Farelogix</fullName>
                <label>Farelogix (F1)</label>
            </value>
            <value>
                <fullName>Galileo</fullName>
            </value>
            <value>
                <fullName>Infini</fullName>
            </value>
            <value>
                <fullName>Kyte</fullName>
            </value>
            <value>
                <fullName>Mystifly</fullName>
            </value>
            <value>
                <fullName>Navan</fullName>
            </value>
            <value>
                <fullName>QDP Portal</fullName>
            </value>
            <value>
                <fullName>Sabre</fullName>
            </value>
            <value>
                <fullName>Sabre Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Serko</fullName>
            </value>
            <value>
                <fullName>Spotnana</fullName>
            </value>
            <value>
                <fullName>TPConnects</fullName>
            </value>
            <value>
                <fullName>Travelfusion</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Concur</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Cytric</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Locomote</fullName>
            </value>
            <value>
                <fullName>Travelsky</fullName>
            </value>
            <value>
                <fullName>Verteil Technologies</fullName>
            </value>
            <value>
                <fullName>Worldspan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/GDS_Status__c.field-meta.xml
<CustomField>
    <fullName>GDS_Status__c</fullName>
    <description>Introduced as part of Agency Channel Registration, It will be updated by ETL Jobs When its status is New</description>
    <label>GDS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validating</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
            <value>
                <fullName>Pending de-registration</fullName>
                <isActive>false</isActive>
                <label>Pending de-registration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Migrated__c.field-meta.xml
<CustomField>
    <fullName>Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag indicating that the record was migrated from Quest.</description>
    <label>Migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/PCC__c.field-meta.xml
<CustomField>
    <fullName>PCC__c</fullName>
    <description>This is to store the PCC (Pseudo City Code)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Pseudo City Code</inlineHelpText>
    <label>PCC</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/QDP_Status__c.field-meta.xml
<CustomField>
    <fullName>QDP_Status__c</fullName>
    <label>QDP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Surcharge_Exemption_Status__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Exemption_Status__c</fullName>
    <label>Surcharge Exemption Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactivation</fullName>
            </value>
            <value>
                <fullName>Pending deregistration</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>De-registered</fullName>
                <isActive>false</isActive>
                <label>De-registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/recordTypes/GDS.recordType-meta.xml
<RecordType>
    <fullName>GDS</fullName>
    <active>true</active>
    <description>To be used only for Agency Accounts</description>
    <label>GDS</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Channel_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Value__c.field-meta.xml
<CustomField>
    <fullName>Config_Value__c</fullName>
    <description>Text values used in the code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QAC_TMCOperations_Test.cls
/***********************************************************************************************************************************

Description: Apex Test class for QAC_TMCOperations Class 

*****************************************************************************************************************************/
@IsTest
public class QAC_TMCOperations_Test {
    
    @testSetup
    public static void setup() {
        
        system.debug('inside test setup**');
        String agencyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency Account').getRecordTypeId();
        List<QantasConfigData__c> qcdList = new List<QantasConfigData__c>();
        QantasConfigData__c qcd = new QantasConfigData__c(Name = 'Log Integration Logs Rec Type',Config_Value__c = 'Integration Logs');
        qcdList.add(qcd);
        
        QantasConfigData__c qcd2 = new QantasConfigData__c(Name = 'Log Exception Logs Rec Type',Config_Value__c = 'Exception Logs');
        qcdList.add(qcd2);
        
        QantasConfigData__c qcd3 = new QantasConfigData__c(Name='Account RecType1',Config_Value__c='Agency Account');
        qcdList.add(qcd3);
        insert qcdList;
        
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
             
        insert lsttrgStatus;

        //Inserting Account
        List<Account> accList = new List<Account>();
        Account acc = new Account(Name = 'Sample', Active__c = true, Aquire__c = true, Type = 'Agency Account', 
                                  RecordTypeId = agencyRecordTypeId, Migrated__c = true, ABN_Tax_Reference__c  ='34563565365',
                                  Estimated_Total_Air_Travel_Spend__c = 0,IATA_Number__c = '4364557');
        
        accList.add(acc);
        
        Account relatedAcc = new Account(Name = 'Sample2', Active__c = true, Aquire__c = true, Type = 'Agency Account', 
                                         RecordTypeId = agencyRecordTypeId, Migrated__c = true, ABN_Tax_Reference__c  ='34563565365',
                                         Estimated_Total_Air_Travel_Spend__c = 0,IATA_Number__c = '1000000', Qantas_Industry_Centre_ID__c = '1000000');
        
        accList.add(relatedAcc);
        
        insert accList;

        String tmcRTID = Schema.SObjectType.Agency_Info__c.getRecordTypeInfosByName().get('GDS').getRecordTypeId();

        //Inserting TMC Info
        List<Agency_Info__c> listAgencyinfo = new List<Agency_Info__c>();
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.Account__c = accList[0].Id;
        Agencyinfo.RecordTypeId = tmcRTID;        
        Agencyinfo.Active__c=true;
        Agencyinfo.Email_Id__c='test@test.com';
        Agencyinfo.Code__c  ='Galileo';
        Agencyinfo.PCC__c   ='AS2P';
        Agencyinfo.GDS_Status__c ='New';
        
        listAgencyinfo.add(Agencyinfo);

        Agency_Info__c Agencyinfo2 = new Agency_Info__c();
        Agencyinfo2.Account__c = accList[0].Id;
        Agencyinfo2.RecordTypeId = tmcRTID;        
        Agencyinfo2.Active__c=true;
        Agencyinfo2.Email_Id__c='test@test.com';
        Agencyinfo2.Code__c  ='Sabre';
        Agencyinfo2.PCC__c   ='2yMT';
        Agencyinfo2.GDS_Status__c='Accepted';
        Agencyinfo2.ATPCO_Status__c='Accepted';
        Agencyinfo2.Surcharge_Exemption_Status__c='Accepted';
        Agencyinfo2.QDP_Status__c='Accepted';
        Agencyinfo2.Channel_Effective_Date__c = System.today().addDays(+2);
        
        listAgencyinfo.add(Agencyinfo2);
        
        Agency_Info__c Agencyinfo3 = new Agency_Info__c();
        Agencyinfo3.Account__c = accList[0].Id;
        Agencyinfo3.RecordTypeId = tmcRTID;        
        Agencyinfo3.Active__c=true;
        Agencyinfo3.Email_Id__c='test@test.com';
        Agencyinfo3.Code__c  ='Sabre';
        Agencyinfo3.PCC__c   ='2yMC';
        Agencyinfo3.GDS_Status__c='Accepted';
        Agencyinfo3.ATPCO_Status__c='';
        Agencyinfo3.Surcharge_Exemption_Status__c='';
        Agencyinfo3.QDP_Status__c='';
        
        listAgencyinfo.add(Agencyinfo3);
        
        Agency_Info__c Agencyinfo4 = new Agency_Info__c();
        Agencyinfo4.Account__c = accList[0].Id;
        Agencyinfo4.RecordTypeId = tmcRTID;        
        Agencyinfo4.Active__c=true;
        Agencyinfo4.Email_Id__c='test@test.com';
        Agencyinfo4.Code__c  ='Sabre';
        Agencyinfo4.PCC__c   ='2yMD';
        Agencyinfo4.GDS_Status__c='Accepted';
        Agencyinfo4.ATPCO_Status__c='Accepted';
        Agencyinfo4.Surcharge_Exemption_Status__c='Accepted';
        Agencyinfo4.QDP_Status__c='Accepted';
        Agencyinfo4.Channel_Effective_Date__c = System.today().addDays(-2);
        
        listAgencyinfo.add(Agencyinfo4);
        
        Agency_Info__c Agencyinfo5 = new Agency_Info__c();
        Agencyinfo5.Account__c = accList[0].Id;
        Agencyinfo5.RecordTypeId = tmcRTID;        
        Agencyinfo5.Active__c=true;
        Agencyinfo5.Email_Id__c='test@test.com';
        Agencyinfo5.Code__c  ='Galileo';
        Agencyinfo5.PCC__c   ='2yMK';
        Agencyinfo5.GDS_Status__c='Rejected';
        
        listAgencyinfo.add(Agencyinfo5);
        
        Agency_Info__c Agencyinfo6 = new Agency_Info__c();
        Agencyinfo6.Account__c = accList[0].Id;
        Agencyinfo6.RecordTypeId = tmcRTID;        
        Agencyinfo6.Active__c=true;
        Agencyinfo6.Email_Id__c='test@test.com';
        Agencyinfo6.Code__c  ='Galileo';
        Agencyinfo6.PCC__c   ='2yMH';
        Agencyinfo6.GDS_Status__c='Deregistered';
        Agencyinfo6.ATPCO_Status__c='Deregistered';
        Agencyinfo6.Surcharge_Exemption_Status__c='Deregistered';
        Agencyinfo6.QDP_Status__c='Pending deregistration';
        
        listAgencyinfo.add(Agencyinfo6);
        
        Agency_Info__c Agencyinfo7 = new Agency_Info__c();
        Agencyinfo7.Account__c = accList[0].Id;
        Agencyinfo7.RecordTypeId = tmcRTID;        
        Agencyinfo7.Active__c=true;
        Agencyinfo7.Email_Id__c='test@test.com';
        Agencyinfo7.Code__c  ='Apollo';
        Agencyinfo7.PCC__c   ='2yMI';
        Agencyinfo7.GDS_Status__c='Deregistered';
        Agencyinfo7.ATPCO_Status__c='Deregistered';
        Agencyinfo7.Surcharge_Exemption_Status__c='Deregistered';
        Agencyinfo7.QDP_Status__c='Deregistered';
        
        listAgencyinfo.add(Agencyinfo7);
        
        Agency_Info__c Agencyinfo8 = new Agency_Info__c();
        Agencyinfo8.Account__c = accList[0].Id;
        Agencyinfo8.RecordTypeId = tmcRTID;        
        Agencyinfo8.Active__c=true;
        Agencyinfo8.Email_Id__c='test@test.com';
        Agencyinfo8.Code__c  ='Sabre';
        Agencyinfo8.PCC__c   ='2yML';
        Agencyinfo8.GDS_Status__c='';
        
        listAgencyinfo.add(Agencyinfo8);
        
        /*Agency_Info__c Agencyinfo3 = new Agency_Info__c();
        Agencyinfo3.Account__c = accList[1].Id;
        Agencyinfo3.Active__c=true;
        Agencyinfo3.Email_Id__c='test@test.com';
        Agencyinfo3.Code__c  ='Galileo';
        Agencyinfo3.PCC__c   ='AS2P';
        Agencyinfo3.Market_Segment__c ='Corporate';
        listAgencyinfo.add(Agencyinfo3);
        */
        insert listAgencyinfo;
        
        List<Trigger_Status__c> st = new List<Trigger_Status__c>();
        Trigger_Status__c tr = new Trigger_Status__c(name='AssetCalculateFeesandDiscounts');
        st.add(tr);
        Trigger_Status__c tr1 = new Trigger_Status__c(name='AssetConvertingAssetType');
        st.add(tr1);
        Trigger_Status__c tr2 = new Trigger_Status__c(name='AssetChannel');
        st.add(tr2);
        insert st;
        Asset asstObj = new Asset();
        asstObj.accountId=accList[1].Id;
        asstObj.Name='Test';
        asstObj.Status='New';
        asstObj.RecordTypeId=Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Agency Channel').getRecordTypeId();
        insert asstObj;
    }
    
    
    // Testing positive scenario
    @isTest
    public static void testParse() {
        
        Account agencyAccount = [SELECT Id, IATA_Number__c FROM Account WHERE IATA_Number__c = '1000000' LIMIT 1];
        
        system.debug(' @@ agencyAccount @@ ' + agencyAccount);
        
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.Account__c = agencyAccount.Id;
        Agencyinfo.Active__c=true;
        Agencyinfo.Email_Id__c='test@test.com';
        Agencyinfo.Code__c  ='Galileo';
        Agencyinfo.PCC__c   ='AS2P';
        Agencyinfo.Market_Segment__c ='Corporate';
        
        list<QAC_TMCInformationParsing> requestBody = new list<QAC_TMCInformationParsing>();
        requestBody.add(new QAC_TMCInformationParsing(Agencyinfo));

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/QACTMCOperations/1000000';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serializePretty(requestBody));
        //req.requestBody = Blob.valueOf(JSON.serializePretty(myApi));
        
        RestContext.request = req;
        RestContext.response = res;
        
        test.startTest();
        QAC_TMCOperations.doTMCInsertion();
        test.stopTest();
    }
    @isTest
    public static void testParse1() {
        
        Account agencyAccount = [SELECT Id, IATA_Number__c FROM Account WHERE IATA_Number__c = '4364557' LIMIT 1];
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.Account__c = agencyAccount.Id;
        Agencyinfo.Active__c=true;
        Agencyinfo.Email_Id__c='test@test.com';
        Agencyinfo.Code__c  ='Galileo';
        Agencyinfo.PCC__c   ='AS2P';
        Agencyinfo.Market_Segment__c ='Corporate';
        
        list<QAC_TMCInformationParsing> requestBody = new list<QAC_TMCInformationParsing>();
        requestBody.add(new QAC_TMCInformationParsing(Agencyinfo));
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/QACTMCOperations/1000000';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serializePretty(requestBody));
        //req.requestBody = Blob.valueOf(JSON.serializePretty(myApi));
        
        RestContext.request = req;
        RestContext.response = res;
        
        test.startTest();
        QAC_TMCOperations.doTMCInsertion();
        test.stopTest();
    
    }    
    @isTest
    public static void testPatch1() {
        
        Agency_Info__c tmc= [SELECT Id,Email_Id__c FROM Agency_Info__c limit 1]; 
        System.debug('tmcList'+tmc);
        Agency_Info__c agencyinfo = new Agency_Info__c();
        agencyinfo.id = tmc.Id;
        agencyinfo.Active__c=true;
        QAC_TMCInformationParsing requestBody = new QAC_TMCInformationParsing(Agencyinfo);
        reqMethodBody('1000000','PATCH',requestBody);
        test.startTest();
        QAC_TMCOperations.doTMCupdate();
        test.stopTest();
    
    }
    @isTest
    public static void testPatch2() {
        
       Agency_Info__c tmc= [SELECT Id,Account__r.Qantas_Industry_Centre_ID__c FROM Agency_Info__c limit 1];    
       
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.id = tmc.Id;
        Agencyinfo.Active__c=false;
        
        QAC_TMCInformationParsing requestBody = new QAC_TMCInformationParsing(Agencyinfo);
        reqMethodBody('1000000','PATCH',requestBody);
        test.startTest();
        QAC_TMCOperations.doTMCupdate();
        test.stopTest();
    
    }
    @isTest
    public static void testPatch3() {
        
       Agency_Info__c tmc= [SELECT Id,Account__r.Qantas_Industry_Centre_ID__c FROM Agency_Info__c limit 1];    
       
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.id = tmc.Id;
        Agencyinfo.Active__c=false;
        
        QAC_TMCInformationParsing requestBody = new QAC_TMCInformationParsing(Agencyinfo);
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/QACTMCOperations';  
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(JSON.serializePretty(requestBody));
        //req.requestBody = Blob.valueOf(JSON.serializePretty(myApi));
        
        RestContext.request = req;
        RestContext.response = res;
        
        test.startTest();
        QAC_TMCOperations.doTMCupdate();
        test.stopTest();
    
    }
    @isTest
    public static void testPatch4() {
        
       Agency_Info__c tmc= [SELECT Id,Account__r.Qantas_Industry_Centre_ID__c FROM Agency_Info__c limit 1];    
       
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.id = tmc.Id;
        Agencyinfo.Active__c=false;
        
        QAC_TMCInformationParsing requestBody = new QAC_TMCInformationParsing(Agencyinfo);
        reqMethodBody('','PATCH',requestBody);
        test.startTest();
        QAC_TMCOperations.doTMCupdate();
        test.stopTest();
    
    }
    @isTest
    public static void testPatch5() {
        
       Agency_Info__c tmc= [SELECT Id,Account__r.Qantas_Industry_Centre_ID__c FROM Agency_Info__c limit 1];    
       
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        
        Agencyinfo.Active__c=false;
        
        QAC_TMCInformationParsing requestBody = new QAC_TMCInformationParsing(Agencyinfo);
        reqMethodBody('1000000','PATCH',requestBody);
        test.startTest();
        QAC_TMCOperations.doTMCupdate();
        test.stopTest();
    
    }
    @isTest
    public static void testwithExcepJSON()
    {
        try{
            system.debug('Inside JSON Excep');
            
            Test.startTest();
            QAC_TMCOperations.doTMCRetrieval();
            Test.stopTest();
        }
        catch(Exception myException){
            system.debug('inside exception test'+myException.getTypeName());
        }
    }
    @isTest
    public static void testwithExptJSON()
    {
        try{
            system.debug('Inside JSON Excep');
            
            Test.startTest();
            QAC_TMCOperations.doTMCupdate();
            Test.stopTest();
        }
        catch(Exception myException){
            system.debug('inside exception test'+myException.getTypeName());
        }
    }
    // Testing positive Exceptions
    @isTest
    public static void testException_1() {
        
        Account agencyAccount = [SELECT Id, IATA_Number__c FROM Account WHERE IATA_Number__c = '1000000' LIMIT 1];
        system.debug(' @@ agencyAccount @@ ' + agencyAccount);
        
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.Account__c = agencyAccount.Id;
        Agencyinfo.Active__c=true;
        Agencyinfo.Email_Id__c='test@test.com';
        Agencyinfo.Code__c  ='Galileo';
        Agencyinfo.PCC__c   ='AS2P';
        Agencyinfo.Market_Segment__c ='Corporate';
        
        list<QAC_TMCInformationParsing> requestBody = new list<QAC_TMCInformationParsing>();
        requestBody.add(new QAC_TMCInformationParsing(Agencyinfo));

        
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/QACTMCOperations/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serializePretty(requestBody));
        //req.requestBody = Blob.valueOf(JSON.serializePretty(myApi));
        
        RestContext.request = req;
        RestContext.response = res;
        
        test.startTest();
        QAC_TMCOperations.doTMCInsertion();
        test.stopTest();
    
    }
    
    // Testing Exceptions
    @isTest
    public static void testException_2() {
        
        Account agencyAccount = [SELECT Id, IATA_Number__c FROM Account WHERE IATA_Number__c = '1000000' LIMIT 1];
        system.debug(' @@ agencyAccount @@ ' + agencyAccount);
        
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.Account__c = agencyAccount.Id;
        Agencyinfo.Active__c=true;
        Agencyinfo.Email_Id__c='test@test.com';
        Agencyinfo.Code__c  ='Galileo';
        Agencyinfo.PCC__c   ='AS2P';
        Agencyinfo.Market_Segment__c ='Corporate';
        
        list<QAC_TMCInformationParsing> requestBody = new list<QAC_TMCInformationParsing>();
        requestBody.add(new QAC_TMCInformationParsing(Agencyinfo));

        
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/QACTMCOperations/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serializePretty(requestBody));
        //req.requestBody = Blob.valueOf(JSON.serializePretty(myApi));
        
        RestContext.request = req;
        RestContext.response = res;
        
        test.startTest();
        QAC_TMCOperations.doTMCInsertion();
        test.stopTest();
    
    }
    
    // Testing Exceptions
    @isTest
    public static void testException_3() {
        
        Account agencyAccount = [SELECT Id, IATA_Number__c FROM Account WHERE IATA_Number__c = '1000000' LIMIT 1];
        system.debug(' @@ agencyAccount @@ ' + agencyAccount);
        
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.Account__c = agencyAccount.Id;
        Agencyinfo.Active__c=true;
        Agencyinfo.Email_Id__c='test@test.com';
        Agencyinfo.Code__c  ='Galileo';
        Agencyinfo.PCC__c   ='AS2P';
        Agencyinfo.Market_Segment__c ='Corporate';
        
        list<QAC_TMCInformationParsing> requestBody = new list<QAC_TMCInformationParsing>();
        requestBody.add(new QAC_TMCInformationParsing(Agencyinfo));

        
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/QACTMCOperations/1000001';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serializePretty(requestBody));
        //req.requestBody = Blob.valueOf(JSON.serializePretty(myApi));
        
        RestContext.request = req;
        RestContext.response = res;
        
        test.startTest();
        QAC_TMCOperations.doTMCInsertion();
        test.stopTest();
    
    }
    
    // Testing Exceptions
    @isTest
    public static void testException_4() {
        
        Account agencyAccount = [SELECT Id, IATA_Number__c FROM Account WHERE IATA_Number__c = '1000000' LIMIT 1];
        system.debug(' @@ agencyAccount @@ ' + agencyAccount);
        
        Agency_Info__c Agencyinfo = new Agency_Info__c();
        Agencyinfo.Account__c = agencyAccount.Id;
        Agencyinfo.Active__c=true;
        Agencyinfo.Email_Id__c='test@test.com';
        Agencyinfo.Code__c  ='Galileo';
        Agencyinfo.PCC__c   ='AS2P';
        Agencyinfo.Market_Segment__c ='Corporate';
        
        QAC_TMCInformationParsing requestBody = new QAC_TMCInformationParsing(Agencyinfo);

        reqMethodBody('1000000','POST',requestBody);
        test.startTest();
        QAC_TMCOperations.doTMCInsertion();
        test.stopTest();
    
    }
       
    // Testing positive scenario
    @isTest
    public static void testParse_Retrieval() {
        requestMethod('4364557','GET');
        
        test.startTest();
        QAC_TMCOperations.doTMCRetrieval();
        test.stopTest();
    }
    @isTest
    public static void testRetrieval() {
        requestMethod('1000000','GET');
        test.startTest();
        QAC_TMCOperations.doTMCRetrieval();
        test.stopTest();
    }
    
    // Testing Exceptions
    @isTest
    public static void testException_3_Retrieval() {
        requestMethod('1000001','GET');
        test.startTest();
        QAC_TMCOperations.doTMCRetrieval();
        test.stopTest();
    }
    
    // Testing Exceptions
    @isTest
    public static void testException_4_Retrieval() {
        
        requestMethod('','GET');
        
        test.startTest();
        QAC_TMCOperations.doTMCRetrieval();
        test.stopTest();
    }
    
    public static void requestMethod(String agencyCode,String method)
    {
        system.debug('@@@@insideRequest method');
        RestRequest req = new RestRequest();
        RestResponse res =  new RestResponse();
        
        req.requestURI = '/services/apexrest/QACTMCOperations/'+agencyCode;
        req.httpMethod = method;
        RestContext.request = req;
        RestContext.response = res;
    }
    public static void reqMethodBody(String agencyCode,String method,QAC_TMCInformationParsing requestBody)
    {
        system.debug('@@@@insideRequest method');
        RestRequest req = new RestRequest();
        RestResponse res =  new RestResponse();
        
        req.requestURI = '/services/apexrest/QACTMCOperations/'+agencyCode;
        req.httpMethod = method;
        req.requestBody = Blob.valueOf(JSON.serializePretty(requestBody));
        RestContext.request = req;
        RestContext.response = res;
    }
}