force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AMEX__c.field-meta.xml
<CustomField>
    <fullName>AMEX__c</fullName>
    <defaultValue>false</defaultValue>
    <description>American Express Qantas Co-brand Card</description>
    <inlineHelpText>American Express Qantas Co-brand Card</inlineHelpText>
    <label>AMEX</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_System__c.field-meta.xml
<CustomField>
    <fullName>Aquire_System__c</fullName>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is &quot;Active&quot;.</description>
    <formula>No_of_Aquires__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Agency is a member of the Aquire Program</inlineHelpText>
    <label>Qantas Business Rewards (QBR)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Qantas_Corporate_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Corporate_Identifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Qantas Corporate Identifier</inlineHelpText>
    <label>QCI</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <formula>IF( LeadId != null,Lead.ABN_Tax_Reference__c ,IF(ContactId != null , Contact.Account.ABN_Tax_Reference__c,&apos;&apos;))</formula>
    <label>ABN/Tax Reference</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>HYPERLINK(&quot;https://qantas.my.salesforce.com/&quot;&amp;Contact.Account.Id, Contact.Account.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Assigned_to_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To Track the campaign members assigned to logged-in user</description>
    <label>Assigned to User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Related) Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QL_CampaignMemberDetails.cls
/***********************************************************************************************************************************

Description: Apex controller for Campaign Member List component

History:
======================================================================================================================
Name                    Jira        Description                                                                Tag
======================================================================================================================
Pushkar Purushothaman   CRM-3081    Apex controller for Campaign Member List component                         T01
                                    
Created Date    : 28/04/2018 (DD/MM/YYYY)

**********************************************************************************************************************************/

public class QL_CampaignMemberDetails {
    @AuraEnabled
    public static CampaignMemPagerWrapper fetchCampMembers(String userId,Decimal pageNumber,Integer recordToDisply,String campaignId){
        Integer pageSize = recordToDisply;
        Integer offset = ((Integer)pageNumber - 1) * pageSize;
        Integer countRec=0;
        List<CampaignMember> totCampMem = new List<CampaignMember>();
        List<CampaignMemWrapper> CampMemWrapList = new List<CampaignMemWrapper>();
        Set<Id> accIdSet = new Set<Id>();
        Map<Id,Account> accIdMap = new Map<Id,Account>();
        // create a instance of wrapper class.
        CampaignMemPagerWrapper obj =  new CampaignMemPagerWrapper();
        // set the pageSize,Page(Number), total records and accounts List(using OFFSET)   
        obj.pageSize = pageSize;
        obj.page = (Integer) pageNumber;
        for(CampaignMember cm: [SELECT id,Name,Status,Related_Account__c,Account_Name__c 
                                FROM CampaignMember 
                                WHERE Assigned_to_User__c= :userId
                                AND CampaignId= :campaignId]){
            totCampMem.add(cm);
            if(cm.Related_Account__c != null)
                accIdSet.add(cm.Related_Account__c);
            countRec++;
        }
        for(Account acc : [SELECT Id,Name,ABN_Tax_Reference__c,Qantas_Corporate_Identifier__c,Aquire_System__c,AMEX__c 
                           FROM Account
                           WHERE Id IN :accIdSet]){
            accIdMap.put(acc.Id, acc);           
        }
        obj.total = countRec;      
        
        for(CampaignMember cm : [SELECT id,Name,Status,Related_Account__c,Account_Name__c 
                                 FROM CampaignMember 
                                 WHERE Assigned_to_User__c= :userId 
                                 AND CampaignId= :campaignId 
                                 LIMIT :recordToDisply 
                                 OFFSET :offset]){
            CampaignMemWrapper objInst = new CampaignMemWrapper();
            objInst.CampaignMemURL = System.URL.getSalesforceBaseUrl().toExternalForm()+'/'+cm.id;
            objInst.CampaignMemName = cm.Name;
            objInst.CampaignStatus = cm.Status;   
            
            if(accIdMap.containsKey(cm.Related_Account__c)) {
                objInst.AccountABN = accIdMap.get(cm.Related_Account__c).ABN_Tax_Reference__c;
                objInst.AccountName = accIdMap.get(cm.Related_Account__c).Name;
                objInst.AccountQCI = accIdMap.get(cm.Related_Account__c).Qantas_Corporate_Identifier__c;
                objInst.AccountQBR = (accIdMap.get(cm.Related_Account__c).Aquire_System__c)?'Yes':'No';
                objInst.AMEX = (accIdMap.get(cm.Related_Account__c).AMEX__c)?'Yes':'No';
                objInst.AccountURL = System.URL.getSalesforceBaseUrl().toExternalForm()+'/'+cm.Related_Account__c;
            }                        
            
            CampMemWrapList.add(objInst);    
        }
        obj.totalCampMems = CampMemWrapList;
        // return the wrapper class instance .
        return obj;
    }
    
        
    public class CampaignMemPagerWrapper {
        @AuraEnabled public Integer pageSize {get;set;}
        @AuraEnabled public Integer page {get;set;}
        @AuraEnabled public Integer total {get;set;}
        @AuraEnabled public List<CampaignMemWrapper> campMems {get;set;}
        @AuraEnabled public List<CampaignMemWrapper> totalCampMems {get;set;}
    }
    
    public class CampaignMemWrapper {
        @AuraEnabled public String CampaignMemName {get;set;}
        @AuraEnabled public String CampaignMemURL {get;set;}
        @AuraEnabled public String CampaignStatus {get;set;}
        @AuraEnabled public String AccountName {get;set;}
        @AuraEnabled public String AccountABN {get;set;}
        @AuraEnabled public String AccountQCI {get;set;}
        @AuraEnabled public String AccountQBR {get;set;}
        @AuraEnabled public String AMEX {get;set;}
        @AuraEnabled public String AccountURL {get;set;}
    }
}