force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <description>QAC - This field is used to Store ABN number which is coming from Agency Account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Used on CL Renewal Cases to capture the location of the Chairman Lounge member (his/her Home port)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Procurement/Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agency Manager</fullName>
            </value>
            <value>
                <fullName>Agency Owner</fullName>
            </value>
            <value>
                <fullName>Ambassador / High Commissioner</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager - Agency</fullName>
            </value>
            <value>
                <fullName>Business Development Manager – Corporate</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chancellor</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Charter Key Contact</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of Business Unit</fullName>
            </value>
            <value>
                <fullName>Chief of Finance</fullName>
            </value>
            <value>
                <fullName>Chief of Organisation</fullName>
            </value>
            <value>
                <fullName>Chief of Procurement</fullName>
            </value>
            <value>
                <fullName>Chief of the Organisation</fullName>
            </value>
            <value>
                <fullName>Commercial Director</fullName>
            </value>
            <value>
                <fullName>Commerical Partner Contact</fullName>
            </value>
            <value>
                <fullName>Consultant/agent</fullName>
            </value>
            <value>
                <fullName>Consultant/agent - Senior</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Assistant</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Executive Team Member (non Finance)</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Head of Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Key Traveller</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Description__c.field-meta.xml
<CustomField>
    <fullName>Config_Description__c</fullName>
    <description>Apex class in which it is used and key notes on the value</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Value__c.field-meta.xml
<CustomField>
    <fullName>Config_Value__c</fullName>
    <description>Text values used in the code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Queue Members location (manila , Sydney , ..)</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manila</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Hobart</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Capetown</fullName>
            </value>
            <value>
                <fullName>Suva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QCCCloneEmailMessagesWithAttachmentsTest.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Pradnya Unde
Company:       TCS
Description:   Test class for QCCCloneEmailMessagesWithAttachments--Jira CRM-5051
-----------------------------------------------------------------------------------------------------------------------*/
@isTest
public class QCCCloneEmailMessagesWithAttachmentsTest {
    @testSetup
    static void setup() {
        Test.startTest();
        //List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.enableTriggers();
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        List<Trigger_Status__c> customSettingList1 = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusCase', null, null, null, null);
        insert customSettingList1;
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createEmailMessageTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContentdocumentLinkTriggerSetting());
        
        insert lsttrgStatus;
        TestUtilityDataClassQantas.insertQantasConfigData();
        QantasConfigData__c qc = new QantasConfigData__c();
        qc.Name = 'Log Exception Logs Rec Type';
        qc.Config_Value__c = 'Exception Logs';
        qc.Config_Description__c = 'Log Exception Logs Record Type Name';
        insert qc;
        //(User Story: QSFR-23) START
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('QCC_DamagedBaggageHighQueue','CCC_R1_Damaged_Baggage_Q'));
        insert lstConfigData;
        //(User Story: QSFR-23) END
        //TestUtilityDataClassQantas.insertQantasConfigData();
        Map<String, Profile> profMap = TestUtilityDataClassQantas.getProfileMap();

        List<User> testUsers = new List<User>();
        // Replacing the Run as user profile with QCC Contact Center Agent profile and adding QCC Base,Contact Center and Genesys permission sets on the user as part of RBAC CRM-11628
        User u1 = new User(LastName = 'User1', Alias = 'User', Email = 'sampleuser1@sample.com',
                           Username = 'sampleuser1username@sample.com', ProfileId = profMap.get('QCC Contact Center Agent Hobart').Id,
                           EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_AU',Location__c='Hobart',
                           TimeZoneSidKey = 'Australia/Sydney'
                           );
        testUsers.add(u1);
        insert testUsers;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            List<Id> permissionSetIds = TestUtilityDataClassQantas.getPermissionSetIds('QCC_Base_User_Permissions,QCC_Contact_Center_Agent_Permissions,QCC_Genesys_User_Permissions');
            List<PermissionSetAssignment> psaList = TestUtilityDataClassQantas.createPermissionSetAssignments(u1.Id,permissionSetIds);
        }

        System.runAs(u1){
            Account acc        = TestUtilityDataClassQantas.createAccountOfQantasCorporateEmailAccount();
            acc.ABN_Tax_Reference__c = '11111111111';
            insert acc;
            System.debug('ZZZ in EmailMessageTriggerHelperTest testsetup acc: '+acc);
            Contact con        = TestUtilityDataClassQantas.createContact(acc.Id);
            con.Business_Types__c = 'Agency';
            con.Job_Role__c       = 'Other';
            con.Function__c       = 'Other';
            con.Frequent_Flyer_Tier__c = 'Bronze';
            con.Frequent_Flyer_Number__c = '12345';
            insert con;
            con.AccountId         = acc.id;
            update con;
            System.debug('ZZZ in EmailMessageTriggerHelperTest testsetup con: '+con);
            System.debug('ZZZ in EmailMessageTriggerHelperTest testsetup con Acc Name: '+con.Account.Name);
            Case newcase1      = TestUtilityDataClassQantas.createCaseWithCodingValues('CCC Complaints','Complaint','Departure Airport','Announcements','General','');
            newcase1.ContactId = con.id;
            newcase1.Origin    = 'Phone';
            insert newcase1;
            


            Case newchildcase1      = TestUtilityDataClassQantas.createCaseWithCodingValues('CCC Complaints','Complaint','Departure Airport','Announcements','General','');
            newchildcase1.ContactId = con.id;
            newchildcase1.Origin    = 'Email';
            newchildcase1.ParentId    = newcase1.Id;
            //insert newchildcase1;
        }
        Test.stopTest();
    }

    static testMethod void testCreateEmailMessagesWithAttachments() { 
        User u1 = [Select Id, Username from User where Username = 'sampleuser1username@sample.com'];
        System.debug('userid = '+u1.Id);
        Account acct = [SELECT Id,Name FROM Account WHERE Name='QantasCorporateEmailAccount' LIMIT 1];
        Contact cont = [Select Id,Name,Email,AccountId From Contact Where Account.Name ='QantasCorporateEmailAccount' Limit 1];
        Case ncase   = [Select Id,CaseNumber,ContactId, RecordTypeId, Type, Group__c, Cabin_Class__c, OwnerId From Case where ContactId=: cont.id Limit 1];
        ncase.Type   = 'Baggage';
        ncase.Group__c = 'Delayed Baggage';
        ncase.Cabin_Class__c = 'Economy';
        ncase.RecordTypeId = GenericUtils.getObjectRecordTypeId('Case', CustomSettingsUtilities.getConfigDataMap('Case Baggage RecType'));
        System.debug('case owner = '+ncase.OwnerId);
        ncase.OwnerId = u1.Id;
        ncase.Auto_Close_on_Email_Sent__c = true;
        update ncase;

        ContentVersion objContVersion = new ContentVersion(Title = 'EmailAttachment',  PathOnClient = 'EmailAttachment.pdf', 
                                                           VersionData = Blob.valueOf('Email Attachment Content'), IsMajorVersion = true);
        insert objContVersion; 
        
        List<ContentDocument> objCOnDoc = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
                
        EmailMessage emIn   = new EmailMessage(); 
        emIn.Incoming       = true;
        emIn.FromAddress    = cont.Email;
        emIn.ToAddress      = CustomSettingsUtilities.getConfigDataMap('Qantas Customer Care Email');
        emIn.Subject        = 'Qantas Customer Care';
        emIn.HtmlBody       = '<br/><h1>Hello!!</h1>';
        emIn.Status         = '3';
        emIn.ParentId       = ncase.id;  
        emIn.QCC_Has_Attachment__c = true;
        insert emIn;    
        //create ContentDocumentLink  record 
        ContentDocumentLink objCDL = New ContentDocumentLink();
        objCDL.LinkedEntityId =  emIn.Id;
        objCDL.ContentDocumentId = objCOnDoc[0].Id;
        objCDL.shareType = 'V';
        insert objCDL;
        
        List<EmailMessage> emlist = new List<EmailMessage>();
        emlist.add(emIn);
        Test.startTest();
            List<QCCCloneEmailMessagesWithAttachments.inputWrapper> inputs = new List<QCCCloneEmailMessagesWithAttachments.inputWrapper>();
            QCCCloneEmailMessagesWithAttachments.inputWrapper iw = new QCCCloneEmailMessagesWithAttachments.inputWrapper();
            iw.parentCaseId = ncase.Id;
        	iw.childCaseId = ncase.Id;
            iw.parentCaseEmailMsgs = emlist;            
            iw.isFromEmailReplyReceived = true;
            inputs.add(iw);
            QCCCloneEmailMessagesWithAttachments.createEmailMessagesWithAttachments(inputs);
        
       		inputs = new List<QCCCloneEmailMessagesWithAttachments.inputWrapper>();
            iw = new QCCCloneEmailMessagesWithAttachments.inputWrapper();
            iw.parentCaseId = ncase.Id;
        	iw.childCaseId = ncase.Id;
            iw.parentCaseEmailMsgs = emlist;            
            iw.isFromEmailReplyReceived = false;
            inputs.add(iw);
            QCCCloneEmailMessagesWithAttachments.createEmailMessagesWithAttachments(inputs);
        Test.stopTest();
        List<emailmessage> emailMsgs = [SELECT ID, IsAsyncLogic__c, ValidatedFromAddress FROM EmailMessage];
        System.assertEquals(emailMsgs[0].IsAsyncLogic__c, true);
        System.assertEquals(emailMsgs[0].ValidatedFromAddress, 'test1contact@duptest.com');

    }
    
    
    static testMethod void testCreateEmailMessagesWithAttachments2() { 
        User u1 = [Select Id, Username from User where Username = 'sampleuser1username@sample.com'];
        System.debug('userid = '+u1.Id);
        Account acct = [SELECT Id,Name FROM Account WHERE Name='QantasCorporateEmailAccount' LIMIT 1];
        Contact cont = [Select Id,Name,Email,AccountId From Contact Where Account.Name ='QantasCorporateEmailAccount' Limit 1];
        Case ncase   = [Select Id,CaseNumber,ContactId, RecordTypeId, Type, Group__c, Cabin_Class__c, OwnerId From Case where ContactId=: cont.id Limit 1];
        ncase.Type   = 'Baggage';
        ncase.Group__c = 'Delayed Baggage';
        ncase.Cabin_Class__c = 'Economy';
        ncase.RecordTypeId = GenericUtils.getObjectRecordTypeId('Case', CustomSettingsUtilities.getConfigDataMap('Case Baggage RecType'));
        System.debug('case owner = '+ncase.OwnerId);
        ncase.OwnerId = u1.Id;
        ncase.Auto_Close_on_Email_Sent__c = true;
        update ncase;

        ContentVersion objContVersion = new ContentVersion(Title = 'EmailAttachment',  PathOnClient = 'EmailAttachment.pdf', 
                                                           VersionData = Blob.valueOf('Email Attachment Content'), IsMajorVersion = true);
        insert objContVersion; 
        
        List<ContentDocument> objCOnDoc = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
                
        EmailMessage emIn   = new EmailMessage(); 
        emIn.Incoming       = true;
        emIn.FromAddress    = cont.Email;
        emIn.ToAddress      = CustomSettingsUtilities.getConfigDataMap('Qantas Customer Care Email');
        emIn.Subject        = 'Qantas Customer Care 1';
        emIn.HtmlBody       = '<br/><h1>Hello!!</h1>';
        emIn.Status         = '3';
        emIn.ParentId       = ncase.id;  
        emIn.QCC_Has_Attachment__c = true;
        insert emIn;    
        //create ContentDocumentLink  record 
        ContentDocumentLink objCDL = New ContentDocumentLink();
        objCDL.LinkedEntityId =  emIn.Id;
        objCDL.ContentDocumentId = objCOnDoc[0].Id;
        objCDL.shareType = 'V';
        insert objCDL;
        
        EmailMessage emIn2   = new EmailMessage(); 
        emIn2.Incoming       = true;
        emIn2.FromAddress    = cont.Email;
        emIn2.ToAddress      = CustomSettingsUtilities.getConfigDataMap('Qantas Customer Care Email');
        emIn2.Subject        = 'Qantas Customer Care 2';
        emIn2.HtmlBody       = '<br/><h1>Hello!!</h1>';
        emIn2.Status         = '3';  
        emIn2.QCC_Has_Attachment__c = true;
        //insert emIn2;  
        List<EmailMessage> lst2 = new List<EmailMessage>();
        lst2.add(emIn2);

        Test.startTest();
        
        	QCCCloneEmailMessagesWithAttachments.createChildContentDocumentLinks(emIn.Id, JSON.serialize(lst2), true);
        Test.stopTest();
        
    }

}