force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire__c.field-meta.xml
<CustomField>
    <fullName>Aquire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is either &quot;Active&quot; or &quot;Pending&quot;.</description>
    <inlineHelpText>Agency is a member of the Qantas Business Rewards Program</inlineHelpText>
    <label>QBR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Air_Travel_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Air_Travel_Spend__c</fullName>
    <inlineHelpText>Used to capture the total estimated air travel spend (AUD) of the account - this field is either populated via Aquire/QBD product registration or is to be manually captured/updated by the Account Manager/Team. This is used to drive the account assignment.</inlineHelpText>
    <label>Estimated Total Air Travel Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/IATA_Number__c.field-meta.xml
<CustomField>
    <fullName>IATA_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IATA #</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Value__c.field-meta.xml
<CustomField>
    <fullName>Config_Value__c</fullName>
    <description>Text values used in the code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QAC_AgencySecondaryDetailsUpdate_Test.cls
/* 
* Created By : Ajay | TCS | Cloud Developer 
* Purpose : Test the main class 
* Main Class : QAC_AgencySecondaryDetailsUpdate
*/

@IsTest
public class QAC_AgencySecondaryDetailsUpdate_Test {

    public static String[] getURLIATAs(){
        String[] myJson = new String[]{'1000001','10101',''};
        return myJson;
    }    

    @testSetup
    public static void setup() {
        
        system.debug('inside test setup**');
        String agencyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency Account').getRecordTypeId();
        
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createCaseTriggerSetting();
        insert lsttrgStatus;
        TestUtilityDataClassQantas.insertQantasConfigData();
        
        QantasConfigData__c qcd = new QantasConfigData__c(Name = 'Log Integration Logs Rec Type',Config_Value__c = 'Integration Logs');
        insert qcd;
        
        QantasConfigData__c qcd2 = new QantasConfigData__c(Name = 'Log Exception Logs Rec Type',Config_Value__c = 'Exception Logs');
        insert qcd2;
        
        //Inserting Account
        Account acc = new Account(Name = 'Sample', Active__c = true, Aquire__c = true, Type = 'Agency Account', 
                                  RecordTypeId = agencyRecordTypeId, Migrated__c = true, ABN_Tax_Reference__c  ='34563565365',
                                  Estimated_Total_Air_Travel_Spend__c = 0,IATA_Number__c = '1000001');
        insert acc;
    }
    
    // success scenario
    @isTest
    public static void validIATA()
    {
        //System.debug('API values'+myApi);
        QAC_AgencySecondaryParsing myApi = QAC_AgencySecondaryParsing_Test.testParse();
        QAC_AgencySecondaryDetailsUpdate_Test.restLogic(myApi,null,QAC_AgencySecondaryDetailsUpdate_Test.getURLIATAs()[0]);
        
        Test.startTest();
        QAC_AgencySecondaryDetailsUpdate.doSecondaryUpdate();
        Test.stopTest();
    }
    
    // failure scenario
    @isTest
    public static void invalidIATA()
    {
        //System.debug('API values'+myApi);
        QAC_AgencySecondaryParsing myApi = QAC_AgencySecondaryParsing_Test.testParse();
        QAC_AgencySecondaryDetailsUpdate_Test.restLogic(myApi,null,QAC_AgencySecondaryDetailsUpdate_Test.getURLIATAs()[1]);
        
        Test.startTest();
        QAC_AgencySecondaryDetailsUpdate.doSecondaryUpdate();
        Test.stopTest();
    }
    
    // null scenario
    @isTest
    public static void blankIATA()
    {
        //System.debug('API values'+myApi);
        QAC_AgencySecondaryParsing myApi = QAC_AgencySecondaryParsing_Test.testParse();
        QAC_AgencySecondaryDetailsUpdate_Test.restLogic(myApi,null,QAC_AgencySecondaryDetailsUpdate_Test.getURLIATAs()[2]);
        
        Test.startTest();
        QAC_AgencySecondaryDetailsUpdate.doSecondaryUpdate();
        Test.stopTest();
    }
    
    @isTest
    public static void testwithExcepJSON()
    {
        try{
            system.debug('Inside JSON Excep');
            String myExcepJson = '';
            QAC_AgencySecondaryDetailsUpdate_Test.restLogic(null,myExcepJson,QAC_AgencySecondaryDetailsUpdate_Test.getURLIATAs()[0]);
            
            Test.startTest();
            QAC_AgencySecondaryDetailsUpdate.doSecondaryUpdate();
            Test.stopTest();
        }
        catch(Exception myException){
            system.debug('inside exception test'+myException.getTypeName());
        }
        
    }
    
    public static void restLogic(QAC_AgencySecondaryParsing theApi, String theExcepJson, String myURL){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/QACAgencySecondaryInfo/'+myURL;  
        req.httpMethod = 'POST';
        req.requestBody = (theApi != null) ? Blob.valueOf(JSON.serializePretty(theApi)) : (theExcepJson != null) ? Blob.valueOf(theExcepJson) : null ;
        //req.requestBody = Blob.valueOf(JSON.serializePretty(myApi));
        
        RestContext.request = req;
        RestContext.response = res;
    }  
}