force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_of_Aquires__c.field-meta.xml
<CustomField>
    <fullName>No_of_Aquires__c</fullName>
    <label>No of QBRs [System]</label>
    <summaryFilterItems>
        <field>Product_Registration__c.Stage_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Product_Registration__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Product_Registration__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Aquire Registration</value>
    </summaryFilterItems>
    <summaryForeignKey>Product_Registration__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/Product_Registration__c.object-meta.xml
<CustomObject>
    <description>To be used to capture details for different product registrations like Aquire and AMEX.</description>
    <label>Product Registration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AEQCC</fullName>
            </value>
            <value>
                <fullName>Aquire</fullName>
            </value>
            <value>
                <fullName>QBD</fullName>
            </value>
            <value>
                <fullName>AQBRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/CreateQBRAPITest.cls
/*==================================================================================================================================
Author:         Benazir Amir/Praveen Sampath
Company:        Capgemini
Purpose:        Test Class for CreateQBRAPI Class
Date:           28/04/2017        
History:

==================================================================================================================================

==================================================================================================================================*/

@isTest(SeeAllData = false)
private class CreateQBRAPITest{

	@testSetup
    static void createTestData(){
    	

    	List<user> lstUserUpdate = new List<User>();
        List<User> lstUser = TestUtilityDataClassQantas.getUsers('Data Administrator', 'MAS Team', 'QF-DOM-Sales-SME-QIS-Operations');
        system.assert(lstUser[0].Id != Null, 'User list is not Inserted');
        system.assert(lstUser.size()==2, 'List size is small');

        User objUser = lstUser[0];
        objUser.Id = lstUser[0].Id;
        objUser.IsActive = true;
        objUser.Email = 'test@QIs.com';
        lstUserUpdate.add(objUser);
        
        update lstUserUpdate;
        User objActiveUser = [select Id, UserRoleId from User where Id =: objUser.Id ];
        system.assert(objActiveUser.UserRoleId != Null, 'User Role is Null');

        system.runAs(objActiveUser){
        	List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSetting();
	        lsttrgStatus.addAll(TestUtilityDataClassQantas.createProductRegTriggerSetting());
	        insert lsttrgStatus;
			
			List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
			lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Rec Type', 'Aquire Registration'));
            lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg AEQCC Registration Rec Type','AEQCC Registration'));
	        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
	        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Integration Logs Rec Type','Integration Logs'));
	        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('createIntegrationLogQBRAPI','Yes'));
	        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Status','Active'));
            insert lstConfigData;
	        Account objAcc = TestUtilityDataClassQantas.createAccount();
			objAcc.ABN_Tax_Reference__c = '99999999999';
			insert objAcc;
			system.assert(objAcc.Id != Null, 'Account is not inserted');

			Product_Registration__c objQBDProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'AEQCC');
			insert objQBDProdReg;
			Product_Registration__c amexProduct = [ Select Id,Type__c, Active__c from Product_Registration__c where Id =: objQBDProdReg.Id];
			system.assert(amexProduct.Type__c == 'AEQCC' , 'Amex Product Registration is not Inserted');
			system.assert(amexProduct.Active__c == true , 'Amex Product Registration is not Inserted');
		}
    }

    static TestMethod void CreateQBRProductTest(){
		
		Product_Registration__c amexProduct = [ Select Id from Product_Registration__c where Type__c = 'AEQCC'];
		User testUsr = [select Id from User where Email = 'test@QIs.com' LIMIT 1];
		Test.startTest();
       
        List<QBRProductRegWrapper> lstprodRegistrations = new list<QBRProductRegWrapper>();
        QBRProductRegWrapper qbrWrapper = new QBRProductRegWrapper();

        qbrWrapper.enrolmentStatusCode = 'S00';
        qbrWrapper.amexProductId = amexProduct.Id;
        qbrWrapper.enrolmentStatusDescription = 'Success!!!!';

        QBRProductRegWrapper.QBRProduct qbrInfos = new QBRProductRegWrapper.QBRProduct();
        qbrInfos.membershipNumber = '779922';
        qbrInfos.membershipStatus = 'Active';
        qbrInfos.membershipStartDate = System.today();
        qbrInfos.membershipEndDate = null;
        qbrInfos.companyIndustry = 'Manufacturing';
		qbrInfos.companyAirlineLevel = '1';
		qbrInfos.companyGSTRegistered = 'Y';
		qbrInfos.companyEntityType = 'Australian Public Company';

		qbrWrapper.qbrInfo = qbrInfos;
        
        lstprodRegistrations.add(qbrWrapper);

        system.runAs(testUsr){
	        CreateQBRAPI.create(lstprodRegistrations);
	    }
	    Test.stopTest();

	    List<Account> lstAcc = [Select Id,No_of_Aquires__c from Account LIMIT 1];
	    system.assert(lstAcc.size() == 1 , 'Account is not fetched');
	    system.assert(lstAcc[0].No_of_Aquires__c == 1 , 'QBR Product Registration is not Inserted');
	}

	static TestMethod void CreateQBRExceptionTest(){
		Test.startTest();
        List<QBRProductRegWrapper> lstprodRegistrations = new list<QBRProductRegWrapper>();
        QBRProductRegWrapper qbrWrapper = new QBRProductRegWrapper();

        lstprodRegistrations.add(qbrWrapper);
        CreateQBRAPI.create(lstprodRegistrations);
	    Test.stopTest();

        List<Log__c> lstLog = [select Id from Log__c];
	    system.assert(lstLog.size() != 0, 'Log record is not Inserted');
	}


}