force-app/main/default/objects/Account/fields/ABN_Tax_Reference__c.field-meta.xml
<CustomField>
    <fullName>ABN_Tax_Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Record the ABN/Tax Reference Number with no spaces.</inlineHelpText>
    <label>ABN / Tax Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ABTA_Number__c.field-meta.xml
<CustomField>
    <fullName>ABTA_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Applicable only for UK &amp; Ireland Accounts</inlineHelpText>
    <label>ABTA Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Agency_Sales_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Sales Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Region__c.sales_h_eq_type__c</field>
            <operation>equals</operation>
            <value>Corporate-Industry, Industry</value>
        </filterItems>
        <filterItems>
            <field>Sales_Region__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>The Brand value and associated Brand Code comes from the Sales Region master list. For the value to appear as a selectable it must be added to the Sales Region list first.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Agency Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Sub_Chain__c.field-meta.xml
<CustomField>
    <fullName>Agency_Sub_Chain__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Agency Sub Chain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ATAS__c.field-meta.xml
<CustomField>
    <fullName>ATAS__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the agencies AFTA Travel Accreditation Scheme Number</inlineHelpText>
    <label>ATAS Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ATOL_Number__c.field-meta.xml
<CustomField>
    <fullName>ATOL_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Applicable only for UK &amp; Ireland Accounts</inlineHelpText>
    <label>ATOL Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <inlineHelpText>Freight: Please select relevant business type
Corporate:
Prospect - Corporate account not on a deal
Customer - Corporate account on a deal
Agency - An Industry Account</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Leisure</fullName>
            </value>
            <value>
                <fullName>Leisure &amp; Corporate</fullName>
            </value>
            <value>
                <fullName>Consolidator</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Share of Business</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
            <value>
                <fullName>Commercial Partner</fullName>
            </value>
            <value>
                <fullName>ITO - Inbound Tour Operator</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Customer Prospect</fullName>
            </value>
            <value>
                <fullName>Agency Prospect</fullName>
            </value>
            <value>
                <fullName>Online Travel Agent (OTA)</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Tourism</fullName>
            </value>
            <value>
                <fullName>Freight Forwarder</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Partner Airline</fullName>
            </value>
            <value>
                <fullName>GSA</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Aggregator</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Mobile Developer</fullName>
            </value>
            <value>
                <fullName>Online Booking Tool</fullName>
            </value>
            <value>
                <fullName>Travel Management Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Member__c.field-meta.xml
<CustomField>
    <fullName>Channel_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Channel Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Generic Company Email</inlineHelpText>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Date__c</fullName>
    <description>TS-4725 : Save maintenance date in SF for Agency Accounts</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agency : The date when the agency manager reviewed and confirmed the agency contact details online.</inlineHelpText>
    <label>Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Phone_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone Country Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QAC_Request_Pending__c.field-meta.xml
<CustomField>
    <fullName>QAC_Request_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Pending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Qantas_Industry_Centre_ID__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Industry_Centre_ID__c</fullName>
    <description>Unique Field after CRM-1340 is resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Qantas Industry Centre Identifier</inlineHelpText>
    <label>QIC ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Tradesite__c.field-meta.xml
<CustomField>
    <fullName>Tradesite__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Mark if the agent is a register user of the Industry Sales Site</inlineHelpText>
    <label>Tradesite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <description>Created as a result of SFDC and iDeal integration.</description>
    <label>Sales Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Region__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Active flag based on End Date</description>
    <formula>OR(Today() &lt; sales_h_end_date__c, ISNULL(sales_h_end_date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Brand Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agency : Email address which the report will be sent to. Separate multiple email addresses using the semicolon character &quot;;&quot;</inlineHelpText>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Hide_TMCTA__c.field-meta.xml
<CustomField>
    <fullName>Hide_TMCTA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To show/hide on the Website</description>
    <label>Hide TMCTA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QAC_AgencyAccountRetrieval.cls
/*
Purpose : Response class for Account Primary & Secondary Retrieval to My Agency Profile
Developed By : 
Yuvraj :        For My Agency profile response
Ajay :          For including channel response for Channel Retrieval
Main Class :    QAC_AcctRetrievalUsingIATA

Modified Date   : 23/08/19 (DD/MM/YYYY)
Modified By     : Vinothkumar Balasubramanian
JIRA            : TS-4725
Version         : V2.0 - Added new field "Maintenance Date"

Modified Date   : 18/09/19 (DD/MM/YYYY)
Modified By     : Vinothkumar Balasubramanian
JIRA            : TS-4810
Version         : V3.0 - Add agencyBrandCode

*/

global class QAC_AgencyAccountRetrieval 
{
    global AgencyPrimaryDetails agencyPrimaryDetails;
    global AgencySecondaryDetails agencySecondaryDetails;
    
    public class AgencyPrimaryDetails 
    {
        public String agencyTradingName;
        public String agencyCode;
        public String agencyABN;
        public String agencyChain;
        public String agencySubChain;
        public Boolean isManualRequestPending;
        public Boolean active;
        public Boolean hideTa;
        //New Changes JIRA:TS-4810
        public String agencyBrandCode;
        //Changes ends JIRA:TS-4810
        public AgencyPrimaryDetails(Account theAccount)
        {
            agencyTradingName = theAccount.Name;
            agencyCode = theAccount.Qantas_Industry_Centre_ID__c;
            agencyABN = theAccount.ABN_Tax_Reference__c;
            agencyChain = theAccount.Agency_Sales_Region__r.Name;
            agencySubChain = theAccount.Agency_Sub_Chain__c;
            isManualRequestPending = theAccount.QAC_Request_Pending__c;
            active = theAccount.Active__c;
            hideTa = theAccount.Agency_Sales_Region__r.Hide_TMCTA__c;
            //New Changes JIRA:TS-4810
            if(theAccount.Agency_Sales_Region__c != null){
                
                if (theAccount.BillingCountryCode == 'AU')
                    agencyBrandCode = theAccount.Agency_Sales_Region__r.Brand_Code__c;
                else
                    agencyBrandCode = theAccount.BillingCountryCode;
            }
            else
                agencyBrandCode = theAccount.BillingCountryCode;
            //Changes ends JIRA:TS-4810
        }
    }
    
    public class AgencySecondaryDetails 
    {
        public String primaryAgencyBusiness;
        public String agencyAddressLine1;
        public String city;
        public String stateCode;
        public String countryCode;
        public String postalCode;
        public String phoneNumber;
        public String employees;
        public String accountEmail;
        public String atasNumber;
        public String abtaNumber;
        public String atolNumber;
        public String agencyWebsite;
        public string dialCode;
        public date maintenanceDate;  //New Change JIRA:TS-4725 : Add Maintenance Date
        
        // included for Channel Retrieval new fields 
        // JIRA: TS - 4223 
        public Boolean tradesite;
        public Boolean channelStatus;
        public Set<String> associatedGdsList;
        
        public AgencySecondaryDetails(Account theAccount, Set<String> gdsValues)
        {
            associatedGdsList = gdsValues;
            channelStatus = theAccount.Channel_Member__c;
            tradesite = theAccount.Tradesite__c;
            String regExp = '[\\-\\+\\.\\^:\\(\\),]';
            String replaceExp = '';
            String dialingCode;
            string phone;
            
            if(string.isNotBlank(theAccount.Phone_Country_Code__c))
            {
                dialingCode = theAccount.Phone_Country_Code__c.replaceall(regExp,replaceExp);
                dialingCode = dialingCode.replace(' ', replaceExp); 
            }
            
            if(string.isNotBlank(theAccount.Phone_Number__c))
            {
                phone = theAccount.Phone_Number__c.replaceall(regExp,replaceExp);
                phone = phone.replace(' ', replaceExp); 
            }
            
            //Uncomment the below code in order to revert
            /**if((string.isNotBlank(dialingCode) || string.isNotEmpty(dialingCode)) && (string.isNotBlank(phone) || string.isNotEmpty(phone)))
{
phoneNumber = '+' + dialingCode + phone;
}
else if(string.isEmpty(dialingCode) && string.isNotEmpty(phone))
{
phoneNumber = phone;
}**/
            
            if(string.isNotBlank(dialingCode) && string.isNotEmpty(dialingCode))
                dialCode = '+' + dialingCode;
            if(string.isNotBlank(phone) && string.isNotEmpty(phone))
                phoneNumber = phone;
            
            primaryAgencyBusiness = theAccount.Business_Type__c;
            agencyAddressLine1 = theAccount.BillingStreet;
            city = theAccount.BillingCity;
            stateCode = theAccount.BillingState;
            countryCode = theAccount.BillingCountryCode;
            postalCode = theAccount.BillingPostalCode;
            employees = String.valueOf(theAccount.NumberOfEmployees);
            accountEmail = theAccount.Email__c;
            atasNumber = theAccount.ATAS__c;
            atolNumber = theAccount.ATOL_Number__c;
            abtaNumber = theAccount.ABTA_Number__c;
            agencyWebSite = theAccount.Website;
            maintenanceDate = theAccount.Maintenance_Date__c; //New Change JIRA:TS-4725 : Add Maintenance Date
            
        }
    }
}