force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <inlineHelpText>Prospect - Corporate Account not on a deal, Customer - Corporate account on a deal and Agency - An Industry Account</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Industry (agency)</fullName>
            </value>
            <value>
                <fullName>Corporate (customer)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Customer Account airline level calculated by and received from iFly (Aquire)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account airline level as set by Aquire</inlineHelpText>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <formula>Account.Airline_Level__c</formula>
    <label>Airline Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Used on CL Renewal Cases to capture the location of the Chairman Lounge member (his/her Home port)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CAP_ID__c.field-meta.xml
<CustomField>
    <fullName>CAP_ID__c</fullName>
    <description>Contact CAP ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>QCC: Used to store the Account Type of the Bank Account for EFT refunds</description>
    <inlineHelpText>Required for bank accounts in USA/South America and South Africa</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <description>QCC: Used to store the name of the Bank Account that is having funds deposited for EFT refund recoveries</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>QCC: Used to store the bank account number for EFT refund recoveries</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Alphanumeric characters only i.e. must not contain dashes, slashes, spaces, etc.</inlineHelpText>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>QCC: Used to store the name of the bank for EFT refunds given as a recovery</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Name of Financial Institution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>QCC: Used to store the name of the bank branch for EFT refunds as recovery</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Branch_Number_BSB_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Number_BSB_Sort_Code__c</fullName>
    <description>QCC: Used to store the Branch Identification number for EFT recoveries</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Alphanumeric characters only i.e. must not contain dashes, slashes, spaces, etc.</inlineHelpText>
    <label>Branch Number(BSB/SortCode/Routing Code)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Branch_Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Party_Id__c</fullName>
    <description>QCC: Used to store the Bank Branch Party Id for EFT Refunds</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Party Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Branch_Swift_BIC_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Swift_BIC_Code__c</fullName>
    <description>Used to store the Branch Swift/BIC code for EFT refunds</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Required for foreign payments</inlineHelpText>
    <label>Branch Swift / BIC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>QCC: Used to store the abbreviated form of the POS refund country</description>
    <formula>LEFT(TEXT(Refund_POS_Country__c), 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>QCC; Used to store the International Bank Account Number (IBAN) value which is converted from the Account Number for certain countries.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Required for bank accounts in UK/Europe</inlineHelpText>
    <label>IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Invoice_Claim_Description__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Claim_Description__c</fullName>
    <description>QCC: Used to store a description for finance about the claim/invoice for EFT/Credit Card refunds. Shorter than regular description so it is contained within finance system</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice/Claim Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Monetary_Value__c.field-meta.xml
<CustomField>
    <fullName>Monetary_Value__c</fullName>
    <description>QCC: Used to track the monetary value of the payment in any currency</description>
    <inlineHelpText>Credit card - Must be AUD equivalent.
EFT - Must be currency of country of bank</inlineHelpText>
    <label>Monetary Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/TAX_Id_VAT_Reg_No__c.field-meta.xml
<CustomField>
    <fullName>TAX_Id_VAT_Reg_No__c</fullName>
    <description>QCC: Used to store the TAX Id or VAT registration number for EFT Refunds</description>
    <encryptionScheme>None</encryptionScheme>
    <label>TAX Id / VAT Reg No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>QCC: Created to show/store Type of goodwill given to customer.</description>
    <label>Recovery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qantas Points</fullName>
            </value>
            <value>
                <fullName>Payment (EFT)</fullName>
            </value>
            <value>
                <fullName>Payment (Credit Card)</fullName>
            </value>
            <value>
                <fullName>Travel vouchers</fullName>
                <label>Travel Vouchers</label>
            </value>
            <value>
                <fullName>Lounge Passes</fullName>
            </value>
            <value>
                <fullName>Bag Replacement</fullName>
            </value>
            <value>
                <fullName>Bag Repair</fullName>
            </value>
            <value>
                <fullName>No Goodwill</fullName>
            </value>
            <value>
                <fullName>Ticket Refund EFT</fullName>
            </value>
            <value>
                <fullName>Cover Refund</fullName>
            </value>
            <value>
                <fullName>First Lounge Pass</fullName>
                <label>First Lounge Pass (CCAT Only)</label>
            </value>
            <value>
                <fullName>Space available upgrade</fullName>
                <label>Space Available Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>Firm space upgrade</fullName>
                <label>Firm Space Upgrade (CCAT Only)</label>
            </value>
            <value>
                <fullName>QF_HOTEL_voucher</fullName>
            </value>
            <value>
                <fullName>QF_WINE_voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>QCC: Created to show/store the value of the goodwill given in AUD</description>
    <inlineHelpText>Goodwill value in AUD. This is a calculated field for equivalent AUD value. Please fill in monetary value instead.</inlineHelpText>
    <label>Equivalent AUD Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Queue Members location (manila , Sydney , ..)</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manila</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Hobart</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Capetown</fullName>
            </value>
            <value>
                <fullName>Suva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QCC_InvokeEQAPITest.cls
@isTest
public class QCC_InvokeEQAPITest {
    static User u1;
    static Account objAcc; 
    
    @testSetup
	static void createTestData() {
        Map<String, Profile> profMap = TestUtilityDataClassQantas.getProfileMap();
        Map<String, UserRole> rolesMap = TestUtilityDataClassQantas.getRoles();
        u1 = new User(LastName = 'User1', Alias = 'User', Email = 'sampleuser1@sample.com', 
                      Username = 'sampleuser1username@sample.com', ProfileId = profMap.get('QCC Customer Journey Manager').Id, //CRM-11908 Update metadata rerferences
                      EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_AU',
                      TimeZoneSidKey = 'Australia/Sydney', Location__c='Sydney', UserRoleId = rolesMap.get('QF-QDC-OM-MNL-TL').Id
                     );
        insert u1;
        //CRM-11908 Update metadata rerferences
        System.runAs(new User(Id = UserInfo.getUserId())) {
            List<Id> permissionSetIds = TestUtilityDataClassQantas.getPermissionSetIds('QCC_Base_User_Permissions,QCC_Contact_Center_Agent_Permissions,QCC_Customer_Journey_Agent_Permissions');
            List<PermissionSetAssignment> psaList = new List<PermissionSetAssignment>();
            for (Id psId : permissionSetIds) {
                psaList.add(new PermissionSetAssignment(AssigneeId = u1.Id, PermissionSetId = psId));
            }
            if (!psaList.isEmpty()) {
                insert psaList;
            }
        }
        
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId()];
        system.runAs(thisUser) {
            List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
            lsttrgStatus.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
            lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
            lsttrgStatus.addAll(TestUtilityDataClassQantas.createRecoveryTriggerSetting());
            insert lsttrgStatus;
            TestUtilityDataClassQantas.insertQantasConfigData();
        }

        System.runAs(u1) {
            Id recvyEFTRecTypeId = GenericUtils.getObjectRecordTypeId('Recovery__c', CustomSettingsUtilities.getConfigDataMap('QCC Recovery EFT RecType'));
            //Create Account
            Account objAcc = TestUtilityDataClassQantas.createPersonAccount();
            objAcc.Airline_Level__c = '1';
            objAcc.Active__c = true;
            insert objAcc;
            system.assert(objAcc != Null, 'Account is not inserted');
        	
            //Create Contact
            Contact objContact = TestUtilityDataClassQantas.createContact(objAcc.Id);
            objContact.LastName='ContTesttwo';
            objContact.CAP_ID__c='710000000017';
            objContact.RecordTypeId = GenericUtils.getObjectRecordTypeId('Contact', CustomSettingsUtilities.getConfigDataMap('QCC Individual Contact'));
            system.debug('>>>Before Contact is inserted');
            insert objContact;
            System.assert(objContact.Id != Null, 'Contact is not inserted');
            
            //Create Case
            List<Contact> lstContact = new List<Contact>();
            lstContact.add(objContact);
            String recordType = 'CCC Complaints';
            String type = 'Complaint';
            List<Case> caseRecs = new List<Case>();
            List<Case> lstCase = TestUtilityDataClassQantas.insertCases(lstContact, recordType, type, 'Qantas.com','','','');
            for(Case c : [Select Id, Status from Case where Id =: lstCase[0].Id]){
                c.Status = 'In Progress';
                caseRecs.add(c);
            }
            update caseRecs;

            system.assert(lstCase.size()>0, 'Case List is Zero');
            system.assert(lstCase[0].Id != Null, 'Case is not inserted');

            //Create Recovery
            system.debug('recvy rec type...'+recvyEFTRecTypeId);
            system.debug('RecoveryPStatusQuedForPaymentPrcsng...'+CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusQuedForPaymentPrcsng'));
            List<Recovery__c> recvyRecs = new List<Recovery__c>();
            List<Recovery__c> lstRecovery = TestUtilityDataClassQantas.insertRecoverieswithRecType(lstCase, recvyEFTRecTypeId, 
                                            CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusQuedForPaymentPrcsng'),
                                            'Ticket Refund EFT');

            for(Recovery__c r : [Select Id, Invoice_Claim_Description__c, Value__c, Monetary_Value__c, Country_Code__c,
                                 Bank_Name__c, Branch_Name__c, Branch_Number_BSB_Sort_Code__c,Branch_Swift_BIC_Code__c,
                                 Branch_Party_Id__c, Bank_Account_Name__c, Bank_Account_Number__c, IBAN__c, TAX_Id_VAT_Reg_No__c, Account_Type__c
                                 from Recovery__c where Id IN: lstRecovery]){
                r.Invoice_Claim_Description__c = 'Test Claim';
                r.Value__c = 100;
                r.Monetary_Value__c = 100; //this value should be same as Value__c
                r.Bank_Name__c = 'BANK OF QUEENSLAND LIMITED';
                r.Branch_Name__c = 'BRISBANE (124327)';
                r.Branch_Number_BSB_Sort_Code__c = '124327';
                r.Branch_Swift_BIC_Code__c = '';
                r.Branch_Party_Id__c = '31062229';
                r.Bank_Account_Name__c = 'dfdf';
                r.Bank_Account_Number__c = '12345678';
                r.IBAN__c = '';
                r.TAX_Id_VAT_Reg_No__c = '';
                r.Account_Type__c = 'Savings';
                recvyRecs.add(r);                
            }
            update recvyRecs;
        }	
	}
    
    @isTest   
    static void testEQAPISuccess() {
        QCC_EQResponseWrapper resParams = new QCC_EQResponseWrapper();
        Test.startTest();
        /* Due to real time existing code issue - Too many SOQL queries: 101 the below code is added inside Test.start/stop methods */
        Id recvyEFTRecTypeId = GenericUtils.getObjectRecordTypeId('Recovery__c', CustomSettingsUtilities.getConfigDataMap('QCC Recovery EFT RecType'));
        List<Recovery__c> recvyList = [Select Id, Name, type__c, Original_Currency__c, Invoice_Claim_Description__c, payment_Details_added_manually__c, Original_Currency_Acronym__c, Value__c,Recovery_Reason__c,
                                Monetary_Value__c, Refund_Cost_Centre_Number__c, Refund_Account_Number__c, Case_Number__r.Contact.Salutation, Country_Code__c,
                                Case_Number__r.First_Name__c,  Case_Number__r.Last_Name__c, Case_Number__r.Contact.FirstName, Case_Number__r.Contact.LastName, Bank_Name__c, Branch_Name__c, Branch_Number_BSB_Sort_Code__c,
                                Branch_Swift_BIC_Code__c, Branch_Party_Id__c, Bank_Account_Name__c, Bank_Account_Number__c, IBAN__c, TAX_Id_VAT_Reg_No__c,
                                Account_Type__c from Recovery__c where  Process_Status__c =: CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusQuedForPaymentPrcsng') and 
                                RecordTypeId =: recvyEFTRecTypeId order by Value__c, Name asc];
 
        //prepare json
        QCC_EQRequestWrapper requestEQ = QCC_EQCalloutsQueuable.preparePayload(recvyList);
        String resBody = '{\"P_CC_CLAIM_HEADER\":{\"UNIQUE_SOURCE_CALL_SEQ\":20240827122054,\"EMAIL\":\"shr_ccreq@qantas.com.au\",\"PHONE_EXT\":913234,\"PREPARED_BY\":171323},\"P_CC_CLAIM_LINES\":{\"P_CC_CLAIM_LINES_ITEM\":[{\"TITLE\":null,\"FIRST_NAME\":\"Test\",\"LAST_NAME\":\"Contactq\",\"CLAIM_NO\":\"RXXXXXX\",\"STATUS\":\"SUCCESS\",\"ERROR_CODE\":null,\"STATUS_MESSAGES\":null}]},\"OUT_RESULT\":{\"CC_BATCH_NAME\":\"CC:20240827122054:2024-08-27:12:16:16\",\"EXCEPTIONTYPE\":\"SUCCESS\",\"ERRORMESSAGE\":null}}';
        resParams = QCC_EQResponseWrapper.parse(resBody);
        resParams.P_CC_CLAIM_LINES.P_CC_CLAIM_LINES_ITEM[0].CLAIM_NO = recvyList[0].Name;
        Test.setMock(HttpCalloutMock.class, new QCC_InvokeEQAPIMock(200, JSON.serialize(resParams)));
        QCC_InvokeEQAPI.invokeProcessRecoveries(requestEQ);
        Test.stopTest();
    }
    
    @isTest   
    static void testEQAPIEFTFail() {
        QCC_EQResponseWrapper resParams = new QCC_EQResponseWrapper();
        Test.startTest();
        /* Due to real time existing code issue - Too many SOQL queries: 101 the below code is added inside Test.start/stop methods */
        Id recvyEFTRecTypeId = GenericUtils.getObjectRecordTypeId('Recovery__c', CustomSettingsUtilities.getConfigDataMap('QCC Recovery EFT RecType'));
        List<Recovery__c> recvyList = [Select Id, Name, type__c, Original_Currency__c, Invoice_Claim_Description__c, payment_Details_added_manually__c, Original_Currency_Acronym__c, Value__c,Recovery_Reason__c,
                                Monetary_Value__c, Refund_Cost_Centre_Number__c, Refund_Account_Number__c, Case_Number__r.Contact.Salutation, Country_Code__c,
                                Case_Number__r.First_Name__c,  Case_Number__r.Last_Name__c, Case_Number__r.Contact.FirstName, Case_Number__r.Contact.LastName, Bank_Name__c, Branch_Name__c, Branch_Number_BSB_Sort_Code__c,
                                Branch_Swift_BIC_Code__c, Branch_Party_Id__c, Bank_Account_Name__c, Bank_Account_Number__c, IBAN__c, TAX_Id_VAT_Reg_No__c,
                                Account_Type__c from Recovery__c where  Process_Status__c =: CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusQuedForPaymentPrcsng') and 
                                RecordTypeId =: recvyEFTRecTypeId order by Value__c, Name asc];

        //prepare json
        QCC_EQRequestWrapper requestEQ = QCC_EQCalloutsQueuable.preparePayload(recvyList);
        String resBody = '{\"P_CC_CLAIM_HEADER\":{\"UNIQUE_SOURCE_CALL_SEQ\":20240703164605,\"EMAIL\":\"shr_ccreq@qantas.com.au\",\"PHONE_EXT\":913234,\"PREPARED_BY\":171323},\"P_CC_CLAIM_LINES\":{\"P_CC_CLAIM_LINES_ITEM\":[{\"TITLE\":null,\"FIRST_NAME\":\"test\",\"LAST_NAME\":\"EFTEmailtemplate\",\"CLAIM_NO\":\"R01030985\",\"STATUS\":\"FAIL\",\"ERROR_CODE\":null,\"STATUS_MESSAGES\":\"InvalidBankBranchselected.PleaseselecttheBankBranchinfofromtheLOV\"}]},\"OUT_RESULT\":{\"CC_BATCH_NAME\":null,\"EXCEPTIONTYPE\":\"ERROR\",\"ERRORMESSAGE\":\"Noclaimlinescouldbeprocessed,Pleasereviewtheindvidualerrormessages\"}}';
        resParams = QCC_EQResponseWrapper.parse(resBody);
        resParams.P_CC_CLAIM_LINES.P_CC_CLAIM_LINES_ITEM[0].CLAIM_NO = recvyList[0].Name;
        Test.setMock(HttpCalloutMock.class, new QCC_InvokeEQAPIMock(200, JSON.serialize(resParams)));
        QCC_InvokeEQAPI.invokeProcessRecoveries(requestEQ);
        Test.stopTest();
    }
    
    @isTest   
    static void testEQAPIFail() {
        QCC_EQResponseWrapper resParams = new QCC_EQResponseWrapper();
        Test.startTest();
        /* Due to real time existing code issue - Too many SOQL queries: 101 the below code is added inside Test.start/stop methods */
        Id recvyEFTRecTypeId = GenericUtils.getObjectRecordTypeId('Recovery__c', CustomSettingsUtilities.getConfigDataMap('QCC Recovery EFT RecType'));
        List<Recovery__c> recvyList = [Select Id, Name, type__c, Original_Currency__c, Invoice_Claim_Description__c, payment_Details_added_manually__c, Original_Currency_Acronym__c, Value__c,Recovery_Reason__c,
                                Monetary_Value__c, Refund_Cost_Centre_Number__c, Refund_Account_Number__c, Case_Number__r.Contact.Salutation, Country_Code__c,
                                Case_Number__r.First_Name__c,  Case_Number__r.Last_Name__c, Case_Number__r.Contact.FirstName, Case_Number__r.Contact.LastName, Bank_Name__c, Branch_Name__c, Branch_Number_BSB_Sort_Code__c,
                                Branch_Swift_BIC_Code__c, Branch_Party_Id__c, Bank_Account_Name__c, Bank_Account_Number__c, IBAN__c, TAX_Id_VAT_Reg_No__c,
                                Account_Type__c from Recovery__c where  Process_Status__c =: CustomSettingsUtilities.getConfigDataMap('RecoveryPStatusQuedForPaymentPrcsng') and 
                                RecordTypeId =: recvyEFTRecTypeId order by Value__c, Name asc];

        //prepare json
        QCC_EQRequestWrapper requestEQ = QCC_EQCalloutsQueuable.preparePayload(recvyList);
        String resBody = '{\"P_CC_CLAIM_HEADER\":{\"UNIQUE_SOURCE_CALL_SEQ\":20240827122054,\"EMAIL\":\"shr_ccreq@qantas.com.au\",\"PHONE_EXT\":913234,\"PREPARED_BY\":171323},\"P_CC_CLAIM_LINES\":{\"P_CC_CLAIM_LINES_ITEM\":[{\"TITLE\":null,\"FIRST_NAME\":\"Test\",\"LAST_NAME\":\"Contactq\",\"CLAIM_NO\":\"RXXXXXX\",\"STATUS\":\"SUCCESS\",\"ERROR_CODE\":null,\"STATUS_MESSAGES\":null}]},\"OUT_RESULT\":{\"CC_BATCH_NAME\":\"CC:20240827122054:2024-08-27:12:16:16\",\"EXCEPTIONTYPE\":\"SUCCESS\",\"ERRORMESSAGE\":null}}';
        resParams = QCC_EQResponseWrapper.parse(resBody);
        resParams.P_CC_CLAIM_LINES.P_CC_CLAIM_LINES_ITEM[0].CLAIM_NO = recvyList[0].Name;
        Test.setMock(HttpCalloutMock.class, new QCC_InvokeEQAPIMock(500, JSON.serialize(resParams)));
        QCC_InvokeEQAPI.invokeProcessRecoveries(requestEQ);
        Test.stopTest();
    }
}