force-app/main/default/objects/Account/fields/AccreditationStatus__c.field-meta.xml
<CustomField>
    <fullName>AccreditationStatus__c</fullName>
    <label>Accreditation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Active - No BSP</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <isActive>false</isActive>
                <label>A</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
            <value>
                <fullName>S</fullName>
                <isActive>false</isActive>
                <label>S</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AccreditationType__c.field-meta.xml
<CustomField>
    <fullName>AccreditationType__c</fullName>
    <label>Accreditation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IATA</fullName>
            </value>
            <value>
                <fullName>TIDS</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>VTC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Agency_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Agency_Sales_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Sales Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Region__c.sales_h_eq_type__c</field>
            <operation>equals</operation>
            <value>Corporate-Industry, Industry</value>
        </filterItems>
        <filterItems>
            <field>Sales_Region__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>The Brand value and associated Brand Code comes from the Sales Region master list. For the value to appear as a selectable it must be added to the Sales Region list first.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Agency Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Generic Company Email</inlineHelpText>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Qantas_Industry_Centre_ID__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Industry_Centre_ID__c</fullName>
    <description>Unique Field after CRM-1340 is resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Qantas Industry Centre Identifier</inlineHelpText>
    <label>QIC ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SecondaryEmail__c.field-meta.xml
<CustomField>
    <fullName>SecondaryEmail__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>This field is used to hold any secondary email for the Agency/Account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency_Account.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account</fullName>
    <active>true</active>
    <description>To be used for all Industry Accounts having a contract with Qantas</description>
    <label>Agency Account</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Agency_Identifier__c</fullName>
    <description>QAC - Agency Credits</description>
    <formula>Account.Qantas_Industry_Centre_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/GDS_Name__c.field-meta.xml
<CustomField>
    <fullName>GDS_Name__c</fullName>
    <formula>GDS__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GDS Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Invitation_Date__c.field-meta.xml
<CustomField>
    <fullName>Invitation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invitation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Premium_Channel_Status__c.field-meta.xml
<CustomField>
    <fullName>Premium_Channel_Status__c</fullName>
    <label>Premium NDC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>GDS Pending</fullName>
            </value>
            <value>
                <fullName>GDS Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>GDS Disable</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Agency_Channel.recordType-meta.xml
<RecordType>
    <fullName>Agency_Channel</fullName>
    <active>true</active>
    <description>This is being used for Channel Registration.</description>
    <label>Agency Channel</label>
</RecordType>

force-app/main/default/objects/Global_Properties__mdt/Global_Properties__mdt.object-meta.xml
<CustomObject>
    <label>Global Properties</label>
    <pluralLabel>Global Properties</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Properties__mdt/fields/Static_Values__c.field-meta.xml
<CustomField>
    <fullName>Static_Values__c</fullName>
    <label>Static Values</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Offer_Allocation__c/Offer_Allocation__c.object-meta.xml
<CustomObject>
    <label>Offer Allocation</label>
    <nameField>
        <displayFormat>OAN-{0000}</displayFormat>
        <label>Offer Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Allocation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offer Allocations</relationshipLabel>
    <relationshipName>Offer_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer_Allocation__c/fields/Offer_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Offer_Catalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Catalogue</label>
    <referenceTo>Offer_Catalogue__c</referenceTo>
    <relationshipLabel>Offer Allocations</relationshipLabel>
    <relationshipName>Offer_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer_Allocation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Deallocated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer_Catalogue__c/Offer_Catalogue__c.object-meta.xml
<CustomObject>
    <label>Offer Catalogue</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Offer Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Catalogue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <description>Created as a result of SFDC and iDeal integration.</description>
    <label>Sales Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Region__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Active flag based on End Date</description>
    <formula>OR(Today() &lt; sales_h_end_date__c, ISNULL(sales_h_end_date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agency : Email address which the report will be sent to. Separate multiple email addresses using the semicolon character &quot;;&quot;</inlineHelpText>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AgencyInvitationController.cls
public with sharing class AgencyInvitationController {
    
    @AuraEnabled
    public static Object getAllocations(List<String> agencyBrand, List<String> agencyGroup, List<String> agencyIATA, List<String> agencyIATACodes, Id selectedOfferId){
        try {
            if ( String.isBlank(selectedOfferId) ) return null;
            if ( agencyIATA == null || agencyBrand == null || agencyGroup == null || agencyIATACodes == null) return null;
            if ( agencyIATA.isEmpty() && agencyBrand.isEmpty() && agencyGroup.isEmpty() && agencyIATACodes.isEmpty()) return null;

            String[] eligibleStatus = new String[] {'Active'};
            // Fetching excluded accreditation statuses and GDS from labels
            String[] excludedGDS = Label.PNDC_Excluded_Aggregators.split(';');
            Map<String, Object> returnData = new Map<String, Object>();
            Set<Id> acntIds = new Set<Id>();
            /*for (String status : eligibleStatus) {
                Map<Id, Account> accs = new Map<Id, Account> ([select Id, Name, Active__c,  Qantas_Industry_Centre_ID__c, Agency_Sales_Region__r.Email__c, Agency_Sales_Region__r.name, 
                                            BillingCountryCode, 
                                            (select id, Status__c from Offer_Allocations__r where Offer_Catalogue__c = :selectedOfferId limit 1 ) from Account where 
                                            Id in 
                        (select AccountId from Asset where RecordType.DeveloperName = 'Agency_Channel' and Active__c = true and 
                        Account.RecordType.DeveloperName = 'Agency_Account' and Account.Active__c = true and 
                            Account.Agency_Sales_Region__r.Active__c = true and 
                            GDS_Name__c not in :excludedGDS and 
                            (AccountId in :agencyIATA or Account.Agency_Sales_Region__r.Name like :agencyGroup or Account.Agency_Sales_Region__c in :agencyBrand OR 
                            Account.Qantas_Industry_Centre_ID__c in :agencyIATACodes)
                         and Premium_Channel_Status__c = :status and AccountId not in :acntIds
                        ) with USER_MODE order by Qantas_Industry_Centre_ID__c Nulls Last]);
                if(!accs.isEmpty()) {
                    acntIds.addAll(accs.keySet());
                    returnData.put(status, accs.values());
                }
            }*/

            return [select Id, Name, Active__c,  Qantas_Industry_Centre_ID__c, Agency_Sales_Region__r.Email__c, Agency_Sales_Region__r.name, BillingCountryCode, 
                (select id, Status__c from Offer_Allocations__r where Offer_Catalogue__c = :selectedOfferId limit 1 ), 
                (select id, Premium_Channel_Status__c from Assets 
                            where RecordType.DeveloperName = 'Agency_Channel' and Active__c = true and GDS_Name__c not in :excludedGDS and Premium_Channel_Status__c in :eligibleStatus 
                            order by Premium_Channel_Status__c desc limit 1)
                from Account 
                where RecordType.DeveloperName = 'Agency_Account' and Active__c = true and Agency_Sales_Region__r.Active__c = true and 
                        (Id in :agencyIATA 
                        OR Agency_Sales_Region__r.Name like :agencyGroup 
                        OR Agency_Sales_Region__c in :agencyBrand 
                        OR Qantas_Industry_Centre_ID__c in :agencyIATACodes) with USER_MODE order by Qantas_Industry_Centre_ID__c Nulls Last];
            /*String queryString = 'select Id, Name, Active__c,  Qantas_Industry_Centre_ID__c, Agency_Sales_Region__r.Email__c, Agency_Sales_Region__r.name, '
                + '(select id from Offer_Allocations__r where Offer_Catalogue__c = :selectedOffer limit 1 ) from Account where Id in '
                    + '(select AccountId from Asset where Active__c = true and Account.Active__c = true and Account.Agency_Sales_Region__r.Active__c = true and '
                    + ' (AccountId in :agencyIATA or Account.Agency_Sales_Region__r.Name like :agencyGroup or Account.Agency_Sales_Region__c in :agencyBrand)'
                    + ' and Premium_Channel_Status__c in :eligibleStatus' 
                    + ')';*/

            //return returnData;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<sObject> getAgencyInvitations(List<String> agencyBrand, List<String> agencyGroup, List<String> agencyIATA, List<String> agencyIATACodes){
        try {
            if ( agencyIATA == null || agencyBrand == null || agencyGroup == null || agencyIATACodes == null ) return null;
            if(agencyIATA.isEmpty() && agencyBrand.isEmpty() && agencyGroup.isEmpty() && agencyIATACodes.isEmpty()) return null;

            String[] excludedGDS = Label.PNDC_Excluded_Aggregators.split(';');

            return [select id, GDS_Name__c, Agency_Identifier__c, Invitation_Date__c, Invitation_Expiry_Date__c, EffectiveDate__c, Premium_Channel_Status__c,
                    Account.Name, Account.Agency_Sales_Region__r.Name, Account.Agency_Sales_Region__r.Email__c, Account.Email__c, Account.AccreditationType__c,
                    Account.AccreditationStatus__c, Account.SecondaryEmail__c, AccountId
                    from Asset where RecordType.DeveloperName = 'Agency_Channel' and Active__c = true and 
                        Account.RecordType.DeveloperName = 'Agency_Account' and Account.Active__c = true and Account.Agency_Sales_Region__r.Active__c = true and 
                        GDS_Name__c not in :excludedGDS and 
                        ( AccountId in :agencyIATA or Account.Agency_Sales_Region__r.Name like :agencyGroup or 
                        Account.Agency_Sales_Region__c in :agencyBrand or Account.Qantas_Industry_Centre_ID__c in :agencyIATACodes) 
                        with USER_MODE order by Agency_Identifier__c Nulls Last];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void sendInvitations(List<String> managerEmails, String invitationType){
        try {
            String metadataName;
            if (invitationType == 'Commercial Agreement') {
                metadataName = 'Agency_Invitation_Email_Template';
            }else if(invitationType == 'EOI'){
                metadataName = 'Agency_Invitation_EOI_Email_Template';
            }else if(invitationType == 'PNDC Email'){
                metadataName = 'Agency_Invitation_PNDC_Email_Template';
            }else{
                throw new AuraHandledException('Invalid Invitation Type');
            }
            Global_Properties__mdt agencyInviteTemplate = Global_Properties__mdt.getInstance(metadataName);
            EmailTemplate et = [select id from EmailTemplate where DeveloperName =: agencyInviteTemplate.Static_Values__c limit 1];
            String orgWideId = [select id, address from orgwideemailaddress where displayname='No-Response'].id;
            List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
            for(String email : managerEmails) {
                if (String.isBlank(email)) continue;
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setOrgWideEmailAddressId(orgWideId);
                message.setToAddresses(new List<String>{email});
                message.setTemplateId(et.Id);
                message.setTargetObjectId(UserInfo.getUserId());
                message.setTreatTargetObjectAsRecipient(false);
                message.setSaveAsActivity(true);
                messages.add(message);
            }
            Messaging.sendEmail(messages);
                //message.setSenderDisplayName('QC-Lounge');
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<sObject> getAgencyNamesFromIATAs(List<String> agencyIATA){
        try {
            if (agencyIATA == null || agencyIATA.isEmpty()) return null;

            return [select id, Name
                    from Account where Active__c = true and Agency_Sales_Region__r.Active__c = true and 
                    RecordType.DeveloperName = 'Agency_Account' and Qantas_Industry_Centre_ID__c in :agencyIATA with USER_MODE];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /*@AuraEnabled
    public static Object performDml(Object records, String action){
        List<sObject> sObjectRecs;
        sObjectRecs = (List<sObject>)Json.deserializeStrict(Json.serialize(records), List<sObject>.class); 
        if (sObjectRecs == null || sObjectRecs.isEmpty()) {throw new AuraHandledException('No data to perform DML');}
        if (String.isBlank(action)) {throw new AuraHandledException('Invalid action');}
        switch on action.toLowerCase() {
            when 'insert' {
                Database.insert(sObjectRecs, AccessLevel.USER_MODE);
            } when 'update' {
                Database.update(sObjectRecs, AccessLevel.USER_MODE);
            }when 'upsert' {
                Database.upsert(sObjectRecs, AccessLevel.USER_MODE);
            }when 'delete' {
                Database.delete(sObjectRecs, AccessLevel.USER_MODE);
            }when else {
                throw new AuraHandledException('Invalid action');
            }
        }
        return sObjectRecs;
    }*/
}