force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <description>Is this an agency account? (Aquire)</description>
    <label>Travel Agent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Customer Account airline level calculated by and received from iFly (Aquire)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account airline level as set by Aquire</inlineHelpText>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire__c.field-meta.xml
<CustomField>
    <fullName>Aquire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is either &quot;Active&quot; or &quot;Pending&quot;.</description>
    <inlineHelpText>Agency is a member of the Qantas Business Rewards Program</inlineHelpText>
    <label>QBR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_Override__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Override__c</fullName>
    <description>Override Aquire? (Aquire)</description>
    <label>QBR Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract End Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealing_Flag__c.field-meta.xml
<CustomField>
    <fullName>Dealing_Flag__c</fullName>
    <description>Is Qantas currently dealing with this customer?</description>
    <label>Corporate Deal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Air_Travel_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Air_Travel_Spend__c</fullName>
    <inlineHelpText>Used to capture the total estimated air travel spend (AUD) of the account - this field is either populated via Aquire/QBD product registration or is to be manually captured/updated by the Account Manager/Team. This is used to drive the account assignment.</inlineHelpText>
    <label>Estimated Total Air Travel Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manual_Revenue_Update__c.field-meta.xml
<CustomField>
    <fullName>Manual_Revenue_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Revenue Update [System]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Logs_Tracker__c/Account_Logs_Tracker__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of fields to be racked with the value to be present</description>
    <label>Account Logs Tracker</label>
</CustomObject>

force-app/main/default/objects/AEQCC_Rebates__c/AEQCC_Rebates__c.object-meta.xml
<CustomObject>
    <label>AEQCC Rebate</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>AEQCC Rebates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AEQCC Rebates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AEQCC_Rebates__c/fields/Cheque_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Amount__c</fullName>
    <inlineHelpText>Cheque amount is inclusive of GST</inlineHelpText>
    <label>Cheque Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AEQCC_Rebates__c/fields/Prod_Reg_Link__c.field-meta.xml
<CustomField>
    <fullName>Prod_Reg_Link__c</fullName>
    <label>Prod Reg Link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Registration__c.Type__c</field>
            <operation>equals</operation>
            <value>AEQCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Registration__c</referenceTo>
    <relationshipLabel>AEQCC Rebates</relationshipLabel>
    <relationshipName>AEQCC_Rebates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AEQCC_Rebates__c/fields/Rebate_Payment__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Payment__c</fullName>
    <inlineHelpText>Rebate Payment is exclusive of GST</inlineHelpText>
    <label>Rebate Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AEQCC_Rebates__c/fields/Rebate_Sent_to__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Sent_to__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Contact name and address details are source from American Express, based on Company&apos;s last updated Decision Maker</inlineHelpText>
    <label>Rebate Sent to</label>
    <length>800</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AEQCC_Rebates__c/fields/Rebate_term__c.field-meta.xml
<CustomField>
    <fullName>Rebate_term__c</fullName>
    <label>Rebate term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jan-Jun</fullName>
            </value>
            <value>
                <fullName>Jul-Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AEQCC_Rebates__c/fields/Rebate_Tier__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Tier__c</fullName>
    <inlineHelpText>Rebate tier is determined by Domestic and International revenue on Qantas for the period.</inlineHelpText>
    <label>Rebate Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 %</fullName>
            </value>
            <value>
                <fullName>2 %</fullName>
            </value>
            <value>
                <fullName>3 %</fullName>
            </value>
            <value>
                <fullName>4 %</fullName>
            </value>
            <value>
                <fullName>5 %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AEQCC_Rebates__c/fields/Rebate_Year__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Year__c</fullName>
    <label>Rebate Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <formula>Account.Airline_Level__c</formula>
    <label>Airline Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>This field is used on the Dealing Model Request layout</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please enter the CURRENT contracted end date</inlineHelpText>
    <label>Current Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Migrated__c.field-meta.xml
<CustomField>
    <fullName>Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used for data migration only</description>
    <label>Migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QBD.recordType-meta.xml
<RecordType>
    <fullName>QBD</fullName>
    <active>false</active>
    <businessProcess>QBD</businessProcess>
    <label>QBD</label>
</RecordType>

force-app/main/default/objects/Product_Registration__c/Product_Registration__c.object-meta.xml
<CustomObject>
    <description>To be used to capture details for different product registrations like Aquire and AMEX.</description>
    <label>Product Registration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>To be used to link the registered product record with the respective account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Registration</relationshipLabel>
    <relationshipName>Product_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Holds the Airline Level of QBR Product Enrolled for AMEX</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Migrated__c.field-meta.xml
<CustomField>
    <fullName>Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check for Data Migration data from QUEST</description>
    <label>Migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/objects/User/fields/migrated__c.field-meta.xml
<CustomField>
    <fullName>migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_AEQCCRebate.cls
@isTest 
public with sharing class Test_AEQCCRebate {
   //Create all Test Data 
    @testSetup
    static void createTestData(){

        //Enable Account and Product Registration Triggers
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createProductRegTriggerSetting());
        //Added by QCC
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        insert lsttrgStatus;
        TestUtilityDataClassQantas.insertQantasConfigData();
        
        //Insert Hierarchy Setting
        TestUtilityDataClassQantas.createEnableValidationRuleSetting();
        
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType();

        //Custom Setting for Account Anf product Reg
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        //lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg QBD Registration Rec Type','QBD Registration'));
        //lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Rec Type','Aquire Registration'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Del Log SME Account Rec Type','SME Account'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('AccListner Type Direct Stream','Direct Stream'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Case SystemAdmin RecordType','System Admin Request'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseDescription_MultiQBR','Please action upon the Multiple Active QBR Product created for the same ABN at the earliest'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseOrigin_MultiQBR','QBR'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CasePriority_MultiQBR','Medium'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseReason_MultiQBR','QBR Product Closure due to Multiple Active QBR for the same ABN'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseStatus_MultiQBR','Open'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseSubject_MultiQBR','Multiple Active QBR Product Created'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseSubType_MultiQBR','QBR'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseSubType2_MultiQBR','Multiple Active QBR Product'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseType_MultiQBR','System Issues'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Status','Active'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg AEQCC Registration Rec Type','AEQCC Registration'));
        //lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        insert lstConfigData;

        List<Account_Logs_Tracker__c> lstAccLog = new List<Account_Logs_Tracker__c>();
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','QBR Override', 'Y', 'acc-001'));
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','Qantas Business Rewards (QBR)', 'false', 'acc-002'));
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','Travel Agent', 'Y', 'acc-003'));
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','Valid Entity Type', 'N', 'acc-004'));
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','GST Registered', 'N', 'acc-005'));
        insert lstAccLog;

        //Create Account 
       /* Account objAcc = TestUtilityDataClassQantas.createAccount();
        objAcc.Airline_Level__c = '1';
        objAcc.Active__c = true;
        insert objAcc;
        system.assert(objAcc != Null, 'Account is not inserted');*/
    }
    @isTest      
    public static void Test_AEQCCRebate() {
    TestUtilityDataClassQantas.enableTriggers();
        
        String orgId = UserInfo.getOrganizationId();
        String sandboxName = UserInfo.getUserName().substringAfterLast('.au');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + randomInt;
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.Email = uniqueName + '@test' + sandboxName + '.com'; 
        u.CompanyName = 'test.com';
        u.Title = 'Test User';
        u.Username = uniqueName + '@test' + sandboxName + '.com'; 
        u.Alias = 'testuser';
        u.CommunityNickname = 'Test User';
        u.TimeZoneSidKey = 'Australia/Sydney';
        u.LocaleSidKey = 'en_AU';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = pf.Id;
        u.LanguageLocaleKey = 'en_US';
        insert u;
     system.runAs(u){ 
       String prospectRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect Account').getRecordTypeId();
       Account acc = new Account(Name = 'Sample', Active__c = true, Aquire__c = true,Type = 'Prospect Account', 
                                      RecordTypeId = prospectRecordTypeId, Migrated__c = false, 
                                      Estimated_Total_Air_Travel_Spend__c = 0, Manual_Revenue_Update__c = false,
                                      Agency__c = 'N', Dealing_Flag__c = 'N', Aquire_Override__c = 'N' ,Contract_End_Date__c = Date.Today()
                                      );
                                    
                                    
       insert acc;
        AEQCCRebate controller = new AEQCCRebate(new ApexPages.StandardController(new Product_Registration__c()));

        List<Product_Registration__c> Prodreglist = new List<Product_Registration__c>();
        List<AEQCC_Rebates__c> Reblist = New List<AEQCC_Rebates__c>();
        Product_Registration__c Pr = new Product_Registration__c(name = 'Test AEQCC REBATE',Account__c=acc.id);
        AEQCC_Rebates__c Aeqreb = new AEQCC_Rebates__c (Rebate_Year__c = '2015',Rebate_Tier__c ='2 %',Rebate_term__c='Jul-Dec',Rebate_Payment__c=753,Cheque_Amount__c=826.61,Rebate_Sent_to__c='Adam Simon Po Box 103 Port Melbourne Vic 3207',Prod_Reg_Link__c='a2cO00000013Djs');
        
        //Custom Setting
        TestUtilityDataClassQantas.getrelatedCustObjRecs1();
        
     try{
            Database.Insert(Pr);
        }catch(Exception e){
            System.debug('Error Occured: '+e.getMessage());
        }

    try{
            Database.Insert(Aeqreb);
        }catch(Exception e){
            System.debug('Error Occured: '+e.getMessage());
        }  
 
        AEQCCRebate controllerTest = new AEQCCRebate(new ApexPages.StandardController(pr));     
        controllerTest.getrelatedCustObjRecs1();
        Reblist.add(Aeqreb);
   }     
 }    
}