force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <description>Is this an agency account? (Aquire)</description>
    <label>Travel Agent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Annual_International_Flights__c.field-meta.xml
<CustomField>
    <fullName>Annual_International_Flights__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Annual International Flights</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-10</fullName>
            </value>
            <value>
                <fullName>11-20</fullName>
            </value>
            <value>
                <fullName>21-50</fullName>
            </value>
            <value>
                <fullName>51-100</fullName>
            </value>
            <value>
                <fullName>101-200</fullName>
            </value>
            <value>
                <fullName>201-300</fullName>
            </value>
            <value>
                <fullName>300+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_Override__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Override__c</fullName>
    <description>Override Aquire? (Aquire)</description>
    <label>QBR Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_Override_Reason__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Override_Reason__c</fullName>
    <label>QBR Override Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Company affiliated with a Company with the principal operation is to sell or resell travel</fullName>
            </value>
            <value>
                <fullName>Member of/ Affiliated with, a company that has a Qantas Corporate Airfares Agreement</fullName>
            </value>
            <value>
                <fullName>Principal place of business is outside of Australia</fullName>
            </value>
            <value>
                <fullName>Receiving third-party private airfares, discounts or rebates from Qantas</fullName>
            </value>
            <value>
                <fullName>SME dealing customer - point earn to be negotiated</fullName>
            </value>
            <value>
                <fullName>Suspension of airline point earn at commercial request</fullName>
            </value>
            <value>
                <fullName>Travel using the registered ABN is for leisure</fullName>
            </value>
            <value>
                <fullName>Other (full explanation required in SME Override Note)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealing_Flag__c.field-meta.xml
<CustomField>
    <fullName>Dealing_Flag__c</fullName>
    <description>Is Qantas currently dealing with this customer?</description>
    <label>Corporate Deal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Manual_Revenue_Update__c.field-meta.xml
<CustomField>
    <fullName>Manual_Revenue_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Revenue Update [System]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage/Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Travel_Frequency__c/Account_Travel_Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Auto insert  the opportunity based on travel frequency value</description>
    <label>Account Travel Frequency</label>
</CustomObject>

force-app/main/default/objects/Account_Travel_Frequency__c/fields/Travel_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Travel_Frequency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Travel Frequency</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/Product_Registration__c.object-meta.xml
<CustomObject>
    <description>To be used to capture details for different product registrations like Aquire and AMEX.</description>
    <label>Product Registration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>To be used to link the registered product record with the respective account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Registration</relationshipLabel>
    <relationshipName>Product_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Annual_International_Flights__c.field-meta.xml
<CustomField>
    <fullName>Annual_International_Flights__c</fullName>
    <label>Annual International Flights</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-10</fullName>
            </value>
            <value>
                <fullName>11-20</fullName>
            </value>
            <value>
                <fullName>21-50</fullName>
            </value>
            <value>
                <fullName>51-100</fullName>
            </value>
            <value>
                <fullName>101-200</fullName>
            </value>
            <value>
                <fullName>201-300</fullName>
            </value>
            <value>
                <fullName>300+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Aq_Business_Domestic_annual_spend__c.field-meta.xml
<CustomField>
    <fullName>Aq_Business_Domestic_annual_spend__c</fullName>
    <description>Incoming data from QBR</description>
    <label>QBR Business Domestic annual spend</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Aq_Business_international_annual_spend__c.field-meta.xml
<CustomField>
    <fullName>Aq_Business_international_annual_spend__c</fullName>
    <description>Incoming from Qantas Business Rewards</description>
    <label>QBR Business international annual spend</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Aquire_Membership_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Membership_End_Date__c</fullName>
    <description>End Date of QBR Membership being sent to AMEX</description>
    <encryptionScheme>None</encryptionScheme>
    <label>QBR Membership End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Customer_s_Requested_Choice__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_Requested_Choice__c</fullName>
    <description>Customer’s Requested Choice from AMEX</description>
    <inlineHelpText>A - Aquire Points, R - Rebate</inlineHelpText>
    <label>Customer’s Requested Choice</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage/Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Contract Expired</fullName>
            </value>
            <value>
                <fullName>No Contract</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>New Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/Test_ProductRegistrationHandler.cls
@isTest
public class Test_ProductRegistrationHandler{
    
    //Added By Praveen For test class failure fix
    @testsetup
    static void createData(){
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg AEQCC Registration Rec Type','AEQCC Registration'));
        insert lstConfigData;
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType();
        
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createProductRegTriggerSetting();
        insert lsttrgStatus;
    }
    
    public static testMethod void testProductRegistrationInsert(){
        
        TestUtilityDataClassQantas.enableTriggers();
        insert new Account_Travel_Frequency__c(Name = 'Travel Frequency', Travel_Frequency__c = '300');
        Test.startTest();
        // Insert Accounts
        List<Account> accList = new List<Account>(); 
        accList.add(new Account(Name = 'Sample1', Active__c = true,
                                RecordTypeId = TestUtilityDataClassQantas.prospectRecordTypeId, 
                                Agency__c = 'N', Dealing_Flag__c = 'N', Aquire_Override__c = 'N' 
                               ));
        accList.add(new Account(Name = 'Sample2', Active__c = true, 
                                RecordTypeId = TestUtilityDataClassQantas.prospectRecordTypeId, 
                                Agency__c = 'N', Dealing_Flag__c = 'N', Aquire_Override__c = 'N' 
                               ));
        accList.add(new Account(Name = 'Sample3', Active__c = true, 
                                RecordTypeId = TestUtilityDataClassQantas.prospectRecordTypeId, 
                                Agency__c = 'N', Dealing_Flag__c = 'N', Aquire_Override__c = 'N' 
                               ));
        accList.add(new Account(Name = 'Sample4', Active__c = true,
                                RecordTypeId = TestUtilityDataClassQantas.prospectRecordTypeId, 
                                Agency__c = 'Y', Dealing_Flag__c = 'N', Aquire_Override__c = 'N' 
                               ));
        accList.add(new Account(Name = 'Sample5', Active__c = true, Manual_Revenue_Update__c = true,
                                RecordTypeId = TestUtilityDataClassQantas.prospectRecordTypeId, 
                                Agency__c = 'N', Dealing_Flag__c = 'Y', Aquire_Override__c = 'N' 
                               ));
        accList.add(new Account(Name = 'Sample6', Active__c = true, 
                                RecordTypeId = TestUtilityDataClassQantas.prospectRecordTypeId, 
                                Agency__c = 'N', Dealing_Flag__c = 'N', Aquire_Override__c = 'Y', Aquire_Override_Reason__c ='test' 
                               ));
        accList.add(new Account(Name = 'Sample7', Active__c = true, 
                                RecordTypeId = TestUtilityDataClassQantas.prospectRecordTypeId, 
                                Agency__c = 'N', Dealing_Flag__c = 'N', Aquire_Override__c = 'Y', Aquire_Override_Reason__c ='test'
                               ));
        accList.add(new Account(Name = 'Sample8', Active__c = true,
                                RecordTypeId = TestUtilityDataClassQantas.prospectRecordTypeId, 
                                Agency__c = 'N', Dealing_Flag__c = 'N', Aquire_Override__c = 'N' 
                               ));  
        insert accList;
        
        // Insert trigger 
        
        List<Product_Registration__c> prAqList = new List<Product_Registration__c>();          
        prAqList.add(new Product_Registration__c(Name = 'prAQ', Account__c = accList[0].id, RecordTypeId = TestUtilityDataClassQantas.aquireRecordTypeId, Active__c = true, 
                                                 Stage_Status__c = 'Active', Annual_International_Flights__c = '200-500', Aquire_Membership_End_Date__c = Date.today()));
        prAqList.add(new Product_Registration__c(Name = 'prAQ', Account__c = accList[3].id, RecordTypeId = TestUtilityDataClassQantas.aquireRecordTypeId, Active__c = true, 
                                                 Stage_Status__c = 'Active', Aq_Business_Domestic_annual_spend__c = 100, Aq_Business_international_annual_spend__c = 300));
        prAqList.add(new Product_Registration__c(Name = 'prAQ', Account__c = accList[4].id, RecordTypeId = TestUtilityDataClassQantas.aquireRecordTypeId, Active__c = true, Stage_Status__c = 'Active'));                         
        insert prAqList;
        
        List<Product_Registration__c> prList = new List<Product_Registration__c>(); 
        prList.add(new Product_Registration__c(Name = 'pr1', Account__c = accList[0].id, Customer_s_Requested_Choice__c = 'A', RecordTypeId = TestUtilityDataClassQantas.amexRecordTypeId, Active__c = true));
        prList.add(new Product_Registration__c(Name = 'pr2', Account__c = accList[1].id, Customer_s_Requested_Choice__c = 'A', RecordTypeId = TestUtilityDataClassQantas.amexRecordTypeId, Active__c = true));
        prList.add(new Product_Registration__c(Name = 'pr3', Account__c = accList[2].id, Customer_s_Requested_Choice__c = 'R', RecordTypeId = TestUtilityDataClassQantas.amexRecordTypeId, Active__c = true));
        prList.add(new Product_Registration__c(Name = 'pr4', Account__c = accList[3].id, Customer_s_Requested_Choice__c = 'R', RecordTypeId = TestUtilityDataClassQantas.amexRecordTypeId, Active__c = true));
        prList.add(new Product_Registration__c(Name = 'pr5', Account__c = accList[4].id, Customer_s_Requested_Choice__c = 'R', RecordTypeId = TestUtilityDataClassQantas.amexRecordTypeId, Active__c = true));
        prList.add(new Product_Registration__c(Name = 'pr6', Account__c = accList[5].id, Customer_s_Requested_Choice__c = 'A', RecordTypeId = TestUtilityDataClassQantas.amexRecordTypeId, Active__c = true));
        prList.add(new Product_Registration__c(Name = 'pr7', Account__c = accList[6].id, Customer_s_Requested_Choice__c = 'R', RecordTypeId = TestUtilityDataClassQantas.amexRecordTypeId, Active__c = true));
        prList.add(new Product_Registration__c(Name = 'pr8', Account__c = accList[7].id, Customer_s_Requested_Choice__c = 'R', RecordTypeId = TestUtilityDataClassQantas.amexRecordTypeId, Active__c = true));
        insert prList; 
        
        delete prAqList;
        Test.stopTest();
        //Test.startTest();
        // Update trigger      
        
        List<Product_Registration__c>prAqList2 = new List<Product_Registration__c>();
        prAqList2.add(new Product_Registration__c(Name = 'prAQ2', Account__c = accList[0].id, RecordTypeId = TestUtilityDataClassQantas.aquireRecordTypeId, Active__c = true, 
                                                  Stage_Status__c = 'Active', Annual_International_Flights__c = '200-500', Aquire_Membership_End_Date__c = Date.today()));
        prAqList2.add(new Product_Registration__c(Name = 'prAQ3', Account__c = accList[2].id, RecordTypeId = TestUtilityDataClassQantas.aquireRecordTypeId, Active__c = true, 
                                                  Stage_Status__c = 'Active', Annual_International_Flights__c = '200-500', Aquire_Membership_End_Date__c = Date.today()));                         
        insert prAqList2;
        
        ProductRegistrationHandler.hasRunProcessAMEXEligibilityUpdate = false;   
        
        //Test.stopTest();        
    }
}