force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <description>Is this an agency account? (Aquire)</description>
    <label>Travel Agent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AMEX__c.field-meta.xml
<CustomField>
    <fullName>AMEX__c</fullName>
    <defaultValue>false</defaultValue>
    <description>American Express Qantas Co-brand Card</description>
    <inlineHelpText>American Express Qantas Co-brand Card</inlineHelpText>
    <label>AMEX</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Annual_Domestic_Flights__c.field-meta.xml
<CustomField>
    <fullName>Annual_Domestic_Flights__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Annual Domestic Flights</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-10</fullName>
            </value>
            <value>
                <fullName>11-20</fullName>
            </value>
            <value>
                <fullName>21-50</fullName>
            </value>
            <value>
                <fullName>51-100</fullName>
            </value>
            <value>
                <fullName>101-200</fullName>
            </value>
            <value>
                <fullName>201-300</fullName>
            </value>
            <value>
                <fullName>300+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Annual_International_Flights__c.field-meta.xml
<CustomField>
    <fullName>Annual_International_Flights__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Annual International Flights</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-10</fullName>
            </value>
            <value>
                <fullName>11-20</fullName>
            </value>
            <value>
                <fullName>21-50</fullName>
            </value>
            <value>
                <fullName>51-100</fullName>
            </value>
            <value>
                <fullName>101-200</fullName>
            </value>
            <value>
                <fullName>201-300</fullName>
            </value>
            <value>
                <fullName>300+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire__c.field-meta.xml
<CustomField>
    <fullName>Aquire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set to TRUE if the Stage/Status for Aquire Product Registration is either &quot;Active&quot; or &quot;Pending&quot;.</description>
    <inlineHelpText>Agency is a member of the Qantas Business Rewards Program</inlineHelpText>
    <label>QBR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_Override__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Override__c</fullName>
    <description>Override Aquire? (Aquire)</description>
    <label>QBR Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealing_Flag__c.field-meta.xml
<CustomField>
    <fullName>Dealing_Flag__c</fullName>
    <description>Is Qantas currently dealing with this customer?</description>
    <label>Corporate Deal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Air_Travel_Spend__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Air_Travel_Spend__c</fullName>
    <inlineHelpText>Used to capture the total estimated air travel spend (AUD) of the account - this field is either populated via Aquire/QBD product registration or is to be manually captured/updated by the Account Manager/Team. This is used to drive the account assignment.</inlineHelpText>
    <label>Estimated Total Air Travel Spend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estimated_Total_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Annual_Revenue__c</fullName>
    <inlineHelpText>To be captured by the Account Manager/Team if there are no actuals or if estimated is different from actuals</inlineHelpText>
    <label>Estimated QF Annual Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manual_Revenue_Update__c.field-meta.xml
<CustomField>
    <fullName>Manual_Revenue_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Revenue Update [System]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Max_Airline_Points_for_Membership_Year__c.field-meta.xml
<CustomField>
    <fullName>Max_Airline_Points_for_Membership_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To store the incoming information from Acquire</description>
    <label>Max. Airline Points for Membership Year</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage/Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Travel_Frequency__c/Account_Travel_Frequency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Auto insert  the opportunity based on travel frequency value</description>
    <label>Account Travel Frequency</label>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/Product_Registration__c.object-meta.xml
<CustomObject>
    <description>To be used to capture details for different product registrations like Aquire and AMEX.</description>
    <label>Product Registration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>To be used to link the registered product record with the respective account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Registration</relationshipLabel>
    <relationshipName>Product_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Annual_Domestic_Flights__c.field-meta.xml
<CustomField>
    <fullName>Annual_Domestic_Flights__c</fullName>
    <label>Annual Domestic Flights</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-10</fullName>
            </value>
            <value>
                <fullName>11-20</fullName>
            </value>
            <value>
                <fullName>21-50</fullName>
            </value>
            <value>
                <fullName>51-100</fullName>
            </value>
            <value>
                <fullName>101-200</fullName>
            </value>
            <value>
                <fullName>201-300</fullName>
            </value>
            <value>
                <fullName>300+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Annual_International_Flights__c.field-meta.xml
<CustomField>
    <fullName>Annual_International_Flights__c</fullName>
    <label>Annual International Flights</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-10</fullName>
            </value>
            <value>
                <fullName>11-20</fullName>
            </value>
            <value>
                <fullName>21-50</fullName>
            </value>
            <value>
                <fullName>51-100</fullName>
            </value>
            <value>
                <fullName>101-200</fullName>
            </value>
            <value>
                <fullName>201-300</fullName>
            </value>
            <value>
                <fullName>300+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Aq_Business_Domestic_annual_spend__c.field-meta.xml
<CustomField>
    <fullName>Aq_Business_Domestic_annual_spend__c</fullName>
    <description>Incoming data from QBR</description>
    <label>QBR Business Domestic annual spend</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Aq_Business_international_annual_spend__c.field-meta.xml
<CustomField>
    <fullName>Aq_Business_international_annual_spend__c</fullName>
    <description>Incoming from Qantas Business Rewards</description>
    <label>QBR Business international annual spend</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Aquire_Membership_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Membership_End_Date__c</fullName>
    <description>End Date of QBR Membership being sent to AMEX</description>
    <encryptionScheme>None</encryptionScheme>
    <label>QBR Membership End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Estimated_Total_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Annual_Revenue__c</fullName>
    <label>Estimated Total Annual Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Max_Airline_Points_for_Membership_Year__c.field-meta.xml
<CustomField>
    <fullName>Max_Airline_Points_for_Membership_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Achieved Max QBR Pts fr Membership Yr</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <description>Aquire Inbound</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage/Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Contract Expired</fullName>
            </value>
            <value>
                <fullName>No Contract</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>New Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductRegistrationHandler.cls
/**********************************************************************************************************************************

Created Date: 18/03/2015

Description: Process Product Registration trigger for:
1. processing AMEX Eligibility on accounts.
2. Opportunity creation based on travel frequency. (Disabling the creation through the JIRA CRM-1902)

Version:
V1.0 - 18/03/2015 - Initial version [FO]
Membership_Expiry_Date__c replaces Aquire_membership_end_date__c CRM-1093  13/06/2015
Removed QBD Account references 
CRM-1573 (PR2810494) Recurring Amex requests need logic to run again.
CRM-1902 - Remove auto-create opp for Aquire
        - Fix for duplicate record in account update list

    Modified Date   : 29/01/19 (DD/MM/YYYY)
    Added By        : Vinothkumar Balasubramanian
    JIRA            : CRM - 3494
    Version         : V2.0 - Commented the unused lines after discussing with Nijo to increase test class coverage
**********************************************************************************************************************************/
public class ProductRegistrationHandler {
    
    /*
    Purpose:  Create opportunity based on travel frequency, Change account type
    Parameters: trigger.new list of product Registrations.
    Return: none. 
    */
    public static boolean hasRunProcessAMEXEligibilityUpdate = false;
    public void processAccountAndOpportunity(List<Product_Registration__c> newList){
        String aquireRecordTypeId = Schema.SObjectType.Product_Registration__c.getRecordTypeInfosByName().get('Aquire Registration').getRecordTypeId();
        String amexRecordTypeId = Schema.SObjectType.Product_Registration__c.getRecordTypeInfosByName().get('AEQCC Registration').getRecordTypeId();
        
        set<Id> aquireAccounts = new set<Id>();
        //set<Id> amexAccounts = new set<Id>();
        
        map<Id,account> accToUpdate = new map<Id,account>();
        
        for(Product_Registration__c pr:newList){
            if(pr.RecordTypeId == aquireRecordTypeId){
                aquireAccounts.add(pr.Account__c);
            }/*else if(pr.RecordTypeId == amexRecordTypeId){
                amexAccounts.add(pr.Account__c);
            }*/
        }
        
        /*Create oppertunities */
        
        //CRM-1902 - Commented the below lines to disable the auto Opportunity creation
        
        /*List<Opportunity> oppoList = new List<Opportunity>();
        Account_Travel_Frequency__c atf = Account_Travel_Frequency__c.getValues('Travel Frequency');*/
        
        for(Product_Registration__c pr:[SELECT id, Account__c, Annual_Domestic_Flights__c, Annual_International_Flights__c, Account__r.Name, Account__r.OwnerId,
                                        Account__r.CreatedDate, Account__r.Manual_Revenue_Update__c, Stage_Status__c, Estimated_Total_Annual_Revenue__c, Aq_Business_Domestic_annual_spend__c, Aq_Business_international_annual_spend__c 
                                        FROM Product_Registration__c 
                                        WHERE id IN:(Trigger.newMap.keySet()) AND Account__c IN:(aquireAccounts)])
        {    
            Account tempAcc = new Account(id = pr.Account__c, Aquire__c = true);        //All Aquire Accounts
            if(pr.Account__r.Manual_Revenue_Update__c != true){
                if(pr.Aq_Business_Domestic_annual_spend__c == null && pr.Aq_Business_international_annual_spend__c == null){
                    tempAcc.Estimated_Total_Air_Travel_Spend__c  = null;
                }else {
                    Decimal a=0, b=0;
                    //CRM-2618  commenting the logic starts here
                   /* if(pr.Aq_Business_Domestic_annual_spend__c != null && pr.Aq_Business_Domestic_annual_spend__c != '') a =  Decimal.valueOf(rectifySpendAmount(pr.Aq_Business_Domestic_annual_spend__c));
                    if(pr.Aq_Business_international_annual_spend__c != null && pr.Aq_Business_international_annual_spend__c != '') b =  Decimal.valueOf(rectifySpendAmount(pr.Aq_Business_international_annual_spend__c));*/
                    //CRM-2618  commenting the logic end here
                    //CRM-2618 new datatype change logic
                    if(pr.Aq_Business_Domestic_annual_spend__c != null)a =  pr.Aq_Business_Domestic_annual_spend__c;
                    if(pr.Aq_Business_international_annual_spend__c != null) b =  pr.Aq_Business_international_annual_spend__c;
                    //CRM-2618 new datatype change logic
                    Decimal amnt = a+b ;
                    tempAcc.Estimated_Total_Air_Travel_Spend__c  = amnt ;
                }
            }
            accToUpdate.put(tempAcc.Id,tempAcc);         
        }
        
        //CRM-1902 - Commented the below lines to disable the auto Opportunity creation
        
        /* Save Opportunities */
        /* if(oppoList.size() > 0){
        if(oppoList.size()>0) Database.insert(oppoList);
        }*/
        
        /* Update Account types */
        /*for(id aId : amexAccounts){    //All amex Accounts
            if(accToUpdate.containsKey(aId)){
                accToUpdate.get(aId).AMEX__c = true;
            }else{
             accToUpdate.put(aId,New Account(id = aId, AMEX__c = true));
            }   
        }*/

        system.debug('accToUpdate##########'+accToUpdate);
        
        if(accToUpdate.size() > 0){
            Database.update(accToUpdate.values());
        }
        
        
    }
    
        
    /*
    Purpose:  Process AMEX eligibility on update trigger
    Parameters: trigger.new list of product Registrations, record type
    Return: list of production registration. 
    */
    
    // CRM - 3494 - Commented the below method
    /*private List<Product_Registration__c> getProductRegistrationRecords(String recType, List<Product_Registration__c> newList){
        
        List<Product_Registration__c> recTypeProducts = new List<Product_Registration__c>();
        String recTypeId = Schema.SObjectType.Product_Registration__c.getRecordTypeInfosByName().get(recType).getRecordTypeId();
        
        
        for(Product_Registration__c pr : newList){
            if(pr.RecordTypeId == recTypeId){
                recTypeProducts.add(pr);
            }
        }
        return recTypeProducts;
    }*/
    
    /*
    Purpose: Get accouts for Product registraion
    Parameters: trigger.new list of product Registrations
    Return: list of Accounts. 
    */
    
    // CRM - 3494 - Commented the below method
    /*private Map<Id, Account> getAccounts(List<Product_Registration__c> newList){
        List<Id> accIds = new List<Id>();
        
        for(Product_Registration__c pr : newList){
            if(pr.Account__c != null){
                accIds.add(pr.Account__c);
            }
        }
        
        Map<Id, Account> accMap = new Map<Id, Account>([SELECT Id, CreatedDate, Aquire__c, Agency__c, Dealing_Flag__c, Aquire_Override__c
                                                        FROM Account 
                                                        WHERE Id IN :accIds]);
        return accMap;
    }*/
    
    /*
    Purpose: Get Aquire Product registraions for an account
    Parameters: set of accountIds
    Return: Map of product registrations indexed with accountId. 
    */
    
    // CRM - 3494 - Commented the below method
    /*private Map<Id, Product_Registration__c> getAquireProductRegistrations(Set<id> accountIds){
        Map<Id, Product_Registration__c> aquireProducts = new Map<Id, Product_Registration__c>();
        if(accountIds.size()>0){
            String aquireRecordTypeId = Schema.SObjectType.Product_Registration__c.getRecordTypeInfosByName().get('Aquire Registration').getRecordTypeId();
            for(Product_Registration__c pr : [SELECT Id, Account__c, Stage_Status__c,Membership_Expiry_Date__c ,Max_Airline_Points_for_Membership_Year__c
                                              FROM Product_Registration__c 
                                              WHERE RecordTypeId =:aquireRecordTypeId AND Account__c IN :accountIds]){
                                                  aquireProducts.put(pr.Account__c, pr);
                                              }
        }
        return aquireProducts;
    }*/
    /*
    Purpose: Remove all special characters from Spend Amount.
    */
    // CRM - 3494 - Commented the below method
    /*private String rectifySpendAmount(String str){
        String regExp = '^((0+)?(\\D)+(0+)?|0+)';
        String amount = str.replaceFirst(regExp, '');
        if(amount.contains(',')) amount = amount.remove(','); 
        return amount;
    }*/
    
}