force-app/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <description>Is this an agency account? (Aquire)</description>
    <label>Travel Agent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Customer Account airline level calculated by and received from iFly (Aquire)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account airline level as set by Aquire</inlineHelpText>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AMEX__c.field-meta.xml
<CustomField>
    <fullName>AMEX__c</fullName>
    <defaultValue>false</defaultValue>
    <description>American Express Qantas Co-brand Card</description>
    <inlineHelpText>American Express Qantas Co-brand Card</inlineHelpText>
    <label>AMEX</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AMEX_response_Code__c.field-meta.xml
<CustomField>
    <fullName>AMEX_response_Code__c</fullName>
    <description>Eligibility Code that gets sent to to AMEX.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>D - Double Points, R - Rebate, I - Ineligible</inlineHelpText>
    <label>AMEX Eligibility Code [System]</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Membership_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>QBR Membership Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aquire_Override__c.field-meta.xml
<CustomField>
    <fullName>Aquire_Override__c</fullName>
    <description>Override Aquire? (Aquire)</description>
    <label>QBR Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enrolment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Date__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Enrolment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/key_Contact_Office_ID__c.field-meta.xml
<CustomField>
    <fullName>key_Contact_Office_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>key Contact Office ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MCA_Number__c.field-meta.xml
<CustomField>
    <fullName>MCA_Number__c</fullName>
    <description>Represents MCA Number of AMEX Product</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AMEX MCA Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <description>To store the incoming information from iFly (Acquire)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>QBR Membership #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Logs_Tracker__c/Account_Logs_Tracker__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of fields to be racked with the value to be present</description>
    <label>Account Logs Tracker</label>
</CustomObject>

force-app/main/default/objects/Case/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <formula>Account.Airline_Level__c</formula>
    <label>Airline Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QBD.recordType-meta.xml
<RecordType>
    <fullName>QBD</fullName>
    <active>false</active>
    <businessProcess>QBD</businessProcess>
    <label>QBD</label>
</RecordType>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/Product_Registration__c.object-meta.xml
<CustomObject>
    <description>To be used to capture details for different product registrations like Aquire and AMEX.</description>
    <label>Product Registration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>To be used to link the registered product record with the respective account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Registration</relationshipLabel>
    <relationshipName>Product_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Holds the Airline Level of QBR Product Enrolled for AMEX</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Customer_s_Requested_Choice__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_Requested_Choice__c</fullName>
    <description>Customer’s Requested Choice from AMEX</description>
    <inlineHelpText>A - Aquire Points, R - Rebate</inlineHelpText>
    <label>Customer’s Requested Choice</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Enrolment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Date__c</fullName>
    <description>Aquire Inbound</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Enrolment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Key_Contact_Office_ID__c.field-meta.xml
<CustomField>
    <fullName>Key_Contact_Office_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Key Contact Office ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/MCA_Number__c.field-meta.xml
<CustomField>
    <fullName>MCA_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>MCA/Gen ID #  Identifier for both AWQCC and AQBRC</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>MCA/Gen ID #</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Membership #</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Registration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AEQCC</fullName>
            </value>
            <value>
                <fullName>Aquire</fullName>
            </value>
            <value>
                <fullName>QBD</fullName>
            </value>
            <value>
                <fullName>AQBRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/ProductRegistrationTriggerTest.cls
/*==================================================================================================================================
Author:         Praveen Sampath
Company:        Capgemini
Purpose:        Test Class for ProductRegistrationTrigger Trigger. All functionalities of ProductRegistrationTriggerHelper are covered.
Date:           28/04/2017          
History:

==================================================================================================================================
Modified By : Venkata Suresh Kumar (TCS Team), 02-Apr-2026
Desc : Remediated test class failures. Updated testCreateCaseOnMultipleActiveQBRException(), testCalculateAMEXAcceptRejectCodeException() methods.
==================================================================================================================================*/

@isTest(SeeAllData = false)
private class ProductRegistrationTriggerTest {

    //Create all Test Data 
    @testSetup
    static void createTestData(){
        //Enable Account and Product Registration Triggers
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createProductRegTriggerSetting());
        //Added by QCC
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        insert lsttrgStatus;
        TestUtilityDataClassQantas.insertQantasConfigData();
        
        //Insert Hierarchy Setting
        TestUtilityDataClassQantas.createEnableValidationRuleSetting();

        //Custom Setting for Account Anf product Reg
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        //lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg QBD Registration Rec Type','QBD Registration'));
        //lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Rec Type','Aquire Registration'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Del Log SME Account Rec Type','SME Account'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('AccListner Type Direct Stream','Direct Stream'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Case SystemAdmin RecordType','System Admin Request'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseDescription_MultiQBR','Please action upon the Multiple Active QBR Product created for the same ABN at the earliest'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseOrigin_MultiQBR','QBR'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CasePriority_MultiQBR','Medium'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseReason_MultiQBR','QBR Product Closure due to Multiple Active QBR for the same ABN'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseStatus_MultiQBR','Open'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseSubject_MultiQBR','Multiple Active QBR Product Created'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseSubType_MultiQBR','QBR'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseSubType2_MultiQBR','Multiple Active QBR Product'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('CaseType_MultiQBR','System Issues'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Status','Active'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg AEQCC Registration Rec Type','AEQCC Registration'));
        insert lstConfigData;

        List<Account_Logs_Tracker__c> lstAccLog = new List<Account_Logs_Tracker__c>();
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','QBR Override', 'Y', 'acc-001'));
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','Qantas Business Rewards (QBR)', 'false', 'acc-002'));
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','Travel Agent', 'Y', 'acc-003'));
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','Valid Entity Type', 'N', 'acc-004'));
        lstAccLog.add(TestUtilityDataClassQantas.createAccountLogsTracker('Account','GST Registered', 'N', 'acc-005'));
        insert lstAccLog;

        //Create Account 
        Account objAcc = TestUtilityDataClassQantas.createAccount();
        objAcc.Airline_Level__c = '1';
        objAcc.Active__c = true;
        insert objAcc;
        //system.assert(objAcc != Null, 'Account is not inserted');

    }

    //Method to Check Membership #, Direct and Indirect discound code added to Account from QBR Product Insert
    static TestMethod void testUpdateMemNumonAccountPostiveInsert() {
        Account objAcc = [Select Id, Aquire_Membership_Number__c From Account where Active__c = true];
        
        Test.startTest();
        List<Product_Registration__c> lstObjProdReg = new List<Product_Registration__c>();
        Product_Registration__c objAcqProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'Acquire');
        objAcqProdReg.Key_Contact_Office_ID__c ='abc 1233';
        objAcqProdReg.Enrolment_Date__c  = system.today();
        insert objAcqProdReg;
        Test.stopTest();

        //system.assert(objAcqProdReg.Id != Null, 'Product Registration is not Inserted');
        objAcc = [Select Id, Aquire_Membership_Number__c from Account where Active__c = true ]; 
        //system.assert(objAcc.Aquire_Membership_Number__c =='12345', 'Membership Number Mismatch in Account');
        
    }

    //Method to Check Membership #, Direct and Indirect discound code added to Account from QBR Product Delete
    static TestMethod void testUpdateMemNumonAccountPostiveDelete() {
        Account objAcc = [Select Id, Aquire_Membership_Number__c From Account where Active__c = true];
        Product_Registration__c objAcqProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'Acquire');
        objAcqProdReg.Key_Contact_Office_ID__c ='abc 1233';
        objAcqProdReg.Enrolment_Date__c  = system.today();
        insert objAcqProdReg;
        system.assert(objAcqProdReg.Id != Null, 'Product Registration is not Inserted');
        
        Test.startTest();
        delete objAcqProdReg;
        Test.stopTest();
        
        List<Product_Registration__c> lstObjProdReg = [Select Id from Product_Registration__c where Key_Contact_Office_ID__c = 'abc 1233'];
        system.assert(lstObjProdReg.size() == 0,'Product is Not Deleted');
        objAcc = [Select Id, Aquire_Membership_Number__c from Account where Aquire_Membership_Number__c = '' ]; 
        //system.assert(objAcc != Null, 'Membership Number Mismatch in Account');
        
    }

    //Method to check case creation when from Multiple Active QBR Product are added for an Account
    static TestMethod void testCreateCaseOnMultipleActiveQBR() {
        Account objAcc = [Select Id, Aquire_Membership_Number__c From Account where Active__c = true];
        List<Product_Registration__c> lstObjProdReg = new List<Product_Registration__c>();
        Product_Registration__c objAcqProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'Acquire');
        objAcqProdReg.Key_Contact_Office_ID__c ='abc 1233';
        objAcqProdReg.Enrolment_Date__c  = system.today();
        lstObjProdReg.add(objAcqProdReg);
        Product_Registration__c objQBDProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'Acquire');
        objQBDProdReg.Key_Contact_Office_ID__c ='abc 1234';
        objAcqProdReg.Enrolment_Date__c  = system.today();
        objQBDProdReg.Membership_Number__c = '12346';
        lstObjProdReg.add(objQBDProdReg);
        
        Test.startTest();
        insert lstObjProdReg;
        //system.assert(lstObjProdReg[1].Id != Null, 'Product Registration is not Inserted');
        Test.stopTest();
        
        objAcc = [Select Id, Aquire_Membership_Number__c from Account where Aquire_Membership_Number__c = '' ]; 
        //system.assert(objAcc != Null, 'Membership Number Mismatch in Account');
        
        List<Case> lstCase = [select Id from Case where AccountId = : objAcc.Id];
        //system.assert(lstCase.size() == 1, 'case is created');
    }

    //Method to Check Membership #, Direct and Indirect discound code added to Account from QBR Product Exceptions
    static TestMethod void testUpdateMemNumonAccountException(){
        Account objAcc = [Select Id From Account where Active__c = true];
        List<Product_Registration__c> lstObjProdReg = new List<Product_Registration__c>();
        Product_Registration__c objAcqProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'Acquire');
        objAcqProdReg.Key_Contact_Office_ID__c ='abc 1233';
        objAcqProdReg.Enrolment_Date__c  = system.today();
        //lstObjProdReg.add(objAcqProdReg);
        //insert objAcqProdReg;
        QantasConfigData__c recType = [select Id from QantasConfigData__c where Name = 'Prd Reg Aquire Registration Rec Type'];
        delete recType;
        
        Test.startTest();
        insert objAcqProdReg;
        Test.stopTest();

        List<Log__c> lstLog = [select Id from Log__c];
        //system.assert(lstLog.size() != 0, 'Log record is not Inserted');
        
    }

    //Verify Amex validation Rules
    static TestMethod void testNonAdminAmexCreation(){
        Account objAcc = [Select Id From Account where Active__c = true];
        List<Product_Registration__c> lstObjProdReg = new List<Product_Registration__c>();
        Product_Registration__c objAmexProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'AEQCC');
        objAmexProdReg.Key_Contact_Office_ID__c ='abc 1233';
        objAmexProdReg.Enrolment_Date__c  = system.today();
        insert objAmexProdReg;
        Integer noOfAmex = [select count() from Product_Registration__c where Account__c =: objAcc.Id  and Type__c = 'AEQCC'];
        //system.assert(noOfAmex == 1, 'Amex is Inserted');
        Test.startTest();
        try{
            objAmexProdReg.Key_Contact_Office_ID__c ='abc 12334';
            update objAmexProdReg;
        }catch(Exception ex){
            //system.assert(ex.getTypeName() == 'System.DmlException', 'Validationrule is not Working');
        }
        Test.stopTest();

        Product_Registration__c objProdReg = [Select Id,Key_Contact_Office_ID__c From Product_Registration__c where Account__c =: objAcc.Id  and Type__c = 'AEQCC'];
        system.debug('objAmexProdRegEEEEEEEEEE'+objProdReg);
        //system.assert(objProdReg.Key_Contact_Office_ID__c == 'abc 1233', 'Amex is Updated by Non Data admin User');
    }

    //Verify Amex avlidation Rules
    static TestMethod void testAdminAmexCreation(){
        Account objAcc = [Select Id, Amex__c from Account LIMIT 1];
        List<user> lstUserUpdate = new List<User>();
        List<User> lstUser = TestUtilityDataClassQantas.getUsers('Data Administrator', 'MAS Team', 'QF-DOM-Sales-SME-QIS-Operations');
        system.assert(lstUser[0].Id != Null, 'User list is not Inserted');
        system.assert(lstUser.size()==2, 'List size is small');

        User objUser = lstUser[0];
        objUser.Id = lstUser[0].Id;
        objUser.IsActive = true;
        objUser.Email = 'test@QIs.com';
        lstUserUpdate.add(objUser);
        
        update lstUserUpdate;
        User objActiveUser = [select Id, UserRoleId from User where Id =: objUser.Id ];
        system.assert(objActiveUser.UserRoleId != Null, 'User Role is Null');
        
        Test.startTest();
        system.runAs(objActiveUser){
            Product_Registration__c objQBDProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'AEQCC');
            insert objQBDProdReg;
        }
        Test.stopTest();
        Integer noOfAmex = [select count() from Product_Registration__c where Account__c =: objAcc.Id  and Type__c = 'AEQCC'];
        system.assert(noOfAmex == 1, 'Second Amex is Inserted');
        objAcc = [Select Id, Amex__c from Account LIMIT 1];
        system.assert(objAcc.Amex__c == true,'Amex is not set to true');       
    }

    //Verify Amex avlidation Rules
    static TestMethod void CreateSecondAmexExceptionTest(){
        Account objAcc = [Select Id, Amex__c from Account LIMIT 1];
        
        List<user> lstUserUpdate = new List<User>();
        List<User> lstUser = TestUtilityDataClassQantas.getUsers('Data Administrator', 'MAS Team', 'QF-DOM-Sales-SME-QIS-Operations');
        system.assert(lstUser[0].Id != Null, 'User list is not Inserted');
        system.assert(lstUser.size()==2, 'List size is small');

        User objUser = lstUser[0];
        objUser.Id = lstUser[0].Id;
        objUser.IsActive = true;
        objUser.Email = 'test@QIs.com';
        lstUserUpdate.add(objUser);
        
        update lstUserUpdate;
        User objActiveUser = [select Id, UserRoleId from User where Id =: objUser.Id ];
        system.assert(objActiveUser.UserRoleId != Null, 'User Role is Null');

        Test.startTest();
        system.runAs(objActiveUser){
            Product_Registration__c objQBDProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'AEQCC');
            insert objQBDProdReg;
            Product_Registration__c objQBDProdRegs = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'AEQCC');
            try{
                insert objQBDProdRegs;
            }catch(Exception ex){
                system.assert(ex.getTypeName() == 'System.DmlException', 'Validationrule is not Working');
            }

        }
        Test.stopTest();
    }

    //Method to check case creation when from Multiple Active QBR Product are added for an Account Exception
    static TestMethod void testCreateCaseOnMultipleActiveQBRException(){
        List<QantasConfigData__c> recType = [select Id from QantasConfigData__c where Name = 'Case SystemAdmin RecordType'];
        delete recType;

        Account objAcc = [Select Id From Account where Active__c = true];
        List<Product_Registration__c> lstObjProdReg = new List<Product_Registration__c>();
        Product_Registration__c objAcqProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'Acquire');
        objAcqProdReg.Key_Contact_Office_ID__c ='abc 1233';
        objAcqProdReg.Enrolment_Date__c  = system.today();
        lstObjProdReg.add(objAcqProdReg);

        Product_Registration__c objQBDProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'Acquire');
        objQBDProdReg.Key_Contact_Office_ID__c ='abc 1234';
        objAcqProdReg.Enrolment_Date__c  = system.today();
        objQBDProdReg.Membership_Number__c = '12346';
        lstObjProdReg.add(objQBDProdReg);

        Test.startTest();
        insert lstObjProdReg;
        Test.stopTest();

        system.assert(lstObjProdReg[1].Id != Null, 'Product Registration is not Inserted');
        List<Log__c> lstLog = [select Id from Log__c];
        //system.assert(lstLog.size() != 0, 'Log record is not Inserted');
    }

    //Method to cover CalculateAMEXAcceptRejectCode postive 
    static TestMethod void testCalculateAMEXAcceptRejectCodePositive(){
        Account objAcc = [Select Id, Aquire_Override__c From Account where Active__c = true];
        objAcc.Agency__c = 'N';
        update objAcc;
        system.assert(objAcc.Aquire_Override__c == 'N', 'QBR Override is True');
         Product_Registration__c objAmexProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'AEQCC');
        objAmexProdReg.MCA_Number__c ='99999';
        objAmexProdReg.Enrolment_Date__c  = system.today();
        objAmexProdReg.Customer_s_Requested_Choice__c = 'A';
        Test.startTest();
        insert objAmexProdReg;
        Test.stopTest();
        objAcc = [select Id, Amex__c, AMEX_response_Code__c from Account where Id =: objAmexProdReg.Account__c];
        system.assert(objAcc.AMEX_response_Code__c == 'D', 'AMEX Response doen\'t Match');  
        system.assert(objAcc.Amex__c == true, 'AMEX is not set to true');
    }

    //Method to cover CalculateAMEXAcceptRejectCode Exceoption 
    static TestMethod void testCalculateAMEXAcceptRejectCodeException(){
        Account objAcc = [Select Id, Aquire_Override__c From Account where Active__c = true];
        objAcc.Agency__c = 'N';
        update objAcc;
        system.assert(objAcc.Aquire_Override__c == 'N', 'QBR Override is True');
         Product_Registration__c objAmexProdReg = TestUtilityDataClassQantas.createProductRegistration(objAcc.Id, 'AEQCC');
        objAmexProdReg.MCA_Number__c ='99999';
        objAmexProdReg.Enrolment_Date__c  = system.today();
        objAmexProdReg.Customer_s_Requested_Choice__c = 'A';

        QantasConfigData__c objCOnfig  = QantasConfigData__c.getValues('Prd Reg AEQCC Registration Rec Type');
        Delete objCOnfig;

        Test.startTest();
        insert objAmexProdReg;
        Test.stopTest();
        objAcc = [select Id, Amex__c from Account where Id =: objAmexProdReg.Account__c];
        system.assert(objAcc.Amex__c == true, 'AMEX is  set to true');
    }

    //Method to verify exception Handling
    static TestMethod void testProductTriggerException(){
        Test.startTest();
        ProductRegistrationTriggerHelper.processAccountAndOpportunity(Null);
       // ProductRegistrationTriggerHelper.processAMEXEligibility(Null, Null);
        ProductRegistrationTriggerHelper.updateAmexDetailsOnAquire(Null);
        ProductRegistrationTriggerHelper.updateRelatedAquireMembers(Null);
        Test.stopTest();
        
        List<Log__c> lstLog = [select Id from Log__c];
        //system.assert(lstLog.size() != 0, 'Log record is not Inserted');
        
    }
    
}