force-app/main/default/objects/Account/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Customer Account airline level calculated by and received from iFly (Aquire)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account airline level as set by Aquire</inlineHelpText>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <formula>Account.Airline_Level__c</formula>
    <label>Airline Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>IF( ISBLANK( ParentId ) ,  CaseNumber ,  Parent.CaseNumber )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CAP_ID__c.field-meta.xml
<CustomField>
    <fullName>CAP_ID__c</fullName>
    <description>Contact CAP ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <description>CASE Number For loyalty API</description>
    <formula>Case_Number__r.CaseNumber</formula>
    <label>CaseNumber</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: The status of the recovery</description>
    <label>Recovery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Further Action Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replaced Recovery</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submit for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalisation Declined</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/recordTypes/Other_Recovery.recordType-meta.xml
<RecordType>
    <fullName>Other_Recovery</fullName>
    <active>true</active>
    <label>Other Recovery</label>
</RecordType>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/LoyaltyAPIHelperTest.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Benazir Amir/Praveen Sampath
Company:       Capgemini
Description:   Test Class for AssetTrigger Helper
Inputs:
Test Class:    Not Required
************************************************************************************************
History
************************************************************************************************
31-Jan-2018    Praveen Sampath   InitialDesign
-----------------------------------------------------------------------------------------------------------------------*/
@isTest(seeAllData = false)
private class LoyaltyAPIHelperTest {
    
    @testSetup
    static void createTestData(){ 
        Id recoveryRTId = SObjectType.Recovery__c.getRecordTypeInfosByDeveloperName().get('Other_Recovery').getRecordTypeId();
        TestUtilityDataClassQantas.insertQantasConfigData();
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createRecoveryTriggerSetting());
        insert lsttrgStatus;

        List<Qantas_API__c> lstQantas = TestUtilityDataClassQantas.createQantasAPI();
        insert lstQantas;
        //TestUtilityDataClassQantas.insertQantasConfigData();

        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Integration Logs Rec Type','Integration Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('RecoveryStatusApproved','Approved'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('RecoveryStatusFinalised','Finalised'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('RecoveryStatusFinalisation Declined','Finalisation Declined'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('RecoveryType','Qantas Points'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('SubmitForFinalisation','Submit For Finalisation'));
        
        insert lstConfigData;

        //Create Account
        Account objAcc = TestUtilityDataClassQantas.createAccount();
        objAcc.Airline_Level__c = '1';
        objAcc.Active__c = true;
        insert objAcc;
        system.assert(objAcc != Null, 'Account is not inserted');

        //Create Contact
        Contact objContact = TestUtilityDataClassQantas.createContact(objAcc.Id);
        objContact.LastName='ContTest2';
        objContact.CAP_ID__c='710000000017';
        insert objContact;
        system.assert(objContact.Id != Null, 'Contact is not inserted');

        //Create Case
        List<Contact> lstContact = new List<Contact>();
        lstContact.add(objContact);
        String recordType = 'CCC Complaints';
        String type = 'Compliment';
        List<Case> lstCase = TestUtilityDataClassQantas.insertCases(lstContact, recordType, type, 'Qantas.com','','','');
        system.assert(lstCase.size()>0, 'Case List is Zero');
        system.assert(lstCase[0].Id != Null, 'Case is not inserted');

        //Create Recovery
        List<Recovery__c> lstRecovery = TestUtilityDataClassQantas.insertRecoverieswithRecType(lstCase, recoveryRTId, 'New', 'Qantas Points');
        system.assert(lstRecovery.size()>0, 'Recovery List is Zero');
        system.assert(lstRecovery[0].Id != Null, 'Recovery is not inserted');
    }
    
    static TestMethod void invokeLoyaltyAPIPostitiveTest() {
        Recovery__c objRecovery = [select Id, Case_Number__c, CaseNumber__c from Recovery__c where RecordType.DeveloperName='Other_Recovery' limit 1];
        Case objCas = [Select id, status, ownerId from case where Id =: objRecovery.Case_Number__c];
        system.assert(objCas.status != 'Closed', 'Case is Closed');
        system.debug('CaseEEEEEEEEEE'+objCas);

        String Body = '{ "success": true, "message": "Point Accrual information successfully updated", "member": {'+
                      '"memberid": 1900007871, "pointsbalance": 2 }, "othermemberdetails": { "emailid": "kevinliu@qantas.com.au"'+
                      '}, "reference": { "identifier": 787987122 }, "outcome": { "status": "SUCCESS", "reason": 0, "reasoncode": 0'+
                      '}}';
        Map<String, String> mapHeader= new Map<String, String>();
        mapHeader.put('Content-Type', 'application/json');
        
        Test.setMock(HttpCalloutMock.class, new QCC_CAPBookingMock(200, 'Success', Body, mapHeader));
        Test.startTest();
        LoyaltyAPIHelper.invokeLoyaltyAPI('1234576', 10, 'Sampath', objRecovery.CaseNumber__c, objRecovery.Id );
        Test.stopTest();
        Recovery__c newRecovery = [select Id, Status__c from Recovery__c where RecordType.DeveloperName='Other_Recovery' and Id =: objRecovery.Id];
        system.debug('newRecovery.Status__c$$$$$$$$$$'+newRecovery.Status__c);
        //system.assert(newRecovery.Status__c == 'Finalisation Declined', 'Recovery Status is not Updates as Finalized Declined');
    }

    static TestMethod void invokeLoyaltyAPINegativeTest() {
        Recovery__c objRecovery = [select Id, Case_Number__c, CaseNumber__c from Recovery__c where RecordType.DeveloperName='Other_Recovery' limit 1];
        objRecovery.Status__c = 'New';
        update objRecovery;

        String Body = '{ "success": false, "message": "Invalid request", "details": { "reason": "Duplicate Request - entry already exists", "reasoncode": 8025 }}';
        Map<String, String> mapHeader= new Map<String, String>();
        mapHeader.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new QCC_CAPBookingMock(400, 'Bad Request', Body, mapHeader));
        
        Test.startTest();
        //LoyaltyAPIHelper.invokeLoyaltyAPI('1234576', 10, 'Sampath', objRecovery.CaseNumber__c, objRecovery.Id );
        LoyaltyAPIHelper.invokeLoyaltyAPI(null, 10, 'Sampath', objRecovery.CaseNumber__c, objRecovery.Id );
        Test.stopTest();
        Recovery__c newRecovery = [select Id, Status__c from Recovery__c where RecordType.DeveloperName='Other_Recovery' and Id =: objRecovery.Id];
        system.debug('newRecovery.Status__c$$$$$$$$$$'+newRecovery.Status__c);
        system.assert(newRecovery.Status__c == 'Further Action Required', 'Recovery Status is not Updated as Exception');
    }

    static TestMethod void invokeLoyaltyAPIExceptionTest() {
        Recovery__c objRecovery = [select Id, Case_Number__c, CaseNumber__c from Recovery__c where RecordType.DeveloperName='Other_Recovery' limit 1];
        objRecovery.Status__c = 'New';
        update objRecovery;

        String Body = '{ "success": false, "message": "Invalid request", "details": { "reason": "Duplicate Request - entry already exists", "reasoncode": 8025 }}';
        Map<String, String> mapHeader= new Map<String, String>();
        mapHeader.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new QCC_CAPBookingMock(400, 'Bad Request', Body, mapHeader));
        
        Test.startTest();
        LoyaltyAPIHelper.invokeLoyaltyAPI('1234576', 10, 'Sampath', objRecovery.CaseNumber__c, 'abc' );
        Test.stopTest();
        Recovery__c newRecovery = [select Id, Status__c from Recovery__c where RecordType.DeveloperName='Other_Recovery' and Id =: objRecovery.Id];
        system.debug('newRecovery.Status__c$$$$$$$$$$'+newRecovery.Status__c);
        system.assert(newRecovery.Status__c == 'New', 'Recovery Status is not Updates as Open');
        
    }
    
}