force-app/main/default/objects/Account/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Customer Account airline level calculated by and received from iFly (Aquire)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account airline level as set by Aquire</inlineHelpText>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract End Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract Start Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Qantas_Club_Join_Discount_Offer__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Club_Join_Discount_Offer__c</fullName>
    <formula>IF(NOT(ISBLANK(TEXT(Contract__r.Qantas_Club_Join_Discount_Offer__c))),
VALUE(SUBSTITUTE(TEXT(Contract__r.Qantas_Club_Join_Discount_Offer__c), &quot;%&quot;,&quot;&quot;))/100,0)</formula>
    <label>Qantas Club Join Discount Offer</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_Active_Member_Count__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Active_Member_Count__c</fullName>
    <label>Scheme Active Member Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Corporate_Scheme.recordType-meta.xml
<RecordType>
    <fullName>Corporate_Scheme</fullName>
    <active>true</active>
    <description>Record Type for Corporate Scheme Asset</description>
    <label>Corporate Scheme</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Public_Scheme.recordType-meta.xml
<RecordType>
    <fullName>Public_Scheme</fullName>
    <active>true</active>
    <description>Record Type for Public Scheme Asset</description>
    <label>Public Scheme</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agency Manager</fullName>
            </value>
            <value>
                <fullName>Agency Owner</fullName>
            </value>
            <value>
                <fullName>Ambassador / High Commissioner</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager - Agency</fullName>
            </value>
            <value>
                <fullName>Business Development Manager – Corporate</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chancellor</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Charter Key Contact</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of Business Unit</fullName>
            </value>
            <value>
                <fullName>Chief of Finance</fullName>
            </value>
            <value>
                <fullName>Chief of Organisation</fullName>
            </value>
            <value>
                <fullName>Chief of Procurement</fullName>
            </value>
            <value>
                <fullName>Chief of the Organisation</fullName>
            </value>
            <value>
                <fullName>Commercial Director</fullName>
            </value>
            <value>
                <fullName>Commerical Partner Contact</fullName>
            </value>
            <value>
                <fullName>Consultant/agent</fullName>
            </value>
            <value>
                <fullName>Consultant/agent - Senior</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Assistant</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Executive Team Member (non Finance)</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Head of Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Key Traveller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the contact&apos;s job title within the organisation. Please use full description and avoid using abbreviations.
**S&amp;D - max 50 character limit applies.</inlineHelpText>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the end date for the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the start date for the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Qantas_Club_Join_Discount_Offer__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Club_Join_Discount_Offer__c</fullName>
    <inlineHelpText>Qantas Club joining fee / points discount offer</inlineHelpText>
    <label>Qantas Club Join Discount Offer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>5%</fullName>
            </value>
            <value>
                <fullName>6%</fullName>
            </value>
            <value>
                <fullName>7%</fullName>
            </value>
            <value>
                <fullName>14%</fullName>
            </value>
            <value>
                <fullName>21%</fullName>
            </value>
            <value>
                <fullName>38%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/QL_Effective_Tier__c.field-meta.xml
<CustomField>
    <fullName>QL_Effective_Tier__c</fullName>
    <description>Proposal 2-Tier changes CRM - 5209</description>
    <label>Effective Tier</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>QL_Discount_Model__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forecast_MCA_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Forecast_MCA_Revenue__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Made Field Required based on CRM-5337 
Removed Required Field check -FCRM-956</description>
    <inlineHelpText>Including EK spend if joint customer</inlineHelpText>
    <label>Forecast MCA Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/SchemeFees__c/SchemeFees__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Loyalty Holds the Scheme Fees Details</description>
    <label>Scheme Fees</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/FetchSchemeMemberCountAPITest.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Praveen Sampath/Benazir Amir
Company:       Capgemini
Description:   Https callout to fetch the Scheme Active Member Count received from LSL
Inputs:
Test Class:     
************************************************************************************************
History
************************************************************************************************
25-AUG-2017    Praveen Sampath               Initial Design

-----------------------------------------------------------------------------------------------------------------------*/

@isTest(seeAllData = False)
private class FetchSchemeMemberCountAPITest{
    @testSetup
    static void createTestData(){
        //Enable Asset Triggers
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createAssetTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createProductRegTriggerSetting()); 
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContractTriggerSetting());
        insert lsttrgStatus;
        
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg QBD Registration Rec Type','QBD Registration'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Rec Type', 'Aquire Registration'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg AEQCC Registration Rec Type','AEQCC Registration'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Integration Logs Rec Type','Integration Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Asset Public Scheme Rec Type','Public Scheme'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Asset Corporate Scheme Rec Type','Corporate Scheme'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Status','Active'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('GST Rate NZD','15'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('GST Rate AUD','10'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('SchemesPointRoundOffNumber','500'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('AssetHeaderName','Basic    '));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('AssetStatusCode','200'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('createIntegrationLogSchemeMemCountAPI','Yes'));
        insert lstConfigData;
        
        //Insert Scheme Fees Setting
        List<SchemeFees__c> lstSchemeData = new List<SchemeFees__c>();
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee1', 420, 65000, 'AUD', 60000, 420, 750, null,  null,200,'Corporate Scheme'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee2', 420, 65000, 'NZD', 60000, 420, 750, null,  null,200,'Corporate Scheme'));
        //lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee3', 420, 65000, '000', 60000, 420, 750, null,  null,200,'Corporate Scheme'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee4', 420, 65000, 'AUD', 60000, 420, 750, 150,  1500,200,'Public Scheme'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee5', 420, 65000, 'NZD', 60000, 420, 750, 150,  1500,200,'Public Scheme'));
        //lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee6', 420, 65000, '000', 60000, 420, 750, 150,  1500,200,'Public Scheme'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee7', 420, 65000, 'AUD', 60000, 420, 750, 150,  1500,200,'Retail'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee8', 420, 65000, 'NZD', 60000, 420, 750, 150,  1500,200,'Retail'));
        //lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee9', 420, 65000, '000', 60000, 420, 750, 150,  1500,200,'Retail'));
        insert lstSchemeData; 
        
        //Enable Validation
        TestUtilityDataClassQantas.createEnableValidationRuleSetting(); 
        
        //Create Account 
        Account objAcc = TestUtilityDataClassQantas.createAccount(); 
        objAcc.Airline_Level__c = '1';
        objAcc.Active__c = true;
        insert objAcc;
        system.assert(objAcc.Id != Null, 'Account is not inserted');
        
        //Create Contact
        Contact objContact = TestUtilityDataClassQantas.createContact(objAcc.Id);
        objContact.LastName='ContTest2';
        objContact.FirstName = 'Sample';
        objContact.Job_Role__c ='BDM';
        objContact.Job_Title__c ='Developer';
        objContact.Phone='8907654321';
        objContact.Email='abc@gmail.com';
        objContact.MailingCountry = 'AU';
        objContact.MailingStreet = 'xyz';
        objContact.MailingCity = 'abc';
        objContact.MailingState = 'VIC';
        objContact.MailingPostalCode = '123456';
        objContact.Salutation ='Mr.';
        insert objContact;
        system.assert(objContact.Id != Null, 'Contact is not inserted');
        
        //Create Opportunity
        Opportunity objOppty = TestUtilityDataClassQantas.CreateOpportunity(objAcc.Id);
        objOppty.Name='OppTest2';
        objOppty.Type='Business and Government';
        objOppty.Forecast_MCA_Revenue__c=20000;
        insert objOppty;
        system.assert(objOppty.Id != Null, 'Opportunity is not inserted');
        
        //Create Contract
        List<Contract__c> lstContract = new List<Contract__c>();
        Contract__c objContract = TestUtilityDataClassQantas.createContract(objAcc.Id,objOppty.Id);
        objContract.CurrencyIsoCode='AUD';
        objContract.Name = 'TestContracts';
        objContract.Qantas_Club_Join_Discount_Offer__c = '7%';
        objContract.Qantas_Club_Join_Discount_Offer__c = '21%';
        objContract.QL_Effective_Tier__c='Tier 1';
        objContract.Contract_Start_Date__c = system.today().addDays(-200);
        objContract.Contract_End_Date__c = system.today().addDays(200);
        lstContract.add(objContract);
        insert lstContract;
        system.assert(objContract.Id != Null, 'Contract is not inserted');
        
        //Create Asset 
        List<Asset> lstAsset = new List<Asset>();
        for(Integer i=0;i<50;i++){
            lstAsset.add(TestUtilityDataClassQantas.createAsset(objAcc.Id,objContact.Id, objContract.Id,'Corporate Scheme','Coordinator'));
            lstAsset.add(TestUtilityDataClassQantas.createAsset(objAcc.Id,objContact.Id, objContract.Id,'Public Scheme','Individual'));
        }
        insert lstAsset;
    }
    
    private static testmethod void FetchSchemeMemberCountAPITPostiveResponce() {
        String resBody = FetchSchemeMemberCountAPITest.postiveBody();
        Map<String, String> mapHeader = new Map<String, String>();
        mapHeader.put('Content-Type', 'application/json');
        FetchSchemeMemberCountAPIMock postiveMock = new FetchSchemeMemberCountAPIMock(200,'OK', resBody, mapHeader);
        Test.setMock(HttpCalloutMock.class, postiveMock);
        Test.startTest();
        FetchSchemeMemberCountAPI.getActiveMemberCount();
        Test.stopTest();
        
        Id corpSchemeRecTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Corporate_Scheme').getRecordTypeId();
        Id publicSchemeRecTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Public_Scheme').getRecordTypeId();            
        for(Asset objAsset: [select Id, Scheme_Active_Member_Count__c from Asset where RecordTypeId=:corpSchemeRecTypeId OR RecordTypeId=:publicSchemeRecTypeId]){
            //system.assert(objAsset.Scheme_Active_Member_Count__c == 9, 'Asset Count is not Updated');
        }
    }
    
    private static testmethod void FetchSchemeMemberCountAPITNegativeResponce() {
        Map<String, String> mapHeader = new Map<String, String>();
        mapHeader.put('Content-Type', 'application/json');
        FetchSchemeMemberCountAPIMock postiveMock = new FetchSchemeMemberCountAPIMock(400,'FAILED', '', mapHeader);
        Test.setMock(HttpCalloutMock.class, postiveMock);
        Test.startTest();
        FetchSchemeMemberCountAPI.getActiveMemberCount();
        Test.stopTest();
        List<Log__c> lstLog = [select Id from Log__c];
        system.assert(lstLog.size() != 1, 'Log record is not Inserted');
    }
    
    private static testmethod void FetchSchemeMemberCountAPITExceptionResponce() {
        String resBody = FetchSchemeMemberCountAPITest.exceptionBody();
        Map<String, String> mapHeader = new Map<String, String>();
        mapHeader.put('Content-Type', 'application/json');
        FetchSchemeMemberCountAPIMock postiveMock = new FetchSchemeMemberCountAPIMock(200,'OK', resBody, mapHeader);
        Test.setMock(HttpCalloutMock.class, postiveMock);
        Test.startTest();
        FetchSchemeMemberCountAPI.getActiveMemberCount();
        Test.stopTest();
        List<Log__c> lstLog = [select Id from Log__c];
        system.assert(lstLog.size() != 1, 'Log record is not Inserted');
    }
    
    private static String postiveBody(){
        String resBody = '{"schemes":[';
        for(Asset objAsset: [select Id from Asset]){
            resBody += '{"schemeId":"0000104022","nomineeCount":9,"salesforceId":"';
            resBody += objAsset.Id;
            resBody += '"},';
        }
        resBody = resBody.substring(0, resBody.length()-1);
        resBody += ']}';
        return resBody;
    }
    
    private static String exceptionBody(){
        String resBody = '{"schemes":[';
        for(Asset objAsset: [select Id from Asset]){
            resBody += '{"schemeId":"0000104022","nomineeCount":09,"salesforceId":"';
            resBody += objAsset.Id;
            resBody += '"},';
        }
        resBody = resBody.substring(0, resBody.length()-1);
        resBody += ']}';
        return resBody;
    }
    
}