force-app/main/default/objects/Account/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Customer Account airline level calculated by and received from iFly (Aquire)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account airline level as set by Aquire</inlineHelpText>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/Freight_RecordTypeSeggregation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting designed for Segregation of Trigger Logic based on Record types.</description>
    <label>Freight_RecordTypeSeggregation</label>
</CustomObject>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>It will be used to categorized recordtype as Sales Passenger or Freight.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Category</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ObjectType</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <description>It will contain 18 digit Id of RecordType.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RecordTypeId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Assumed_Tag_Rate_at_Maturity__c.field-meta.xml
<CustomField>
    <fullName>Assumed_Tag_Rate_at_Maturity__c</fullName>
    <description>This field is used to capture percentage values and can have up to 2 decimal points</description>
    <inlineHelpText>Tag rate at the height of program</inlineHelpText>
    <label>Assumed Tag Rate at Maturity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Average_Spend_Per_Customer__c.field-meta.xml
<CustomField>
    <fullName>Average_Spend_Per_Customer__c</fullName>
    <description>Text field to capture dollar values. Values are captured up to 2 decimal points.Values are thousandth separated by commas (,)</description>
    <inlineHelpText>Estimated average annual spend of partnership</inlineHelpText>
    <label>Average Annual Spend Per Customer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Quote or Contract type</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Airfares</fullName>
                <default>true</default>
                <label>Corporate Airfares</label>
            </value>
            <value>
                <fullName>Qantas Business Savings</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>FIFO Scheduled</fullName>
            </value>
            <value>
                <fullName>Spot Rate</fullName>
            </value>
            <value>
                <fullName>Preferred Rate</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Market Rate</fullName>
            </value>
            <value>
                <fullName>DPP Onboarding</fullName>
            </value>
            <value>
                <fullName>RB - Limited Availability Lanes</fullName>
            </value>
            <value>
                <fullName>RB - Special Lane Pricing</fullName>
            </value>
            <value>
                <fullName>RB - New Accounts Tier Assignment</fullName>
            </value>
            <value>
                <fullName>RB - Change in Tier Assignment</fullName>
            </value>
            <value>
                <fullName>RB - Spot Rates</fullName>
            </value>
            <value>
                <fullName>RB - Partner Rates</fullName>
            </value>
            <value>
                <fullName>Freighter</fullName>
            </value>
            <value>
                <fullName>Freighter - Spot Rates</fullName>
            </value>
            <value>
                <fullName>Freighter - SLP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Base__c.field-meta.xml
<CustomField>
    <fullName>Customer_Base__c</fullName>
    <description>This field is used to capture numbers.</description>
    <inlineHelpText>Size of the customer segment eligible for the proposition</inlineHelpText>
    <label>Customer Base</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forecast_MCA_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Forecast_MCA_Revenue__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Made Field Required based on CRM-5337 
Removed Required Field check -FCRM-956</description>
    <inlineHelpText>Including EK spend if joint customer</inlineHelpText>
    <label>Forecast MCA Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Spend_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Spend_Commitment__c</fullName>
    <description>Text field to capture minimum spend commitment in dollars.Values are captured up to 2 decimal points</description>
    <inlineHelpText>Key information around this account for Loyalty</inlineHelpText>
    <label>Minimum Spend Commitment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Points_Per__c.field-meta.xml
<CustomField>
    <fullName>Points_Per__c</fullName>
    <description>This field is used to capture number values and are up to 2 decimal points</description>
    <inlineHelpText>Points issued per $</inlineHelpText>
    <label>Points Per $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Per_Point__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Point__c</fullName>
    <description>This field captures dollar values and are up to 4 decimal points.</description>
    <inlineHelpText>How much an individual point costs (Please enter the value in Dollars)</inlineHelpText>
    <label>Price Per Point excluding GST</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <defaultValue>20000</defaultValue>
    <description>Field to capture currency value and has a default value as 20000</description>
    <inlineHelpText>Additional cost to partner for signing up to a program</inlineHelpText>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Proposed_Term_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Term_of_Agreement__c</fullName>
    <description>Text field for commercial managers to enter the proposed term of agreement</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Term that the contract will observe</inlineHelpText>
    <label>Proposed Term of Agreement</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ramp_up_factor__c.field-meta.xml
<CustomField>
    <fullName>Ramp_up_factor__c</fullName>
    <description>This field is used for Loyalty Commercial Opportunity by Loyalty Commercial Managers.</description>
    <inlineHelpText>Modifies deal value to take into account how long it will take for offer to achieve full market penetration.
Values represented in days.</inlineHelpText>
    <label>Ramp up factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>25%</fullName>
                <isActive>false</isActive>
                <label>25%</label>
            </value>
            <value>
                <fullName>50%</fullName>
                <isActive>false</isActive>
                <label>50%</label>
            </value>
            <value>
                <fullName>75%</fullName>
                <isActive>false</isActive>
                <label>75%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <description>Loyalty Sales commercial field</description>
    <inlineHelpText>Total points expected from partnership</inlineHelpText>
    <label>Total Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Business_and_Government.recordType-meta.xml
<RecordType>
    <fullName>Business_and_Government</fullName>
    <active>true</active>
    <businessProcess>Qantas Sales Process</businessProcess>
    <description>To be used to capture all opportunities for Business and Government</description>
    <label>Business and Government</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Box will be checked if the variation is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Assumed_Tag_Rate_at_Maturity__c.field-meta.xml
<CustomField>
    <fullName>Assumed_Tag_Rate_at_Maturity__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Tag rate at the height of program</inlineHelpText>
    <label>Assumed Tag Rate at Maturity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Minimum_Spend_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Spend_Commitment__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Minimum spend required of partnership</inlineHelpText>
    <label>Minimum Spend Commitment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Points_Per__c.field-meta.xml
<CustomField>
    <fullName>Points_Per__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Points issued per $</inlineHelpText>
    <label>Points Per $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Price_Per_Point__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Point__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>How much an individual point costs</inlineHelpText>
    <label>Price Per Point</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Additional cost to partner for signing up to a program</inlineHelpText>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Proposed_Term_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Term_of_Agreement__c</fullName>
    <description>Loyalty commercial field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Term that the contract will observe</inlineHelpText>
    <label>Proposed Term of Agreement</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Ramp_up_factor__c.field-meta.xml
<CustomField>
    <fullName>Ramp_up_factor__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Percentage of ramp up discount</inlineHelpText>
    <label>Ramp up factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Loyalty commercial field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the contract will start</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Total points expected from partnership</inlineHelpText>
    <label>Total Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of OpportunityTriggerHandler class.
 */
/*----------------------------------------------------------------------------------------------------------------------
Modified By : Venkata Suresh Kumar (TCS Team), 20-May-2026
Desc : Remediated test class failures. Updated afterupdateData() method.
-----------------------------------------------------------------------------------------------------------------------*/
@isTest

public class OpportunityTriggerHandlerTest {
    
  static TestMethod void beforeupdateData() {
                
        //String oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Business_and_Government').getRecordTypeId();
        Id oppRecordTypeId= GenericUtils.getObjectRecordTypeId('Opportunity', 'Business and Government'); 
        Account objAcc = TestUtilityDataClassQantas.createAccount(); 
        objAcc.Airline_Level__c = '1';
        objAcc.Active__c = true;
        insert objAcc;
        
         Freight_RecordTypeSeggregation__c customSettingRecord = new Freight_RecordTypeSeggregation__c();
         
         customSettingRecord = new Freight_RecordTypeSeggregation__c(Name = 'Sample', Category__c = 'Sales', ObjectType__c = 'Opportunity',
                                            RecordTypeId__c = oppRecordTypeId);
                                            
        insert customSettingRecord;
        
        

            Opportunity opp = new Opportunity();
            opp.RecordTypeId = customSettingRecord.RecordTypeId__c;
            opp.AccountId = objAcc.Id;
            opp.Name = 'Opp';
            opp.Start_Date__c = System.today().addDays(-30);
            opp.Proposed_Term_of_Agreement__c = 'text';
            opp.Customer_Base__c = 1000;
            opp.Points_Per__c = 1.45;
            opp.Price_Per_Point__c = 10;
            opp.Assumed_Tag_Rate_at_Maturity__c = 1.45;
            opp.Average_Spend_Per_Customer__c = 1000;
            opp.Amount = 2000;
            //opp.Ramp_up_factor__c = '75';
            opp.Minimum_Spend_Commitment__c = 100;
            opp.Total_Points__c = 20;
            opp.Program_Fee__c = 1000;
            opp.StageName = 'Prospect';
            opp.CloseDate = System.today();
            opp.Type = 'Business and Government';
            opp.CloseDate = Date.Today().addDays(5);
            opp.PushCount__c = NULL;
            opp.Forecast_MCA_Revenue__c=20000;
            
            insert opp;
            
            System.debug('Close Date:' +opp.CloseDate);
            
            system.assert(opp.Id != Null, 'Opportunity is not inserted');
            
            opp.CloseDate = Date.Today().addDays(60);
            
            System.debug('Updated Close Date:' +opp.CloseDate);
            
            update opp;
            
            System.debug('Updated Close Dates:' +opp.CloseDate);
            System.debug('Push Count' +opp.PushCount__c);
    }

    static TestMethod void afterupdateData() {
        
        Id LoyaltyRecordTypeId= GenericUtils.getObjectRecordTypeId('Quote', 'Loyalty Commercial');
        Id oppRecordTypeId= GenericUtils.getObjectRecordTypeId('Opportunity', 'Loyalty Commercial');       

        Account objAcc = TestUtilityDataClassQantas.createAccount(); 
        objAcc.Airline_Level__c = '1';
        objAcc.Active__c = true;
        insert objAcc;
        
        Contact objcontact = new Contact();
        objcontact.FirstName = 'TestContact-Loyalty';
        objcontact.LastName = objAcc.Name;
        objcontact.Business_Types__c = 'Loyalty';
        objcontact.Email = 'test923@abc.com';
        insert objcontact;

            Opportunity opp = new Opportunity();
            opp.RecordTypeId = oppRecordTypeId;
            opp.AccountId = objAcc.Id;
            opp.Name = 'Opp';
            opp.Start_Date__c = System.today().addDays(-30);
            opp.Proposed_Term_of_Agreement__c = 'text';
            opp.Customer_Base__c = 1000;
            opp.Points_Per__c = 1.45;
            opp.Price_Per_Point__c = 10;
            opp.Contact__c = objcontact.Id;
            opp.Assumed_Tag_Rate_at_Maturity__c = 1.45;
            opp.Average_Spend_Per_Customer__c = 1000;
            opp.Amount = 2000;
            opp.Ramp_up_factor__c = '75';
            opp.Minimum_Spend_Commitment__c = 100;
            opp.Total_Points__c = 20;
            opp.Program_Fee__c = 1000;
            opp.StageName = 'Prospect';
            opp.CloseDate = System.today();
            opp.Type = 'Business and Government';
            opp.CloseDate = Date.Today().addDays(5);
            opp.Forecast_MCA_Revenue__c=20000;
            
            insert opp;
            
            Quote qt = new Quote();
            
            qt.RecordTypeId = LoyaltyRecordTypeId;
            qt.OpportunityId = opp.Id;
            qt.Name = opp.Name;
            qt.Start_Date__c = opp.Start_Date__c;
            qt.Proposed_Term_of_Agreement__c = opp.Proposed_Term_of_Agreement__c;
            qt.Price_Per_Point__c = opp.Price_Per_Point__c;
            qt.Points_Per__c = opp.Points_Per__c;
            qt.Average_Annual_Spend_Per_Customer__c = opp.Average_Spend_Per_Customer__c;
            qt.Turnover__c = opp.Turnover__c;
            qt.Assumed_Tag_Rate_at_Maturity__c = opp.Assumed_Tag_Rate_at_Maturity__c;
            qt.Amount__c = opp.Amount;
            qt.Ramp_up_factor__c = opp.Ramp_up_factor__c;
            qt.Minimum_Spend_Commitment__c = opp.Minimum_Spend_Commitment__c;
            qt.Total_Points__c = opp.Total_Points__c;
            qt.Total_Program_Amount__c = opp.Total_Program_Amount__c;
            qt.Program_Fee__c = opp.Program_Fee__c;
            qt.Active__c = true;
            qt.ContactId = objcontact.Id;
            qt.Rate_Valid_after_acceptance_until__c=Date.today(); //CRM-11408 test class fix
            
            insert qt;
          
            IsRecursive.run = true; 
            opp.StageName = 'Negotiate';
            update opp;
        }
}