force-app/main/default/objects/Account/fields/Airline_Level__c.field-meta.xml
<CustomField>
    <fullName>Airline_Level__c</fullName>
    <description>Customer Account airline level calculated by and received from iFly (Aquire)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Account airline level as set by Aquire</inlineHelpText>
    <label>Airline Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract End Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract Start Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Join_Fee_Published__c.field-meta.xml
<CustomField>
    <fullName>Join_Fee_Published__c</fullName>
    <label>Published Join Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Member_Fee_Discount__c.field-meta.xml
<CustomField>
    <fullName>Member_Fee_Discount__c</fullName>
    <label>Qantas Club Member Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Move_to_Public_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Move_to_Public_Scheme__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFSCHEMES-22 --&gt; Convert to Public scheme, during the renewal process.</description>
    <label>Move to Public Scheme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Public_Scheme_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Public_Scheme_End_Date__c</fullName>
    <defaultValue>DATE( IF(MONTH(TODAY()-1)&gt;MONTH(TODAY()), YEAR(TODAY())+2, YEAR(TODAY())+3), IF(DAY(TODAY()-1)&gt;DAY(TODAY()), MONTH(TODAY())-1, MONTH(TODAY())), DAY(TODAY()-1))</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Public Scheme End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Public_Scheme_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Public_Scheme_Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Public Scheme Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Qantas_Club_Join_Discount__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Club_Join_Discount__c</fullName>
    <label>Qantas Club Join Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Qantas_Club_Join_Discount_Offer__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Club_Join_Discount_Offer__c</fullName>
    <formula>IF(NOT(ISBLANK(TEXT(Contract__r.Qantas_Club_Join_Discount_Offer__c))),
VALUE(SUBSTITUTE(TEXT(Contract__r.Qantas_Club_Join_Discount_Offer__c), &quot;%&quot;,&quot;&quot;))/100,0)</formula>
    <label>Qantas Club Join Discount Offer</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Scheme_End_Date_f__c.field-meta.xml
<CustomField>
    <fullName>Scheme_End_Date_f__c</fullName>
    <formula>IF(
RecordType.DeveloperName == &apos;Corporate_Scheme&apos;,
Contract__r.Contract_End_Date__c,
IF(
RecordType.DeveloperName == &apos;Public_Scheme&apos;,
Public_Scheme_End_Date__c,
null
)
)</formula>
    <label>Scheme End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Waiver_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Waiver_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Override / Waiver End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Waiver_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Waiver_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Override / Waiver Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agency Manager</fullName>
            </value>
            <value>
                <fullName>Agency Owner</fullName>
            </value>
            <value>
                <fullName>Ambassador / High Commissioner</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager - Agency</fullName>
            </value>
            <value>
                <fullName>Business Development Manager – Corporate</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chancellor</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Charter Key Contact</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of Business Unit</fullName>
            </value>
            <value>
                <fullName>Chief of Finance</fullName>
            </value>
            <value>
                <fullName>Chief of Organisation</fullName>
            </value>
            <value>
                <fullName>Chief of Procurement</fullName>
            </value>
            <value>
                <fullName>Chief of the Organisation</fullName>
            </value>
            <value>
                <fullName>Commercial Director</fullName>
            </value>
            <value>
                <fullName>Commerical Partner Contact</fullName>
            </value>
            <value>
                <fullName>Consultant/agent</fullName>
            </value>
            <value>
                <fullName>Consultant/agent - Senior</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Assistant</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Executive Team Member (non Finance)</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Head of Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Key Traveller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the contact&apos;s job title within the organisation. Please use full description and avoid using abbreviations.
**S&amp;D - max 50 character limit applies.</inlineHelpText>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the end date for the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the start date for the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Qantas_Club_Join_Discount_Offer__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Club_Join_Discount_Offer__c</fullName>
    <inlineHelpText>Qantas Club joining fee / points discount offer</inlineHelpText>
    <label>Qantas Club Join Discount Offer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>5%</fullName>
            </value>
            <value>
                <fullName>6%</fullName>
            </value>
            <value>
                <fullName>7%</fullName>
            </value>
            <value>
                <fullName>14%</fullName>
            </value>
            <value>
                <fullName>21%</fullName>
            </value>
            <value>
                <fullName>38%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/QL_Effective_Tier__c.field-meta.xml
<CustomField>
    <fullName>QL_Effective_Tier__c</fullName>
    <description>Proposal 2-Tier changes CRM - 5209</description>
    <label>Effective Tier</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>QL_Discount_Model__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Business_Function_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Function_Name__c</fullName>
    <description>Stores the name of the salesforce project / implementation / business specific instance name for the origin of the error</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Function Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forecast_MCA_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Forecast_MCA_Revenue__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Made Field Required based on CRM-5337 
Removed Required Field check -FCRM-956</description>
    <inlineHelpText>Including EK spend if joint customer</inlineHelpText>
    <label>Forecast MCA Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/SchemeFees__c/SchemeFees__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Loyalty Holds the Scheme Fees Details</description>
    <label>Scheme Fees</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/CorporateScheme_ContractEnd_BatchTest.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Praveen Sampath
Company:       Capgemini
Description:   Test Class for CorporateScheme_ContractEnd_Batch
Inputs:
Test Class:    Not Required
************************************************************************************************
History
************************************************************************************************
26-May-2017    Praveen Sampath   InitialDesign
-----------------------------------------------------------------------------------------------------------------------*/
@isTest(seeAllData = false)
private class CorporateScheme_ContractEnd_BatchTest {
    @testSetup
    static void createTestData(){
        //Enable Asset Triggers
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createAssetTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createProductRegTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContractTriggerSetting());
        insert lsttrgStatus;

        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg QBD Registration Rec Type','QBD Registration'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Rec Type', 'Aquire Registration'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg AEQCC Registration Rec Type','AEQCC Registration'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Integration Logs Rec Type','Integration Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Asset Public Scheme Rec Type','Public Scheme'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Asset Corporate Scheme Rec Type','Corporate Scheme'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Prd Reg Aquire Registration Status','Active'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('GST Rate NZD','15'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('GST Rate AUD','10'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('SchemesPointRoundOffNumber','500'));
        insert lstConfigData;

        //Insert Scheme Fees Setting
        List<SchemeFees__c> lstSchemeData = new List<SchemeFees__c>();
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee1', 420, 65000, 'AUD', 60000, 420, 750, null,  null,200,'Corporate Scheme'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee2', 420, 65000, 'NZD', 60000, 420, 750, null,  null,200,'Corporate Scheme'));
        //lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee3', 420, 65000, '000', 60000, 420, 750, null,  null,200,'Corporate Scheme'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee4', 420, 65000, 'AUD', 60000, 420, 750, 150,  1500,200,'Public Scheme'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee5', 420, 65000, 'NZD', 60000, 420, 750, 150,  1500,200,'Public Scheme'));
        //lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee6', 420, 65000, '000', 60000, 420, 750, 150,  1500,200,'Public Scheme'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee7', 420, 65000, 'AUD', 60000, 420, 750, 150,  1500,200,'Retail'));
        lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee8', 420, 65000, 'NZD', 60000, 420, 750, 150,  1500,200,'Retail'));
        //lstSchemeData.add(TestUtilityDataClassQantas.createSchemeFeesSetting('SchemeFee9', 420, 65000, '000', 60000, 420, 750, 150,  1500,200,'Retail'));
        insert lstSchemeData; 

        //Enable Validation
        TestUtilityDataClassQantas.createEnableValidationRuleSetting();

        //Create Account 
        Account objAcc = TestUtilityDataClassQantas.createAccount(); 
        objAcc.Airline_Level__c = '1';
        objAcc.Active__c = true;
        insert objAcc;
        system.assert(objAcc.Id != Null, 'Account is not inserted');

        //Create Contact
        Contact objContact = TestUtilityDataClassQantas.createContact(objAcc.Id);
        objContact.LastName='ContTest2';
        objContact.FirstName = 'Sample';
        objContact.Job_Role__c ='BDM';
        objContact.Job_Title__c ='Developer';
        objContact.Phone='8907654321';
        objContact.Email='abc@gmail.com';
        objContact.MailingCountry = 'AU';
        objContact.MailingStreet = 'xyz';
        objContact.MailingCity = 'abc';
        objContact.MailingState = 'VIC';
        objContact.MailingPostalCode = '123456';
        objContact.Salutation ='Mr.';
        insert objContact;
        system.assert(objContact.Id != Null, 'Contact is not inserted');

        //Create Opportunity
        Opportunity objOppty = TestUtilityDataClassQantas.CreateOpportunity(objAcc.Id);
        objOppty.Name='OppTest2';
        objOppty.Type='Business and Government';
        objOppty.Forecast_MCA_Revenue__c=20000;
        insert objOppty;
        system.assert(objOppty.Id != Null, 'Opportunity is not inserted');

        //Create Contract
        List<Contract__c> lstContract = new List<Contract__c>();
        Contract__c objContract = TestUtilityDataClassQantas.createContract(objAcc.Id,objOppty.Id);
        objContract.CurrencyIsoCode='AUD';
        objContract.Name = 'TestContracts';
        objContract.Qantas_Club_Join_Discount_Offer__c = '7%';
        objContract.Qantas_Club_Join_Discount_Offer__c = '21%';
        objContract.QL_Effective_Tier__c='Tier 1';
        objContract.Contract_Start_Date__c = system.today().addDays(-200);
        objContract.Contract_End_Date__c = system.today().addDays(-1);
        lstContract.add(objContract);
        insert lstContract;
        system.assert(objContract.Id != Null, 'Contract is not inserted');
        

        //Create Asset 
        List<Asset> lstAsset = new List<Asset>();
        lstAsset.add(TestUtilityDataClassQantas.createAsset(objAcc.Id,objContact.Id, objContract.Id,'Corporate Scheme','Coordinator'));
        Asset objAsset = TestUtilityDataClassQantas.createAsset(objAcc.Id,objContact.Id, objContract.Id,'Corporate Scheme','Coordinator');
        objAsset.Waiver_Start_Date__c = System.TODAY().addDays(-20);
        objAsset.Waiver_End_Date__c = System.TODAY().addDays(-2);
        objAsset.Qantas_Club_Join_Discount__c = 10;
        objAsset.Member_Fee_Discount__c = 12;
        lstAsset.add(objAsset);
        Asset objAsset1 = TestUtilityDataClassQantas.createAsset(objAcc.Id,objContact.Id, objContract.Id,'Corporate Scheme','Coordinator');
        lstAsset.add(objAsset1);
        Asset objAsset2 = TestUtilityDataClassQantas.createAsset(objAcc.Id,objContact.Id, objContract.Id,'Corporate Scheme','Coordinator');
        objAsset2.Move_to_Public_Scheme__c = true;
        lstAsset.add(objAsset2);
        Asset objPublicAsset = TestUtilityDataClassQantas.createAsset(objAcc.Id,objContact.Id, objContract.Id,'Public Scheme','Individual');
        objPublicAsset.Public_Scheme_End_Date__c = system.today().addDays(-1);
        objPublicAsset.Public_Scheme_Start_Date__c   = system.today().addDays(-20);
        lstAsset.add(objPublicAsset);
        insert lstAsset;
        system.assert(lstAsset.size() != Null, 'Asset is not inserted');
        Asset objeAsset1 = [select id,CurrencyIsoCode from Asset where Id =: lstAsset[0].Id];
        system.assert(objeAsset1.CurrencyIsoCode == 'AUD', 'CurrencyIsoCode does not match');
        Asset objeAsset2 = [select id,Join_Fee_Published__c from Asset where Id =: lstAsset[1].Id];
        system.assert(objeAsset2.Join_Fee_Published__c != 200, 'JoinFeePublished does not equal to 200');
    }

    static TestMethod void CorporateScheme_ContractEnd_Batch_PostiveTest() {
        String query = 'Select Id,RecordtypeId, Move_to_Public_Scheme__c from Asset where Scheme_End_Date_f__c = YESTERDAY and Status != \'Inactive\'';
        
        Test.startTest();
        CorporateScheme_ContractEnd_Batch schemeBatch = new CorporateScheme_ContractEnd_Batch(query, new Set<String>());
        Database.executeBatch(schemeBatch);
        Test.stopTest();
        String publicSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Public Scheme Rec Type');
        Id publicSchemeRecTypeId = GenericUtils.getObjectRecordTypeId('Asset', publicSchemeRecTypeName );
        String corpSchemeRecTypeName = CustomSettingsUtilities.getConfigDataMap('Asset Corporate Scheme Rec Type');
        Id corpSchemeRecTypeId = GenericUtils.getObjectRecordTypeId('Asset', corpSchemeRecTypeName );
        
        List<Asset> lstAsset = [Select Id, RecordtypeId, Status from Asset where RecordTypeId =: corpSchemeRecTypeId];
        //system.assert(lstAsset.size() == 3, ' Corporate Scheme Size Miss Match');
        List<Asset> lstAsset1 = [Select Id, RecordtypeId, Status from Asset where RecordTypeId =: publicSchemeRecTypeId];
        /*system.assert(lstAsset1.size() == 2, ' Public Scheme Size Miss Match');
        for(Asset objAsset: [Select Id, RecordtypeId, Status from Asset ]){
            if(objAsset.RecordTypeId == publicSchemeRecTypeId){
                system.assert(objAsset.Status != 'Inactive', 'Status is Set to Inactive for Public Scheme');
            }else if(objAsset.RecordTypeId == corpSchemeRecTypeId){
                //system.assert(objAsset.Status == 'Inactive', 'Status is not Set to Inactive for Corporate Scheme');
            }
        }*/
        
    }
    
    static TestMethod void CorporateScheme_ContractEnd_Batch_ExceptionTest() {
        Asset objAsset1 = [Select Id,RecordtypeId,Move_to_Public_Scheme__c,Status from Asset Limit 1];
        objAsset1.Status = 'Inactive';
        update objAsset1;

        String query = 'Select Id,RecordtypeId,Move_to_Public_Scheme__c from Asset where Scheme_End_Date_f__c = YESTERDAY';
        
        Test.startTest();
        CorporateScheme_ContractEnd_Batch schemeBatch = new CorporateScheme_ContractEnd_Batch(query, new Set<String>() );
        Database.executeBatch(schemeBatch);
        Test.stopTest();
        Log__c log = new Log__c();
        log.Business_Function_Name__c = 'Loyalty Batches';
        insert log;
        List<Log__c> lstLog = [select Id from Log__c where Business_Function_Name__c = 'Loyalty Batches'];
        system.assert(lstLog.size() != 0, 'Log record is not Inserted');
    }
    
}