force-app/main/default/objects/Account/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Ranking__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ranking__c</fullName>
    <description>Freight - To store the value to display the Customer Rank</description>
    <label>Customer Ranking</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sentiment__c.field-meta.xml
<CustomField>
    <fullName>Sentiment__c</fullName>
    <description>If the company key decision makers attitude towards qantas</description>
    <inlineHelpText>Current level of satisfaction of the client with Qantas</inlineHelpText>
    <label>Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Airport_Code__c/Airport_Code__c.object-meta.xml
<CustomObject>
    <description>To capture the Airport Code</description>
    <label>Airport Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport_Code__c/fields/Freight_Airport_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Freight_Airport_State_Code__c</fullName>
    <description>Freight - records the state code of the Port</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport State Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Code__c/fields/Freight_Station_Name__c.field-meta.xml
<CustomField>
    <fullName>Freight_Station_Name__c</fullName>
    <description>Freight - Capture the name of the Stations</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Code__c/fields/QF_Freight_Presence__c.field-meta.xml
<CustomField>
    <fullName>QF_Freight_Presence__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Freight - indicates whether Qantas Freight has a presence at this port</description>
    <label>QF Freight Presence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Advice_Method__c.field-meta.xml
<CustomField>
    <fullName>Customer_Advice_Method__c</fullName>
    <description>Freight - Drop down showing which resolution method the caller would prefer to get the feedback ie, phone, email, sms/text, other</description>
    <inlineHelpText>Mandatory field. Select as per customer request</inlineHelpText>
    <label>Preferred customer advice method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>SMS_Text</fullName>
                <label>SMS/Text</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Other (add in Comments)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Freight_Port__c.field-meta.xml
<CustomField>
    <fullName>Freight_Port__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Freight - captures where the freight issue is most likely to be located</description>
    <inlineHelpText>Three letter IATA code - If with AWB#, value will be auto-refreshed from iCargo and will overwrite your manual entry.</inlineHelpText>
    <label>Port</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Airport_Code__c.QF_Freight_Presence__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Airport_Code__c</referenceTo>
    <relationshipLabel>Cases (City Code)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Procurement/Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/Freight_RecordTypeSeggregation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting designed for Segregation of Trigger Logic based on Record types.</description>
    <label>Freight_RecordTypeSeggregation</label>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QL_FreightRecordtypeAssignmentTest.cls
/***********************************************************************************************************************************

Description: Test Method-Lightning component handler for the FreightRecordtypeAssignment

History:
======================================================================================================================
Name                    Jira        Description                                                 Tag
======================================================================================================================
Karpagam               CRM-3068   Test method LEx-FreightRecordtypeAssignment                T01

Created Date    : 25/05/17 (DD/MM/YYYY)

**********************************************************************************************************************************/
@isTest
private class QL_FreightRecordtypeAssignmentTest { 
    
    @testsetup
    static void createTestData(){
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createCaseTriggerSetting();
        insert lsttrgStatus;
        TestUtilityDataClassQantas.insertQantasConfigData();
        
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Integration Logs Rec Type','Integration Logs'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('RecoveryStatusApproved','Approved'));
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('RecoveryType','Qantas Points'));
        insert lstConfigData;
    }

    static testMethod void validateTestData() {
        
        String caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Claims').getRecordTypeId();
        String accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Freight Account').getRecordTypeId();
        
        TestUtilityDataClassQantas.enableTriggers();
        TestUtilityDataClassQantas.createEnableValidationRuleSetting();
        List<Freight_RecordTypeSeggregation__c> lstfreCusSetting = Freight_TriggerRecordTypeUtility.createAccTrigTestCustomSetting();
        insert lstfreCusSetting;
        
        Airport_Code__c aCode = new Airport_Code__c(Name = 'SYD', QF_Freight_Presence__c =TRUE, Freight_Station_Name__c = 'Sydney', Freight_Airport_State_Code__c  ='NSW');
        insert aCode;
        
        String orgId = UserInfo.getOrganizationId();
        String sandboxName = UserInfo.getUserName().substringAfterLast('.au');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + randomInt;
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.Email = uniqueName + '@qantas.com.au'; 
        u.CompanyName = 'test.com';
        u.Title = 'Test User';
        u.Username = uniqueName + '@test' + sandboxName + '.com'; 
        u.Alias = 'testuser';
        u.CommunityNickname = 'Test User';
        u.TimeZoneSidKey = 'Australia/Sydney';
        u.LocaleSidKey = 'en_AU';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = pf.Id;
        u.LanguageLocaleKey = 'en_US';
        u.CountryCode='AU';
        insert u;
        
        Account testacc = new Account(Name='Test Tcs Account',
                                      Active__c = true,
                                      Type = 'Freight-Country',
                                      Customer_Ranking__c = '5',
                                      Sentiment__c = 'Positive',
                                      OwnerId = u.Id,
                                      RecordTypeId = accRTId);
        insert testacc;
        
        Contact testcon = new Contact(FirstName='Bob',
                                      LastName='Test',
                                      AccountId=testacc.id,
                                      Function__c = 'IT',
                                      Business_Types__c = 'Freight',
                                      Email = 'abc@test.com');
        insert testcon;
        List<Case> testCases = new List<case>();
        Case testcase1 = new Case(AccountId = testacc.id,
                                 ContactId = testcon.id,
                                 RecordTypeId = caseRTId,
                                 Subject = 'the case',
                                 Description = 'test desc',
                                 Status = 'Open',
                                 Priority = 'Medium',
                                 Origin = 'Phone',
                                 Type = 'Customer Query',
                                 Customer_Advice_Method__c = 'Email',
                                 Freight_Port__c = aCode.Id
                                );
        testCases.add(testcase1);
        
        Case testcase2 = new Case(AccountId = testacc.id,
                                 ContactId = testcon.id,
                                 RecordTypeId = caseRTId,
                                 Subject = 'the case',
                                 Description = 'test desc',
                                 Status = 'Closed',
                                 Priority = 'Medium',
                                 Origin = 'Phone',
                                 Type = 'Customer Query',
                                 Customer_Advice_Method__c = 'Email',
                                 Freight_Port__c = aCode.Id
                                );
        testCases.add(testcase2);
        
        
        insert testCases; 
        
        system.runAs(u) {
            Test.startTest();               
            try{
                //  Database.Update(conList);
                //Invoke the controller Method
                QL_FreightRecordtypeAssignment.getlistrecType();
                QL_FreightRecordtypeAssignment.reassignToRecordType(testcases[0].Id,testcases[0].Type);
                QL_FreightRecordtypeAssignment.reassignToRecordType(testcases[1].Id,testcases[1].Type);
                
            }catch(Exception e){
                System.debug('Error Occured: '+e.getMessage());
            } 
            Test.stopTest(); 
        }
    }

    // CRM-10461: Added test method to cover query exception
    static testMethod void testQueryException() {
        
        String caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Claims').getRecordTypeId();
        String accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Freight Account').getRecordTypeId();

        TestUtilityDataClassQantas.enableTriggers();
        TestUtilityDataClassQantas.createEnableValidationRuleSetting();
        List<Freight_RecordTypeSeggregation__c> lstfreCusSetting = Freight_TriggerRecordTypeUtility.createAccTrigTestCustomSetting();
        insert lstfreCusSetting;
        
        Airport_Code__c aCode = new Airport_Code__c(Name = 'SYD', QF_Freight_Presence__c =TRUE, Freight_Station_Name__c = 'Sydney', Freight_Airport_State_Code__c  ='NSW');
        insert aCode;
        
         String orgId = UserInfo.getOrganizationId();
        String sandboxName = UserInfo.getUserName().substringAfterLast('.au');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + randomInt;
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.Email = uniqueName + '@qantas.com.au'; 
        u.CompanyName = 'test.com';
        u.Title = 'Test User';
        u.Username = uniqueName + '@test' + sandboxName + '.com'; 
        u.Alias = 'testuser';
        u.CommunityNickname = 'Test User';
        u.TimeZoneSidKey = 'Australia/Sydney';
        u.LocaleSidKey = 'en_AU';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = pf.Id;
        u.LanguageLocaleKey = 'en_US';
        u.CountryCode='AU';
        insert u;

        Account testacc = new Account(Name='Test Tcs Account',
                                      Active__c = true,
                                      Type = 'Freight-Country',
                                      Customer_Ranking__c = '5',
                                      Sentiment__c = 'Positive',
                                      OwnerId = u.Id,
                                      RecordTypeId = accRTId);
        insert testacc;
        
        Contact testcon = new Contact(FirstName='Bob',
                                      LastName='Test',
                                      AccountId=testacc.id,
                                      Function__c = 'IT',
                                      Business_Types__c = 'Freight',
                                      Email = 'abc@test.com');
        insert testcon;
        
        Case testcase = new Case(AccountId = testacc.id,
                                 ContactId = testcon.id,
                                 RecordTypeId = caseRTId,
                                 Subject = 'the case',
                                 Description = 'test desc',
                                 Status = 'Open',
                                 Priority = 'Medium',
                                 Origin = 'Phone',
                                 Type = 'Customer Query',
                                 Customer_Advice_Method__c = 'Email',
                                 Freight_Port__c = aCode.Id
                                );
        insert testcase; 
      
        system.runAs(u) {
            Test.startTest();               
            try{
                QL_FreightRecordtypeAssignment.getlistrecType();
                QL_FreightRecordtypeAssignment.reassignToRecordType(testcase.Id,testcase.Type);
            }catch(Exception e){
                System.debug('Error Occured: '+e.getMessage());
            } 
            Test.stopTest(); 
        }
    }
    
    
    
}