force-app/main/default/objects/Account/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Phone_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone Country Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Code__c/Airport_Code__c.object-meta.xml
<CustomObject>
    <description>To capture the Airport Code</description>
    <label>Airport Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Phone_Country_Code__c</fullName>
    <description>Field for Data Migration</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Country Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_Preferred_Contact_Channel__c.field-meta.xml
<CustomField>
    <fullName>QCC_Preferred_Contact_Channel__c</fullName>
    <description>Value comes from the Loyalty platform event reflecting customer&apos;s preference for day-prior contact</description>
    <inlineHelpText>Customer&apos;s preference for day-prior contact</inlineHelpText>
    <label>Preferred VIP Service Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_Qantas_Host_Always_Call__c.field-meta.xml
<CustomField>
    <fullName>QCC_Qantas_Host_Always_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Qantas Host Always Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QCC_First_Host__c/QCC_First_Host__c.object-meta.xml
<CustomObject>
    <description>Container for creating records for the First Host process</description>
    <label>Qantas Host</label>
    <nameField>
        <displayFormat>FH{00000000}</displayFormat>
        <label>First Host Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qantas Hosts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Cabin__c.field-meta.xml
<CustomField>
    <fullName>QCC_Cabin__c</fullName>
    <description>Value comes from Pre-Departure platform event. This is extracted as part of the Qantas Host report.</description>
    <label>Cabin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
                <label>First</label>
            </value>
            <value>
                <fullName>J</fullName>
                <label>Business</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Premium Economy</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Economy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Carrier_Code__c.field-meta.xml
<CustomField>
    <fullName>QCC_Carrier_Code__c</fullName>
    <defaultValue>&quot;QF&quot;</defaultValue>
    <description>Value comes from Pre-Departure platform event. This is referenced by the Email Alert for first host is sent.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Flight_No__c.field-meta.xml
<CustomField>
    <fullName>QCC_Flight_No__c</fullName>
    <description>Value comes from Pre-Departure platform event. This is referenced by the Email Alert for first host is sent.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight No</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Preferred_Contact_Channel__c.field-meta.xml
<CustomField>
    <fullName>QCC_Preferred_Contact_Channel__c</fullName>
    <formula>TEXT(QCC_First_Host_Contact__r.QCC_Preferred_Contact_Channel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preferred VIP Service Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_TECH_SMS_Need_To_Send__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_SMS_Need_To_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine if the SMS is needed to be send to the customer.</description>
    <inlineHelpText>This field is used to determine if the SMS is needed to be send to the customer.</inlineHelpText>
    <label>SMS Need to Send?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_QantasHostSendSMSSchedulableTest.cls
/*********************************************************************************
Name         : QCC_QantasHostSendSMSSchedulableTest
Created By   : Raymart Airon Tolentino
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 12 November 2019
Usages       : This class is used for the code coverage of the apex class below:
			   - QCC_QantasHostSendSMSSchedulable

Modified By : Venkata Suresh Kumar (TCS Team), 19-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method. Added Test.start and Test.Stop methods
*********************************************************************************/
@isTest
public class QCC_QantasHostSendSMSSchedulableTest {
	@testSetup
    static void setupTestData(){
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        List<Trigger_Status__c> customSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusCase', null, null, null, null);
        insert customSettingList;

        //Create test data for Flight Event object
        List<Trigger_Status__c> customSettingListQantasHost = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusQantasHost', null, null, null, null);
        insert customSettingListQantasHost;

        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        List<Contact> contactList = new List<Contact>();
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        
        //QCC_Qantas_Host_Always_Call__c = false
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.RecordTypeId = contactRecordTypeId;
        contactRecord.Frequent_Flyer_Number__c = '000001';
        contactRecord.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord.QCC_Qantas_Host_Always_Call__c = false;
        contactList.add(contactRecord);
        
        //QCC_Qantas_Host_Always_Call__c = true
        Contact contactRecord2 = QCC_TestDataFactory.createContactTestData(2, accountRecord.Id);
        contactRecord2.RecordTypeId = contactRecordTypeId;
        contactRecord2.Frequent_Flyer_Number__c = '000002';
        contactRecord2.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord2.QCC_Qantas_Host_Always_Call__c = true;
        contactList.add(contactRecord2);
        
        //QCC_Qantas_Host_Always_Call__c = false
        //QCC_Preferred_Contact_Channel__c = 'Email'
        Contact contactRecord3 = QCC_TestDataFactory.createContactTestData(3, accountRecord.Id);
        contactRecord3.RecordTypeId = contactRecordTypeId;
        contactRecord3.Frequent_Flyer_Number__c = '000003';
        contactRecord3.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord3.QCC_Qantas_Host_Always_Call__c = false;
        contactRecord3.QCC_Preferred_Contact_Channel__c = 'Email';
        contactRecord3.Email = 'sample@test.com';
        contactRecord3.MobilePhone = '1234123412';
        contactRecord3.Phone_Country_Code__c = '61';
        contactList.add(contactRecord3);
        
        //QCC_Qantas_Host_Always_Call__c = false
        //QCC_Preferred_Contact_Channel__c = 'SMS'
        Contact contactRecord4 = QCC_TestDataFactory.createContactTestData(4, accountRecord.Id);
        contactRecord4.RecordTypeId = contactRecordTypeId;
        contactRecord4.Frequent_Flyer_Number__c = '000004';
        contactRecord4.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord4.QCC_Qantas_Host_Always_Call__c = false;
        contactRecord4.QCC_Preferred_Contact_Channel__c = 'SMS';
        contactRecord4.Email = 'sample@test.com';
        contactRecord4.MobilePhone = '1234123412';
        contactRecord4.Phone_Country_Code__c = '61';
        contactList.add(contactRecord4);
        
        insert contactList;
        
        //Create test data for Qantas API object
        List<Qantas_API__c> qantasAPIRecords = QCC_TestDataFactory.createQantasAPITestDataList();
        insert qantasAPIRecords;
        
        //Create test data for Airport Code to be used in QHost record creation
        Airport_Code__c airportCodeRecord = QCC_TestDataFactory.createAirportCodeTestData();
        insert airportCodeRecord;
        
        //Create test data for Qantas Host
        List<QCC_First_Host__c> qantasHostList = new List<QCC_First_Host__c>();
        QCC_First_Host__c qantasHostRecord = QCC_TestDataFactory.createFirstHostTestData(contactRecord.Id, airportCodeRecord.Id);
        qantasHostRecord.QCC_Flight_No__c = '0001';
        qantasHostRecord.QCC_Carrier_Code__c = 'QF';
        qantasHostList.add(qantasHostRecord);
        
        QCC_First_Host__c qantasHostRecord2 = QCC_TestDataFactory.createFirstHostTestData(contactRecord2.Id, airportCodeRecord.Id);
        qantasHostRecord2.QCC_Flight_No__c = '0009';
        qantasHostRecord2.QCC_Carrier_Code__c = 'QF';
        qantasHostList.add(qantasHostRecord2);
        
        QCC_First_Host__c qantasHostRecord3 = QCC_TestDataFactory.createFirstHostTestData(contactRecord3.Id, airportCodeRecord.Id);
        qantasHostRecord3.QCC_Flight_No__c = '0002';
        qantasHostRecord3.QCC_Carrier_Code__c = 'QF';
        qantasHostRecord3.QCC_Cabin__c = 'P';
        qantasHostRecord3.QCC_TECH_SMS_Need_To_Send__c = true;
        qantasHostList.add(qantasHostRecord3);
        
        QCC_First_Host__c qantasHostRecord4 = QCC_TestDataFactory.createFirstHostTestData(contactRecord4.Id, airportCodeRecord.Id);
        qantasHostRecord4.QCC_Flight_No__c = '0003';
        qantasHostRecord4.QCC_Carrier_Code__c = 'QF';
        qantasHostRecord4.QCC_Cabin__c = 'P';
        qantasHostRecord4.QCC_TECH_SMS_Need_To_Send__c = true;
        qantasHostList.add(qantasHostRecord4);
        
        insert qantasHostList;  
    }
    
    static testmethod void test1(){
		String Body = '{"token_type":"bearer","expires_in":172800,"access_token":"71c6f08c68fac962cf08b4667206043e79a66ef6"}';
		Map<String, String> mapHeader= new Map<String, String>();
		mapHeader.put('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, new QCC_CAPBookingMock(200, 'Success', Body, mapHeader));
        QCC_QantasHostSendSMSSchedulable batchJob = new QCC_QantasHostSendSMSSchedulable(); 
        Test.startTest();
        batchJob.execute(null);
        Test.stopTest();
    }
}