force-app/main/default/objects/Account/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Code__c/Airport_Code__c.object-meta.xml
<CustomObject>
    <description>To capture the Airport Code</description>
    <label>Airport Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport_Code__c/fields/Freight_Station_Name__c.field-meta.xml
<CustomField>
    <fullName>Freight_Station_Name__c</fullName>
    <description>Freight - Capture the name of the Stations</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_RecordTypeSeggregation__c/Freight_RecordTypeSeggregation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting designed for Segregation of Trigger Logic based on Record types.</description>
    <label>Freight_RecordTypeSeggregation</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Forecast_MCA_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Forecast_MCA_Revenue__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Made Field Required based on CRM-5337 
Removed Required Field check -FCRM-956</description>
    <inlineHelpText>Including EK spend if joint customer</inlineHelpText>
    <label>Forecast MCA Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Freight_Destination__c.field-meta.xml
<CustomField>
    <fullName>Freight_Destination__c</fullName>
    <description>Freight - It used for AWB Integration, contains destination.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Freight_Origin__c.field-meta.xml
<CustomField>
    <fullName>Freight_Origin__c</fullName>
    <description>Freight - It used for AWB Integration, contains origin.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Freight.recordType-meta.xml
<RecordType>
    <fullName>Freight</fullName>
    <active>true</active>
    <businessProcess>Freight Sales</businessProcess>
    <description>To be used to capture all opportunities for Qantas Freight</description>
    <label>Freight</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Flat_Rate__c.field-meta.xml
<CustomField>
    <fullName>Flat_Rate__c</fullName>
    <label>Flat Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Freight_Commodity__c.field-meta.xml
<CustomField>
    <fullName>Freight_Commodity__c</fullName>
    <description>Freight - to capture the commodity of the Opportunity</description>
    <inlineHelpText>Popular commodities listed alphabetically</inlineHelpText>
    <label>Commodity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abalone</fullName>
            </value>
            <value>
                <fullName>Aircraft Engines</fullName>
            </value>
            <value>
                <fullName>Aircraft On Ground</fullName>
            </value>
            <value>
                <fullName>Asparagus</fullName>
            </value>
            <value>
                <fullName>Avocados</fullName>
            </value>
            <value>
                <fullName>Baby Poultry</fullName>
            </value>
            <value>
                <fullName>Books/Brochures</fullName>
            </value>
            <value>
                <fullName>Brocolli</fullName>
            </value>
            <value>
                <fullName>Bulk Utilisation, Shipper Consignee Handled Unit</fullName>
            </value>
            <value>
                <fullName>Cheese</fullName>
            </value>
            <value>
                <fullName>Company Materials</fullName>
            </value>
            <value>
                <fullName>Corrosive</fullName>
            </value>
            <value>
                <fullName>Courier Bag Voucher</fullName>
            </value>
            <value>
                <fullName>Crabs</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Deferred Cargo</fullName>
            </value>
            <value>
                <fullName>Density Shipments</fullName>
            </value>
            <value>
                <fullName>Diplomatic Mail</fullName>
            </value>
            <value>
                <fullName>Dry Ice</fullName>
            </value>
            <value>
                <fullName>Eel</fullName>
            </value>
            <value>
                <fullName>Eggs</fullName>
            </value>
            <value>
                <fullName>Fish</fullName>
            </value>
            <value>
                <fullName>Fish/Seafood</fullName>
            </value>
            <value>
                <fullName>Flowers</fullName>
            </value>
            <value>
                <fullName>Flowers/Plants</fullName>
            </value>
            <value>
                <fullName>Foodstuffs</fullName>
            </value>
            <value>
                <fullName>Fruit And Vegetables</fullName>
            </value>
            <value>
                <fullName>General Commodity</fullName>
            </value>
            <value>
                <fullName>Hatching Eggs</fullName>
            </value>
            <value>
                <fullName>Heavy Cargo,150Kg And Over Per Piece</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Freight_Destination__c.field-meta.xml
<CustomField>
    <fullName>Freight_Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Freight Implementation: It will be the destination for the products.</description>
    <inlineHelpText>Search by IATA aiport code (e.g. LAX, SYD, DXB)</inlineHelpText>
    <label>Destination</label>
    <referenceTo>Airport_Code__c</referenceTo>
    <relationshipLabel>Opportunity Product (Destination)</relationshipLabel>
    <relationshipName>Opportunity_Product1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Freight_Origin__c.field-meta.xml
<CustomField>
    <fullName>Freight_Origin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Freight Implementation: It will be a start destination of underlying product</description>
    <inlineHelpText>Search by IATA aiport code (e.g. LAX, SYD, DXB)</inlineHelpText>
    <label>Origin</label>
    <referenceTo>Airport_Code__c</referenceTo>
    <relationshipLabel>Opportunity Product Origin</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Min_Charge__c.field-meta.xml
<CustomField>
    <fullName>Min_Charge__c</fullName>
    <label>Min Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Pivot_Rate__c.field-meta.xml
<CustomField>
    <fullName>Pivot_Rate__c</fullName>
    <label>Pivot Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Pivot_Weight_Kgs__c.field-meta.xml
<CustomField>
    <fullName>Pivot_Weight_Kgs__c</fullName>
    <label>Pivot Weight (Kgs)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Rate_Valid_after_acceptance_until__c.field-meta.xml
<CustomField>
    <fullName>Rate_Valid_after_acceptance_until__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate Valid after acceptance until</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Freight_Quote.recordType-meta.xml
<RecordType>
    <fullName>Freight_Quote</fullName>
    <active>true</active>
    <description>This record type for Freight related Quote</description>
    <label>Freight_Quote</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Flat_Rate__c.field-meta.xml
<CustomField>
    <fullName>Flat_Rate__c</fullName>
    <label>Flat Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Freight_Commodity__c.field-meta.xml
<CustomField>
    <fullName>Freight_Commodity__c</fullName>
    <description>Freight - to capture the commodity of the Opportunity</description>
    <label>Commodity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abalone</fullName>
            </value>
            <value>
                <fullName>Aircraft Engines</fullName>
            </value>
            <value>
                <fullName>Aircraft On Ground</fullName>
            </value>
            <value>
                <fullName>Asparagus</fullName>
            </value>
            <value>
                <fullName>Avocados</fullName>
            </value>
            <value>
                <fullName>Baby Poultry</fullName>
            </value>
            <value>
                <fullName>Books/Brochures</fullName>
            </value>
            <value>
                <fullName>Brocolli</fullName>
            </value>
            <value>
                <fullName>Bulk Utilisation, Shipper Consignee Handled Unit</fullName>
            </value>
            <value>
                <fullName>Cheese</fullName>
            </value>
            <value>
                <fullName>Company Materials</fullName>
            </value>
            <value>
                <fullName>Corrosive</fullName>
            </value>
            <value>
                <fullName>Courier Bag Voucher</fullName>
            </value>
            <value>
                <fullName>Crabs</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Deferred Cargo</fullName>
            </value>
            <value>
                <fullName>Density Shipments</fullName>
            </value>
            <value>
                <fullName>Diplomatic Mail</fullName>
            </value>
            <value>
                <fullName>Dry Ice</fullName>
            </value>
            <value>
                <fullName>Eel</fullName>
            </value>
            <value>
                <fullName>Eggs</fullName>
            </value>
            <value>
                <fullName>Fish</fullName>
            </value>
            <value>
                <fullName>Fish/Seafood</fullName>
            </value>
            <value>
                <fullName>Flowers</fullName>
            </value>
            <value>
                <fullName>Flowers/Plants</fullName>
            </value>
            <value>
                <fullName>Foodstuffs</fullName>
            </value>
            <value>
                <fullName>Fruit And Vegetables</fullName>
            </value>
            <value>
                <fullName>General Commodity</fullName>
            </value>
            <value>
                <fullName>Hatching Eggs</fullName>
            </value>
            <value>
                <fullName>Heavy Cargo,150Kg And Over Per Piece</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Freight_Destination__c.field-meta.xml
<CustomField>
    <fullName>Freight_Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Freight Implementation: It will be the destination for the products replication.</description>
    <label>Destination</label>
    <referenceTo>Airport_Code__c</referenceTo>
    <relationshipLabel>Quote Line Items (Destination)</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Freight_Origin__c.field-meta.xml
<CustomField>
    <fullName>Freight_Origin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Freight Implementation: It will be a start destination of underlying product replication.</description>
    <label>Origin</label>
    <referenceTo>Airport_Code__c</referenceTo>
    <relationshipLabel>Quote Line Items (Origin)</relationshipLabel>
    <relationshipName>Quote_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Min_Charge__c.field-meta.xml
<CustomField>
    <fullName>Min_Charge__c</fullName>
    <label>Min Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Pivot_Rate__c.field-meta.xml
<CustomField>
    <fullName>Pivot_Rate__c</fullName>
    <label>Pivot Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Pivot_Weight_Kgs__c.field-meta.xml
<CustomField>
    <fullName>Pivot_Weight_Kgs__c</fullName>
    <label>Pivot Weight (Kgs)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QuoteLineItemTriggerTest.cls
/*==================================================================================================================================
Author:         Abhieet P
Company:        TCS
Purpose:        Test Class for Quote Line Item Trigger
Date:           15/06/2017         
History:
Modified By : Hari B (TCS Team), 27-Feb-2026
Desc : Fixed test class failures and added setupTestData() method.

==================================================================================================================================
CRM-4167 Raj Sharma 28-02-2020

Modified By : Venkata Suresh Kumar (TCS Team), 20-May-2026
Desc : Remediated test class failures. Updated createTestData() method.
==================================================================================================================================*/
@isTest
private class QuoteLineItemTriggerTest {
    @testSetup static void setupTestData() {
        Test.startTest();
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType();
        Test.stopTest();
    }


    static testMethod void  createTestData() {
      
      Test.startTest();
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSetting();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createProductRegTriggerSetting());
        insert lsttrgStatus;
        
        List<Freight_RecordTypeSeggregation__c> lstfreCusSetting = Freight_TriggerRecordTypeUtility.createAccTrigTestCustomSetting();
        insert lstfreCusSetting;
        
        Account objaccount = new Account();
        objaccount.Name = 'TestAccount-Freight';
        objaccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Freight Account').getRecordTypeId();
        insert objaccount;
        
        Contact objcontact = new Contact();
        objcontact.FirstName = 'TestContact-Freight';
        objcontact.LastName = objaccount.Name;
        objcontact.Business_Types__c = 'Freight';
        objcontact.Email = 'test135@abc.com';
        insert objcontact;        
        
        Product2 objProduct2=new Product2();
        objProduct2.Name='Q-GO Priority Test';
        objProduct2.CurrencyIsoCode='AUD';
        objProduct2.isActive = TRUE;
        insert objProduct2;       
        
        Airport_Code__c objAirportCitySYD = new Airport_Code__c();
        objAirportCitySYD.Name = 'SYD';
        objAirportCitySYD.Freight_Station_Name__c ='Sydney';
        insert objAirportCitySYD;
        
        Airport_Code__c objAirportCityMEL = new Airport_Code__c();
        objAirportCityMEL.Name = 'MEL';
        objAirportCityMEL.Freight_Station_Name__c ='Melbourne';
        insert objAirportCityMEL;
        
        id stdPricebookId = Test.getStandardPricebookId();        
        Opportunity objopportunity = new Opportunity();
        objopportunity.AccountID = objaccount.id;
        objopportunity.Name = 'TestOpportunity';
        objopportunity.StageName = 'Identify';
        objopportunity.CloseDate = Date.today();
        objopportunity.Pricebook2ID = stdPricebookId;
        objopportunity.Forecast_MCA_Revenue__c=20000;
        insert objopportunity;        
        
        // system.debug('@@ stdPricebookId @@ ' + stdPricebookId);
        PricebookEntry objpricebookentry = new PricebookEntry();
        objpricebookentry.Product2ID = objProduct2.id;
        objpricebookentry.Pricebook2ID = stdPricebookId;
        objpricebookentry.UnitPrice = 0;
        objpricebookentry.isActive = true;
        insert objpricebookentry;    
        
        OpportunityLineItem objOpportunityProduct = new OpportunityLineItem();
        objOpportunityProduct.Quantity = 2;
        objOpportunityProduct.OpportunityId = objopportunity.Id;
        objOpportunityProduct.UnitPrice = 10;
        objOpportunityProduct.PriceBookEntryId = objpricebookentry.Id;
        objOpportunityProduct.Freight_Destination__c = objAirportCitySYD.Id;
        objOpportunityProduct.Freight_Origin__c = objAirportCityMEL.Id;
        objOpportunityProduct.Freight_Commodity__c = 'Abalone';
        objOpportunityProduct.Description = 'freightQLI';
        objOpportunityProduct.Flat_Rate__c = 2;
        objOpportunityProduct.Min_Charge__c = 3;   
        objOpportunityProduct.Pivot_Rate__c = 4;
        objOpportunityProduct.Pivot_Weight_Kgs__c = 5;    
        
               //objOpportunityProduct.Product2ID = objProduct2.id;
        insert objOpportunityProduct;

        Quote objquote=new Quote();
        objquote.Name='TestQuote';
        objquote.RecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('Freight_Quote').getRecordTypeId();
        objquote.OpportunityID=objopportunity.id;
        objquote.pricebook2id = stdPricebookId;
        objquote.ContactId = objcontact.Id;
        objquote.Rate_Valid_after_acceptance_until__c=Date.today()-30; // CRM-11408 added as part of Test class fix
        insert objquote;
        
        QuoteLineItem objQuoteLineItem = new QuoteLineItem();
        objQuoteLineItem.QuoteId = objquote.Id;
        objQuoteLineItem.Quantity = 2;
        objQuoteLineItem.UnitPrice = 10;
        objQuoteLineItem.Description = 'freightQLI';
        objQuoteLineItem.Product2ID = objProduct2.id;
        objQuoteLineItem.PricebookEntryId = objpricebookentry.Id;
        objQuoteLineItem.Flat_Rate__c = 2;
        objQuoteLineItem.Min_Charge__c = 3;   
        objQuoteLineItem.Pivot_Rate__c = 4;
        objQuoteLineItem.Pivot_Weight_Kgs__c = 5; 
        insert objQuoteLineItem;        
        Test.stopTest();
    }
}