force-app/main/default/objects/Account/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Code__c/Airport_Code__c.object-meta.xml
<CustomObject>
    <description>To capture the Airport Code</description>
    <label>Airport Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/QCC_First_Host__c.object-meta.xml
<CustomObject>
    <description>Container for creating records for the First Host process</description>
    <label>Qantas Host</label>
    <nameField>
        <displayFormat>FH{00000000}</displayFormat>
        <label>First Host Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qantas Hosts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Flight_No__c.field-meta.xml
<CustomField>
    <fullName>QCC_Flight_No__c</fullName>
    <description>Value comes from Pre-Departure platform event. This is referenced by the Email Alert for first host is sent.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight No</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Number_of_Bags__c.field-meta.xml
<CustomField>
    <fullName>QCC_Number_of_Bags__c</fullName>
    <description>Updated automatically when the Qantas Host online form is submitted by the customer. Can also be set manually by agent either when a customer calls or reply via email.</description>
    <inlineHelpText>The number of bags specified by the customer</inlineHelpText>
    <label>Number of Bags</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Other_Details__c.field-meta.xml
<CustomField>
    <fullName>QCC_Other_Details__c</fullName>
    <description>Updated automatically when the Qantas Host online form is submitted by the customer. Can also be set manually by agent either when a customer calls or reply via email.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Specify value based on the customer&apos;s reply on the Qantas Host email or call or automatically from the online form submission</inlineHelpText>
    <label>Other Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_PNR__c.field-meta.xml
<CustomField>
    <fullName>QCC_PNR__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Qantas_First_Spa_Lounge__c.field-meta.xml
<CustomField>
    <fullName>QCC_Qantas_First_Spa_Lounge__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated automatically when the Qantas Host online form is submitted by the customer. Can also be set manually by agent either when a customer calls or reply via email.</description>
    <inlineHelpText>Checked for customers requesting spa service</inlineHelpText>
    <label>Qantas First Spa Lounge</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_Qantas_Porter_Service__c.field-meta.xml
<CustomField>
    <fullName>QCC_Qantas_Porter_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated automatically when the Qantas Host online form is submitted by the customer. Can also be set manually by agent either when a customer calls or reply via email.</description>
    <inlineHelpText>Checked for customers requesting porter service</inlineHelpText>
    <label>Qantas Porter Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_RESTAPIInboundQantasHostTest.cls
/*********************************************************************************
Name         : QCC_RESTAPIInboundQantasHostTest
Created By   : Raymart Airon Tolentino
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 30 October 2019
Usages       : This will handle the test class and code coverage of
QCC_RESTAPIInboundQantasHost APEX class

Modified By : Venkata Suresh Kumar (TCS Team), 19-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method.
*********************************************************************************/
@isTest
public class QCC_RESTAPIInboundQantasHostTest {
    @testSetup
    static void createData() {
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        //Create test data for Flight Event object
        List<Trigger_Status__c> customSettingListQantasHost = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusQantasHost', null, null, null, null);
        insert customSettingListQantasHost;
        
        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.RecordTypeId = contactRecordTypeId;
        contactRecord.Frequent_Flyer_Number__c = '000001';
        insert contactRecord;
        
        //Create test data for Airport object
        Airport_Code__c airportRecord = QCC_TestDataFactory.createAirportCodeTestData();
        
        insert airportRecord;
        
        //Create test data for QCC_First_Host__c
        QCC_First_Host__c qantasHostRecord = QCC_TestDataFactory.createFirstHostTestData(contactRecord.Id, airportRecord.id);
        qantasHostRecord.QCC_Flight_No__c = '0001';
        qantasHostRecord.QCC_PNR__c = '123123';
        qantasHostRecord.QCC_Qantas_First_Spa_Lounge__c = true;
        qantasHostRecord.QCC_Qantas_Porter_Service__c = true;
        qantasHostRecord.QCC_Number_of_Bags__c = 5;
        qantasHostRecord.QCC_Other_Details__c = 'Sample';
        insert qantasHostRecord;
    }
    
    static testMethod void test1(){
        QCC_First_Host__c qantasHostRecord = [SELECT Id, QCC_Qantas_First_Spa_Lounge__c, QCC_Qantas_Porter_Service__c, QCC_Number_of_Bags__c, QCC_Other_Details__c FROM QCC_First_Host__c LIMIT 1];
        
        String recordString = '{"Id":"<Id>","QCC_Qantas_First_Spa_Lounge__c":"false","QCC_Qantas_Porter_Service__c":"false","QCC_Number_of_Bags__c":1,"QCC_Other_Details__c":"None"}';
        recordString = recordString.replace('<Id>', qantasHostRecord.Id);
        System.debug('recordString: ' + recordString);
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/AccessQantasHost/';
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueof(recordString);
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        QCC_RESTAPIInboundQantasHost.start();
        Test.stopTest();
    }
    
    static testMethod void test2(){
        QCC_First_Host__c qantasHostRecord = [SELECT Id, QCC_Qantas_First_Spa_Lounge__c, QCC_Qantas_Porter_Service__c, QCC_Number_of_Bags__c, QCC_Other_Details__c FROM QCC_First_Host__c LIMIT 1];
        
        String recordString = '{"Id":"<Id>","QCC_Qantas_First_Sa_Lounge__c":"false","QCC_Qantas_Porter_Service__c":"false","QCC_Number_of_Bags__c":1,"QCC_Other_Details__c":"None"}';
        recordString = recordString.replace('<Id>', qantasHostRecord.Id);
        System.debug('recordString: ' + recordString);
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/AccessQantasHost/';
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueof(recordString);
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        QCC_RESTAPIInboundQantasHost.start();
        Test.stopTest();
    }
}