force-app/main/default/objects/Account/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Code__c/Airport_Code__c.object-meta.xml
<CustomObject>
    <description>To capture the Airport Code</description>
    <label>Airport Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proposal Name</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fare_Structure__c/Fare_Structure__c.object-meta.xml
<CustomObject>
    <description>Custom object to replace standard Product object</description>
    <label>Fare</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Booking Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fares</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Custom object to replace standard Quote object</description>
    <label>Proposal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QEC_Special_Condition__c/QEC_Special_Condition__c.object-meta.xml
<CustomObject>
    <description>special conditions for proposal</description>
    <label>Special Condition</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QEC_Special_Condition__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Special Conditions</relationshipLabel>
    <relationshipName>Special_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QEC_Special_Condition__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Special Conditions</relationshipLabel>
    <relationshipName>Special_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QEC_Special_Condition__c/fields/QEC_Destination__c.field-meta.xml
<CustomField>
    <fullName>QEC_Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter Airport Code, Country, Domestic or International.</inlineHelpText>
    <label>Destination</label>
    <referenceTo>Airport_Code__c</referenceTo>
    <relationshipLabel>Special Conditions (Destination)</relationshipLabel>
    <relationshipName>Special_Conditions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QEC_Special_Condition__c/fields/QEC_Origin__c.field-meta.xml
<CustomField>
    <fullName>QEC_Origin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter Airport Code, Country, Domestic or International.</inlineHelpText>
    <label>Origin</label>
    <referenceTo>Airport_Code__c</referenceTo>
    <relationshipLabel>Special Conditions</relationshipLabel>
    <relationshipName>Special_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QEC_Special_Condition__c/fields/QEC_Type__c.field-meta.xml
<CustomField>
    <fullName>QEC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Route Deal</fullName>
            </value>
            <value>
                <fullName>Incentive Fare</fullName>
            </value>
            <value>
                <fullName>Block Fare</fullName>
            </value>
            <value>
                <fullName>Fixed Fare</fullName>
            </value>
            <value>
                <fullName>Advance Res/Ticketing</fullName>
            </value>
            <value>
                <fullName>Penalties</fullName>
            </value>
            <value>
                <fullName>Additional Baggage</fullName>
            </value>
            <value>
                <fullName>JQ Inclusion</fullName>
            </value>
            <value>
                <fullName>Excess Baggage</fullName>
                <isActive>false</isActive>
                <label>Excess Baggage</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QEC_SpecialConditionControllerTest.cls
/**********************************************************************
Name:  QEC_SpecialConditionControllerTest
Copyright © 2019  Qantas Airways.
======================================================
Req: 
QEC - Adding, Viewing, Editing and Deleting Special Conditions on a Proposal
======================================================
Purpose:                                                            
Test class for QEC_SpecialConditionController
======================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE              DETAIL
1.0 	Anil Nair       28/06/2019      Initial Development
========================================================
Methods
1. testInsertRecords() - performs data insert and call the insertRecords method to insert special condition records
2. testGetSpecialConditions() - performs test data insert and calls getSpecialConditions method to check if records are retrieved
3. testdeleteRecord() - performs test data insert for special condition records and then deletes a record by calling the deleteRecord method and checks if delete operation was successful
4. testGetFares() - performs test data insert of fare structure records and then calls getFares method to check if the records can be retrieved
5. testGetFieldMap() - calls getFieldMap method and verfies that it is able to retrieve metadata values
6. testGetPickListMap() - calls getPicklistMap method and verifies that picklist values corresponding to picklist fields are retrieved.
7. testSpecialConditionOnContract() - calls insertRecord methods to simulate creation of special conditions on contract
8. testGetObjectType() - creates an account and passes the id to the getObjectType method and check if the correct object name is returned.
***********************************************************************/
@isTest
public class QEC_SpecialConditionControllerTest {
    public static testMethod void testInsertRecords(){
        List<Account> accList = TestUtilityDataClassQantas.getAccounts();
        List<Opportunity> oppList = TestUtilityDataClassQantas.getOpportunities(accList);
        List<Proposal__c> proposalList = TestUtilityDataClassQantas.getProposal(oppList);
        
        QEC_Special_Condition__c specialCondition = new QEC_Special_Condition__c();
        List<Airport_Code__c> airport_codes = TestUtilityDataClassQantas.createAirportCode();
        specialCondition.QEC_Origin__c = airport_codes[0].Id;
        specialCondition.QEC_Destination__c = airport_codes[1].Id;
        specialCondition.Proposal__c = proposalList[0].Id;
        
        List<QEC_Special_Condition__c> specialConditionList = new List<QEC_Special_Condition__c>();
        specialConditionList.add(specialCondition);
        
        QEC_SpecialConditionController.insertRecords(specialConditionList);
    }
    public static testMethod void testGetSpecialConditions() {
        List<QEC_Special_Condition__c> specialConditionList = TestUtilityDataClassQantas.getSpecialConditions();
        insert specialConditionList;
        Map<String, List<QEC_Special_Condition__c>> specialConditionMap = QEC_SpecialConditionController.getSpecialConditions(specialConditionList[0].Proposal__c);
        system.assertEquals(3, specialConditionMap.get('Additional Baggage').size()); 
    }
    public static testMethod void testdeleteRecord() {
        List<QEC_Special_Condition__c> specialConditionList = TestUtilityDataClassQantas.getSpecialConditions();
        insert specialConditionList;
        QEC_SpecialConditionController.deleteRecord(specialConditionList[0].id);
        List<QEC_Special_Condition__c> testList = [select id from QEC_Special_Condition__c where Proposal__c = :specialConditionList[0].proposal__c];
        //System.assertEquals(2, testList.size());
    }
    public static testMethod void testGetFares() {
        List<Fare_Structure__c> fareList = TestUtilityDataClassQantas.getFareStructures();
        insert fareList;
        List<Fare_Structure__c> testList = QEC_SpecialConditionController.getFares();
        System.assertEquals(3,testList.size());
    }
    public static testMethod void testGetFieldMap() {
        Map<String,List<Object>> fieldMap = QEC_SpecialConditionController.getFieldMap();
        System.assertNotEquals(0, fieldMap.get('Additional Baggage').size());   
    }
    public static testMethod void testGetPickListMap() {
        Map<String,List<String>> picklistMap = QEC_SpecialConditionController.getPicklistMap();
        System.assertNotEquals(0, pickListMap.get('QEC_Type__c').size());
    }
    public static testMethod void testSpecialConditionOnContract() {
        List<Account> accList = TestUtilityDataClassQantas.getAccounts();
        List<Opportunity> oppList = TestUtilityDataClassQantas.getOpportunities(accList);
        List<Proposal__c> proposalList = TestUtilityDataClassQantas.getProposal(oppList);
        List<Contract__c> contractList = TestUtilityDataClassQantas.getContracts(proposalList);
        
        QEC_Special_Condition__c specialCondition = new QEC_Special_Condition__c();
        List<Airport_Code__c> airport_codes = TestUtilityDataClassQantas.createAirportCode();
        specialCondition.QEC_Origin__c = airport_codes[0].Id;
        specialCondition.QEC_Destination__c = airport_codes[1].Id;
        specialCondition.Contract__c = contractList[0].Id;
        
        List<QEC_Special_Condition__c> specialConditionList = new List<QEC_Special_Condition__c>();
        specialConditionList.add(specialCondition);
        
        QEC_SpecialConditionController.insertRecords(specialConditionList);
    }
    public static testMethod void testGetObjectType() {
        List<Account> accList = TestUtilityDataClassQantas.getAccounts();
        String objName = QEC_SpecialConditionController.getObjectType(accList[0].id);
        System.assertEquals('Account', objName);
    }
}