force-app/main/default/objects/Account/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Generic Company Email</inlineHelpText>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Freight_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Freight_Unique_Identifier__c</fullName>
    <description>Freight Implementation: It will be combination of FCI, Country Code, Customer Code.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Unique code which identifies the customer account in Salesforce (e.g. DGF-AU)</inlineHelpText>
    <label>Freight Unique Identifier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function (Related)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Procurement/Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role (Related)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agency Manager</fullName>
            </value>
            <value>
                <fullName>Agency Owner</fullName>
            </value>
            <value>
                <fullName>Ambassador / High Commissioner</fullName>
            </value>
            <value>
                <fullName>BDM</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager - Agency</fullName>
            </value>
            <value>
                <fullName>Business Development Manager – Corporate</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chancellor</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Charter Key Contact</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of Business Unit</fullName>
            </value>
            <value>
                <fullName>Chief of Finance</fullName>
            </value>
            <value>
                <fullName>Chief of Organisation</fullName>
            </value>
            <value>
                <fullName>Chief of Procurement</fullName>
            </value>
            <value>
                <fullName>Chief of the Organisation</fullName>
            </value>
            <value>
                <fullName>Commercial Director</fullName>
            </value>
            <value>
                <fullName>Commerical Partner Contact</fullName>
            </value>
            <value>
                <fullName>Consultant/agent</fullName>
            </value>
            <value>
                <fullName>Consultant/agent - Senior</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Assistant</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Executive Team Member (non Finance)</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Head of Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the contact&apos;s job title within the organisation. Please use full description and avoid using abbreviations.
**S&amp;D - max 50 character limit applies.</inlineHelpText>
    <label>Job Title (Related)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Code__c/Airport_Code__c.object-meta.xml
<CustomObject>
    <description>To capture the Airport Code</description>
    <label>Airport Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport_Code__c/fields/QF_Freight_Presence__c.field-meta.xml
<CustomField>
    <fullName>QF_Freight_Presence__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Freight - indicates whether Qantas Freight has a presence at this port</description>
    <label>QF Freight Presence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email from Corporate Scheme Record</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Procurement/Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Types__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agency Manager</fullName>
            </value>
            <value>
                <fullName>Agency Owner</fullName>
            </value>
            <value>
                <fullName>Ambassador / High Commissioner</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager - Agency</fullName>
            </value>
            <value>
                <fullName>Business Development Manager – Corporate</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chancellor</fullName>
            </value>
            <value>
                <fullName>Charter Broker</fullName>
            </value>
            <value>
                <fullName>Charter Key Contact</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of Business Unit</fullName>
            </value>
            <value>
                <fullName>Chief of Finance</fullName>
            </value>
            <value>
                <fullName>Chief of Organisation</fullName>
            </value>
            <value>
                <fullName>Chief of Procurement</fullName>
            </value>
            <value>
                <fullName>Chief of the Organisation</fullName>
            </value>
            <value>
                <fullName>Commercial Director</fullName>
            </value>
            <value>
                <fullName>Commerical Partner Contact</fullName>
            </value>
            <value>
                <fullName>Consultant/agent</fullName>
            </value>
            <value>
                <fullName>Consultant/agent - Senior</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Assistant</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Executive Team Member (non Finance)</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>Head of Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Key Traveller</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the contact&apos;s job title within the organisation. Please use full description and avoid using abbreviations.
**S&amp;D - max 50 character limit applies.</inlineHelpText>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/batchClass_USInvoicesCasesTest.cls
/*Jira-> FCRM-854- US Invoicing - auto create invoice case
Description-> Test Class for batchClass_USInvoicesCases
Developer-> Navpreet Kaur
Creation Date-> Feb 2022
*/
@isTest
public class batchClass_USInvoicesCasesTest 
{
	static testMethod void batchTheUSInvoicesTest()
    {
        try
        {
        List<Airport_Code__c> listAirCodes=new List<Airport_Code__c>();
        List<Contact> listContacts=new List<contact>();
        List<Account> listAccounts=new List<Account>();
        List<AccountContactRelation> listACRs=new List<AccountContactRelation>(); 
        ID accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Freight Account').getRecordTypeId();
        ID contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        string headRow='Origin,Agent Name,Agent code,Air waybill num,Org Total Charges,Org prepaid weight charge,Adj Prepaid weight charge,Comments,Agent Contact Name,Agent Contact Tel,Agent Contact Email \n';
		string rowRec1='ATL,Vikrant Tajane,0110008,08153451403,6927.21,952.24,245.23,Please review the attached with rated booking,Vikrant Tajane,281-233-9444,Vikrant.Tajane@qantas.com.au \n';
		string rowRec2='GRU,Kim Wethmar,0110090,08153451467,5927.21,952.24,245.23,Please review the attached with rated booking,Kim Wethmar,281-233-9444,Kim.Wethmar@qantas.com.au \n';		
		string 	finalstr = headRow+rowRec1+rowRec2;
		blob csvBlob = Blob.valueOf(finalstr);
        string csvname= 'FreightInvoicingUS_'+system.today().day()+'_'+system.today().month()+'_'+system.today().year();
       
        Folder fold=[select id from folder where DeveloperName ='Freight_Invoicing_Process_US'];
        List<Trigger_Status__c> getListStatus=new List<Trigger_Status__c>(); 
      	getListStatus.addAll(freightUtilToBypassTrgCustSett.createAccountTriggerSettingFalse());
        getListStatus.addAll(freightUtilToBypassTrgCustSett.createCaseTriggerSettingFalse());
        insert getListStatus;
            
        Document docFile=new document();
        docFile.Body=csvBlob;
        docFile.DeveloperName=csvname;
        docFile.Name=csvname;
        docFile.FolderId=fold.Id;
        docFile.type='csv';
        docFile.AuthorId=UserInfo.getUserId();
        insert docFile;
        
        Airport_Code__c  mdtRec=new Airport_Code__c (Name='ATL',QF_Freight_Presence__c=true);
        Airport_Code__c  mdtRec2=new Airport_Code__c (Name='GRU',QF_Freight_Presence__c=true);
        listAirCodes.add(mdtRec);
        listAirCodes.add(mdtRec2);
            
        if(listAirCodes!=null && listAirCodes.size()>0)
        {
             insert listAirCodes;
        }   

        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        accountRecord.billingcountry='US';
        accountRecord.Freight_Unique_Identifier__c='0110008';
        accountRecord.Email__c='Vikrant.Tajane@qantas.com.au';    
        listAccounts.add(accountRecord);
        
        Account accountRecord2 = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord2.RecordTypeId = accountRecordTypeId;
        accountRecord2.billingcountry='US';
        accountRecord2.Freight_Unique_Identifier__c='0110090';
        accountRecord.Email__c='Kim.Wethmar@qantas.com.au';  
        listAccounts.add(accountRecord2);
		
        if(listAccounts!=null && listAccounts.size()>0)
        {
            insert listAccounts;
        }

        
        Contact cont=new Contact(recordtypeid=contactRecordTypeId,accountid=accountRecord.id,firstname='Vikrant',lastname='Tajane',email='Vikrant.Tajane@qantas.com.au',Job_Title__c='CEO',Function__c='Other',Business_Types__c='Agency',Job_Role__c='Other');
		Contact cont2=new Contact(recordtypeid=contactRecordTypeId,accountid=accountRecord2.id,firstname='Kim',lastname='Wethmar',email='Kim.Wethmar@qantas.com.au',Job_Title__c='CEO',Function__c='Other',Business_Types__c='Agency',Job_Role__c='Other');
		listContacts.add(cont);
        listContacts.add(cont2);
        
        if(listContacts!=null && listContacts.size()>0)
        {
            insert listContacts;
        }
	
        test.startTest();
        	database.executebatch(new batchClass_USInvoicesCases(),300);
        test.stopTest();
        }
        catch(Exception e)
        {
            system.debug('Exception Occured'+e.getMessage()+' '+e.getCause()+' '+e.getLineNumber());
        }
    }
}