force-app/main/default/objects/Account/fields/Chairmans_Lounge__c.field-meta.xml
<CustomField>
    <fullName>Chairmans_Lounge__c</fullName>
    <description>As an Account Manager, I would like to see the number of contacts that are having Chairman&apos;s Lounge = True.
NOTE: Amend the associated hover help</description>
    <inlineHelpText>As an Account Manager, I would like to see the number of contacts that are having Chairman&apos;s Lounge = True.</inlineHelpText>
    <label>Chairmans Lounge #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_CL_Flag__c.field-meta.xml
<CustomField>
    <fullName>Profile_CL_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chairmans Lounge Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Non_Agency_Contact.recordType-meta.xml
<RecordType>
    <fullName>Non_Agency_Contact</fullName>
    <active>true</active>
    <description>To be used for all contacts.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/RollupofCLcontactsHandler.cls
/**********************************************************************************************************************************
 
    Created Date: 23/05/17
 
    Description: Roll up of CL contacts of an account.
  
    Versión:
    V1.0 - 23/05/17 - Initial version [FO]
 
**********************************************************************************************************************************/

public class RollupofCLcontactsHandler {

        public static void CountNumofContacts(List < Contact > newList) {
            Set<ID> acctIds = new Set<ID>();
            Id ContRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Non_Agency_Contact').getRecordTypeId();
  try {
       // get list of accounts

    for (Contact con : newList) {
            acctIds.add(con.AccountId);
    }
   
  /*  Map<ID, Contact> contactsForAccounts = new Map<ID, Contact>([select Id
                                                            ,AccountId
                                                            from Contact
                                                            where AccountId in :acctIds and Profile_CL_Flag__c=TRUE]);*/
                                                            

   /* Map<ID, Account> acctsToUpdate = new Map<ID, Account>([select Id
                                                                 ,Chairmans_Lounge__c
                                                                  from Account
                                                                  where Id in :acctIds]);*/
                                                                  
                                                                  
        list<Account> acctsToUpdate = [select Id
                                                ,Chairmans_Lounge__c
                                                ,(select Id from Contacts where Profile_CL_Flag__c=TRUE AND RecordTypeId = :ContRecordTypeId )
                                                from Account
                                                where Id in :acctIds];                                                        
                                                                
    for (Account acct : acctsToUpdate) {
        /*Set<ID> conIds = new Set<ID>();
        for (Contact con : contactsForAccounts.values()) {
            if (con.AccountId == acct.Id)
                conIds.add(con.Id);
        }*/
        list<Contact> Allcons  = new list<Contact>();
        Allcons = acct.Contacts;
        if (acct.Chairmans_Lounge__c != Allcons.size())
            acct.Chairmans_Lounge__c = Allcons.size();
    }
    If(acctsToUpdate.size()>0)
    update acctsToUpdate;

  }
  
  catch(Exception e){
        System.debug('Error Occured From RollupofCLcontacts  Handler: '+e.getMessage());
    }
}
}