force-app/main/default/objects/Account/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract End Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract Start Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Qantas_Industry_Centre_ID__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Industry_Centre_ID__c</fullName>
    <description>Unique Field after CRM-1340 is resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Qantas Industry Centre Identifier</inlineHelpText>
    <label>QIC ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Agency_Info__c/Agency_Info__c.object-meta.xml
<CustomObject>
    <label>TMC Info</label>
    <nameField>
        <displayFormat>TMC-{0000}</displayFormat>
        <label>TMC Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMC Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TMC Info</relationshipLabel>
    <relationshipName>Agency_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>For intergration</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>This stores the GDS (Global Distribution System) Values</description>
    <inlineHelpText>Global Distribution System</inlineHelpText>
    <label>GDS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AARON GROUP</fullName>
            </value>
            <value>
                <fullName>Aeronology</fullName>
            </value>
            <value>
                <fullName>AirGateway</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Apollo</fullName>
            </value>
            <value>
                <fullName>Axess</fullName>
            </value>
            <value>
                <fullName>ClarityTTS</fullName>
            </value>
            <value>
                <fullName>CTM</fullName>
            </value>
            <value>
                <fullName>Duffel</fullName>
            </value>
            <value>
                <fullName>Expedia</fullName>
            </value>
            <value>
                <fullName>Farelogix</fullName>
                <label>Farelogix (F1)</label>
            </value>
            <value>
                <fullName>Galileo</fullName>
            </value>
            <value>
                <fullName>Infini</fullName>
            </value>
            <value>
                <fullName>Kyte</fullName>
            </value>
            <value>
                <fullName>Mystifly</fullName>
            </value>
            <value>
                <fullName>Navan</fullName>
            </value>
            <value>
                <fullName>QDP Portal</fullName>
            </value>
            <value>
                <fullName>Sabre</fullName>
            </value>
            <value>
                <fullName>Sabre Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Serko</fullName>
            </value>
            <value>
                <fullName>Spotnana</fullName>
            </value>
            <value>
                <fullName>TPConnects</fullName>
            </value>
            <value>
                <fullName>Travelfusion</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Concur</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Cytric</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Locomote</fullName>
            </value>
            <value>
                <fullName>Travelsky</fullName>
            </value>
            <value>
                <fullName>Verteil Technologies</fullName>
            </value>
            <value>
                <fullName>Worldspan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Info__c/fields/PCC__c.field-meta.xml
<CustomField>
    <fullName>PCC__c</fullName>
    <description>This is to store the PCC (Pseudo City Code)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Pseudo City Code</inlineHelpText>
    <label>PCC</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agency_Info__c/recordTypes/GDS.recordType-meta.xml
<RecordType>
    <fullName>GDS</fullName>
    <active>true</active>
    <description>To be used only for Agency Accounts</description>
    <label>GDS</label>
</RecordType>

force-app/main/default/objects/Case/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>This field is used on the Dealing Model Request layout</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please enter the CURRENT contracted end date</inlineHelpText>
    <label>Current Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>This field is used on the Dealing Model Request layout</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please enter the CURRENT contracted start date</inlineHelpText>
    <label>Current Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Distribution_Email__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Email__c</fullName>
    <description>100715-Change Hover Help. (YZ)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the TMC’s email address where you want Dealing Support team to send the Fare Sheet.</inlineHelpText>
    <label>Distribution Email</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Deal_Support_request.recordType-meta.xml
<RecordType>
    <fullName>Deal_Support_request</fullName>
    <active>true</active>
    <businessProcess>Deal Support</businessProcess>
    <description>Use this create deal support requests for Deal Implementations</description>
    <label>Deal Support Request</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the end date for the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the start date for the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts &amp; Agreements</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proposal Name</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/QEC_Distribution_Email__c.field-meta.xml
<CustomField>
    <fullName>QEC_Distribution_Email__c</fullName>
    <description>Email distribution field for Manage TMCPCC</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Distribution Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Custom object to replace standard Quote object</description>
    <label>Proposal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Proposal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposal_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the End Date for the Contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Proposal_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the Start Date of the Contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QEC_ContractTMCInfo__c/QEC_ContractTMCInfo__c.object-meta.xml
<CustomObject>
    <label>Contract TMC Info</label>
    <nameField>
        <displayFormat>TATMC-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract TMC Info</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QEC_ContractTMCInfo__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract TMC Info</relationshipLabel>
    <relationshipName>Contract_TMC_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QEC_ContractTMCInfo__c/fields/History__c.field-meta.xml
<CustomField>
    <fullName>History__c</fullName>
    <defaultValue>false</defaultValue>
    <description>History flag to display records in TMC PCC Management</description>
    <label>History</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QEC_ContractTMCInfo__c/fields/PCC__c.field-meta.xml
<CustomField>
    <fullName>PCC__c</fullName>
    <formula>TMC_Info__r.PCC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PCC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QEC_ContractTMCInfo__c/fields/PCC_End_Date__c.field-meta.xml
<CustomField>
    <fullName>PCC_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PCC End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QEC_ContractTMCInfo__c/fields/PCC_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>PCC_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PCC Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QEC_ContractTMCInfo__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Contract TMC Info</relationshipLabel>
    <relationshipName>Contract_TMC_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QEC_ContractTMCInfo__c/fields/TMC_Info__c.field-meta.xml
<CustomField>
    <fullName>TMC_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMC Info</label>
    <referenceTo>Agency_Info__c</referenceTo>
    <relationshipName>ContractTMCInfo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QEC_AddTMCPCCController.cls
/***********************************************************************************************************************************
Description: class for Handling TMC PCC management in Proposal and Contract Objects
Lightning Component : QEC_AddTMCPCCcmp

History:
======================================================================================================================
Name                    Jira        Description                                                 Tag
======================================================================================================================
Ram Kolli             EXPRCON-97     Manage TMC/PCC on Proposal and Contract  objects            T01                    
Created Date    : 20/08/19 (DD/MM/YYYY)

**********************************************************************************************************************************/

public without sharing class QEC_AddTMCPCCController {
    @AuraEnabled public Boolean isProposalRecord {get;set;}
    @AuraEnabled public Boolean isCaseCreated {get;set;}
    @AuraEnabled public String emailDistribution {get;set;}
    @AuraEnabled public List<QEC_AddTMCPCCWrapper> wrapperList = new List<QEC_AddTMCPCCWrapper>();
    
     @AuraEnabled 
    public static String getUserRoleName(){
        Id UserId = UserInfo.getUserId();
        User currentUser = [Select Id, UserRole.Name from User where Id =:UserId Limit 1];
        return currentUser.UserRole.Name != null ? currentUser.UserRole.Name:'';
    }
    
    @AuraEnabled
    public static QEC_AddTMCPCCController getTMCPCC(String recordid){
        Id currentRecordID = Id.valueof(recordId);
        String query;
        List<Id> tmcIds = new List<Id>();
        Proposal__c currentProposal;
        Contract__c currentContract;
        QEC_AddTMCPCCController cntrl = new QEC_AddTMCPCCController();
        //List<QEC_AddTMCPCCWrapper> wrapperList = new List<QEC_AddTMCPCCWrapper>();
        
        if(currentRecordID.getSObjectType().getDescribe().getName() == 'Contract__c') {
            cntrl.isProposalRecord = false;
            query = 'SELECT Id,Contract_Start_Date__c,Contract_End_Date__c,QEC_Distribution_Email__c, (select id,TMC_Info__c, History__c from Contract_TMC_Info__r) from Contract__c WHERE id=: recordId';
        }else{
            cntrl.isProposalRecord = true;
            query = 'SELECT Id,Proposal_Start_Date__c,Proposal_End_Date__c, (select id,TMC_Info__c, History__c from Contract_TMC_Info__r) from Proposal__c WHERE id=: recordId';
        }
        sObject record = Database.query(query);
        
        if(cntrl.isProposalRecord){    
            currentProposal = (Proposal__c)record;
        }else{
            currentContract = (Contract__c)record;
            cntrl.emailDistribution = currentContract.QEC_Distribution_Email__c;
        }
        
        if(cntrl.isProposalRecord && currentProposal.Contract_TMC_Info__r <> null){
            for(QEC_ContractTMCInfo__c obj : currentProposal.Contract_TMC_Info__r){
                tmcIds.add(obj.TMC_Info__c);
            }
        }
        if(!cntrl.isProposalRecord && currentContract.Contract_TMC_Info__r <> null){
            for(QEC_ContractTMCInfo__c obj : currentContract.Contract_TMC_Info__r){
                tmcIds.add(obj.TMC_Info__c);
            }
        }
        for(QEC_ContractTMCInfo__c agencyRecord : [SELECT Id, History__c, PCC_Start_Date__c,PCC_End_Date__c,Proposal__c,TMC_Info__c,Contract__c,TMC_Info__r.PCC__c,TMC_Info__r.Account__r.name,TMC_Info__r.Active__c, TMC_Info__r.Code__c, TMC_Info__r.Account__r.Qantas_Industry_Centre_ID__c from  QEC_ContractTMCInfo__c where TMC_Info__c =: tmcIds AND (Proposal__c =: recordId or Contract__c =: recordId) order by lastmodifieddate desc]){
            QEC_AddTMCPCCWrapper wrapper = new QEC_AddTMCPCCWrapper();
            wrapper.tmcId = agencyRecord.TMC_Info__c;
            wrapper.pcc = agencyRecord.TMC_Info__r.PCC__c;
            wrapper.gds = agencyRecord.TMC_Info__r.Code__c;
            wrapper.sdate = agencyRecord.PCC_Start_Date__c;
            wrapper.edate = agencyRecord.PCC_End_Date__c;
            wrapper.iata = agencyRecord.TMC_Info__r.Account__r.Qantas_Industry_Centre_ID__c;
            wrapper.history = agencyRecord.History__c;
            wrapper.contractTMCId = agencyRecord.Id;
            wrapper.active = agencyRecord.TMC_Info__r.Active__c;
            wrapper.accountName = agencyRecord.TMC_Info__r.Account__r.Name;
            cntrl.wrapperList.add(wrapper);
        }
        if(!cntrl.wrapperList.isEmpty()){
            return cntrl;
        }
        return null;
    }
    
    @AuraEnabled
    public static List<searchWrapper> fetchPCCData(String searchString, String recordId){
        Id currentRecordID = Id.valueof(recordId);
        List<searchWrapper> childWrapper = new List<searchWrapper>();
        Proposal__c currentProposal;
        Contract__c currentContract;
        String query;
        QEC_AddTMCPCCController cntrl = new QEC_AddTMCPCCController();
        if(currentRecordID.getSObjectType().getDescribe().getName() == 'Contract__c') {
            cntrl.isProposalRecord = false;
        }else{
            cntrl.isProposalRecord = true;
        }
        List<Agency_Info__c> agencyList = [SELECT Id, PCC__c,Code__c,Account__c,Active__c, Account__r.Qantas_Industry_Centre_ID__c FROM Agency_Info__c where PCC__c =: searchString or Account__r.Qantas_Industry_Centre_ID__c =: searchString];
        if(cntrl.isProposalRecord){
            query = 'SELECT Id,Proposal_End_Date__c from Proposal__c WHERE Id =: recordId';
        }else{
            query = 'SELECT Id, Contract_End_Date__c from Contract__c where Id =: recordId';
        }
        sObject currentRecord = Database.query(query);
        if(cntrl.isProposalRecord){    
            currentProposal = (Proposal__c)currentRecord;
        }else{
            currentContract = (Contract__c)currentRecord;
        }
        
        for(Agency_Info__c currentAgency : agencyList){
            searchWrapper sw = new searchWrapper();
            sw.tmcId = currentAgency.Id;
            sw.pcc = currentAgency.PCC__c;
            sw.gds = currentAgency.Code__c;
            sw.iata = currentAgency.Account__r.Qantas_Industry_Centre_ID__c;
            sw.sdate = System.today();
            sw.active = currentAgency.Active__c;
            childWrapper.add(sw);
        }
        return childWrapper;
    }
    
    @AuraEnabled
    public static Object performSave(String data, String recordId, String removalArray, String linkedArray,String emailField){
        Boolean returnFlag = false;
        Boolean history = false;
        Date dueDate;
        QEC_AddTMCPCCController returnObj = new QEC_AddTMCPCCController();
        returnObj.isCaseCreated=false;
        try{
            Id currentRecordID = Id.valueof(recordId);
            Set<Agency_Info__c> updateHistorySet = new Set<Agency_Info__c>();
            List<Agency_Info__c> updateHistory = new List<Agency_Info__c>();
            List<QEC_AddTMCPCCWrapper> wrapper = (List<QEC_AddTMCPCCWrapper>)JSON.deserialize(data, List<QEC_AddTMCPCCWrapper>.class);
            List<QEC_AddTMCPCCWrapper> linkedRecords = (List<QEC_AddTMCPCCWrapper>)JSON.deserialize(linkedArray, List<QEC_AddTMCPCCWrapper>.class);
            List<QEC_AddTMCPCCWrapper> removeList = (List<QEC_AddTMCPCCWrapper>)JSON.deserialize(removalArray, List<QEC_AddTMCPCCWrapper>.class);
            List<Id> addAgencyIds = new List<Id>();
            Map<Id, Date> removeAgencyIds = new Map<Id, Date>();
            Id accountId;
            List<QEC_ContractTMCInfo__c> qcList = new List<QEC_ContractTMCInfo__c>();
            if(currentRecordID.getSObjectType().getDescribe().getName() == 'Contract__c') {
                
                Contract__c contract = [select id, Name, Account__c,Opportunity__c,Opportunity__r.OwnerId from Contract__c where id =: currentRecordID];
                accountId = contract.Account__c;
                if(contract.Opportunity__r.OwnerId != UserInfo.getUserId()){
                    OpportunityTeamMember otm = new OpportunityTeamMember();
                    otm.UserId = UserInfo.getUserId();
                    otm.TeamMemberRole = 'Account Manager';
                    otm.OpportunityAccessLevel = 'Edit';
                    otm.OpportunityId = contract.Opportunity__c;
                    insert otm;
                }
                returnObj.isProposalRecord = false;
                Contract__c currentContract = new Contract__c(Id=recordId);
                currentContract.QEC_Distribution_Email__c=emailField;
                update currentContract;
                
            }else{
                returnObj.isProposalRecord = true;
            }
            Set<id> qccListIds = new Set<id>();
            //update history for removed reocrds -starts
            if(null != wrapper && wrapper.size() > 0){
                for(QEC_AddTMCPCCWrapper record: wrapper){
                    addAgencyIds.add(record.tmcId);
                    //save newly linked pcc records - starts
                    QEC_ContractTMCInfo__c qc = new QEC_ContractTMCInfo__c();
                    qc.TMC_Info__c = record.tmcId;
                    if(returnObj.isProposalRecord){
                        qc.Proposal__c = recordId;
                    }else{
                        qc.Contract__c = recordId;
                    }
                    qc.PCC_Start_Date__c = record.sdate;
                    dueDate =record.sdate;
                    qc.PCC_End_Date__c = record.edate;
                    qc.History__c = false;
                    qcList.add(qc);
                    qccListIds.add(record.tmcId);
                    //save newly linked pcc records - ends
                }
            }
            Set<id> contractTMCIds = new Set<id>();
            if(null != linkedRecords && linkedRecords.size() > 0){
                for(QEC_AddTMCPCCWrapper record: linkedRecords){
                    QEC_ContractTMCInfo__c qc = new QEC_ContractTMCInfo__c();
                    qc.PCC_End_Date__c = record.edate;
                    qc.History__c = record.history;
                    qc.Id = record.ContractTMCId;
                    qcList.add(qc);
                    qccListIds.add(record.ContractTMCId);
                    //save newly linked pcc records - ends
                    if(record.history == true ){
                        contractTMCIds.add(record.ContractTMCId);
                    }
                }
            }
            
            if(removeList.size() > 0){
                for(QEC_AddTMCPCCWrapper rec: removeList){
                    removeAgencyIds.put(rec.contractTMCId, rec.edate);
                }
                
                
                //update end date to contract end date for removed records - starts
                List<QEC_ContractTMCInfo__c> pccremoveList = new List<QEC_ContractTMCInfo__c>();
                for(QEC_ContractTMCInfo__c record : [select id,History__c, PCC_End_Date__c from QEC_ContractTMCInfo__c where Id =:removeAgencyIds.keySet() ]){
                    for(Id d : removeAgencyIds.keySet()){
                        if(String.valueOf(d).equals(String.valueOf(record.id))){
                            record.PCC_End_Date__c = null != String.valueOf(removeAgencyIds.get(d)) ? removeAgencyIds.get(d) : System.today();
                            record.History__c = true;
                            pccremoveList.add(record);
                        }
                    }
                }
                
                if(!pccremoveList.isEmpty()){
                    update pccremoveList;
                    returnFlag = true;
                }
                //update end date to contract end date for removed records - ends
            }
            
            
            //insert newly linked records
            if(!qcList.isEmpty()){
                upsert qcList;
                returnFlag = true;
                //case creation starts here - case will be created only for Contracts
                if(!returnObj.isProposalRecord) {
                    //String description ;
                    String pccString='';
                    String iataString='';
                    String gdsString='';
                    List<String> addedPair = new List<String>();
                    List<String> modifiedPair = new List<String>();
                    if(null != wrapper){
                        //added PCC/IATA
                        for(Integer i=0; i< wrapper.size(); i++) {
                            if(null != wrapper[i].pcc && (!String.isEmpty(wrapper[i].pcc))){
                                pccString += wrapper[i].pcc+',';
                            }
                            if(null != wrapper[i].iata && (!String.isEmpty(wrapper[i].iata))){
                                iataString += wrapper[i].iata+',';
                            }
                            if(null != wrapper[i].gds && (!String.isEmpty(wrapper[i].gds))){
                                gdsString += wrapper[i].gds+',';
                            }
                            addedPair.add(wrapper[i].pcc +'-'+ wrapper[i].gds);
                        }
                    } 
                    if(null != linkedArray){
                        //Modified PCC/IATA
                        for(Integer i=0; i< linkedRecords.size(); i++){
                            if(null != linkedRecords[i].pcc && (!String.isEmpty(linkedRecords[i].pcc))){
                                pccString += linkedRecords[i].pcc+',';
                            }
                            if(null != linkedRecords[i].iata && (!String.isEmpty(linkedRecords[i].iata))){
                                iataString += linkedRecords[i].iata+',';
                            }
                            if(null != linkedRecords[i].gds && (!String.isEmpty(linkedRecords[i].gds))){
                                gdsString += linkedRecords[i].gds+',';
                            }
                            modifiedPair.add(linkedRecords[i].pcc +'-'+ linkedRecords[i].gds);
                        }
                    }
                    
                    for(Id ids: qccListIds){
                        if(contractTMCIds.size()<1 && !contractTMCIds.contains(ids)){
                            Case c = new Case();
                            String dataNotPresent = Label.QEC_Code_Not_defined;
                            date addDays = system.today();
                            addDays = addDays.addDays(3);
                            iataString=String.isEmpty(iataString) ? dataNotPresent :iataString.removeEnd(',');
                            pccString=String.isEmpty(pccString) ? dataNotPresent : pccString.removeEnd(',');
                            gdsString = String.isEmpty(gdsString) ? dataNotPresent : gdsString.removeEnd(',');
                            String modifiedPairString='';
                            for(String m : modifiedPair){
                                modifiedPairString += m+'\n';
                            }
                            String addedPairString='';
                            for(String m : addedPair){
                                addedPairString += m+'\n';
                            }
                            c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Deal_Support_request').getRecordTypeId();
                            c.Related_Contract__c = currentRecordID;
                            c.OwnerId = [select id from Group where  Type = 'Queue' and name='Deal Support Team Queue'].Id;
                            c.Type = Label.Case_Type_Deal_Amendment;
                            c.status =Label.Case_Status_Deal_Support;
                            c.Sub_Type__c = Label.Case_sub_type_IATA_PCC_related;
                            c.Subject = Label.QEC_Case_Subject ;
                            c.AccountId = accountId;
                            //CRM-7815 Case due date update  
                            //CRM-8047 Case due date update
                            c.Due_Date__c = addDays;
                            //c.Due_Date__c = dueDate;
                            c.Description = Label.Case_TMC_PCC_Description+'\n'+'Added TMC/PCC :'+'\n'+addedPairString+'\n'+'Modified TMC/PCC :'+'\n'+modifiedPairString;
                            c.Distribution_Email__c = emailField;
                            c.PCC_Codes_DAT__c=pccString;
                            c.PCC_Codes_DAI__c=pccString;
                            c.IATA_DAT__c= iataString;
                            c.IATA_DAI__c= iataString;
                            c.Date_Effective_DAT__c = System.today();
                            c.New_IATA_Start_Date_DAI__c = system.today();
                            c.GDS_DAT__c=gdsString;
                            c.GDS_DAI__c =gdsString;
                            // c.New_TMC_Name__c= getAccountRelation(c.AccountId); /*Commented as part of Jira CRM- 5688*/ 
                            insert c;
                            returnObj.isProposalRecord = false;
                            returnObj.isCaseCreated = true;
                            break;
                        }
                        //case creation ends here
                    }
                }
                
            }
        }
        catch(Exception e){
            returnFlag = false;
            system.debug('Exception is '+e.getMessage());
            return e.getMessage();
        }        
        if(returnFlag)
            return returnObj;
        return null;
    }
    public static Id getAccountRelation(Id accId){
        Account_Relation__c c = new Account_Relation__c();
        c.Active__c= true;
        c.Relationship__c ='Travel Manager Of';
        c.Related_Account__c =accId;
        insert c;
        return c.id;
    }
    public class searchWrapper{
        @AuraEnabled public String pcc {get;set;}
        @AuraEnabled public String iata {get;set;}
        @AuraEnabled public String gds {get;set;}
        @AuraEnabled public Id tmcId {get;set;}
        @AuraEnabled public Date sdate {get;set;}
        @AuraEnabled public Date edate {get;set;}
        @AuraEnabled public Boolean history {get;set;}
        @AuraEnabled public Boolean active{get;set;}
        
    }
}