force-app/main/default/objects/Account/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract End Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>Used for Executive Summary</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for Executive Summary</inlineHelpText>
    <label>Contract Start Date [System]</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contracted__c.field-meta.xml
<CustomField>
    <fullName>Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate if there is an existing contract with this account</description>
    <inlineHelpText>To indicate if there is an existing contract with this account</inlineHelpText>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Count_of_open_opportunities__c.field-meta.xml
<CustomField>
    <fullName>Count_of_open_opportunities__c</fullName>
    <label>Count of open opportunities</label>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Qualify, Propose &amp; Negotiate</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.Sub_Type_Level_2__c</field>
        <operation>equals</operation>
        <value>Renewal, Variation</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>Business and Government</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opportunity_Maximum_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Maximum_Close_Date__c</fullName>
    <label>Opportunity Maximum Close Date</label>
    <summarizedField>Opportunity.CloseDate</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed - Accepted, Closed - Not Accepted</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>Business and Government</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Proposed_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Revenue_Amount__c</fullName>
    <formula>IF(((Domestic_Air_Travel_Spend__c != 0.00 || Domestic_Air_Travel_Spend__c != NULL) &amp;&amp; (International_Air_Travel_Spend__c != 0.00 || International_Air_Travel_Spend__c != NULL)), 
(Domestic_Air_Travel_Spend__c * 0.90 + International_Air_Travel_Spend__c *0.70), 

IF(((Domestic_Air_Travel_Spend__c == 0.00 || Domestic_Air_Travel_Spend__c == NULL) &amp;&amp; (International_Air_Travel_Spend__c != 0.00 || International_Air_Travel_Spend__c != NULL)), 
International_Air_Travel_Spend__c *0.70, 

IF(((Domestic_Air_Travel_Spend__c != 0.00 || Domestic_Air_Travel_Spend__c != NULL) &amp;&amp; (International_Air_Travel_Spend__c == 0.00 || International_Air_Travel_Spend__c == NULL)), 
Domestic_Air_Travel_Spend__c * 0.90, 

Estimated_Total_Air_Travel_Spend__c)))</formula>
    <label>Proposed Revenue Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the end date for the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please use this to capture the start date for the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contracted__c.field-meta.xml
<CustomField>
    <fullName>Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contracted [System]</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Farthest_Signed_Contract_End_Date_check__c.field-meta.xml
<CustomField>
    <fullName>Farthest_Signed_Contract_End_Date_check__c</fullName>
    <formula>IF(Account__r.Contracted__c = TRUE &amp;&amp; Account__r.Contract_Expiry_Date__c = Contract_End_Date__c, TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Farthest Signed Contract End Date check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts &amp; Agreements</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Proposed_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Revenue_Amount__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Revenue that is expected as part of the points price, minimum commitment etc.</inlineHelpText>
    <label>Billings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required - Internal</fullName>
            </value>
            <value>
                <fullName>Signature Required by Customer</fullName>
            </value>
            <value>
                <fullName>Signed by Customer</fullName>
            </value>
            <value>
                <fullName>Rejected - Customer</fullName>
            </value>
            <value>
                <fullName>Rejected – Legal</fullName>
            </value>
            <value>
                <fullName>Approval Required – Legal</fullName>
            </value>
            <value>
                <fullName>Rejected - Internal</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Superceded</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Airfares</fullName>
            </value>
            <value>
                <fullName>Qantas Business Savings</fullName>
                <default>true</default>
                <label>Qantas Business Savings</label>
            </value>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>FIFO Scheduled</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Quote or Contract type</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Airfares</fullName>
                <default>true</default>
                <label>Corporate Airfares</label>
            </value>
            <value>
                <fullName>Qantas Business Savings</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>FIFO Scheduled</fullName>
            </value>
            <value>
                <fullName>Spot Rate</fullName>
            </value>
            <value>
                <fullName>Preferred Rate</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Market Rate</fullName>
            </value>
            <value>
                <fullName>DPP Onboarding</fullName>
            </value>
            <value>
                <fullName>RB - Limited Availability Lanes</fullName>
            </value>
            <value>
                <fullName>RB - Special Lane Pricing</fullName>
            </value>
            <value>
                <fullName>RB - New Accounts Tier Assignment</fullName>
            </value>
            <value>
                <fullName>RB - Change in Tier Assignment</fullName>
            </value>
            <value>
                <fullName>RB - Spot Rates</fullName>
            </value>
            <value>
                <fullName>RB - Partner Rates</fullName>
            </value>
            <value>
                <fullName>Freighter</fullName>
            </value>
            <value>
                <fullName>Freighter - Spot Rates</fullName>
            </value>
            <value>
                <fullName>Freighter - SLP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Proposed_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Revenue_Amount__c</fullName>
    <description>delete this</description>
    <inlineHelpText>To be used to capture the proposed revenue amount for the opportunity.</inlineHelpText>
    <label>Proposed Revenue Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To be used for Group Sales Opportunity</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Payment Received</fullName>
            </value>
            <value>
                <fullName>Deposit Taken</fullName>
            </value>
            <value>
                <fullName>Full Amount Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_main__c/Opportunity_main__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Auto insert the opportunity based on field &quot;Create an Opportunity before (in months)&quot;</description>
    <label>Opportunity maintenance</label>
</CustomObject>

force-app/main/default/objects/Opportunity_main__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_main__c/fields/Create_an_Opportunity_before_in_months__c.field-meta.xml
<CustomField>
    <fullName>Create_an_Opportunity_before_in_months__c</fullName>
    <label>Create an Opportunity before (in months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QL_OpportunityRenewalChatterPost.cls
/**********************************************************************************************************************************

Created Date    : 13/12/2019 (DD/MM/YYYY)
Added By        : Karpagam Swaminathan
Description     : Batch Job notify Account Owners Renewal Oppty Creation.
JIRA            : CRM - 4101
Version         : V1.0 -  Initial version


**********************************************************************************************************************************/

global class QL_OpportunityRenewalChatterPost implements Database.Batchable<sObject> {
    Database.SaveResult[] lsterroResult = new Database.SaveResult[0]; 
    List < String > convertMsgs = new List < String > ();
    global Database.QueryLocator start(Database.BatchableContext BC){
        Map<string, Opportunity_main__c> categoryCY = Opportunity_main__c.getAll();
        
        List<String> category = new List<String>();
        
        List<String> categoryDate = new List<String>();
        if(categoryCY.containsKey('Corporate Airfares')){
            category.add(categoryCY.get('Corporate Airfares').Category__c);
        }
        if(categoryCY.containsKey('Qantas Business Savings')){
            category.add(categoryCY.get('Qantas Business Savings').Category__c);
        }
        
        
        
        return Database.getQueryLocator([SELECT Id, Contract_Start_Date__c, Contracted__c, Contract_End_Date__c, Account__c, Account__r.Name,
                                         Farthest_Signed_Contract_End_Date_check__c, Account__r.OwnerId,Opportunity__r.StageName,Opportunity__r.RecordType.Name,Opportunity__r.CloseDate, Type__c, Status__c,Account__r.Active__c, Account__r.RecordType.Name, Account__r.BillingCountry, Account__r.Count_of_open_opportunities__c,Account__r.Opportunity_Maximum_Close_Date__c, Account__r.Proposed_Revenue_Amount__c
                                         FROM Contract__c where (Account__r.Active__c = TRUE AND 
                                                                 Account__r.RecordType.Name = 'Customer Account' AND 
                                                                 Farthest_Signed_Contract_End_Date_check__c = TRUE AND Account__r.BillingCountry = 'AU' AND Account__r.Count_of_open_opportunities__c = 0 AND
                                                                 Type__c IN:category)]);
    }
    
    global void execute(Database.BatchableContext ctx, List<Contract__c> activecontracts){
        
        
        Map<string, Opportunity_main__c> categoryCY = Opportunity_main__c.getAll();
        List<Id> lstRecId = new List<Id>();
        for(Contract__c theContracts: activecontracts){
            
            
            
            Date d = theContracts.Contract_End_Date__c;
            
            System.debug('Contract End date: '+d);
            
            Date t = Date.today();
            
            
            Decimal decimalvalue1 =  categoryCY.get('Corporate Airfares').Create_an_Opportunity_before_in_months__c;
            Integer integerValue1 = decimalvalue1.intValue();
            
            System.debug('Corp Create an opportunity before in months : '+integerValue1);
            
            Decimal decimalvalues1 =  categoryCY.get('Qantas Business Savings').Create_an_Opportunity_before_in_months__c;
            Integer integerValues1 = decimalValues1.intValue();
            
            System.debug('QBS Create an opportunity before in months : '+integerValues1);
            
            
            if(theContracts.Account__r.Opportunity_Maximum_Close_Date__c <> null) {
                
                
                if((theContracts.Type__c == categoryCY.get('Corporate Airfares').Category__c && ((t.addMonths(integerValue1)) - 1) == d && categoryCY.get('Corporate Airfares').Active__c == true &&
                    ((theContracts.Account__r.Opportunity_Maximum_Close_Date__c < (categoryCY.get('Corporate Airfares').Close_Date__c)))) || 
                   (theContracts.Type__c == categoryCY.get('Qantas Business Savings').Category__c && ((t.addMonths(integerValues1)) - 1) == d  && categoryCY.get('Qantas Business Savings').Active__c == true &&
                    ((theContracts.Account__r.Opportunity_Maximum_Close_Date__c < (categoryCY.get('Qantas Business Savings').Close_Date__c))))){
                        String convertMsg = System.Label.RenewalOpportunityNotification;
                        convertMsgs.add(convertMsg);
                        ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
                        ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
                        ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
                        ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
                        
                        messageBodyInput.messageSegments = new List < ConnectApi.MessageSegmentInput > ();
                        
                        mentionSegmentInput.id = theContracts.Account__r.OwnerId;
                        messageBodyInput.messageSegments.add(mentionSegmentInput);
                        
                        textSegmentInput.text = ' ' + convertMsg;
                        messageBodyInput.messageSegments.add(textSegmentInput);
                        
                        feedItemInput.body = messageBodyInput;
                        feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
                        feedItemInput.subjectId = theContracts.Account__c;
                        try{
                            ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedItemInput);
                        }
                        catch(Exception e){
                            
                            
                            System.debug('Exception Occured: '+e.getMessage());   
                        } 
                    }
            }
            
            if(theContracts.Account__r.Opportunity_Maximum_Close_Date__c == null){
                
                if((theContracts.Type__c == categoryCY.get('Corporate Airfares').Category__c && ((t.addMonths(integerValue1)) - 1) == d && categoryCY.get('Corporate Airfares').Active__c == true) || 
                   (theContracts.Type__c == categoryCY.get('Qantas Business Savings').Category__c && ((t.addMonths(integerValues1)) - 1) == d  && categoryCY.get('Qantas Business Savings').Active__c == true ))
                    
                {
                    
                    String convertMsg = System.Label.RenewalOpportunityNotification;
                    
                    convertMsgs.add(convertMsg);
                    ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
                    ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
                    ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
                    ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
                    
                    messageBodyInput.messageSegments = new List < ConnectApi.MessageSegmentInput > ();
                    
                    mentionSegmentInput.id = theContracts.Account__r.OwnerId;
                    messageBodyInput.messageSegments.add(mentionSegmentInput);
                    
                    textSegmentInput.text = ' ' + convertMsg;
                    messageBodyInput.messageSegments.add(textSegmentInput);
                    
                    feedItemInput.body = messageBodyInput;
                    feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
                    feedItemInput.subjectId = theContracts.Account__c;
                    
                    try{
                        ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedItemInput);
                    }
                    catch(Exception e){
                        
                        
                        System.debug('Exception Occured: '+e.getMessage());   
                    }   
                    
                }                
                
                
            }
        }            
        
        
        
    }
    
    global void finish(Database.BatchableContext ctx){
        
    }
}