force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>To capture Legal Names for deals/contracts.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>To capture Legal Names for deals/contracts.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Owner__c/Account_Owner__c.object-meta.xml
<CustomObject>
    <label>Account Ownership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Character</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Ownership</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QL_QuipScheduledJob__c/QL_QuipScheduledJob__c.object-meta.xml
<CustomObject>
    <description>CRM-5833 This custom object stores the scheduled jobs for the batch that sends the emails along with Quip PDFs.</description>
    <label>Quip Scheduled Job</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Quip Scheduled Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quip Scheduled Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Owner</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>Batch_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current Batch Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/QL_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>QL_Account_Id__c</fullName>
    <description>CRM-5833 This field stores the ID of the account for which the job has been scheduled.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/QL_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>QL_Account_Name__c</fullName>
    <description>CRM-5833 This stores the name of the Account for which the job is to be scheduled.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/QL_ACR_Subscribed_Count__c.field-meta.xml
<CustomField>
    <fullName>QL_ACR_Subscribed_Count__c</fullName>
    <label>ACR Subscribed Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/QL_Job_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>QL_Job_Completed_Date__c</fullName>
    <description>This holds the date and time for the batch completion. CRM-6830</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Job Completed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/QL_Job_Name__c.field-meta.xml
<CustomField>
    <fullName>QL_Job_Name__c</fullName>
    <description>CRM-5833 This field is to store the name of the scheduled job.</description>
    <label>Completed Job Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Batch to Create QUIPs</fullName>
            </value>
            <value>
                <fullName>Batch to Remove QUIP Docs</fullName>
            </value>
            <value>
                <fullName>Batch to Refresh QUIPs</fullName>
            </value>
            <value>
                <fullName>Batch To Export As PDFs</fullName>
            </value>
            <value>
                <fullName>Batch to Send Emails Comms</fullName>
            </value>
            <value>
                <fullName>Batch To Send Comms Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/QL_Job_Scheduled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>QL_Job_Scheduled_Date_Time__c</fullName>
    <description>CRM-5833 This field stores the value at which the job has been scheduled to run.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Job Scheduled Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QL_QuipScheduledJob__c/fields/QL_Next_Job_Name__c.field-meta.xml
<CustomField>
    <fullName>QL_Next_Job_Name__c</fullName>
    <label>Next Job Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch to Create QUIPs</fullName>
            </value>
            <value>
                <fullName>Batch to Remove QUIP Docs</fullName>
            </value>
            <value>
                <fullName>Batch to Refresh QUIPs</fullName>
            </value>
            <value>
                <fullName>Batch To Export As PDFs</fullName>
            </value>
            <value>
                <fullName>Batch to Send Emails Comms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QL_QuipBatchesStatusUpdator.cls
/*
Author: Navpreet Kaur
Class Description: Apex controller that creates and updates the QUIP Scheduled Jobs status.
Date: AUG 2023
EPIC CRM-5831
 */
public with sharing class QL_QuipBatchesStatusUpdator 
{
    public static String batchName;
    public static datetime dateCompleted;
    public static List<QL_QuipScheduledJob__c> listInsertJobs;
    
    //Method that creates the scheduled job record to track batch status progress
    public static List<QL_QuipScheduledJob__c> createStatusRecord(List<Account> getListAccounts,Id getBatchId)
    {
        
        listInsertJobs=new list<QL_QuipScheduledJob__c>();
        AsyncApexJob asyClass = [Select Id, Status,CompletedDate,ApexClass.name, CreatedBy.Email from AsyncApexJob where Id = :getBatchId];
        batchName=asyClass.ApexClass.name;
        
        
        
        system.debug('>>> the value of batchName'+batchName);
        dateCompleted=asyClass.CompletedDate;
        system.debug('>>> the value of dateCompleted'+dateCompleted);
        
        If(getListAccounts!=null && getListAccounts.size()>0)   
                {
                    for(Account acct: getListAccounts)
                    {
                        QL_QuipScheduledJob__c createQuip=new QL_QuipScheduledJob__c();
                        createQuip.QL_Account_Id__c=acct.id;
                        createQuip.QL_Job_Name__c=getUserFriendlyBatchname(batchName);
                        createQuip.QL_Job_Completed_Date__c=dateCompleted;
                        createQuip.QL_Account_Name__c=acct.Legal_Name__c;   
                        createQuip.Account_Owner__c=acct.owner.name;
                        createQuip.Batch_Status__c=asyClass.Status;
                        createQuip.QL_ACR_Subscribed_Count__c=acct.AccountContactRelations.size();
                        
                        listInsertJobs.add(createQuip);    
                    }
                    database.SaveResult[] results=database.insert(listInsertJobs,false);
                    system.debug('>>> the database. save results'+results);
                }    
        return listInsertJobs;    
    }
    //Method that updates the completed scheduled jobs status
    public static List<QL_QuipScheduledJob__c> updateStatusRecord(List<Id> getAccountIds,Id getBatchId)
    {
        List<QL_QuipScheduledJob__c> getScheduledJobs=[select id,QL_Job_Completed_Date__c,QL_Job_Name__c,QL_Job_Scheduled_Date_Time__c,QL_Next_Job_Name__c,Batch_Status__c from QL_QuipScheduledJob__c where QL_Account_Id__c IN: getAccountIds];
        system.debug('>>> received batch job id'+getBatchId);
        listInsertJobs=new list<QL_QuipScheduledJob__c>();
        AsyncApexJob[] asyClass = [Select Id, Status,CompletedDate,ApexClass.name, CreatedBy.Email from AsyncApexJob where Id = :getBatchId];
        batchName=asyClass[0].apexClass.name;
        dateCompleted=   asyClass[0].CompletedDate; 
       
        system.debug('>>> the query results'+asyClass );
        system.debug('>>> batchName '+batchName);
        if(getScheduledJobs.size()>0)
        {
            for(QL_QuipScheduledJob__c getJobs:getScheduledJobs)
            {
                getJobs.Batch_Status__c=asyClass[0].Status;
                getJobs.QL_Job_Completed_Date__c=dateCompleted;
                getJobs.QL_Job_Name__c=getUserFriendlyBatchname(batchName);
                system.debug('the value of each quip scheduled job'+getJobs);
                listInsertJobs.add(getJobs);
            }
            
            if(listInsertJobs.size()>0)
            {
                database.SaveResult[] results=database.update(listInsertJobs,false);
                system.debug('>>> the database. save results for update'+results);
            }
        }
        return listInsertJobs;    
    }
    //Method that updates the next job scheduled date
    public static Boolean updateBatchScheduleTime(List<Id> getAccountIds,datetime getScheduleTime,String batchname)
    {
        List<QL_QuipScheduledJob__c> getScheduledJobs=[select id,QL_Job_Scheduled_Date_Time__c,QL_Next_Job_Name__c,Batch_Status__c from QL_QuipScheduledJob__c where QL_Account_Id__c IN: getAccountIds];
        listInsertJobs=new list<QL_QuipScheduledJob__c>();
        system.debug('>>> received batch name in upadtor'+batchname);
        if(getScheduledJobs.size()>0)
        {
            for(QL_QuipScheduledJob__c getJob:getScheduledJobs)
            {
                if(batchname==null && getScheduleTime==null)
                {
                    getJob.QL_Job_Scheduled_Date_Time__c=null;
                    getJob.QL_Next_Job_Name__c='None';
                    getJob.Batch_Status__c='Completed';
                }
                else
                {
                    getJob.QL_Job_Scheduled_Date_Time__c=getScheduleTime;
                    getJob.QL_Next_Job_Name__c=getUserFriendlyBatchname(batchName);
                }
                system.debug('>>> the job record fields'+getJob);
                listInsertJobs.add(getJob);
            }
            if(listInsertJobs.size()>0)
            {
               database.SaveResult[] results =database.update(listInsertJobs,false);
               system.debug('>>> the database save results for update schedule time'+results);
            }
        }
        return true;
    }
    //Method that forms User friendly batch name
    public static string getUserFriendlyBatchname(String batchname)
    {
        String finalBatchName;
        system.debug('>>> the value of batchname in getUserFriendlyBatchname '+batchname);
        if(batchName.contains('QL_batchClassToInvokeQuipFlowPDF'))
        {
            finalBatchName='Batch To Export As PDFs';
        }
        else if(batchName.contains('QL_batchClassToInvokeQuipFlow'))
        {
            finalBatchName='Batch to Create QUIPs';
        }
        else if(batchName.contains('QL_FlowHelperToScheduleBatch') || batchName.contains('QL_BatchToSendQUIPEmailComms'))
        {
            finalBatchName='Batch to Send Emails Comms';
        }
        else if(batchName.contains('QL_batchClassToInvokeREFRESHQUIPFlow'))
        {
            finalBatchName='Batch to Refresh QUIPs';
        }
        else if(batchName.contains('QL_batchClassToRemoveQuipDocs'))
        {
            finalBatchName='Batch to Remove QUIP Docs';
        }
        return finalBatchName;
    }
}