force-app/main/default/objects/Account/fields/Phone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Phone_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone Country Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Customer&apos;s Frequent Flyer Tier.</description>
    <formula>TEXT(Contact.Frequent_Flyer_Tier__c)</formula>
    <label>Frequent Flyer Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Phone_Country_Code__c</fullName>
    <description>Field for Data Migration</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Country Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_LoyaltyBonus_Channel__c.field-meta.xml
<CustomField>
    <fullName>QCC_LoyaltyBonus_Channel__c</fullName>
    <description>Value comes from the Loyalty platform event when customer opts out for the bonus notification</description>
    <inlineHelpText>Customers with a None value, have selected to not receive bonus reward notifications.</inlineHelpText>
    <label>Loyalty Bonus Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
                <default>true</default>
                <label>SMS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_TECH_Loyalty_Point_Type__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_Loyalty_Point_Type__c</fullName>
    <description>This is used to determine what Loyalty Status Bonus to send as SMS notification.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is used to determine what Loyalty Status Bonus to send as SMS notification.</inlineHelpText>
    <label>QCC TECH Loyalty Point Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_TECH_MobilePhoneCountryCode__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_MobilePhoneCountryCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mobile Phone Country Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_TECH_MobilePhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_MobilePhoneNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mobile Phone Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_LoyaltyStatusSendSMSInvocableTest.cls
/*********************************************************************************
Name         : QCC_LoyaltyStatusSendSMSInvocableTest
Created By   : Raymart Airon Tolentino
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 9 September 2019
Usages       : This class is used for the code coverage of the apex class below:
			   - QCC_LoyaltyStatusSendSMSInvocable

Modified By : Venkata Suresh Kumar (TCS Team), 18-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method. Added Test.start and Test.Stop methods
*********************************************************************************/
@isTest
public class QCC_LoyaltyStatusSendSMSInvocableTest {
	@testSetup
    static void setupTestData(){
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        //Create test data for Account object
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountRecord = QCC_TestDataFactory.createAccountTestData(1);
        accountRecord.RecordTypeId = accountRecordTypeId;
        insert accountRecord;
        
        //Create test data for Contact object
        List<Contact> contactList = new List<Contact>();
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        Contact contactRecord = QCC_TestDataFactory.createContactTestData(1, accountRecord.Id);
        contactRecord.RecordTypeId = contactRecordTypeId;
        contactRecord.Frequent_Flyer_Number__c = '000001';
        contactRecord.Frequent_Flyer_Tier__c = 'Platinum One';
        contactRecord.QCC_TECH_Loyalty_Point_Type__c = 'PB100K';
        contactRecord.QCC_LoyaltyBonus_Channel__c = 'SMS';
        contactRecord.QCC_TECH_MobilePhoneCountryCode__c = '+61';
        contactRecord.QCC_TECH_MobilePhoneNumber__c = '9973073476';
        insert contactRecord;
        
        //Create test data for Qantas API object
        List<Qantas_API__c> qantasAPIRecords = QCC_TestDataFactory.createQantasAPITestDataList();
        insert qantasAPIRecords;

        //Create custom setting for case trigger
        List<Trigger_Status__c> customSettingList = QCC_UtilityHelper.createDynamicObjectRecords('Trigger_Status__c', 'QCCTestDataTriggerStatusCase', null, null, null, null);
        insert customSettingList;
    }
    
    static testmethod void test1(){
        List<Contact> contactRecords = [SELECT Id, FirstName, MobilePhone, Phone_Country_Code__c FROM Contact];
        Test.startTest();
        QCC_LoyaltyStatusSendSMSInvocable.processLoyaltyStatusSMSSending(contactRecords);
        Test.stopTest();
    }
}