force-app/main/default/objects/Account/fields/Proposed_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Revenue_Amount__c</fullName>
    <formula>IF(((Domestic_Air_Travel_Spend__c != 0.00 || Domestic_Air_Travel_Spend__c != NULL) &amp;&amp; (International_Air_Travel_Spend__c != 0.00 || International_Air_Travel_Spend__c != NULL)), 
(Domestic_Air_Travel_Spend__c * 0.90 + International_Air_Travel_Spend__c *0.70), 

IF(((Domestic_Air_Travel_Spend__c == 0.00 || Domestic_Air_Travel_Spend__c == NULL) &amp;&amp; (International_Air_Travel_Spend__c != 0.00 || International_Air_Travel_Spend__c != NULL)), 
International_Air_Travel_Spend__c *0.70, 

IF(((Domestic_Air_Travel_Spend__c != 0.00 || Domestic_Air_Travel_Spend__c != NULL) &amp;&amp; (International_Air_Travel_Spend__c == 0.00 || International_Air_Travel_Spend__c == NULL)), 
Domestic_Air_Travel_Spend__c * 0.90, 

Estimated_Total_Air_Travel_Spend__c)))</formula>
    <label>Proposed Revenue Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AWB_Info__c/AWB_Info__c.object-meta.xml
<CustomObject>
    <label>AWB Info</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AWB Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWB Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AWB_Info__c/fields/Freight_Destination__c.field-meta.xml
<CustomField>
    <fullName>Freight_Destination__c</fullName>
    <description>Freight - It used for AWB Integration, contains destination.
Capturing Destination for AWB Info CRM - 9349</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWB_Info__c/fields/Freight_Origin__c.field-meta.xml
<CustomField>
    <fullName>Freight_Origin__c</fullName>
    <description>Freight - It used for AWB Integration, contains origin - CRM - 9349</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Freight_AWB_Number__c.field-meta.xml
<CustomField>
    <fullName>Freight_AWB_Number__c</fullName>
    <description>Freight - AWB Number to be provided by the customer while raising Complaint against Freight business.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>AWB# must be in format &quot;XXX-XXXXXXXX&quot;</inlineHelpText>
    <label>AWB#</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Freight_Destination__c.field-meta.xml
<CustomField>
    <fullName>Freight_Destination__c</fullName>
    <description>Freight - It used for AWB Integration, contains destination.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Freight_Origin__c.field-meta.xml
<CustomField>
    <fullName>Freight_Origin__c</fullName>
    <description>Freight - It used for AWB Integration, contains origin.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/recordTypes/Freight.recordType-meta.xml
<RecordType>
    <fullName>Freight</fullName>
    <active>true</active>
    <description>For capturing Freight related sales activity insights</description>
    <label>Freight</label>
</RecordType>

force-app/main/default/objects/Case/fields/Customer_Advice_Method__c.field-meta.xml
<CustomField>
    <fullName>Customer_Advice_Method__c</fullName>
    <description>Freight - Drop down showing which resolution method the caller would prefer to get the feedback ie, phone, email, sms/text, other</description>
    <inlineHelpText>Mandatory field. Select as per customer request</inlineHelpText>
    <label>Preferred customer advice method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>SMS_Text</fullName>
                <label>SMS/Text</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Other (add in Comments)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Freight_AWB_Number__c.field-meta.xml
<CustomField>
    <fullName>Freight_AWB_Number__c</fullName>
    <description>Freight - AWB Number to be provided by the customer while raising Complaint against Freight business.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>AWB# must be in format &quot;XXX-XXXXXXXX&quot;</inlineHelpText>
    <label>AWB #</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Freight_Destination__c.field-meta.xml
<CustomField>
    <fullName>Freight_Destination__c</fullName>
    <description>Freight - It used for AWB Integration, contains destination.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Freight_Origin__c.field-meta.xml
<CustomField>
    <fullName>Freight_Origin__c</fullName>
    <description>Freight - It used for AWB Integration, contains origin.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>General Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Procurement/Supplier Relations</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_User_Tradesite__c/Integration_User_Tradesite__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Credentials for tradesite user</description>
    <label>Integration User Tradesite</label>
</CustomObject>

force-app/main/default/objects/Integration_User_Tradesite__c/fields/Authentication_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Endpoint_URL__c</fullName>
    <description>URL for authentication to be specified to get access token</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Authentication Endpoint URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_User_Tradesite__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>To Store Client Ids for OAuth Authentications</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_User_Tradesite__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>To Store Client Secret for OAuth Authentication</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Secret</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_User_Tradesite__c/fields/NameChangeEndNumber__c.field-meta.xml
<CustomField>
    <fullName>NameChangeEndNumber__c</fullName>
    <label>NameChangeEndNumber</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_User_Tradesite__c/fields/NameChangeStartNumber__c.field-meta.xml
<CustomField>
    <fullName>NameChangeStartNumber__c</fullName>
    <label>NameChangeStartNumber</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_User_Tradesite__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Password</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_User_Tradesite__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Username</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Freight_AWB_Number__c.field-meta.xml
<CustomField>
    <fullName>Freight_AWB_Number__c</fullName>
    <defaultValue>&quot;081-&quot;</defaultValue>
    <description>Freight - To record the AWB Number against an Opporrtunity</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Insert AWB number/s associated with this opportunity</inlineHelpText>
    <label>AWB Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Freight_Destination__c.field-meta.xml
<CustomField>
    <fullName>Freight_Destination__c</fullName>
    <description>Freight - It used for AWB Integration, contains destination.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Destination</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Freight_Origin__c.field-meta.xml
<CustomField>
    <fullName>Freight_Origin__c</fullName>
    <description>Freight - It used for AWB Integration, contains origin.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Proposed_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Revenue_Amount__c</fullName>
    <description>delete this</description>
    <inlineHelpText>To be used to capture the proposed revenue amount for the opportunity.</inlineHelpText>
    <label>Proposed Revenue Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Freight.recordType-meta.xml
<RecordType>
    <fullName>Freight</fullName>
    <active>true</active>
    <businessProcess>Freight Sales</businessProcess>
    <description>To be used to capture all opportunities for Qantas Freight</description>
    <label>Freight</label>
</RecordType>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Qantas_API__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>Allows to set the Endpoint of the system to be integrated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FreightAWBPopUpControllerTest.cls
/*----------------------------------------------------------------------------------------------------------------------

************************************************************************************************
History
************************************************************************************************
16-Jan-2026   Mark-Capgemini      CRM-10359:Test method updated for PSV changes
-----------------------------------------------------------------------------------------------------------------------*/
@isTest
public class FreightAWBPopUpControllerTest {
    
    @testSetup
    static void setup() {
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createAccountTriggerSettingasTrue();
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createContactTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createCaseTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createRecoveryTriggerSetting());
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createEventTriggerSetting());
        
        insert lsttrgStatus;
        TestUtilityDataClassQantas.insertQantasConfigData();
        List<Qantas_API__c> lstQantas = TestUtilityDataClassQantas.createQantasAPI();
        insert lstQantas;
        
        String caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Freight Claims').getRecordTypeId();
        String accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Freight Account').getRecordTypeId();
        String conRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        String campRTId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Freight').getRecordTypeId();
        String campmemRTId = Schema.SObjectType.CampaignMember.getRecordTypeInfosByName().get('Freight').getRecordTypeId();
        String oppRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Freight').getRecordTypeId();
        
        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        insert lstConfigData;
        
        TestUtilityDataClassQantas.insertQantasConfigData();
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType();
        TestUtilityDataClassQantas.enableTriggers();
        /*
        Integration_User_Tradesite__c ss = new Integration_User_Tradesite__c(
            Name = 'Freight_iCargo_Integration',
            Username__c = 'SALESICARGOS',
            Password__c = 'CU329VR3',
            Endpoint__c = 'https://api-stage.qantas.com/freight/freightgatewayservice/v1/tracking/shipmentevents/awbs/081-18413673',
            NameChangeStartNumber__c = 1, 
            NameChangeEndNumber__c = 1,
            Client_Id__c = '08c64f80',
            Client_Secret__c = 'f272c21fcea5a9d661f9fe8890510622',
            Authentication_Endpoint_URL__c = 'https://api-stage.qantas.com/customer/oauth/token');
        insert ss; 
        
        
        Trigger_Status__c ts = new Trigger_Status__c(Name = 'trgTradeSiteResponses', Active__c = false);
        insert ts;*/
        
        // Create common test accounts
        Account testacc = new Account(Name='Test Tcs Account',Active__c = true,Type = 'Freight-Country',RecordTypeId = accRTId);
        insert testacc;
        
        Contact testcon = new Contact(FirstName='Bob1',LastName='Test2',AccountId=testacc.id,Function__c = 'IT',Business_Types__c = 'Freight',Email = 'abc@test.com',RecordTypeId =conRTId);
        insert testcon;
        
        //insert new Trigger_Status__c(name = 'trgCaseFieldUpdates',Active__c = true);
        
        Case awbNumOn = new Case(AccountId = testacc.id, RecordTypeId = caseRTId,Subject = 'awbOn',Description = 'test desc',Status = 'Open',Priority = 'Medium',Origin = 'Web',Type = 'Customer Query',Customer_Advice_Method__c = 'Email',Freight_AWB_Number__c = '081-14290113');
        insert awbNumOn;
        
        AWB_Info__c awb = new AWB_Info__c(Name='081-56274540', Freight_Origin__c='SYD', Freight_Destination__c='Sydney');
       insert awb;
        
        
        Campaign testCamp =  new Campaign(Name = 'Test Tcs Campaign', RecordTypeId = campRTId, Status = 'Progress');
        insert testCamp;
        
        CampaignMember campmemawbNum = new CampaignMember(CampaignId = testCamp.id, ContactId = testcon.Id, Status = 'Open', Freight_AWB_Number__c = '081-14290113');
        insert campmemawbNum;
        
        Opportunity oppRecord = new Opportunity ( Name = 'Test Opportunity', AccountId = testacc.Id, Contact__c = testcon.Id, CloseDate = Date.Today()+10,StageName = 'Propose & Negotiate', Proposed_Revenue_Amount__c = 30000, Type = 'Freight', Category__c   ='Freighter', Freight_Shipping__c   = 'Domestic', 
                                                 Freight_Frequency__c    = 'Annual', Freight_Aircraft_Type__c = 'Freighter',RecordTypeId = oppRTId,Forecast_MCA_Revenue__c=20000);
        insert oppRecord;
        
    }
    
    @isTest 
    static void AWBOnTest() {
        
        Case awbNumOn = [SELECT Id,Freight_AWB_Number__c FROM Case WHERE Subject='awbOn' LIMIT 1];
        AWB_Info__c awbc = new AWB_Info__c(Name='081-56274540', Freight_Origin__c='SYD', Freight_Destination__c='Sydney');
      
        //Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration'); 
        /*String jsonResponse = '{'+
                        '"shipmentSummary": {'+
                        '"awb": "081-56274540", "origin": "SYD", "originStationName": "SYDNEY",'+
                        '"destination": "MNL", "destinationStationName": "MANILA", "statedPieces": 1,'+
                        '"statedWeight": "58.0", "statedVolume": 0.645, "shipmentDescription": "1 X LIVE DOG",'+
                        '"handlingCodes": "AVI,EAP,PSR,SPX", "product": "QGO PETS", "productDisplayName": "QGO PETS",'+
                        '"agent": "CT FREIGHT PTY LTD", "consigneeName": "KARL CHWALCZYK C O PET TRANSPRO", "shipperName": "PETFLYERS PTY LTD",'+
                        '"subProduct": null,'+
                        '"stageSummary": {'+
                            '"STAGE_BOOKED": "INACTIVE", "STAGE_DELIVERY": "INACTIVE",'+
                            '"STAGE_GOT_YOUR_FREIGHT": "INACTIVE", "STAGE_INTRANSIT": "INACTIVE",'+
                            '"STAGE_PREDELIVERY": "ACTIVE"'+
                        '},'+
                        '"bookingStatus": null'+
                    '},'+
                    '"shipmentHistory": ['+
                        '{ "eventType": "BKD","airportCode": "SYD","transactionDate": "2024-01-31T14:42:49+11:00",'+
                            '"transactionDateUtc": "2024-01-31T03:42:49Z","pieces": 1,"weight": 58,'+
                            '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                            '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00","arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                            '},'+
                            '"eventDetails": {},"bookingSequence": 1,"eventName": "Flight details",'+
                            '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                        '}'+
                    '],'+
                    '"unitOfMeasures": { "weight": "kg","volume": "cbm","length": "cm"},'+
                    '"shipmentStages": {'+
                        '"STAGE_BOOKED": {'+
                            '"events": ['+
                                '{'+
                                    '"eventType": "BKD","airportCode": "SYD","transactionDate": "2024-01-31T14:42:49+11:00",'+
                                    '"transactionDateUtc": "2024-01-31T03:42:49Z","pieces": 1,"weight": 58,'+
                                    '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                                    '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00",'+
                                    '"arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                                    '}, "eventDetails": {}, "bookingSequence": 1, "eventName": "Flight details",'+ 
                                    '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                                '},'+
                                '{'+
                                    '"eventType": "BKD","airportCode": "AKL","transactionDate": "2024-02-09T11:41:02+13:00",'+
                                    '"transactionDateUtc": "2024-02-08T22:41:02Z","pieces": 1,"weight": 58,'+
                                    '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                                        '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00",'+
                                        '"arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                                    '}, "eventDetails": {},"bookingSequence": 2,"eventName": "Updated flight details",'+
                                    '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                                '}'+
                            '],'+
                            '"status": "INACTIVE"'+
                        '}'+
                    '}'+
                '}';*/
        // Added by Bharath Inti
        String jsonResponse =
        '{' +
        '"shipmentSummary": {' +
        '"origin": "SYD",' +
        '"destination": "MNL",' +
        '"statedPieces": 1,' +
        '"statedWeight": "58.0",' +
        '"handlingCodes": "AVI,TEST",' +
        '"shipmentDescription": "TEST DESC",' +
        '"product": "TEST PROD"' +
        '},' +
        '"shipmentHistory": [' +
        '{' +
        '"eventName":"Flight landed",' +
        '"pieces":1,' +
        '"eventDetails":{"uldNumber":"ULD123"}' +
        '}' +
        '],' +
        '"unitOfMeasures":{"weight":"kg"}' +
        '}';
        //String sampleJSON;
        HTTPResponse resp;
        //sampleJSON = FreightAWBPopUpController.getRequestString(ss.Username__c,ss.Password__c,awbNumOn.Freight_AWB_Number__c);
       // system.debug('json val**'+sampleJSON); 
        String AWB = '081-19639966';
        Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('yes'));
        Test.StartTest();
        FreightAWBPopUpController.getBeforeAWBDetails(awbNumOn.Id);
       // resp = FreightAWBPopUpController.getAWBResponse(sampleJSON,ss,AWB); //Commit error
        // FreightAWBPopUpController.getRecordUpdate(awbNumOn.Id);
        FreightAWBPopUpController.returnParsedCase(jsonResponse, awbc);
        Test.StopTest();    
    }
    
    @isTest 
    static void AWBOffTest() {
        
        Case awbNumOn = [SELECT Id,Freight_AWB_Number__c FROM Case WHERE Subject='awbOn' LIMIT 1];
        
        //Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration');
        
        //String sampleJSON;
        HTTPResponse resp;
        //sampleJSON = FreightAWBPopUpController.getRequestString(ss.Username__c,ss.Password__c,awbNumOn.Freight_AWB_Number__c);
        //system.debug('json val**'+sampleJSON);
        String AWB = '081-19639966';
        Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('no'));
        Test.StartTest();
        resp = FreightAWBPopUpController.getAWBResponse(AWB);
        system.debug('response **'+resp);
        FreightAWBPopUpController.getRecordUpdate(awbNumOn.Id);
        Test.StopTest();    
    }
    
    @isTest 
    static void AWBBlankTest() {
        
        Case awbNumOn = [SELECT Id,Freight_AWB_Number__c FROM Case WHERE Subject='awbOn' LIMIT 1];
        //Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration');
        
        Test.StartTest();
        //String sampleJSON;
        awbNumOn.Freight_AWB_Number__c = '';
        update awbNumOn;
        //sampleJSON = FreightAWBPopUpController.getRequestString(ss.Username__c,ss.Password__c,awbNumOn.Freight_AWB_Number__c);
        FreightAWBPopUpController.getRecordUpdate(awbNumOn.Id);
        Test.StopTest();    
    }
    
    @isTest 
    static void AWBResponseErrorTest() {
        
        Case awbNumOn = [SELECT Id,Freight_AWB_Number__c FROM Case WHERE Subject='awbOn' LIMIT 1];
        // Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration');
        String AWB = '081-19639966';
        //String sampleJSON;
        HTTPResponse resp;
        //sampleJSON = FreightAWBPopUpController.getRequestString(ss.Username__c,ss.Password__c,awbNumOn.Freight_AWB_Number__c);
        //system.debug('json val**'+sampleJSON);
        
        Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('no'));
        Test.StartTest();
        resp = FreightAWBPopUpController.getAWBResponse(AWB);
        system.debug('response **'+resp);
        FreightAWBPopUpController.getRecordUpdate(awbNumOn.Id);
        Test.StopTest();    
    }
    
   /* @isTest 
    static void CampAWBOnTest() {
        
        CampaignMember campmemawbNum = [SELECT Id,Freight_AWB_Number__c FROM CampaignMember WHERE Campaign.Name='Test Tcs Campaign' LIMIT 1];
        
        Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration'); 
        String jsonResponse = '{'+
                        '"shipmentSummary": {'+
                        '"awb": "081-56274540", "origin": "SYD", "originStationName": "SYDNEY",'+
                        '"destination": "MNL", "destinationStationName": "MANILA", "statedPieces": 1,'+
                        '"statedWeight": "58.0", "statedVolume": 0.645, "shipmentDescription": "1 X LIVE DOG",'+
                        '"handlingCodes": "AVI,EAP,PSR,SPX", "product": "QGO PETS", "productDisplayName": "QGO PETS",'+
                        '"agent": "CT FREIGHT PTY LTD", "consigneeName": "KARL CHWALCZYK C O PET TRANSPRO", "shipperName": "PETFLYERS PTY LTD",'+
                        '"subProduct": null,'+
                        '"stageSummary": {'+
                            '"STAGE_BOOKED": "INACTIVE", "STAGE_DELIVERY": "INACTIVE",'+
                            '"STAGE_GOT_YOUR_FREIGHT": "INACTIVE", "STAGE_INTRANSIT": "INACTIVE",'+
                            '"STAGE_PREDELIVERY": "ACTIVE"'+
                        '},'+
                        '"bookingStatus": null'+
                    '},'+
                    '"shipmentHistory": ['+
                        '{ "eventType": "BKD","airportCode": "SYD","transactionDate": "2024-01-31T14:42:49+11:00",'+
                            '"transactionDateUtc": "2024-01-31T03:42:49Z","pieces": 1,"weight": 58,'+
                            '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                            '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00","arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                            '},'+
                            '"eventDetails": { "uldNumber": "PKC20054QF" },"bookingSequence": 1,"eventName": "Flight details",'+
                            '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                        '}'+
                    '],'+
                    '"unitOfMeasures": { "weight": "kg","volume": "cbm","length": "cm"},'+
                    '"shipmentStages": {'+
                        '"STAGE_BOOKED": {'+
                            '"events": ['+
                                '{'+
                                    '"eventType": "BKD","airportCode": "SYD","transactionDate": "2024-01-31T14:42:49+11:00",'+
                                    '"transactionDateUtc": "2024-01-31T03:42:49Z","pieces": 1,"weight": 58,'+
                                    '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                                    '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00",'+
                                    '"arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                                    '}, "eventDetails": {}, "bookingSequence": 1, "eventName": "Flight details",'+ 
                                    '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                                '},'+
                                '{'+
                                    '"eventType": "BKD","airportCode": "AKL","transactionDate": "2024-02-09T11:41:02+13:00",'+
                                    '"transactionDateUtc": "2024-02-08T22:41:02Z","pieces": 1,"weight": 58,'+
                                    '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                                        '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00",'+
                                        '"arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                                    '}, "eventDetails": {},"bookingSequence": 2,"eventName": "Updated flight details",'+
                                    '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                                '}'+
                            '],'+
                            '"status": "INACTIVE"'+
                        '}'+
                    '}'+
                '}';
        String sampleJSON;
        HTTPResponse resp;
        sampleJSON = FreightAWBPopUpController.getRequestStringCampMember(ss.Username__c,ss.Password__c,campmemawbNum.Freight_AWB_Number__c);
        system.debug('json val**'+sampleJSON); 
        String AWB = '081-19639966';
        Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('yes'));
        Test.StartTest();
        FreightAWBPopUpController.getBeforeAWBDetailsCampMember(campmemawbNum.Id);
        resp = FreightAWBPopUpController.getAWBResponseCampMember(sampleJSON,ss,AWB);
        FreightAWBPopUpController.getRecordUpdateCampMember(campmemawbNum.Id);
        FreightAWBPopUpController.returnParsedCampaignMember(jsonResponse, campmemawbNum);
        Test.StopTest();    
    }
    
    @isTest 
    static void CampAWBOffTest() {
        
        CampaignMember campmemawbNum = [SELECT Id,Freight_AWB_Number__c FROM CampaignMember WHERE Campaign.Name='Test Tcs Campaign' LIMIT 1];
        
        Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration');
        
        String sampleJSON;
        HTTPResponse resp;
        sampleJSON = FreightAWBPopUpController.getRequestStringCampMember(ss.Username__c,ss.Password__c,campmemawbNum.Freight_AWB_Number__c);
        system.debug('json val**'+sampleJSON);
        String AWB = '081-19639966';
        Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('no'));
        Test.StartTest();
        
        resp = FreightAWBPopUpController.getAWBResponseCampMember(sampleJSON,ss,AWB);
        system.debug('response **'+resp);
        FreightAWBPopUpController.getRecordUpdateCampMember(campmemawbNum.Id);
        Test.StopTest();    
    }*/
    @isTest 
    static void OptyAWBOnTest() {
        
        Opportunity opp = [SELECT Id,Freight_AWB_Number__c, Freight_Weight__c,Freight_AWB_Pieces__c,Latest_Status__c,
                           Freight_AWB_Handling_Code__c, Freight_Origin__c, Freight_Destination__c,
                           Freight_AWB_Shipment_Description__c,Freight_AWB_Weight_Unit__c,Freight_AWB_Unit_Type__c
                           FROM Opportunity WHERE Name='Test Opportunity' LIMIT 1];
        
        //Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration'); 
        String jsonResponse = '{'+
                        '"shipmentSummary": {'+
                        '"awb": "081-56274540", "origin": "SYD", "originStationName": "SYDNEY",'+
                        '"destination": "MNL", "destinationStationName": "MANILA", "statedPieces": 1,'+
                        '"statedWeight": "58.0", "statedVolume": 0.645, "shipmentDescription": "1 X LIVE DOG",'+
                        '"handlingCodes": "AVI,EAP,PSR,SPX", "product": "QGO PETS", "productDisplayName": "QGO PETS",'+
                        '"agent": "CT FREIGHT PTY LTD", "consigneeName": "KARL CHWALCZYK C O PET TRANSPRO", "shipperName": "PETFLYERS PTY LTD",'+
                        '"subProduct": null,'+
                        '"stageSummary": {'+
                            '"STAGE_BOOKED": "INACTIVE", "STAGE_DELIVERY": "INACTIVE",'+
                            '"STAGE_GOT_YOUR_FREIGHT": "INACTIVE", "STAGE_INTRANSIT": "INACTIVE",'+
                            '"STAGE_PREDELIVERY": "ACTIVE"'+
                        '},'+
                        '"bookingStatus": null'+
                    '},'+
                    '"shipmentHistory": ['+
                        '{ "eventType": "BKD","airportCode": "SYD","transactionDate": "2024-01-31T14:42:49+11:00",'+
                            '"transactionDateUtc": "2024-01-31T03:42:49Z","pieces": 1,"weight": 58,'+
                            '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                            '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00","arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                            '},'+
                            '"eventDetails": { "uldNumber": "PKC20054QF" },"bookingSequence": 1,"eventName": "Flight details",'+
                            '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                        '}'+
                    '],'+
                    '"unitOfMeasures": { "weight": "kg","volume": "cbm","length": "cm"},'+
                    '"shipmentStages": {'+
                        '"STAGE_BOOKED": {'+
                            '"events": ['+
                                '{'+
                                    '"eventType": "BKD","airportCode": "SYD","transactionDate": "2024-01-31T14:42:49+11:00",'+
                                    '"transactionDateUtc": "2024-01-31T03:42:49Z","pieces": 1,"weight": 58,'+
                                    '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                                    '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00",'+
                                    '"arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                                    '}, "eventDetails": {}, "bookingSequence": 1, "eventName": "Flight details",'+ 
                                    '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                                '},'+
                                '{'+
                                    '"eventType": "BKD","airportCode": "AKL","transactionDate": "2024-02-09T11:41:02+13:00",'+
                                    '"transactionDateUtc": "2024-02-08T22:41:02Z","pieces": 1,"weight": 58,'+
                                    '"flightDetails": { "segmentOrigin": "SYD","segmentDestination": "MNL","flightNumber": "QF0019",'+
                                        '"flightDepartureDate": "2024-02-14T12:20:00+11:00","flightArrivalDate": "2024-02-14T17:30:00+08:00",'+
                                        '"arrivalDateStatus": "Scheduled","arrivalStatus": "S"'+
                                    '}, "eventDetails": {},"bookingSequence": 2,"eventName": "Updated flight details",'+
                                    '"stageCode": "STAGE_BOOKED","stageName": "Booked","isLatest": false'+
                                '}'+
                            '],'+
                            '"status": "INACTIVE"'+
                        '}'+
                    '}'+
                '}';
        String sampleJSON;
        HTTPResponse resp;
        //sampleJSON = FreightAWBPopUpController.getRequestStringOppty(ss.Username__c,ss.Password__c,opp.Freight_AWB_Number__c);
        system.debug('json val**'+sampleJSON); 
        String AWB = '081-19639966';
        Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('yes'));
        Test.StartTest();
        FreightAWBPopUpController.getBeforeAWBDetailsOppty(opp.Id);
        //resp = FreightAWBPopUpController.getAWBResponseOppty(sampleJSON,ss,AWB);
        FreightAWBPopUpController.getRecordUpdateOppty(opp.Id);
        FreightAWBPopUpController.returnParsedOpptyMember(jsonResponse, opp);
        Test.StopTest();    
    }
    
    @isTest 
    static void OptyAWBOffTest() {
        
        Opportunity opp = [SELECT Id,Freight_AWB_Number__c, Freight_Weight__c,Freight_AWB_Pieces__c,Latest_Status__c,
                           Freight_AWB_Handling_Code__c, Freight_Origin__c, Freight_Destination__c,
                           Freight_AWB_Shipment_Description__c,Freight_AWB_Weight_Unit__c,Freight_AWB_Unit_Type__c
                           FROM Opportunity WHERE Name='Test Opportunity' LIMIT 1];        
        //Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration');
        
        String sampleJSON;
        HTTPResponse resp;
        //sampleJSON = FreightAWBPopUpController.getRequestStringOppty(ss.Username__c,ss.Password__c,'');
        system.debug('json val**'+sampleJSON);
        String AWB = '081-19639966';
        Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('no'));
        Test.StartTest();
        //resp = FreightAWBPopUpController.getAWBResponseOppty(sampleJSON,ss,AWB);
        //system.debug('response **'+resp);
        FreightAWBPopUpController.getRecordUpdateOppty(opp.Id);
        Test.StopTest();    
    }
    
    
   /* @isTest 
    static void CampAWBBlankTest() {
        
        CampaignMember campmemawbNum = [SELECT Id,Freight_AWB_Number__c FROM CampaignMember WHERE Campaign.Name='Test Tcs Campaign' LIMIT 1];
        
        Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration');
        
        Test.StartTest();
        String sampleJSON;
        campmemawbNum.Freight_AWB_Number__c = '';
        update campmemawbNum;
        sampleJSON = FreightAWBPopUpController.getRequestStringCampMember(ss.Username__c,ss.Password__c,campmemawbNum.Freight_AWB_Number__c);
        FreightAWBPopUpController.getRecordUpdateCampMember(campmemawbNum.Id);
        Test.StopTest();    
    }*/
    
    /*@isTest 
    static void CampAWBResponseErrorTest() {
        
        CampaignMember campmemawbNum = [SELECT Id,Freight_AWB_Number__c FROM CampaignMember WHERE Campaign.Name='Test Tcs Campaign' LIMIT 1];
        
        Integration_User_Tradesite__c ss = Integration_User_Tradesite__c.getInstance('Freight_iCargo_Integration');
        
        String sampleJSON;
        HTTPResponse resp;
        sampleJSON = FreightAWBPopUpController.getRequestStringCampMember(ss.Username__c,ss.Password__c,campmemawbNum.Freight_AWB_Number__c);
        system.debug('json val**'+sampleJSON);
        String AWB = '081-19639966';
        Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest(''));
        Test.StartTest();
        resp = FreightAWBPopUpController.getAWBResponseCampMember(sampleJSON,ss,AWB);
        system.debug('response **'+resp);
        FreightAWBPopUpController.getRecordUpdateCampMember(campmemawbNum.Id);
        Test.StopTest();    
    }*/

    @isTest
    static void GetBeforeAWBDetails_QueryException1() {
        Case c = [SELECT Id FROM Case WHERE Subject='awbOn' LIMIT 1];

        try {
            Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            Alias = 'stduser',
            Email='stduser@qantas.com.au',
            EmailEncodingKey='UTF-8',
            LastName='User',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles',
            Username='stduser'+System.currentTimeMillis()+'@example.com',
            ProfileId = p.Id
        );
        Test.startTest();
        System.runAs(u) {
             FreightAWBPopUpController.getBeforeAWBDetails(c.Id);
        }
         Test.stopTest();                      
        System.assert(false, 'Expected CustomException was not thrown');
        } catch (Exception ex) {
            //System.assert(ex.getMessage().startsWith('You don\'t have access to these fields:'), 'CustomException message did not match expected prefix');
        }
         //catch (Exception ex) {
            //System.assert(ex.getMessage().startsWith('Script-thrown exception'), 'Inaccessible fields: ' + ex.getMessage());
        //}
    }

   
   @isTest static void GetBeforeAWBDetails_QueryException2() {
        String jsonResponse = '{ "shipmentSummary": { "origin": "SYD", "destination": "MNL", "statedPieces": 1, "statedWeight": "10.0", "handlingCodes": "AVI", "shipmentDescription": "DESC", "product": "PROD" }, "shipmentHistory": [], "unitOfMeasures": { "weight": "kg" } }';
        AWB_Info__c awb = new AWB_Info__c(Name='081-00000000', Port_Override_Flag__c = false);

        try {
            Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            Alias = 'stduser',
            Email='stduser@qantas.com.au',
            EmailEncodingKey='UTF-8',
            LastName='User',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles',
            Username='stduser'+System.currentTimeMillis()+'@example.com',
            ProfileId = p.Id
        );
        Test.startTest();
        System.runAs(u) {
            FreightAWBPopUpController.returnParsedCase(jsonResponse, awb);
        }
         Test.stopTest();                      
        //System.assert(false, 'Expected CustomException was not thrown');
        } catch (Exception ex) {
            //System.assert(ex.getMessage().startsWith('You don\'t have access to these fields:'), 'CustomException message did not match expected prefix');
        } //catch (Exception ex) {
          //  System.assert(ex.getMessage().startsWith('Script-thrown exception'), 'Inaccessible fields: ' + ex.getMessage());
        //}
    }

    @isTest
    static void GetBeforeAWBDetails_QueryException3() {
        Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];

        try {
            Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            Alias = 'stduser',
            Email='stduser@qantas.com.au',
            EmailEncodingKey='UTF-8',
            LastName='User',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles',
            Username='stduser'+System.currentTimeMillis()+'@example.com',
            ProfileId = p.Id
        );
        Test.startTest();
        System.runAs(u) {
             FreightAWBPopUpController.getBeforeAWBDetails(o.Id);
        }
         Test.stopTest();                      
        System.assert(false, 'Expected CustomException was not thrown');
        } //catch (FreightAWBPopUpController.CustomException ex) {
            //System.assert(ex.getMessage().startsWith('You don\'t have access to these fields:'), 'CustomException message did not match expected prefix');
        //} 
    catch (Exception ex) {
            //System.assert(ex.getMessage().startsWith('Script-thrown exception'), 'Inaccessible fields: ' + ex.getMessage());
        }
    }
    
    @isTest
    static void GetBeforeAWBDetails_QueryException4() {
        Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];

        try {
            Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            Alias = 'stduser',
            Email='stduser@qantas.com.au',
            EmailEncodingKey='UTF-8',
            LastName='User',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles',
            Username='stduser'+System.currentTimeMillis()+'@example.com',
            ProfileId = p.Id
        );
        Test.startTest();
        System.runAs(u) {
             FreightAWBPopUpController.getBeforeAWBDetailsOppty(o.Id);
        }
         Test.stopTest();                      
        System.assert(false, 'Expected CustomException was not thrown');
        } //catch (FreightAWBPopUpController.CustomException ex) {
           // System.assert(ex.getMessage().startsWith('You don\'t have access to these fields:'), 'CustomException message did not match expected prefix');
        //}
         catch (Exception ex) {
           // System.assert(ex.getMessage().startsWith('Script-thrown exception'), 'Inaccessible fields: ' + ex.getMessage());
        }
    }

   /* @isTest
    static void GetBeforeAWBDetails_QueryException5() {
        
        Campaign testCampaign = new Campaign(
            Name = 'Test Campaign',
            Status = 'Planned',
            Type = 'Email',
            StartDate = Date.today()
        );
        insert testCampaign;

        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'test@example.com'
        );
        insert testContact;

        CampaignMember cm = new CampaignMember(
            CampaignId = testCampaign.Id,
            ContactId = testContact.Id,
            Status = 'Sent'
        );
        insert cm;

        try {
            Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            Alias = 'stduser',
            Email='stduser@example.com',
            EmailEncodingKey='UTF-8',
            LastName='User',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles',
            Username='stduser'+System.currentTimeMillis()+'@example.com',
            ProfileId = p.Id
        );
        Test.startTest();
        System.runAs(u) {
             FreightAWBPopUpController.getBeforeAWBDetailsCampMember(cm.Id);
        }
         Test.stopTest();                      
       // System.assert(false, 'Expected CustomException was not thrown');
        } //catch (FreightAWBPopUpController.CustomException ex) {
            //System.assert(ex.getMessage().startsWith('You don\'t have access to these fields:'), 'CustomException message did not match expected prefix');
        //} 
        catch (Exception ex) {
          //  System.assert(ex.getMessage().startsWith('Script-thrown exception'), 'Inaccessible fields: ' + ex.getMessage());
        }
    }*/
    
    //Added by Bharath Inti

    @isTest
    static void testFullSuccessFlow() {

    Case c = [SELECT Id FROM Case WHERE Subject='awbOn' LIMIT 1];

    Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('yes'));

    Test.startTest();
    FreightAWBPopUpController res =
        FreightAWBPopUpController.getRecordUpdate(c.Id);
    Test.stopTest();

    //System.assertEquals(true, res.isSuccess);
    //Added by Bharath Inti
    System.assertNotEquals(null, res.controllerCase);
    System.assertNotEquals(null, res.controllerCase);
    }
    
    // Added by Bharath Inti
    @isTest
    static void testRetry400Then200() {

    Case c = [SELECT Id FROM Case WHERE Subject='awbOn' LIMIT 1];

    Test.setMock(HttpCalloutMock.class, new Freight_AWBMockRequest('retry'));

    Test.startTest();
    FreightAWBPopUpController res =
        FreightAWBPopUpController.getRecordUpdate(c.Id);
    Test.stopTest();

    System.assertNotEquals(null, res);
    }
}