force-app/main/default/objects/Account/fields/Qantas_Industry_Centre_ID__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Industry_Centre_ID__c</fullName>
    <description>Unique Field after CRM-1340 is resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Qantas Industry Centre Identifier</inlineHelpText>
    <label>QIC ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency_Account.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account</fullName>
    <active>true</active>
    <description>To be used for all Industry Accounts having a contract with Qantas</description>
    <label>Agency Account</label>
</RecordType>

force-app/main/default/objects/Affected_Passenger__c/Affected_Passenger__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures the affected passenger list for a specific Event. This stores passenger information pertaining to the specific Event, such as, FF tier (snapshot), Cabin, Seat No, Pre and Post Flight</description>
    <label>Passenger</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Passenger__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: the related Case for Insurance Letter creation</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Affected_Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Passenger First Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/FrequentFlyerNumber__c.field-meta.xml
<CustomField>
    <fullName>FrequentFlyerNumber__c</fullName>
    <description>QCC: snapshot of the passenger&apos;s frequent flyer number at the time of the Event</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Frequent Flyer Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Passenger Last Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Passenger_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Sequence__c</fullName>
    <label>Passenger Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Passenger_Tattoo_Number__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Tattoo_Number__c</fullName>
    <label>Passenger Tattoo Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Affected_Passenger__c/fields/Passenger_Type__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Type__c</fullName>
    <label>Passenger Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Senior Citizen</fullName>
            </value>
            <value>
                <fullName>Infants</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Infant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <description>QCC: Used to track/store the arrival airport for a case</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Airport</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cabin_Class__c.field-meta.xml
<CustomField>
    <fullName>Cabin_Class__c</fullName>
    <description>QCC: Created to show/store Customer Cabin Class.</description>
    <inlineHelpText>CCC: Required for queuing prioritisation</inlineHelpText>
    <label>Cabin Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBC</fullName>
            </value>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <description>QCC: Used to track/store the departure airport information on a case</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Airport</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <description>QCC: Created to show/store Customer Flight Number for which this Case is raised.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/GDS_DI__c.field-meta.xml
<CustomField>
    <fullName>GDS_DI__c</fullName>
    <description>used in QAC project for the Service Request record type.</description>
    <label>GDS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AARON GROUP</fullName>
            </value>
            <value>
                <fullName>Aeronology</fullName>
            </value>
            <value>
                <fullName>AirGateway</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Apollo</fullName>
            </value>
            <value>
                <fullName>ClarityTTS</fullName>
            </value>
            <value>
                <fullName>CTM</fullName>
            </value>
            <value>
                <fullName>Duffel</fullName>
            </value>
            <value>
                <fullName>Expedia</fullName>
            </value>
            <value>
                <fullName>QDP</fullName>
                <label>Farelogix (F1)</label>
            </value>
            <value>
                <fullName>Galileo</fullName>
            </value>
            <value>
                <fullName>Infini</fullName>
            </value>
            <value>
                <fullName>Kyte</fullName>
            </value>
            <value>
                <fullName>Mystifly</fullName>
            </value>
            <value>
                <fullName>Navan</fullName>
            </value>
            <value>
                <fullName>QDP Portal</fullName>
            </value>
            <value>
                <fullName>Sabre</fullName>
            </value>
            <value>
                <fullName>Sabre Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Serko</fullName>
            </value>
            <value>
                <fullName>Spotnana</fullName>
            </value>
            <value>
                <fullName>TPConnects</fullName>
            </value>
            <value>
                <fullName>Travelfusion</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Concur</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Cytric</fullName>
            </value>
            <value>
                <fullName>Travelfusion – Locomote</fullName>
            </value>
            <value>
                <fullName>Travelsky</fullName>
            </value>
            <value>
                <fullName>Verteil Technologies</fullName>
            </value>
            <value>
                <fullName>Worldspan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>QF-{0000000}</displayFormat>
        <label>Flight ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Airport</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Cabin_Class__c.field-meta.xml
<CustomField>
    <fullName>Cabin_Class__c</fullName>
    <label>Cabin Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Airport</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Qantas_API__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>Allows to set the Endpoint of the system to be integrated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Sets the method for the system to be integrated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QAC_PNRSearch_Controller.cls
/*
 * Created By : Abhijeet | TCS | Cloud Developer. 
 * Purpose : Search Booking Application's Controller.
 * Modified by : Ajay | Purpose : To include local PNR Search.
 * Referred in Ltng Component: QAC_SearchForm, QAC_PNRSearch_Tab.
*/

public with sharing class QAC_PNRSearch_Controller
{
    @AuraEnabled
    public static Map<String,String> fieldMap(List<String> fieldAPINames)
    {
        system.debug('incoming field map**'+fieldAPINames);
        Map<String, Schema.SObjectField> thefieldMap = Schema.SObjectType.Case.fields.getMap();
        Map<String,String> myFieldMap = new Map<String,String>();
        
        for(String eachAPIName: fieldAPINames){
            myFieldMap.put(eachAPIName,thefieldMap.get(eachAPIName).getDescribe().getLabel());
        }
        system.debug('my field map**'+myFieldMap);
        return myFieldMap;
    }

    @AuraEnabled
    public static list<Case> getLocalSearchCases(String pnrNum){
        if(String.isNotBlank(pnrNum)){
            return QAC_localPNRCases.getAllPNRCases(pnrNum,NULL);
        }
        return null;
    }

    @AuraEnabled 
    public static QAC_PNRDetailsWrapper invokeCallout(String pnrNumber, String lastName){
        
        lastName = EncodingUtil.urlEncode(lastName, 'UTF-8').replaceAll('\\+','%20');
        
        // To retrieve Authentication token
        String token = QCC_GenericUtils.getCAPValidToken('QCC_BookingToken');
        // To update authentication token
        QCC_GenericUtils.updateToken(token, 'QCC_BookingToken');
        
        // Complete information to be returned to Component
        QAC_PNRDetailsWrapper pnrInfo = new QAC_PNRDetailsWrapper();
        
        // Retrieving Flight Details
        pnrInfo.flightDetailsWrapper = getFlightDetails(pnrNumber, lastName, token);
        
        // Retrieving Passenger Details
        pnrInfo.passengerDetailsWrapper = getPassengerDetails(pnrNumber, lastName, token);
        
        // Retrieving Point of Sales Information
        pnrInfo.pointSales = getPointOfSales(pnrNumber, lastName, token);
        
        // Retrieving Case Details
        pnrInfo.caseFields = getCaseDetails(pnrNumber, pnrInfo);
        
        
    
        return pnrInfo;
    }
    
    // Returning Point of Sales from Booking API
    public Static QAC_PNRDetailsWrapper.PointOfSalesWrapper getPointOfSales(String pnrNumber, String lastName, String token)
    {
        QAC_PNRDetailsWrapper.PointOfSalesWrapper returnPointOfSales;
        
        Qantas_API__c qantasAPI = CustomSettingsUtilities.getQantasCAPAPI('QAC_PointOfSales');
        
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        String dynamicURL = '/'+pnrNumber+'/point-of-sale?lastName=' + lastName;
        String endpointURL = qantasAPI.EndPoint__c+''+dynamicURL;
        
        req.setEndpoint(endpointURL);
        req.setMethod(qantasAPI.Method__c); 
        req.setHeader('System', 'CAPCRE_CC');
        req.setHeader('Authorization', token);
        req.setTimeout(120000);
        HTTPResponse response = http.send(req);
        
        QAC_PointOfSalesParser pnrPassenger;
        //Jira CRM-6218: Token refresh when there is a mismatch
        if (response.getStatusCode() == 401)
        {
            token = QCC_GenericUtils.getCAPValidToken('QCC_BookingToken', true);
            QCC_GenericUtils.updateToken(token, 'QCC_BookingToken');
            req.setHeader('Authorization', token);
            response = http.send(req);
        }
        
        if(response.getStatusCode() == 200){
            system.debug('Point of Sales response Body#########' + response.getBody());
            pnrPassenger = QAC_PointOfSalesParser.parse(response.getBody());
            system.debug('QCC_PNRBookingRetrieveCAPWrapper#########'+pnrPassenger);
        }
        
        if(pnrPassenger != null){
            returnPointOfSales = new QAC_PNRDetailsWrapper.PointOfSalesWrapper(pnrPassenger.Booking.pointofSale);
        }
        system.debug('QCC_PNRBookingRetrieveCAPWrapper#########'+returnPointOfSales);
        return returnPointOfSales;
    }
    
    // Invoking Passenger API, to retrieve Passenger details from CAP CRE
    // Returning list Passenger details wrapper
    public Static List<QAC_PNRDetailsWrapper.PassengerDetailsWrapper> getPassengerDetails(String pnrNumber, String lastName, String token){
        
        List<QAC_PNRDetailsWrapper.PassengerDetailsWrapper> returnPassengerDetails = new List<QAC_PNRDetailsWrapper.PassengerDetailsWrapper>();
        
        Qantas_API__c qantasAPI = CustomSettingsUtilities.getQantasCAPAPI('QCC_CAPPNRRetrieve');
        
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        String dynamicURL = '/'+pnrNumber+'/passengers?lastName=' + lastName;
        String endpointURL = qantasAPI.EndPoint__c+''+dynamicURL;
        req.setEndpoint(endpointURL);
        req.setMethod(qantasAPI.Method__c); 
        req.setHeader('System', 'CAPCRE_CC');
        req.setHeader('Authorization', token);
        req.setTimeout(120000);
        HTTPResponse response = http.send(req);
        
        QCC_PNRPassengerInfoWrapper pnrPassenger = new QCC_PNRPassengerInfoWrapper();
        //Jira CRM-6218: Token refresh when there is a mismatch
        if (response.getStatusCode() == 401)
        {
            token = QCC_GenericUtils.getCAPValidToken('QCC_BookingToken', true);
             QCC_GenericUtils.updateToken(token, 'QCC_BookingToken');
            req.setHeader('Authorization', token);
            response = http.send(req);
        }
       
        if(response.getStatusCode() == 200){
            system.debug('response Body#########' + response.getBody());
            pnrPassenger = (QCC_PNRPassengerInfoWrapper)JSON.deserialize(response.getBody(), QCC_PNRPassengerInfoWrapper.class);
            system.debug('QCC_PNRBookingRetrieveCAPWrapper#########'+pnrPassenger);
        }
        
        if(pnrPassenger != null && pnrPassenger.Booking != null && pnrPassenger.Booking.passengers != null)
        {
            for( QCC_PNRPassengerInfoWrapper.Passengers eachRec : pnrPassenger.Booking.passengers ){
                returnPassengerDetails.add(new QAC_PNRDetailsWrapper.PassengerDetailsWrapper(eachRec, False));
            }    
        }
        system.debug('QCC_PNRBookingRetrieveCAPWrapper#########'+returnPassengerDetails);
        
        return returnPassengerDetails;
    }
    
    // Invoking Flight API, to retrieve Flight details from CAP CRE
    // Returning list Flight details wrapper
    public Static List<QAC_PNRDetailsWrapper.FlightDetailsWrapper> getFlightDetails(String pnrNumber, String lastName, String token)
    {
        List<QAC_PNRDetailsWrapper.FlightDetailsWrapper> returnFlightDetails = new List<QAC_PNRDetailsWrapper.FlightDetailsWrapper>();
        
        Qantas_API__c qantasAPI = CustomSettingsUtilities.getQantasCAPAPI('QCC_CAPPNRRetrieve');
        
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        String dynamicURL = '/'+pnrNumber+'/flights?lastName='+lastName;
        String endpointURL = qantasAPI.EndPoint__c + '' + dynamicURL;
        req.setEndpoint(endpointURL);
        req.setMethod(qantasAPI.Method__c); 
        req.setHeader('System', 'CAPCRE_CC');
        req.setHeader('Authorization', token);
        req.setTimeout(120000);
        HTTPResponse response = http.send(req);
        
        QCC_PNRFlightInfoWrapper pnrBooking = new QCC_PNRFlightInfoWrapper();
        
        //Jira CRM-6218: Token refresh when there is a mismatch
        if (response.getStatusCode() == 401)
        {
            token = QCC_GenericUtils.getCAPValidToken('QCC_BookingToken', true);
            QCC_GenericUtils.updateToken(token, 'QCC_BookingToken');
            req.setHeader('Authorization', token);
            response = http.send(req);
        }

        
        if(response.getStatusCode() == 200){
            system.debug('response Body#########'+response.getBody());
            pnrBooking = (QCC_PNRFlightInfoWrapper)JSON.deserialize(response.getBody(), QCC_PNRFlightInfoWrapper.class);
            system.debug('QCC_PNRFlightInfoWrapper#########'+pnrBooking);
        }
        
        if(pnrBooking != null && pnrBooking.Booking != null && pnrBooking.Booking.Segments != null)
        {
            for(QCC_PNRFlightInfoWrapper.Segments eachRec : pnrBooking.Booking.Segments){
                returnFlightDetails.add(new QAC_PNRDetailsWrapper.FlightDetailsWrapper(eachRec, False));
            }    
        }
        
        for(QAC_PNRDetailsWrapper.FlightDetailsWrapper eachVar : returnFlightDetails){
            eachVar.flightDetails.arrivalLocalTime = eachVar.flightDetails.arrivalLocalTime.left(5);
            eachVar.flightDetails.departureLocalTime = eachVar.flightDetails.departureLocalTime.left(5);
        }
        
        system.debug(' Reture Data '+returnFlightDetails);
        return returnFlightDetails;
    }
    
    // To return list of Affected_Passenger__c to be inserted 
    public static list<Affected_Passenger__c> preparePassengerData(String caseId, list<QAC_PNRDetailsWrapper.PassengerDetailsWrapper> passengersList){
        
        list<Affected_Passenger__c> toReturnPassengersList = new List<Affected_Passenger__c>();
        String recTypeId = Schema.SObjectType.Affected_Passenger__c.getRecordTypeInfosByName().get('Service Request').getRecordTypeId();
        for(QAC_PNRDetailsWrapper.PassengerDetailsWrapper eachRec : passengersList)
        {
            if(eachRec.selectedFlight)
            {
                System.debug('@@ eachRec @@ ' + eachRec);
                toReturnPassengersList.add(new Affected_Passenger__c (Case__c               = caseId,
                                                                      FirstName__c           = eachRec.passengerDetails.firstName,
                                                                      FrequentFlyerNumber__c = eachRec.passengerDetails.qantasFFNo,
                                                                      LastName__c            = eachRec.passengerDetails.lastName,
                                                                      Name                   = eachRec.passengerDetails.firstName + ' ' + eachRec.passengerDetails.lastName,
                                                                      RecordTypeId           = recTypeId,
                                                                      Passenger_Sequence__c  = String.isNotBlank(eachRec.passengerDetails.passengerTattoo) ? Decimal.valueOf(eachRec.passengerDetails.passengerTattoo): null,
                                                                      Passenger_Tattoo_Number__c = String.isNotBlank(eachRec.passengerDetails.passengerTattoo) ? Decimal.valueOf(eachRec.passengerDetails.passengerTattoo): null,
                                                                      Passenger_Type__c      = QAC_CaseMappingUtility.fetchPassengerType(eachRec.passengerDetails.typeCode)
                                                                     ));
            }
        }
        
        return toReturnPassengersList;
    }
    
    // To return list of Flights to be inserted 
    public static list<Flight__c> prepareFlightData(String caseId, list<QAC_PNRDetailsWrapper.FlightDetailsWrapper> flightList){
        
        list<Flight__c> toReturnFlightList = new List<Flight__c>();
        list<String> dataParamters = new list<String>();
        Date departureDate;
        Integer arrivalDays = 0;
        for(QAC_PNRDetailsWrapper.FlightDetailsWrapper eachRec : flightList)
        {
            if(eachRec.selectedFlight){
                System.debug('@@ eachRec @@ ' + eachRec.flightDetails.departureLocalTime);
                dataParamters = eachRec.flightDetails.departureLocalDate.split('/');
                departureDate = Date.newInstance(Integer.valueOf(dataParamters[2]),Integer.valueOf(dataParamters[1]),Integer.valueOf(dataParamters[0]));
                dataParamters = new list<String>(); 
                dataParamters = eachRec.flightDetails.arrivalLocalDate.split('/');
                arrivalDays = departureDate.daysBetween(Date.newInstance(Integer.valueOf(dataParamters[2]),Integer.valueOf(dataParamters[1]),Integer.valueOf(dataParamters[0])));
                
                toReturnFlightList.add(new Flight__c    (Case__c                    = caseId,
                                                         Arrival_Airport__c         = eachRec.flightDetails.arrivalAirportCode,
                                                         Departure_Airport__c       = eachRec.flightDetails.departureAirportCode,
                                                         Flight_Number__c           = eachRec.flightDetails.marketingCarrierAlphaCode + eachRec.flightDetails.marketingFlightNumber,
                                                         Flight_Date__c             = departureDate,
                                                         Arrival_Time__c            = (arrivalDays > 0) ? eachRec.flightDetails.arrivalLocalTime + ' +' + String.valueOf(arrivalDays) : eachRec.flightDetails.arrivalLocalTime,
                                                         Departure_Time__c          = eachRec.flightDetails.departureLocalTime,
                                                         // Cabin_Class__c              = eachRec.flightDetails.departureLocalTime,
                                                         Cabin_Class__c             = eachRec.flightDetails.bookedReservationClass));
            }
        }
        
        return toReturnFlightList;
    }
    
    @AuraEnabled
    public static String getRecordTypeId(){
        String rtId = (String)QAC_PaymentsProcess.fetchRecordTypeId('Case','Service Request');
        return rtId;
    } 
    
    public static QAC_PNRDetailsWrapper.CaseDefaultValues getCaseDetails(String pnrNumber, QAC_PNRDetailsWrapper pnrInfo)
    {
        String travelAgentCode;
        String qciCode;
        String abnNumber;
        String passengerName;

        // added by Ajay for calc First Flight Date & First Flight Number
        list<String> dataParameters = new list<String>();
        list<String> timeParameters = new list<String>();
        Datetime departureDT;
        Date firstFLDate;
        String firstFLNumber;
        List<Datetime> DateDiff = new List<Datetime>();
        map<Datetime,String> FFDt_FFNo_map = new map<Datetime,String>();
        // ended
        
        Integer count = 0;
        String agencyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agency_Account').getRecordTypeId();
        list<Account> agencies = new list<Account>();
        Account agencyRef = new Account();
        String gdsValue;
        if(pnrInfo != NULL && pnrInfo.pointSales != null && pnrInfo.pointSales.pointOfSales.creatorDetails.companyId != NULL){
            gdsValue = QAC_CaseMappingUtility.fetchGDSValues(pnrInfo.pointSales.pointOfSales.creatorDetails.companyId);
        }
        system.debug('@@ gdsValue @@ ' + gdsValue);
        
        if(pnrInfo != NULL)
        {
            for(QAC_PNRDetailsWrapper.PassengerDetailsWrapper eachRec : pnrInfo.passengerDetailsWrapper){
                qciCode = eachRec.passengerDetails.corpId;
                abnNumber = eachRec.passengerDetails.smeId;
                passengerName = eachRec.passengerDetails.firstName + ' ' + eachRec.passengerDetails.lastName;
                count ++ ;
            }
            
            // added by Ajay to calculate first flight Date
            for(QAC_PNRDetailsWrapper.FlightDetailsWrapper eachFRec : pnrInfo.flightDetailsWrapper){
                dataParameters = eachFRec.flightDetails.departureLocalDate.split('/');
                timeParameters = eachFRec.flightDetails.departureLocalTime.split(':');
                
                departureDT = datetime.newInstance(
                                        Integer.valueOf(dataParameters[2]),
                                        Integer.valueOf(dataParameters[1]),
                                        Integer.valueOf(dataParameters[0]),
                                        Integer.valueOf(timeParameters[0]),
                                        Integer.valueOf(timeParameters[1]),
                                        0                    
                                    );
                
                if(departureDT >= System.now()){
                    DateDiff.add(departureDT);
                    String FFNo = eachFRec.flightDetails.marketingCarrierAlphaCode + eachFRec.flightDetails.marketingFlightNumber;
                    FFDt_FFNo_map.put(departureDT,FFNo);
                }
            }
            system.debug('date diff*'+DateDiff+' |date Flight Map'+FFDt_FFNo_map);
            if(!DateDiff.isEmpty()){
                DateDiff.sort();
                firstFLDate = DateDiff[0].date();
                firstFLNumber = FFDt_FFNo_map.get(DateDiff[0]);
            }
            // ended
            
            if(pnrInfo.pointSales != null){
                if(pnrInfo.pointSales.pointOfSales.creatorDetails.travelAgentId != NULL ) {
                    travelAgentCode = pnrInfo.pointSales.pointOfSales.creatorDetails.travelAgentId.left(7);
                    for(Account myAcc : [SELECT Id, Name FROM Account WHERE Qantas_Industry_Centre_ID__c =: travelAgentCode AND RecordTypeId =: agencyRecordTypeId LIMIT 1])
                    {
                        if(myAcc != null) agencyRef = myAcc;    
                    }
                    //agencies = [SELECT Id, Name FROM Account WHERE Qantas_Industry_Centre_ID__c =: travelAgentCode AND RecordTypeId =: agencyRecordTypeId LIMIT 1];
                }
            }
            
            system.debug('@@ Agency Name @@ ' + agencyRef);
        }
        return (new QAC_PNRDetailsWrapper.CaseDefaultValues(agencyRef,'Open','Phone',pnrNumber,abnNumber,qciCode,passengerName, String.valueOf(count), travelAgentCode, firstFLNumber, firstFLDate, gdsValue));
    }    
    
    @AuraEnabled 
    public static User fetchUser(){
        // query current user information  
        return [Select Id, Name FROM User Where id =: userInfo.getUserId()];
    }
    
    @AuraEnabled
    public static String createCase(String passengers, String flights, String caseFields, String caseId)
    {
        try{
            if(!string.isBlank(flights)){
                list<QAC_PNRDetailsWrapper.FlightDetailsWrapper> flightWrapperList = (list<QAC_PNRDetailsWrapper.FlightDetailsWrapper>)System.JSON.deserialize(flights,list<QAC_PNRDetailsWrapper.FlightDetailsWrapper>.class);
                list<Flight__c> toInsertFlights = prepareFlightData(caseId, flightWrapperList);
                insert toInsertFlights;
            }
            
            if(!string.isBlank(passengers)){
                list<QAC_PNRDetailsWrapper.PassengerDetailsWrapper> passengerWrapperList = (list<QAC_PNRDetailsWrapper.PassengerDetailsWrapper>)System.JSON.deserialize(passengers,list<QAC_PNRDetailsWrapper.PassengerDetailsWrapper>.class);
                list<Affected_Passenger__c> toInsertPassengers = preparePassengerData(caseId, passengerWrapperList);
                insert toInsertPassengers;
            }
            
            if(!string.isBlank(caseFields)){
                QAC_PNRDetailsWrapper.CaseDefaultValues caseValues = (QAC_PNRDetailsWrapper.CaseDefaultValues)System.JSON.deserialize(caseFields,QAC_PNRDetailsWrapper.CaseDefaultValues.class);
                Case toUpdateCase = new Case (Id = caseId, GDS_DI__c = caseValues.gdsValue);
                update toUpdateCase;
            }
        }
        catch(Exception ex){}
        return caseId;
    }
}