force-app/main/default/objects/Account/fields/Qantas_Industry_Centre_ID__c.field-meta.xml
<CustomField>
    <fullName>Qantas_Industry_Centre_ID__c</fullName>
    <description>Unique Field after CRM-1340 is resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Qantas Industry Centre Identifier</inlineHelpText>
    <label>QIC ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Tradesite__c.field-meta.xml
<CustomField>
    <fullName>Tradesite__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Mark if the agent is a register user of the Industry Sales Site</inlineHelpText>
    <label>Tradesite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency_Account.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account</fullName>
    <active>true</active>
    <description>To be used for all Industry Accounts having a contract with Qantas</description>
    <label>Agency Account</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Agency_Identifier__c</fullName>
    <description>QAC - Agency Credits</description>
    <formula>Account.Qantas_Industry_Centre_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Asset_Year__c.field-meta.xml
<CustomField>
    <fullName>Asset_Year__c</fullName>
    <description>QAC</description>
    <label>Asset Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Total_Acquired_Credits__c.field-meta.xml
<CustomField>
    <fullName>Total_Acquired_Credits__c</fullName>
    <defaultValue>(0)</defaultValue>
    <description>QAC</description>
    <label>Total Acquired Credits</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Total_Consumed_Credits__c.field-meta.xml
<CustomField>
    <fullName>Total_Consumed_Credits__c</fullName>
    <defaultValue>(0)</defaultValue>
    <description>QAC</description>
    <label>Total Consumed Credits</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Total_Outstanding_Credits__c.field-meta.xml
<CustomField>
    <fullName>Total_Outstanding_Credits__c</fullName>
    <description>QAC</description>
    <formula>Total_Acquired_Credits__c  -  Total_Consumed_Credits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Outstanding Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Agency_Credit.recordType-meta.xml
<RecordType>
    <fullName>Agency_Credit</fullName>
    <active>true</active>
    <description>QAC - Agency Credits record type</description>
    <label>Agency Credit</label>
</RecordType>

force-app/main/default/objects/Case/fields/Sub_Type_1__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_1__c</fullName>
    <label>Sub Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>Act on a Schedule Change</fullName>
            </value>
            <value>
                <fullName>Add an Infant</fullName>
            </value>
            <value>
                <fullName>Ad-hoc Credits</fullName>
                <isActive>false</isActive>
                <label>Ad-hoc Credits</label>
            </value>
            <value>
                <fullName>ADM/BSP/ARC Billing</fullName>
            </value>
            <value>
                <fullName>ADM/BSP Billing</fullName>
            </value>
            <value>
                <fullName>AEQCC</fullName>
            </value>
            <value>
                <fullName>Agency Connect</fullName>
                <isActive>false</isActive>
                <label>Agency Connect</label>
            </value>
            <value>
                <fullName>Agency Product Fares</fullName>
                <isActive>false</isActive>
                <label>Agency Product Fares</label>
            </value>
            <value>
                <fullName>Already in Lightning</fullName>
            </value>
            <value>
                <fullName>Animal</fullName>
            </value>
            <value>
                <fullName>Atlas</fullName>
            </value>
            <value>
                <fullName>AVI</fullName>
            </value>
            <value>
                <fullName>AWB not found in iCargo</fullName>
            </value>
            <value>
                <fullName>AWB Not Found in warehouse</fullName>
            </value>
            <value>
                <fullName>AWB wrong location</fullName>
            </value>
            <value>
                <fullName>AWB wrong location (from ULD in wrong location)</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Cancel Booking</fullName>
            </value>
            <value>
                <fullName>Capacity</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Change flight time, date or location</fullName>
            </value>
            <value>
                <fullName>Change of TMC</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Charter Rate</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
                <isActive>false</isActive>
                <label>Chatter</label>
            </value>
            <value>
                <fullName>Conga Related</fullName>
            </value>
            <value>
                <fullName>Cool room Pre Alert</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <description>QAC - This object is used to maintain the transaction history of agency credit points.</description>
    <label>Ledger</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QAC</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Credits_Ledger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Agency_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Agency_Identifier__c</fullName>
    <description>QAC</description>
    <formula>Account__r.Qantas_Industry_Centre_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QAC</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Credits_Ledger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Qac</description>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adhoc Credits</fullName>
            </value>
            <value>
                <fullName>Annual Credits</fullName>
            </value>
            <value>
                <fullName>Expired Credits</fullName>
            </value>
            <value>
                <fullName>Paid Service (Online)</fullName>
            </value>
            <value>
                <fullName>Paid Service (Offline)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Total_Credit_value__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit_value__c</fullName>
    <description>QAC</description>
    <label>Total Credit value</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Total_Outstanding_credits__c.field-meta.xml
<CustomField>
    <fullName>Total_Outstanding_credits__c</fullName>
    <description>QAC</description>
    <label>Total Outstanding credits</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Transaction_date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_date__c</fullName>
    <description>Qac</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Transaction date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Transaction_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Frequency__c</fullName>
    <description>QAC</description>
    <label>Transaction Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>QAC</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger__c/recordTypes/Agency_Credit.recordType-meta.xml
<RecordType>
    <fullName>Agency_Credit</fullName>
    <active>true</active>
    <description>QAC- Agency Credit record type</description>
    <label>Agency Credit</label>
</RecordType>

force-app/main/default/classes/QAC_Credits.cls
/***********************************************************************************************************************************
Description: ResptAPI class for GET on Asset,Ledger__c. It would get Credits from Asset and Statement from Ledger__c  
Author: Sobhan - TCS

***********************************************************************************************************************************/
@RestResource(urlmapping='/QACCredits/*')
global with sharing class QAC_Credits {

    public static string responseJson='';
    Public Static QAC_CreditsResponse assetResp = new QAC_CreditsResponse();
    
    @HttpGet
    global static void doCreditsRetrieval()
    {
         /*
         * Variable Declarations
         */
        RestRequest request                             = RestContext.request;
        RestResponse response                           = RestContext.response;
        
        list<QAC_CreditsResponse.balanceResponse> assetResponsesList = new list<QAC_CreditsResponse.balanceResponse>();
        List<QAC_CreditsResponse.FieldErrors> listFieldErrorResp = new List<QAC_CreditsResponse.FieldErrors>();
        QAC_CreditsResponse.ExceptionResponse myExceptionResponse; 
    
        String accId;
        String filter;
        
        map<Id,Account> existingAccountMap = new Map<Id,Account>();
        map<Id,list<Asset>> existingAssetsMap = new map<Id,list<Asset>>();
        map<Id,list<Asset>> inactiveAssetsMap = new map<Id,list<Asset>>();
        try{
           String agencyCode = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
            system.debug('agencyCode @@'+agencyCode);
            filter = request.params.get('filter');
            Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agency_Account').getRecordTypeId();
            
            if(String.isNotBlank(agencyCode))
            {
                for(Account eachAccount : [Select Id, Qantas_Industry_Centre_ID__c,Active__c,Tradesite__c from Account 
                                           where Qantas_Industry_Centre_ID__c =: agencyCode AND RecordTypeId =: accRTId])
                {
                    if(eachAccount != null){
                        existingAccountMap.put(eachAccount.Id,eachAccount);
                        accId = eachAccount.Id;
                    }
                }
                system.debug('existingAccount:'+existingAccountMap);
                
                if(!existingAccountMap.isEmpty())
                {
                    if(existingAccountMap.get(accId).Active__c==false || existingAccountMap.get(accId).Tradesite__c==false )
                    {
                        response.statusCode         = 404;
                        listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('AccountId','No Active Account For Agency :'+agencyCode));
                        myExceptionResponse         = new QAC_CreditsResponse.ExceptionResponse('404','Agency not Active', listFieldErrorResp); 
                        assetResp.exceptionResponse=myExceptionResponse;
                        
                        //response.responseBody     = Blob.valueOf(JSON.serializePretty(myExceptionResponse, true));   
                    }
                    else{
                    String asstRecType = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Agency_Credit').getRecordTypeId();
                    for(Asset eachAsset : [SELECT id,AccountId,Agency_Identifier__c,Asset_Year__c,Total_Acquired_Credits__c,Total_Consumed_Credits__c,
                               Total_Outstanding_Credits__c,Active__c FROM Asset
                               WHERE AccountId IN: existingAccountMap.keySet()  
                               AND RecordTypeId =:asstRecType])
                    {
                        if(eachAsset != null){
                            if(eachAsset.Active__c)
                            {
                                if(existingAssetsMap.containsKey(eachAsset.AccountId)){
                                    existingAssetsMap.get(eachAsset.AccountId).add(eachAsset);
                                }
                                else{
                                    existingAssetsMap.put(eachAsset.AccountId, new list<Asset>{eachAsset});
                                }
                            }
                            else{
                              if(inactiveAssetsMap.containsKey(eachAsset.AccountId)){
                                inactiveAssetsMap.get(eachAsset.AccountId).add(eachAsset);
                            }
                            else{
                                inactiveAssetsMap.put(eachAsset.AccountId, new list<Asset>{eachAsset});
                            }  
                            }
                        }
                    }
                    if(filter!='Statement' && existingAssetsMap.isEmpty()){
                    response.statusCode         = 412;
                    listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('Assets', 'No Active Assets Found'));
                    myExceptionResponse         = new QAC_CreditsResponse.ExceptionResponse('412', 'Agency not eligible for this program', listFieldErrorResp); 
                    assetResp.exceptionResponse=myExceptionResponse;
                    //response.responseBody     = Blob.valueOf(JSON.serializePretty(myExceptionResponse, true));    
                    }
                    else if(filter=='Statement'){
                        assetResp=  doLedger(existingAccountMap,existingAssetsMap,inactiveAssetsMap,accId,request,response);    
                    }
                    else if(existingAssetsMap.get(accId).size()>0){
                           if(existingAssetsMap.get(accId).size() == 1){
                                response.statusCode         = 200;
                                assetResponsesList.add(new QAC_CreditsResponse.balanceResponse(existingAssetsMap.get(accId)));
                                assetResp.creditResponse = assetResponsesList;
                               
                            //response.responseBody         = Blob.valueOf(JSON.serializePretty(assetResponsesList, true));    
                            }
                            else if(existingAssetsMap.get(accId).size() > 1){
                            response.statusCode         = 409;
                            listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('Assets', 'Data Issue'));
                            myExceptionResponse         = new QAC_CreditsResponse.ExceptionResponse('409', 'Multiple Active Assets Found', listFieldErrorResp); 
                            assetResp.exceptionResponse = myExceptionResponse;
                            
                            //response.responseBody     = Blob.valueOf(JSON.serializePretty(myExceptionResponse, true));    
                            }
                    }
                    }
                 }
                else {
                response.statusCode         = 404;
                listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('AccountId','No Account For Agency :'+agencyCode));
                myExceptionResponse         = new QAC_CreditsResponse.ExceptionResponse('404','Agency does not exist in Salesforce', listFieldErrorResp); 
                assetResp.exceptionResponse = myExceptionResponse;
                //response.responseBody     = Blob.valueOf(JSON.serializePretty(myExceptionResponse, true));
                }
               
            }
                              
            /*
             * Preparing Appropriate Response If IATA not found
             */
                
            else{
                response.statusCode         = 400;
                listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('Agency Code', 'Missing'));
                myExceptionResponse         = new QAC_CreditsResponse.ExceptionResponse('400', 'Agency Code Not Provided in Header', listFieldErrorResp); 
                assetResp.exceptionResponse = myExceptionResponse;
                
                //response.responseBody     = Blob.valueOf(JSON.serializePretty(myExceptionResponse, true));
            }
            responseJson += JSON.serializePretty(assetResp,true);
            response.responseBody = Blob.valueOf(responseJson);
            
      }
        
        /*
         * Checking Exceptions
         */
       catch(Exception ex)
        {
            system.debug(' @@ ' + ex.getMessage());
            CreateLogs.insertLogRec('Log Exception Logs Rec Type', 'QAC Agency Credits', 'QAC_Credits',
                                    'doCreditsRetrieval', (responseJson.length() > 32768) ? responseJson.substring(0,32767) : responseJson,
                                    String.valueOf(''), true,'', ex);
            
            String sfErrMessage = ex.getMessage();
            
            response.statusCode = 500;
            listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('Exception',sfErrMessage));
            myExceptionResponse = new QAC_CreditsResponse.ExceptionResponse('500','Found errors.Please contact Salesforce.',listFieldErrorResp);

            assetResp.exceptionResponse = myExceptionResponse;
            responseJson += JSON.serializePretty(assetResp,true);
            response.responseBody = Blob.valueOf(responseJson);
            
        }
    }
        
    public static QAC_CreditsResponse doLedger(Map<Id,Account> accountMap, Map<Id,List<Asset>> assetMap,Map<Id,List<Asset>> inactiveMap,String accId,RestRequest request,RestResponse response)
    {
        QAC_CreditsResponse.QACCreditResponse ledgerResponse;
        List<QAC_CreditsResponse.LedgerResponse> liststatementResp = new List<QAC_CreditsResponse.LedgerResponse>();
        List<QAC_CreditsResponse.FieldErrors> listFieldErrorResp = new List<QAC_CreditsResponse.FieldErrors>();
        QAC_CreditsResponse.ExceptionResponse myExceptionResponse; 
        Date fromDate = request.params.get('fromDate')!=null?Date.parse(request.params.get('fromDate')):system.today().addDays(-90);
        Date toDate   = request.params.get('toDate')!=null?Date.parse(request.params.get('toDate')):System.today();
        map<String,list<Ledger__c>> existingLedgerMap = new map<String,list<Ledger__c>>();
        
        if(fromDate<system.today().addMonths(-15) || toDate<system.today().addMonths(-15)){
            response.statusCode         = 412;
            listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('fromDate/toDate','RequestDates Beyond 15 months'));
            myExceptionResponse         = new QAC_CreditsResponse.ExceptionResponse('412','Please Change the filter', listFieldErrorResp); 
            assetResp.exceptionResponse = myExceptionResponse;  
        }
        else
        {
            for(Ledger__c eachLedger : [Select Id,case__r.CaseNumber,case__r.Sub_Type_1__c,Transaction_Type__c,Transaction_Frequency__c,
                                                Transaction_date__c,Reason__c,Total_Credit_value__c,Account__C
                                                from Ledger__c where Account__C IN: accountMap.keySet() AND
                                                Transaction_date__c>= :fromDate AND Transaction_date__c<=:toDate])
                    {
                        if(eachLedger != null){
                            if(existingLedgerMap.containsKey(eachLedger.Account__c)){
                                existingLedgerMap.get(eachLedger.Account__c).add(eachLedger);
                            }
                            else{
                                existingLedgerMap.put(eachLedger.Account__c, new list<Ledger__c>{eachLedger});
                            }
                        }
                    }
        if(!existingLedgerMap.isEmpty())
        {   
            if(existingLedgerMap.get(accId).size()<500)
            {
                if(!assetmap.isEmpty() && assetmap.get(accId).size()==1 )
                {
                    ledgerResponse = new QAC_CreditsResponse.QACCreditResponse('200',assetMap.get(accId),
                                                                                     existingLedgerMap.get(accId)
                                                                                    );
                    assetResp.QACCreditResponse = ledgerResponse;
                }
                else if(!assetmap.isEmpty() && assetmap.get(accId).size()>1){
                    response.statusCode         = 409;
                    listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('Assets', 'Data Issue'));
                    myExceptionResponse         = new QAC_CreditsResponse.ExceptionResponse('409', 'Multiple Active Assets Found', listFieldErrorResp); 
                    assetResp.exceptionResponse = myExceptionResponse;
                            
                }
                else{
                    for(Ledger__c ledgerObj :existingLedgerMap.get(accId) )
                    {
                    liststatementResp.add(new QAC_CreditsResponse.LedgerResponse(ledgerObj.case__r.CaseNumber,
                                                                            ledgerObj.case__r.Sub_Type_1__c,
                                                                            ledgerObj.Transaction_Type__c,
                                                                            ledgerObj.Transaction_Frequency__c,
                                                                            ledgerObj.Transaction_date__c,
                                                                            ledgerObj.Reason__c,
                                                                            ledgerObj.Total_Credit_value__c));
                    assetResp.Statement = liststatementResp;
                    }
                }
            }                
        
        else{
            response.statusCode         = 412;
            listFieldErrorResp.add(new QAC_CreditsResponse.FieldErrors('LedgerData','Records Limit Exceeded'));
            myExceptionResponse         = new QAC_CreditsResponse.ExceptionResponse('412','Narrow the results by giving filter', listFieldErrorResp); 
            assetResp.exceptionResponse = myExceptionResponse;
                
        }
        }            
      }
        return assetResp;
    }
}