force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Object Label name Change as per Onshore mail.</description>
    <label>Contract &amp; Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract &amp; Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts &amp; Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>To be used under the &quot;Special Conditions&quot; section</description>
    <label>Performance Bonus Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Domestic_Amendment__c.field-meta.xml
<CustomField>
    <fullName>Domestic_Amendment__c</fullName>
    <label>Domestic Amendment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All Discounts</fullName>
            </value>
            <value>
                <fullName>Advance res/Ticketing</fullName>
            </value>
            <value>
                <fullName>Block fares</fullName>
            </value>
            <value>
                <fullName>Domestic discount</fullName>
            </value>
            <value>
                <fullName>Excess Baggage</fullName>
            </value>
            <value>
                <fullName>Fixed Fares</fullName>
            </value>
            <value>
                <fullName>Incentive Fares</fullName>
            </value>
            <value>
                <fullName>No Change to discount</fullName>
            </value>
            <value>
                <fullName>Penalties</fullName>
            </value>
            <value>
                <fullName>Route Deal</fullName>
            </value>
            <value>
                <fullName>JQ Inclusion</fullName>
            </value>
            <value>
                <fullName>Non-Tier to Tier 1</fullName>
            </value>
            <value>
                <fullName>Non-Tier to Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 1 to Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 2 to Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 1 to Non-Tier</fullName>
            </value>
            <value>
                <fullName>Tier 2 to Non-Tier</fullName>
            </value>
            <value>
                <fullName>Regional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/General__c.field-meta.xml
<CustomField>
    <fullName>General__c</fullName>
    <label>General</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Code update</fullName>
            </value>
            <value>
                <fullName>Account Name Change</fullName>
            </value>
            <value>
                <fullName>Deal Extension</fullName>
            </value>
            <value>
                <fullName>Deal Termination</fullName>
            </value>
            <value>
                <fullName>Groups allowed</fullName>
            </value>
            <value>
                <fullName>PCC update</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
            <value>
                <fullName>W Class</fullName>
            </value>
            <value>
                <fullName>New Deal Tier 1</fullName>
            </value>
            <value>
                <fullName>New Deal Tier 2</fullName>
            </value>
            <value>
                <fullName>New Deal Non-Tiered</fullName>
            </value>
            <value>
                <fullName>Change of QCI</fullName>
            </value>
            <value>
                <fullName>Deal Ended</fullName>
                <isActive>false</isActive>
                <label>Deal Ended</label>
            </value>
            <value>
                <fullName>Deal Extended</fullName>
                <isActive>false</isActive>
                <label>Deal Extended</label>
            </value>
            <value>
                <fullName>New Deal</fullName>
                <isActive>false</isActive>
                <label>New Deal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proposal Name</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required - Internal</fullName>
            </value>
            <value>
                <fullName>Signature Required by Customer</fullName>
            </value>
            <value>
                <fullName>Signed by Customer</fullName>
            </value>
            <value>
                <fullName>Rejected - Customer</fullName>
            </value>
            <value>
                <fullName>Rejected – Legal</fullName>
            </value>
            <value>
                <fullName>Approval Required – Legal</fullName>
            </value>
            <value>
                <fullName>Rejected - Internal</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Superceded</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Airfares</fullName>
            </value>
            <value>
                <fullName>Qantas Business Savings</fullName>
                <default>true</default>
                <label>Qantas Business Savings</label>
            </value>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>FIFO Scheduled</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Payments__c/Contract_Payments__c.object-meta.xml
<CustomObject>
    <description>Used to capture the contract payment information against each Payment Type.</description>
    <label>Contract Payments</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contract Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Payments__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Contract Payments</relationshipLabel>
    <relationshipName>Contract_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Payments__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>To hold the Agency and Corporate contract payment type information</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guaranteed Payment</fullName>
            </value>
            <value>
                <fullName>One-Off Payment</fullName>
            </value>
            <value>
                <fullName>Performance Bonus</fullName>
            </value>
            <value>
                <fullName>Sign-On Bonus</fullName>
            </value>
            <value>
                <fullName>Tech fund</fullName>
            </value>
            <value>
                <fullName>Incentive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <summaryForeignKey>Contract__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To be used for Group Sales Opportunity</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Payment Received</fullName>
            </value>
            <value>
                <fullName>Deposit Taken</fullName>
            </value>
            <value>
                <fullName>Full Amount Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <description>Custom object to replace standard Quote object</description>
    <label>Proposal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required - Internal</fullName>
            </value>
            <value>
                <fullName>Acceptance Required - Customer</fullName>
            </value>
            <value>
                <fullName>Accepted by Customer</fullName>
            </value>
            <value>
                <fullName>Rejected - Internal</fullName>
            </value>
            <value>
                <fullName>Rejected - External</fullName>
            </value>
            <value>
                <fullName>Pending ENG Approval</fullName>
            </value>
            <value>
                <fullName>ENG approved</fullName>
            </value>
            <value>
                <fullName>System Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qantas Business Savings</fullName>
            </value>
            <value>
                <fullName>Corporate Airfares</fullName>
            </value>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>FIFO Scheduled</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractPaymentHandlerTest.cls
/**********************************************************************************************************************************

Created Date: 14/02/17

Description: Create and process the invoices based on the Contract Payment functionality. Test method for ContractPaymentHandler.

Versión:
V1.0 - 14/02/17 - Initial version [FO]

**********************************************************************************************************************************/
@isTest
public class ContractPaymentHandlerTest {
    
    @testsetup
    static void createCPTestData() {
        
        // Custom setting creation
        TestUtilityDataClassContractPayment.enableCPTriggers();
        Trigger_Status__c ts = new Trigger_Status__c(Name='ProposalTrigger', Active__c=false);
        insert ts;
    }
    public static testMethod void TestContractPayment() {
        
        List < Account > accList = new List < Account > ();
        List < Opportunity > oppList = new List < Opportunity > ();
        List < Proposal__c > propList = new List < Proposal__c > ();
        List < Contract_Payments__c > cpList = new List < Contract_Payments__c > ();
        List < Contract__c > contList = new List < Contract__c > ();
        // Load Accounts
        accList = TestUtilityDataClassContractPayment.getAccounts();
        System.debug('#####################################################################################');
        // Load Opportunities
        oppList = TestUtilityDataClassContractPayment.getOpportunities(accList);
        System.debug('-----------------------------------------------------------------------------------------');
        // Load Proposals
        propList = TestUtilityDataClassContractPayment.getProposal(oppList);
        System.debug('******************************************************************************************');
        //Load CP
        cpList = TestUtilityDataClassContractPayment.getCP(propList);
        Test.startTest();
        //Update CP
        For(Contract_Payments__c c: cpList) {
            c.Amount__c = 2000;
        }
        
        //Load contract
        contList = TestUtilityDataClassContractPayment.getContract(propList);
        system.debug('accList:'+accList);
        system.debug('oppList:'+oppList);
        system.debug('propList:'+propList);
        system.debug('contList:'+contList);
        system.debug('cpList:'+cpList);
        
        try {
             Database.Update(contList);
			Database.Update(cpList);
			Database.delete(cpList);
           
        } catch (Exception e) {
            
            //System.assert(e.getMessage().contains('Error'), e.getMessage());
            
        }
        Test.stopTest();
    }
    
    public static testMethod void TestContractPaymentSignOn() {
        
        List < Account > accList = new List < Account > ();
        List < Opportunity > oppList = new List < Opportunity > ();
        List < Proposal__c > propList = new List < Proposal__c > ();
        List < Contract_Payments__c > cpList = new List < Contract_Payments__c > ();
        List < Contract_Payments__c > cpListUpd = new List < Contract_Payments__c > ();
        List < Contract__c > contList = new List < Contract__c > ();
        List < Contract__c > contListUp = new List < Contract__c > ();
        // Load Accounts
        accList = TestUtilityDataClassContractPayment.getAccounts();
        
        // Load Opportunities
        oppList = TestUtilityDataClassContractPayment.getOpportunities(accList);
        
        // Load Proposals
        propList = TestUtilityDataClassContractPayment.getProposal(oppList);
        
        //Load CP
        cpList = TestUtilityDataClassContractPayment.getCP(propList);
        Test.startTest();
        //Update CP
        For(Contract_Payments__c c: cpList) {
            c.Type__c = 'Sign-On Bonus';
            cpListUpd.add(c);
        }
        
        //Load contract
        contList = TestUtilityDataClassContractPayment.getContract(propList);
        for (Contract__c cn: contList) {
            cn.Status__c = 'Signed by Customer';
            cn.General__c ='New Deal';
            cn.Domestic_Amendment__c ='Penalties';
            cn.International_Amendment__c='All Discounts';
            cn.Amendments__c='All Discounts';
            //cn.QL_Effective_Tier__c ='Tier 1';
            contListUp.add(cn);
        }
        
        try {
             Database.Update(cpListUpd);
            Database.Update(contListUp);
            
        } catch (Exception e) {
            
            //System.assert(e.getMessage().contains('Error'), e.getMessage());
            
        }
        Test.stopTest();
    }
    
    public static testMethod void TestOneoffPay() {
        
        List < Account > accList = new List < Account > ();
        List < Opportunity > oppList = new List < Opportunity > ();
        List < Proposal__c > propList = new List < Proposal__c > ();
        List < Contract_Payments__c > cpList = new List < Contract_Payments__c > ();
        List < Contract_Payments__c > cpListUpd = new List < Contract_Payments__c > ();
        List < Contract__c > contList = new List < Contract__c > ();
        List < Contract__c > contListUp = new List < Contract__c > ();
        // Load Accounts
        accList = TestUtilityDataClassContractPayment.getAccounts();
        
        // Load Opportunities
        oppList = TestUtilityDataClassContractPayment.getOpportunities(accList);
        
        // Load Proposals
        propList = TestUtilityDataClassContractPayment.getProposal(oppList);
        
        //Load CP
        cpList = TestUtilityDataClassContractPayment.getCP(propList);
        Test.startTest();
        //Update CP
        For(Contract_Payments__c c: cpList) {
            c.Type__c = 'One-Off Payment';
            cpListUpd.add(c);
        }
        
        //Load contract
        contList = TestUtilityDataClassContractPayment.getContract(propList);
        for (Contract__c cn: contList) {
            cn.Status__c = 'Signed by Customer';
            cn.General__c ='New Deal';
            cn.Domestic_Amendment__c ='Penalties';
            cn.International_Amendment__c='All Discounts';
            cn.Amendments__c='All Discounts';
            //  cn.QL_Effective_Tier__c ='Tier 1';
            contListUp.add(cn);
        }
        
        try {
            Database.Update(cpListUpd);
            Database.Update(contListUp);
           
            
        } catch (Exception e) {
            
           // System.assert(e.getMessage().contains('Error'), e.getMessage());
            
        }
        Test.stopTest();
    }
    
    public static testMethod void TestContractTermination() {
        List < Account > accList = new List < Account > ();
        List < Opportunity > oppList = new List < Opportunity > ();
        List < Proposal__c > propList = new List < Proposal__c > ();
        List < Contract_Payments__c > cpList = new List < Contract_Payments__c > ();
        List < Contract_Payments__c > cpListUpd = new List < Contract_Payments__c > ();
        List < Contract__c > contList = new List < Contract__c > ();
        List < Contract__c > contListUp = new List < Contract__c > ();
        // Load Accounts
        accList = TestUtilityDataClassContractPayment.getAccounts();
        
        // Load Opportunities
        oppList = TestUtilityDataClassContractPayment.getOpportunities(accList);
        
        // Load Proposals
        propList = TestUtilityDataClassContractPayment.getProposal(oppList);
        
        //Load CP
        cpList = TestUtilityDataClassContractPayment.getCP(propList);
        Test.startTest();
        
        
        //Load contract
        contList = TestUtilityDataClassContractPayment.getContract(propList);
        for (Contract__c cn: contList) {
            cn.Status__c = 'Signed by Customer';
            cn.Contract_End_Date__c = cn.Contract_End_Date__c.addmonths(1);
            cn.General__c ='New Deal';
            cn.Domestic_Amendment__c ='Penalties';
            cn.International_Amendment__c='All Discounts';
            cn.Amendments__c='All Discounts';
            // cn.QL_Effective_Tier__c ='Tier 1';
            contListUp.add(cn);
        }
        //Update CP
        For(Contract_Payments__c c: cpList) {
            c.Type__c = 'One-Off Payment';
            c.Contract_Agreement__c = contListUp[0].Id;
           
            cpListUpd.add(c);
        }
        try {
            Database.Update(cpListUpd);
             Database.Update(contListUp);
           
        } catch (Exception e) {
            
           // System.assert(e.getMessage().contains('Error'), e.getMessage());
            
        }
        Test.stopTest();
    }
}