force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>IF( ISBLANK( ParentId ) ,  CaseNumber ,  Parent.CaseNumber )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Used to capture the new user&apos;s first name.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s first name, for whom the request is being logged.</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>To capture the new user&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>User&apos;s last name, for whom the request is being logged.</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To store the incoming information from Acquire</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Qantas_API__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>CRM-7281: Stores the Token of the system to be integarted</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Cost_Centre_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Cost_Centre_Account_Number__c</fullName>
    <label>Cost Centre/Account Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airports : Baggage Damaged (100814 : 718011)</fullName>
            </value>
            <value>
                <fullName>Airports : Baggage Lost (100814 : 718006)</fullName>
            </value>
            <value>
                <fullName>Customer Care : Ex Gratia Passenger (309276 : 718017)</fullName>
                <label>Customer Care : Goodwill Passenger (309276 : 718017)</label>
            </value>
            <value>
                <fullName>Customer Care : Ops Expenditure (309276 : 718086)</fullName>
                <label>Customer Care : Delays and Operational (309276 : 718086)</label>
            </value>
            <value>
                <fullName>Customer Care : Events  (309276 : 718009)</fullName>
            </value>
            <value>
                <fullName>Baggage Goodwill : Baggage Emergency Expenses (101366 :  718000)</fullName>
            </value>
            <value>
                <fullName>Baggage Goodwill :  Baggage Pilferage (101366 : 718044)</fullName>
            </value>
            <value>
                <fullName>EU Regulation :  EU Regulation (800301 : 712001)</fullName>
            </value>
            <value>
                <fullName>Canada Regulation : Canada Regulation (100333 : 718100)</fullName>
            </value>
            <value>
                <fullName>Full Cost Centre/ Account Number</fullName>
            </value>
            <value>
                <fullName>Customer Service : Cargo Claims (557175: 715110)</fullName>
            </value>
            <value>
                <fullName>Customer Service : Sent to Wrong Destination / Mishandled (557175: 715105)</fullName>
            </value>
            <value>
                <fullName>Sydney Freight : Cargo Claims (557143 : 715110)</fullName>
            </value>
            <value>
                <fullName>Sydney Freight : Sent to Wrong Destination / Mishandled (557143 : 715105)</fullName>
            </value>
            <value>
                <fullName>Melbourne Freight : Cargo Claims (557151 : 715110)</fullName>
            </value>
            <value>
                <fullName>Melbourne Freight : Sent to Wrong Destination / Mishandled (557151 : 715105)</fullName>
            </value>
            <value>
                <fullName>INT Baggage Solutions : Baggage Recharge (100782 : 718007)</fullName>
            </value>
            <value>
                <fullName>FF Operations : Operations and Service Centre (169789 : 754905)</fullName>
            </value>
            <value>
                <fullName>QANTAS Fin Svcs REVERA (100759 : 390527)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Monetary_Value__c.field-meta.xml
<CustomField>
    <fullName>Monetary_Value__c</fullName>
    <description>QCC: Used to track the monetary value of the payment in any currency</description>
    <inlineHelpText>Credit card - Must be AUD equivalent.
EFT - Must be currency of country of bank</inlineHelpText>
    <label>Monetary Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Refund_Account__c.field-meta.xml
<CustomField>
    <fullName>Refund_Account__c</fullName>
    <description>QCC: Used to store the account the EFT/Credit card refund is coming from for a recovery</description>
    <label>Refund Account</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Centre_Account_Number__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>111017	(DPS Cntrl CCP Chargeback)</fullName>
            </value>
            <value>
                <fullName>151370	(QDT)</fullName>
            </value>
            <value>
                <fullName>320022	(Qlink CX SYD)</fullName>
            </value>
            <value>
                <fullName>351356 (Group Insurance Services)</fullName>
            </value>
            <value>
                <fullName>664100	(Misc Revenue)</fullName>
            </value>
            <value>
                <fullName>706021	(Other Employment Costs-Non FBT)</fullName>
            </value>
            <value>
                <fullName>712001	(EU Regulation)</fullName>
            </value>
            <value>
                <fullName>715105 (Sent to wrong destination / Mishandled)</fullName>
            </value>
            <value>
                <fullName>715110 (Cargo Claims)</fullName>
            </value>
            <value>
                <fullName>718000	(Baggage Emergency Expenses)</fullName>
            </value>
            <value>
                <fullName>718001	(Delay Costs)</fullName>
            </value>
            <value>
                <fullName>718005	(Frontline Recovery)</fullName>
            </value>
            <value>
                <fullName>718006	(Baggage Lost)</fullName>
            </value>
            <value>
                <fullName>718007 (Baggage Recharge)</fullName>
            </value>
            <value>
                <fullName>718009	(Events)</fullName>
            </value>
            <value>
                <fullName>718011	(Baggage Damaged)</fullName>
            </value>
            <value>
                <fullName>718012	(Surprise and Delight)</fullName>
            </value>
            <value>
                <fullName>718015	(Denied Boarding Compensation)</fullName>
            </value>
            <value>
                <fullName>718016	(Denied Pax Meals/Accom)</fullName>
            </value>
            <value>
                <fullName>718017	(Ex Gratia Passenger)</fullName>
            </value>
            <value>
                <fullName>718018	(Travel Certificate)</fullName>
            </value>
            <value>
                <fullName>718019	(Downgrade Compensation)</fullName>
            </value>
            <value>
                <fullName>718020	(EU Compensation)</fullName>
            </value>
            <value>
                <fullName>718038	(Charter/Divert Costs - QF)</fullName>
            </value>
            <value>
                <fullName>718044	(Baggage Pilferage)</fullName>
            </value>
            <value>
                <fullName>718086 (Misc Pax Expenses)</fullName>
            </value>
            <value>
                <fullName>718086	(Ops Expenditure)</fullName>
            </value>
            <value>
                <fullName>718100 (Canada Regulation)</fullName>
            </value>
            <value>
                <fullName>754315	(Short Collection)</fullName>
            </value>
            <value>
                <fullName>754905 (FF Operations)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>QCC: The status of the recovery</description>
    <label>Recovery Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
            <value>
                <fullName>Further Action Required</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Replaced Recovery</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submit for Finalisation</fullName>
            </value>
            <value>
                <fullName>Finalisation Declined</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Voucher_Number__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Voucher Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Voucher_Validity_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Validity_in_Months__c</fullName>
    <label>Voucher Validity (in months)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recovery__c/recordTypes/Travel_Voucher_Recovery.recordType-meta.xml
<RecordType>
    <fullName>Travel_Voucher_Recovery</fullName>
    <active>true</active>
    <label>Travel Voucher Recovery</label>
</RecordType>

force-app/main/default/classes/QCC_TravelVoucherCallTest.cls
/*----------------------------------------------------------------------------------------------------------------------
Modified By : Venkata Suresh Kumar (TCS Team), 19-Mar-2026
Desc : Remediated test class failures. Updated testSetUPMethod() method.  
-----------------------------------------------------------------------------------------------------------------------*/
@isTest
public class QCC_TravelVoucherCallTest {
    @testSetup
    static void setup() {
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
        list<Trigger_Status__c> ts = new list<Trigger_Status__c>();
        ts.add(new Trigger_Status__c(name='RecoveryTriggerSubmitForFinalisation',Active__c =false));
        ts.add(new Trigger_Status__c(name='CaseTriggerV2',Active__c =false));
        ts.add(new Trigger_Status__c(name='RecoveryTriggerUpdateCaseRecoveryValue',Active__c =false));
        ts.add(new Trigger_Status__c(name='isNotFrequentFlyerMember',Active__c =false));
        ts.add(new Trigger_Status__c(name='isFrequentFlyerMember',Active__c =false));
        ts.add(new Trigger_Status__c(name='getSuggestedRange',Active__c =false));
        ts.add(new Trigger_Status__c(name='updateRecoveryType',Active__c =false));
        ts.add(new Trigger_Status__c(name='setFulfilledBy',Active__c =false));
        ts.add(new Trigger_Status__c(name='handleRecoveryTrigger',Active__c =false));
        ts.add(new Trigger_Status__c(name='RecoveryInvokeLoyaltyPostService',Active__c =false));
        ts.add(new Trigger_Status__c(name='RecoveryTriggerUpdateCaseRecoveryEvent',Active__c =false));
        ts.add(new Trigger_Status__c(name='RecoveryTriggerPostToChatter',Active__c =false));
        ts.add(new Trigger_Status__c(name='routeCaseOnRecoveryPaymentUpdate',Active__c =false));
        insert ts;
        
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        Contact con = new contact (accountid = acc.id, FirstName = 'Test1234',LastName='Test2345',email='test@mail.com');
        insert con;
        Id recoveryCaseRTId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CCC_On_The_Spot_Recovery').getRecordTypeId();
        insert new Qantas_API__c( Name = 'TV_Encryption_Key', Token__c =     EncodingUtil.base64Encode(Crypto.generateAesKey(256))  );
        // Create test Cases
        List<Case> cases = new List<Case>{
            new Case(Status = 'New', Origin = 'Phone',recordtypeid = recoveryCaseRTId,type='',First_Name__c ='Test First 1',Last_Name__c ='Test Last 1'),
                new Case(Status = 'Closed', Origin = 'Email',recordtypeid = recoveryCaseRTId,type='',First_Name__c ='Test First 2',Last_Name__c ='Test Last 2'),
                new Case(Status = 'New', Origin = 'Email',recordtypeid = recoveryCaseRTId,type='',First_Name__c ='Test First 3',Last_Name__c ='Test Last 3')
                };
                    insert cases;
        
        // Create test Recoveries related to the first Case
        Id recoveryRTId = SObjectType.Recovery__c.getRecordTypeInfosByDeveloperName().get('Travel_Voucher_Recovery').getRecordTypeId();
        List<Recovery__c> recoveries = new List<Recovery__c>
        {
            new Recovery__c(Case_Number__c = cases[0].Id, recordtypeid = recoveryRTId,Monetary_Value__c = 100 ,Voucher_Validity_in_Months__c = '6', Status__c = 'New',Cost_Centre_Account_Number__c ='Customer Care : Ex Gratia Passenger (309276 : 718017)', Voucher_Number__c = '10986747', Refund_Account__c='718017	(Ex Gratia Passenger)',Refund_Cost_Centre__c = '309276	(Customer Care)'),
                new Recovery__c(Case_Number__c = cases[1].Id,recordtypeid = recoveryRTId,Monetary_Value__c = 100 ,Voucher_Validity_in_Months__c = '6', Status__c = 'New',Cost_Centre_Account_Number__c ='Customer Care : Ex Gratia Passenger (309276 : 718017)', Voucher_Number__c = '10986748', Refund_Account__c='718017	(Ex Gratia Passenger)',Refund_Cost_Centre__c = '309276	(Customer Care)'),
                new Recovery__c(Case_Number__c = cases[2].Id,recordtypeid = recoveryRTId,Monetary_Value__c = 100 ,Voucher_Validity_in_Months__c = '6', Status__c = 'New',Cost_Centre_Account_Number__c ='Customer Care : Ex Gratia Passenger (309276 : 718017)',Voucher_Number__c = '10986749', Refund_Account__c='718017	(Ex Gratia Passenger)',Refund_Cost_Centre__c = '309276	(Customer Care)')
                };
                    RecoveryTriggerHelper.hasrun = true;
        insert recoveries;
    }
    
    @isTest
    static void testExecute1() {
        
        list<id> recordIds = new list<id>();
        for(Recovery__c rec : [select id from Recovery__c]){
            recordIds.add(rec.id);
        }
        
        // Mock the HTTP callout
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(0));
        
        QCC_TravelVoucherCall tvc = new QCC_TravelVoucherCall(recordIds);
        System.enqueueJob(tvc);
        
        Test.stopTest();
    }
    
    @isTest
    static void testExecute2() {
        
        list<id> recordIds = new list<id>();
        for(Recovery__c rec : [select id from Recovery__c]){
            recordIds.add(rec.id);
        }
        
        // Mock the HTTP callout
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(1));
        
        QCC_TravelVoucherCall tvc = new QCC_TravelVoucherCall(recordIds);
        System.enqueueJob(tvc);
        
        Test.stopTest();
    }
    
    @isTest
    static void testExecute3() {
        
        list<id> recordIds = new list<id>();
        for(Recovery__c rec : [select id from Recovery__c]){
            recordIds.add(rec.id);
        }
        
        // Mock the HTTP callout
        Test.startTest();
        
        QCC_TravelVoucherCall tvc = new QCC_TravelVoucherCall(recordIds);
        System.enqueueJob(tvc);
        
        Test.stopTest();
    }
    
    @isTest
    static void testExecute4() {
        
        list<id> recordIds = new list<id>();
        for(Recovery__c rec : [select id from Recovery__c]){
            recordIds.add(rec.id);
        }
        
        // Mock the HTTP callout
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(2));
        
        QCC_TravelVoucherCall tvc = new QCC_TravelVoucherCall(recordIds);
        System.enqueueJob(tvc);
        
        Test.stopTest();
    }

    @isTest
    static void testExecute5() {
        
        List<Id> recordIds = new List<id>();
        List<Recovery__c> recoveries = New List<Recovery__c>([SELECT Id, Name,  Contact_First_Name__c,Contact_LastName__c, Case_Number__c, recordtypeid, Monetary_Value__c, Voucher_Validity_in_Months__c, 
                                                              Status__c, Cost_Centre_Account_Number__c, Refund_Account__c, Refund_Cost_Centre__c, Refund_Cost_Centre_Number__c, Refund_Account_Number__c,
                                                              Voucher_Number__c
                                                              FROM Recovery__c]);
        
        for(Recovery__c rec: recoveries){
            recordIds.add(rec.Id);
        }
        
        // Mock the HTTP callout
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(2));
        QCC_TravelVoucherCallHelper.createRecoveryJson(recordIds, Date.today());        
        QCC_TravelVoucherCallHelper.checkTravelVoucherNumber(recoveries, new Map<Id, Recovery__c>(recoveries));
        QCC_TravelVoucherCallHelper.updateRecoveries(recordIds,  QCC_TravelVoucherCallHelper.createRecoveryJson(recordIds, Date.today()), false, '');
        QCC_TravelVoucherCallHelper.SubmitStatusDetail objSatus = new QCC_TravelVoucherCallHelper.SubmitStatusDetail();
        objSatus.referenceNumber = 'Test'; objSatus.campaign_reference = 'Test'; objSatus.status = 'Test' ; objSatus.message = 'None'; objSatus.errorCode = 'None';        
        QCC_TravelVoucherCallHelper.BatchStatus objBatchSta = new QCC_TravelVoucherCallHelper.BatchStatus ();
        objBatchSta.batch_timestamp = 'Batch Stamp'; objBatchSta.code = '20'; objBatchSta.message = 'No Message'; objBatchSta.description = 'Batch Description';         
        QCC_TravelVoucherCallHelper.createNoteForRecord(recoveries[0].Id, 'Title', 'noteBody');  
        Test.stopTest();
    } 
    
    // Mock HTTP Response Generator
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public MockHttpResponseGenerator(integer c){
            this.count =c;
        }
        public integer count;
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            if(this.count ==0){
                res.setBody('{"batch_reference": "12345", "batch_timestamp": "2024-01-01", "code": null, "message": "Success", "submit_status_details": [ {"referenceNumber": "20","campaign_reference": "233455","status": "SUCCESS","message": "OK"}]}');
                res.setStatusCode(200);
            }
            if(this.count == 1){
                res.setBody('{"batch_reference": "12345", "batch_timestamp": "2024-01-01", "code": null, "message": "Success", "submit_status_details": [ {"referenceNumber": "20","campaign_reference": "233455","status": "SUCCESS","message": "OK"}]}');
                res.setStatusCode(404);
            }
            if(this.count == 2){
                res.setBody('{"code": "900901","message": "Invalid Credentials","description": "Invalid Credentials. Make sure you have provided the correct security credentials" , "submit_status_details": [ {"referenceNumber": "20","campaign_reference": "233455","status": "FAIL","message": "Failed"}]}');
                res.setStatusCode(200);
            }
            return res;
        }
    }
}