force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>QF-{0000000}</displayFormat>
        <label>Flight ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Cabin_Class__c.field-meta.xml
<CustomField>
    <fullName>Cabin_Class__c</fullName>
    <label>Cabin Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PNR__c/PNR__c.object-meta.xml
<CustomObject>
    <label>PNR</label>
    <nameField>
        <label>PNR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PNRs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/Recovery__c.object-meta.xml
<CustomObject>
    <description>Container for recoveries offered to the customer</description>
    <label>Recovery</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Recovery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recoveries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recovery__c/fields/Booking_currency__c.field-meta.xml
<CustomField>
    <fullName>Booking_currency__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Booking currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Booking_email__c.field-meta.xml
<CustomField>
    <fullName>Booking_email__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Booking email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Booking_phone_number__c.field-meta.xml
<CustomField>
    <fullName>Booking_phone_number__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Booking phone number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Cabin_class__c.field-meta.xml
<CustomField>
    <fullName>Cabin_class__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Cabin class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Created to show/store Case number the recovery is associated to</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recoveries</relationshipLabel>
    <relationshipName>Recoveries_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/CorrelationID__c.field-meta.xml
<CustomField>
    <fullName>CorrelationID__c</fullName>
    <description>Correlation_ID unique to the passenger</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Correlation ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Departing_port__c.field-meta.xml
<CustomField>
    <fullName>Departing_port__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Departing port</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Disruption__c.field-meta.xml
<CustomField>
    <fullName>Disruption__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Disruption</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Disruption_duration__c.field-meta.xml
<CustomField>
    <fullName>Disruption_duration__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <label>Disruption duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Disruption_reason__c.field-meta.xml
<CustomField>
    <fullName>Disruption_reason__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Disruption reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/FF_ID__c.field-meta.xml
<CustomField>
    <fullName>FF_ID__c</fullName>
    <description>Used in exgratia flight pass recovery process</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FF ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/FF_Tier__c.field-meta.xml
<CustomField>
    <fullName>FF_Tier__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FF Tier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Flight_date__c.field-meta.xml
<CustomField>
    <fullName>Flight_date__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Flight_elibility__c.field-meta.xml
<CustomField>
    <fullName>Flight_elibility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <label>Flight elibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Flight_elibility_reason__c.field-meta.xml
<CustomField>
    <fullName>Flight_elibility_reason__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight elibility reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Flight_IDR__c.field-meta.xml
<CustomField>
    <fullName>Flight_IDR__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight IDR</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Issuance_email__c.field-meta.xml
<CustomField>
    <fullName>Issuance_email__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Issuance email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Issuance_email_address_validation__c.field-meta.xml
<CustomField>
    <fullName>Issuance_email_address_validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <label>Issuance email address validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Issuance_email_address_validation_failur__c.field-meta.xml
<CustomField>
    <fullName>Issuance_email_address_validation_failur__c</fullName>
    <description>Issuance email address validation failure reason.
Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Issuance email address validation failur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Issuance_phone_number__c.field-meta.xml
<CustomField>
    <fullName>Issuance_phone_number__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Issuance phone number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Issuance_phone_number_validation__c.field-meta.xml
<CustomField>
    <fullName>Issuance_phone_number_validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <label>Issuance phone number validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/ODP__c.field-meta.xml
<CustomField>
    <fullName>ODP__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ODP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Pax_first_name__c.field-meta.xml
<CustomField>
    <fullName>Pax_first_name__c</fullName>
    <description>Used in exgratia flight pass recovery process.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Pax first name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Pax_last_name__c.field-meta.xml
<CustomField>
    <fullName>Pax_last_name__c</fullName>
    <description>Used in exgratia flight pass recovery process.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Pax last name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Payment_eligibility__c.field-meta.xml
<CustomField>
    <fullName>Payment_eligibility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <label>Payment eligibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Payment_eligibility_reason__c.field-meta.xml
<CustomField>
    <fullName>Payment_eligibility_reason__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment eligibility reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <description>Used in exgratia flight pass recovery process.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PNR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/PNR_remarks_updated_with_card_issuance__c.field-meta.xml
<CustomField>
    <fullName>PNR_remarks_updated_with_card_issuance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <label>PNR remarks updated with card issuance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/PNR_remarks_updated_with_eligibility__c.field-meta.xml
<CustomField>
    <fullName>PNR_remarks_updated_with_eligibility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <label>PNR remarks updated with eligibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/POS_location__c.field-meta.xml
<CustomField>
    <fullName>POS_location__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>POS location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/fields/Seat_number__c.field-meta.xml
<CustomField>
    <fullName>Seat_number__c</fullName>
    <description>Field used in Ex-gratia Flight Pass Voucher program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Seat number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery__c/recordTypes/Exgratia_Flight_Pass.recordType-meta.xml
<RecordType>
    <fullName>Exgratia_Flight_Pass</fullName>
    <active>true</active>
    <description>This record type is used in Exgratia Flight Pass business process.</description>
    <label>Exgratia Flight Pass</label>
</RecordType>

force-app/main/default/classes/ExgratiaRecoveryCreator.cls
/**
 * @author: dattaraj.deshmukh@qantas.com.au
 * @date: 2/11/2023
 * @desc: Class to create recovery records for Exgratia component. 
 * @history
 * 			2/11/2023	-	created 
 */
public without sharing class ExgratiaRecoveryCreator {
	public static final Id RECOVERY_RECORDTYPE_ID = Schema.SObjectType.Recovery__c.getRecordTypeInfosByDeveloperName().get('Exgratia_Flight_Pass').getRecordTypeId();
	
	@AuraEnabled
    public static string createRecoveryRecord(String wrapperObjectString, String caseId){
        try {
			Boolean isDuplicate = false;
			system.debug('wrapperObjectString'+wrapperObjectString);
			system.debug('caseId'+caseId);
            ExgratiaFlightPassSearchWrapper wrapperObj = ExgratiaFlightPassSearchWrapper.parseSingleRecord(wrapperObjectString);
			system.debug('wrapperObj'+wrapperObj);
			isDuplicate = isDuplicateRecovery(wrapperObj, caseId);
			system.debug('isDuplicate =='+isDuplicate);
			if(! isDuplicate) {
				createRecovery(wrapperObj, caseId);
			}
            
            return ( isDuplicate == false ? 'Recovery record created successfully!' : 'create recovery record was not created!');
        } catch (Exception e) {
			system.debug(e);
			system.debug(e.getStackTraceString()); 
            throw new AuraHandledException(e.getMessage());
        }
    }

	@testVisible
	private static boolean isDuplicateRecovery(ExgratiaFlightPassSearchWrapper wrapperObj, Id caseId) {

		List<Recovery__c> recoveryRecords = [Select Id, Pax_first_name__c, Pax_last_name__c, FF_ID__c, CorrelationID__c, Case_Number__c
												from Recovery__c
												 Where Case_Number__c =: caseId AND recordTypeId =: RECOVERY_RECORDTYPE_ID];
		Boolean isDuplicate = false;
		if(recoveryRecords != null && !recoveryRecords.isEmpty()) {
			
			for(Recovery__c rec : recoveryRecords) {

				if(String.isNotBlank(rec.Pax_first_name__c) && rec.Pax_first_name__c.equalsIgnoreCase(wrapperObj.Pax_first_name) 
					&& String.isNotBlank(rec.Pax_last_name__c) && rec.Pax_last_name__c.equalsIgnoreCase(wrapperObj.Pax_last_name) && rec.CorrelationID__c.equalsIgnoreCase(wrapperObj.Correlation_ID)) {
						system.debug('rec ='+rec);
						isDuplicate = true;
						break;
				}
			}
		}
		
		return isDuplicate;
		

	}
	@testVisible
	private static void createRecovery(ExgratiaFlightPassSearchWrapper wrapperObj, String caseId) {
		system.debug('wrapperObj'+wrapperObj);
		Recovery__c recovery = new Recovery__c();
		
		recovery.Pax_first_name__c = wrapperObj.Pax_first_name;
		recovery.Pax_last_name__c = wrapperObj.Pax_last_name;
		recovery.PNR__c = wrapperObj.PNR;
		
		recovery.FF_Tier__c = wrapperObj.FF_Tier;
		recovery.Cabin_Class__c = wrapperObj.Cabin_class;
		recovery.Seat_number__c = wrapperObj.Seat_number;
		recovery.Booking_email__c = wrapperObj.Booking_email;
		recovery.Booking_phone_number__c = wrapperObj.Booking_phone_number;
		recovery.Booking_currency__c = wrapperObj.Booking_currency;
		recovery.POS_location__c = wrapperObj.POS_location;
		recovery.Payment_eligibility__c = wrapperObj.Payment_eligibility == 'T' ? true : false;
		recovery.Payment_eligibility_reason__c = wrapperObj.Payment_eligibility_reason ;
		recovery.PNR_remarks_updated_with_eligibility__c = wrapperObj.PNR_remarks_updated_with_eligibility == 'T' ? true : false;
		recovery.PNR_remarks_updated_with_card_issuance__c = wrapperObj.PNR_remarks_updated_with_card_issuance == 'T' ? true : false;
		recovery.Flight__c = wrapperObj.Flight;
		recovery.Flight_date__c = wrapperObj.Flight_date;
		recovery.Flight_IDR__c = wrapperObj.Flight_IDR;
		recovery.Departing_port__c = wrapperObj.Departing_port;
		recovery.ODP__c = wrapperObj.ODP;
		recovery.Disruption__c = wrapperObj.Disruption;
		recovery.Disruption_reason__c = wrapperObj.Disruption_reason;
		recovery.Disruption_duration__c = wrapperObj.Disruption_duration;
		recovery.Flight_elibility__c = wrapperObj.Flight_eligibility  == 'T' ? true : false;
		recovery.Flight_elibility_reason__c = wrapperObj.Flight_eligibility_reason;
		recovery.Issuance_email_address_validation__c	= wrapperObj.Issuance_email_address_validation  == 'T' ? true : false;
		recovery.Issuance_email_address_validation_failur__c = wrapperObj.Issuance_email_address_validation_failure_reason;
		recovery.Issuance_email__c = wrapperObj.Issuance_email;
		recovery.Issuance_phone_number__c = wrapperObj.Issuance_phone_number;
		recovery.Issuance_phone_number_validation__c = wrapperObj.Issuance_phone_number_validation  == 'T' ? true : false;
		recovery.Issuance_phone_number_validation_failure__c = wrapperObj.Issuance_phone_number_validation_failure_reason;
		recovery.Bespoke_exgratia_payment__c = wrapperObj.Bespoke_exgratia_payment == 'T' ? true : false;
		recovery.Issuance_status__c = wrapperObj.Issuance_status;
		recovery.Issuance_failure_reason__c = wrapperObj.Issuance_failure_reason;
		recovery.Issuance_currency__c = wrapperObj.Issuance_currency;
		recovery.Issuance_currency_validation__c = wrapperObj.Issuance_currency_validation == 'T' ? true : false;
		recovery.Issuance_currency_validation_failure_rea__c = wrapperObj.Issuance_currency_validation_failure_reason;
		recovery.SMS_type_sent__c = wrapperObj.SMS_type_sent;
		recovery.SMS_status_code__c = wrapperObj.SMS_status_code;
		recovery.Sequence_No__c = wrapperObj.Sequance_No;
		recovery.Case_Number__c = caseId;
		recovery.RecordTypeId = RECOVERY_RECORDTYPE_ID;
		recovery.CorrelationID__c = wrapperObj.Correlation_ID;
		system.debug('recovery'+recovery);
		insert recovery;
		system.debug('recovery ='+recovery);
		system.debug('recovery Id ='+recovery.id);
		
	}

	
}