force-app/main/default/objects/Account_Classification_Type__c/Account_Classification_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the Classification values of Account Classification object.</description>
    <label>Account Classification Type</label>
</CustomObject>

force-app/main/default/objects/Account_Classification_Type__c/fields/Classification_Type__c.field-meta.xml
<CustomField>
    <fullName>Classification_Type__c</fullName>
    <description>Holds Classification Type</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Classification Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Classifications__c/Account_Classifications__c.object-meta.xml
<CustomObject>
    <description>To capture the Account Travel Policy and Preferred Carrier Information</description>
    <label>Account Classifications</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Account Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Classifications__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Classifications</relationshipLabel>
    <relationshipName>Account_Classifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Classifications__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preferred Carrier</fullName>
            </value>
            <value>
                <fullName>Travel Policy</fullName>
            </value>
            <value>
                <fullName>OBT</fullName>
            </value>
            <value>
                <fullName>Multi POS</fullName>
            </value>
            <value>
                <fullName>Strategic Priority</fullName>
            </value>
            <value>
                <fullName>Loyalty Partner Update</fullName>
            </value>
            <value>
                <fullName>Agency Tier</fullName>
            </value>
            <value>
                <fullName>Account Onboarding</fullName>
            </value>
            <value>
                <fullName>Procurement Tier</fullName>
            </value>
            <value>
                <fullName>QBR Segmentation</fullName>
            </value>
            <value>
                <fullName>Joint Customer</fullName>
            </value>
            <value>
                <fullName>SME TIER</fullName>
                <label>SME Tier</label>
            </value>
            <value>
                <fullName>Top QBR Customer&gt;$200K</fullName>
            </value>
            <value>
                <fullName>QBR QF Share</fullName>
            </value>
            <value>
                <fullName>Company Policy</fullName>
            </value>
            <value>
                <fullName>Cost</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Revenue Integrity</fullName>
            </value>
            <value>
                <fullName>Multiple Breaches</fullName>
            </value>
            <value>
                <fullName>Commercial Deal or Buying Group</fullName>
            </value>
            <value>
                <fullName>IATA or TIDS</fullName>
            </value>
            <value>
                <fullName>Compliance to policy</fullName>
            </value>
            <value>
                <fullName>Revenue Threshold</fullName>
            </value>
            <value>
                <fullName>Previous EOI rejected</fullName>
            </value>
            <value>
                <fullName>Look to book</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Account_ClassificationValidationHelper.cls
/**********************************************************************************************************************************

Created Date    : 27/07/17 (DD/MM/YYYY)
Added By        : Karpagam Swaminathan
Description     : To validate only one account  classification added  to account
JIRA            : CRM-2653
Version         : V1.0 - 27/07/17 - Initial version



**********************************************************************************************************************************/




public class Account_ClassificationValidationHelper
{
    public static void accClassPCValidation(List<Account_Classifications__c> accList){
        String ExpRecId;
        
        try{
            List<String> accclasType = new List<String>();
            Set<Id> setAccountIds = new Set<Id>();
            Set<Id> setAccountIds1 = new Set<Id>();
            system.debug('accList*************'+accList);
            for(Account_Classifications__c objAcc : accList ) {
                setAccountIds1 . add(objAcc.Account__c);
                system.debug('objAcc $$$$$$$$$$$$$'+objAcc);
                Account_Classification_Type__c act = Account_Classification_Type__c.getValues(objAcc.Classification__c);
                String accType= String.valueof(act.Classification_Type__c);
                accclasType.add(accType);
                System.debug('accType%%%%%%%%%%%%'+accType);
                if(objAcc.Classification__c == accType)
                {
                    setAccountIds.add(objAcc.Account__c); 
                    system.debug('inside if');
                }
            }
            
            //Populate a map of the query results
            Map<Id, Account_Classifications__c  > mapAccclassification = new Map<Id, Account_Classifications__c >();
            for(Account_Classifications__c objAcc : [SELECT Id, Name,Classification__c,Account__c
                                                     FROM Account_Classifications__c 
                                                     WHERE Account__c IN :setAccountIds1 and Classification__c IN:accclasType
                                                    ]) {
                                                        mapAccclassification.put(objAcc.Account__c, objAcc);
                                                        System.debug('mapAccclassification%%%%%%%%%%%%'+mapAccclassification);
                                                    }
            
            //Iterate through your list of Account classifications records and generate an error for any 
            //that have a matching Classification in the map
            for(Account_Classifications__c objAcc : accList) {
                if(mapAccclassification.containsKey(objAcc.Account__c)) {
                    Account_Classifications__c objExistingAcc = mapAccclassification.get(objAcc.Account__c);
                    System.debug('Found another copy ' + objExistingAcc.Id + '  name is ' + objExistingAcc.Name);
                    ExpRecId=objExistingAcc.Id;
                    objAcc.addError(Label.Account_Classification_Validation_Error);
                }
            }
        }
        
        Catch(Exception e){
        //insert Log record to capture the exception occured
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Account_ClassificationValidation', 'Account_ClassificationValidationHelper', 
                                    'Account_ClassificationValidationHelper',String.valueOf(''), String.valueOf(''),false, ExpRecId, e);
        }
    }
    
}