force-app/main/default/objects/Airport_Code__c/Airport_Code__c.object-meta.xml
<CustomObject>
    <description>To capture the Airport Code</description>
    <label>Airport Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Airport Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport_Code__c/fields/Freight_Airport_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Freight_Airport_State_Code__c</fullName>
    <description>Freight - records the state code of the Port</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Airport State Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Assign_using_active_assignment_rules__c.field-meta.xml
<CustomField>
    <fullName>Assign_using_active_assignment_rules__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether to assign cases using active assignment rules</description>
    <inlineHelpText>CCC: Tick this box to use queue allocation</inlineHelpText>
    <label>Assign using active assignment rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>QCC: Created to show/store Issue Category.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Accommodation/Reimbursement of Expenses</fullName>
            </value>
            <value>
                <fullName>Account Queries</fullName>
            </value>
            <value>
                <fullName>Advertising</fullName>
            </value>
            <value>
                <fullName>Aircraft Condition</fullName>
            </value>
            <value>
                <fullName>Aircraft Schedule Change/Notification</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Airport Security</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Announcements</fullName>
            </value>
            <value>
                <fullName>AQIRE</fullName>
            </value>
            <value>
                <fullName>ARD Web</fullName>
            </value>
            <value>
                <fullName>Audits</fullName>
            </value>
            <value>
                <fullName>Award Bookings</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>BART Document</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Blue Prism</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Bounce Back</fullName>
            </value>
            <value>
                <fullName>Cabin Baggage</fullName>
            </value>
            <value>
                <fullName>Call outs</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cancellation Fees</fullName>
            </value>
            <value>
                <fullName>Carbon Offset</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Charter Flights</fullName>
            </value>
            <value>
                <fullName>Chauffeur Drive</fullName>
            </value>
            <value>
                <fullName>In-Flight Entertainment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Catering not assured</fullName>
            </value>
            <value>
                <fullName>Nil catering, ran out of meals</fullName>
            </value>
            <value>
                <fullName>Nil catering whole aircraft</fullName>
            </value>
            <value>
                <fullName>Mention of illness/food poisoning</fullName>
            </value>
            <value>
                <fullName>Did not receive first choice</fullName>
            </value>
            <value>
                <fullName>Presentation/quality of selection</fullName>
            </value>
            <value>
                <fullName>Presentation Quality</fullName>
            </value>
            <value>
                <fullName>Not provided</fullName>
            </value>
            <value>
                <fullName>App/nil in seat IFE</fullName>
            </value>
            <value>
                <fullName>Not functioning</fullName>
            </value>
            <value>
                <fullName>Content variety</fullName>
            </value>
            <value>
                <fullName>Inappropriate content</fullName>
            </value>
            <value>
                <fullName>Legroom/Seat width</fullName>
            </value>
            <value>
                <fullName>Customers of size</fullName>
            </value>
            <value>
                <fullName>Burn in lounge</fullName>
            </value>
            <value>
                <fullName>Customer Concerns – Lounge</fullName>
            </value>
            <value>
                <fullName>Cuts/Abrasions</fullName>
            </value>
            <value>
                <fullName>Fall on escalator/stairs</fullName>
            </value>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Slip/Fall in lounge</fullName>
            </value>
            <value>
                <fullName>Violence in lounge</fullName>
            </value>
            <value>
                <fullName>Other lounge Safety issue</fullName>
            </value>
            <value>
                <fullName>Burn in terminal</fullName>
            </value>
            <value>
                <fullName>Customer concerns – terminal</fullName>
            </value>
            <value>
                <fullName>Customer transport vehicle</fullName>
            </value>
            <value>
                <fullName>Fall on escalator/stairs/travelator</fullName>
            </value>
            <value>
                <fullName>Slip/trip/fall in terminal</fullName>
            </value>
            <value>
                <fullName>Wheelchair in terminal</fullName>
            </value>
            <value>
                <fullName>Other airport safety issue</fullName>
            </value>
            <value>
                <fullName>Broken tooth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>QCC: Created to show/store Case Group.</description>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Flight Disruptions</fullName>
            </value>
            <value>
                <fullName>Contact Centre</fullName>
            </value>
            <value>
                <fullName>Departure Airport</fullName>
            </value>
            <value>
                <fullName>Lounges</fullName>
            </value>
            <value>
                <fullName>Arrival Airport</fullName>
            </value>
            <value>
                <fullName>In-Flight</fullName>
            </value>
            <value>
                <fullName>Frequent Flyer</fullName>
            </value>
            <value>
                <fullName>Qantas.com</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Insurance letter</fullName>
            </value>
            <value>
                <fullName>Request Copy of Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Damaged Baggage</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Delayed Flight</fullName>
            </value>
            <value>
                <fullName>Delayed or Lost Baggage</fullName>
            </value>
            <value>
                <fullName>Flight Cancelled by Qantas</fullName>
            </value>
            <value>
                <fullName>Personal Property Lost In-flight</fullName>
            </value>
            <value>
                <fullName>Proof of Boarding or No Show</fullName>
            </value>
            <value>
                <fullName>Baggage Delivery Delayed Baggage</fullName>
            </value>
            <value>
                <fullName>Mid Range Repair</fullName>
            </value>
            <value>
                <fullName>Post Flight Survey</fullName>
            </value>
            <value>
                <fullName>Denial</fullName>
            </value>
            <value>
                <fullName>General Wear and Tear or removal of locks email template</fullName>
            </value>
            <value>
                <fullName>Mid Range Letter</fullName>
            </value>
            <value>
                <fullName>Finalisation</fullName>
            </value>
            <value>
                <fullName>Delayed Baggage</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Specific Needs</fullName>
            </value>
            <value>
                <fullName>EMD Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <description>QCC: Built to show/store Sub Category.</description>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Beverage Payment</fullName>
            </value>
            <value>
                <fullName>Beverage Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Catering Quality/Selection</fullName>
            </value>
            <value>
                <fullName>Menu Select Meal not Provided</fullName>
            </value>
            <value>
                <fullName>Special Meal Quality/Provision</fullName>
            </value>
            <value>
                <fullName>Q Streaming</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Functionality</fullName>
            </value>
            <value>
                <fullName>Bassinet Availability</fullName>
            </value>
            <value>
                <fullName>Comfort/Functionality</fullName>
            </value>
            <value>
                <fullName>Seating Allocation</fullName>
            </value>
            <value>
                <fullName>Prepaid seat not provided</fullName>
            </value>
            <value>
                <fullName>Fees/Cost/Price</fullName>
            </value>
            <value>
                <fullName>In-Flight Seating</fullName>
            </value>
            <value>
                <fullName>Staff Assistance</fullName>
            </value>
            <value>
                <fullName>Poor Communication</fullName>
            </value>
            <value>
                <fullName>Agent booking</fullName>
            </value>
            <value>
                <fullName>Aircraft cleanliness</fullName>
            </value>
            <value>
                <fullName>Aircraft Type</fullName>
            </value>
            <value>
                <fullName>Airport co-ordination</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Applied correctly</fullName>
            </value>
            <value>
                <fullName>Applied incorrectly</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Bid Now Product</fullName>
            </value>
            <value>
                <fullName>Boarding Process</fullName>
            </value>
            <value>
                <fullName>Booking Errors</fullName>
            </value>
            <value>
                <fullName>Cabin baggage policy</fullName>
            </value>
            <value>
                <fullName>Car did not arrive</fullName>
            </value>
            <value>
                <fullName>Catering Quality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active (Do Not Use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/TECH_FromChatter__c.field-meta.xml
<CustomField>
    <fullName>TECH_FromChatter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Backend flag to identify that the email is sent from Chatter to not auto close the Case</description>
    <label>TECH From Chatter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseAndEmailMessageTriggerV1Test.cls
@isTest
public class CaseAndEmailMessageTriggerV1Test {

    private static final Id RTID_CASE_QFREIGHT = Schema.SobjectType.Case.getRecordTypeInfosByDeveloperName().get('Qantas_Freight').getRecordTypeId();

    @testSetup
    static void createData() {
        
        List<Trigger_Status__c> lsttrgStatus = new List<Trigger_Status__c>();
        Trigger_Status__c CaseTriggerV1 = new Trigger_Status__c();
        CaseTriggerV1.Name = 'CaseTriggerV1';
        CaseTriggerV1.Active__c = true;
        lsttrgStatus.add(CaseTriggerV1);

        
        Trigger_Status__c CaseTriggerupdateContactBlankEmail = new Trigger_Status__c();
        CaseTriggerupdateContactBlankEmail.Name = 'CaseTriggerupdateContactBlankEmail';
        CaseTriggerupdateContactBlankEmail.Active__c = true;
        lsttrgStatus.add(CaseTriggerupdateContactBlankEmail);

        
        Trigger_Status__c CaseTriggerDeleteAffectedPassengers = new Trigger_Status__c();
        CaseTriggerDeleteAffectedPassengers.Name = 'CaseTriggerDeleteAffectedPassengers';
        CaseTriggerDeleteAffectedPassengers.Active__c = true;
        lsttrgStatus.add(CaseTriggerDeleteAffectedPassengers);
        
        Trigger_Status__c CaseTriggerPostNotification = new Trigger_Status__c();
        CaseTriggerPostNotification.Name = 'CaseTriggerPostNotification';
        CaseTriggerPostNotification.Active__c = true;
        lsttrgStatus.add(CaseTriggerPostNotification);

        
        Trigger_Status__c caseTriggerCaseStream = new Trigger_Status__c();
        caseTriggerCaseStream.Name = 'QCC_CaseStream';
        caseTriggerCaseStream.Active__c = true;
        lsttrgStatus.add(caseTriggerCaseStream);
        
        Trigger_Status__c postToChatterFeed = new Trigger_Status__c();
        postToChatterFeed.Name = 'postToChatterFeed';
        postToChatterFeed.Active__c = true;
        lsttrgStatus.add(postToChatterFeed);

        Trigger_Status__c SubmitForFinalisation = new Trigger_Status__c();
        SubmitForFinalisation.Name = 'SubmitForFinalisation';
        SubmitForFinalisation.Active__c = true;
        lsttrgStatus.add(SubmitForFinalisation);
        
        Trigger_Status__c trgCaseFieldUpdates = new Trigger_Status__c();
        trgCaseFieldUpdates.Name = 'trgCaseFieldUpdates';
        trgCaseFieldUpdates.Active__c = true;
        lsttrgStatus.add(trgCaseFieldUpdates);
        
        //GRAPHITE-409, GRAPHITE-927: Enforces running the assignment rule for VIP cases
        Trigger_Status__c assignVIPCaseUsingAssignmentRule = new Trigger_Status__c();
        assignVIPCaseUsingAssignmentRule.Name = 'assignVIPCaseUsingAssignmentRule';
        assignVIPCaseUsingAssignmentRule.Active__c = true;
        lsttrgStatus.add(assignVIPCaseUsingAssignmentRule);
        
        Trigger_Status__c autoCaseProcess = new Trigger_Status__c();
        autoCaseProcess.Name = 'autoCaseProcess';
        autoCaseProcess.Active__c = true;
        lsttrgStatus.add(autoCaseProcess);

        Trigger_Status__c fetchCongaEmailTemplateId = new Trigger_Status__c();
        fetchCongaEmailTemplateId.Name = 'fetchCongaEmailTemplateId';
        fetchCongaEmailTemplateId.Active__c = true;
        lsttrgStatus.add(fetchCongaEmailTemplateId);
        
        Trigger_Status__c populateBasicAutoCaseValues = new Trigger_Status__c();
        populateBasicAutoCaseValues.Name = 'CaseTriggerPopulateBasicAutoCaseValues';
        populateBasicAutoCaseValues.Active__c = true;
        lsttrgStatus.add(populateBasicAutoCaseValues);

        Trigger_Status__c SetAuditFieldsOnCase = new Trigger_Status__c();
        SetAuditFieldsOnCase.Name = 'SetAuditFieldsOnCase';
        SetAuditFieldsOnCase.Active__c = true;
        lsttrgStatus.add(SetAuditFieldsOnCase);

        Trigger_Status__c CaseTriggerUpdateTECHFields = new Trigger_Status__c();
        CaseTriggerUpdateTECHFields.Name = 'CaseTriggerUpdateTECHFields';
        CaseTriggerUpdateTECHFields.Active__c = true;
        lsttrgStatus.add(CaseTriggerUpdateTECHFields);

        
        Trigger_Status__c CaseHotwordQueueRoutingTrigger= new Trigger_Status__c();
        CaseHotwordQueueRoutingTrigger.Name = 'CaseHotwordQueueRoutingTrigger';
        CaseHotwordQueueRoutingTrigger.Active__c = true;
        lsttrgStatus.add(CaseHotwordQueueRoutingTrigger);
        
        Trigger_Status__c UpdateCaseOnClos = new Trigger_Status__c();
        UpdateCaseOnClos.Name = 'CaseTriggerUpdateCaseOnClose';
        UpdateCaseOnClos.Active__c = true;
        lsttrgStatus.add(UpdateCaseOnClos);

        
        Trigger_Status__c caseStatusUpdated = new Trigger_Status__c();
        caseStatusUpdated.Name = 'caseStatusUpdated';
        caseStatusUpdated.Active__c = true;
        lsttrgStatus.add(caseStatusUpdated);
        
        Trigger_Status__c CaseTriggerCalculateEmergencyExpense = new Trigger_Status__c();
        CaseTriggerCalculateEmergencyExpense.Name = 'CaseTriggerCalculateEmergencyExpense';
        CaseTriggerCalculateEmergencyExpense.Active__c = true;
        lsttrgStatus.add(CaseTriggerCalculateEmergencyExpense);
        
        Trigger_Status__c CaseTriggerpopulateonCaseCreate = new Trigger_Status__c();
        CaseTriggerpopulateonCaseCreate.Name = 'CaseTriggerpopulateonCaseCreate';
        CaseTriggerpopulateonCaseCreate.Active__c = true;
        lsttrgStatus.add(CaseTriggerpopulateonCaseCreate);

        Trigger_Status__c assignCaseOwner = new Trigger_Status__c();
        assignCaseOwner.Name = 'assignCaseOwner';
        assignCaseOwner.Active__c = true;
        lsttrgStatus.add(assignCaseOwner);
        
        
        Trigger_Status__c CaseTriggerUpdateCaseEscalatedTo = new Trigger_Status__c();
        CaseTriggerUpdateCaseEscalatedTo.Name = 'CaseTriggerUpdateCaseEscalatedTo';
        CaseTriggerUpdateCaseEscalatedTo.Active__c = true;
        lsttrgStatus.add(CaseTriggerUpdateCaseEscalatedTo);

        Trigger_Status__c CaseTriggerUpdateCaseSLA = new Trigger_Status__c();
        CaseTriggerUpdateCaseSLA.Name = 'CaseTriggerUpdateCaseSLA';
        CaseTriggerUpdateCaseSLA.Active__c = true;
        lsttrgStatus.add(CaseTriggerUpdateCaseSLA);

        
        Trigger_Status__c updateCaseFields = new Trigger_Status__c();
        updateCaseFields.Name = 'updateCaseFields';
        updateCaseFields.Active__c = true;
        lsttrgStatus.add(updateCaseFields);

        Trigger_Status__c updateCaseComplimentTemplateValue = new Trigger_Status__c();
        updateCaseComplimentTemplateValue.Name = 'updateCaseComplimentTemplateValue';
        updateCaseComplimentTemplateValue.Active__c = true;
        lsttrgStatus.add(updateCaseComplimentTemplateValue);
        
        Trigger_Status__c trgTradeSiteResponses = new Trigger_Status__c();
        trgTradeSiteResponses.Name = 'trgTradeSiteResponses';
        trgTradeSiteResponses.Active__c = true;
        lsttrgStatus.add(trgTradeSiteResponses);

        Trigger_Status__c EmailMessageTriggerV1 = new Trigger_Status__c();
        EmailMessageTriggerV1.Name = 'EmailMessageTriggerV1';
        EmailMessageTriggerV1.Active__c = true;
        lsttrgStatus.add(EmailMessageTriggerV1);
        
        Trigger_Status__c EmailMessageHelper = new Trigger_Status__c();
        EmailMessageHelper.Name = 'EmailMessageHelper';
        EmailMessageHelper.Active__c = true;
        lsttrgStatus.add(EmailMessageHelper);

        Trigger_Status__c EmailMessageTriggerLoungePassNonFFM = new Trigger_Status__c();
        EmailMessageTriggerLoungePassNonFFM.Name = 'EmailMessageTriggerLoungePassNonFFM';
        EmailMessageTriggerLoungePassNonFFM.Active__c = false;
        lsttrgStatus.add(EmailMessageTriggerLoungePassNonFFM);
        
        Trigger_Status__c processCaseEmailMessage = new Trigger_Status__c();
        processCaseEmailMessage.Name = 'processCaseEmailMessage';
        processCaseEmailMessage.Active__c = true;
        lsttrgStatus.add(processCaseEmailMessage);
        
        
        Trigger_Status__c captureFirstOutboundEmail = new Trigger_Status__c(Name='captureFirstOutboundEmail', Active__c=true);
        lsttrgStatus.add(captureFirstOutboundEmail);

        insert lsttrgStatus;

        TestUtilityDataClassQantas.insertQantasConfigData();
        
    }

    static testMethod void testCaseTrigger() {
        try {

            String type = 'Complaint';
            String recordType = 'CCC Complaints';
            Test.startTest();
            //Contact con = [SELECT Id, Name FROM Contact Limit 1];
            Case cs = TestUtilityDataClassQantas.createCaseWithCodingValues(recordType, type, 'In-Flight', 'In-Flight Entertainment', 'Content', 'Content variety');
            //cs.ContactId = con.id;
            insert cs;
            cs.RecordTypeId = GenericUtils.getObjectRecordTypeId('Case', CustomSettingsUtilities.getConfigDataMap('Case QCC Medical RecType'));
            cs.Type = 'Medical-Patient';
            cs.Group__c = 'Departure Airport';
            cs.Category__c = '';
            cs.Sub_Category__c = '';
            cs.Classification__c = '';
            cs.Assign_using_active_assignment_rules__c = true;
            update cs;
            Test.stopTest();
        } catch (Exception ex) {
            system.debug('exception in testCaseTrigger=======>  ' + ex.getMessage());
            System.debug(LoggingLevel.ERROR, ex.getMessage());
            System.debug(LoggingLevel.ERROR, ex.getStackTraceString());
        }
    }

    
    static testMethod void testEmailMessageTrigger() {
        try {
            String type = 'Complaint';
            String recordType = 'CCC Complaints';
            Test.startTest();
            //Contact con = [SELECT Id, Name FROM Contact Limit 1];
            Case objCase = TestUtilityDataClassQantas.createCaseWithCodingValues(recordType, type, 'In-Flight', 'In-Flight Entertainment', 'Content', 'Content variety');
            insert objCase;

            EmailMessage em   = new EmailMessage();
            em.Incoming       = false;
            em.FromAddress    = 'qantas_customer_care@qantas.com.au';
            em.ToAddress      = 'test@test.com';
            em.Subject        = 'Qantas Customer Care';
            em.HtmlBody       = '<br/><h1>Hello!!</h1>';
            em.Status         = '3';
            em.ParentId       = objCase.Id;
            insert em;
    
            em.TECH_FromChatter__c = false;
            update em;

            delete em;

        } catch (Exception ex) {
            system.debug('exception in testEmailMessageTrigger=======>  ' + ex.getMessage());
            System.debug(LoggingLevel.ERROR, ex.getMessage());
            System.debug(LoggingLevel.ERROR, ex.getStackTraceString());
        }

    }


    static testMethod void testFreightEmailMessageTrigger() {
    try {

        Airport_Code__c arptCode = new Airport_Code__c (Name='NONE', Freight_Airport_State_Code__c='CA', QF_Freight_Presence__c=true);
        insert arptCode;
        
        Case cs = new Case( 
            RecordTypeId = RTID_CASE_QFREIGHT, 
            Origin = 'FRT Cust Service',
            Status = 'Open',
            Subject = 'Test Case 10',
            Description = 'This is for testing.',
            Freight_Port__c = arptCode.Id,
            SuppliedEmail = 'greenavenue@qantas.com.au',
            SuppliedCompany = 'Green Avenue Corp'
        );
        insert cs;
        
        EmailMessage em   = new EmailMessage();
        em.Incoming       = false;
        em.FromAddress    = 'qantas_customer_care@qantas.com.au';
        em.ToAddress      = 'test@test.com';
        em.Subject        = 'Qantas Customer Care';
        em.HtmlBody       = '<br/><h1>Hello!!</h1>';
        em.Status         = '3';
        em.ParentId       = cs.Id;
        insert em;
    
        em.TECH_FromChatter__c = false;
        update em;

    } catch (Exception ex) {
        system.debug('exception in testEmailMessageTrigger=======>  ' + ex.getMessage());
        System.debug(LoggingLevel.ERROR, ex.getMessage());
        System.debug(LoggingLevel.ERROR, ex.getStackTraceString());
    }

 }

    

}