force-app/main/default/objects/Contact/fields/Business_Types__c.field-meta.xml
<CustomField>
    <fullName>Business_Types__c</fullName>
    <inlineHelpText>Freight: Users always need to select &quot;Freight&quot;
Loyalty: Users always need to select &quot;Loyalty&quot;</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>B&amp;G</fullName>
            </value>
            <value>
                <fullName>Supplier/Commercial Partner</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Assumed_Tag_Rate_at_Maturity__c.field-meta.xml
<CustomField>
    <fullName>Assumed_Tag_Rate_at_Maturity__c</fullName>
    <description>This field is used to capture percentage values and can have up to 2 decimal points</description>
    <inlineHelpText>Tag rate at the height of program</inlineHelpText>
    <label>Assumed Tag Rate at Maturity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Average_Spend_Per_Customer__c.field-meta.xml
<CustomField>
    <fullName>Average_Spend_Per_Customer__c</fullName>
    <description>Text field to capture dollar values. Values are captured up to 2 decimal points.Values are thousandth separated by commas (,)</description>
    <inlineHelpText>Estimated average annual spend of partnership</inlineHelpText>
    <label>Average Annual Spend Per Customer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Base__c.field-meta.xml
<CustomField>
    <fullName>Customer_Base__c</fullName>
    <description>This field is used to capture numbers.</description>
    <inlineHelpText>Size of the customer segment eligible for the proposition</inlineHelpText>
    <label>Customer Base</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forecast_MCA_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Forecast_MCA_Revenue__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Made Field Required based on CRM-5337 
Removed Required Field check -FCRM-956</description>
    <inlineHelpText>Including EK spend if joint customer</inlineHelpText>
    <label>Forecast MCA Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Points_Per__c.field-meta.xml
<CustomField>
    <fullName>Points_Per__c</fullName>
    <description>This field is used to capture number values and are up to 2 decimal points</description>
    <inlineHelpText>Points issued per $</inlineHelpText>
    <label>Points Per $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Per_Point__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Point__c</fullName>
    <description>This field captures dollar values and are up to 4 decimal points.</description>
    <inlineHelpText>How much an individual point costs (Please enter the value in Dollars)</inlineHelpText>
    <label>Price Per Point excluding GST</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Assumed_Tag_Rate_at_Maturity__c.field-meta.xml
<CustomField>
    <fullName>Assumed_Tag_Rate_at_Maturity__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Tag rate at the height of program</inlineHelpText>
    <label>Assumed Tag Rate at Maturity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Points_Per__c.field-meta.xml
<CustomField>
    <fullName>Points_Per__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>Points issued per $</inlineHelpText>
    <label>Points Per $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Price_Per_Point__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Point__c</fullName>
    <description>Loyalty commercial field</description>
    <inlineHelpText>How much an individual point costs</inlineHelpText>
    <label>Price Per Point</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Rate_Valid_after_acceptance_until__c.field-meta.xml
<CustomField>
    <fullName>Rate_Valid_after_acceptance_until__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rate Valid after acceptance until</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QuickQuoteControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of QuickQuoteController class.
 * Modified By : Venkata Suresh Kumar (TCS Team), 02-Apr-2026
 * Desc : Remediated test class failures. Added setUpData() method. Updated test() method
 */
@isTest
public class QuickQuoteControllerTest {
    @testSetup static void setUpData() {
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType(); //Added as part of test class refactor CRM-11408
    }
    
    public static testMethod void test() {
        Id LoyaltyRecordTypeId= GenericUtils.getObjectRecordTypeId('Quote', 'Loyalty Commercial');
        Id oppRecordTypeId= GenericUtils.getObjectRecordTypeId('Opportunity', 'Loyalty Commercial');
        Account acc = new Account(Name = 'Test1');
        insert acc;
        
        Contact objcontact = new Contact();
        objcontact.FirstName = 'TestContact-Loyalty';
        objcontact.LastName = acc.Name;
        objcontact.Business_Types__c = 'Loyalty';
        objcontact.Email = 'test923@abc.com';
        insert objcontact;
        
        Opportunity opp = new Opportunity();        
        opp.RecordTypeId = oppRecordTypeId;
        opp.AccountId = acc.Id;
        opp.Name = 'Oppty';
        opp.Customer_Base__c = 1000;
        opp.Points_Per__c = 10;
        opp.Price_Per_Point__c = 0.0180;
        opp.Assumed_Tag_Rate_at_Maturity__c = 1.45;
        opp.Average_Spend_Per_Customer__c = 1000;
        opp.StageName = 'Prospect';
        opp.CloseDate = System.today();
        opp.Type = 'Qantas Business Rewards';
        opp.Forecast_MCA_Revenue__c=20000;
        insert opp;
        
        Opportunity opp2 = QuickQuoteController.getOpp(opp.Id);
        System.assertEquals(opp.Name, opp2.Name);
        System.assertEquals(opp.Price_Per_Point__c, opp2.Price_Per_Point__c);
        
        Quote qt = new Quote(Name='Test Quote', ContactId = objcontact.Id, Rate_Valid_after_acceptance_until__c=Date.today());
        qt = QuickQuoteController.saveQuoteWithOpp(qt, opp2);
        System.assertEquals('Test Quote', qt.Name);
        System.assertEquals(opp2.Price_Per_Point__c, qt.Price_Per_Point__c);
    }
}