force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_Last_Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>QCC_Last_Activity_Date__c</fullName>
    <description>Automatically set to the current date when a task or event is created. Used as reference to determine the most recent last activity date.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_Last_Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>QCC_Last_Flight_Date__c</fullName>
    <description>Value comes from Pre-Departure platform event. This is used as a reference date after x number of days on when to create &quot;No Fly Health Check&quot; case.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Flight Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_TECH_FF_Number_External_Id__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_FF_Number_External_Id__c</fullName>
    <description>Used for enforcing uniqueness of Frequent Flyer Number within the B2B and B2C space separately.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>QCC TECH FF Number External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_TECH_RecordType__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_RecordType__c</fullName>
    <description>Populated automatically for Individual Contact record to be used in enforcing matching rules</description>
    <encryptionScheme>None</encryptionScheme>
    <label>QCC TECH RecordType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&apos;CAP&apos;</defaultValue>
    <description>Indicates the origin of this contact</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Source</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SSU__c.field-meta.xml
<CustomField>
    <fullName>SSU__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Corporate: Special Service Unit -This person&apos;s travel / relationship is overseen by the special service unit</inlineHelpText>
    <label>SSU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/batchToMergeDuplicateNonFFConts.cls
public with sharing class batchToMergeDuplicateNonFFConts implements Database.Batchable<sObject>, Database.stateful, schedulable {
    
   public Contact contNonFFMast;
   public Integer soqlLimit;

    public batchToMergeDuplicateNonFFConts(){}
    public batchToMergeDuplicateNonFFConts(Integer intLmt){
        this.soqlLimit=intLmt;
    }
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        String query;
        Id contactRTID= Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        String techRecName='Individual Contact';
        system.debug('contact record type id'+contactRTID);
        query='SELECT id,email,firstname,lastname,Phone,Frequent_Flyer_Number__c,QCC_Last_Activity_Date__c,QCC_Last_Flight_Date__c,Source__c,QCC_TECH_FF_Number_External_Id__c,SSU__c FROM Contact WHERE recordtypeid=:contactRTID and firstname!=null and lastname!=null and email!=null and phone!=null and QCC_TECH_RecordType__c=:techRecName order by firstname,lastname,email,phone,createddate,Frequent_Flyer_Number__c asc limit '+soqlLimit;
       return Database.getQueryLocator(query);
    }
 
    public void execute(Database.BatchableContext bc, List<contact> scope)
    {
        try 
        {
            Map<String,Id> nonFFMasterContMap=new Map<String,Id>();
            Map<Id,List<Id>> masterContDupMap=new Map<Id,List<Id>>();
            Map<Id,contact> mapScopeConts=new Map<Id,Contact>(scope);

            System.debug('>>>In the execute');
            if(scope!=null)
            {
                if(this.contNonFFMast!=null)
                {
                    String uniquePhone=this.contNonFFMast.Phone.deleteWhitespace().trim().right(9);
                    String key = this.contNonFFMast.FirstName.deleteWhitespace().trim() +this.contNonFFMast.LastName.deleteWhitespace().trim() + uniquePhone +this.contNonFFMast.Email;
                    nonFFMasterContMap.put(key,this.contNonFFMast.id);
                    masterContDupMap.put(this.contNonFFMast.id,new list<Id>());
                    mapScopeConts.put(this.contNonFFMast.id,this.contNonFFMast);
                }
                for(Contact getCont :scope)
                {
                    
                    String uniquePhone=getCont.Phone.deleteWhitespace().trim().right(9);
                    String key = getCont.FirstName.deleteWhitespace().trim() + getCont.LastName.deleteWhitespace().trim() + uniquePhone + getCont.Email;
                    system.debug('>>> here is the Key'+key);
                    //MasterContactMap check if it has NOT matched the current contacts key
                    if(!nonFFMasterContMap.containskey(key))
                    {
                        //Add the Master Contacts unique Key value and the master contacts ID
                        nonFFMasterContMap.put(key,getCont.id);
                        //Add the Master contacts ID and instantiate the list of duplicate contacts IDs
                        masterContDupMap.put(getCont.id,new list<Id>());
                        //Add master contact to a contact variable
                        this.contNonFFMast=mapScopeConts.get(getCont.id);
                    }
                    else //If nonFFMasterContMap already has the unique Key but needs to add more duplicate contacts
                    {
                        masterContDupMap.get(nonFFMasterContMap.get(key)).add(getCont.id);  
                    }
                }
                System.debug('>>>print the mapkeys masterContDupMap'+masterContDupMap.keySet());
                System.debug('>>>print the mapValue masterContDupMap'+masterContDupMap.values());
                System.debug('>>>print the mapValue masterContDupMap value length'+masterContDupMap.values().size());

                //Assign
                for(Contact getCont :scope)
                {
                    if(masterContDupMap.get(getCont.id)!=null)
                    {
                        for(Id getId: masterContDupMap.get(getCont.id))
                        {
                            if(mapScopeConts.get(getId).Frequent_Flyer_Number__c!=null)
                            {
                                List<Id> getResturnedIds=masterContDupMap.remove(getCont.id);
                                system.debug('>>> the values of deleted key'+getResturnedIds);
                                getResturnedIds.remove(getResturnedIds.indexof(getId));
                                getResturnedIds.add(getCont.id);
                                masterContDupMap.put(getId,getResturnedIds);
                                system.debug('>>> here is the map key'+getId);
                                system.debug('>>> here is the map values'+masterContDupMap.get(getId));
                                system.debug('>>> here is the map values size'+masterContDupMap.get(getId).size());
                                break;
                            }
                        }
                    }
                   
                }
                System.debug('>>>print the mapkeys masterContDupMap after resorting'+masterContDupMap.keySet());
                System.debug('>>>print the mapValue masterContDupMap after resorting'+masterContDupMap.values());
                System.debug('>>>print the mapValue masterContDupMap value length after resorting'+masterContDupMap.values().size());


                if(!masterContDupMap.isEmpty())
                {
                    for(Id getMasterId: masterContDupMap.keySet())
                    {
                        list<Id> lstDupSetIds=masterContDupMap.get(getMasterId); 
                        while(!lstDupSetIds.isempty())
                        {
                            List<Id> duplList=new List<Id>();
                            List<Contact> dupContLst=new List<Contact>();
                            duplList.add(lstDupSetIds.remove(0));
                            dupContLst.add(mapScopeConts.get(duplList[0]));
                            if(!lstDupSetIds.isempty())
                            {
                                duplList.add(lstDupSetIds.remove(0));
                                dupContLst.add(mapScopeConts.get(duplList[1]));
                            }
                            Map<Id,Contact> getDupMap=mapFieldsValueToMaster(mapScopeConts.get(getMasterId),dupContLst);
                            database.merge(getDupMap.get(getMasterId),duplList);
                        }
                    }
                }
            }

        } catch (Exception ex) 
        {
            system.debug('Duplicates Merge Fields Mapping Exception###'+ex);
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC - batchToMergeDuplicateFFConts', 'batchToMergeDuplicateFFConts', 
                            'Execute', '', '', false,'', ex);
        }    
    }
 
    public void finish(Database.BatchableContext bc){
    }
    public void execute(SchedulableContext sc) 
   {
      Database.executeBatch(new batchToMergeDuplicateNonFFConts(soqlLimit));
   } 
    public Map<Id,Contact> mapFieldsValueToMaster(Contact getMaster,List<Contact> listConts)
    {
        Map<Id,Contact> returnMap=new Map<Id,Contact>();
        try {
            
        if(getMaster!=null)
        {
                List<Contact> contList=new List<Contact>();
                for(Contact getCont: listConts)
                {
                    if((getMaster.SSU__c ==false) && (getCont.SSU__c!=false))
                    {
                        getMaster.SSU__c=getCont.SSU__c;
                        
                    }
                    if((getMaster.QCC_TECH_FF_Number_External_Id__c ==null || getMaster.QCC_TECH_FF_Number_External_Id__c =='') && (getCont.QCC_TECH_FF_Number_External_Id__c!=null || getCont.QCC_TECH_FF_Number_External_Id__c!=''))
                    {
                        getMaster.QCC_TECH_FF_Number_External_Id__c=getCont.QCC_TECH_FF_Number_External_Id__c;
                        
                    }
                    if((getMaster.Source__c  ==null || getMaster.Source__c  =='') && (getCont.Source__c !=null || getCont.Source__c !=''))
                    {
                        getMaster.Source__c =getCont.Source__c ;
                        
                    }
                    if((getMaster.QCC_Last_Activity_Date__c==null && getCont.QCC_Last_Activity_Date__c!=null) || ((getMaster.QCC_Last_Activity_Date__c!=null && getCont.QCC_Last_Activity_Date__c!=null) &&
                        (getMaster.QCC_Last_Activity_Date__c < getCont.QCC_Last_Activity_Date__c)))
                    {
                        getMaster.QCC_Last_Activity_Date__c=getCont.QCC_Last_Activity_Date__c;
                    }
                    if( (getMaster.QCC_Last_Flight_Date__c==null && getCont.QCC_Last_Flight_Date__c!=null) || ((getMaster.QCC_Last_Flight_Date__c!=null && getCont.QCC_Last_Flight_Date__c!=null) &&
                    (getMaster.QCC_Last_Flight_Date__c < getCont.QCC_Last_Flight_Date__c)) )
                    {
                        getMaster.QCC_Last_Flight_Date__c =getCont.QCC_Last_Flight_Date__c ;
                    }
                    
                }
                returnMap.put(getMaster.id,getMaster);
        }
        return returnMap;
    } catch (Exception ex) {
        system.debug('Duplicates Merge Fields Mapping Exception###'+ex);
        CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'QCC - Duplicated Merging Field Mapping Failed', 'batchToMergeDuplicateNonFFConts', 
                            'mapFieldsValueToMaster', '', '', false,'', ex);
    }
    return returnMap;
    }
}