force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Frequent_Flyer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Tier__c</fullName>
    <description>QCC: Created to show/store Contact&apos;s Frequent Flyer Tier.</description>
    <label>Frequent Flyer Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-tiered</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Non-tiered</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
                <color>#DDDDDD</color>
                <label>Bronze</label>
            </value>
            <value>
                <fullName>Silver</fullName>
                <color>#DDDDDD</color>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
                <color>#FFCC33</color>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
                <color>#FFCC33</color>
                <label>Platinum</label>
            </value>
            <value>
                <fullName>Platinum One</fullName>
                <color>#000000</color>
                <label>Platinum One</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge</label>
            </value>
            <value>
                <fullName>Lifetime Silver</fullName>
                <color>#DDDDDD</color>
                <label>Lifetime Silver</label>
            </value>
            <value>
                <fullName>Lifetime Gold</fullName>
                <color>#FFCC33</color>
                <label>Lifetime Gold</label>
            </value>
            <value>
                <fullName>Chairman&apos;s Lounge Platinum One</fullName>
                <color>#000000</color>
                <label>Chairman&apos;s Lounge Platinum One</label>
            </value>
            <value>
                <fullName>Chairmans Lounge</fullName>
            </value>
            <value>
                <fullName>Chairmans Lounge Platinum One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_Qantas_Host_Always_Call__c.field-meta.xml
<CustomField>
    <fullName>QCC_Qantas_Host_Always_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Qantas Host Always Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Description__c.field-meta.xml
<CustomField>
    <fullName>Config_Description__c</fullName>
    <description>Apex class in which it is used and key notes on the value</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/fields/Config_Value__c.field-meta.xml
<CustomField>
    <fullName>Config_Value__c</fullName>
    <description>Text values used in the code</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Config Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/classes/QCC_LookupPhoneNumberControllerTest.cls
/*----------------------------------------------------------------------------------------------------------------------
Author:        Sherin Yohannan
Company:       Accenture
Description:   Test class for QCC_LookupPhoneNumberControllerTest
Inputs:
Test Class:     
************************************************************************************************
History
************************************************************************************************

-----------------------------------------------------------------------------------------------------------------------*/
@isTest
public class QCC_LookupPhoneNumberControllerTest {
    @testSetup
    static void createData() {
        QantasConfigData__c qc = new QantasConfigData__c();
        qc.Name = 'Log Exception Logs Rec Type';
        qc.Config_Value__c = 'Exception Logs';
        qc.Config_Description__c = 'Log Exception Logs Record Type Name';
        insert qc;
        
        TestUtilityDataClassQantas.insertQantasConfigData();
        List<Qantas_API__c> lstQantas = TestUtilityDataClassQantas.createQantasAPI();
        insert lstQantas;
        
        //Set Custom Settings for Trigger_Status__c Custom settings
        List<Trigger_Status__c> customSettingTriggerStatusLists = QCC_TestDataFactory.createTriggerStatusData();
        insert customSettingTriggerStatusLists;
        
        String accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc = QCC_TestDataFactory.createAccountTestData(1);
        acc.RecordTypeId = accountRecordTypeId;
        insert acc;
        
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        Contact con = QCC_TestDataFactory.createContactTestData(1, acc.Id);
        con.RecordTypeId = contactRecordTypeId;
        con.Phone = String.valueOf(1234123412);
        con.Frequent_Flyer_Number__c = '6142207';
        con.Frequent_Flyer_Tier__c = 'Platinum One';
        con.QCC_Qantas_Host_Always_Call__c = false;
        insert con;
        Contact con1 = [select Id,Phone from contact];
        system.debug('the contact  and acoount created'+ con1);
    }
    
    static testMethod void testLookupCustomerPositive() {
        QCC_LookupPhoneNumberController.CustomerWrapper cw = new QCC_LookupPhoneNumberController.CustomerWrapper();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new QCC_CAPServicesMock());
        List<String> str = QCC_LookupPhoneNumberController.lookupCustomer('6142207','','');
        system.debug('from lookuptester'+str);
        //CRM-6427: CIP Decommissioning
        //cw = (QCC_LookupPhoneNumberController.CustomerWrapper)JSON.deserialize(str[0], QCC_LookupPhoneNumberController.CustomerWrapper.Class);
        Test.stopTest();
        //System.assertEquals('Chairmanslounge', cw.lastName);
    }
    
    static testMethod void testLookupCustomerPhoneNumber() {
        QCC_LookupPhoneNumberController.CustomerWrapper cw = new QCC_LookupPhoneNumberController.CustomerWrapper();
        Test.startTest();
        List<String> str = QCC_LookupPhoneNumberController.lookupCustomer('','1234123412','');
        Test.stopTest();
        System.assertEquals(1, str.size());
    }
    
    static testMethod void testLookupCustomerException() {
        QCC_LookupPhoneNumberController.CustomerWrapper cw = new QCC_LookupPhoneNumberController.CustomerWrapper();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new QCC_CalloutExceptionMock());
        List<String> str = QCC_LookupPhoneNumberController.lookupCustomer('0006142212','','');
        Test.stopTest();
        System.assertEquals(null, str);
        
    }
}