force-app/main/default/objects/Contact/fields/Frequent_Flyer_Number__c.field-meta.xml
<CustomField>
    <fullName>Frequent_Flyer_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Frequent Flyer Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/QCC_TECH_RecordType__c.field-meta.xml
<CustomField>
    <fullName>QCC_TECH_RecordType__c</fullName>
    <description>Populated automatically for Individual Contact record to be used in enforcing matching rules</description>
    <encryptionScheme>None</encryptionScheme>
    <label>QCC TECH RecordType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Schedule_Sensitive_Message__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sensitive_Message__c</fullName>
    <description>CRM-8645 This field is used to store schedule date and time for sensitive message.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedule Sensitive Message</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&apos;CAP&apos;</defaultValue>
    <description>Indicates the origin of this contact</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Source</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SSU__c.field-meta.xml
<CustomField>
    <fullName>SSU__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Corporate: Special Service Unit -This person&apos;s travel / relationship is overseen by the special service unit</inlineHelpText>
    <label>SSU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QantasConfigData__c/QantasConfigData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to hold all the hard code text that are used in Apex.</description>
    <label>Qantas ConfigData</label>
</CustomObject>

force-app/main/default/classes/qccDateTimeOperationsTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class qccDateTimeOperationsTest {

    @isTest
    static void myUnitTest1() {

        List<QantasConfigData__c> lstConfigData = new List<QantasConfigData__c>();
        lstConfigData.add(TestUtilityDataClassQantas.createQantasConfigData('Log Exception Logs Rec Type','Exception Logs'));
        insert lstConfigData;
        TestUtilityDataClassQantas.createQantasConfigDataAccRecType();
        
        Datetime currentDateTime=DateTime.now();
        DateTime GMTDateNow = Datetime.newInstanceGmt(currentDateTime.year(),currentDateTime.month(),currentDateTime.day(),currentDateTime.hour(),currentDateTime.minute(),currentDateTime.second());
        Datetime selectedDateTime=currentDateTime.addhours(3);    

        Id contactRTID= Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual Contact').getRecordTypeId();
        Contact createCont=new Contact(firstname='Duplicate',lastname='Cont1',Frequent_Flyer_Number__c='12345',Source__c='',SSU__c=false,recordtypeid=contactRTID,Schedule_Sensitive_Message__c=GMTDateNow.addminutes(-10),QCC_TECH_RecordType__c='Individual Contact');
        insert createCont;
        
        Contact createCont2=new Contact(firstname='Duplicate',lastname='Cont2',Frequent_Flyer_Number__c='123456',Source__c='',SSU__c=false,recordtypeid=contactRTID,Schedule_Sensitive_Message__c=GMTDateNow.addhours(5),QCC_TECH_RecordType__c='Individual Contact');
        insert createCont2;


        test.startTest();
        qccDateTimeOperations.getCurrentDateTime();
        qccDateTimeOperations.compareDateTime(createCont.id);
		qccDateTimeOperations.compareDateTime(createCont2.id);
        qccDateTimeOperations.convertInGMT(selectedDateTime);
        qccDateTimeOperations.compareSelectedDateTime(selectedDateTime);

        try{
            qccDateTimeOperations.compareSelectedDateTime(null);
            qccDateTimeOperations.convertInGMT(null);
          }catch(AuraHandledException e){
            Assert.areEqual('Script-thrown exception', e.getMessage());
             }
          
       

        test.stopTest();
    }
}