force-app/main/default/objects/Contact/fields/QAC_Contact__c.field-meta.xml
<CustomField>
    <fullName>QAC_Contact__c</fullName>
    <description>Used to Identify QAC Manager Contacts</description>
    <label>QAC Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Verification_Number__c.field-meta.xml
<CustomField>
    <fullName>Verification_Number__c</fullName>
    <description>IATA issued individual agent verification number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agent IATA Card Verification number</inlineHelpText>
    <label>Verification Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QAC_ManagerContDupCheck_Test.cls
/*-----------------------------------------------------------------------------------------------------------------------------
Author:TCS       
Description:To check whether Manager contact is duplicate or not based few scenarios   
Test Class for  QAC_ManagerContactsDuplicateCheck  
*********************************************************************************************************************************
*********************************************************************************************************************************/
@IsTest
public class QAC_ManagerContDupCheck_Test {
    
    @testsetup
    public static void setupdata()
    {
           
        // Create PermissionSet with Custom Permission and assign to test user
    PermissionSet ps = new PermissionSet();
    ps.Name = 'Test';
    ps.Label = 'Test';
    insert ps;
    SetupEntityAccess sea = new SetupEntityAccess();
    sea.ParentId = ps.Id;
    sea.SetupEntityId = [select Id from CustomPermission where DeveloperName = 'QCC_Bypass_Account_Contact_Case_Triggers'][0].Id;
    insert sea;
    PermissionSetAssignment psa = new PermissionSetAssignment();
    psa.AssigneeId = UserInfo.getUserId();
    psa.PermissionSetId = ps.Id;
    insert psa;
    }
    @IsTest
    public static void dedupe(){
        TestUtilityDataClassQantas.enableTriggers();
     	TestUtilityDataClassQantas.createContactTriggerSetting();
        
        String conRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId(); 
     	List<Contact> conList = new List<Contact>();
        Contact con1 = new Contact(FirstName='Fname1', LastName='testxby',Email='testxby@gmail.com',MobilePhone='9999256123',verification_number__c='1234567098',QAC_Contact__c='Yes',RecordTypeId=conRTId);
        conList.add(con1);
        Contact con2 = new Contact(FirstName='Fname2', LastName='testxby',Email='testxby@gmail.com',MobilePhone='9999256123',QAC_Contact__c='Yes',RecordTypeId=conRTId);
        conList.add(con2);
        try{
        insert conList;
        
        Contact con = new Contact();
        con.id=conList[0].id;
        con.Verification_Number__c='1234586709';
        update con;
        }Catch(Exception e){System.debug('Exception Caught');}
        
        
    }

}