force-app/main/default/objects/Contact/fields/QCC_Qantas_Host_Always_Call__c.field-meta.xml
<CustomField>
    <fullName>QCC_Qantas_Host_Always_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Qantas Host Always Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QCC_First_Host__c/QCC_First_Host__c.object-meta.xml
<CustomObject>
    <description>Container for creating records for the First Host process</description>
    <label>Qantas Host</label>
    <nameField>
        <displayFormat>FH{00000000}</displayFormat>
        <label>First Host Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qantas Hosts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QCC_First_Host__c/fields/QCC_First_Host_Contact__c.field-meta.xml
<CustomField>
    <fullName>QCC_First_Host_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Automatically populated when watchlist record is created under the contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>First_Hosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QCC_Source_to_Target_Object_Mapping__mdt/QCC_Source_to_Target_Object_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>QCC Source to Target Object Mapping</label>
    <pluralLabel>QCC Source to Target Object Mappings</pluralLabel>
</CustomObject>

force-app/main/default/classes/QCC_QantasHostCreateCaseInvocable.cls
//for contacts with always call ticked
//for GRAPHITE-958
public class QCC_QantasHostCreateCaseInvocable {
    @InvocableMethod
    public static void createCaseUponQantasHostCreation(List<id> qantasHostIds){
        System.debug('>>>createCaseUponQantasHostCreation - qantasHostIds:'+ qantasHostIds);
        try{
            //get List of created QCC_First_Host__c and relate the contact to new case
            List<QCC_First_Host__c> qantasHostRecords = new List<QCC_First_Host__c>([SELECT Name,createdDate, QCC_First_Host_Contact__c, QCC_First_Host_Contact__r.QCC_Qantas_Host_Always_Call__c 
                                                                                     FROM QCC_First_Host__c 
                                                                                     WHERE  Id in :qantasHostIds AND QCC_First_Host_Contact__r.QCC_Qantas_Host_Always_Call__c = TRUE]);
           
            Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('QCC Elite Process').getRecordTypeId();
            String metaName = 'QCC_Source_to_Target_Object_Mapping__mdt';
            String conditionClause = ' WHERE Module_Name__c =  \'Case Always Call\'';
            List<sObject> metaObjects = QCC_UtilityHelper.getObjRecords (metaName, conditionClause);
            system.debug('>>>metaObjects: ' + metaObjects);
            
            List<sObject> newCaseRecords = QCC_UtilityHelper.transformSourceToTargetObjects('Case Always Call', qantasHostRecords,metaObjects , 'Case', recordTypeId, null);
            
            System.debug('>>>newCaseRecords: '+newCaseRecords);
            insert newCaseRecords;
    	}catch(Exception ex){
            System.debug('>>>exeption: '+ex);
            Log__c logRecord = QCC_LogUtilityHelper.generateLogRecord('QCC Qantas Host - Create Case', 'QCC_QantasHostCreateCaseInvocable', 'createCaseUponQantasHostCreation', '', '', false, '', ex, '');
            QCC_LogUtilityHelper.createLogRecord(logRecord);
        }
    }
}