force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/ArrivalPort__c.field-meta.xml
<CustomField>
    <fullName>ArrivalPort__c</fullName>
    <description>QCC: arrival port of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>QCC: detailed description of the Event</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/DeparturePort__c.field-meta.xml
<CustomField>
    <fullName>DeparturePort__c</fullName>
    <description>QCC: departure port of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EstimatedDepDateTime__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDepDateTime__c</fullName>
    <description>QCC: Estimated departure date/time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Estimated Departure Date/Time</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <description>QCC: the flight number affected</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepDate__c</fullName>
    <description>QCC: scheduled departure date of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepTime__c</fullName>
    <description>QCC: scheduled departure time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/EventActionPlan__c.object-meta.xml
<CustomObject>
    <description>QCC:  CJM will enter the plans to overcome the event.</description>
    <label>Event Action Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Recovery Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Action Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EventActionPlan__c/fields/ActionCompleted__c.field-meta.xml
<CustomField>
    <fullName>ActionCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IOC Action Completed check box.</description>
    <label>Action Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>IOC comments</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventActionPlan__c/fields/FlightEvent__c.field-meta.xml
<CustomField>
    <fullName>FlightEvent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QCC: Lookup to Flight Event</description>
    <label>Flight Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Action Plans</relationshipLabel>
    <relationshipName>Recovery_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qantas_API__c/Qantas_API__c.object-meta.xml
<CustomObject>
    <description>QCC: Store the endpoint, customer key and secret. 
  -- Loyalty
  -- CAP</description>
    <label>Qantas API</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Qantas API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qantas API</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Status__c/Trigger_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Enable/ Disable Trigger by using this custom setting</description>
    <label>Trigger Status</label>
</CustomObject>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Queue Members location (manila , Sydney , ..)</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manila</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Hobart</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Capetown</fullName>
            </value>
            <value>
                <fullName>Suva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RecoveryActionPlanControllerTest.cls
@isTest(seeAllData = false)
private class RecoveryActionPlanControllerTest {
    
    @testSetup
    static void setup() {
        List<Qantas_API__c> lstQantas = TestUtilityDataClassQantas.createQantasAPI();
        TestUtilityDataClassQantas.insertQantasConfigData();
        List<Trigger_Status__c> lsttrgStatus = TestUtilityDataClassQantas.createCaseTriggerSetting();
        for(Trigger_Status__c ts : lsttrgStatus){
            ts.Active__c = false;
        }
        lsttrgStatus.addAll(TestUtilityDataClassQantas.createEventTriggerSetting());
        insert lsttrgStatus;
        //CRM-11908 Updated Role for the User
        Map<String, UserRole> rolesMap = TestUtilityDataClassQantas.getRoles();
        Map<String, Profile> profMap = TestUtilityDataClassQantas.getProfileMap();
        User u1 = new User(LastName = 'User1', Alias = 'User', Email = 'sampleuser1@sample.com', 
            Username = 'sampleuser1username@sample.com', ProfileId = profMap.get('QCC Customer Journey Manager').Id, //CRM-11908 Update metadata rerferences
            EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_AU', Location__c = 'Sydney',
            TimeZoneSidKey = 'Australia/Sydney');
        insert u1;
        //CRM-11908 Update metadata rerferences
        System.runAs(new User(Id = UserInfo.getUserId())) {
            //CRM-11908 Updated Role for the User 
            u1.UserRoleId =  rolesMap.get('QF-QDC-CJM').Id; 
            update u1;
            List<Id> permissionSetIds = TestUtilityDataClassQantas.getPermissionSetIds('QCC_Base_User_Permissions,QCC_Contact_Center_Agent_Permissions,QCC_Customer_Journey_Agent_Permissions');
            List<PermissionSetAssignment> psaList = new List<PermissionSetAssignment>();
            for (Id psId : permissionSetIds) {
                psaList.add(new PermissionSetAssignment(AssigneeId = u1.Id, PermissionSetId = psId));
            }
            if (!psaList.isEmpty()) {
                insert psaList;
            }
        }
      
        // Create events
       System.runAs(u1){
        List<Event__c> events = new List<Event__c>();
        Event__c newEvent1 = TestUtilityDataClassQantas.createEventWithValues('Flight Event - Active', 'Assigned', 'Flight Delay', 'Domestic');
        //newEvent1.OwnerId = u1.Id;
        newEvent1.EstimatedDepDateTime__c = '2018-06-19 11:40:00';
        newEvent1.ScheduledDepTime__c = '19:15';
        newEvent1.ScheduledDepDate__c = Date.newInstance(2018, 06, 18);
        newEvent1.FlightNumber__c = 'QF0401';
        newEvent1.DeparturePort__c = 'SYD';
        newEvent1.ArrivalPort__c = 'MEL';
        events.add(newEvent1);

        // Add other event records similarly (newEvent2, newEvent3, etc.)

        insert events;
        Event__c objEvt = [Select Id from Event__c limit 1];
        EventActionPlan__c objActionPlan = new EventActionPlan__c();
        objActionPlan.Name = 'CJL: Meals';
        objActionPlan.ActionCompleted__c = true;
        objActionPlan.Comments__c = 'Completed';
        objActionPlan.FlightEvent__c = newEvent1.Id;
        insert objActionPlan; 
       }
    }

    @isTest
        static  void getReimbursementDataTest(){
        
       
     
        Event__c objEvt = [Select Id from Event__c limit 1];
        
        
        Test.startTest();
        List<EventActionPlan__c> result = RecoveryActionPlanController.getReimbursementData(objEvt.Id, 'CJL: Meals');
        Test.stopTest();
        System.assertNotEquals(0, result.size(), 'There should be results.');
        System.assertEquals('CJL: Meals', result[0].Name, 'The action plan name should match.');
    }
}