force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Actual_Arrival_UTC__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_UTC__c</fullName>
    <description>QCC: The scheduled arrival time in UTC format</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Arrival UTC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Actual_Departure_UTC__c.field-meta.xml
<CustomField>
    <fullName>Actual_Departure_UTC__c</fullName>
    <description>QCC: Used to capture the actual departure date/time in UTC format</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Departure UTC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ActualArriDateTime__c.field-meta.xml
<CustomField>
    <fullName>ActualArriDateTime__c</fullName>
    <description>QCC: actual arrival date/time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Arrival Date/Time</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ActualDepaDateTime__c.field-meta.xml
<CustomField>
    <fullName>ActualDepaDateTime__c</fullName>
    <description>QCC: actual departure date/time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Departure Date/Time</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/AirplaneType__c.field-meta.xml
<CustomField>
    <fullName>AirplaneType__c</fullName>
    <description>QCC: type of the airplane</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Aircraft Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ArrivalPort__c.field-meta.xml
<CustomField>
    <fullName>ArrivalPort__c</fullName>
    <description>QCC: arrival port of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/DelayFailureCode__c.field-meta.xml
<CustomField>
    <fullName>DelayFailureCode__c</fullName>
    <description>QCC: specific delay categories of the disruption(s).</description>
    <label>Delay Failure Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air Turn Back</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Mechanical</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Medical</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Other</fullName>
            </value>
            <value>
                <fullName>Diversion Due to Weather</fullName>
            </value>
            <value>
                <fullName>Flight Cancellation</fullName>
            </value>
            <value>
                <fullName>Flight Delay</fullName>
            </value>
            <value>
                <fullName>Add Stop</fullName>
            </value>
            <value>
                <fullName>Heads Up</fullName>
            </value>
            <value>
                <fullName>Flight Delay Greater than 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Greater than 20 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay Less between 5 and 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Less between 5 and 20 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay Less than 5 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay Less than 5 Hours</label>
            </value>
            <value>
                <fullName>Flight Delay between 5 and 20 Hours</fullName>
                <isActive>false</isActive>
                <label>Flight Delay between 5 and 20 Hours</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/DeparturePort__c.field-meta.xml
<CustomField>
    <fullName>DeparturePort__c</fullName>
    <description>QCC: departure port of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Diverted_Port__c.field-meta.xml
<CustomField>
    <fullName>Diverted_Port__c</fullName>
    <description>QCC: Diverted Port information.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Diverted Port</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Estimated_Arrival_UTC__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Arrival_UTC__c</fullName>
    <description>QCC: Used to capture the estimated arrival time in UTC Format</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Estimated Arrival UTC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Estimated_Departure_UTC__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Departure_UTC__c</fullName>
    <description>QCC: Used to capture the estimated Departure time in UTC Format</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Estimated Departure UTC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EstimatedArrDateTime__c.field-meta.xml
<CustomField>
    <fullName>EstimatedArrDateTime__c</fullName>
    <description>QCC: Estimated arrival date/time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Estimated Arrival Date/Time</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EstimatedDepDateTime__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDepDateTime__c</fullName>
    <description>QCC: Estimated departure date/time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Estimated Departure Date/Time</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Flight_Info_Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Flight_Info_Update_Status__c</fullName>
    <description>Store the status of updating flight info for Event.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Info Update Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Flight_Number_Changed__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Indicates whether flight number changed or not</description>
    <label>Flight Number Changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Flight_Status__c.field-meta.xml
<CustomField>
    <fullName>Flight_Status__c</fullName>
    <description>QCC: Status of the flight</description>
    <label>Flight Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOARDING-OPEN</fullName>
            </value>
            <value>
                <fullName>BOARDING</fullName>
            </value>
            <value>
                <fullName>BOARDING-FINAL-CALL</fullName>
            </value>
            <value>
                <fullName>BOARDING-CLOSE</fullName>
            </value>
            <value>
                <fullName>DEPARTED</fullName>
            </value>
            <value>
                <fullName>LANDED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>ESTIMATED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <description>QCC: the flight number affected</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/IsEventReopened__c.field-meta.xml
<CustomField>
    <fullName>IsEventReopened__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsEventReopened</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Operating_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operating_Carrier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Operating Carrier</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Operational_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Operational_Carrier__c</fullName>
    <description>QCC: Identifies the Flight Operator</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Operational Carrier</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Plane_Number__c.field-meta.xml
<CustomField>
    <fullName>Plane_Number__c</fullName>
    <description>QCC: Identifies the unique Flight Number(Tail Number)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Aircraft Registration</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Scheduled_Arrival_UTC__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Arrival_UTC__c</fullName>
    <description>QCC: Used to capture the scheduled arrival date/time in UTC format</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Arrival UTC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Scheduled_Depature_UTC__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Depature_UTC__c</fullName>
    <description>QCC: The scheduled Departure time in UTC format</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure UTC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledArrDateTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledArrDateTime__c</fullName>
    <description>QCC: scheduled arrival date and time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Arrival Date/Time</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepDate__c</fullName>
    <description>QCC: scheduled departure date of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/ScheduledDepTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledDepTime__c</fullName>
    <description>QCC: scheduled departure time of the flight</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Departure Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/TECH_FlightAPIInvoked__c.field-meta.xml
<CustomField>
    <fullName>TECH_FlightAPIInvoked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>QCC: Once the Flight API is Invoked it will be set to true</description>
    <label>FlightAPIInvoked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/updateCheckForDelayTime__c.field-meta.xml
<CustomField>
    <fullName>updateCheckForDelayTime__c</fullName>
    <defaultValue>false</defaultValue>
    <label>updateCheckForDelayTime</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QCC_AutoEventFlightInfoUpdateHelper.cls
/********************************************************************************************************************************

Description: Flight events Autorefresh Functionality
History:
======================================================================================================================
Name                    Jira                Description                                                 Tag
======================================================================================================================
Bharathkumar Narayanan  CRM-3913    Flight Event Autorefresh Functionality                                T01
                                    
Created Date    : 15/10/19 (DD/MM/YYYY)

**********************************************************************************************************************************/

public class QCC_AutoEventFlightInfoUpdateHelper {
    @AuraEnabled
    public static String submitUpdateforEvent(String eventId){
        List<id> listIds = new List<Id>();
        listIds.add(eventId);
        return QCC_AutoEventFlightInfoUpdateHelper.updateforEvent(listIds);
    }

      
    /*--------------------------------------------------------------------------------------       
    Method Name:        updateforEvent
    Description:        Call to Flight Schedule API single sector flights
    Parameter:          Event listIds
    --------------------------------------------------------------------------------------*/  
   public static String updateforEvent(List<Id> listIds){
        String output = '';
        Boolean isException = false;
        Boolean checkUpdate = false;
        List<Event__c> events = [Select id, name, ScheduledDepDate__c,Flight_Number_Changed__c, DeparturePort__c, FlightNumber__c, AirplaneType__c, Plane_Number__c,
                            ScheduledArrDateTime__c,ActualDepaDateTime__c, ActualArriDateTime__c, Scheduled_Arrival_UTC__c, Estimated_Arrival_UTC__c,
                            Actual_Arrival_UTC__c, Scheduled_Depature_UTC__c, Estimated_Departure_UTC__c, Actual_Departure_UTC__c, DelayFailureCode__c,
                            Operating_Carrier__c, EstimatedDepDateTime__c, 
                            ArrivalPort__c, Operational_Carrier__c, ScheduledDepTime__c, Flight_Info_Update_Status__c,
                            IsEventReopened__c, TECH_FlightAPIInvoked__c, Diverted_Port__c,updateCheckForDelayTime__c
                            FROM Event__c 
                            WHERE Id IN :listIds];
        try{
            //create request for getting flight info
            flightRequest fr = new flightRequest();
            List<String> lstAddStopIds = new List<String>();

            for(event__c ev:events){
                
                //adding logic for Add Stop flight
                if(ev.DelayFailureCode__c == 'Add Stop'){
                    lstAddStopIds.add(ev.id);
                    continue;
                }
                
                if(fr.departureDate== null || fr.departureDate== ''){
                    if(ev.ScheduledDepDate__c != null){
                        String formatStr = Datetime.newInstance(ev.ScheduledDepDate__c, Time.newInstance(0,0,0,0)).format('yyyy-MM-dd');
                        fr.departureDate = formatStr;
                    }
                }
                if(fr.departurePort== null || fr.departurePort== ''){
                    if(!String.isBlank(ev.DeparturePort__c)){
                        fr.departurePort = ev.DeparturePort__c;
                    }
                }
                if(fr.arrivalPort== null || fr.arrivalPort== ''){
                    if(!String.isBlank(ev.ArrivalPort__c)){
                        fr.arrivalPort = ev.ArrivalPort__c;
                    }
                }
                if(fr.flightNo== null || fr.flightNo== ''){
                    if(!String.isBlank(ev.FlightNumber__c)){
                        String fightNumber = ev.FlightNumber__c;
                        //remove the prefix if needed (Usually 2 characters QF)
                        while(!GenericUtils.checkisNumeric(fightNumber)){
                            fightNumber = fightNumber.substring(1);
                        }
    
                        fr.flightNo = fightNumber;
                    }
                } 
                if(fr.carrier== null || fr.carrier== ''){
                    if(!String.isBlank(ev.FlightNumber__c)){
                        String carrier = ev.FlightNumber__c;  
                        fr.carrier = carrier.substring(0,2);
                    }
                }       
            }
            
            //adding logic for Add Stop flight
            if(lstAddStopIds.size() > 0){
                //switch to Multi Sector Flight flow
                system.debug('invoke multi Secotr Flight: ');        
                QCC_MultiSectorFlightUpdateQueuable getMultiSectorFlightDetailJob = new QCC_MultiSectorFlightUpdateQueuable(lstAddStopIds);
                ID jobID = System.enqueueJob(getMultiSectorFlightDetailJob);
            }

            //calling to Flight schedule api to get departure time and arrival time
            if(!String.isBlank(fr.departureDate) && !String.isBlank(fr.departurePort) && !String.isBlank(fr.flightNo)){
                QCC_FlightInfoResponse fir = QCC_InvokeCAPAPI.invokeFlightInfoAPI(fr.departureDate, fr.departurePort, fr.flightNo, fr.arrivalPort, fr.carrier);
                System.debug(LoggingLevel.ERROR, fir);
                if(fir != null && fir.flights != null && fir.flights.size()>0){
                    for(QCC_FlightInfoResponse.flight singleFlight :  fir.flights){
                        for(event__c ev:events){
                            //update Flight Info for Event
                            
                            //delayDuration use for Primary root delay cause
                            Integer delayDuration = 0;
                            if(ev.FlightNumber__c.contains(singleFlight.marketingFlightNo)){
                                System.debug(LoggingLevel.ERROR, singleFlight);
                                ev.AirplaneType__c = (singleFlight.equipmentTypeCode != null ? singleFlight.equipmentTypeCode : '') + (singleFlight.equipmentSubTypeCode != null ? ('-' + singleFlight.equipmentSubTypeCode) : '');
                                ev.Plane_Number__c = singleFlight.equipmentTailNumber != null ? singleFlight.equipmentTailNumber : '';                
                                ev.Flight_Status__c = singleFlight.flightStatus != null ? singleFlight.flightStatus : '';  
                                ev.Operational_Carrier__c = singleFlight.marketingCarrier != null ? singleFlight.marketingCarrier : ''; 

                                ev.Scheduled_Arrival_UTC__c = ev.Flight_Number_Changed__c != true?GenericUtils.parseStringToGMT(singleFlight.scheduledArrivalUTCTimeStamp):ev.Scheduled_Arrival_UTC__c;
                                ev.Estimated_Arrival_UTC__c = GenericUtils.parseStringToGMT(singleFlight.estimatedArrivalUTCTimeStamp);
                                ev.Actual_Arrival_UTC__c = GenericUtils.parseStringToGMT(singleFlight.actualArrivalUTCTimeStamp);
                                ev.Scheduled_Depature_UTC__c = GenericUtils.parseStringToGMT(singleFlight.scheduledDepartureUTCTimeStamp);
                                ev.Estimated_Departure_UTC__c = GenericUtils.parseStringToGMT(singleFlight.estimatedDepartureUTCTimeStamp);
                                ev.Actual_Departure_UTC__c = GenericUtils.parseStringToGMT(singleFlight.actualDepartureUTCTimeStamp);

                                ev.ScheduledArrDateTime__c = ev.Flight_Number_Changed__c != true?singleFlight.scheduledArrivalLocalTimeStamp:ev.ScheduledArrDateTime__c;
                                ev.ActualDepaDateTime__c = singleFlight.actualDepartureLocalTimeStamp;
                                ev.ActualArriDateTime__c = singleFlight.actualArrivalLocalTimeStamp;
                                ev.EstimatedArrDateTime__c = singleFlight.estimatedArrivalLocalTimeStamp;
                                ev.EstimatedDepDateTime__c = singleFlight.estimatedDepartureLocalTimeStamp;
                                if(!String.isBlank(singleFlight.scheduledDepartureLocalTimeStamp)){
                                    ev.ScheduledDepTime__c =  singleFlight.scheduledDepartureLocalTimeStamp.substring(11,16); 
                                }

                                //update Diverted Port
                                System.debug(LoggingLevel.ERROR, singleFlight.airDiversion);
                                if(singleFlight.airDiversion != null 
                                        && singleFlight.airDiversion.unScheduledArrivalAirport != null){
                                    ev.Diverted_Port__c = singleFlight.airDiversion.unScheduledArrivalAirport;
                                }

                                ev.Flight_Info_Update_Status__c = '';
                                //turn off isOpen in order to auto close
                                ev.IsEventReopened__c = false;

                                //assign root cause
                                if(singleFlight.delay != null && singleFlight.delay.size() > 0){
                                    for(QCC_FlightInfoResponse.Delay delayReason : singleFlight.delay){
                                        if(delayDuration <= QCC_GenericUtils.stringToInteger(delayReason.delayDuration)){
                                            delayDuration = QCC_GenericUtils.stringToInteger(delayReason.delayDuration);
                                            ev.Primary_Root_Cause__c = QCC_GenericUtils.getDelayReason(delayReason.reasonCode , delayReason.shortDescription);
                                        }
                                    }
                                }
                            }
                            //Add to stop invoking mutiple times and sequence the Passenger API invoke
                            ev.TECH_FlightAPIInvoked__c = true;
                            System.debug('ev.updateCheckForDelayTime__c'+ev.updateCheckForDelayTime__c);
                            checkUpdate = ev.updateCheckForDelayTime__c;
                            
                        }
                    }
                    system.debug('events##########'+events);  
                    system.debug('events checkUpdate##########'+checkUpdate);  
                    if(!checkUpdate){                           
                                            system.debug('events checkUpdate##########111111111'+checkUpdate);  
                        update events;                         
                    }
                    
                    
                    //output = 'Success: flight info updated';
                }else if(fir != null && fir.errorMessage != null && fir.errorMessage.equals('404-=-Not Found')){
                    //switch to Multi Sector Flight flow
                    system.debug('invoke multi Secotr Flight: ');        
                    QCC_MultiSectorFlightUpdateQueuable getMultiSectorFlightDetailJob = new QCC_MultiSectorFlightUpdateQueuable(listIds);
                    ID jobID = System.enqueueJob(getMultiSectorFlightDetailJob);
                }else if(fir != null && fir.errorMessage != null){
                    //Stop updating Flight Info if the Departure Info is not retrieved      
                    output = 'Flight schedule is not found';
                    for(event__c ev:events){
                        ev.Flight_Info_Update_Status__c = output;
                        //Add to stop invoking mutiple times and sequence the Passenger API invoke
                        ev.TECH_FlightAPIInvoked__c = true;
                    }
                    if(!checkUpdate){ 
                         system.debug('events checkUpdate##########22222222'+checkUpdate);  
                    update events;
                   }
                }
            }

        }catch(exception ex){
            isException = true;
            System.debug(LoggingLevel.ERROR, ex.getMessage());
            System.debug(LoggingLevel.ERROR, ex.getStackTraceString());
            
            CreateLogs.insertLogRec( 'Log Exception Logs Rec Type', 'Event', 'QCC_AutoEventFlightInfoUpdateHelper', 
                                    'updateforEvent', String.valueOf(''), String.valueOf(''),false,'', ex);

            output = 'Error: '+ ex.getMessage();
        }finally{
            if(isException){
                for(Event__c ev: events){
                    if( ev.TECH_FlightAPIInvoked__c != true){
                        ev.TECH_FlightAPIInvoked__c = true;
                    }
                }
                if(!checkUpdate){  
                update events;
                }
            }
        }       
        
        return output;
    }
    
    
    public class flightRequest{
        public String departureDate{get;set;}
        public String departurePort{get;set;}
        public String arrivalPort{get;set;}
        public String flightNo{get;set;}
        public String carrier{get;set;}
        public flightRequest(){
            departurePort = '';
            departureDate = '';
            arrivalPort = '';
            flightNo = '';
            carrier = '';
        }
    }

    public class flightStatusRequest{
        public String departureFrom{get;set;}
        public String departureTo{get;set;}
        public String flightNo{get;set;}
        public flightStatusRequest(){
            departureFrom = '';
            departureTo = '';
            flightNo = '';
        }
    }
}