force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>QCC: Captures and tracks service disruption(s) for a particular flight on a particular schedule. e.g. Delay, Cancellation, Diversion, IFE, Food(Cathering), etc</description>
    <label>Flight Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Affected_Ports__c.field-meta.xml
<CustomField>
    <fullName>Affected_Ports__c</fullName>
    <description>QCC: Ports affected by this event</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Affected Ports</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>QCC: detailed description of the Event</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>QCC: Indicates when the global event was marked as resolved</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Global_Event_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Global_Event_Sub_Type__c</fullName>
    <label>Global Event Sub Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Global_Event_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adverse Weather</fullName>
            </value>
            <value>
                <fullName>Baggage</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Cyclone</fullName>
            </value>
            <value>
                <fullName>Fog</fullName>
            </value>
            <value>
                <fullName>High Winds</fullName>
            </value>
            <value>
                <fullName>Hurricane</fullName>
            </value>
            <value>
                <fullName>IFE – Full</fullName>
            </value>
            <value>
                <fullName>Lights</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Q-Entertainment</fullName>
            </value>
            <value>
                <fullName>Strike Action</fullName>
            </value>
            <value>
                <fullName>Thunderstorm Activity</fullName>
            </value>
            <value>
                <fullName>Toilets</fullName>
            </value>
            <value>
                <fullName>Volcano</fullName>
            </value>
            <value>
                <fullName>Wifi</fullName>
            </value>
            <value>
                <fullName>Baggage Belt</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Local_End_Time__c.field-meta.xml
<CustomField>
    <fullName>QCC_Local_End_Time__c</fullName>
    <description>End Time of the Global Heads Up flight event</description>
    <inlineHelpText>End Time of the Global Heads Up flight event</inlineHelpText>
    <label>Local End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/QCC_Local_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>QCC_Local_Start_Time__c</fullName>
    <description>Start Time of the Global Heads Up flight event</description>
    <inlineHelpText>Start Time of the Global Heads Up flight event</inlineHelpText>
    <label>Local Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>QCC: Indicates when the event was first noted</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object will store all the errors and exceptions arising out of the application</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QCC_CreateTaskForGlobalHeadsUpInvocable.cls
/*********************************************************************************
Name         : QCC_CreateTaskForGlobalHeadsUpInvocable
Created By   : Raymart Airon Tolentino
Company Name : Accenture
Project      : Pre-Travel, GRAPHITE
Created Date : 30 September 2019
Usages       : This class is used to create task record for every user that is part of QANTAS VIP Service Team public group.
*********************************************************************************/
public class QCC_CreateTaskForGlobalHeadsUpInvocable {
    //@Purpose: This method execute the whole logic to create task record.
    //@input parameters:
    //	1. flightEventRecords - The list of flight event records that will come from the process builder.
    //@return type: None
    @InvocableMethod
    public static void execute(List<Event__c> flightEventRecords) {
        try {
            List<Id> flightEventIds = new List<Id>();
            for(Event__c flightEventRecord : flightEventRecords) {
                flightEventIds.add(flightEventRecord.Id);
            }
            System.debug('flightEventIds: ' + flightEventIds);

            //Get all flight event record information necessary for create task notification.
            List<Event__c> newFlightEventRecords = [
                SELECT Id, Affected_Ports__c, Start_Date__c, End_Date__c, QCC_Local_Start_Time__c,
                QCC_Local_End_Time__c, Global_Event_Sub_Type__c, Comments__c, OwnerId
                FROM Event__c
                WHERE Id IN: flightEventIds
            ];
            System.debug('newFlightEventRecords: ' + newFlightEventRecords);

            List<Task> taskToBeCreatedList = new List<Task>();

            //Get all user id which is part of QANTAS VIP Service Team public group and QF-QDC-OM-VIP-TL role.
            List<Id> groupMemberIds = new List<Id>();
            groupMemberIds.addAll(QCC_UtilityHelper.getAllUserFromPublicGroup('QANTAS VIP Service Team'));

            System.debug('groupMemberIds: ' + groupMemberIds);

            List<Group> groupRecords = [SELECT Id, RelatedId, Type FROM Group WHERE Id IN: groupMemberIds];
            List<Id> roleIds = new List<Id>();
            List<Id> roleWithSubordinateIds = new List<Id>();
            for(Group groupRecord : groupRecords) {
                if (groupRecord.Type == 'Role') {
                    roleIds.add(groupRecord.RelatedId);
                } else if (groupRecord.Type == 'RoleAndSubordinates' || groupRecord.Type == 'roleAndSubordinatesInternal') {
                    roleWithSubordinateIds.add(groupRecord.RelatedId);
                }
            }

            Set<User> userRecords = new Set<User>();

            //Get all user per User in Public Group
            userRecords.addAll(QCC_UtilityHelper.getAllUserByIds(groupMemberIds));

            //Get all user per Role in Public Group
            userRecords.addAll(QCC_UtilityHelper.getAllUserByUserRoleIds(roleIds));

            //Get all user per RoleAndSubordinates in Public Group
            List<Id> finalRoleWithSubordinateIds = new List<Id>();
            Map<Id, List<UserRole>> userRoleHierarchyMap = QCC_UtilityHelper.getUserRoleHierarchyMap();
            System.debug('userRoleHierarchyMap: ' + userRoleHierarchyMap);
            for(Id roleWithSubordinateId : roleWithSubordinateIds) {
                finalRoleWithSubordinateIds.addAll(QCC_UtilityHelper.getSubHierarchyRoleIds(roleWithSubordinateId, userRoleHierarchyMap));
            }

            System.debug('finalRoleWithSubordinateIds: ' + finalRoleWithSubordinateIds);

            userRecords.addAll(QCC_UtilityHelper.getAllUserByUserRoleIds(finalRoleWithSubordinateIds));

            System.debug('userRecords: ' + userRecords);

            for(Event__c newFlightEventRecord : newFlightEventRecords) {
                DateTime currentDate = System.now();
                DateTime startDate = DateTime.valueOf(String.valueOf(newFlightEventRecord.Start_Date__c) + ' ' + String.valueOf(newFlightEventRecord.QCC_Local_Start_Time__c));
                DateTime endDate = DateTime.valueOf(String.valueOf(newFlightEventRecord.End_Date__c) + ' ' + String.valueOf(newFlightEventRecord.QCC_Local_End_Time__c));

                //Check if end Date time is later than current date time. Create task if later.
                if (endDate >= currentDate) {
                    String notificationMessage = 'A Global Heads Up has been created for <Affected Port> between <Start Time> and <End Time>. The reason for this Heads Up is <Sub-Type>. Comments have been added: <Comments>';
                    notificationMessage = notificationMessage.replace('<Affected Port>', newFlightEventRecord.Affected_Ports__c);
                    notificationMessage = notificationMessage.replace('<Start Time>', startDate.format('dd/MM/y HH:mm'));
                    notificationMessage = notificationMessage.replace('<End Time>', endDate.format('dd/MM/y HH:mm'));
                    notificationMessage = notificationMessage.replace('<Sub-Type>', newFlightEventRecord.Global_Event_Sub_Type__c);

                    if (newFlightEventRecord.Comments__c != null) {
                        notificationMessage = notificationMessage.replace('<Comments>', newFlightEventRecord.Comments__c);
                    } else {
                        notificationMessage = notificationMessage.replace('<Comments>', 'None');
                    }

                    //Create task for every user
                    for(User userRecord : userRecords) {
                        Task newTaskRecord = new Task();
                        newTaskRecord.OwnerId = userRecord.Id;
                        newTaskRecord.Subject = notificationMessage;
                        newTaskRecord.WhatId = newFlightEventRecord.Id;
                        newTaskRecord.Status = 'Not Started';
                        newTaskRecord.Priority = 'High';
                        newTaskRecord.IsReminderSet = true;
                        newTaskRecord.ReminderDateTime = startDate;

                        taskToBeCreatedList.add(newTaskRecord);
                    }
                }
            }

            System.debug('taskToBeCreatedList: ' + taskToBeCreatedList);
            if(!taskToBeCreatedList.isEmpty()) {
                insert taskToBeCreatedList;
            }
        } catch(Exception ex) {
            Log__c logRecord = QCC_LogUtilityHelper.generateLogRecord('QCC - Create Task For Global Heads Up', 'QCC_CreateTaskForGlobalHeadsUpInvocable', 'execute', '', '', false, '', ex, '');
            QCC_LogUtilityHelper.createLogRecord(logRecord);
        }
    }
}